### ISSUE TITLE
Passenger 4 disastrous performance issue

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1058]
_From [kochka](https://code.google.com/u/107328056656763629508/) on October 03, 2013 19:25:38_

What version of Phusion Passenger are you using? Which version of Rails? On what operating system? Passenger 4.0.19
Rails 3.2.14
Ruby 1.9.3
Debian 7.1 Please provide any additional information below. We have tried to migrate one server of our cluster from passenger 3.0.19 to 4.0.19 and we have experimented atrocious performances.
The performance difference between a server running 3 version and the one running 4 is shown on attached picture.
The performances seems to getting worse with time.
We have also tried Ruby 2 with same consequences.

We have currently no lead to explain this issue.

Here the passenger config used in both cases :
passenger_user_switching off;
passenger_default_user www-data;
passenger_max_pool_size 125;
passenger_pool_idle_time 0;
passenger_max_instances_per_app 120;
rails_app_spawner_idle_time 0;

**Attachment:** [passenger4.png](http://code.google.com/p/phusion-passenger/issues/detail?id=959)

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=959_

**Comment by OnixGH** [comment]
@kochka it's getting to be a pretty old issue, are you still on Passenger, and did you try it on 5? That version has a lot more builtin diagnostics for these kinds of issues, as well as a lot of rewritten code that make it faster and more robust.

**Comment by kochka** [comment]
Sorry but we never tried Passenger 5 against this project.
We never have been able to make it work with Passenger 4 so we have switched to Unicorn at this time.

**Comment by OnixGH** [comment]
OK, thanks for the reply!
