### ISSUE TITLE
Server instance dir might not be reused correctly on Apache graceful reload

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1060]
_From [honglilai](https://code.google.com/u/honglilai@gmail.com/) on October 08, 2013 00:25:27_

See http://stackoverflow.com/questions/19223676/phusion-passenger-crash It appears a graceful reload happened, and then Phusion Passenger failed to reinitialize. This should be investigated.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=961_

**Comment by OnixGH** [comment]
Unable to reproduce, please reopen if you encounter this issue and can provide us with extra information.
