### ISSUE TITLE
Upon restarting, already spawning processes should be aborted

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1100]
_From [honglilai](https://code.google.com/u/honglilai@gmail.com/) on October 17, 2013 11:49:20_

If there is already a process being spawned at the time restart.txt is touched, then that process will survive the restart. As a result, a process belonging to the old deploy may stay alive even though a restart command was issued. This can be worked around by touching restart.txt again after some time, but that is problematic for users who have a lot of servers or a lot of traffic.

When restarting, the code should abort any already spawning processes.

This issue has been reported by an Enterprise customer.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1001_

**Comment by OnixGH** [comment]
Unable to reproduce, please reopen if you experience this issue and can provide us with extra information.
