### ISSUE TITLE
4.0.21.pre: FYI: libev on Solaris: special compile requirements to avoid crashing

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1102]
_From [mark@ibiblio.org](https://code.google.com/u/105216905314054538170/) on October 18, 2013 08:35:07_

What is the expected output? What do you see instead? Getting lots of crashes, i.e. it doesn't run:

[ 2013-10-17 16:45:31.4987 8744/1 agents/Watchdog/Main.cpp:677 ]: All Phusion Passenger agents started!
[Thu Oct 17 16:45:31.513785 2013] [mpm_event:notice] [pid 8710:tid 1] AH00489: Apache/2.4.3 (Unix) OpenSSL/0.9.8y Phusion_Passenger/4.0.20 configured -- res
uming normal operations
[Thu Oct 17 16:45:31.514428 2013] [core:notice] [pid 8710:tid 1] AH00094: Command line: '/usr/local/apache.httpd.2.4.3/bin/httpd -f /usr/local/etc/httpd.conf'
(libev) port_getn (see http://bugs.opensolaris.org/view_bug.do?bug_id=6268715 , try LIBEV_FLAGS=3 env variable): Timer expired
[ pid=8747, timestamp=1381988791 ] Process aborted! signo=SIGABRT(6), reason=#18446744073709551615, signal sent by PID 8747 with UID 0, si_addr=0x222a000000
00, randomSeed=1381988731
[ pid=8747 ] Crash log dumped to /var/tmp/passenger-crash-log.1381988791 What version of Phusion Passenger are you using? Which version of Rails? On what operating system? passenger-master @ commit_b05d76f9de43aa38b27def5d40b75d03ea95b2d6
Rails 4.0.0
Solaris 10 SPARC
Sun Studio 12.3 Please provide any additional information below. From http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#FUNCTIONS_CONTROLLING_EVENT_LOOPS SOLARIS PROBLEMS AND WORKAROUNDS
errno reentrancy

The default compile environment on Solaris is unfortunately so thread-unsafe that you can't even use components/libraries compiled without -D_REENTRANT in a threaded program, which, of course, isn't defined by default. A valid, if stupid, implementation choice.

If you want to use libev in threaded environments you have to make sure it's compiled with _REENTRANT defined.
Event port backend

The scalable event interface for Solaris is called "event ports". Unfortunately, this mechanism is very buggy in all major releases. If you run into high CPU usage, your program freezes or you get a large number of spurious wakeups, make sure you have all the relevant and latest kernel patches applied. No, I don't know which ones, but there are multiple ones to apply, and afterwards, event ports actually work great.

If you can't get it to work, you can try running the program by setting the environment variable LIBEV_FLAGS=3 to only allow poll and select backends.

Comment:
Since I'm using a more recent libev than ships in passenger, I'll now recompile it with the suggested settings above. This bug is logged as an FYI to feed the googleplex.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1003_

**Comment by OnixGH** [comment]
If this still occurs with Passenger 5, please post a new issue.
