### ISSUE TITLE
Determine PassengerRuby from application's .ruby-version file to remove repetition

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1111]
_From [stuart@throwspace.com](https://code.google.com/u/111055131005319243274/) on October 30, 2013 22:56:49_

It would be fantastic if Passenger would look within my app's .ruby-version text file, which contains the precise Ruby version string to use (a convention established in RVM and Rbenv). Currently in Passenger 4, I have to duplicate the path to my Ruby binary in two places:

1) in my app's .ruby-version file, which is used during local development, and
2) in the PassengerRuby directive of my Apache <VirtualHost> file, which is used by Passenger.

Duplicating the version in multiple places is undesirable since its easy to forget to change ever place it is set whenever we upgrade Ruby versions. So it would be nice if Passenger could dynamically detect which Ruby version to use by reading the .ruby-version file within my application root.

Perhaps a new directive could be added that informs Passenger to read this file and determine the path using RVM or Rbenv. For example, this could look like:

  # File path is relative to PassengerAppRoot
  PassengerRubyVersionFile .ruby-version

  # Colon-delimited list of directories in which to search for the Ruby version
  # specified by the contents of PassengerRubyVersionFile
  PassengerRubyVersionsPath /usr/local/rvm/wrappers:/usr/bin

The specific directive names and semantics are up for debate, this is just an example of how it could work. And presumably Nginx would have similar functionality.

For more details of how the .ruby-version file works, see:
- https://gist.github.com/fnichol/1912050 \* http://rvm.io/workflow/projects \* https://github.com/sstephenson/rbenv#choosing-the-ruby-version

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1012_

**Comment by scambra** [comment]
With rvm it works using rvm-auto-ruby,  I have this in config for apache2 module:
PassengerDefaultRuby /usr/local/rvm/bin/rvm-auto-ruby

**Comment by sandrinr** [comment]
If it is not about the principle of having the configuration directive to actually make Passenger aware of rbenv then it can already be solved today. We use rbenv and use the Apache configuration

```PassengerRuby /usr/local/rbenv/shims/ruby```

We of course ensure that at the specified location a rbenv environment is setup with the required version of Ruby.

**Comment by FooBarWidget** [comment]
Thanks for the tip @sandrinr. Since this is trivially solvable with a script, I'm closing this issue.
