### ISSUE TITLE
passenger-status --show=xml outputs non-XML parts

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1136]
_From [honglilai](https://code.google.com/u/honglilai@gmail.com/) on December 28, 2013 23:31:56_

This is the current output:

Version : 4.0.29
Date    : 2013-12-28 11:34:22 -0800
Instance: 44
<?xml version="1.0" encoding="iso8859-1"?>
<info>etc.</info>

The preface should go away.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1037_

**Comment by nkts** [comment]
# passenger-status --show=xml
Version : 5.0.6
Date    : 2015-04-09 12:11:16 +0000
Instance: gAJHxFZR (nginx/1.6.2 Phusion_Passenger/5.0.6)

<?xml version="1.0" encoding="iso8859-1"?>
<info version="3">
   <passenger_version>5.0.6</passenger_version>

**Comment by FooBarWidget** [comment]
@OnixGH Looks like a regression. Can you fix this for 5.0.7?

**Comment by OnixGH** [comment]
@nkts @FooBarWidget the script expects you to use --no-header to omit the xml header because it is otherwise shown by default. I changed this for 5.0.7 such that the default is not applied when --show=xml is used, to recreate the old behavior.
