### ISSUE TITLE
Seg fault with 4.0.30+ on OSX 10.8 / MacPorts Apache 

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1142]
_The Phusion Passenger authors cannot reproduce this issue. If you have found a way to reproduce it, please post details._

_From [ireuben](https://code.google.com/u/111950343924597893775/) on January 06, 2014 07:53:23_

**What steps will reproduce the problem?**

1. Install passenger gem 4.0.30 or 4.0.33
2. Run passenger-install-apache2-module
3. Restart apache
4. Make a request to the app

**What is the expected output? What do you see instead?**

Get a seg fault (attached).

**What version of Phusion Passenger are you using? Which version of Rails? On what operating system?**

Works fine with 4.0.29 gem (even ran passenger-install-apache2-module again using that to see if there was a compilation issue that was new).  I am using MacPorts for ruby and apache.  Very old (1.x) version of rails.

**Attachment:** [httpd_2014-01-05-222443_isaac.crash](http://code.google.com/p/phusion-passenger/issues/detail?id=1043)

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1043_

**Comment by OnixGH** [comment]
This issue is now outdated, if there are problems with Passenger 5 please open a new issue.
