### ISSUE TITLE
Add a hook for spawn failures

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1150]
_From [honglilai](https://code.google.com/u/honglilai@gmail.com/) on January 24, 2014 17:22:54_

An Enterprise customer requested a hook for spawn failures, so that he can get notified of spawn errors instead of having to parse the log file periodically.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1051_

**Comment by OnixGH** [comment]
Fixed in #1252
