### ISSUE TITLE
Concurrency issue with websocket and long polling requests blocking workers when hijacked using faye

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1187]
_From [bigbourin](https://code.google.com/u/105824566137332740947/) on May 16, 2014 13:04:18_

While testing faye ( http://faye.jcoglan.com/ ) on passenger we found a weird issue compared to other servers. Every connection seems to block a worker whereas they are hijacked by faye and should release the worker.

We tried with passenger entreprise also, in threaded mode, and the pattern is the same, each connection block one thread, which requires tons of thread to scale a bit, whereas a sever like thin or puma will accept thousands of open connections with 1 thread.

I made a repo with some explanation and a reproducible test case: https://github.com/dimelo/passenger-faye-issue To reproduce:

```
git clone https://github.com/dimelo/passenger-faye-issue.git cd passenger-faye-issue
bundle
bundle exec passenger start --max-pool-size 1
./test.rb
```

The expected output is:

```
$> ./test.rb
Connecting client 1 ... ok
Connecting client 2 ... ok
Connecting client 3 ... ok
Connecting client 4 ... ok
Connecting client 5 ... ok
Connecting client 6 ... ok
Connecting client 7 ... ok
etc...
```

**What do you see instead?**

`
$> ./test.rb
Connecting client 1 ...
`

**What version of Phusion Passenger are you using?**

Phusion Passenger 4.0.42
Ubuntu 12.04

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1088_

**Comment by uri** [comment]
What would the side effects be for setting ` PhusionPassenger.advertised_concurrency_level = 0`? We're using 4.0.x.

**Comment by OnixGH** [comment]
Autoscaling stops working. Passenger's load balancer is bypassed.
