### ISSUE TITLE
Allow some URLs to have unlimited concurrency

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1195]
_From [honglilai](https://code.google.com/u/honglilai@gmail.com/) on May 29, 2014 08:43:25_

Currently, an app's concurrency is solely determined by the app type and multithreading options. This is problematic for Ruby apps which usually have limited concurrency, except for WebSocket endpoints. There should be a way to allow some URLs to have unlimited concurrency.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1096_

**Comment by btucker** [comment]
Has there been any progress on this in light of 5.0's release?

**Comment by FooBarWidget** [comment]
It is on the roadmap, but no progress yet. We are currently focusing on high-priority bug fixes. For now, it is recommended that you use [this workaround](https://github.com/phusion/passenger/issues/1187#issuecomment-44814845).

**Comment by OnixGH** [comment]
With the new [force_max_concurrent_requests_per_process](https://www.phusionpassenger.com/library/config/reference/?a=passenger_force_max_concurrent_requests_per_process) option you can configure the concurrency limits, and also have them per URL by using application groups.

Example:
```
server {
   listen 80;
   server_name foo.com;
   root /webapps/foo/public;
   passenger_enabled on;

   # Use default concurrency for the app. But for the endpoint /special_websocket_endpoint,
   # force a different concurrency.
   location /special_websocket_endpoint {
       passenger_app_group_name foo_websocket;
       passenger_force_max_concurrent_requests_per_process 0;
   }
}
```

**Comment by jarthod** [comment]
Nice! Thanks. :beers:
