### ISSUE TITLE
When WebSockets are disabled in Meteor, and Meteor is bundled, browser keeps polling Meteor in an infinite loop

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1198]
Edit: The solution is to enable sticky sessions.

Given a Meteor app that's bundled and for which WebSockets are disabled, the browser seems to keep sending requests to Meteor in an infinite busy loop.

Consider the following virtual host on Nginx:

```
server {
    listen 8000;
    server_name meteor.dev;
    root /Users/hongli/Sites/leaderboard-bundle/bundle/public;
    passenger_app_type node;
    passenger_startup_file main.js;

    passenger_set_cgi_param MONGO_URL mongodb://localhost:27017/meteor;
    passenger_set_cgi_param ROOT_URL http://www.foo.com;
    passenger_set_cgi_param DISABLE_WEBSOCKETS 1;
    passenger_enabled on;
}
```

After visiting http://meteor.dev:8000/, the browser immediately makes thousands of requests.

This does not happen if Meteor is unbundled, or if WebSockets are enabled.

Original discussion: https://groups.google.com/forum/#!msg/phusion-passenger/3qtQThCIfPQ/tc2GBryJHN0J

**Comment by Joostvanderlaan** [comment]
This issue is reocurring when using Meteor on the phusion-docker image. phusion/passenger-nodejs:0.9.14
in Nginx config I have set     passenger_set_cgi_param DISABLE_WEBSOCKETS 1;
and I am getting:
xhr_send 404 (Not Found)

**Comment by FooBarWidget** [comment]
@Joostvanderlaan Did you enable sticky sessions? Sticky sessions are required when using long polling.

**Comment by Joostvanderlaan** [comment]
@FooBarWidget Yes I did, see:
```nginx
server {
    # listen 80;
    # server_name dockerbiproduction.fashionunited.com;
    listen 80 default_server;
    root /home/app/webapp;

    # The following deploys your Ruby/Python/Node.js/Meteor app on Passenger.

    # Not familiar with Passenger, and used (G)Unicorn/Thin/Puma/pure Node before?
    # Yes, this is all you need to deploy on Passenger! All the reverse proxying,
    # socket setup, process management, etc are all taken care automatically for
    # you! Learn more at https://www.phusionpassenger.com/.
    passenger_enabled on;
    passenger_user app;

    passenger_sticky_sessions on;
    passenger_set_cgi_param MONGO_URL mongodb://xxx;
    passenger_set_cgi_param MONGO_OPLOG_URL mongodb://xxx;
    passenger_set_cgi_param ROOT_URL http://localhost/i;
# Disabling websockets breaks the app due to passenger problem https://github.com/phusion/passenger/issues/1198
#    passenger_set_cgi_param DISABLE_WEBSOCKETS 1;

    # Set these ONLY if your app is a Meteor bundle!
    passenger_app_type node;
    passenger_startup_file webapp/bundle/main.js;
}
```

**Comment by mewm** [comment]
Did you resolve this? Still getting it per date.

**Comment by OnixGH** [comment]
@mewm What is your issue exactly, and which deployment of Passenger are you using (version, nginx/apache/standalone)?

**Comment by mewm** [comment]
I'm sorry, there is no issue. I didn't enable sticky sessions in my load balancer :P

**Comment by yeeking** [comment]
I just had this one in 2016... sticky sessions still fixes it.

**Comment by introspection3** [comment]
you should not use sockjs 

socket.io is better
