### ISSUE TITLE
Update documentation for Ruby WebSocket demos

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1208]
Upon releasing 4.0.47, update the documentation for:

* https://github.com/phusion/passenger-ruby-websocket-demo
* https://github.com/phusion/passenger-ruby-faye-websocket-demo

They should suggest enabling unlimited concurrency for WebSocket URLs.

**Comment by d-snp** [comment]
I've submitted a pull request to faye-ruby-websocket to enable this the faye-way. I will update the documentation when they pull it in.

**Comment by FooBarWidget** [comment]
All documentation updated.
