### ISSUE TITLE
Passenger will not bring up Rails 3.2 application - LoadError

### ISSUE THREAD

**Issue by HuckyDucky** [phusion/passenger#1229]
I'm using ruby1.9.3-p547 in an rbenv environment. I was not able to get Passenger 4 to work with RVM, as it insisted upon using site ruby on Mavericks. The behavior is better with rbenv, as it is using the correct Ruby. However, it appears unable to access the gems:

     cannot load such file -- bundler/setup (LoadError)

Still, it's farther than I have ever gotten on Passenger 4. I used Passenger 3 and 2 for years without the complications I'm now facing.

I have to run nginx as sudo, because I want it to use ports 80 and 443. Could that somehow be the issue?

Ans: No, that's not the problem. Same error on 8080 and 8443 without running as sudo.

**Comment by bsoule** [comment]
I just ran into this same issue with a fresh install of Passenger (v 5.0.8), and ruby 1.9.3. I got it working by setting GEM_HOME and GEM_PATH with passenger_env_var. I've only got one system ruby, and not using rvm or rbenv -- I just compiled and the ruby I wanted, so this seemed especially odd!
