### ISSUE TITLE
SIGABRT at random

### ISSUE THREAD

**Issue by DubitPlatform** [phusion/passenger#1242]
Seem to be getting the following error at random every 2-3 days, and this only seems to be happening on one server that appears to have an identical setup to the rest. It's fairly hard to replicate though so can't be certain :)

http://sprunge.us/MWIf

We're running Passenger standalone. It seems to be very similar to an issue I saw where it was crashing at `onAppInputChunkEnd`, but that issue was resolved.

**Comment by FooBarWidget** [comment]
It's been a long time since this issue has been open, and I haven't seen further complaints, either from the poster or from other users. So closing this issue. If you still have a problem please feel free to request a reopen.
