### ISSUE TITLE
Nginx sub uri deploy

### ISSUE THREAD

**Issue by Volox** [phusion/passenger#1256]
Hi,
first of all thanks for the great work, passenger is awesome!
I have a problem with the sub uri deployment of a node application. My configuration is the following:
```nginx
location ~ ^/cs-demo(/.*|$) {
    alias /opt/cs-demo/cs/public$1;  # <-- be sure to point to 'public'!
    passenger_base_uri /cs-demo;
    passenger_app_root /opt/cs-demo/cs;
    passenger_document_root /opt/cs-demo/cs/public;
    passenger_nodejs nodejs;
    passenger_app_type node;
    passenger_startup_file cs.js;
    passenger_enabled on;
}
```

But when i go to http://example.com/cs-demo in the log of my application i see:
```log
Requested "GET /cs-demo/manage" by 127.0.0.1
```
rather then
```log
Requested "GET /manage" by 127.0.0.1
```

Any idea on what i am missing?

**Comment by gziskind** [comment]
I was able to fix this by adding in a rewrite of 

rewrite ^/cs-demo/?(.*)$ /$1 break;

This makes it so it only passes the uri request after cs-demo down to the node app.

However this caused a problem when serving multiple node apps with the same rewrite rule under the same nginx/passenger instance. All traffic was routed to whichever node application was accessed first. Can't figure out how to get around this problem

**Comment by FooBarWidget** [comment]
I'm closing this issue because I think the answer to the original reporter, Volox, has been satisfactory.

gziskind's issue is handled separately in #1489.
