### ISSUE TITLE
Apps forked from preloaders should get their own stderr

### ISSUE THREAD

**Issue by x-yuri** [phusion/passenger#1266]
I'm running several `ruby` applications on `passenger` + `nginx`. And all the output goes to `nginx`'s `error.log`. So I'm trying to separate things.

Consider the following `sinatra` application:

```
require 'sinatra'
get '/' do
    $stdout.puts 's1'
    $stderr.puts 's2'
    'done'
end
```

And here's what goes to `error.log`:

```
[ 2014-08-21 18:05:29.7598 12335/7f229ebe8700 Pool2/Spawner.h:796 ]: [App 19539 stdout]
[ 2014-08-21 18:05:30.5976 12335/7f229ebe8700 Pool2/SmartSpawner.h:305 ]: Preloader for /srv/nginx/s1 started on PID 19539, listening on unix:/tmp/passenger.1.0.8422/generation-179/backends/preloader.19539
[ 2014-08-21 18:05:30.6464 12335/7f22a5e15700 Pool2/Implementation.cpp:1274 ]: [App 19915 stdout] s1
[ 2014-08-21 18:05:30.6464 12335/7f22a5f2a700 Pool2/Implementation.cpp:1274 ]: [App 19539 stderr] s2
[ 2014-08-21 18:05:30.6482 12335/7f22a5f2a700 Pool2/Implementation.cpp:1274 ]: [App 19539 stderr] 1.1.1.1 - - [21/Aug/2014 18:05:30] "GET /t1 " 200 4 0.0028
```

First, I thought that `Preloader` lines show that the `PID` for an application has changed:

```
... Preloader ... PID 1 ...
<only PID 1 lines here and lines of different applications>
... Preloader ... PID 2 ...
<only PID 2 lines here and lines of different applications>
```

It appears, older `PID`s might be used as well. And to top it off, writing to `stderr` gets marked with different `PID`. Can I safely separate output of different applications?

I'm running `debian 6`, `passenger-4.0.23`, `ruby-2.0.0` and `nginx-1.4.3`.

**Comment by FooBarWidget** [comment]
This is caused by the fact that processes forked from preloaders only get a new stdout, but not a new stderr. As a result, they share the stderr with their preloader process.

**Comment by x-yuri** [comment]
And what about the other issue? Is it expected, that after "Preloader..." line the old `PID` still appears in the log? I thought after this line, new app is started, and the old one terminates. Isn't it so?

**Comment by FooBarWidget** [comment]
Yes, due to the way it is implemented. The cause is as I said earlier. Some work needs to be done to cleanly separate this.

**Comment by FooBarWidget** [comment]
With Passenger 5.3 and the new SpawningKit, this issue has been solved.
