### ISSUE TITLE
Passenger 4.0.50 leaking MREGS, achieving 65k+ over just days

### ISSUE THREAD

**Issue by smadness** [phusion/passenger#1278]
There seems to be an egregious memory regions leak within Passenger 4.0.50, that is not apparent in 4.0.10 or possibly 4.0.19 (which we are testing currently)

There are not too many physical leaks (as reported with `leaks`), and heap doesn't look quite as bad, so I'm not sure where these are coming from, but maybe they are regions that are just not being cleaned up manually.

% sudo leaks 13851
Process:         PassengerHelperAgent [13851]
Path:            /Library/Ruby/Gems/1.8/gems/passenger-4.0.50/buildout/agents/PassengerHelperAgent
Load Address:    0x1094e9000
Identifier:      PassengerHelperAgent
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  PassengerWatchdog [13849]

Date/Time:       2014-09-09 14:04:23.736 -0700
OS Version:      Mac OS X 10.8.4 (12E55)
Report Version:  7

leaks Report Version:  2.0
Process 13851: 2977 nodes malloced for 1782 KB
Process 13851: 222 leaks for 12768 total leaked bytes.
...

% sudo heap 13851                                  
Process 13851: 1 zone
Zone DefaultMallocZone_0x109b8e000: Overall size: 38052KB; 2879 nodes malloced for 1732KB (4% of capacity); largest unused: [0x7f83da890400-7614KB]

Zone DefaultMallocZone_0x109b8e000: 2879 nodes - Sizes: 160KB[1] 64KB[1] 40KB[6] 32KB[1] 12KB[23] 11KB[2] 10KB[1] 8KB[58] 8KB[3] 4KB[2] 3584[3] 2560[1] 2048[50] 1536[52] 1024[9] 1008[2] 992[1] 880[1] 832[1] 720[3] 688[2] 656[1] 608[2] 592[26] 576[1] 560[1] 528[1] 512[30] 480[1] 448[3] 432[1] 416[12] 400[27] 384[3] 352[1] 304[2] 288[12] 272[2] 256[28] 240[60] 208[3] 192[3] 160[6] 144[1] 128[40] 112[17] 96[26] 80[55] 64[327] 48[1363] 32[424] 16[177] 

Found 42 ObjC classes in process 13851
Can't get the CFTypes for process 13851

-----------------------------------------------------------------------
Zone DefaultMallocZone_0x109b8e000: 2878 nodes (1772912 bytes) 

    COUNT     BYTES       AVG   CLASS_NAME                                       TYPE    BINARY
    =====     =====       ===   ==========                                       ====    ======
     2488   1168976     469.8   non-object                                                                 
       79      3792      48.0   boost::detail::sp_counted_impl_pd<Passenger::FileDescriptor::SharedData*, boost::detail::sp_ms_deleter<Passenger::FileDescriptor::SharedData> >  C++     PassengerHelperAgent
       58    504832    8704.0   boost::detail::sp_counted_impl_pd<Passenger::EventedBufferedInput<8192ul>*, boost::detail::sp_ms_deleter<Passenger::EventedBufferedInput<8192ul> > >  C++     PassengerHelperAgent
       58     13920     240.0   boost::detail::sp_counted_impl_pd<Passenger::FileBackedPipe*, boost::detail::sp_ms_deleter<Passenger::FileBackedPipe> >  C++     PassengerHelperAgent
       29     44544    1536.0   boost::detail::sp_counted_impl_pd<Passenger::Client*, boost::detail::sp_ms_deleter<Passenger::Client> >  C++     PassengerHelperAgent
       27       864      32.0   boost::detail::sp_counted_impl_p<oxt::thread_local_context>  C++     PassengerHelperAgent
       26     15392     592.0   boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(boost::function<void ()>, boost::shared_ptr<oxt::thread_local_context>), boost::_bi::list2<boost::_bi::value<boost::function<void ()> >, boost::_bi::value<boost::shared_ptr<oxt::thread_local_context> > > > >  C++     PassengerHelperAgent
       26       832      32.0   boost::detail::sp_counted_impl_p<boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(boost::function<void ()>, boost::shared_ptr<oxt::thread_local_context>), boost::_bi::list2<boost::_bi::value<boost::function<void ()> >, boost::_bi::value<boost::shared_ptr<oxt::thread_local_context> > > > > >  C++     PassengerHelperAgent
       19      4864     256.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::PipeWatcher*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::PipeWatcher> >  C++     PassengerHelperAgent
       11      4576     416.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::Process*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::Process> >  C++     PassengerHelperAgent
       11       704      64.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::SocketList*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::SocketList> >  C++     PassengerHelperAgent
        3        96      32.0   boost::detail::sp_counted_impl_pd<char*, boost::checked_array_deleter<char> >  C++     PassengerHelperAgent
        2       608     304.0   boost::detail::sp_counted_impl_pd<Passenger::SafeLibev*, boost::detail::sp_ms_deleter<Passenger::SafeLibev> >  C++     PassengerHelperAgent
        2       416     208.0   boost::detail::sp_counted_impl_pd<Passenger::CachedFileStat::Entry*, boost::detail::sp_ms_deleter<Passenger::CachedFileStat::Entry> >  C++     PassengerHelperAgent
        2       240     120.0   OS_xpc_pipe                                      ObjC    libxpc.dylib      
        2       160      80.0   OS_xpc_string                                    ObjC    libxpc.dylib      
        2        64      32.0   boost::detail::sp_counted_impl_p<Passenger::Account>  C++     PassengerHelperAgent
        2        64      32.0   boost::detail::sp_counted_impl_p<oxt::dynamic_thread_group::thread_handle>  C++     PassengerHelperAgent
        2        64      32.0   boost::detail::sp_counted_impl_p<oxt::thread>    C++     PassengerHelperAgent
        1      2048    2048.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::Group*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::Group> >  C++     PassengerHelperAgent
        1      1536    1536.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::SmartSpawner*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::SmartSpawner> >  C++     PassengerHelperAgent
        1       880     880.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::SuperGroup*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::SuperGroup> >  C++     PassengerHelperAgent
        1       656     656.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::Pool*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::Pool> >  C++     PassengerHelperAgent
        1       432     432.0   boost::detail::sp_counted_impl_pd<Passenger::RequestHandler*, boost::detail::sp_ms_deleter<Passenger::RequestHandler> >  C++     PassengerHelperAgent
        1       272     272.0   boost::detail::sp_counted_impl_pd<Passenger::AgentOptions*, boost::detail::sp_ms_deleter<Passenger::AgentOptions> >  C++     PassengerHelperAgent
        1       240     240.0   OS_xpc_dictionary                                ObjC    libxpc.dylib      
        1       208     208.0   boost::detail::sp_counted_impl_pd<Passenger::UnionStation::Core*, boost::detail::sp_ms_deleter<Passenger::UnionStation::Core> >  C++     PassengerHelperAgent
        1       192     192.0   boost::detail::sp_counted_impl_pd<Passenger::MessageServer*, boost::detail::sp_ms_deleter<Passenger::MessageServer> >  C++     PassengerHelperAgent
        1       160     160.0   OS_dispatch_queue                                ObjC    libdispatch.dylib 
        1       160     160.0   boost::detail::sp_counted_impl_pd<Passenger::AccountsDatabase*, boost::detail::sp_ms_deleter<Passenger::AccountsDatabase> >  C++     PassengerHelperAgent
        1       160     160.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::SpawnerConfig*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::SpawnerConfig> >  C++     PassengerHelperAgent
        1       160     160.0   boost::detail::sp_counted_impl_pd<Passenger::ApplicationPool2::SpawnerFactory*, boost::detail::sp_ms_deleter<Passenger::ApplicationPool2::SpawnerFactory> >  C++     PassengerHelperAgent
        1       128     128.0   OS_xpc_domain                                    ObjC    libxpc.dylib      
        1       112     112.0   boost::detail::sp_counted_impl_pd<Passenger::UnionStation::Transaction*, boost::detail::sp_ms_deleter<Passenger::UnionStation::Transaction> >  C++     PassengerHelperAgent
        1        80      80.0   boost::detail::sp_counted_impl_pd<RemoteController*, boost::detail::sp_ms_deleter<RemoteController> >  C++     PassengerHelperAgent
        1        64      64.0   boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_>  C++     PassengerHelperAgent
        1        64      64.0   boost::exception_detail::clone_impl<boost::exception_detail::bad_exception_>  C++     PassengerHelperAgent
        1        48      48.0   boost::detail::sp_counted_impl_pd<Passenger::RandomGenerator*, boost::detail::sp_ms_deleter<Passenger::RandomGenerator> >  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<ExitHandler>    C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<Passenger::FileChangeChecker::Entry>  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<Passenger::ServerInstanceDir::Generation>  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_alloc_> >  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<boost::exception_detail::clone_impl<boost::exception_detail::bad_exception_> >  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<boost::re_detail::basic_regex_implementation<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > >  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<boost::re_detail::cpp_regex_traits_implementation<char> >  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_p<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >  C++     PassengerHelperAgent
        1        32      32.0   boost::detail::sp_counted_impl_pd<unsigned int*, boost::checked_array_deleter<unsigned int> >  C++     PassengerHelperAgent
        1        16      16.0   ExitHandler                                      C++     PassengerHelperAgent

**Comment by OnixGH** [comment]
@smadness perhaps you could give Passenger 5 a try? We've run it through some detailed memory analysis in the process of solving leaks, and it's stable for us after that.
