### ISSUE TITLE
Per-application log files for Apache/Nginx integration mode

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1279]
Currently, all application stdout and stderr output is redirected to a single log file. Lately there seems to be more interest among users - in particular Node.js users - to have per-application log files.

We're considering adding this feature. If you'd like to see the feature too, please vote for it here. Note that we weight votes from Enterprise customers more heavily, so if you're an Enterprise customer please mention that here.

Edit: If working on this also see the (probably outdated) patch in #260.

**Comment by forkfork** [comment]
+1

**Comment by roy** [comment]
+1

**Comment by jmscholen** [comment]
+1

**Comment by saadtazi** [comment]
+1

**Comment by aletourneau** [comment]
+1

**Comment by numian** [comment]
+1

**Comment by Thesephi** [comment]
+1

**Comment by gokuu** [comment]
+1

**Comment by msva** [comment]
I'd also add +1, just to show how much that feature is wanted by community ;)

**Comment by msva** [comment]
btw, it will be also nice, if Passenger also handle tracebacks of the, say, python apps and log them in that file too, without the need to make custom logger :-/

**Comment by dylansm** [comment]
+1

**Comment by nukturnal** [comment]
+1

**Comment by tomdunning** [comment]
+1

**Comment by bgardella** [comment]
:+1:

**Comment by garysmi** [comment]
:+1:

**Comment by mz3** [comment]
:+1:

**Comment by pnicolai** [comment]
:+1:

**Comment by ylecuyer** [comment]
+1

**Comment by koenrh** [comment]
:+1:

**Comment by jewilmeer** [comment]
:+1:

**Comment by koenbollen** [comment]
+1

**Comment by wvdeutekom** [comment]
:+1: 

![Alt Text](http://media.giphy.com/media/xTiTnp5IsLPRspI0PS/giphy.gif)

**Comment by Dolphi2** [comment]
+1 
This is a very important feature. In a hosting environment it is not possible to let all users access the same common error log. Every application needs it's own log.

**Comment by muhammett** [comment]
+1

**Comment by Dolphi2** [comment]
Here is a script that lets a user on a shared server to view only his application's logs.
Name of the script passenger-log can be copied to /usr/local/bin
and then chmod 0755 to allow execution by all users.
It suits for a situation where the common log is /var/log/nginx/error_log (you can set the name of the common log file in the script)
`
#!/usr/bin/python

# Shows log lines of the running passenger instances (the stdout od the applications) for that user

import subprocess
import re
import sys
web_log='/var/log/nginx/error_log'
def get_passenger_pid(s):
        a=re.findall('PID\:\W+(\d+)\W+', i, re.MULTILINE)
        return a
# prints only the  nginx common log ilines with  App: pid
def grep_log(pid):
        print "Showing log for PID {}\n".format(pid)
        global web_log
        s_command="grep 'App " + pid + "' " + web_log
        lines=subprocess.check_output(s_command, shell=True)
        print lines
try:
        i=subprocess.check_output('passenger-status', stderr=subprocess.STDOUT)
except subprocess.CalledProcessError as details:
        print "The command shows the log of active processes. It seems that there are no active passenger processes for this web site."
        print "Send a request to the web site, to create an active process. Then try the command passenger-log again\n";
        sys.exit()

pids=get_passenger_pid(i)

# Itereate through the pids that were found in the passenger-status output
for pid in pids:
        grep_log(pid)

`

**Comment by Dolphi2** [comment]
Here is a script that lets a user on a shared server to view only his application's logs.
Name of the script passenger-log can be copied to /usr/local/bin
and then chmod 0755 to allow execution by all users.
User can execute the script using passenger-log and view the log of all his application instances.
It uses passenger-status to get the PID of user's applications and then searches for these PID in the common web server log.
It suits for a situation where the common log is /var/log/nginx/error_log (you can set the name of the common log file in the script)
```
#!/usr/bin/python

# Shows log lines of the running passenger instances (the stdout od the applications) for that user

import subprocess
import re
import sys
web_log='/var/log/nginx/error_log'
def get_passenger_pid(s):
        a=re.findall('PID\:\W+(\d+)\W+', i, re.MULTILINE)
        return a
# prints only the  nginx common log ilines with  App: pid
def grep_log(pid):
        print "Showing log for PID {}\n".format(pid)
        global web_log
        s_command="grep 'App " + pid + "' " + web_log
        lines=subprocess.check_output(s_command, shell=True)
        print lines
try:
        i=subprocess.check_output('passenger-status', stderr=subprocess.STDOUT)
except subprocess.CalledProcessError as details:
        print "The command shows the log of active processes. It seems that there are no active passenger processes for this web site."
        print "Send a request to the web site, to create an active process. Then try the command passenger-log again\n";
        sys.exit()

pids=get_passenger_pid(i)

# Itereate through the pids that were found in the passenger-status output
for pid in pids:
        grep_log(pid)

```

**Comment by msva** [comment]
1) it is a very kludge
2) this script assumes it (when run under user) has read access to system-wide passenger log. If it has access, then user has it. And this is what we want to avoid.

So, right way is per-application log files, and not kludgy scripts ;)

**Comment by Dolphi2** [comment]
As for point 2 I am aware of this limitation of the script. It can be fixed, by changing the script and running part of it as setuid.
The feature of seperation of the applications logs to sperate files is absolutly essential. We have no time to wait (this issue was opened in Sep 2014). It should have been introduced in version 1 not 5. It is difficult (and sometimes impossibe) for nodejs applications developer to deploy an application without access to the log which contains the stdout.

**Comment by jwhitmarsh** [comment]
:+1:

**Comment by Iazel** [comment]
+1

**Comment by mateuszef** [comment]
+1

**Comment by stoivo** [comment]
:+1:

**Comment by jharley** [comment]
:+1:

**Comment by msva** [comment]
Any chance this will be completed in the near time?

// after more than year of moving milestones :(

**Comment by OnixGH** [comment]
@msva it just happens to be an enhancement that requires relatively big changes, which is probably also the reason that noone has contributed a patch for something that is obviously wanted.

Anyway, the feature is on our radar and we're working on increasing our dev. speed, hoping to pick up enhancements like this in the coming months :)

**Comment by serkandurusoy** [comment]
+1

**Comment by wyardley** [comment]
At the very least, a program name or other identifier would be infinitely more useful than the PID. Since apps may run under >1 PIDs, and the PIDs cycle constantly, the current implementation [App PID] is not that useful.

**Comment by msva** [comment]
I think, it can be solved by implementing passenger_log_format directive (by analogy with access/error log directives)

**Comment by super-ienien** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by pbenefice** [comment]
+1 (as an Enterprise customer)

**Comment by pablitoc** [comment]
+1

**Comment by iDoMeteor** [comment]
How about just respecting Nginx's access_log & error_log?

**Comment by stewartcelani** [comment]
+1

**Comment by EduardJS** [comment]
+1

**Comment by igorloboda** [comment]
+1

**Comment by msva** [comment]
and still we playing in "move the milestone" game :(

**Comment by OnixGH** [comment]
@msva are you not able to use a logging framework?

**Comment by EduardJS** [comment]
@OnixGH We're sorry, we ain't that smart as you are. *cough*

**Comment by OnixGH** [comment]
@EduardJS what do you mean? I wasn't being sarcastic, I just wonder why using a logging framework isn't a good workaround, since they are generally recommended anyway, as well as dedicated to this purpose (so probably offer more flexibility)?

I can understand the case that it would be a great thing to have available "by default" (through Passenger), so you don't have to use anything else for the simple logging needs, but it somehow seems like @msva is blocked by not having it so I'm interested in why a logging framework (apparently?) isn't an option.

Anyway keep it nice please..

**Comment by msva** [comment]
First of all, sometimes, it is needed to hook messages even before application 
is started (if you mean intergrating logging in the application),

And sometimes it is not as easy as sounds like (AFAIRC, someone here wrote 
about node applications in that context).

======

Anyway, like it was already said, it will be pretty perfect, if passenger at 
least obeyed NginX's access_log/error_log/log_format settings.

**Comment by OnixGH** [comment]
@msva we need to take into account that Passenger is also used with Apache as well as in reverse proxy setups. I don't see anything about node in this thread, but can you say something about your own use case? People in this thread are asking for different things (which are not always compatible) so it's most valuable to know the use cases.

Btw. last month I tried something that might be relatively easy to implement, in line with what @wyardley suggested. We could prefix the app's stdout/stderr logging with application group name like in the example below (`/home/test/apps/nodejs/simple/public (development)`). By default that's the full path + environment, but you can already configure group names to something custom if you want to shorten.

```
=============== Phusion Passenger Standalone web server started ===============
PID file: /home/test/apps/nodejs/simple/passenger.3000.pid
Log file: /home/test/apps/nodejs/simple/passenger.3000.log
Environment: development
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
[ 2016-11-10 12:16:45.7121 9348/7f0609c59780 age/Cor/CoreMain.cpp:817 ]: Passenger core online, PID 9348
App 885 /home/test/apps/nodejs/simple/public (development) stdout: 
App 885 /home/test/apps/nodejs/simple/public (development) stdout: Simple app listening on port 2000!
App 885 /home/test/apps/nodejs/simple/public (development) stdout: GOT REQUEST
App 885 /home/test/apps/nodejs/simple/public (development) stdout: { connection: 'close',
App 885 /home/test/apps/nodejs/simple/public (development) stdout:   host: '0.0.0.0',
App 885 /home/test/apps/nodejs/simple/public (development) stdout:   'x-forwarded-for': '127.0.0.1',
App 885 /home/test/apps/nodejs/simple/public (development) stdout:   '!~passenger-client-address': '127.0.0.1' }
```

This would allow for per-(spawned)-application logs with a simple tailgrep (which could for example be started / stopped automatically using the attached_process / detached_process [hooks](https://www.phusionpassenger.com/library/indepth/hooks.html).

**Comment by wyardley** [comment]
FWIW, we mostly just use Winston + syslog transport with node projects that we run through Passenger (though I'd still love to see a more elegant fix for this problem as well).

**Comment by Wardrop** [comment]
+1 I've been wanting this for a long time.

**Comment by vaivars** [comment]
+1

**Comment by msva** [comment]
Is it any progress?

The issue has been reported 3 years ago, and it has [Priority/High] and [EnterpriseCustomer] tags for 1.5 years already, but looks like still not fixed in any way 😿 

P.S. @OnixGH, mostly, people (including me) just want that passenger either obey nginx access_log/error_log directives, or had the possibility to set `passenger_log` on per-`server{}` and per-`location{}` level.
So, each application will use separated logs without tons of kludges from user side (global passenger roubles can still go to the per-`http{}` log).

**Comment by OnixGH** [comment]
@msva I know it's not what you want to hear, but we don't consider it something that is broken, especially not since there are workarounds to achieve per-application log separation through additional tools (logging libraries, parse/forwarders,, etc.).

We did recently spend some rewriting effort in the logging department to make some parts easier (leading to a bonus of [supporting log level display](https://blog.phusion.nl/2017/08/23/passenger-5-1-8/)), but the core of the matter is that log separation is not something that is easy to realize (which is probably also why, despite the apparent popularity, we also haven't really gotten any patch submissions :( ).

I keep the Prio label on to make sure it has our (continued) attention (and it certainly does), but I also want to be clear that there is no roadmap for this feature at this time, We are [hiring](https://www.phusion.nl/careers#vacancies) though to further expand what we can spend on Passenger :).

**Comment by OnixGH** [comment]
This feature is now available in the [Fuse Panel](https://www.phusionpassenger.com/fuse-panel).

**Comment by OnixGH** [comment]
And also added to [Passenger 5.3.0](https://blog.phusion.nl/2018/05/09/passenger-5-3-0/) (Enterprise).
