### ISSUE TITLE
Passenger tries to start on port 0 and won't connect

### ISSUE THREAD

**Issue by thehack** [phusion/passenger#1308]
sudo /etc/nginx/sbin/nginx ## gives this  error: 

```
Cannot assign requested address - bind(2) for "127.0.0.1" port 0 (Errno::EADDRNOTAVAIL)
```

rvmsudo passenger start -p80 ##errors:

```
/home/username/.rvm/gems/ruby-2.1.5/gems/daemon_controller-1.2.0/lib/daemon_controller.rb:776:in `connect_nonblock': Invalid argument - connect(2) for 0.0.0.0:80 (Errno::EINVAL)
```

rvmsudo -s passenger-config validate-install ##reports:

```
 * Checking whether this Phusion Passenger install is in PATH... ✓
 * Checking whether there are no other Phusion Passenger installations... ✓
```

Config File:

```
   worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        passenger_root /home/thehack/.rvm/gems/ruby-2.1.5/gems/passenger-5.0.0.beta1;
        passenger_ruby /home/thehack/.rvm/gems/ruby-2.1.5/wrappers/ruby;
        passenger_friendly_error_pages on;
        gzip on;
        server {
            listen       80;
            server_name  beta.kidbuilder.net www.beta.kidbuilder.net;
            root /home/thehack/beta.kidbuilder/public;
            passenger_enabled on;
        }
    }
```

The app runs fine in Mongrel.

**Comment by FooBarWidget** [comment]
Unfortunately I haven't had any luck reproducing this problem on any Ubuntu 14.04 machine. :( Is there anybody else who can reproduce this?

**Comment by mlh758** [comment]
I think I'm having a very similar issue with passenger.
ubuntu:18.04

```
server {
    listen 8080;
    server_name localhost;

    root /var/www/app/public;
    rails_env crt;
    # Turn on Passenger
    passenger_enabled on;
}

passenger_pre_start localhost;
```

I then get `/usr/share/passenger/helper-scripts/prespawn:131:in `initialize': Cannot assign requested address - connect(2) for "::1" port 80 (Errno::EADDRNOTAVAIL)` like it is still trying to start on 80.

I'm using an nginx integration and due to a requirement in our environment I'm running nginx as a non-root user.

**Comment by FooBarWidget** [comment]
That's not how `passenger_pre_start` works. Try `passenger_pre_start http://localhost:8080`.

**Comment by mlh758** [comment]
Ah, I changed it just to mask the server name... but I think that might still be my problem. I didn't specify a port on the url. Let me try that.

**Comment by mlh758** [comment]
That was indeed my problem. Had to add the port number to the server_name and pre start directives after changing the listen port from 80. Thank you!
