### ISSUE TITLE
Ruby 2.2 got rid of rb_thread_blocking_region?

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1314]
It is reported that, when running Passenger under Ruby 2.2, the following error occurs:

```
passenger_native_support.so: undefined symbol: rb_thread_blocking_region
```

There have probably been large changes with regard to thread handling. This needs to be investigated.

**Comment by Ch4s3** [comment]
@FooBarWidget Any word on whether or not this will get released today?

**Comment by FooBarWidget** [comment]
That depends on QA results. If it's not today, probably Monday.

**Comment by Ch4s3** [comment]
Awesome! Thanks @FooBarWidget

**Comment by scott-stewart** [comment]
I noticed that 4.0.57 was recently pushed to ruby gems and confirm that all is well now on a Heroku Ruby 2.2.0 app.

**Comment by FooBarWidget** [comment]
Yes, 4.0.57 is unofficially released. I'm still working on the release announcement.

**Comment by roybotnik** [comment]
I just updated to 4.0.59 and for some reason this started showing up on one of my web servers again? Not sure what to make of it.

symbol lookup error: /home/deploy/.passenger-enterprise/native_support/4.0.59/ruby-2.2.0-x86_64-linux/passenger_native_support.so: undefined symbol: rb_thread_blocking_region
