### ISSUE TITLE
Passenger 4.0.53, fails to download precompiled passenger_native_support

### ISSUE THREAD

**Issue by tormedo** [phusion/passenger#1319]
Hi,

i have "ruby --version"

    ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]

and when i try to enter my page i get this in my nginx error logs:

    App 30628 stdout: 
    App 30628 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
    App 30628 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
    App 30628 stderr:  --> Downloading precompiled passenger_native_support.so for the current Ruby interpreter...
    App 30628 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
    App 30628 stderr:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/4.0.53/rubyext-ruby-2.1.4-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
    App 30628 stderr:      Trying next mirror...
    App 30628 stderr:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/4.0.53/rubyext-ruby-2.1.4-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
    App 30628 stderr:  --> Continuing without passenger_native_support.so.
    [ 2014-12-11 20:43:38.1324 30560/7f02b3e63700 Pool2/SmartSpawner.h:298 ]: Preloader for /opt/gitlab/embedded/service/gitlab-rails started on PID 30628, listening on unix:/tmp/passenger.1.0.30556/generation-0/backends/preloader.1rw1knv
    App 30662 stdout: 

so it seems the generated link

    rubyext-ruby-2.1.4-x86_64-linux.tar.gz

is wrong.

**Comment by OnixGH** [comment]
No feedback received, assuming resolved.
