### ISSUE TITLE
Add delay/wait for passenger_pre_start

### ISSUE THREAD

**Issue by terrybleger** [phusion/passenger#1323]
My Node.js server needs some time to do some work before it can start to accept connection. So ```passenger_pre_start``` will always fails. But any first request is always success if the server is already up and running. 

This means that ```passenger_pre_start``` didn't wait for the server to be up and running, while passenger it self is able to wait/hold the request.

So, I have 2 suggestions:
1. Is it possible to have ```passenger_pre_start_delay``` in seconds?
2. Or could ```passenger_pre_start``` **wait** until the server is up and running? Because any first request is always success if the server is already up and running because passenger is able to wait/hold the request, while request from ```passenger_pre_start``` doesn't wait/hold the request.

**Comment by FooBarWidget** [comment]
@terrybleger What do you think about my last comment?

**Comment by terrybleger** [comment]
@FooBarWidget 

Sorry for having late reply.

I haven't had the time to test it against the latest version of passenger.

Currently since the last time I tested it, passenger_pre_start has always failed. So my only solution is just create a bash script, everytime after nginx is started, it will execute curl just to boot the site (which is ironically the same thing that passenger_pre_start should able to do it).

**Comment by OnixGH** [comment]
@terrybleger any update on using the method @FooBarWidget described? It should accomplish what you reported.
