### ISSUE TITLE
passenger 5.0.0.beta1 has http post error

### ISSUE THREAD

**Issue by parangdae** [phusion/passenger#1327]
previous version Release 4.0.46
Fixed Nginx HTTP POST failures on ARM platforms. Thanks to nocelic for the fix.
   Closes GH-1151.

but i test env
Version : 5.0.0.beta1
Date    : 2014-12-18 19:33:03 +0900
Instance: cujhiZSn (nginx/1.6.2 Phusion_Passenger/5.0.0.beta1)

that appears above issue.

test another platform is not problem.

**Comment by FooBarWidget** [comment]
I think this is the same issue as #1331. It has already been fixed in git master.
