### ISSUE TITLE
Passenger failed on ruby2.2.0 + Rails 4.2 on CentOS 6.5

### ISSUE THREAD

**Issue by wzymaster** [phusion/passenger#1342]
I recently upgrade my rails app from **ruby 2.0.0 + Rails 4.0**  to  **ruby 2.2.0 + Rails 4.2**.  However, I hit error  like following after start up my app :  

/usr/local/rvm/gems/ruby-2.2.0@ruby/gems/passenger-4.0.42/lib/phusion_passenger/request_handler.rb:356 'trap': Invalid Argument - SIGKILL(Argument:ENVAL)

It looks like that **"KILL"** signal isn't supported there.   My quick work-around here is to add codes to skip "KILL" signal in the loop like following : 

def reset_signal_handlers
                Signal.list_trappable.each_key do |signal|
                        begin
                               **next if signal == "KILL"**
                                prev_handler = trap(signal, DEFAULT)
                                if prev_handler != DEFAULT
                                        @previous_signal_handlers[signal] = prev_handler
                                end
                        rescue ArgumentError

**Comment by FooBarWidget** [comment]
This is a bug in Phusion Passenger, as also reported in #1341. I'll have this fixed.

**Comment by shyam** [comment]
@wzymaster - Did you try with  `passenger-4.0.57` ?
I too experienced the same issue with my **Rails 4.2** application with **ruby 2.2.0-p0** on `passenger-4.0.50`. However, `passenger-4.0.57` works for me.

**Comment by FooBarWidget** [comment]
This is odd, I cannot reproduce this problem in the end. In Signal.list_trappable, we explicitly exclude SIGKILL, so you shouldn't have run into this problem in the first place.

Could you help me and run the following command in the Passenger source directory and tell me what you see?

    ./dev/runner -rruby_core_enhancements 'Signal.list_trappable.keys'

**Comment by wzymaster** [comment]
Sorry for the late reply and here is what I get from running the above command line :  

[root@bluforcloud-test passenger-4.0.42]# ./dev/runner -rruby_core_enhancements 'Signal.list_trappable.keys'
 --> Compiling passenger_native_support.so for the current Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Compilation succesful. The logs are here:
     /tmp/passenger_native_support-jb8hg5.log
 --> passenger_native_support.so successfully loaded.
["EXIT", "HUP", "INT", "QUIT", "ILL", "TRAP", "ABRT", "IOT", "FPE", "KILL", "BUS", "SEGV", "SYS", "PIPE", "TERM", "URG", "TSTP", "CONT", "TTIN", "TTOU", "IO", "XCPU", "XFSZ", "PROF", "WINCH", "USR1", "USR2", "PWR", "POLL"]

**Comment by wzymaster** [comment]
Here is my ruby and rails version in my app directory :  

[root@bluforcloud-test IMDC-Jclouds-Dashboard]# rails -v
Rails 4.2.0
[root@bluforcloud-test IMDC-Jclouds-Dashboard]# ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

**Comment by FooBarWidget** [comment]
I see why I can't reproduce the problem, you're just on an old version of Phusion Passenger. This bug has already been fixed. Please upgrade to 4.0.58.
