### ISSUE TITLE
Passenger meteor: cannot create directory `/nonexistent/.meteor-install-tmp'

### ISSUE THREAD

**Issue by tiaozi0912** [phusion/passenger#1344]
Following meteor passenger tutorial here: https://github.com/phusion/passenger/wiki/Phusion-Passenger:-Meteor-tutorial#deploying_to_production. Using meteor 1.0.2.1 and passenger 4.0.57.
The public and tmp directory both exist. Deployed as the raw meteor app(not bundled).

But got the error

    App 10979 stderr: mkdir: 
    App 10979 stderr: cannot create directory `/nonexistent/.meteor-install-tmp'
    App 10979 stderr: : No such file or directory

when starting the server. Can't figure out where went wrong.

The nginx config was:

    server {
        listen 8080;
        server_name www.example.com;
        root /root/myapp/public;
        passenger_enabled on;
        passenger_sticky_sessions on;
        passenger_set_cgi_param MONGO_URL mongodb://localhost:27017/meteor;
        passenger_set_cgi_param MONGO_OPLOG_URL mongodb://localhost:27017/local;
        passenger_set_cgi_param ROOT_URL http://www.example.com;
    
        # Set these ONLY if your app is a Meteor bundle!
        #passenger_app_type node;
        #passenger_startup_file main.js;
    }

**Comment by FooBarWidget** [comment]
It's because your app is being run as the 'nobody' user, per [the user switching rules](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#user_switching). Try forcing your app to be run as a specific user through the [passenger_user](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerUser) directive.

**Comment by tiaozi0912** [comment]
Add the passenger_user in the server block but the error still happens. 

Per the document, the auto user switch is on by default. It should run the app as the owner of the .meteor directory even without the passenger_user directive. That directory is owned by root shown below, which is the right owner. Wondering why there is the problem.
```
-rwxrwxrwx 1 root root    1 Jan 10 07:41 cordova-plugins
drwxrwxrwx 3 root root 4096 Jan 10 07:41 local
-rwxrwxrwx 1 root root  275 Jan 10 07:41 packages
-rwxrwxrwx 1 root root   27 Jan 10 07:41 platforms
-rwxrwxrwx 1 root root   15 Jan 10 07:41 release
-rwxrwxrwx 1 root root  823 Jan 10 07:41 versions
```

**Comment by FooBarWidget** [comment]
Does the error message stay the same despite adding passenger_user? Or is it different now?

Did you restart Nginx after making the Nginx configuration file change?

**Comment by colindensem** [comment]
I had this using the non bundle, so in this case, copying files from host to image via: 
ADD meteorapp /home/app/meteor-app 

Three things I noted:
* Add tmp dir to project, facilitates touching restart.txt.
* Set ownership of user, i.e. app
  *  ADD webApp /home/app/meteor-app
  *  RUN chown -R app:app /home/app/meteor-app
* In my nginx vhost,   passenger_user app;

It's plausible one or none of those will be needed going forwards. I'm planning on using the bundle approach, but this was a simple test and the above got rid of this error. HTH
