### ISSUE TITLE
cannot load such file -- passenger (LoadError)

### ISSUE THREAD

**Issue by tianlitao** [phusion/passenger#1345]
i recently use gem faye-rails in my progject,i have the error of this,can you help me?thanks

cannot load such file -- passenger (LoadError)
  /var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
  /var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
  /var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
  /var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
  /var/lib/gems/1.9.1/gems/faye-websocket-0.9.2/lib/faye/websocket.rb:42:in `load_adapter'
  /var/lib/gems/1.9.1/gems/faye-rails-2.0.0/lib/faye-rails/middleware.rb:44:in `initialize'
  /var/lib/gems/1.9.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:43:in `new'
  /var/lib/gems/1.9.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:43:in `build'
  /var/lib/gems/1.9.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
  /var/lib/gems/1.9.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:118:in `each'
  /var/lib/gems/1.9.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:118:in `inject'
  /var/lib/gems/1.9.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:118:in `build'
  /var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:498:in `app'
  /var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application/finisher.rb:36:in `block in <module:Finisher>'
  /var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `run'
  /var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
  /usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
  /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
  /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
  /usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
  /var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application.rb:300:in `initialize!'
  /home/tlt/work/faye-rails-demo-master/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:112:in `eval'
  /var/lib/gems/1.9.1/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /var/lib/gems/1.9.1/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /var/lib/gems/1.9.1/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:28:in `<main>'
Error ID
3650db5a
Application root
/home/tlt/work/faye-rails-demo-master
Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)
development
Ruby interpreter command
/usr/bin/ruby1.9.1
User and groups
uid=1000(tlt) gid=1000(tlt) groups=1000(tlt),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),112(lpadmin),118(sambashare)
Environment variables
GNOME_KEYRING_PID = 1724
USER = tlt
_system_version = 16
XDG_SEAT = seat0
SSH_AGENT_PID = 1808
SHLVL = 1
OLDPWD = /home/tlt
HOME = /home/tlt
MDM_LANG = zh_CN.UTF-8
XDG_SESSION_COOKIE = 0df215f550635bcb759d4fe753889629-1421024671.99673-894041116
DESKTOP_SESSION = default
GDM_XSERVER_LOCATION = local
DBUS_SESSION_BUS_ADDRESS = unix:abstract=/tmp/dbus-Oq1KCx0Wob,guid=b5efb73f88dfba58f60d507b54b31d9f
COLORTERM = gnome-terminal
GNOME_KEYRING_CONTROL = /run/user/1000/keyring-RjTP6c
MDMSESSION = default
MANDATORY_PATH = /usr/share/gconf/default.mandatory.path
LOGNAME = tlt
GTK_IM_MODULE = fcitx
rvm_bin_path = /home/tlt/.rvm/bin
WINDOWID = 46137352
_ = /usr/local/bin/passenger
DEFAULTS_PATH = /usr/share/gconf/default.default.path
XDG_SESSION_ID = c2
TERM = xterm
USERNAME = tlt
GNOME_DESKTOP_SESSION_ID = this-is-deprecated
WINDOWPATH = 8
PATH = /var/lib/gems/1.9.1/bin:/home/tlt/program/android-sdk-linux/tools:/home/tlt/program/android-sdk-linux/platform-tools:/usr/lib/jvm/java-7-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games::/usr/bin/ant/bin:/home/tlt/.rvm/bin:/home/tlt/download/android-sdk-linux/tools:/home/tlt/download/android-sdk-linux/platform-tools
ANT_HOME = /usr/bin/ant
SESSION_MANAGER = local/tlt-Lenovo-B470:@/tmp/.ICE-unix/1734,unix/tlt-Lenovo-B470:/tmp/.ICE-unix/1734
rvm_recommended_ruby = rvm install ruby-1.9.3-p547
XDG_RUNTIME_DIR = /run/user/1000
DISPLAY = :0
LANG = zh_CN.UTF-8
XDG_CURRENT_DESKTOP = GNOME
LS_COLORS = rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
XMODIFIERS = @im=fcitx
XAUTHORITY = /tmp/.mdmG0PASX
SSH_AUTH_SOCK = /run/user/1000/keyring-RjTP6c/ssh
SHELL = /bin/bash
NODE_PATH = /var/lib/gems/1.9.1/gems/passenger-4.0.57/node_lib
CLUTTER_DISABLE_XINPUT = 1
rvm_prefix = /home/tlt
GDMSESSION = default
_system_type = Linux
GPG_AGENT_INFO = /run/user/1000/keyring-RjTP6c/gpg:0:1
SECRET_KEY_BASE = e666fd082bfa95dff96edb5fe3ea7b0800172b978dc1182bc99842439d16f50b4c2f409531da93d4f09efc5c6464429484c854ff052b8c6ab2ccc4e6868af73f
rvm_version = 1.25.28 (stable)
CLASSPATH = .:/usr/lib/jvm/java-7-openjdk-amd64/lib/dt.jar:/usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar
XDG_VTNR = 8
QT_IM_MODULE = fcitx
_system_arch = x86_64
PWD = /home/tlt/work/faye-rails-demo-master
JAVA_HOME = /usr/lib/jvm/java-7-openjdk-amd64
ANDROID_HOME = /home/tlt/download/android-sdk-linux
XDG_CONFIG_DIRS = /etc/xdg/xdg-default:/etc/xdg
XDG_DATA_DIRS = /usr/share/default:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/mdm/
MDM_XSERVER_LOCATION = local
_system_name = Mint
VTE_VERSION = 3406
rvm_path = /home/tlt/.rvm
rvm_delete_flag = 0
SERVER_SOFTWARE = nginx/1.6.2
PASSENGER_DEBUG_DIR = /tmp/passenger.spawn-debug.XXXXwSuChO
IN_PASSENGER = 1
PYTHONUNBUFFERED = 1
RAILS_ENV = development
RACK_ENV = development
WSGI_ENV = development
NODE_ENV = development
PASSENGER_APP_ENV = development
SERVER_PROTOCOL = HTTP/1.1
SCGI = 1
DOCUMENT_ROOT = /home/tlt/work/faye-rails-demo-master/public
QUERY_STRING = 
SERVER_NAME = 0.0.0.0
REMOTE_PORT = 34607
REMOTE_ADDR = 127.0.0.1
SERVER_PORT = 3000
REQUEST_METHOD = HEAD
SERVER_ADDR = 127.0.0.1
REQUEST_URI = /
GEM_PATH = /var/lib/gems/1.9.1:/home/tlt/.gem/ruby/1.9.1
GEM_HOME = /var/lib/gems/1.9.1
BUNDLE_BIN_PATH = /usr/lib/ruby/bin/bundle
BUNDLE_GEMFILE = /home/tlt/work/faye-rails-demo-master/Gemfile
RUBYOPT = -I/usr/lib/ruby/vendor_ruby -rbundler/setup

**Comment by tianlitao** [comment]
my same problem of stackoverflow
http://stackoverflow.com/questions/23570507/rails-faye-apache-moving-faye-from-thin-to-passenger

**Comment by FooBarWidget** [comment]
From a first look, this appears to be a bug in the faye gem.

**Comment by tianlitao** [comment]
Thanks,has been resolved.Beacuse of gem 'faye-rails'
https://github.com/jamesotron/faye-rails/issues/58

Thanks again.
