### ISSUE TITLE
Typo in builtin_engine.rb causes passenger standalone to fail to run

### ISSUE THREAD

**Issue by peterc** [phusion/passenger#1348]
There's a typo on line 83 of builtin_engine.rb! I changed it locally and then passenger start run fine :-) It otherwise fails like so:

    /usr/local/lib/ruby/gems/2.1.0/gems/passenger-5.0.0.beta2/lib/phusion_passenger/standalone/start_command/builtin_engine.rb:83:in `build_daemon_controller_options': undefined method `ecape' for Shellwords:Module (NoMethodError)

Changing "ecape" to "escape" resolves.

**Comment by d-snp** [comment]
Hi Peter,

Thanks for reporting! Someone else also had already reported the bug, and it's due for the next release :)

https://github.com/phusion/passenger/commit/fb301acb41a36041300acb7d0ec2434598e08a2a
