### ISSUE TITLE
Session being emptied on POST requests in 5.0.0-beta2

### ISSUE THREAD

**Issue by peterc** [phusion/passenger#1349]
(I'm aware of #1310 and the #1296 Set-Cookie bugs from beta 1 - this *appears* to be something else.)

On 5.0.0-beta2 in standalone mode against Rails 4.2.0, any POST request is causing the existing session cookie's contents to be wiped back to basics (with a new session ID as well). That is, if a ~1500 byte cookie heads in to the POST request, a ~150 byte one comes back. It's not a CSRF issue as it's the same with protect_from_forgery off (and the auth tokens are valid anyway).

Data is retained correctly between multiple GET requests, but as soon as a POST request (even one that does nothing to the session itself in the controller code) occurs, a new empty session is returned. This does not occur with WEBrick or Passenger 4.0.57 which I have now downgraded to.

**Comment by FooBarWidget** [comment]
Are you able to reproduce this issue with beta 3?

**Comment by FooBarWidget** [comment]
Peter, do you have any feedback on this? If possible I'd like to get this solved before the 5.0.1 release next week.

**Comment by peterc** [comment]
My mind's not really in the project I was using on this, but I just installed 5.0.1b3 and the app in question (which has since become somewhat larger in scale) no longer exhibits the behavior and the session is maintained.
