### ISSUE TITLE
Passenger  4.0.58 Apache module installation fails on Centos 7- libcurl 7.29.0

### ISSUE THREAD

**Issue by sardpost** [phusion/passenger#1355]
Hi all!
I'm trying to install Passenger module for Apache on a new Centos 7 server with ruby 2.0.0p353. I installed all the required packages but when I run ```passenger-install-apache2-module``` I get this error:

```
Error: libcurl was found, but it isn't usable. Set VERBOSE=1 to see why.
      curl-config location: /usr/bin/curl-config
      Header location: somewhere, not sure where
      Version: libcurl 7.29.0
      Usable: no
```
When I run ```VERBOSE=1 passenger-install-apache2-module``` the output is this one:

```
* Checking for Curl development headers with SSL support...
       -> Checking for curl/curl.h
          Running: cc -v -c '/tmp/passenger.1mic7yr/passenger-compile-check.c' -o '/tmp/passenger.1mic7yr/passenger-compile-check.c.o'
          Source file contains:
          -------------------------
          #include <curl/curl.h>
          -------------------------
       -> Output:
          -------------------------
          
          -------------------------
       -> Check suceeded
       -> Checking for libcurl usability
          Running: cc '/tmp/passenger.5mro4b/passenger-run-check.c' -o '/tmp/passenger.5mro4b/passenger-run-check.c.out'  -lcurl
          Source file contains:
          -------------------------
          #include <curl/curl.h>
          int main() {
          	curl_global_init(CURL_GLOBAL_ALL);
          	return 0;
          }
          -------------------------
       -> Check suceeded
       -> Running /tmp/passenger.5mro4b/passenger-run-check.c.out
       -> Command exited with status 127. Output:
          --------------
          sh: /tmp/passenger.5mro4b/passenger-run-check.c.out: No such file or directory
          
          --------------
      Found: yes, but there was an error
      Error: libcurl was found, but it isn't usable. Set VERBOSE=1 to see why.
      curl-config location: /usr/bin/curl-config
      Header location: somewhere, not sure where
      Version: libcurl 7.29.0
      Usable: no
```

I also tried previous versions of Passenger (4.0.57) but I still got the same issue. Unfortunately on Centos 7 I wasn't able to downgrade curl, and libcurl-dev to see if the issue could be solved.

**Comment by FooBarWidget** [comment]
Maybe your /tmp directory is mounted noexec. Try re-running
passenger-install-apache2-module with TMPDIR=/somewhere-else, where
/somewhere-else is some directory which it can use for storing temporary
files.

On Fri, Jan 23, 2015 at 5:21 PM, Davide Puggioni <notifications@github.com>
wrote:

> Hi all!
> I'm trying to install Passenger module for Apache on a new Centos 7 server
> with ruby 2.0.0p353. I installed all the required packages but when I run
> passenger-install-apache2-module I get this error:
>
> Error: libcurl was found, but it isn't usable. Set VERBOSE=1 to see why.
>       curl-config location: /usr/bin/curl-config
>       Header location: somewhere, not sure where
>       Version: libcurl 7.29.0
>       Usable: no
>
> When I run VERBOSE=1 passenger-install-apache2-module the output is this
> one:
>
> * Checking for Curl development headers with SSL support...
>        -> Checking for curl/curl.h
>           Running: cc -v -c '/tmp/passenger.1mic7yr/passenger-compile-check.c' -o '/tmp/passenger.1mic7yr/passenger-compile-check.c.o'
>           Source file contains:
>           -------------------------
>           #include <curl/curl.h>
>           -------------------------
>        -> Output:
>           -------------------------
>
>           -------------------------
>        -> Check suceeded
>        -> Checking for libcurl usability
>           Running: cc '/tmp/passenger.5mro4b/passenger-run-check.c' -o '/tmp/passenger.5mro4b/passenger-run-check.c.out'  -lcurl
>           Source file contains:
>           -------------------------
>           #include <curl/curl.h>
>           int main() {
>             curl_global_init(CURL_GLOBAL_ALL);
>             return 0;
>           }
>           -------------------------
>        -> Check suceeded
>        -> Running /tmp/passenger.5mro4b/passenger-run-check.c.out
>        -> Command exited with status 127. Output:
>           --------------
>           sh: /tmp/passenger.5mro4b/passenger-run-check.c.out: No such file or directory
>
>           --------------
>       Found: yes, but there was an error
>       Error: libcurl was found, but it isn't usable. Set VERBOSE=1 to see why.
>       curl-config location: /usr/bin/curl-config
>       Header location: somewhere, not sure where
>       Version: libcurl 7.29.0
>       Usable: no
>
> I also tried previous versions of Passenger (4.0.57) but I still got the
> same issue. Unfortunately on Centos 7 I wasn't able to downgrade curl, and
> libcurl-dev to see if the issue could be solved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phusion/passenger/issues/1355>.
>



-- 
Phusion | Web Application deployment, scaling, and monitoring solutions

Web: http://www.phusion.nl/
E-mail: info@phusion.nl
Chamber of commerce no: 08173483 (The Netherlands)

**Comment by sardpost** [comment]
Hi, I tried the installation setting the TMPDIR to a different path as you suggested but I had the same results with the same output. If it can be useful to replicate the issue, the server it's a new server from a Centos 7 minimal iso. After the installation I updated everything with yum upgrade and then I just installed Apache and all the required packages needed by Passenger.

**Comment by ylluminate** [comment]
Interesting, having the same problem here now too (CentOS / CloudLinux 6.6):
```
$ TMPDIR=$HOME/tmp VERBOSE=1 passenger-install-apache2-module --apxs2-path "/usr/local/apache/bin/apxs"
```
```
 * Checking for Curl development headers with SSL support...
       -> Checking for curl/curl.h
          Running: cc -v -c '/root/tmp/passenger.12ammjf/passenger-compile-check.c' -o '/root/tmp/passenger.12ammjf/passenger-compile-check.c.o'
          Source file contains:
          -------------------------
          #include <curl/curl.h>
          -------------------------
       -> Output:
          -------------------------
          Using built-in specs.
          Target: x86_64-redhat-linux
          Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
          Thread model: posix
          gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
          COLLECT_GCC_OPTIONS='-v' '-c' '-o' '/root/tmp/passenger.12ammjf/passenger-compile-check.c.o' '-mtune=generic'
           /usr/libexec/gcc/x86_64-redhat-linux/4.4.7/cc1 -quiet -v /root/tmp/passenger.12ammjf/passenger-compile-check.c -quiet -dumpbase passenger-compile-check.c -mtune=generic -auxbase-strip /root/tmp/passenger.12ammjf/passenger-compile-check.c.o -version -o /root/tmp/ccwGABvw.s
          ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/include-fixed"
          ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../x86_64-redhat-linux/include"
          #include "..." search starts here:
          #include <...> search starts here:
           /usr/local/include
           /usr/lib/gcc/x86_64-redhat-linux/4.4.7/include
           /usr/include
          End of search list.
          GNU C (GCC) version 4.4.7 20120313 (Red Hat 4.4.7-11) (x86_64-redhat-linux)
          	compiled by GNU C version 4.4.7 20120313 (Red Hat 4.4.7-11), GMP version 4.3.1, MPFR version 2.4.1.
          GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
          Compiler executable checksum: afbaaee14938b25395866d0c9f1de15a
          COLLECT_GCC_OPTIONS='-v' '-c' '-o' '/root/tmp/passenger.12ammjf/passenger-compile-check.c.o' '-mtune=generic'
           as -V -Qy -o /root/tmp/passenger.12ammjf/passenger-compile-check.c.o /root/tmp/ccwGABvw.s
          GNU assembler version 2.20.51.0.2 (x86_64-redhat-linux) using BFD version version 2.20.51.0.2-5.42.el6 20100205
          COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/:/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/:/usr/lib/gcc/x86_64-redhat-linux/:/usr/libexec/gcc/x86_64-redhat-linux/4.4.7/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/:/usr/lib/gcc/x86_64-redhat-linux/
          LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.4.7/:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../:/lib/:/usr/lib/
          COLLECT_GCC_OPTIONS='-v' '-c' '-o' '/root/tmp/passenger.12ammjf/passenger-compile-check.c.o' '-mtune=generic'
          
          -------------------------
       -> Check suceeded
       -> Checking for libcurl usability
          Running: cc '/root/tmp/passenger.mk9lw/passenger-run-check.c' -o '/root/tmp/passenger.mk9lw/passenger-run-check.c.out'
          Source file contains:
          -------------------------
          #include <curl/curl.h>
          int main() {
          	curl_global_init(CURL_GLOBAL_ALL);
          	return 0;
          }
          -------------------------
/root/tmp/ccZTSqcC.o: In function `main':
passenger-run-check.c:(.text+0x9a): undefined reference to `curl_global_init'
collect2: ld returned 1 exit status
       -> Check failed with exit status 1
      Found: yes, but there was an error
      Error: libcurl was found, but it isn't usable. Set VERBOSE=1 to see why.
      curl-config location: /usr/bin/curl-config
      Header location: /usr/include/curl/curl.h
      Version: libcurl 7.19.7
      Usable: no
```

Interestingly it worked fine previously in `/tmp` with NOEXEC set, but I did a sanity check and set tmp to the user tmp folder that would not have that set and had the same result either way.

**Comment by FooBarWidget** [comment]
I just tested on an empty CentOS 7 distro, but I can't reproduce either of your problems.

@ylluminate What do you see when you run `/usr/bin/curl-config --cflags`? What do you see when you run `/usr/bin/curl-config --libs`?

**Comment by ylluminate** [comment]
FOUND THE PROBLEM:

`/usr/bin/curl-config --cflags` returns a blank string / nil.

`/usr/bin/curl-config --libs` returns:
```
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
```

Upon seeing this, I realized that `pkg-config` was having problems due to also being present in `linuxbrew`.  I installed linuxbrew just a couple days ago due to some dependency issues for a couple apps and my having wanted a reliable way to install and update needed utilities.  To this end I installed `linuxbrew` as an admin user and then symlink'd it over to `/opt/linuxbrew` and added a path for all users in the env config in /etc/profile.d for bash and /etc/zshenv for zsh.  Since I have the linuxbrew bins superseding system binaries, pkg-config was running from /opt/linuxbrew/bin/pkg-config and was not finding libcurl.  Not entirely sure why yet, but that is what happened.  After I did a `brew install curl`, `passenger -install-apache2-module`, as indicated before, executed completely and correctly.

Sorry for the false alarm and not catching this myself.  Do you have a recommendation on how to make `linuxbrew` play more nicely in the case of `pkg-config` detecting system libs that are installed?

**Comment by FooBarWidget** [comment]
I'm not familiar with linuxbrew so I'm afraid I can't give you advice on that matter.

**Comment by hanynowsky** [comment]
In case of a CENTOS:

$~ locate libcurl.pc
/usr/lib64/pkgconfig/libcurl.pc
$~ export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib64/pkgconfig/
$~ /usr/bin/curl-config --libs
-L/usr/lib64 -lcurl
