### ISSUE TITLE
Introduce hook for request queue overflows

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1358]
A user has requested a hook for request queue overflows. That way, he can install notifications for when such events occur (e.g. when the server is being DoS'ed). More info: http://stackoverflow.com/a/20419536/20816

**Comment by dmitry** [comment]
@FooBarWidget thank you! That would be definitely very helpful to monitor possible downtimes and the reason of them.

**Comment by FooBarWidget** [comment]
@OnixGH You should add an entry to the changelog. The changelog entry should reference this issue.

**Comment by dmitry** [comment]
Please update documentation here: https://github.com/phusion/passenger/blob/491f12e6886df9a970e2c81e89a289910b4c9103/doc/users_guide_snippets/tips.txt#L484

**Comment by OnixGH** [comment]
Hi dmitry, that was already done in the previous commit (2dca16b), but on branch dk-intro. I will be merging it into the master when fully ready :)

**Comment by dmitry** [comment]
@OnixGH thanks for the update!
