### ISSUE TITLE
Ruby 2.2.0-p0 + Rails 4.2 + Passenger 5.0.0.beta2 -undefined symbol: rb_thread_blocking_region

### ISSUE THREAD

**Issue by cfiorini** [phusion/passenger#1359]
hi guys,
may be this issue was already fix but on my staging  server during try out of passenger 5.0.0.beta2
I get this error:

App 21425 stderr: Passenger RubyApp: /var/... (staging): symbol lookup error: /home/webmaster/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/passenger-5.0.0.beta2/buildout/ruby/ruby-2.2.0-x86_64-linux/passenger_native_support.so: undefined symbol: rb_thread_blocking_region

agents/HelperAgent/RequestHandler/Utils.cpp:89 ]: [Client 1.1] Sending 502 response: application did not send a complete response

using ruby 2.2.0-p0 + rails 4.2 + passenger 4.0.58 i don't have any issue, everything works fine.

if this is still an issue let me know if i can help you in some way

**Comment by FooBarWidget** [comment]
This fix is indeed already committed. It will be part of 5.0.0 beta 3.
