### ISSUE TITLE
Add json format to passenger-status 

### ISSUE THREAD

**Issue by mikechau** [phusion/passenger#1363]
I see `passenger-status` can output `xml`, any chance for a `json` option so it can be easily parsed by tools like `Ansible`?

I'd love to be able to do something like:

```
passenger-status --show=json
```

**Comment by FooBarWidget** [comment]
There are no plans for doing this. The output format is XML because the mechanism was invented at a time before JSON has become the new hotness. There is nothing wrong with XML. While I am not familiar with Ansible, there should be tons of XML parsers out there that you can use.

**Comment by spider-network** [comment]
The benefit about json is: You can pipe the output to Logstash->Elasticsearch and analyse the data via Kibana

Please reopen the issue ;-)

**Comment by OnixGH** [comment]
@spider-network doesn't logstash have an XML filter?
