### ISSUE TITLE
When installing apache module, add an optional command line switch to output the passenger.conf snippet to a file

### ISSUE THREAD

**Issue by shyam-habarakada** [phusion/passenger#1365]
If there was a switch like `--generate-passenger-conf` that saves a `passenger.conf` file (in addition to outputting the information to the terminal) this would greatly simplify automated installs.

Thanks

**Comment by shyam-habarakada** [comment]
This is to automate this step from the docs https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#working_with_apache_conf

**Comment by FooBarWidget** [comment]
This can already be automated. Just pass `--snippet` to the installer.
