### ISSUE TITLE
Date header must be in GMT

### ISSUE THREAD

**Issue by thibaudgg** [phusion/passenger#1367]
I think  #1012 is back in 5.0 beta3. 
My app serves now (with last beta) Date header as `Tue, 10 Feb 2015 10:03:07 +0000` causing `Time.httpdate` to raise `ArgumentError: not RFC 2616 compliant date`.

It should be "Tue, 10 Feb 2015 10:03:07 GMT", like it was in version 4.0, no?

**Comment by FooBarWidget** [comment]
Yes, though I do not know why. We didn't change the timestamp generation code.

Anyway, the %Z formatter in strftime is problematic. I'll just replace it with a hardcoded "GMT" string.

**Comment by thibaudgg** [comment]
:+1:
