### ISSUE TITLE
Debian packages for Ubuntu 14.04

### ISSUE THREAD

**Issue by andrey-evdokimov** [phusion/passenger#1369]
After upgrade to Ubuntu 14.10 I get error when I run command `sudo apt-get update`:
Error:

```
W: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/utopic/main/binary-amd64/Packages  HttpError404
W: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/utopic/main/binary-i386/Packages  HttpError404
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

and fail to get passenger_native_support.so in Ubuntu 14.10 (with ruby 2.1.2)

```
App 2139 stdout:
App 2139 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 2139 stderr:
App 2139 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 2139 stderr:
App 2139 stderr:  --> Downloading precompiled passenger_native_support.so for the current Ruby interpreter...
App 2139 stderr:
App 2139 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 2139 stderr:
App 2139 stderr:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/4.0.59/rubyext-ruby-2.1.2-x86_64-linux.tar.gz: Resolving timed out after 4514 milliseconds
App 2139 stderr:      Trying next mirror...
App 2139 stderr:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/4.0.59/rubyext-ruby-2.1.2-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 2139 stderr:  --> Continuing without passenger_native_support.so.
```

**Comment by FooBarWidget** [comment]
You are experiencing two distinct issues here. The first one is that we do not have Ubuntu 14.10 packages yet (see #1400), so the APT failure is normal.

The other one is a timeout while downloading passenger_native_support.so because of network problems. You should initiate a manual download (with higher timeouts) by running `passenger-config build-native-support`).

**Comment by andrey-evdokimov** [comment]
Thanks for response. But it is not a network problem, a problem of lack of file rubyext-ruby-**2.1.2**-x86_64-linux.tar.gz

**Comment by FooBarWidget** [comment]
Oh yes, I see. I was confused by the initial connect timeout error.

We don't supply native_support binaries for every Ruby interpreter version, but we don't have to. If it fails to download a binary, it will compile from source instead. If that fails too, it will just continue without native_support. native_support provides a number of micro-optimizations, but performance is quite good without native_support too.
