### ISSUE TITLE
"Request queue is full. Returning an error"

### ISSUE THREAD

**Issue by jelder** [phusion/passenger#1375]
This error message would a be a lot more helpful if it indicated the configured size of the request queue and the error being returned ("an" error is not helpful).

**Comment by FooBarWidget** [comment]
Why should the configured size be mentioned in the log? Isn't that already obvious by looking at the configuration file?

As for the error: it should be obvious from the [passenger_request_queue_overflow_status_code](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#passenger_request_queue_overflow_status_code) rules, so why mention it in the log?

**Comment by FooBarWidget** [comment]
@jelder Looking forward to hear your thoughts on my last comment.

**Comment by jelder** [comment]
@FooBarWidget I reported this error while I was trying to debug the latest Passenger 5 beta in production, so I apologize for any apparent frustration in my tone. I will try to submit a reproducible example soon.

My thinking is that since the error code and queue size are each configurable at 4 different scopes, the log message is actually quite ambiguous without further context.

**Comment by FooBarWidget** [comment]
No offense taken. I am genuinely curious about your rationale. Changes are up for discussion but need to be backed by good reasons.

When you say that they are configurable at 4 different scopes, does this mean that you tried to configure it, but felt frustrated because you didn't know whether it had effect? That sounds like a good reason to include setting value in the message.

**Comment by jelder** [comment]
Exactly. I *think* I saw that the setting was not getting applied (our custom error page was not being returned), but in the end for other reasons I decided to roll back to Passenger 4 for the time being.

**Comment by FooBarWidget** [comment]
Ok, scheduling this for the 5.0 final release (5.0.1). Sorry for the confusion it caused.

5.0.0 RC 1 has just been released so this change won't make it into that.

**Comment by FooBarWidget** [comment]
@OnixGH Your turn. ;) This should be easy.
