### ISSUE TITLE
LoaderSharedHelpers.dump_system_metrics invokes ruby via /bin/env

### ISSUE THREAD

**Issue by jdollarda** [phusion/passenger#1381]
The dump_system_metrics method in LoaderSharedHelpers uses 'env' to set an environment variable and invoke passenger-config.  This results in errors being output if ruby isn't in your path, or if the ruby that's in your path cannot run the passenger-config script.

This method should presumably be using ruby from options['ruby'] instead.

**Comment by FooBarWidget** [comment]
This has been fixed. Thanks for reporting this.
