### ISSUE TITLE
Improve log readability by reducing file path strings

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger#1383]
The log contains: "agents/HelperAgent/RequestHandler/CheckoutSession.cpp:236", which could be shortened to for example: "a/H/R/CheckoutSession.cpp:236" to make the logs a lot more readable.
The filename by itself will usually be unique enough to know where to look anyway, and for the other cases there is the path shorthand.

**Comment by FooBarWidget** [comment]
I've commented on your change. Feel free to merge to master once you've addressed them.
