### ISSUE TITLE
Passenger has to be explicitly told the app concurrency

### ISSUE THREAD

**Issue by d-snp** [phusion/passenger#1384]
The current loader protocol requires the loader to advertise the concurrency. It's dependant on the amount of configured threads for Ruby apps and hardcoded to be infinity for Node.js apps.

Why can't the Passenger Helper Agent simply deduce the concurrency of an app by checking if the socket will accept another connection?

**Comment by FooBarWidget** [comment]
This is not possible. There is no way to reliably check for that.

**Comment by d-snp** [comment]
But the Passenger loader controls the socket implementation exposed to the application right? Can't we just make socket#accept signal te acceptance of a request?
