### ISSUE TITLE
RealIP Module with Phusion Passenger Standalone

### ISSUE THREAD

**Issue by bizmurr** [phusion/passenger#1389]
Continuing the conversation from: https://groups.google.com/forum/#!topic/phusion-passenger/aCb8k2ayTvM

I think this would be a very good thing to include by default, because you are most likely running Phusion Passenger Standalone behind a reverse proxy setup. It can also be helpful for users behind Heroku who are using a proxy-cdn like Cloudflare, rather than relying on Rack middleware implementation in their application to set the correct IP.

Cheers.

**Comment by FooBarWidget** [comment]
Marking for serious consideration for 5.0.2.

**Comment by FooBarWidget** [comment]
@OnixGH Can you take care of this?

**Comment by FooBarWidget** [comment]
Implemented in 5.0.11.

**Comment by OnixGH** [comment]
Using standalone via gem install downloads an Nginx binary that doesn't appear to be compiled with the RealIP module.
