### ISSUE TITLE
`passenger-config restart-app` should work if the user who invoked it is the same as the app's user

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1392]
Currently, `passenger-config restart-app` only works when invoked as root, because only root can read the control password. But this is very inconvenient when using Capistrano, because the administrator will have to setup sudo access. It should be possible to run restart-app without being root, as long as the app being restarted is running as the same user that invoked restart-app.

Since we're dealing with HTTP, it's not possible to send credentials over a Unix domain socket. Instead, we should use a challenge-response mechanism. The server should create a temp file that's owned by the app's user, chmodded 400 and with random contents. The client should send the contents of that file to the server as proof that it is indeed that user.

**Comment by hsyn** [comment]
Since you mentioned Capistrano, I also want to add one more thing. 

I added `passenger_min_instances` flag to production apps and did not add it to staging ones. It is really nice that passenger kills the instances that are not used. 

Now i can restart production apps with the new syntax. `passenger-config restart-app #{release_path}`

But this is throwing an error when I deploy staging apps, since `passenger_min_instances` is not set and app is not running, passenger thinks that there are no apps in the given path :/

`There are no Phusion Passenger-served applications running whose paths begin with '/var/www/staging/current'.`

Can't passenger actually start the app with the same restart command if it is not running?
Thanks for the great work btw! :+1:

**Comment by betesh** [comment]
:+1:

**Comment by FooBarWidget** [comment]
Actually, it might be possible to send Unix socket credentials over HTTP. Will investigate this.

**Comment by sauliusgrigaitis** [comment]
This is really a must feature for my sudoless deployments. Can't wait to get this feature shipped, so I can switch to new restart method.

**Comment by 9mm** [comment]
Definitely subscribing to this, I just encountered this.

**Comment by cjjuice** [comment]
+1 to this

**Comment by wiggly** [comment]
This would be a good thing to have working without requiring sudo, guess I'll keep touching tempfiles for now.

**Comment by FooBarWidget** [comment]
The change has been implemented in the `GH-1392` branch. It will be merged to `master` soon.

This change won't make it to 5.0.8, and probably won't make it to 5.0.9 either, because the change depends on a bunch of other refactoring-related changes which need more testing. I think it may land in 5.0.10.

**Comment by svoop** [comment]
Speaking for many here: Thanks a lot, @FooBarWidget !!

**Comment by FooBarWidget** [comment]
Aaand it's live: https://blog.phusion.nl/2015/06/11/phusion-passenger-5-0-10/

**Comment by supagroova** [comment]
Rock on! :+1:

**Comment by ahukkanen** [comment]
:+1:

**Comment by svoop** [comment]
I've just upped to 5.0.10 (on Nginx 1.7.6), but when I try `passenger-status` or `passenger-config restart-app` with the same owner and group as my Rails' app `config/environment.rb`, I still get:

    *** ERROR: You are not authorized to query the status for this Phusion Passenger instance. Please try again with 'sudo'.

I've also tried to set `passenger_user` and `passenger_group` explicitly in the vhost config, but the message remains the same. Am I missing something here?

**Comment by FooBarWidget** [comment]
@svoop Are you sure Passenger 5.0.10 is running? Did you restart Nginx after upgrading Passenger?

Also, which OS are you running? This feature is only supported on Linux, OS X and FreeBSD.

**Comment by svoop** [comment]
@FooBarWidget Yes, 5.0.10 is running – at least it's the sole version installed and configured in `nginx.conf`, `passenger-config about version` also reports 5.0.10. The OS is Gentoo Linux. However, I've seen this line in your commit:

    @instance.http_request("agents.s/server_admin", request)

I'm trying this on our staging which has both a htpasswd as well as some malicious agent filters installed. Maybe the request doesn't get through.

**Comment by svoop** [comment]
@FooBarWidget Got it. After restarting Nginx, I get the above authorization error. However, if I hit the (staging) application once, the admin tools work afterwards. Apparently, there's no instance running after an Nginx restart. (@hysin has mentioned this in a slightly different context above.)

**Comment by FooBarWidget** [comment]
Yeah, that's a known issue. No instances running is currently being confused with authorization error.

**Comment by svoop** [comment]
@FooBarWidget However, with `passenger_min_instances` and `passenger_pre_start` there should always be an instance, shouldn't it? (If so, there seems to be a problem with the prestarting on my staging box.)

**Comment by FooBarWidget** [comment]
Yes.

**Comment by svoop** [comment]
@FooBarWidget Figured it out: The prestarting doesn't work because I am filtering malicious agents, most notably such without an agent:

    # Block empty user agents
    if ($http_user_agent ~ ^\s*$) { return 400; }

The prestart request, however, is logged as follows:

    127.0.0.1 - - [11/Jun/2015:16:19:04 +0200] "HEAD / HTTP/1.1" 200 779 "-" "-" "-

So it doesn't get past the above rule. I'll open a separate issue for this, maybe it's possible to modify the prestart code so it passes an agent string.

**Comment by FooBarWidget** [comment]
@svoop This should fix the confusing passenger-status error: https://github.com/phusion/passenger/commit/cdb46b0db7771fa2d455674a5e6aed60a74b88e7
