### ISSUE TITLE
Nginx: better error message when PassengerAgent is not found

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1395]
When the PassengerAgent is not found, Nginx currently simply logs "[alert] 6646#0: Support binary PassengerAgent not found (-1: Unknown error)". This message should be improved.

**Comment by mpurham** [comment]
+1 Ran into this problem today and turns out that the location of passenger_root has changed. To fix the this issue I followed these [instructions](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#inserting_passenger_root_for_apt) from the passenger documentation.

**Comment by jamesrwhite** [comment]
+1. I ran into this after upgrading passenger on OSX as the directory name had changed from 5.0.2 to 5.0.5
