### ISSUE TITLE
Where is passenger_native_support.so installed?

### ISSUE THREAD

**Issue by dantman** [phusion/passenger#1396]
I would like to puppetize a run of `passenger-config build-native-support` so it's setup before starting any daemons. For that I need a `unless` or `onlyif` to ensure it doesn't run on every puppet run.

Where does `passenger_native_support.so` get installed? I've searched through all the lib folders, all the folders in `$:`, and even run `find` over all of `/usr` looking for `passenger_native_support.so`.

Ruby code to either return the directory that it is installed to, or test if it can be loaded would also be helpful.

I want to build a command like the one I use to test for the presence of the puppet agent:
```shell
/usr/bin/test -x $(/usr/local/rvm/bin/rvm 2.2@passenger do gem contents passenger --show-install-dir)/buildout/support-binaries/PassengerAgent
```
Or do things in the sysconfdir:
```shell
/usr/local/rvm/bin/rvm all do bash -c 'typeset __siteetc; __siteetc=$(ruby -rrbconfig -e "require \"etc\";puts Etc.sysconfdir"); ...'
```

**Comment by FooBarWidget** [comment]
It's installed in $PASSENGER_ROOT/buildout/ruby if it has write access there, or to ~/.passenger/native_support otherwise. But you do not have to add an `unless/only_if` clause. `passenger-config build-native-support` doesn't do anything if it's already built.

**Comment by dantman** [comment]
I know it doesn't do anything, but puppet is quirky. Even if it's more work leaving out the unless/only_if means puppet outputting an Exec[...] every time saying it thinks it is doing something.

Thanks, I'll try to find a way to automatically compute the 'x86_64-linux' part and write a test for it.

**Comment by dantman** [comment]
For anyone else doing this, this works:
```
test -e "$(passenger-config --root)/buildout/ruby/$(ruby -rphusion_passenger -e "PhusionPassenger.locate_directories; PhusionPassenger.require_passenger_lib 'platform_info/binary_compatibility'; puts PhusionPassenger::PlatformInfo.ruby_extension_binary_compatibility_id")/passenger_native_support.so"
```
