### ISSUE TITLE
Add Ubuntu 14.10 packages

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1400]

**Comment by duhast** [comment]
Hello @FooBarWidget !
What's the ETA for adding `utopic` packages?

**Comment by FooBarWidget** [comment]
That is not yet known. We're currently focusing on bug fixes. Once we've determined that there are no more critical bugs, we'll look at the packaging situation.

**Comment by duhast** [comment]
Thanks for the update.

**Comment by FooBarWidget** [comment]
We'll skip Utopic and go straight for Vivid.
