### ISSUE TITLE
passenger-status invalid JSON NaN values

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1408]
The output from `passenger-status --show=requests` in v5.0.1 can contain invalid JSON, if values are NaN.

Example:
```json
…
"turbocaching" : {
   "fetches" : 0,
   "hit_ratio" : nan,
   "hits" : 0,
   "store_success_ratio" : nan,
   "store_successes" : 0,
   "stores" : 0
}
…
```

Instead those `nan` values should be represented as `null` to comply with JSON.

Example JSON encoding using nodejs:
```javascript
> JSON.stringify(NaN)
'null'
```

**Comment by felixbuenemann** [comment]
This is probably better fixed by just guarding against division by zero.

**Comment by FooBarWidget** [comment]
You're right. This is what our JSON library generates. I guess we should check for this.
