### ISSUE TITLE
Turbocaching possible keep-alive bug

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1409]
It seems that thee logic in the code for keep alive is inverted from what the comments say. By looking at https://github.com/phusion/passenger/blob/c8706fbd1752954397033ea3ef3313302b64a70e/ext/common/agents/HelperAgent/RequestHandler/TurboCaching.h#L166 it seems that keep-alive is enabled with http/1.0 instead of http/1.1:

```cpp
		if (server->canKeepAlive(req)) {
			if (httpVersion < 1010) {
				// HTTP < 1.1 defaults to "Connection: close"
				PUSH_STATIC_STRING("Connection: keep-alive\r\n");
			}
		} else {
			if (httpVersion >= 1010) {
				// HTTP 1.1 defaults to "Connection: keep-alive"
				PUSH_STATIC_STRING("Connection: close\r\n");
			}
		}
```

**Comment by felixbuenemann** [comment]
Hmm, I guess I'm just misreading the code.

Am I right to assume that this enabled keep-alive on HTTP/1.0 if the client for some reason supports it?

**Comment by OnixGH** [comment]
@felixbuenemann I see how the comments can be confusing, but the code is correct.

The outer if { } is important: in case keep-alive is supported, we turn it on (which is only necessary for HTTP < 1.1 that defaults to Connection: close), and if keep-alive is not supported, we need to turn it off (which is only necessary for HTTP >= 1.1 that defaults to Connection: keep-alive)

**Comment by felixbuenemann** [comment]
Thanks, now the intention is clearer!
