### ISSUE TITLE
Possible filedescriptor leak/problem

### ISSUE THREAD

**Issue by nesrual** [phusion/passenger#1412]
After having upgraded to 5.0.2 (from the previous version 4.0.55) I am having a lot of issues with our setup. I use Nginx on Ubuntu and after having upgraded to 5.0.2 the servers starts to run out of file descriptors. Slowly the number of open files increases until Phusion passenger returns error messages and the servers will throw 50x errors. 

The applications are RoR apps, using Rails 2.1.5.

Reverting to 4.0.55 solves the problem.

**Comment by dmitry** [comment]
Do you have `config.ru` for your rails 2.1 application?

**Comment by FooBarWidget** [comment]
I don't think this is related to the Rails version. FD leaks indicate bugs in the core server.

**Comment by FooBarWidget** [comment]
The problem has been reproduced. We're working on a fix.

**Comment by FooBarWidget** [comment]
The problem has been solved now. We'll accumulate a few more bug fixes, then release 5.0.3 as soon as we can. Thanks for reporting this!
