### ISSUE TITLE
Error “can not convert nil into String” when trying to connect to mysql using mysql2 gem

### ISSUE THREAD

**Issue by andersonav91** [phusion/passenger#1415]
i use hostmonster as server hosting, apparently something was updated and for a while I can not access my application ROR (Redmine). The error is as follows:

Error message: can't convert nil into String

Exception class: TypeError

Application root: /home/XXXXXXXX/rails_apps/redmine

Backtrace:

File    Line    Location
0 /home/XXXXXXXXX/ruby/gems/gems/mysql2-0.3.13/lib/mysql2/client.rb 22 in `initialize_ext'

1 /home/XXXXXXXXX/ruby/gems/gems/mysql2-0.3.13/lib/mysql2/client.rb 22 in `initialize'

2 /home/XXXXXXXXX/ruby/gems/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb 16 in `new'

3 /home/XXXXXXXXX/ruby/gems/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb 16 in `mysql2_connection'

4 /home/XXXXXXXXX/ruby/gems/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb 315 in `new_connection'

5 /home/XXXXXXXXX/ruby/gems/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb 325 in `checkout_new_connection'

6 /home/XXXXXXXXX/ruby/gems/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb 247 in `block (2 levels) in checkout'

I have not the remotest idea that may be the problem, thank you very much for the help.

**Comment by FooBarWidget** [comment]
Sorry, but this issue is caused by something in the application or in one of the libraries it uses. It's not an issue caused by Passenger, so we cannot help you.
