### ISSUE TITLE
Response may not contain both Content-Length and Transfer-Encoding

### ISSUE THREAD

**Issue by sleewoo** [phusion/passenger#1416]
Trying to serve a file using `Rack::File`.

Not sure where it is adding Transfer-Encoding header, I traced headers upon [here](https://github.com/phusion/passenger/blob/9bba772a81126fca655c5e749f3c40f21450f4a5/lib/phusion_passenger/rack/thread_handler_extension.rb#L241)

headers look like `{"Content-Type"=>"image/gif", "Last-Modified"=>"Fri, 04 Jan 2008 22:25:01 GMT", "Content-Length"=>"268", "Content-Disposition"=>"inline"}` in `should_add_message_length_header `

so Transfer-Encoding is added later or [this conditional](https://github.com/phusion/passenger/blob/0f27be53c246e6ad206063bd6b3a6c23770ded24/ext/common/ServerKit/HttpHeaderParser.h#L370) is wrong.

Have to delete Content-Length header for now to work,
please advice,
thank you.

**Comment by FooBarWidget** [comment]
I'm not able to reproduce your problem using Rack::File. In thread_handler_extension.rb, we only add Content-Length/Transfer-Encoding if neither headers are set. Could you provide a reproducible test case?

**Comment by sleewoo** [comment]
ok, my bad, the issue is on my app, had to investigate this deeper before bothering :)
thank you.
