### ISSUE TITLE
Stable 5.0 with perl_modules nginx support

### ISSUE THREAD

**Issue by ryanrussell** [phusion/passenger#1419]
Hi, I'm having a difficult time getting stable-5.0 to install nginx with rewrite rules using perl_modules.

Normally, I would just use apt-get install nginx-extras and I'm good to go. Also, I'm attempting to wrap this in a chef recipe, so it needs to be automated.

So, I tried adding in all of the flags that I get from "nginx -V" after doing an nginx-extras install. 
```
/tmp/passenger/bin/passenger-install-nginx-module --auto --prefix=/opt/nginx --auto-download --languages ruby,python,nodejs --extra-configure-flags="--conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-ipv6 --with-mail --with-mail_ssl_module" --force-colors 
```
This seems to fail on flag after flag:

So I singled it down to a module I absolutely have to have(perl_modules for rewrite), and It still fails.
```
/tmp/passenger/bin/passenger-install-nginx-module --auto --prefix=/opt/nginx --auto-download --languages ruby,python,nodejs --extra-configure-flags="--with-http_perl_module" --force-colors 
```

Here's what I get after attempting the install:
```
	-lpthread -lcrypt /tmp/passenger/buildout/common/libpassenger_common/Logging.o /tmp/passenger/buildout/common/libpassenger_common/Exceptions.o /tmp/passenger/buildout/common/libpassenger_common/Utils/SystemTime.o /tmp/passenger/buildout/common/libpassenger_common/Utils/StrIntUtils.o /tmp/passenger/buildout/common/libpassenger_common/Utils/StrIntUtilsNoStrictAliasing.o /tmp/passenger/buildout/common/libpassenger_common/Utils/IOUtils.o /tmp/passenger/buildout/common/libpassenger_common/Utils.o /tmp/passenger/buildout/common/libpassenger_common/AgentsStarter.o /tmp/passenger/buildout/common/libpassenger_common/ApplicationPool2/AppTypes.o /tmp/passenger/buildout/common/libpassenger_common/Utils/CachedFileStat.o /tmp/passenger/buildout/common/libpassenger_common/agents/LoggingAgent/FilterSupport.o /tmp/passenger/buildout/common/libboost_oxt.a -lstdc++ -lpthread -lm -lrt /tmp/passenger.1m1seki/pcre-8.34/.libs/libpcre.a -lssl -lcrypto -ldl -lz \
	-Wl,-E -fstack-protector -L/usr/local/lib -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lc -lcrypt
/usr/bin/ld: cannot find -lperl
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/tmp/passenger.1m1seki/nginx-1.6.2'
make: *** [build] Error 2
```
This is on ubuntu 14.04 if that matters.

I appreciate any help. I'm sure it's something obvious, but I can't figure it out.

**Comment by FooBarWidget** [comment]
It's strange that all those the extra flags fail. Could you post the output of the failure? It seemed like you wanted to post the output, but forgot to paste them in your report.

The second error, "cannot find -lperl", indicates that libperl is not installed. Where is libperl.so located in your system?

**Comment by ryanrussell** [comment]
Absolutely. I started removing the packages one by one, until I realized they were all failing.

root@ubuntu-etl-workstation:/etc/nginx/html# ldd `which perl`
	linux-vdso.so.1 =>  (0x00007ffff6f98000)
	libperl.so.5.18 => /usr/lib/libperl.so.5.18 (0x00007fa0c8328000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa0c7f60000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa0c7d58000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa0c7a50000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa0c7830000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fa0c75f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa0c86d8000)

I'm not sure what I need to do to correct this. Can you please point me in the right direction?

In regards to the first install attempt with all of the arguments from "nginx -V", The original install attempt was:
"--conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_perl_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_spdy_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_xslt_module --with-ipv6 --with-mail --with-mail_ssl_module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/headers-more-nginx-module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-auth-pam --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-cache-purge --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-dav-ext-module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-development-kit --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-echo --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/ngx-fancyindex --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-http-push --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-lua --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-upload-progress --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-upstream-fair --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/passenger/ext/nginx"

Remove:
./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/headers-more-nginx-module/config was found
 --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/headers-more-nginx-module
./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/nginx-auth-pam/config was found
 --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-auth-pam
./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/nginx-cache-purge/config was found
--add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-cache-purge 
./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/nginx-dav-ext-module/config was found
--add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-dav-ext-module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-development-kit --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-echo --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/ngx-fancyindex --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-http-push --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-lua --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-upload-progress --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-upstream-fair --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/passenger/ext/nginx

All of the add-module flags create an error like the following. I removed them one by one until I realized what was going on...

./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/headers-more-nginx-module/config was found
 So I removed: --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/headers-more-nginx-module
./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/nginx-auth-pam/config was found
 So I removed: --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-auth-pam
./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/nginx-cache-purge/config was found
So I removed: --add-module=/tmp/buildd/nginx-1.6.2/debian/modules/nginx-cache-purge 
./configure: error: no /tmp/buildd/nginx-1.6.2/debian/modules/nginx-dav-ext-module/config was found

And the pattern continues...

Thanks for any help!

**Comment by FooBarWidget** [comment]
Ok, I see. You can't just paste the 'nginx -V' flags and expect that to work. The packages supplied by Debian are built in a very specific environment with specific paths. Unless you mimic that environment one-on-one, you can't use the same flags. At the very least you'll have to modify the paths.

Anyway, let's concentrate on the Perl linking problme. I see you have /usr/lib/libperl.so.5.18. But do you also have /usr/lib/libperl.so? Without the .5.18 suffix.

**Comment by ryanrussell** [comment]
Yes, sorry. 

root@ubuntu-etl-workstation:/# find / -name 'libperl.so'
/usr/lib/libperl.so

**Comment by FooBarWidget** [comment]
That's strange, it should work. Can you pass --with-ld-opt=-L/usr/lib to the Nginx configure script and check whether that works?

**Comment by FooBarWidget** [comment]
@ryanrussell Have you had any luck with the tip I gave you last time?

**Comment by OnixGH** [comment]
No feedback received, assuming resolved.
