### ISSUE TITLE
SERVER_PORT is always 80 for https on port 443 (passenger 5.0.2, apache/nginx)

### ISSUE THREAD

**Issue by tomhughes** [phusion/passenger#1421]
Moving to passenger 5.x with apache seems to have caused `@env['SERVER_PORT']` to always be `80` regardless of what port the request was actually received on.

This in turn causes attempts to verify OAuth signed requests to fail because the wrong URL is used when verifying the signature.

**Comment by FooBarWidget** [comment]
@OnixGH Up for a challenge? ;)

**Comment by tomhughes** [comment]
I didn't manage to figure out exactly where it's going wrong, but verified the above by sticking logging statements in Rack::Request#port to see where it was getting the port from.

https://github.com/openstreetmap/openstreetmap-website/commit/88f8544d8cbf8ef099a5df9be85dcbcec300a013 is my current workaround.

**Comment by OnixGH** [comment]
@tomhughes thanks for the heads up. The problem does not appear in a simple setup (passenger 5.0.1 or 5.0.2, apache 2.4.7 set to Listen on port 80 and 3000, a VirtualHost config for each of those ports, and rendering env['SERVER_PORT'] from a ruby app controller shows 80 and 3000 correctly).

Can you post some details on the setup you are seeing the problem in?

**Comment by tomhughes** [comment]
https://gist.github.com/tomhughes/ac254f04c1a451e61742 is the apache configuration file - this is all on Ubuntu 14.04 with apache 2.4.7.

**Comment by tomhughes** [comment]
Our full rack middleware stack is:

```
use Rack::Sendfile
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x000000024ed228>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActionDispatch::Cookies
use ActionDispatch::Session::MemCacheStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use HttpAcceptLanguage::Middleware
use OpenStreetMap::Cors
use OAuth::Rack::OAuthFilter
use OmniAuth::Builder
run OpenStreetMap::Application.routes
```

The problem was originally noticed because it was causing `OAuth::Rack::OAuthFilter` to build incorrect URLs when validating OAuth signatures and I then added logging calls to Rack::Request to find out where port was coming from.

**Comment by tomhughes** [comment]
I've taken one of out servers out of production for now, switched it back to passenger 5, and added a render of `request.env['SERVER_PORT']` to the top bar - you can see it at https://spike-03.openstreetmap.org/ and you'll see it says 80 no matter whether you use http or https.

**Comment by OnixGH** [comment]
Perhaps a silly check, but I see you're using 5.0.2 through apt: did you fully stop and start apache after installing (reload doesn't work reliably - #1423)?

**Comment by tomhughes** [comment]
Yes I discovered that reload doesn't work reliably myself ;-) As in it completely broke the site, so yes a full restart was done.

**Comment by tomhughes** [comment]
Hmm that is claiming that even `service apache2 restart` is not enough? That doesn't seem to square with the explanation about dlopen though?

**Comment by tomhughes** [comment]
I've now done a stop, checked that no apache's are running, and then started again and that makes no difference.

**Comment by OnixGH** [comment]
Thanks for the quick responses! I'm going through your configs and trying to replicate it somehow, this will take some time.

Just noticed something small and probably unrelated, you are PassengerPreStart-ing http://www.openstreetmap.org/ in your https VirtualHost section, this should probably be https://www.openstreetmap.org/

**Comment by tomhughes** [comment]
I actually removed the PreStart from the live server already to see if that fixed it, but you're quite right of course.

**Comment by OnixGH** [comment]
Update: the problem has been reproduced, now diving into the code!

**Comment by stevenhaddox** [comment]
I'm so excited to see this fix. Hopefully it'll fix the same issue I posted to the google group precisely a week ago! Thanks for all your hard work as always!

**Comment by OnixGH** [comment]
@stevenhaddox looks very similar indeed, please try 5.0.4 and don't hesitate to let us know if you still experience it or any other issues.
