### ISSUE TITLE
nginx/passenger returns 503 on long running request

### ISSUE THREAD

**Issue by sr3d** [phusion/passenger#1426]
I have a standard nginx / Passenger setup for a Rails 4 app.  Sometimes there is a request that will take a lot of compute (30s+ to complete), nginx would very quickly return 503.  I already use background jobs to process heavy stuff, but these particular pages need to be calculated live.  So far I have not been able to find out how to increase the timeout for passenger/nginx so that nginx would wait longer until passenger returns the results.  

So which settings in passenger or nginx should be used to increase the execution timeout?

Thanks!

**Comment by dmitry** [comment]
@sr3d looks like you have to compile nginx passenger module in a special way: https://github.com/phusion/passenger/blob/dfa66db02599d1645bd313c8a03cf9eb3207caa8/lib/phusion_passenger/config/compile_nginx_engine_command.rb#L87

**Comment by proigor** [comment]
What if I have same issue, but using passenger with apache?
I'm seeing errors like this:
[ 2015-03-12 05:59:20.3009 3549/7fe3a110c700 agents/HelperAgent/Main.cpp:724 ]: Disconnecting long-running connections for process 3100, application /u/apps/mth/current#default

**Comment by FooBarWidget** [comment]
Passenger [sets the internal Nginx timeout to 3 hours](https://github.com/phusion/passenger/blob/release-5.0.4/ext/nginx/Configuration.c#L490-L497), so it's strange that your requests timeout in only 30 seconds. Are you sure it's Passenger+Nginx that is enforcing the timeout? If you're on Heroku, the Heroku router will enforce a 30 seconds timeout. Similarly, if you have another Nginx layer in front of Nginx+Passenger, then maybe that Nginx layer in front is enforcing the timeout.

@dmitry The code snippet that you're looking at has got nothing to do with how Nginx is compiled. What you're looking at is the *download timeout* for the Nginx source tarball.

@proigor The message you're seeing is not an error, and is not related to the original issue reported by @sr3d. That message is simply an informational message, which is triggered when you restart your app.

**Comment by dmitry** [comment]
@FooBarWidget oh yep, my quick glance was wrong.

@sr3d checkout this option https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerMaxRequestTime
May be you have set it in your nginx.conf?

**Comment by proigor** [comment]
@FooBarWidget I see, thank you.

**Comment by FooBarWidget** [comment]
@sr3d Have you been able to find out more about your issue?

**Comment by OnixGH** [comment]
This doesn't seem to be a Passenger issue.
