### ISSUE TITLE
Move away from libeio to libuv

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1428]
Libeio has a number of design flaws so we must move away from it. It looks like libuv is a good candidate to move to.

**Comment by clemensg** [comment]
That would be great. libuv could replace libeio and libev!

**Comment by FooBarWidget** [comment]
No, we'll keep libev and only replace libeio. It is unlikely that libuv can achieve the performance we need. It performs too many memory allocations, which are necessary in order to make it compatible with Windows, but unnecessary on Unix. Passenger doesn't support Windows anyway.

**Comment by clemensg** [comment]
Did you benchmark that?

It's a pity that Boost.Asio does not support regular files.

**Comment by FooBarWidget** [comment]
No, this is just a guess. But we spent a lot of effort in Passenger 5 to minimize dynamic memory allocations, and using libuv would undo all that effort.

Another issue is libuv has a totally different I/O model than what we now use with libev, so switching fully to libuv requires major rewrites.

In the early days I considered asio, but found its API to be too inwieldly. Asio also requires the use of boost::bind and boost::function in many places. These have significant overhead unless compiled with optimizations; and we often do not compile with optimizations for ease of debugging.

**Comment by clemensg** [comment]
I see. Thanks for the explanation.

Using POSIX AIO would also be interesting. Especially on FreeBSD. Linux and OS X support it too, but if I remember correctly there were certain drawbacks with that API.

**Comment by FooBarWidget** [comment]
POSIX AIO has too many drawbacks to be a viable option for me. This blog post describes it best: http://blog.libtorrent.org/2012/10/asynchronous-disk-io/

Unfortunately, there is nothing better than plain old non-blocking sockets + event poller for socket I/O, and a thread pool for file I/O.

**Comment by FooBarWidget** [comment]
Initial work on this has been completed. A few known issues remain:

 * Does not compile on Ubuntu 14.04 because of conflicting uint64_t definitions (one in libuv, one in boost/cstdint.hpp).
 * All agents use 100% CPU.

**Comment by FooBarWidget** [comment]
Merged into stable-5.0.

**Comment by clemensg** [comment]
By the way: I see you are using libuv 1.4.2. Many important fixes found their way into the current stable release 1.5.0. (released about two weeks ago)

**Comment by FooBarWidget** [comment]
I'll take a look. Thanks.
