### ISSUE TITLE
Apps sharing same domain name will not be killed after 300 seconds 

### ISSUE THREAD

**Issue by hsyn** [phusion/passenger#1429]
I installed Passenger-5.01+ Nginx on Ubuntu 14 and 8+ applications running ruby 2.1.x.

I have 2 versions of same app (staging,production) for each application.

Staging version of the app has this line in its nginx config -->  `server_name staging.app1.com`
Production version of the app has this line --> `server_name app1.com`
Production version has also this line --> `passenger_min_instances 1;`

The problem is, staging app is never killed after default 300 seconds and I am guessing that It is because they are sharing the same domain name?

**Comment by FooBarWidget** [comment]
Since Passenger 4, passenger_min_instances defaults to 1. So the `passenger_min_instances 1` you specified for your production version is actually redundant.

Also, I strongly recommend upgrading to 5.0.4 which fixes a number of issues found in 5.0.1.
