### ISSUE TITLE
Passenger 5.0.4 ubuntu packages don't upgrade cleanly from 4.0.59

### ISSUE THREAD

**Issue by pedrocr** [phusion/passenger#1434]
I've been using the https://oss-binaries.phusionpassenger.com/apt/passenger repository to upgrade. Today I upgraded two Ubuntu trusty servers from 4.0.59 to 5.0.4. In both cases after upgrading and restarting apache2 passenger initialization failed with:

```
[Sat Mar 14 19:56:32.370959 2015] [passenger:error] [pid 3891] *** Passenger could not be initialized because of this error: Option 'agents_dir' missing in file '/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini'
```

After googling this was fixed by doing "apt-get install --reinstall passenger". This should mostly be a no-op but it seems something is not being correctly done on upgrade that is indeed done on a fresh install.

**Comment by FooBarWidget** [comment]
You need to restart Apache/Nginx, as in a full 'stop' and then 'start'. By default, apt-get only *reloads* the web servers, which isn't enough. This is documented in [the upgrade notes](https://blog.phusion.nl/2015/03/04/phusion-passenger-5-0-1-released/#upgrade_notes).
