### ISSUE TITLE
Using Thin and Passenger

### ISSUE THREAD

**Issue by Ap0ph1s** [phusion/passenger#1438]
I have the simple Sinatra chat demo from their repository with a few modifications:

https://gist.github.com/Ap0ph1s/c5183758645b6a5b3683

and I have a Reverse Proxy setup with Passenger.

The problem is that when I run the app, None of my messages send, which seems to be that Thin isn't being used. Unless There is a very simple tutorial on how to set-up this app with Thin on Nginx(Googling shows lots of tutorials that are big hassles/not What I want) I want to know if its possible to run Passenger and Thin at the same time(Thin via the actual gem).

This is what I need:
App listen on 0.0.0.0:80 on chat.stackin.money
root of the folder is /var/www/chat/public;

**Comment by FooBarWidget** [comment]
I can't reproduce your issue.

But it's strange that your app tries to reference Rack::Request::SCRIPT_NAME. SCRIPT_NAME is defined in the 'Rack' module, in rack.rb.

What happens if you insert a 'require "rack"' in your config.ru? Does that help?

Which exact Ruby version are you running?

**Comment by Ap0ph1s** [comment]
@FooBarWidget I tried recreating my app step by step and try to find the cause of the error, so Im going to mark it as resolved for now, but I updated the original issue to a new one that may be doable.

**Comment by Ap0ph1s** [comment]
Is this possible in the first place?

**Comment by FooBarWidget** [comment]
No, you can't use Thin and Passenger at the same time. But why would you want to? Why not just run the app completely on Passenger?

**Comment by Ap0ph1s** [comment]
I dont know how it would work, I think Thin uses eventmachine which the chat app uses so it can be real-time. Do you know how you can make the chat work with only passenger?

**Comment by FooBarWidget** [comment]
Use can use something like faye-websocket. It doesn't use EventMachine but instead uses some other mechanism which works well with Passenger. https://github.com/faye/faye-websocket-ruby#running-the-app-with-passenger
