### ISSUE TITLE
StrIntUtils.cpp:204: array index used before sanity check ?

### ISSUE THREAD

**Issue by dcb314** [phusion/passenger#1441]
StrIntUtils.cpp:204]: (style) Array index 'i' is used before limits check.

   while (data[i] == ' ' && i < str.size()) {

Looking at the bigger picture, it seems to me that the entire stringToUnsignedNumeric
could be replaced by a call into the standard C or C++ library.

**Comment by FooBarWidget** [comment]
You're right. The size check should come before the content check. Thanks for spotting this.

stringTo(Un)signedNumeric cannot be replaced by atoi or a similar standard library call, because atoi and family requires NULL-terminated strings. stringTo(Un)signedNumeric is designed to work with strings that have no termination character.

**Comment by dcb314** [comment]
>stringTo(Un)signedNumeric cannot be replaced by atoi or a similar standard library call, because atoi >and family requires NULL-terminated strings.

Sounds like nonsense to me. Your local variable "data" is a NULL terminated string.

Are you new to C programming ? It looks to me like you are making a newbie error.

**Comment by FooBarWidget** [comment]
dcb314, I appreciate your contribution, but I would prefer it if you refrain from such insinuations.

'data' is a char *, but it is not a NULL-terminated string. It is a pointer to an array of chars which may or may not be not terminated by a nul. For example, the input may be a substring of another string, or it may refer to a network data buffer which has no termination character.

**Comment by FooBarWidget** [comment]
Note that the input 'str' is a StaticString, which is our own lightweight wrapper around a 'char *' with a size field. If you 'str' is an std::string and if I called 'str.c_str()' instead of 'str.data()', then you would have been right.

**Comment by d-snp** [comment]
Hi @dcb314, I noticed that you've reported a lot of issues to C projects on github, how did you come across Passenger? Are you a user? Did you find the bug reading through the source or did you use a static analysis tool?
