### ISSUE TITLE
Changing Ruby versions

### ISSUE THREAD

**Issue by Ap0ph1s** [phusion/passenger#1448]
I did not use the command 'passenger-install-nginx-module' as I was led to use this way of setting up Nginx + Passenger instead(Step 5):

https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-passenger-and-nginx-on-ubuntu-14-04

So I was asking how I can change the Ruby version of passenger as a whole with this set-up, as everything runs fine, I just need to update the ruby version up to 2.2.0.

**Comment by FooBarWidget** [comment]
If you want Passenger to use a different Ruby version, just change the `passenger_ruby` config option.

Which Ruby you used to install Passenger, is not important. See https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#relationship_with_ruby
