### ISSUE TITLE
node.js stdout/stderr stops being logged to nginx error.log after logrotate

### ISSUE THREAD

**Issue by NeoPhi** [phusion/passenger#1450]
We have a daily logrotation configuration that sends a kill -USR1 to nginx after rotating the log files. If a node.js application is logging to stdout or stderr messages are not written to the new log file unless nginx is restarted.

**Comment by FooBarWidget** [comment]
That's because sending SIGUSR1 to Nginx only makes *Nginx* reopen it logs. You also need to tell Passenger to reopen the logs. You can do that by running `passenger-config reopen-logs`.

**Comment by NeoPhi** [comment]
Thank you, I missed that in the release notes.
