### ISSUE TITLE
An internal error occurred while trying to spawn the application.

### ISSUE THREAD

**Issue by proigor** [phusion/passenger#1451]
Hi!

What does it error mean?

An internal error occurred while trying to spawn the application. Exception type: Passenger::RuntimeException Error message: Support binary PassengerAgent not found Backtrace: in 'void Passenger::ApplicationPool2::SmartSpawner::startPreloader()' (SmartSpawner.h:205) in 'virtual Passenger::ApplicationPool2::SpawnObject Passenger::ApplicationPool2::SmartSpawner::spawn(const Passenger::ApplicationPool2::Options&)' (SmartSpawner.h:750) in 'void Passenger::ApplicationPool2::Group::spawnThreadRealMain(const SpawnerPtr&, const Passenger::ApplicationPool2::Options&, unsigned int)' (Implementation.cpp:1038)

**Comment by OnixGH** [comment]
Hi @proigor, when posting an issue please also post the details of your setup, what version, what server (apache or nginx or standalone) and config file(s) so we can help you.

The error means what it reads: PassengerAgent was not found. The passenger root setting in your configuration controls where it searches for the PassengerAgent.

**Comment by proigor** [comment]
It looks like today's morning I tried to install latest passenger via 'gem install' but it still installs 5.0.4.
Later today after restart it stops working. Looks like it re-isntalled 5.0.4 and crashed apache config, i.e. can't find passenger modules

**Comment by FooBarWidget** [comment]
proigor, can you post your Apache/Nginx configuration?

**Comment by proigor** [comment]
I've re-run passenger-install-apache module and it is now working again.
Most probably I shouldn't run gem install passenger, because it may re-install and remove buildout directory.

Please, let me know if you still need any info from me, otherwise you may close this issue if you think it's due to my own mistake.

**Comment by FooBarWidget** [comment]
That is correct. You must run passenger-install-apache2-module after 'gem install'. If you do it the other way around, 'gem install' will remove the built binaries.
