### ISSUE TITLE
Passenger standalone not terminating properly when running under foreman

### ISSUE THREAD

**Issue by jcn** [phusion/passenger#1454]
I am running Passenger and Sidekiq under foreman in development:

```
web: bundle exec passenger start -p $PORT --max-pool-size ${WEB_CONCURRENCY:-3} --environment ${RAILS_ENV:-production}
worker: env LIBRATO_AUTORUN=1 bundle exec sidekiq -e $RAILS_ENV
```

This is the behavior that I see when I start foreman the first time, which is expected, and then I terminate foreman with ctrl-c:

```
$ bundle exec foreman start
09:35:47 web.1    | started with pid 42733
09:35:47 worker.1 | started with pid 42734
09:35:48 web.1    | =============== Phusion Passenger Standalone web server started ===============
09:35:48 web.1    | PID file: /Users/jcn/src/app/web/tmp/pids/passenger.5000.pid
09:35:48 web.1    | Log file: /Users/jcn/src/app/web/log/passenger.5000.log
09:35:48 web.1    | Environment: development
09:35:48 web.1    | Accessible via: http://0.0.0.0:5000/
09:35:48 web.1    | 
09:35:48 web.1    | You can stop Phusion Passenger Standalone by pressing Ctrl-C.
09:35:48 web.1    | Problems? Check https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#troubleshooting
09:35:48 web.1    | ===============================================================================
09:42:04 worker.1 | 2015-03-25T13:42:04.067Z 42949 TID-oxvuhp5nc INFO: Booting Sidekiq 3.3.2 with redis options {:size=>5, :namespace=>"app-sidekiq"}
09:42:06 worker.1 | 2015-03-25T13:42:06.001Z 42949 TID-oxvuhp5nc INFO: Running in ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin12.0]
09:42:06 worker.1 | 2015-03-25T13:42:06.001Z 42949 TID-oxvuhp5nc INFO: See LICENSE and the LGPL-3.0 for licensing details.
09:42:06 worker.1 | 2015-03-25T13:42:06.001Z 42949 TID-oxvuhp5nc INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
09:42:06 worker.1 | 2015-03-25T13:42:06.001Z 42949 TID-oxvuhp5nc INFO: Starting processing, hit Ctrl-C to stop
^CSIGINT received
09:35:58 system   | sending SIGTERM to all processes
09:35:58 web.1    | terminated by SIGTERM
09:36:00 worker.1 | exited with code 0
```

But it appears that passenger is still running:

```
$ ps aux | grep passenger
jcn            42834   0.0  0.0  2424576    412 s011  R+    9:37AM   0:00.00 grep passenger
jcn            42749   0.0  0.0  2439020    244   ??  Ss    9:35AM   0:00.00 /Users/jcn/.passenger/support-binaries/5.0.5/PassengerAgent temp-dir-toucher /var/folders/n_/r66y_v855y33hjp9g38tmllh0000gn/T/passenger-standalone.9zi76k --cleanup --daemonize --pid-file /var/folders/n_/r66y_v855y33hjp9g38tmllh0000gn/T/passenger-standalone.9zi76k/temp_dir_toucher.pid --log-file /Users/jcn/src/app/web/log/passenger.5000.log
jcn            42746   0.0  0.0  2436372    316   ??  Ss    9:35AM   0:00.00 nginx: master process /Users/jcn/.passenger/support-binaries/5.0.5/nginx-1.6.2 -c /var/folders/n_/r66y_v855y33hjp9g38tmllh0000gn/T/passenger-standalone.9zi76k/nginx.conf -p /var/folders/n_/r66y_v855y33hjp9g38tmllh0000gn/T/passenger-standalone.9zi76k    
```

When I go to start foreman again, the process of starting passenger kills the still-running passenger process:

```
$ bundle exec foreman start
09:38:00 web.1    | started with pid 42870
09:38:00 worker.1 | started with pid 42871
09:38:01 web.1    | Phusion Passenger Standalone is already running on PID 42746.
09:38:01 web.1    | Stopping web server... done
09:38:01 web.1    | exited with code 1
09:38:01 system   | sending SIGTERM to all processes
09:38:01 worker.1 | terminated by SIGTERM
```

And then running `foreman start` again starts the app up normally.

This seems possibly related to https://github.com/phusion/passenger-ruby-heroku-demo/issues/3

Passenger 5.0.5
Foreman 0.77
OS X 10.8.5
Ruby 2.2.0
Rails 4.2

**Comment by FooBarWidget** [comment]
Maybe the bug is back. After all, we gave Passenger Standalone a major overhaul in version 5.

**Comment by fabn** [comment]
Having the same issue here.

**Comment by karlsvec** [comment]
I have a similar issue with Passenger 5.0.6 from the APT repository on Ubuntu 14.04 LTS.

I'm using Upstart to control Passenger standalone rather than foreman. Unlike @jcn, I don't have any problems with the main Passenger process being shut down cleanly. In my case, Passenger standalone just leaves a stray `temp-dir-toucher` agent process behind that must be killed separately.

    root@opsworks-vagrant:/home/vagrant# start passenger
    passenger start/running, process 13627
    root@opsworks-vagrant:/home/vagrant# ps aux | grep passenger
    root     13627  0.2  0.3 122836 15268 ?        Ssl  21:41   0:00 ruby /usr/bin/passenger start --engine=builtin --socket=/var/run/passenger/passenger.sock --min-instances=1 --max-pool-size=9 --user=nobody --log-file=/dev/null --pid-file=/var/run/passenger/passenger.pid --environment=web_development --no-friendly-error-pages
    root     13661  0.0  0.0 100392  2484 ?        Ss   21:41   0:00 /usr/lib/passenger/support-binaries/PassengerAgent temp-dir-toucher /tmp/passenger-standalone.njy16j --cleanup --daemonize --pid-file /tmp/passenger-standalone.njy16j/temp_dir_toucher.pid --log-file /dev/null

    root@opsworks-vagrant:/home/vagrant# stop passenger
    passenger stop/waiting
    root@opsworks-vagrant:/home/vagrant# ps aux | grep passenger
    root     13661  0.0  0.0 100392  2484 ?        Ss   21:41   0:00 /usr/lib/passenger/support-binaries/PassengerAgent temp-dir-toucher /tmp/passenger-standalone.njy16j --cleanup --daemonize --pid-file /tmp/passenger-standalone.njy16j/temp_dir_toucher.pid --log-file /dev/null

**Comment by fusion2004** [comment]
I am seeing the exact issue described by @jcn.

**Comment by OnixGH** [comment]
@jcn @FooBarWidget indeed the code for trapping one extra INT/TERM during shutdown disappeared after what looks like a refactor. I re-integrated it with better indications of why it is needed, and it works for me with double CTRL-C.

If anyone wants to try it in Foreman (and maybe @karlsvec with upstart?), the fixed branch is [GH-1454](https://github.com/phusion/passenger/tree/GH-1454).

**Comment by karlsvec** [comment]
I tried the GH-1454 branch, and unfortunately it does not resolve my issue with the `temp-dir-toucher` agent process not being shut down properly.

For reference, here is the Upstart config I'm using to start Passenger:
```
description "Passenger web application server"

start on (local-filesystems and net-device-up IFACE!=lo)
stop on stopping network-services

respawn

kill signal SIGINT

chdir /opt/webapp/deploy/current

console log

env PASSENGER_SOCKET=/var/run/passenger/passenger.sock
env PASSENGER_PID=/var/run/passenger/passenger.pid
env PASSENGER_LOG=/dev/null
env PASSENGER_MIN_INSTANCES=1
env PASSENGER_MAX_POOL_SIZE=9
env PASSENGER_USER=nobody
env PASSENGER_FRAMEWORK_ENV=web_development
env PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0
env PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0

pre-start script
    if [ ! -d "/var/run/passenger" ]
    then
        install -o $PASSENGER_USER -d /var/run/passenger
    fi
end script

exec /usr/local/rvm/wrappers/default/passenger start --engine=builtin \
                         --socket=$PASSENGER_SOCKET \
                         --min-instances=$PASSENGER_MIN_INSTANCES \
                         --max-pool-size=$PASSENGER_MAX_POOL_SIZE \
                         --user=$PASSENGER_USER \
                         --log-file=$PASSENGER_LOG \
                         --pid-file=$PASSENGER_PID \
                         --environment=$PASSENGER_FRAMEWORK_ENV \
                         --no-friendly-error-pages

# "pre-warm" the Passenger app by sending an HTTP HEAD request
post-start script
    until /bin/echo -e "HEAD / HTTP/1.1\r\n" | nc -U $PASSENGER_SOCKET; do
        sleep 1
    done
end script
```

Passenger starts normally:
```
# start passenger
passenger start/running, process 18758
# ps aux | grep -i passenger
root     18758  1.8  0.7 159560 29236 ?        Ssl  16:35   0:00 ruby /usr/local/rvm/gems/ruby-2.1.1/bin/passenger start --engine=builtin --socket=/var/run/passenger/passenger.sock --min-instances=1 --max-pool-size=9 --user=nobody --log-file=/dev/null --pid-file=/var/run/passenger/passenger.pid --environment=web_development --no-friendly-error-pages
nobody   18773  0.0  0.1 380224  6136 ?        Ssl  16:35   0:00 PassengerAgent watchdog
nobody   18775  0.1  0.2 808352 11084 ?        Sl   16:35   0:00 PassengerAgent server
nobody   18781  0.0  0.2 240440  9372 ?        Sl   16:35   0:00 PassengerAgent logger
root     18792  0.0  0.0 100392  2512 ?        Ss   16:35   0:00 /usr/local/rvm/gems/ruby-2.1.1/gems/passenger-5.0.7/buildout/support-binaries/PassengerAgent temp-dir-toucher /tmp/passenger-standalone.ugsfd8 --cleanup --daemonize --pid-file /tmp/passenger-standalone.ugsfd8/temp_dir_toucher.pid --log-file /dev/null
nobody   18801 25.4  3.6 946508 146608 ?       Sl   16:35   0:02 Passenger AppPreloader: /opt/webapp/deploy/releases/88c37fac63568fb0999244340f09f6ee717e7800
nobody   18820 10.8  3.9 1017664 158372 ?      Sl   16:35   0:00 Passenger RubyApp: /opt/webapp/deploy/releases/88c37fac63568fb0999244340f09f6ee717e7800
```

...but when stopped, still leaves a stray `temp-dir-toucher` agent process behind:
```
# stop passenger
passenger stop/waiting
# ps aux | grep -i passenger
root     18792  0.0  0.0 100392  2512 ?        Ss   16:35   0:00 /usr/local/rvm/gems/ruby-2.1.1/gems/passenger-5.0.7/buildout/support-binaries/PassengerAgent temp-dir-toucher /tmp/passenger-standalone.ugsfd8 --cleanup --daemonize --pid-file /tmp/passenger-standalone.ugsfd8/temp_dir_toucher.pid --log-file /dev/null
```

**Comment by OnixGH** [comment]
@jcn @fabn @fusion2004 the fix is now part of the latest [stable 5.0 branch ](https://github.com/phusion/passenger/tree/stable-5.0) so you can try that (or wait for the official 5.0.7 release).

**Comment by OnixGH** [comment]
@karlsvec if you would be so kind to continue in a new issue, yes. It was a pretty specific regression and if this one gets confirmed fixed for foreman we can focus on upstart in the other one.

**Comment by jerryclinesmith** [comment]
For those who might be new to Passenger (like me), you can simply stop passenger manually.  This will clear the PID file and let you restart via foreman:

```
passenger stop --port <port you're using>
```

**Comment by tcocca** [comment]
I am still seeing this issue with Passenger Enterprise 5.0.28, if I run passenger start with sudo (required) and pass the --user option, when we call passenger stop the temp-dir-toucher is still running after everything else has stopped.  Does anybody else have this same issue? Is there a fix?

**Comment by OnixGH** [comment]
@tcocca the temp-dir-toucher is a separate issue #1678 (as I've think you've already discovered), so I'll leave this closed.
