### ISSUE TITLE
Debian passenger standalone: Failed to fetch binary-amd64/Packages. returned error: 403

### ISSUE THREAD

**Issue by roma86** [phusion/passenger#1458]
Hello.

I follow the [guide] (https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#install_on_debian_ubuntu) for Debian and Ubuntu.

My server is (Debian GNU/Linux 7.8 (wheezy))

I stack on the 2.3.1 step. 

```
sudo apt-get update

...
Ign https://oss-binaries.phusionpassenger.com wheezy Release.gpg
Ign https://oss-binaries.phusionpassenger.com wheezy Release
Err https://oss-binaries.phusionpassenger.com wheezy/main amd64 Packages
  The requested URL returned error: 403
...
...
Failed to fetch https://oss-binaries.phusionpassenger.com/
apt/passenger/dists/wheezy/main/binary-amd64/Packages  
The requested URL returned error: 403

```

So `sudo apt-get install passenger` return **unable to locate package passenger** as expected

From my local machine i can not locate this url also (not the same network)
![Screen](https://api.monosnap.com/rpc/file/download?id=IrJiu2DIxGBmu8uB7hzfcDYOJc4Qi8)

I can not understand – is it possible install passenger on debian? is there are actual version of this guide? 

This is not first time when i fail with passenger installation, i come back third time, and can not setup it using this manual. You help will be very helpful. Thank you in advice.

**Comment by FooBarWidget** [comment]
It is possible. But it looks like your apt does not understand the HTTP redirects that our web server generates.

**Comment by FooBarWidget** [comment]
Strange... I've tested your request, but it works fine for me. Our web server doesn't generate a redirect after all. Can you attach your APT source list file?

**Comment by roma86** [comment]
Thank you for quick answer. 
This is my **sources.list**

```
deb http://mirror.yandex.ru/debian/ wheezy main
deb-src http://mirror.yandex.ru/debian/ wheezy main

deb http://security.debian.org/ wheezy/updates main
deb-src http://security.debian.org/ wheezy/updates main

# wheezy-updates, previously known as 'volatile'
deb http://mirror.yandex.ru/debian/ wheezy-updates main
deb-src http://mirror.yandex.ru/debian/ wheezy-updates main
deb http://ftp.debian.org/debian/ wheezy-backports main non-free contrib
```

this is **sources.list.d/passenger.list"**

```
deb https://oss-binaries.phusionpassenger.com/apt/passenger wheezy main
```

**Comment by roma86** [comment]
sorry. we find the problem in server proxy. 

```
mv /etc/apt/apt.conf.d/30proxy /tmp/
```

Thank you for your point to redirect
