### ISSUE TITLE
Rails process crash with SIGSEGV using Nginx module

### ISSUE THREAD

**Issue by shirosaki** [phusion/passenger#1459]
A rails application process crash when I load a page and another page after the application restarts.

I use Passenger 5.0.5 and `passenger_max_instances_per_app 2;`  setting.
After I change the `passenger_max_instances_per_app` setting from 2 to 1, process doesn't crash.

Here is a crash log.
https://gist.github.com/shirosaki/1c28e7ec62a7ccb917a0

**Comment by OnixGH** [comment]
Thanks for reporting, we're going to look into it!

**Comment by FooBarWidget** [comment]
This has a lot of resemblance with #1469, but #1469 doesn't use `passenger_max_instances_per_app`. The issue might be unrelated to that config option.

**Comment by OnixGH** [comment]
@shirosaki are you using Out-Of-Band Garbage Collection?

Your trace indeed looks similar to the ones in #1469.

**Comment by shirosaki** [comment]
@OnixGH Yes, I am using Out-Of-Band GC.

**Comment by OnixGH** [comment]
I've reproduced the same crash using nginx and without the `passenger_max_instances_per_app` so it's probably not related to that, and the same as #1469. Let's continue there.
