### ISSUE TITLE
passenger-status doesn't work with custom temp directory

### ISSUE THREAD

**Issue by omederos** [phusion/passenger#1461]
When I run `passenger-status` (or `rvmsudo passenger-status`) I get the following error:

> ERROR: Phusion Passenger doesn't seem to be running.

I've been trying to find solutions for this problem without success. I have the following running on my server:

- Ubuntu 14.04
- Ruby 2.1.1
- Passenger 4.0.37 (installed via `rvmsudo passenger-install-nginx-module`)
- Nginx 1.4.4

I have a custom log directory set, like this:

    http {
        ....
        passenger_temp_dir /home/john/passenger_temp;
        ....
    }

I tried exporting `PASSENGER_TMPDIR` and `PASSENGER_TEMP_DIR` on my current environment before running `passenger-status`, but it didn't work neither.

However, I commented the `passenger_temp_dir` line on my config, restarted the server, and it worked fine.

**Comment by FooBarWidget** [comment]
Did you know sudo and rvmsudo nuke your environment variables? Try something like: `rvmsudo env PASSENGER_TEMP_DIR=... passenger-status`

**Comment by omederos** [comment]
No, I didn't. 

Thanks for the tip. Worked perfectly.
