### ISSUE TITLE
mod_passenger and umask 077: cannot connect to socket (Permission denied)

### ISSUE THREAD

**Issue by lpirl** [phusion/passenger#1463]
When I restart Apache from a shell with umask 077, ``mod_passenger`` cannot access the Unix socket and dies with "permission denied". Trace:

<pre>
Unexpected error in mod_passenger: Cannot connect to Unix socket '/tmp/passenger.1.0.11362/generation-0/socket': Permission denied (13)
  Backtrace:
     in 'Passenger::ApplicationPool::Client* Passenger::ApplicationPool::Client::connect(const string&, const string&, const Passenger::StaticString&)' (Client.h:438)
     in 'Passenger::ApplicationPool::Client* Hooks::getApplicationPool()' (Hooks.cpp:268)
     in 'Passenger::SessionPtr Hooks::getSession(const Passenger::PoolOptions&)' (Hooks.cpp:294)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:563)
</pre>

Expected result: Unix permission are set ensured correctly so that the ``PassengerUser`` or the ``PassengerGroup`` can access the Unix socket.

Passenger version is 3.0.13.
Operating system is Debian 7.8.

**Comment by FooBarWidget** [comment]
Version 3.0.13 is over 3 years old. We no longer support that version. Please upgrade to the latest version, 5.0.6.

**Comment by lpirl** [comment]
Okay thanks, I'll check a more recent version.

**Comment by lpirl** [comment]
Works for 5.0.7.
Probably fixed by #1027 
Thanks!
