### ISSUE TITLE
404 error for a Node.js app when using standalone mode

### ISSUE THREAD

**Issue by paambaati** [phusion/passenger#1464]
I am using Passenger 5.0.6 (standalone) to run a Node.js app which is behind nginx (1.6.2). I see two weird issues when I start the app - 

1. As soon as I start the app, and before a request could even be sent to the server, I see this error in the console - `directory index of "/myproject/public/" is forbidden, client: 127.0.0.1, server: _, request: "HEAD / HTTP/1.1", host: "0.0.0.0"`. Note that the nginx user and the owner of the `/myproject/public/` are the same.

2. When I try to visit the page (which is `http://myserver.com/webapp/`), I get a 404 - `015/04/03 09:47:05 [error] 19071#0: *5 "/myproject/public/webapp/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /webapp/ HTTP/1.0", host: "myserver.com"`. Note how `/webapp/index.html` is added to the path? That shouldn't be happening.

This is what the configuration for `myserver.com` looks like.

```
upstream server_upstream {
    server 127.0.0.1:3000;
}

server {
    listen *:8080;

    root /myproject/public/static;

    server_name myserver.com;

    location /webapp/static {
        alias /myproject/public/static;
        autoindex on;
        access_log off;
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
        proxy_hide_header       X-Powered-By;
        proxy_hide_header       X-Runtime;
        proxy_hide_header       Server;
    }

    location = /webapp {
        return 301 http://$server_name/webapp/;
    }

    location = / {
        return 301 http://$server_name/webapp/;
    }

    location / {
        proxy_pass      http://server_upstream;
        proxy_read_timeout  90;
        proxy_connect_timeout   90;
        proxy_redirect      off;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
        proxy_http_version  1.1;
        proxy_set_header    Connection "";
        proxy_hide_header   X-Powered-By;
        proxy_hide_header   X-Runtime;
        proxy_hide_header   Server;
        proxy_cache_key     sfs$request_uri$scheme;
    }
}
```

The kicker is I have pretty much the same setup on my local machine and it works flawlessly (OS X, Passenger 5.0.6 standalone from Homebrew, Node v0.12.2, nginx 1.6.2), but it won't work on a company server (RHEL 6.3, Passenger 5.0.5 standalone from TAR, Node v0.12.0, nginx 1.6.2).

**Comment by OnixGH** [comment]
The root must point to public, not static. See also: https://github.com/phusion/passenger/wiki/Phusion-Passenger%3A-Node.js-tutorial#deploying_on_nginx_or_apache

**Comment by FooBarWidget** [comment]
I also don't see any `passenger_enabled on` directives in your config. It should be there.

**Comment by paambaati** [comment]
@OnixGH Changing that didn't help at all. I get the same error message on the log.

**Comment by paambaati** [comment]
@FooBarWidget Isn't that directive needed only when the Nginx module is also installed? I am using only the standalone version. Anyway, when I add that, I get the following error message - 

`nginx: [emerg] unknown directive "passenger_enabled" in /etc/nginx/sites-enabled/myserver.com.conf:14`

**Comment by FooBarWidget** [comment]
Ah I see. Sorry about that, I misunderstood you.

Regarding point 1: have I understood you correctly that, when you said "As soon as I start the app", you meant "As soon as I run `passenger start`"?

Regarding point 2: the error that you saw there, did that come from the myserver.com Nginx log file, or from the Passenger Standalone log file?

**Comment by paambaati** [comment]
Point 1 - yes, as soon as I run `passenger start`.

Point 2 - that's from the Passenger standalone log file.

**Comment by FooBarWidget** [comment]
In which directory did you start Passenger Standalone? What was the exact command invocation?

**Comment by paambaati** [comment]
I started it in  `/myproject`, which has my Node.js server app file. The exact command I used was `passenger start --startup-file myserver.js --port 3000 --min-instances 2`.

**Comment by FooBarWidget** [comment]
Can you add `--app-type node` to the invocation and check whether that helps?

**Comment by paambaati** [comment]
Yup, adding `--apt-type node` resolves my issue.

**Comment by matt212** [comment]
I am getting this 404 error with log statements as "/etc/nginx/sites-enabled/public/muser/index.html"
whereas my actual location is root "/mnt/f/projects/usermanagement/;" I configured the same in sites-enabled and available and also in nginx.conf files where should i give my root application path t ! please suggest

**Comment by OnixGH** [comment]
Please post configuration questions to the [forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger).
