### ISSUE TITLE
Disconnecting long-running connections for process with Rails and RabbitMQ

### ISSUE THREAD

**Issue by phongmh307** [phusion/passenger#1467]
Hello,

I just started using RabbitMQ and Rails under Passenger server and I'm experiencing missing Facebook Realtime Updates Callback recently. I checked nginx log and this error is happening over and over but I never happen before. Does anyone facing the same issue? Is it related to Passenger?

Thank you

```
[ 2015-04-03 16:14:10.1180 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 11249, application /home/pancake/pancake/current/public (production)#default
[ 2015-04-03 16:19:11.1644 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 11150, application /home/pancake/pancake/current/public (production)#default
App 11696 stdout:
App 11817 stdout:
App 11837 stdout:
[ 2015-04-03 16:25:05.2260 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 11837, application /home/pancake/pancake/current/public (production)#default
[ 2015-04-03 16:25:06.3960 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 11817, application /home/pancake/pancake/current/public (production)#default
App 12163 stdout:
App 12284 stdout:
[ 2015-04-03 16:31:40.5468 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 12284, application /home/pancake/pancake/current/public (production)#default
App 12726 stdout:
App 12847 stdout:
App 13376 stdout:
App 13497 stdout:
[ 2015-04-03 16:51:44.7776 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 12847, application /home/pancake/pancake/current/public (production)#default
[ 2015-04-03 16:51:46.8725 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 13497, application /home/pancake/pancake/current/public (production)#default
App 13810 stdout:
App 13931 stdout:
[ 2015-04-03 17:08:24.0562 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 13931, application /home/pancake/pancake/current/public (production)#default
App 14982 stdout:
App 15105 stdout:
[ 2015-04-03 17:22:34.2230 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 15105, application /home/pancake/pancake/current/public (production)#default
App 15356 stdout:
App 15477 stdout:
[ 2015-04-03 17:28:24.1388 2109/7fa2169a2700 age/Hel/Main.cpp:732 ]: Disconnecting long-running connections for process 15477, application /home/pancake/pancake/current/public (production)#default
App 16413 stdout:
App 16536 stdout:
```

**Comment by OnixGH** [comment]
"Disconnecting long-running connections" is not an error, but a notice that Passenger is closing idle applications to save memory. If you don't want this to happen you can set `passenger_pool_idle_time` to zero. Ref: https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerPoolIdleTime

**Comment by SyedTayyab** [comment]
@OnixGH 
Can I set passenger_pool_idle_time for a particular application or process. I am running a socket chat server which starts in a new thread inside my rails app. The chat process is killed by passenger after sometime and I find this notification in the error log. Is there a way that I set this value to 0 only for this particular app?

**Comment by OnixGH** [comment]
@SyedTayyab that should be possible if the app has its own location, by putting it into a separate PassengerAppGroupName which then has its own settings.

**Comment by SyedTayyab** [comment]
Ahan will try that now. Thanks a lot for your help. Btw in which file can I find the max_pool_idle_time?

**Comment by OnixGH** [comment]
It depends on your installation, for example with nginx: https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#_configuring_phusion_passenger

**Comment by ndvbd** [comment]
How can we suppress this message?

**Comment by CamJN** [comment]
@ndvbd the only built in way is to adjust the log level.
