### ISSUE TITLE
mysql2 "ASN: bad other signature confirmation" when running passenger on heroku

### ISSUE THREAD

**Issue by btucker** [phusion/passenger#1468]
When running on passenger with the following Procfile:
```
web: bundle exec passenger start -p $PORT -e ${RACK_ENV:-development} --max-pool-size 6 --no-friendly-error-pages
```
The app throws an exception on first request with:
```
Mysql2::Error (SSL connection error: ASN: bad other signature confirmation)
```
Commenting out that line of the Procfile (switching to using webrick) makes the error go away with no other changes.

Additionally, accessing the database through `heroku run rails c` works fine.  So the problem seems to occur only when passenger is in the mix.

```
mysql2 (0.3.18)
passenger (5.0.6)
rails (4.1.6)
```

**Comment by FooBarWidget** [comment]
Are you using any special Heroku add-ons?

**Comment by btucker** [comment]
I haven't been able to replicate this in a test rails app.  So there must be something else at play.  I'll reopen when I isolate the problem if it points at something that needs addressing in passenger.
