### ISSUE TITLE
Unable to start the Phusion Passenger watchdog because it encountered the following error during startup

### ISSUE THREAD

**Issue by vmcilwain** [phusion/passenger#1470]
I installed the latest version of passenger and I have been struggling with it for the last few days. I have not had luck trying to fix this so I am putting in this in as an issue. What I see in the apache error_log is:

[Wed Apr 08 22:18:21.747552 2015] [passenger:error] [pid 11895] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog because it encountered the following error during startup: Unable to start the Phusion Passenger logging agent: it seems to have crashed during startup for an unknown reason, with exit code 1

I do not know how to solve this issue and it seems to be a "recent" issue since I didn't run into this problem in the 4.x gem running on a different server.

What is the best way to get past this?

**Comment by FooBarWidget** [comment]
Are there any other error messages in the log file?

**Comment by vmcilwain** [comment]
I'm working on getting another environment up and running. I will redo my steps and send you the URL to the tutorial I used for setup and so that you can see my list of steps and I will post the full log file.

**Comment by vmcilwain** [comment]
Ok, so I have just finished the fresh install of centos 7. I used the following tutorial to set up my server:

https://www.digitalocean.com/community/tutorials/how-to-setup-a-rails-4-app-with-apache-and-passenger-on-centos-6

My environment is:
Centos 7
RVM
Apache
MySQL
Passenger

All the latest versions.

I am at the end of this tutorial where I have installed passenger and ran passenger-install-apache2-module.

I add the following to my httpd.conf and then restart apache.

LoadModule passenger_module /home/deploy/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/apache2/mod_passenger.so
<IfModule mod_passenger.c>
  PassengerRoot /home/deploy/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.6
  PassengerDefaultRuby /home/deploy/.rvm/gems/ruby-2.2.1/wrappers/ruby
</IfModule>

<VirtualHost *:80>
   ServerName www.yourhost.com
   # !!! Be sure to point DocumentRoot to 'public'!
   DocumentRoot /apps_myapp/public   
   <Directory /apps/myapp/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
      # Uncomment this if you're on Apache >= 2.4:
      Require all granted
   </Directory>
</VirtualHost>

So far everything comes up fine until I try to hit the IP address of the system with a browser. The browser tells me it can't display the page and when I take a look at apaches error log I see:

[ 2015-04-09 18:02:06.4936 1611/7f8c4f913880 age/Hel/Main.cpp:876 ]: PassengerAgent server shutdown finished
[Thu Apr 09 18:02:06.516239 2015] [passenger:error] [pid 1343] *** Passenger could not be initialized because of this error:
 Unable to start the Phusion Passenger watchdog because it encountered the following error during startup: Unable to start t
he Phusion Passenger logging agent: it seems to have crashed during startup for an unknown reason, with exit code 1
[Thu Apr 09 18:02:06.517918 2015] [mpm_prefork:notice] [pid 1343] AH00163: Apache/2.4.6 (CentOS) Phusion_Passenger/5.0.6 con
figured -- resuming normal operations
[Thu Apr 09 18:02:06.517976 2015] [core:notice] [pid 1343] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

The apache access log does not have any information and the rails love does not have any information.

Is there any other place you need me to look?

**Comment by vmcilwain** [comment]
Hello there. Any updates on this?

**Comment by FooBarWidget** [comment]
Let me spin up a Digital Ocean instance and try to reproduce your error.

**Comment by vmcilwain** [comment]
I will spin up my current vm in its current state and monitor this so if you have any questions, I can answer fairly quickly.

**Comment by vmcilwain** [comment]
So I have cleared the httpd error_log and restart apache just to see what initialization would generate. Here is what the log had just from a restart of httpd.conf

[root@localhost httpd]# systemctl restart httpd
[root@localhost httpd]# systemctl status httpd
httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled)
   Active: active (running) since Tue 2015-04-14 10:44:50 EDT; 3s ago
  Process: 9812 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=0/SUCCESS)
 Main PID: 9817 (httpd)
   Status: "Processing requests..."
   CGroup: /system.slice/httpd.service
           ├─9817 /usr/sbin/httpd -DFOREGROUND
           ├─9824 /usr/sbin/httpd -DFOREGROUND
           ├─9825 /usr/sbin/httpd -DFOREGROUND
           ├─9826 /usr/sbin/httpd -DFOREGROUND
           ├─9827 /usr/sbin/httpd -DFOREGROUND
           └─9828 /usr/sbin/httpd -DFOREGROUND

Apr 14 10:44:50 localhost.localdomain httpd[9817]: AH00558: httpd: Could not r...e
Apr 14 10:44:50 localhost.localdomain systemd[1]: Started The Apache HTTP Server.
Hint: Some lines were ellipsized, use -l to show in full.
[root@localhost httpd]# tail -f /var/log/httpd/error_log
[Tue Apr 14 10:44:50.866538 2015] [core:notice] [pid 9817] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Tue Apr 14 10:44:50.867271 2015] [suexec:notice] [pid 9817] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Apr 14 10:44:50.879512 2015] [passenger:error] [pid 9817] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog (/home/deploy/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/support-binaries/PassengerAgent): Permission denied (errno=13)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 14 10:44:50.889260 2015] [auth_digest:notice] [pid 9817] AH01757: generating secret for digest authentication ...
[Tue Apr 14 10:44:50.890222 2015] [lbmethod_heartbeat:notice] [pid 9817] AH02282: No slotmem from mod_heartmonitor
[Tue Apr 14 10:44:50.892142 2015] [passenger:error] [pid 9817] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog (/home/deploy/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/support-binaries/PassengerAgent): Permission denied (errno=13)
[Tue Apr 14 10:44:50.893873 2015] [mpm_prefork:notice] [pid 9817] AH00163: Apache/2.4.6 (CentOS) Phusion_Passenger/5.0.6 configured -- resuming normal operations
[Tue Apr 14 10:44:50.893896 2015] [core:notice] [pid 9817] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'


When I try to hit my server using the IP address I get the following:

[Tue Apr 14 10:47:04.539002 2015] [autoindex:error] [pid 9825] [client 10.0.0.12:42807] AH01276: Cannot serve directory /apps/my_app/public/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive

Hope this helps

**Comment by FooBarWidget** [comment]
> [Tue Apr 14 10:44:50.879512 2015] [passenger:error] [pid 9817] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog (/home/deploy/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/support-binaries/PassengerAgent): Permission denied (errno=13)

I'm not yet done following the tutorial, but this is the key error message. There's a permission problem, causing the Passenger Apache module to fail to execute PassengerAgent.

Do you have SELinux enabled?

**Comment by FooBarWidget** [comment]
I'm done following the tutorial, but can't reproduce your problem. Your issue is probably caused by specific permissions on your server.

**Comment by vmcilwain** [comment]
Selinux is enabled yes but I have run the command that fixed the shared object permission denied issue that seems common. 

When I first encountered this problem selinux was turned off completely.  I'm consistently getting this issue. I'm surprised you weren't able to reproduce it specially since googling it seems to turn up but with no definitive way to resolve it. 

I used this same tutorial on centos 6.5 but I know the version of passenger and probably Apache are different. When I get back to my laptop I will let you know what versions they were. 

Not sure what other logs I can show you to give you more insight.

**Comment by vmcilwain** [comment]
My last successful install was with:

passenger 4.0.59
centos 6.6 (SELINUX disabled)
Apache 2.2.15

I used the same tutorial.

**Comment by FooBarWidget** [comment]
Maybe it's faster if I can help you on instant messaging. Do you have Skype? If so could you add 'hongli'?

**Comment by vmcilwain** [comment]
Sure. That would be much appreciated. I sent my skype name to your email address.

**Comment by FooBarWidget** [comment]
I've added you. Awaiting your reply. :)

**Comment by erodriguez-gap** [comment]
Hello I'd like to confirm that I have the same issue on a MediaTemple DV Server with Ubuntu 14.04.

**Comment by dynelight** [comment]
I'd like to confirm I have the same issue. I tried setting this up on MediaTemple(dv). I do not use SELinux. 

My environment is:
Ubuntu
RVM
Apache
Passenger

All latest versions. 

Thanks!

**Comment by FooBarWidget** [comment]
Thanks @vmcilwain and @dynelight for your feedback.

@vmcilwain helped me analyze the SELinux issues. I will do more research and report back. It turns out we're having a lot of problems with SELinux. We documented an old workaround involving adding the httpd_sys_script_t to Passenger files, but that doesn't work anymore. Apache executes Passenger inside the Apache domain, so Passenger still can't do the things it wants.

@dynelight's issue turns out to be completely unrelated. He installed two versions of Passenger in such a way that they conflict with each other.

**Comment by FooBarWidget** [comment]
So over Skype, I've determined with @vmcilwain that he had a permission problem and an SELinux problem.

The permission problem was on his home directory. Passenger was installed inside the home directory, so any non-root processes that Passenger spawns couldn't access the Passenger directory.

The SELinux problem is more related to our SELinux support as a whole. I've opened a new ticket for that: #1486

Finally, we've found a problem inside the logging agent. The logging agent was supposed to work despite the permission problem, but it didn't because of bug a bug. I opened #1487 for that.

**Comment by yigitbacakoglu** [comment]
Hi @FooBarWidget , I am having same permission problem instead of my Passenger was installed in root - /user/local directory.

`[root@s13 ~]# which passenger
/usr/local/rvm/gems/ruby-2.2.2/bin/passenger
`



`Validating installation...

 * Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... ✓
 * Checking whether Apache is installed... ✓
 * Checking whether the Passenger module is correctly configured in Apache... ✓

`

```
[root@s13 ~]# passenger -v
Phusion Passenger 5.0.27

```

Centos 5.4
RVM
Apache
MySQL
Passenger

And the error log output:

```
[root@s13 ~]# tail -f /var/log/httpd/error_log
[Sat Apr 16 08:22:30 2016] [notice] SSL FIPS mode disabled
[ 2016-04-16 08:22:30.4608 16592/7a0b4d104730 age/Wat/WatchdogMain.cpp:1301 ]: Starting Passenger watchdog...
[Sat Apr 16 08:22:31 2016] [error] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog because it encountered the following error during startup: Unable to start the Passenger core because exec("/usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.27/buildout/support-binaries/PassengerAgent") failed: Permission denied (errno=13)
[Sat Apr 16 08:22:31 2016] [warn] module ssl_module is already loaded, skipping
[Sat Apr 16 08:22:31 2016] [warn] module limitipconn_module is already loaded, skipping
[Sat Apr 16 08:22:31 2016] [notice] SSL FIPS mode disabled
[ 2016-04-16 08:22:31.5355 16603/6704aa021730 age/Wat/WatchdogMain.cpp:1301 ]: Starting Passenger watchdog...
[Sat Apr 16 08:22:32 2016] [error] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog because it encountered the following error during startup: Unable to start the Passenger core because exec("/usr/local/rvm/gems/ruby-2.2.2/gems/passenger-5.0.27/buildout/support-binaries/PassengerAgent") failed: Permission denied (errno=13)
[Sat Apr 16 08:22:32 2016] [notice] Apache/2.2.3 (CentOS) PHP/5.3.3 mod_ssl/2.2.3 OpenSSL/0.9.8e-fips-rhel5 Phusion_Passenger/5.0.27 configured -- resuming normal operations

```
