### ISSUE TITLE
PassengerAppGroupName apache docs

### ISSUE THREAD

**Issue by jrochkind** [phusion/passenger#1473]
The apache passenger docs for PassengerGroupName say:

> Its default value is the application root, plus (if it is set), the application environment name.

"application root" is a hyperlink, and links to [PassengerRoot](https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerRoot)

I think this is a mistake, and it really ought to link to PassengerAppRoot, it's really the current PassengerAppRoot (when using SubURI's, there could be different ones at different locations) that is part of the default cache key?   Cause that's what would make more sense. 

Can you clarify?

**Comment by FooBarWidget** [comment]
You're right, that is wrong. It's supposed to link to the terminology chapter: https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#application_root
