### ISSUE TITLE
Meteor ignores METEOR_SETTINGS

### ISSUE THREAD

**Issue by serkandurusoy** [phusion/passenger#1474]
I'm using passenger 5.0.6 on ubuntu 14.04 64-bit stock install on a digital ocean vps.

I've set up mongo, oplog and mail url environment variables successfully using 

     passenger_env_var [ENV_VAR] [VAR_CONTENT];

pattern but this does not work:

     passenger_env_var METEOR_SETTINGS ' { "public": { "something": "somevalue" } , "something": "somevalue" } ';

interestingly, if I pass a bad json string, meteor does parse it and complain about it, preventing startup. But when I pass valid json like the above, it just gets ignored.

Furthermore, I've tried setting `METEOR_SETTINGS` on places like `etc/environment` and `profile.d` but meteor does not pick them up either.

As a side note, I'm not deploying as a node application.

I've installed meteor and passenger nginx mode and therefore passenger runs meteor natively, not as a standard node app.

So, what do I do?

**Comment by serkandurusoy** [comment]
Inspecting further, METEOR_SETTINGS is only respected when passenger runs the app as a node app. If it is run as a meteor app, then the settings just gets ignored.

This is a problem with passenger.

As per the latest changes in meteor,

meteor_settings is actually used only in production deployments that are made with meteor build.

otherwise, running meteor from meteor's executable with --production flag does not actually use the settings environment variable. but it does accept the --settings flag and a json file. so what passenger can do is accept a file path in that case. currently, it does not and accepts valid json string.

**Comment by FooBarWidget** [comment]
Please refer to issue #1403, which is the same as what you've reported.
