### ISSUE TITLE
LDAP auth support in packages built for Debian?

### ISSUE THREAD

**Issue by rchady** [phusion/passenger#1476]
I require the ability to do LDAP auth with nginx in my (Debian) environment.  This requires me, currently, to compile my own nginx and create a custom .deb.  Would there be a chance you'd be willing to compile the ldap-auth module in to your built version?

**Comment by OnixGH** [comment]
If you want to use passenger with additional modules (such as ldap-auth), you can use passenger-install-nginx-module and pick option 2 "No: I want to customize my Nginx installation. ". A few steps later it asks for the options for the nginx configure script, where you can specify the `--add-module` option you need for ldap-auth.

**Comment by rchady** [comment]
That works fine if you have the ability to compile everything on each system.  My production systems do not have that capability so things are installed via .debs.  Was just wondering if the 1 extra --add-module line could get added to compile the ldap auth module in.

**Comment by OnixGH** [comment]
Understood, I think we prefer to have our packages as lean as possible, but I'll discuss it with @FooBarWidget.

**Comment by rchady** [comment]
I can understand that desire.  Perhaps only add it to the -extras package?

**Comment by FooBarWidget** [comment]
As a policy, we mimick the Debian packages in order to maximize compatibility. If Debian doesn't compile in LDAP, we don't either.

If you want LDAP, you can take our Debian packages and customize them. The Debian source packages are available from our APT repository.
