### ISSUE TITLE
Bundler::GemfileError trying to start a sinatra app with passenger?

### ISSUE THREAD

**Issue by rchady** [phusion/passenger#1480]
Probably related to #1478, but I am stumped.

I am trying to set up geminabox on this system.  Following what was identified in the previous ticket, I created a Gemfile to force it to use rack 1.6.0 and started.  When I try to load it, either via nginx or passenger standalone, I get:

```
  Message from application: There was an error in your Gemfile, and Bundler cannot continue. (Bundler::GemfileError)
  /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:12:in `rescue in evaluate'
  /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:6:in `evaluate'
  /usr/lib/ruby/vendor_ruby/bundler/definition.rb:18:in `build'
  /usr/lib/ruby/vendor_ruby/bundler.rb:135:in `definition'
  /usr/lib/ruby/vendor_ruby/bundler.rb:123:in `load'
  /usr/lib/ruby/vendor_ruby/bundler.rb:107:in `setup'
  /usr/lib/ruby/vendor_ruby/bundler/setup.rb:17:in `<top (required)>'
  /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:278:in `block in run_load_path_setup_code'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:381:in `running_bundler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:276:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:99:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:157:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'
```

With my Gemfile consisting of:

```
source 'https://rubygems.org'

gem "rack", "~> 1.6.0"
gem "geminabox"
```

And bundle install says everything is fine.  What am I missing?

**Comment by FooBarWidget** [comment]
Is that message everything you see? There are no more messages?

**Comment by rchady** [comment]
That is it, other than Implementation.cpp:287 indicating it could not spawn process for application...

I tried it in standalone and received the same results.

**Comment by FooBarWidget** [comment]
I don't think this is a Passenger issue, but I can't think of what it might be.  Maybe you can edit /usr/lib/ruby/vendor_ruby/bundler/dsl.rb line 12 (per the backtrace), put a few debugging statements there and find out why Bundler is aborting.

**Comment by rchady** [comment]
Sigh, why won't it just report this information rather than make me have to hack this in.  Anyhow, made it output the actual error and it is:

  Message from application: There was an error in your Gemfile, and Bundler cannot continue. (cannot load such file -- rubygems/format) (Bundler::GemfileError)

**Comment by FooBarWidget** [comment]
That... looks very strange. rubygems/format should exist. Can you check whether the app is being run under the Ruby interpreter that you intended to run?

**Comment by rchady** [comment]
Pretty sure the culprit is this rubygems-integration package that is installed. It seems to have put some stubs in place, making ruby grab the wrong directory for rubygems.  Royally frustrated with Debian and how they handle ruby/gems.  Trying to see if I can fix this now.

**Comment by rchady** [comment]
There is only one interpreter on this system, so yeah pretty sure the right one is getting run.  I'm not sure what is going on to be honest here.  It isnt' the rubygems-integration like I thought.. it seems like the bundler/rubygems that is in 2.1.5 somehow aren't fully compatible?  Not sure, something seems very wrong.

**Comment by FooBarWidget** [comment]
That might actually be the case. Passenger calls `require "bundler"` before loading the Gemfile, so maybe your situation is similar to the Rack situation, but with Bundler. Strangely, I did not encounter this in my test on Linux, but maybe I didn't have Bundler installed via RubyGems.

I'm wondering whether it would help if Passenger explicitly loads Bundler and Rack through RubyGems. Can you try editing /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb? Look for:

    require 'rack'

Before that line, add:

    gem 'rack'

Similarly, look for:

    require 'bundler/setup'

Before that line, add:

    gem 'bundler'

Does this help?

**Comment by rchady** [comment]
Just adding the gem 'bundler' fixed the entire issue for me... (don't see require 'rack' in 5.0.6)

**Comment by FooBarWidget** [comment]
Oh oops. The require rack thing isn't in loader_shared_helpers.rb. It is in /usr/share/passenger/helper-scripts/rack-preloader.rb.

Could you try making the modification there, and check whether your app works even without a Gemfile?

**Comment by rchady** [comment]
It does indeed...  Thanks!

**Comment by FooBarWidget** [comment]
Ok, I'll incorporate these into the next version.
