### ISSUE TITLE
What is the minimum version of Ruby required for Passenger 5.x?

### ISSUE THREAD

**Issue by paambaati** [phusion/passenger#1481]
I am trying to find the minimum version of Ruby required for Passenger, and the corresponding link (https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#relationship_with_ruby) on the users guide is non-existent.

Also, what would the recommended version of Ruby be, if the target system is RHEL 6.3 or above?

**Comment by OnixGH** [comment]
The info about versions is in chapter 1 of the standalone guide: https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#_support_information

Indeed, the link to the relationship with ruby isn't there in the standalone manual, I'll fix that. Meanwhile you can check it in the nginx manual: https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#relationship_with_ruby

**Comment by paambaati** [comment]
Ah, got it. Thanks!
