### ISSUE TITLE
symbol lookup error: undefined symbol: rb_str_new_static

### ISSUE THREAD

**Issue by MeiKatz** [phusion/passenger#1483]
There is an error on startup with an undefined symbol named **rb_str_new_static**. Is there any solution or work around for this issue?

```
[ 2015-04-17 13:03:08.0517 15740/7f84ec1a3700 App/Implementation.cpp:287 ]: Could not spawn process for application [edited]: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: ae45bc90
  Error details saved to: /tmp/passenger-error-FAz9bs.html
  Message from application: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>
/usr/bin/ruby: symbol lookup error: /usr/local/lib/ruby/gems/2.2.0/gems/json-1.8.2/lib/json/ext/parser.so: undefined symbol: rb_str_new_static
</pre>
```

I am working on Ubuntu 14.4 LTS with Passenger 5.0.6 and Ruby 2.2.2

**Comment by FooBarWidget** [comment]
This is not a Passenger issue. As you can see in the error message, it's the json gem that is causing the symbol lookup error. Try reinstalling that gem.

**Comment by MeiKatz** [comment]
Well, I reinstalled the gem but it did not change anything.

**Comment by FooBarWidget** [comment]
Try removing the gem completely, then install it from scratch.

**Comment by MeiKatz** [comment]
Removing ruby, rubygems and bundler from my system and reinstall them from the bottom did the trick. I also updated the json package from version 1.8.1 to 1.8.2
