### ISSUE TITLE
doc: apache, restart?

### ISSUE THREAD

**Issue by jrochkind** [phusion/passenger#1484]
[This blog post](https://blog.phusion.nl/2015/03/04/whats-new-in-passenger-5-part-2-better-logging-better-restarting-better-websockets-and-more/) suggests that Passenger 5 no longer uses the `touch ./tmp/restart.txt`, but uses a new restart command. 

But the [Passenger Apache documentation](https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#_redeploying_restarting_the_rack_application) still lists `touch tmp/restart.txt`, and does not discuss the new restart mechanism discussed in the blog post. 

Does `touch tmp/restart.txt` still restart the app in Passenger 5? Is the new method also supported? Should it be mentioned in the docs?

**Comment by OnixGH** [comment]
The old way still works, but with a default timeout of 10 seconds. So by default, there is a max 10 seconds delay before Passenger notices that you have touched restart.txt. You can revert to the old behavior by setting PassengerStatThrottleRate to 0.

See also: https://groups.google.com/forum/#!msg/phusion-passenger/rnFkF56M1hI/FIgMmIZz0GAJ

**Comment by jrochkind** [comment]
Cool, but the new way shoudln't be doc'd next to the old way, along with the clarification about PassengerStatThrottleRate?

**Comment by FooBarWidget** [comment]
Yes it should. The current documentation leaves much to be desired. We're working on a [new documentation project](https://github.com/phusion/passenger_library) with the goal of fixing these shortcomings.
