### ISSUE TITLE
403 Forbidden after updating to version 5.0.6

### ISSUE THREAD

**Issue by torreyj** [phusion/passenger#1485]
I have a demo and a production server. I recently installed ruby 2.2.1 with Ruby Version Mananger for a new project that runs under a different gemset. My older ruby projects use passenger 4.0.59 with a different version of Ruby. On my demo site, I got no issues after installing 2.2.1 and adding gem passenger and installing through 'passenger-install-apache2-module'. I have both passenger version 5.0.6 and 4.0.59 working together great (both are in separate gemsets obviously). 

However, same exact setup for my production server and I can't have either one of them running at the same time. I have to comment out the Load paths for the .so file and the PassengerRuby. I get the following error below. It kicks back the dreaded 403 Forbidden error. Anybody else ever got this and know if this is a bug or is there something I'm missing.  Thanks

```Passenger could not be initialized because of this error: Unable to start Phusion Passenger: Support binary PassengerAgent not found (tried: /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-4.0.59/buildout/support-binaries/PassengerAgent and /root/.passenger/support-binaries/5.0.6/PassengerAgent). 
   This probably means that your Phusion Passenger installation is broken or incomplete, or that your 'PassengerRoot' setting contains the wrong value. Please reinstall Phusion Passenger or adjust the setting (see: https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerRoot).
```

**Comment by OnixGH** [comment]
5.0.9 is not out yet, are you talking about 5.0.6?

**Comment by torreyj** [comment]
yes, my apologies. I updated my comment

**Comment by OnixGH** [comment]
No worries. In any case, did you check your passenger root setting like the error asks? Also check what passenger scripts you are actually executing. It won't work if you accidentally run 4.0.59 with 5.0.6 scripts/folders or the other way around.

**Comment by torreyj** [comment]
I did check the root settings.  I have them both set in my virtual configs. #1 is my new site, and #2 is an example of my other sites. Is there another place I should be looking. I get the path "/usr/local/rvm/gems/ruby-2.2.1/gems/passenger-4.0.59", when I run the command 'passenger-config --root'.  Any help on what command to run to see what scripts are running or located would be appreciated. Thanks

#1--------
   LoadModule passenger_module /usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.6
     PassengerRuby /usr/local/rvm/gems/ruby-2.2.1/wrappers/ruby
   </IfModule>

#2--------
   LoadModule passenger_module /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-4.0.59/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-4.0.59
     PassengerRuby /usr/local/rvm/gems/ruby-1.9.3-p551/wrappers/ruby
   </IfModule>

**Comment by OnixGH** [comment]
Could you post your config files? It looks to me like your passenger 5.0.6 module has the PassengerRoot set to 4.0.59.

**Comment by torreyj** [comment]
Sorry, that was a typo, I updated the comment. I switched both to work under 4.0.59 just to see if it they work during troubleshooting before sending my issue to you. It's now back under 5.0.6. Here's my files again.

4.0.59 config
https://gist.github.com/torreyj/60be4237d7fd346026a8

5.0.6 config
https://gist.github.com/torreyj/5455cb1a55ebc43e7a6e

**Comment by torreyj** [comment]
Yeah, I'm at at a loss. I have all my PassengerRoot directories setup correctly. When I switch between my different ruby versions, and type 'passenger-config --root', I get the correct root paths.  'passenger-config --ruby-command' gives me the correct paths for Ruby. Not sure why it's trying to load both PassengerAgents with this command? Has to be a bug. Never had this issue before using 5.0.6. 

(tried: /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-4.0.59/buildout/support-binaries/PassengerAgent and /root/.passenger/support-binaries/5.0.6/PassengerAgent)

**Comment by OnixGH** [comment]
Thanks for the configs, but you edited out some parts like the ServerName, DocumentRoot, Directory (anything else?). I can understand that, but then I need to check:
- Are the ServerNames different / non-overlapping? 
- Same question for DocumentRoot and Directory.

**Comment by torreyj** [comment]
Yes, the ServerNames are non over lapping. Those values are pretty straightforward. I just edited the Sitename on those paths for non sharing public sake.

I did a little bit more testing on different passenger versions.  Where both older sites, and the newer site are set at 5.0.6. The newer site works, and the older one does not. I get an error saying something about not being able to configure the older ruby? Which would make sense since I thought I read somewhere that 1.9.3 won't work on version 5 and above? Could be wrong on that, but it is an pretty old ruby version, so wouldn't expect it to work at a certain point.

Then, I downgraded the level back to 4.0.59 on both newer and older sites, and they both work. 4.0.59 is not that old and works pretty well, so I'm ok with just leaving them both at that version for now. I'm slowing making the older sites new again, so hopefully this gets resolved by the time I get there. But just and FYI, I have the 5.0.6 and 4.0.59 working in tandem on my demo server, with RAILS_ENV set to "demo". So I'm thinking this is a production module issue only.

**Comment by OnixGH** [comment]
You didn't mention this, but are you sure you are running two different apache servers? As far as I know Apache doesn't support loading multiple versions of the same module on a per-VirtualHost basis. It will give an error like "module passenger_module is already loaded, skipping", so one of the versions will be disabled and the other version will end up being used with the wrong config.

**Comment by torreyj** [comment]
I did mention this in the first paragraph on my first post.  The reason why it works is because I have them sepertated by gemsets. They're not using the same module. I think we're not on the same page. So lets start over.

I have two different version of passenger installed, under two different gemset versions.  Gemset (default 2.2.1) has passenger 5.0.6 installed in it with the module "LoadModule passenger_module /usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/apache2/mod_passenger.so" 
Then, I have a gemset for ruby 1.9.3 (default 1.9.3-p551), that has passenger version 4.0.59 installed under it, with the module "LoadModule passenger_module /usr/local/rvm/gems/ruby-1.9.3-p551/gems/passenger-4.0.59/buildout/apache2/mod_passenger.so". 
Completely different locations and modules installed. They's shouldn't be touching each other, but they are apparently, that's the issue.  Something in 5.0.6 is defaulting the root to try to load the version of passenger and vise versa. 

I know this works or should work, because I have other servers that have that same setup, but with different version of passenger installed under different gemsets.  For eample, I have gemset 1.9.3p-484 with version 4.0.25, and have another gemset with 2.1.1 with version 4.0.42. This is my other production server. This is the first time (for me) have different versions running for different projects and gets an error.  If Apache isn't supposed to do this, then that's a even bigger issue.

**Comment by torreyj** [comment]
I'm going to test with the new PassengerLogFile <filename> option in 5.0.5 and mess with some of the deprecated/new configs and see if anything changes.  Maybe I've been setting up Apache wrong, but never had issues before. So I'll double check my setup

**Comment by OnixGH** [comment]
So you're trying to run with 1 apache? Did you check the apache logs for the "already loaded" error?

I saw from your configuration that you have 2 different gemsets, but that's not relevant. What I'm trying to say is that I don't think you can't LoadModule mod_passenger.so twice in the same Apache, even if they are 2 different files/versions in different VirtualHosts, because they both identify as "mod_passenger". The one that is loaded second will conflict and be ignored, leaving the first to serve both VirtualHost setups.

I would guess in your other setups it's silently working because 4.0.42 is fairly compatible with 4.0.25. But 5.x and 4.x are miles apart so a 4.x apache module can't control a 5.x PassengerAgent, and the other way around.

**Comment by torreyj** [comment]
Ok, so my setup seems to be wrong then. Yes, when I ran the command to see if multiple apaches were running (which there's only 1), I do get a lot of the "module passenger_module is already loaded, skipping" messages.  So basically what you're saying is, only one module can run per server?  If that's the case, then how do I run my older ruby versions (like 1.9.3) if the module is installed under ruby 2.2.1 gemset? Would that just be the PassengerRuby setting and would go in my separate virtual config files? 

So basically set up the LoadModule in one spot (most likely the apache.conf file) and then in my individual virtual hosts, add the PassengerRuby Line to the different ruby wrappers? 
   
-- IN APACHE.CONF
LoadModule passenger_module /usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /usr/local/rvm/gems/ruby-2.2.1/gems/passenger-5.0.6
     PassengerRuby /usr/local/rvm/gems/ruby-2.2.1/wrappers/ruby
   </IfModule>

-- IN site config
PassengerRuby /usr/local/rvm/gems/ruby-1.9.3-p551/wrappers/ruby

**Comment by OnixGH** [comment]
Yep, that looks correct!

I personally like to put module stuff in the apache2/mods-available dir (.conf and .load) so I can easily turn them on/off with a2enmod / a2dismod, but that's more of a convenience thing.

**Comment by torreyj** [comment]
Ok, so I'm 1/2 way there. I got the new site up and running, but still get the forbidden error for ruby 1.9.3 project. I unintalled passenger on that gemset and added the PassengerRuby line into virt config. Any ideas?

**Comment by torreyj** [comment]
Stupid question... does passenger gem have to also be installed on gemset 1.9.3? Just don't run the module process correct?

**Comment by OnixGH** [comment]
No, you just need one 5.0.6 (and probably better to have it on the newer ruby 2.2.1), so that's fine.

But a 403 usually means that passenger isn't active for that location at all, which implies there's still something wrong with the apache config. What you wrote still looks correct (and even if it wasn't it would give a different error), so maybe another place in your config. Did you check the apache and passenger logs for errors?

**Comment by torreyj** [comment]
Yep, looking at the logs and they are not telling me anything. I even up'd the log level. The error log just shows when I shut it down and bring it up. No errors saying a thing on why it's not getting through.  I changed the module code into a mods passenger.conf and load file and enabled them. Hence I got the other site to work. He's my older sites with 1.9.3 ruby (virtual config)

https://gist.github.com/torreyj/2b977a43231e0e2883c9

**Comment by torreyj** [comment]
[Wed Apr 22 17:03:23.137702 2015] [autoindex:error] [pid 5581:tid 139935931655936] [client 74.84.110.222:55496] AH01276: Cannot serve directory /var/www/sites/petrierichardson.com/current/public/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.$

**Comment by torreyj** [comment]
Ok, just so you know. I know have everything setup they way we talked, and I reverted back to 4.0.59 with only one module running in my mods and PassengerRuby pointing to my 1.9.3 gem path... and it works.  So there's definite something wrong with version 5.0.6 with either permission or something in a config that doesn't get logged.  I'm more than happy to help figure this out, but for the time being, I'm ok with staying on 4.0.59 till this gets fixed.  Thanks

**Comment by OnixGH** [comment]
I don't know what to fix -- like I said 5.0.6 works fine for me with 1.9.3 and 2.2.1.

Does your 1.9.3 app have a `config.ru` as per the 5.x upgrade instructions? I remembered that's another way to get a 403, when passenger doesn't recognize the app.

**Comment by torreyj** [comment]
Ok, I must've looked right over that part. The config.ru file did the trick. You may close this issue. 

Just so you know, this was a very helpful post and I highly appreciate you helping me out with my issues with passenger.  My system will be in much better state because of your help. So I hope somebody else comes across this issue will see this and know what to do, because this issue took me days to figure out.  Thanks again

**Comment by caseol** [comment]
Thanks! This thrad resolved my problem as wel!
