### ISSUE TITLE
Passenger 5.0.6 filters out environment variables given in /etc/default/nginx

### ISSUE THREAD

**Issue by nileshtrivedi** [phusion/passenger#1488]
I am on Ubuntu 14.04. I first installed nginx package. Then I followed the instructions here: https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#install_on_debian_ubuntu and installed "nginx-extras" and "passenger" AFTER adding Phusion's APT repository.

I have environment variables added in /etc/default/nginx which /etc/init.d/nginx reads. This set up had been working on a different machine (where I am using Passenger 5.0.4 and did not install nginx-extras). But on this machine, these environment variables seem to be filtered out and are not available in my Rails application

These versions work correctly and I can access ENV in my rails app: nginx:1.6.2 with passenger:5.0.4
These don't work: 1.6.2 with passenger:5.0.6

**Comment by FooBarWidget** [comment]
Did you whitelist them using the Nginx `env` option? Otherwise Nginx may filter them. http://nginx.org/en/docs/ngx_core_module.html#env

**Comment by nileshtrivedi** [comment]
@FooBarWidget Interesting. I did not have to do anything like that on my other machine which is also using Nginx 1.6.2 (but from official Ubuntu repository, and not Phusion's ngins-extra package). Does the nginx binary built by Phusion have different behavior with respect to environment variables?

**Comment by FooBarWidget** [comment]
No, our Nginx binaries should not behave differently from the official Nginx.

Having said that, my experience with Nginx's environment variable clearing is that, although it's supposed to do that, in practice it times does and sometimes does not actually clear environment variables. I have yet to figure out why.

I recommend you to just whitelist the variables you need and call it a day.
