### ISSUE TITLE
403 Nginx error

### ISSUE THREAD

**Issue by jhonc33** [phusion/passenger#1491]
Hello, I recently installed Nginx 1.6.3 with Ruby 2.2.2 and Passenger 5.0.6. Every permission are setting ok, nginx process is running in current user, I don't know what is going on.

Any idea? Is Passenger 5.0.6 compatible with ruby 2.2.2 and nginx 1.6.3?

Regards,

**Comment by FooBarWidget** [comment]
Yes it is. Please post details about the error. In particular, messages from the error log file, messages on the command line, operating system details etc are important.

**Comment by jhonc33** [comment]
Yes, log file says this:

2015/04/28 10:34:06 [error] 978#0: *18 directory index of "/home/{myuser}/www/{myproject}/public/" is forbidden, client: 88.20.***.***, server: www.***.***, request: "GET / HTTP/1.1", host: "www.***.***"

I'm using Centos 7

**Comment by OnixGH** [comment]
Does your app have a config.ru?

**Comment by jhonc33** [comment]
ok, I fixed it setting chmod -R 755 to my user folder. My fault :(

Are this permission correct? Is secure?

Thanks,

**Comment by jhonc33** [comment]
Yes my app have config.ru too

**Comment by OnixGH** [comment]
@jhonc33 you wrote that it works for you now, so I'm closing the issue.

Permission 755 means other users who are logged in to the same system can read the files (but not write). You can try 700. In any case it doesn't look like a passenger issue.
