### ISSUE TITLE
 Installation problem in Debian with apt-get by setting codename to jessie

### ISSUE THREAD

**Issue by stvharman** [phusion/passenger#1493]
I upgraded to jessie (new release of debian) and wanted to install passenger. When I used the code name "jessie", the installation gave errors and stopped. Did anyone experience a similar problem?

I include this line in my /etc/apt/sources.list.d/passenger.list:
deb https://oss-binaries.phusionpassenger.com/apt/passenger jessie main

apt-get update gives this:

Ign https://oss-binaries.phusionpassenger.com jessie Release
Get:3 https://oss-binaries.phusionpassenger.com jessie/main Translation-en_US [162 B]
Get:4 https://oss-binaries.phusionpassenger.com jessie/main Translation-en [162 B]
Get:5 https://oss-binaries.phusionpassenger.com jessie/main Translation-en_US [162 B]
Get:6 https://oss-binaries.phusionpassenger.com jessie/main Translation-en [162 B]
Get:7 https://oss-binaries.phusionpassenger.com jessie/main Translation-en_US [162 B]
Get:8 https://oss-binaries.phusionpassenger.com jessie/main Translation-en [162 B]
Get:9 https://oss-binaries.phusionpassenger.com jessie/main Translation-en_US [162 B]
Get:10 https://oss-binaries.phusionpassenger.com jessie/main Translation-en [162 B]
Err https://oss-binaries.phusionpassenger.com jessie/main amd64 Packages       
  HttpError404
Get:11 https://oss-binaries.phusionpassenger.com jessie/main Translation-en_US [162 B]
Ign https://oss-binaries.phusionpassenger.com jessie/main Translation-en_US    
Get:12 https://oss-binaries.phusionpassenger.com jessie/main Translation-en [162 B]
Ign https://oss-binaries.phusionpassenger.com jessie/main Translation-en       
Fetched 15.9 kB in 14s (1,075 B/s)                                             
W: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/jessie/main/binary-amd64/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.

Subsequently apt-get install passenger does not work.

The current instructions on the passenger install side allows setting the codename to wheezy and even to the older debian versions. Why not jessie? It is the newest Debian release.

**Comment by FooBarWidget** [comment]
Sorry, we do not have packages yet for Debian Jessie. It's still a work in progress.
