### ISSUE TITLE
Disconnecting long-running connections for process

### ISSUE THREAD

**Issue by Akalinsky** [phusion/passenger#1495]
I keep getting this error with an app I deployed with passenger and apache2. The page intentionally takes a long time to load ( as long as 10 minutes) but this one times out after around 4. 

Here are the 3 lines in the error log
It sends a 503 Application did not send a complete response
Process no longer exists!
Disconnecting long-running connections for process 

I saw an issue with a similar error log text here: https://github.com/phusion/passenger/issues/1426
but a comment about this issue with apache2 indicated it wasn't an issue. However this issue prevents my app from working. 

Anyone know how to fix this?

**Comment by Akalinsky** [comment]
Well, turns out it was unrelated to passenger. Oops!

**Comment by pveluvolu** [comment]
What was the issue?
