### ISSUE TITLE
Passenger on Apache doesn't support the Rack Hijack API?

### ISSUE THREAD

**Issue by ylluminate** [phusion/passenger#1497]
We're having an issue wherein Nginx is working, but Apache is not for the Rack Hijack API.  https://github.com/voltrb/volt/pull/192#issuecomment-99210917

Can you confirm this @FooBarWidget or can we provide some additional information that will help to resolve this problem?

**Comment by FooBarWidget** [comment]
Hijacking in Apache should work, except if you're hijacking the socket for the purpose of WebSockets (because of #1202). Can you provide a reproducible example that highlights your problem?

**Comment by ylluminate** [comment]
Okay, so yes, it is indeed an issue with websockets and apache in this case.  I haven't had a chance to dig through too much.  <sigh> How soon are we looking at in terms of seeing a resolution to #1202?  I see a reference there for 5.0.5 and 5.1.0 on this issue...

**Comment by FooBarWidget** [comment]
Not very soon. My best guess would be that we can start working on that half a year from now.

There are workarounds though. You can run your app in Passenger Standalone (with the builtin engine) and setup a reverse proxy to Apache using mod_proxy.
