### ISSUE TITLE
Disable keep-alive upon encountering X-Sendfile or X-Accel-Redirect response headers

### ISSUE THREAD

**Issue by NeoPhi** [phusion/passenger#1498]
We recently rolled out the update from nginx 1.6.2 and passenger 5.0.6 to using nginx 1.6.3 and passenger 5.0.7. Post update we saw a dramatic spike in 502 Bad Gateway errors being logged. After downgrading to passenger 5.0.6 but still using nginx 1.6.3 the error rate returned to normal levels (i.e. almost 0). What additional information would be needed to help debug this issue?

**Comment by OnixGH** [comment]
Did you look in the nginx / passenger error log(s) to see what the source of the 502 error is?

**Comment by NeoPhi** [comment]
Thank you for asking me to look at the logs again. Digging past a log rotation, I noticed errors of this type:

```
[ 2015-05-05 06:38:21.3704 42745/7fcc38103700 age/Hel/Req/ForwardResponse.cpp:100 ]: [Client 2-11723] Error parsing application response header: invalid constant string
```

**Comment by OnixGH** [comment]
@NeoPhi thanks, there was a similar report (#1364) that was fixed during the beta.

@FooBarWidget this could be unrelated, but can you cross check the 5.0.7 changes against this?

**Comment by FooBarWidget** [comment]
@NeoPhi Does your app send X-Sendfile or X-Accel-Redirect headers?

**Comment by NeoPhi** [comment]
Yes we do in a couple of different places. A frequently called Rails controller uses the following logic:
```
    response.headers["X-Accel-Redirect"] = "/internal/legacy.php"
    render(:nothing => true)
```

**Comment by FooBarWidget** [comment]
Since 5.0.7, we assume that responses containing X-Sendfile or X-Accel-Redirect do not have a body. That fixes #1376. Unfortunately, Rails's `render :nothing => true` actually does send a body, namely a single byte. As a result, the connection keep-alive breaks.

We should fix this by disabling keepalive when we encounter X-Sendfile or X-Accel-Redirect.

**Comment by philipgiuliani** [comment]
When does 5.0.8 gets released? Im getting 502 extremely often, and im also setting `X-Accel-Redirect`.

**Comment by FooBarWidget** [comment]
We're shooting for next week wednesday. If you want to use it earlier, feel free to checkout the git repo, stable-5.0 branch.

**Comment by philipgiuliani** [comment]
Thanks for the fast response, i unfortunately installed it via apt-get and not by myself... :( I will wait for the release!

**Comment by FooBarWidget** [comment]
You can also build your own Debian packages against the source code in git. Clone git, checkout stable-5.0 branch, then use the `build` script in [passenger_apt_automation](https://github.com/phusion/passenger_apt_automation) to build packages.

**Comment by keepinmind** [comment]
Cant build from source, getting always: groupmod: GID '0' already exists
We need to downgrade too. The above bug is causing problems on our productive machine.

**Comment by FooBarWidget** [comment]
@keepinmind Can you post a more detailed excerpt of the error in question? Then maybe I can help you better.

**Comment by keepinmind** [comment]
Thanks a lot! We run into the passenger source folder the following command: 
`./packaging/debian/build -p . -w work -c cache -o output -a amd64 -d trusty pkg:all`
and get on our Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-32-generic x86_64) system:
```bash
+ mkdir -p /home/edicola/test/passenger/work
+ mkdir -p /home/edicola/test/passenger/cache
+ mkdir -p /home/edicola/test/passenger/cache/pbuilder/ccache
+ mkdir -p /home/edicola/test/passenger/output
+ Initializing ccache directory
groupmod: GID '0' already exists
```

**Comment by FooBarWidget** [comment]
Were you running the script as root? That hasn't been tested. We've always run it as a normal user.

I'll fix this particular error. Another tip: if it still fails, try running the script in Vagrant. Here is a tutorial: https://github.com/phusion/passenger_apt_automation#tutorial-building-your-own-packages

**Comment by keepinmind** [comment]
Running by normal user we get the following error: 
```bash
+ mkdir -p /home/edicola/test/passenger/work
+ mkdir -p /home/edicola/test/passenger/cache
+ mkdir -p /home/edicola/test/passenger/cache/pbuilder/ccache
+ mkdir -p /home/edicola/test/passenger/output
+ Initializing ccache directory
FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 
```

**Comment by keepinmind** [comment]
Vagrant is currently (for some reasons) no option. We solved other problems and get now other problems. On task (or running it directly) ```pbuilder-dist trusty amd64 *.dsc``` we get the following error: 
```bash
   dh_installdirs
	install -d debian/nginx
	install -d debian/nginx-doc
	install -d debian/nginx-common
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 1: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: etc/nginx: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 2: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: etc/nginx/sites-available: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 3: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: etc/nginx/sites-enabled: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 4: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: etc/nginx/conf.d: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 5: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: etc/ufw/applications.d: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 6: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: usr/share/nginx: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 7: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: var/log/nginx: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 8: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: var/lib/nginx: not found
/tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: 9: /tmp/buildd/nginx-1.6.3/debian/nginx-common.dirs: /usr/share/nginx/html: not found
dh_installdirs: problem reading debian/nginx-common.dirs: 
make: *** [binary] Error 127
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

**Comment by FooBarWidget** [comment]
> FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS? 

This is because the invoking user must be in the 'docker' group in order to be able to communicate with the Docker daemon. Try adding yourself to that group, then relogin and try again.

The pbuilder-dist error, did you get that from inside the build script?

What host OS are you running on?

**Comment by keepinmind** [comment]
Running on Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-32-generic x86_64). 
If you can create the packages ... would be great!

**Comment by FooBarWidget** [comment]
You can now find pre-relase package in the passenger-testing repository:

    deb https://oss-binaries.phusionpassenger.com/apt/passenger-testing trusty main

Please note: this repository is for testing purposes. I may nuke its contents at any time. So be sure to download the packages and save them locally, and be sure to remove the repository .list files afterwards.

Also note: although the packages have version 5.0.8, these are *prerelease* packages. They're not the final version. When 5.0.8 is officially released, apt-get won't tell you that there's an update because the version number is the same.

**Comment by keepinmind** [comment]
GREAT - solved our issue. Bug seems to be solved ;) 
You guys rock!

**Comment by rbatta** [comment]
I'm so glad I stumbled upon this, trying to solve my nginx 502 errors. The 5.0.8 pre-release definitely solved my issue as well. Thanks!!
