### ISSUE TITLE
Improperly shared database connections on Heroku (Postgres)

### ISSUE THREAD

**Issue by harmdewit** [phusion/passenger#1499]
During heavy load on Heroku we see a lot of `prepared statement "..." already exists` errors. [According to Heroku](https://devcenter.heroku.com/articles/postgres-logs-errors#pgerror-prepared-statement-a30-already-exists) this is caused by incorrectly shared database connections. In [this section](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#_smart_spawning_caveat_1_unintentional_file_descriptor_sharing) of your guide i read that each process makes a new database connection but i wonder if this also works in environments like Heroku.

We're seeing this error when getting a lot of traffic or during load tests. Especially pages that require a lot of database requests seem to produce a lot of errors.

Is there something like a unicorn `before_fork` and `after_fork` script that I'm missing or should I maybe disable prepared statements altogether?

**Comment by FooBarWidget** [comment]
The `PhusionPassenger.on_event(:starting_worker_process)` provides the right hook. See https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#_smart_spawning_caveat_1_unintentional_file_descriptor_sharing
