### ISSUE TITLE
Passenger 5 seems to ignore PASSENGER_APP_ENV

### ISSUE THREAD

**Issue by jamgold** [phusion/passenger#1505]
when I switched to passenger 5 (via homebrew) it started running my meteor app with flag --production even though I had set PASSENGER_APP_ENV to development. NODE_ENV was set correctly, but somehow passenger thought to spawn the app with the production flag having meteor complain about it

`Warning: meteor running in simulated production mode (--production). For real production use, bundle your app`

When I switched back to version 4.0.59 it returned back to the expected behavior.

**Comment by OnixGH** [comment]
This is not meteor complaining, it's a new warning in passenger 5.0.7. It's possible that it is also happening with 4 (`--production` causes minification, you can check it).

In any case it's best to use [passenger_app_env ](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#PassengerAppEnv)

**Comment by OnixGH** [comment]
Just to clarify my previous answer, `passenger_app_env` is the option when running passenger standalone with a custom config template. If you're just running `passenger start` then the option is `--environment XXX` (it overrides existing environment settings so even if those are set wrong it will still do what you want).

Btw. if you your app isn't bundled meteor will always set the node environment to development, setting the NODE_ENV has no effect either way.

**Comment by jamgold** [comment]
Thanks for the response. Unfortunately it is not only the error that is printed, it seems Phusion Passenger is treating it as production, because the Meteor is built as if in production (all javascript combined into one file) and code changes take a long time to reflect (build step).

There are other messages in the logs when running under 5.x

`[ 2015-05-06 18:49:18.5989 89566/0x108583000 Ser/Server.h:931 ]: [Client 4-1] Disconnecting client with error: client socket write error: Broken pipe (errno=32)`

None of this happens under 4.x

**Comment by OnixGH** [comment]
Did you try using the options I mentioned (`--environment development` or `passenger_app_env development;`)?

Yes, running meteor with `--production` causes minification, that is correct (meteor) behavior. The socket write errors are also normal (when clients disconnect without receiving the full response).

**Comment by jamgold** [comment]
I am running it under Apache2 with SetEnv PASSENGER_APP_ENV development

**Comment by OnixGH** [comment]
For apache the option I'm talking about is: `PassengerAppEnv development`

**Comment by jamgold** [comment]
Very nice, that was it. Under 4 SetEnv worked, but as the [documentation](https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#PassengerAppEnv) shows it should be `PassengerAppEnv development`. Totally missed that, thank you.
