### ISSUE TITLE
Agent crashes with certain POST responses under high load

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger#1513]
The crash produces a SIGSEGV with reason SEGV_ACCERR and a trace showing http_parse_host as the last method before/during the crash.

First reported against 5.0.5 on Arch linux in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/phusion-passenger/0iofvwnkacE

Reproduced with 5.0.7 on Ubuntu.

**Comment by FooBarWidget** [comment]
Can you submit the patch to [upstream](https://github.com/joyent/http-parser)?

**Comment by OnixGH** [comment]
Patch [accepted](https://github.com/joyent/http-parser/commit/f6f436a12edf209be806be8833bced9419d985ca)  upstream.
