### ISSUE TITLE
Passenger should log external IO operations to Union Station

### ISSUE THREAD

**Issue by ruphin** [phusion/passenger#1515]
We are tracking information to detect several database operations, but some other databases and external APIs are not tracked. It would be nice to track all IO operations in a catch-all way so operations on databases that are not integrated are still tracked.

In particular, these integrations are useful:
- Redis
- MongoDB
- Net::HTTP

**Comment by FooBarWidget** [comment]
Linux 2.6 has RUSAGE_THREAD. We can use that to track per-thread CPU time: http://linux.die.net/man/2/getrusage

**Comment by OnixGH** [comment]
See also: branch.

**Comment by tinco** [comment]
Welke branch @OnixGH ?

**Comment by OnixGH** [comment]
Hmm, looks like my reference was deleted, maybe during the refactoring to Union Station gems (https://github.com/phusion/union_station_hooks_core / https://github.com/phusion/union_station_hooks_rails ). Have a look at the branch "io" in the core one.
