### ISSUE TITLE
With Rails console stand alone on development env I get ERROR: Phusion Passenger doesn't seem to be running

### ISSUE THREAD

**Issue by dovadi** [phusion/passenger#1519]
After updating from passenger 4.0.59 to 5.0.8 (Rails 3-2-stable app, ruby 2.2.2p95, OSX) I get the following error

```
ERROR: Phusion Passenger doesn't seem to be running.
```

when I try to deliver a mail with ActionMailer in the Rails console.

I don't understand why passenger should run if I only want to use a console. And most of the time I use the standard rails server (WEBrick 1.3.1) on my development environment.

**Comment by dovadi** [comment]
BTW the error stays after rollback to Passenger 4.0.59 ...

**Comment by FooBarWidget** [comment]
Passenger shouldn't run when you use a console. I think you have some code in your app which for some reason shells out to one of the Passenger commands. Can you show the entire console output?

**Comment by dovadi** [comment]
Trying to reproduce this issue,  it only seems to happen when using the method name **restart** defined in actionmailer, for example:

```
NoreplyMailer.restart('dovadi.com').deliver
```
I get the following error message

```
ERROR: Phusion Passenger doesn't seem to be running. If you are sure that it is running, then the causes of this problem could be:

1. You customized the instance registry directory using Apache's PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir option, or Phusion Passenger Standalone's --instance-registry-dir command line argument. If so, please set the environment variable PASSENGER_INSTANCE_REGISTRY_DIR to that directory and run passenger-status again.
2. The instance directory has been removed by an operating system background service. Please set a different instance registry directory using Apache's PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir option, or Phusion Passenger Standalone's --instance-registry-dir command line argument.
```

With other method names it works fine and the error message doesn't appear

BTW despite the error message, the mail is sent and delivered

**Comment by FooBarWidget** [comment]
Can you show *entire* terminal output? Preferably a screenshot.

**Comment by dovadi** [comment]
![screen shot 2015-06-05 at 12 38 14](https://cloud.githubusercontent.com/assets/1466/8004398/d54aaec4-0b7f-11e5-830b-38dbd40c81f6.png)

**Comment by FooBarWidget** [comment]
How does your 'restart' method look like? How does your 'restart' template look like?

**Comment by dovadi** [comment]
Oops that's it. The problem lies with my 'restart'  template!

I'm sending a status and memory-stats of passenger (defined in my template).

I'm embarrassed, I was totally wrong-footed by the fact I discovered this issue when trying passenger 5 for the first time and assumed the problem lied with passenger. And I didn't realize the problem only happened with the restart mail until today. (Also, restarting the app hasn't occurred in more than a year and so I 'forgot' about the content of the mail.)

I'm sorry to have bothered you with this ...

Anyway, thanks for your time and help and for the great Passenger itself!
