### ISSUE TITLE
passenger-status: cannot find suitable Ruby interpreter

### ISSUE THREAD

**Issue by michaelrigart** [phusion/passenger#1521]
Passenger version: 5.0.8 - nginx
OS: Ubuntu 14.04
Ruby: 2.2 ( Brightbox )

I just installed passenger-nginx version 5.0.8 . When I run the command passenger-status, I got the following error: 

```
passenger_system_ruby: cannot find suitable Ruby interpreter
```

The ruby packages ( ruby2.2, ruby2.2-dev ) from the Brightbox repository where already installed before installing the passenger, nginx-extras packages.

When viewing the passenger-config script, the shebang indeed states:
#!/usr/bin/passenger_system_ruby

I don't know what the passenger_system_ruby binary does, but if it is used to detect the system ruby, it doesn't seem to detect it correctly.

On passenger 5.0.7, this was set to:
#!/usr/bin/ruby

Changing the shebang to /usr/bin/ruby fixes the issue.

I also noticed that the passenger_ruby option in nginx.conf states:
passenger_ruby /usr/bin/passenger_free_ruby

While up until v 5.0.7, this also pointed to /usr/bin/ruby

**Comment by FooBarWidget** [comment]
We're already aware of this issue, and we're planning a fix for 5.0.9. Please refer to https://github.com/phusion/passenger_apt_automation/issues/11
