### ISSUE TITLE
Interesting little benchmark

### ISSUE THREAD

**Issue by ylluminate** [phusion/passenger#1522]
@FooBarWidget thought this was just an interesting little (silly contrived) benchmark that I stumbled across showing Passenger slightly edging out Go: https://github.com/fukamachi/woo#phusion-passenger-ruby

**Comment by OnixGH** [comment]
You mean this one?
![https://github.com/fukamachi/woo/blob/master/images/benchmark-multicore.png]
(https://raw.githubusercontent.com/fukamachi/woo/master/images/benchmark-multicore.png)

**Comment by ylluminate** [comment]
Yes, but below (in the link I sent) it shows the details and parameters / args for the test.

**Comment by OnixGH** [comment]
Yeah, just wanted it to be more visually obvious what you were talking about ;)

Thanks for an easy to fix issue (Foo saw it too) ;)

**Comment by ylluminate** [comment]
LOL np.  I thought that Hongli would be interested from our previous chats.  Obviously as non-sensical as these non-contextual benchmarks are, they end up being hugely important.

**Comment by FooBarWidget** [comment]
An fast, non-blocking, alpha-quality HTTP server based on libev huh? Well, Passenger is a fast, non-blocking, *production*-quality HTTP server based on libev. ;)

**Comment by ylluminate** [comment]
LOL  Indeed!
