### ISSUE TITLE
Fails to maintein validation on uniqueness

### ISSUE THREAD

**Issue by amejiarosario** [phusion/passenger#1523]
I have multiple Nginx+Passenger instances [nginx.conf file here][1] and many models (more than 40) that has validations on uniqueness. e.g.

    class Ssid < ActiveRecord::Base
      validates :name, :presence => true
      validates :name, :uniqueness => true
      validates :name, :length => { :minimum => 1, :maximum => 32 }
      validate :is_name_valid?
      #... more stuff...
    end

When I hit the server with multiple concurrent requests (50) some of them get duplicated around 2+... I'm using this script to test it: http://pastebin.com/kwfXgdrp

**Is this a bug? or there's already a parameter to avoid this situation?** 

Setup:

 - Ubuntu-12.04
 - Phusion Passenger version 5.0.8
 - nginx/1.6.3: [nginx.conf here][1]
 - rvm 1.25.28
 - ruby 1.9.3p327
 - Rails 3.2.18

  [1]: http://pastebin.com/FqXgLxPc

**Comment by FooBarWidget** [comment]
This is not a Passenger bug. This is an inherent limitation in validates_uniquess_of. See http://izumi.plan99.net/blog/index.php/2008/09/20/validates_uniqueness_of-does-not-guarantee-uniqueness/
