### ISSUE TITLE
Empty Host header can crash passenger under apache

### ISSUE THREAD

**Issue by ambled** [phusion/passenger#1524]
I traced a crashing passenger agent issue to haproxy health checks that default to:

<code>
GET / HTTP/1.1
Host:

500 Internal Server Error
</code>

* Apache/2.4.7 (Ubuntu)
* Ruby ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
* Passenger passenger-5.0.8 / passenger-5.0.6
* HAProxy 1.5
* Ubuntu 14.04

Does not occur under passenger standalone and agents do restart, however it's a very light payload that can be a DOS vector.

It's not our code as it's reproducible with a newly (generated project)[https://github.com/ambled/apache-passenger-fail]

Process aborted! signo=SIGSEGV(11), reason=SEGV_MAPERR

**Comment by FooBarWidget** [comment]
Thanks for reporting this. Problem reproduced.

**Comment by FooBarWidget** [comment]
Issue fixed.
