### ISSUE TITLE
passenger-config restart-app colors issue

### ISSUE THREAD

**Issue by simison** [phusion/passenger#1526]
`passenger-config restart-app` leaves my terminal black+white:

![image](https://cloud.githubusercontent.com/assets/87168/7902996/08783dae-07d7-11e5-9896-797f223ccabe.png)

Default OSX Terminal 2.5.1.

:-(

To get my colors back, I can run `sudo passenger-status`.

**Comment by FooBarWidget** [comment]
Fixed.

**Comment by simison** [comment]
Thanks a bunch!
