### ISSUE TITLE
typo in passenger-install-apache2-module (commit 52a8efc847eadb2f892adda131bdfee5519529bb)

### ISSUE THREAD

**Issue by minoura3** [phusion/passenger#1527]
Errno::ENOTENT should be Errno::ENOENT

+    begin 
+      sestatus = `sestatus` 
+      getenforce = `getenforce` 
+    rescue Errno::ENOTENT 
+      return 
+    end

**Comment by FooBarWidget** [comment]
Thanks for reporting this. It's been fixed.
