### ISSUE TITLE
segfaults in passenger 5.0.9

### ISSUE THREAD

**Issue by codekitchen** [phusion/passenger#1530]
We upgraded one application from 5.0.8 to 5.0.9 last week, and we've been seeing about 6 segfaults per day per server since then. We rolled back all but one server, and built the debug version on that one server and captured some detailed crash logs.

All the segfaults have the same active thread stack trace. Here is an example: https://gist.github.com/codekitchen/84199c1f85e8abed39f1

The active thread is always on this line https://github.com/phusion/passenger/blob/release-5.0.9/ext/oxt/system_calls.cpp#L463 , at first glance it looks like bad params are being passed to the `select` syscall.

I will continue to try and get further information.

**Comment by OnixGH** [comment]
@codekitchen thanks for the report. It's easiest to search for "raise" in the stacktrace to find the offending thread.

In this case Thread 15 at "ext/common/ServerKit/HttpServer.h:1038" is trying to free a string that we recently added in 5.0.9 to support [leaving headers in the original case](https://github.com/phusion/passenger/issues/1436). We'll investigate.

**Comment by codekitchen** [comment]
Ah, I see what you mean. Thanks!

**Comment by OnixGH** [comment]
@FooBarWidget have a look at this, maybe you have a quick solution.

**Comment by OnixGH** [comment]
Upon first glance at the code it looks to me like a missing `psg_lstr_init(&header->origKey);` in `BufferBody.cpp`

**Comment by FooBarWidget** [comment]
Yes, that appears to be the case. I have committed a preliminary fix to the `GH-1530` branch, but haven't tested it yet. Could you take a look @OnixGH?

**Comment by OnixGH** [comment]
@FooBarWidget crash reproduced with Apache, and fixed after the commit.

@codekitchen I don't think this particular bit of code is reached with Nginx, can you confirm you are using Apache?

**Comment by codekitchen** [comment]
Yep, we are using Apache.

**Comment by OnixGH** [comment]
OK, then this is solved for 5.0.10!

**Comment by codekitchen** [comment]
Beautiful, thanks all.
