### ISSUE TITLE
first request slow when reload ngnix.

### ISSUE THREAD

**Issue by TangMonk** [phusion/passenger#1532]
I also try [stackoverflow](http://stackoverflow.com/questions/853532/slow-initial-server-startup-when-using-phusion-passenger-and-rails)

but the answer is seems too old, not works for passenger 4.

**Comment by FooBarWidget** [comment]
This is documented in the troubleshooting guide: https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#_why_does_the_first_request_take_a_long_time

**Comment by TangMonk** [comment]
thanks
