### ISSUE TITLE
PASSENGER_INSTANCE_REGISTRY_DIR not set in homebrew

### ISSUE THREAD

**Issue by CamJN** [phusion/passenger#1535]
In the latest homebrew install, `passenger-config` can't find the `PASSENGER_INSTANCE_REGISTRY_DIR` to run `restart-app` unless it's run as `root` w/ `sudo` which defeats the purpose of allowing app restarts without sudo.

And after some digging around I can't find the dir to set it to manually either.

**Comment by FooBarWidget** [comment]
You should set it to /tmp. On OS X, every user has its own private tmp directory, set via the TMPDIR environment variable. Apache doesn't run with a particular TMPDIR so it uses the default /tmp.

**Comment by CamJN** [comment]
Awesome, thank you.
