### ISSUE TITLE
SIGABRT doesn't terminate RackApp process

### ISSUE THREAD

**Issue by jaypatrickhoward** [phusion/passenger#1542]
Passenger 4.0.59 on CentOS 6.6 managing a Rails 3.2 / Ruby 2.1.5 application through Apache.

Sending SIGABRT to a hung process *does* cause a stack trace to be written to the Apache error log, but the process does not subsequently terminate.

Shouldn't the process die after writing its stack trace?

The behavior is the same when I send SIGABRT to a RackApp process that's completely idle.

**Comment by FooBarWidget** [comment]
Already fixed: https://github.com/phusion/passenger/commit/06938807883ad1c2210bfd9b9c342acabcfeeced
