### ISSUE TITLE
Ability to compile against upstream libev

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1544]
As discussed [here](https://github.com/phusion/passenger/commit/a84b6ae1a64d2ae552d3e03c69d295a166200cd0#commitcomment-11755952).

**Comment by msva** [comment]
ping?

**Comment by CamJN** [comment]
We'd be open to a PR but don't have time to work on this right now.

**Comment by msva** [comment]
> We'd be open to a PR but don't have time to work on this right now.

And is it still a requirement to sign something to have PR merged, or is it 
enough to just open a PR request?

**Comment by CamJN** [comment]
It is still required that you sign the [contributors agreement](https://www.phusion.nl/contributor) in order for a PR to be merged. We need to ensure there's never an ownership issue with any code in the Passenger codebase.
