### ISSUE TITLE
PhusionPassenger::Rack::ApplicationSpawner::Error

### ISSUE THREAD

**Issue by khanimdad** [phusion/passenger#1545]
I have deployed a rails app (on three servers)  with below config
a) Rails 4
b) Ruby 2.2.2
c) Nginx
d) Passenger - 5.0.10

But the error below shows older version of ruby and passenger, and am not sure whats happening and how to fix it, any help would be appreciated. Below is error detail, more can be seen here - http://www.unicircles.com/
	/home/deploy/.passenger/standalone/3.0.18-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/lib/phusion_passenger/rack/application_spawner.rb	135	in `rescue in start'
1	/home/deploy/.passenger/standalone/3.0.18-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/lib/phusion_passenger/rack/application_spawner.rb	130	in `start'
2	/home/deploy/.passenger/standalone/3.0.18-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/lib/phusion_passenger/spawn_manager.rb	253	in `block (2 levels) in spawn_rack_application'
3	/home/deploy/.passenger/standalone/3.0.18-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/lib/phusion_passenger/abstract_server_collection.rb	132	in `lookup_or_add'
4	/home/deploy/.passenger/standalone/3.0.18-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/lib/phusion_passenger/spawn_manager.rb	246	in `block in spawn_rack_application'
5	/home/deploy/.passenger/standalone/3.0.18-x86_64-ruby1.9.2-linux-gcc4.6.1-1002/support/lib/phusion_passenger/abstract_server_collection.rb

**Comment by FooBarWidget** [comment]
The error message indicates that you are not using Passenger 5, but Passenger 3. You probably have duplicate Passenger installations on your system that are conflicting with each other. Try uninstalling all Passenger instances, then reinstalling Passenger from scratch.
