### ISSUE TITLE
Log Passenger version to Union Station

### ISSUE THREAD

**Issue by tinco** [phusion/passenger#1550]
Can you check if the Passenger version is logged to Union Station? If not, could you add it to the xml info Passenger sends?

We would prefer something like `<LoggingAgent>Passenger 4.0.57</LoggingAgent>` over `<PassengerVersion>4.0.57</PassengerVersion>`, so we can discern between different logging agents.

**Comment by FooBarWidget** [comment]
This is now implemented.
