### ISSUE TITLE
Required key 'core_address' is missing

### ISSUE THREAD

**Issue by rnovak1988** [phusion/passenger#1551]
After updating to the newest version of Passenger, (5.0.11), this error is causing NGINX to hang, to the point where I can't even start/stop the processes. I can see in recent commits that this was recently added, so I know it has to do with passenger.

Here's the following line from my log file

2015/06/24 02:16:12 [alert] 4718#0: Required key 'core_address' is missing (-1: Unknown error)

This is *not* a configuration issue, since it was working flawlessly before, and there's absolutely no indication in the changelog, nor any documentation, that this is a new property that needs to be added to the configuration files.

**Comment by FooBarWidget** [comment]
You need to upgrade Nginx too. Passenger requires that the Nginx binary is compiled against the exact same Passenger version.

**Comment by rnovak1988** [comment]
The most recent version of NGINX available through official channels on ubuntu/debian is 1.8.0. Is it really a good idea to release passenger through official channels if the associated NGINX packages can't be updated at the same time? Especially without any warning that it could break?

**Comment by FooBarWidget** [comment]
I do not know what you mean by "official channels". The only APT channel that we consider official, is [our own APT repository](https://www.phusionpassenger.com/library/install/apt_repo.html), which always provides an up-to-date Nginx package compiled against the latest Passenger version. On every Passenger release, we release a new Nginx package.

**Comment by rnovak1988** [comment]
Thank you for your patience in this. As it turns out, the APT repositories don't override the installation in /opt/nginx when Passenger is updated through aptitude. If you ever face this in the future, it required uninstalling the conflicting packages, reinstalling through gem, and then recompiling nginx through the provided passenger-install-nginx-module. Sorry if I came across as crass or rude in any way.

**Comment by FooBarWidget** [comment]
No problem.
