### ISSUE TITLE
PhusionPassenger::Utils::TeeInput should support seek method

### ISSUE THREAD

**Issue by bachue** [phusion/passenger#1553]
When an http request comes with GZip compressed, some request handler use `Zlib::GzipReader` to read from `TeeInput` (because it's in `env['rack.input']`, e.g. https://github.com/schacon/grack/blob/master/lib%2Fgrack.rb#L243), then if someone call `request.body.rewind`, the error happens:
>
undefined method `seek' for #<PhusionPassenger::Utils::TeeInput:0x0000000d4c7ab8>

The reason is GzipReader calls `seek` to do `rewind`
> 
rewind()
Resets the position of the file pointer to the point created the GzipReader object. The associated IO object needs to respond to the seek method.

So can TeeInput implement `seek`? Thanks.

**Comment by OnixGH** [comment]
Technically `env['rack.input'] only needs to implement `rewind` so `Zlib::GzipReader` is apparently depending on an optional feature.

But we'll see what we can do :)
