### ISSUE TITLE
Stopping/restarting nginx corrupts Meteor MongoDB instance

### ISSUE THREAD

**Issue by ababra** [phusion/passenger#1564]
I'm running my Meteor app in native mode (not bundled) and with nginx integration (Digital Ocean Ubuntu 15.04 droplet). It works perfectly, however with one glaring issue:

If I stop or restart nginx (i.e. reboot the server, or do "service nginx stop"), my built-in MongoDB instance completely corrupts. I receive the following errors in my nginx error log:

    Unexpected mongo exit code 100. Restarting.
    Unexpected mongo exit code 100. Restarting.
    Unexpected mongo exit code 100. Restarting.

    Can't start mongod

    MongoDB had an unspecified uncaught exception.
    This can be caused by MongoDB being unable to write to a local database.
    Check that you have permissions to write to .meteor/local. MongoDB does
    not support filesystems like NFS that do not allow file locking.

Deleting the mongod.lock file does nothing. The only way to fix this is to reset the app (i.e. navigate to the project folder, do a "meteor reset"), then manually launch the app (execute "meteor" inside of the project folder) and restore the database using mongorestore. Afterwards shut down the app and re-launch using nginx (service nginx start).

What am I doing wrong here? What is the "clean" way to stop/start Meteor/MongoDB?

**Comment by FooBarWidget** [comment]
How do the file permissions in .meteor/local look like? Are they correct?

In any case, if you are using Meteor in production, then we recommend that you [use it in packaged/bundled mode](https://www.phusionpassenger.com/library/indepth/meteor.html). The [original Passenger-Meteor documentation](https://github.com/phusion/passenger/wiki/Phusion-Passenger%3A-Meteor-tutorial) mentioned that it is possible to run Passenger with Meteor in non-packaged mode, but that document was written in the Meteor 0.6/0.7 days. Somewhere in recent Meteor releases, they changed their scripts in such a way that we can no longer recommend that approach (for production at least). This new recommendation is reflected in our [new, work-in-progress documentation](https://www.phusionpassenger.com/library/).

**Comment by OnixGH** [comment]
Please reopen if there is new information that clearly points to Passenger having an issue.
