### ISSUE TITLE
Bad Gateway when "LOCATION" called

### ISSUE THREAD

**Issue by Wasaabi404** [phusion/passenger#1565]
What steps will reproduce the problem?
1. used on a login script that once "authenticated" tries to redirect to another place

What is the expected output? What do you see instead?
Expected output is the main screen after login.
What I get is "BAD GATEWAY":
code: `<h1>Bad Gateway</h1>`

What version of Phusion Passenger are you using? Which version of Rails? On
what operating system?
Phusion Passenger: passenger-5.0.14
Not rails - Straight ruby: 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
CentOS release 6.4 (Final)

Please provide any additional information below.

here is the log:

    [ 2015-07-18 14:05:15.0541 15560/7ffae29427e0 apa/Hooks.cpp:275 ]: File descriptor opened: 20
    [ 2015-07-18 14:05:15.0543 15533/7f1bd2401700 age/Cor/Req/TurboCaching.h:242 ]: Clearing turbocache
    [ 2015-07-18 14:05:15.0544 15533/7f1bd2401700 Ser/Server.h:241 ]: [ServerThr.1] New clients can be accepted on a server socket
    [ 2015-07-18 14:05:15.0545 15533/7f1bd2401700 Ser/Server.h:261 ]: File descriptor purpose: 34: Server ServerThr.1, client 1-2
    [ 2015-07-18 14:05:15.0546 15533/7f1bd2401700 Ser/Server.h:267 ]: [ServerThr.1] 1 new client(s) accepted; there are now 1 active client(s)
    [ 2015-07-18 14:05:15.0550 15533/7f1bd2401700 App/Gro/SessionManagement.cpp:329 ]: Session checked out from process (pid=15614, group=/data/www/masterplans.com/maps)
    [ 2015-07-18 14:05:15.0551 15533/7f1bd2401700 age/Cor/Req/CheckoutSession.cpp:114 ]: [Client 1-2] Session checked out: pid=15614, gupid=16d8331-OOi3gaopPH
    [ 2015-07-18 14:05:15.0551 15533/7f1bd2401700 age/Cor/Req/CheckoutSession.cpp:182 ]: [Client 1-2] Session initiated: fd=38
    [ 2015-07-18 14:05:15.0670 15533/7f1bd2401700 age/Cor/Req/ForwardResponse.cpp:100 ]:     [Client 1-2] Error parsing application response header: strict mode assertion failed
    [ 2015-07-18 14:05:15.0672 15533/7f1bd2401700 App/Socket.h:68 ]: File descriptor closed: 38
    [ 2015-07-18 14:05:15.0672 15533/7f1bd2401700 Ser/Server.h:909 ]: File descriptor closed: 34
    [ 2015-07-18 14:05:15.0675 15560/7ffae29427e0 FileDescriptor.h:83 ]: File descriptor closed: 20

the line that is reported at "log level 1" is:

    [ 2015-07-18 14:05:15.0670 15533/7f1bd2401700 age/Cor/Req/ForwardResponse.cpp:100 ]: [Client 1-2] Error parsing application response header: strict mode assertion failed

it happens when the following lines are called:

    self.headers['Location'] = "/#{page}"
    self.headers['Location'] << "?#{gets}" if gets

**Comment by OnixGH** [comment]
Can you tell us what the actual header output was at the time of the error? (loglevel 7?), Have you verified that your output meets the HTTP spec?

**Comment by OnixGH** [comment]
Please reopen if there is still a problem and you suspect a Passenger issue.
