### ISSUE TITLE
Passenger & nginx can't see environment variables in Ubuntu Linux

### ISSUE THREAD

**Issue by swarzynski** [phusion/passenger#1568]
Hi,

I have created some simple production server (Ubuntu 14.04) with ruby, rails, postgres and Passenger+nginx. I am not using rvm but precompiled ruby from brightbox (https://www.brightbox.com/docs/ruby/ubuntu/).
At the moment I am using Ruby 2.0 beacuse I have encountered some problems with 2.2 and Passenger (I will write about it in other thread).
After initial configuration of Passenger, when I opened site with my browser, I red:
```
Incomplete response received from application
```
from my simple Rails application.

/var/log/nginx/error.log:
```
[ 2015-07-26 10:13:08.3535 2674/7f550979c7c0 age/Wat/Main.cpp:1274 ]: Starting Passenger watchdog...
[ 2015-07-26 10:13:08.3620 2677/7fba2cf937c0 age/Cor/Main.cpp:957 ]: Starting Passenger core...
[ 2015-07-26 10:13:08.3622 2677/7fba2cf937c0 age/Cor/Main.cpp:234 ]: Passenger core running in multi-application mode.
[ 2015-07-26 10:13:08.3639 2677/7fba2cf937c0 age/Cor/Main.cpp:707 ]: Passenger core online, PID 2677
[ 2015-07-26 10:13:08.3723 2682/7f722fc457c0 age/Ust/Main.cpp:430 ]: Starting Passenger UstRouter...
[ 2015-07-26 10:13:08.3742 2682/7f722fc457c0 age/Ust/Main.cpp:311 ]: Passenger UstRouter online, PID 2682
App 2705 stdout: 
App 2705 stderr: sh: 1: 
App 2705 stderr: env: not found
App 2705 stderr: 
App 2720 stdout: 
App 2705 stderr: [ 2015-07-26 10:13:24.9162 2720/0x00000001dee9e0(Worker 1) utils.rb:85 ]: *** Exception RuntimeError in Rack application object (Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`) (process 2720, thread 0x00000001dee9e0(Worker 1)):
App 2705 stderr: 	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:534:in `validate_secret_key_config!'
App 2705 stderr: 	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:246:in `env_config'
App 2705 stderr: 	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:514:in `call'
App 2705 stderr: 	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
App 2705 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:94:in `process_request'
App 2705 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 2705 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 2705 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 2705 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
[ 2015-07-26 10:13:24.9168 2677/7fba267c3700 age/Cor/Req/Utils.cpp:95 ]: [Client 1-1] Sending 502 response: application did not send a complete response
```
In my secrets.yml I have:
```
    production:
      secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```
In my .bashrc on production server (username: "deploy"):
```
export DATABASE_USER_PASSWORD=>>passwordhere<<
export RAILS_ENV=production
export SECRET_KEY_BASE=>>keyhere<<
```
The issue was that nginx+passenger don't read .bashrc:
http://stackoverflow.com/questions/28912407/phusion-passenger-4-nginx-cannot-see-environment-variables-in-ubuntu-linux
...it was hard to find this answer.

When I moved env variables to .profile - problem dissapeared - application works, but still I get errors:
```
App 2705 stdout: 
App 2705 stderr: sh: 1: 
App 2705 stderr: env: not found
```
and I don't know what it is. Somebody could help me? Thank you in advance.

**Comment by FooBarWidget** [comment]
You can use [passenger_env_var](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_env_var) to set environment variables.

**Comment by OnixGH** [comment]
@swarzynski the answer you posted is outdated regarding environment variables, Passenger 5 has the option @FooBarWidget mentioned.

As for the env error, it's a program that normally exists in /usr/bin (you can query its location with the command "which env"), which is apparently isn't found by sh.

**Comment by deric** [comment]
I got same error with incorrect `PATH` with Ubuntu `ruby-2.0` package which does not replace previous ruby 1.9.3 installation. Make sure you set e.g. in `~/.profile` correct path to your gems:
```
export PATH="/var/lib/gems/2.0.0:$PATH"
```
