### ISSUE TITLE
Rubber Nginx Passenger deployment 'passenger' was not found

### ISSUE THREAD

**Issue by dcalixto** [phusion/passenger#1569]
** [out :: db01.y.com] zlib1g-dev is already the newest version.
 someone is getting this error on the log trying to deploy on ec2?

** [out :: db01.y.com] collectd is already the newest version.
 ** [out :: db01.y.com] monit is already the newest version.
 ** [out :: db01.y.com] ec2-ami-tools is already the newest version.
 ** [out :: db01.y.com] build-essential is already the newest version.
 ** [out :: app01.y.com] 
 ** [out :: app01.y.com] Reading state information...
 ** [out :: app01.y.com] 
 ** [out :: app01.y.com] E: Version '5.0.15' for 'passenger' was not found

my passenger_nginx

 passenger_version: '5.0.15'
    passenger_ruby: "#{ruby_path}/bin/ruby"
    nginx_log_dir: /mnt/nginx/logs
    use_ssl_key: false
    roles:
      passenger_nginx:
        packages: [libcurl4-openssl-dev, libpcre3-dev, nginx-extras, [passenger, "#{passenger_version}"]]

**Comment by FooBarWidget** [comment]
I do not know how Rubber works. Maybe you should ask the Rubber author what's going on?
