### ISSUE TITLE
native_support auto-build race condition

### ISSUE THREAD

**Issue by bensie** [phusion/passenger#1570]
Since updating to 5.0.15 (ubuntu trusty apt package), getting the following error:

`App 1654 stderr: Passenger RubyApp: /mnt/apps/myapp/current/public (production): symbol lookup error: /home/deploy/.passenger/native_support/5.0.15/ruby-2.2.2-x86_64-linux/passenger_native_support.so: undefined symbol: rb_thread_blocking_region`

Let me know if you need additional info!

**Comment by FooBarWidget** [comment]
It looks like your native_support wasn't being compiled properly. Try recompiling it:

    rm -f /home/deploy/.passenger/native_support/5.0.15/ruby-2.2.2-x86_64-linux/passenger_native_support.so
    passenger-config build-native-support

**Comment by bensie** [comment]
That did the trick. At what point does that compilation happen? I upgraded to 5.0.15 with `apt` the same way as usual...

**Comment by FooBarWidget** [comment]
It happens when your app is first executed, and Passenger detects that there is no native_support compiled for the current combination of Passenger version and Ruby version.

Are you using Apache or Nginx? What does your PassengerRuby/passenger_ruby option look like?

**Comment by bensie** [comment]
Using Nginx, with multiple apps running on each node. When adding the node back to the load balancer after the update, it can get pretty slammed with initial requests. Maybe a race condition where 2 different apps didn't see native_support compiled and they both attempted it and :boom:?

`passenger_ruby /opt/rubies/2.2.2/bin/ruby`

**Comment by FooBarWidget** [comment]
I can't see how a race condition would trigger this error, but I admit I haven't quite tested that case, so it's worth investigating.

**Comment by bensie** [comment]
FYI - The same thing happened on the upgrade from 5.0.15 to 5.0.16. Had to manually compile native_support on all web servers and restart Nginx.

**Comment by felixbuenemann** [comment]
Maybe the environment the app server runs in picks up a different ruby version?

If the problem occurs on the next upgrade, capture the output of
 ```sh
ldd /home/deploy/.passenger/native_support/5.0.17/ruby-2.2.2-x86_64-linux/passenger_native_support.so
```
before doing the manual recompile and post it here.

It should show you which version of libruby it was compiled against. The missing symbol points to something pre ruby 2.2.

**Comment by NeoPhi** [comment]
I had this same issue happen on an upgrade to 5.0.19. Definitely a race condition as you can see overlapping compiles in the nginx/error.log:

```
App 71010 stdout:
App 71010 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 71010 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable
)
App 71118 stdout:
App 71118 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 71118 stderr:
App 71118 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 71118 stderr:      Compilation succesful. The logs are here:
App 71118 stderr:      /tmp/passenger_native_support-1729nsa.log
App 71118 stderr: ruby: symbol lookup error: /home/web/.passenger/native_support/5.0.19/ruby-2.0.0-x86_64-linux/passenger_native_support.so: undefined symbol: rb_defi
App 71010 stderr:      Compilation succesful. The logs are here:
App 71010 stderr:      /tmp/passenger_native_support-1m4cu8g.log
App 71010 stderr: ruby: symbol lookup error: /home/web/.passenger/native_support/5.0.19/ruby-2.0.0-x86_64-linux/passenger_native_support.so: undefined symbol: rb_defi
```

**Comment by FooBarWidget** [comment]
The problem has now been fixed.

**Comment by bensie** [comment]
Thanks @FooBarWidget!
