### ISSUE TITLE
Deploying to Sub-URI (possibly just outdated documentation)

### ISSUE THREAD

**Issue by squirrelsRduck** [phusion/passenger#1572]
What steps will reproduce the problem?
1. Create a Ruby on Rails app, with the newest versions.
2. Try launching with Passenger and Apache HTTPD
3. Want to use a sub-uri, but the documentation emphasizes that a virtual host already exists.  Yet, I cannot get a Virtual host to be accepted with passenger.

What is the expected output? What do you see instead?
The latest Passenger fails to cooperate with VirtualHosts on HTTPD, so I cannot follow the "deploy to sub-uri instructions" on the Passenger website (is the documentation perhaps behind a version?)

What version of Phusion Passenger are you using? Which version of Rails? On
what operating system?

Newest of each.  On, RHEL 7.1.

Please provide any additional information below.

Not sure how to get this deployed to a sub-uri, as my httpd.config file has no virtualHost when it works, and fails to run when i add a virtualHost.  I notice that in the Passenger gem, theres a file called apache_default_site.conf, with a VirtualHost, but modifying that file seems to have no effect.

**Comment by OnixGH** [comment]
Which documentation are you referring to exactly? The latest documentation recommends [installing Passenger through yum](https://www.phusionpassenger.com/library/install/apache/install/oss/el7/).

See also [this section](https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/#deploying-an-app-to-a-sub-uri) about sub-uri deployment.

**Comment by squirrelsRduck** [comment]
I was referring to the documentation you linked to, regarding the sub-uri deployment.  I used the ruby gem passenger instead of yum though.

can virtual hosts be used in conjunction with the latest version of passenger?  The link you provided states:
" For example, suppose that you already have a virtual host for the application" ....

Yet, I do not have a virtual host.  I'm honestly new to this topic.  Can somebody confirm that VirtualHosts can be run in conjunction with the latest version of Passenger?  Passenger never asked me to type up a VirtualHost in the installation instructions, and it works perfectly fine at the Root URL, without a VirtualHost.  I cannot seem to run "sudo service httpd restart" successfully when i try adding a VirtualHost, and the error messages aren't very useful

Thanks!

**Comment by OnixGH** [comment]
The question "Can somebody confirm that VirtualHosts can be run in conjunction with the latest version of Passenger?" doesn't really make sense, you don't "run" them together :)

A VirtualHost is simply a way to scope configuration statements. I don't have any issues with the latest Passenger and VirtualHost configurations. You can probably also just leave the <VirtualHost> and </VirtualHost> lines out and use the rest of the example, although the fact that you're getting an error suggests some kind of mistake in your config which might be unrelated to the VirtualHost part.

**Comment by squirrelsRduck** [comment]
Ok, thanks.  I will keep trying then!  I had been including a virtual host within my already working config file, and consequently had to repeat some of the information within that virtual host, as per the VirtHost examples.  Possibly that repeat of info was causing error.  Ill try perhaps putting a virtual machine set of tags around thr entire config file or something like that.  Thanks again, just had to make sure this is actually possible to make work.

**Comment by squirrelsRduck** [comment]
figured it out.  To anybody having the same confusion, u don't need thr virtusl host tags.  Also, if u don't use VH tags, exclude the Location line's and the Alias line
