### ISSUE TITLE
Passenger error returning status 200

### ISSUE THREAD

**Issue by frankh** [phusion/passenger#1574]
Passenger version: 5.0.14
Ruby version: 2.1.3p242
Nginx Version: 1.8.0

Steps to reproduce: 

  1. set up nginx to run a rails app (or any app?) with passenger
  2. start nginx
  3. ```sudo rm /tmp/passenger.rpRaAYb/agent.s/core```

Outcome:

Even though ```curl localhost``` shows an error page, ```curl -I localhost``` shows that it's returning a 200 status code.

Expected:

The error page should be served with a 500 status code

**Comment by OnixGH** [comment]
Hmm, I get a consistent HTTP 502 "Bad Gateway" for both commands, which is the expected behavior when the nginx module cannot reach the Passenger core.

The 200 sounds like a cached reply? Either way, I hope you understand that we can't guarantee consistent Passenger behavior if you "randomly" remove parts of it at runtime ;)

**Comment by frankh** [comment]
Deleting that file was just the simplest way of recreating the problem I'm having.

I think I have a memory leak in my app because every now and then passenger crashes with "cannot fork, out of memory", and then the nginx error log gets filled with "connect() to unix:/tmp/passenger. rpRaAYb/agents.s/core failed (2: No such file or directory) while connecting to upstream"

For some reason nginx is still showing the passenger 500 error page, but with a 200 status.

**Comment by OnixGH** [comment]
Aha, well, deleting file that may recreate the error message, but it doesn't actually recreate the circumstances of the system during an Out Of Memory. For example, deleting the file under normal circumstances doesn't lead to a 500, but rather a 502.

Moreover, with OOM, nginx itself can also go into undefined behavior when it can't allocate memory anymore, and strange things can start to happen outside of Passenger's control.

Passenger does offer ways to help work around application memory leaks, e.g. using the [memory limit](https://www.phusionpassenger.com/library/config/reference/?a=passengermemorylimit) or [max requests](https://www.phusionpassenger.com/library/config/apache/reference/#passengermaxrequests) option (although of course solving them in the app is best :)).

**Comment by FlowerWrong** [comment]
+1

**Comment by adlerfaulkner** [comment]
+1
