### ISSUE TITLE
passenger-install-apache2 not detecting macports Apache

### ISSUE THREAD

**Issue by Behinder** [phusion/passenger#1575]
I filled the bug on MacPorts side about apache2 port. They told it is required to isolate every instance of httpd installed in system as much as possible.
However, when I install macports apache2 (still 2.2 because for some reason 2.4 is not ready for production) script detect osx version of apache only (/usr/sbin/httpd) instead of /opt/local/....

**Comment by FooBarWidget** [comment]
This happens if MacPort's apxs2 command isn't in PATH. You need to tell Passenger about it: https://www.phusionpassenger.com/library/install/apache/customizing_compilation_process.html#forcing-location-of-command-line-tools-and-dependencies
