### ISSUE TITLE
Passenger Rails url prefix causing no route matches

### ISSUE THREAD

**Issue by squirrelsRduck** [phusion/passenger#1576]
I have a Rails application that is rooted inside a folder called convergeops. My Phusion Passenger is setup to serve the PassengerBaseURI to /convergeops.

80% of the time, everything works fine, but every now and then I get a No route matches error as shown in this StackOverflow Question:
http://stackoverflow.com/questions/31886854/passenger-rails-url-prefix-causing-no-route-matches?noredirect=1#comment51691327_31886854

Any idea why I might be getting this routing error?

**Comment by OnixGH** [comment]
Please use the github issue reporter only for suspected Passenger malfunctions. This is a rails error about your non-existent routes in your application.

You can post to the [community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for general help.
