### ISSUE TITLE
Make "friendly error pages" work without loading resources from external sites

### ISSUE THREAD

**Issue by msva** [phusion/passenger#1580]
See discussion at https://github.com/phusion/passenger/commit/11880047e1894bcadf47c4f7cc6c4eb75515bd79#commitcomment-12230295

**Comment by FooBarWidget** [comment]
Whoops, I lost track of that issue because of email overload, sorry about that. @OnixGH what do you think? I think it's fine.

**Comment by OnixGH** [comment]
@FooBarWidget not sure which solution you're asking about, but I'd welcome a PR (and a signed [contributor agreement](http://www.phusion.nl/forms/contributor_agreement)) from @msva :)
