### ISSUE TITLE
deprecation on rails 4.2

### ISSUE THREAD

**Issue by u007** [phusion/passenger#1584]
DEPRECATION WARNING: `#quietly` is deprecated and will be removed in the next release. (called from process_request at /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-5.0.15/lib/phusion_passenger/rack/thread_handler_extension.rb:94)
  Rendered text template (0.0ms)

please help to fix,
thank you :)

**Comment by FooBarWidget** [comment]
Although the backtrace mentions Passenger's source code, #quietly isn't actually called from Passenger, but from the app. Please examine your app's codebase or your middleware stack.
