### ISSUE TITLE
Error during WebSocket handshake: 'Connection' header is missing

### ISSUE THREAD

**Issue by jamgold** [phusion/passenger#1585]
I am deploying passenger: `stable 5.0.15 (bottled), HEAD` behind apache2 on OS X.

Unfortunately I am suddenly (since 5.0.15) seeing  

`WebSocket connection to 'ws://url/sockjs/363/gbi0lxnx/websocket' failed: Error during WebSocket handshake: 'Connection' header is missing`

when accessing my node js (Meteor) websites. I have seen other tickets saying that passenger + apache2 does not support websockets, but wanted to make sure this is the reason for this.

**Comment by OnixGH** [comment]
Can you try running Passenger in standalone mode (builtin engine), and set up a reverse proxy in Apache (mod_proxy)? That should avoid WebSocket related problems while using Apache.

**Comment by jamgold** [comment]
Actually same issue

```
Server version: Apache/2.4.16 (Unix)
Server built:   Jul 22 2015 21:03:09

/usr/local/Cellar/passenger/5.0.15 (3280 files, 148M)
  Poured from bottle
```

followed instructions from [here](https://www.phusionpassenger.com/library/deploy/standalone/reverse_proxy.html)

```
    <VirtualHost *:80>
        ServerName www.example.com
        DocumentRoot /Volumes/Web/Meteor/start_bootstrap
        ProxyPass / http://127.0.0.1:4000/
        ProxyPassReverse / http://127.0.0.1:4000/
        ProxyPreserveHost on
        ErrorLog /private/var/log/apache2/startbootstrap_error_log
        CustomLog /private/var/log/apache2/startbootstrap_access_log combined
    </VirtualHost>
```

Accessing http://localhost:4000 works, but http://www.example.com generates 

```
WebSocket connection to 'ws://www.example.com/sockjs/737/nporlpiu/websocket' failed: Unexpected  response code: 400
```

**Comment by OnixGH** [comment]
Isn't that a different error message? "Unexpected  response code: 400" vs. "'Connection' header is missing"

**Comment by jamgold** [comment]
I be damned, it is. This is a meteor application, do I need to specify a specific flag when starting passenger in --daemonize mode?

**Comment by OnixGH** [comment]
Not that I know of, and certainly not something that would cause a 400/Bad Request. If you set the passenger log level to 7, you can see what the request looks like exactly, and take it from there.

**Comment by jamgold** [comment]
This is what I see
```
[ 2015-08-27 08:01:53.1851 65625/0x10448e000 age/Cor/Req/SendRequest.cpp:34 ]: [Client 2-20] Sending headers to application with http_session protocol
[ 2015-08-27 08:01:53.1851 65625/0x10448e000 age/Cor/Req/SendRequest.cpp:561 ]: [Client 2-20] Header data: "POST /sockjs/246/11dtbi4c/xhr HTTP/1.1
Connection: close
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9
accept-encoding: gzip, deflate
dnt: 1
referer: http://www.example.com/
accept: */*
accept-language: en-us
origin: http://www.example.com
cookie: _passenger_route=384346076; __utma=180318519.1983931012.1397582462.1404868219.1405966309.36; _ga=GA1.2.1983931012.1397582462
x-forwarded-host: www.example.com
host: www.example.com
x-forwarded-server: www.example.com
content-length: 0
x-forwarded-for: x.x.x.x
X-Forwarded-For: 127.0.0.1

"
```

but apache log has something interesting that should help

```
[Wed Aug 26 12:26:54.875551 2015] [proxy:error] [pid 22785] (61)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:4000 (127.0.0.1) failed
[Wed Aug 26 12:26:54.875746 2015] [proxy:error] [pid 22785] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Wed Aug 26 12:26:54.875759 2015] [proxy_http:error] [pid 22785] [client 50.143.140.25:50629] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: http://www.example.com/
```

**Comment by OnixGH** [comment]
It's a bit difficult to work with log excerpts, for example the Apache lines are from the 26th while the Passenger ones are from the 27th?

"No body to send is" correct, since the content-length in the request is 0. The headers don't look wrong to me, but I also don't see any logging about an error 400.

**Comment by jamgold** [comment]
I think I should close the issue at this time, because it works without apache, so clearly passenger is not at fault.

**Comment by OnixGH** [comment]
Alright, I closed it; you can always reopen later or post another more specific one :).
