### ISSUE TITLE
Unix socket sets REMOTE_ADDR to "unix:"

### ISSUE THREAD

**Issue by edbo** [phusion/passenger#1588]
This is a problem since any application code that tries to parse the remote address as an IP will fail.

Either setting this to 127.0.0.1 or an empty string would actually be better.

Right now this crashes our app because we use the better_errors gem which tries to parse this.

To reproduce this try to run any rails app with the better_errors gem installed.

**Comment by OnixGH** [comment]
A simple app with Passenger and the `better_errors` gem doesn't reproduce this problem. `REMOTE_ADDR` shows that it's set to `127.0.0.1`. Can you elaborate on what you're doing exactly?

**Comment by hassan-k** [comment]
You need to run the passenger application with a `--socket-file` option. This will set the `REMOTE_ADDR` to `unix:` and will raise the `IPAddr::InvalidAddressError`

Running the application with `--address` will set the `REMOTE_ADDR` to the address and will not cause the error.

Maybe the problem is with better_errors gem. Who am I to say? is setting `REMOTE_ADDR` to "unix:" any significant within passenger itself?

**Comment by hassan-k** [comment]
You can work around this by setting `"envvars": { "REMOTE_ADDR": "" }` within a `Passengerfile.json`, which allows the better_errors gem to behave itself.

**Comment by edbo** [comment]
Thanks so much hassan. This:

```
"envvars": { "REMOTE_ADDR": "127.0.0.1" }
```

worked a charm. May I suggest small update to the docs to make this clear? I tried editing the page here:

https://www.phusionpassenger.com/library/config/standalone/reference/

under --socket? I tried to make an edit but it isn't obvious where that content comes from.

**Comment by OnixGH** [comment]
If you press edit on the Passenger Library page, then you end up in `passenger_library/source/config/reference/`, which has subdirs for standalone, nginx and apache (this happens to be one that's only in standalone).

In the end this was an issue though with the better_errors gem not being able to deal with a REMOTE_ADDR that is not an IP, and that should be reported/fixed there (Passenger Library is not for tracking bugs in other components).
