### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by LuisDominguez** [phusion/passenger#1590]
passenger-install-apache2-module

he say

* Checking for Apache 2...
      Found: no

but i have apache2 -v

Server version: Apache/2.4.16 (Ubuntu)
Server built: 

error:

EXCEPTION: No such file or directory - /usr/local/apache2/bin/apr-1-config (Errno::ENOENT)

have idea?

**Comment by FooBarWidget** [comment]
That is a problem with your Apache configuration. We autodetect various tools in your Apache toolchain through the 'apxs' command. In particular, we run the following command to autodetect the location of apr-1-config:

    apxs -q APR_CONFIG

It looks like your 'apxs' command outputs a nonexistant filename, which means your installation is broken. How it is broken, I have no idea, but try reinstalling it from scratch.
