### ISSUE TITLE
Passengerfile.json not read on passenger stop

### ISSUE THREAD

**Issue by hassan-k** [phusion/passenger#1593]
I like how you can set the configurations in the Passengerfile.json for `passenger start`. but when you run `passenger stop` it doesn't pick up the `pid_file` or `port`. It would be good to have this ability especially if passenger is being run as a daemon.

**Comment by hobodave** [comment]
:+1:

**Comment by mwpastore** [comment]
+1

**Comment by lakesare** [comment]
+1

**Comment by FooBarWidget** [comment]
This feature has been implemented and will be available in 5.0.22.

**Comment by mwpastore** [comment]
Thank you!
