### ISSUE TITLE
Not a Passenger Issue (was: Nginx + Passenger unescape special charactor)

### ISSUE THREAD

**Issue by tonilin** [phusion/passenger#1594]
I have a file provided by rails + Refile names `test@3x.jpg`

When sending the request, It didn't unescape on development(rails default server): 

```
Refile::App: [2015-06-01 19:14:21 +0800] GET "/574866afc423ab5c49a5e92b448ffd2adab7aa0b/store/fill/320/160/0f4a162a236026c6c5cc2dc1d559067c8c94a3c4c530d7d6542d99987b5d/test%403x.jpg" 200 163.5ms
```

But on production, nginx + passenger auto decode the url:

```
Refile::App: [2015-06-01 19:14:21 +0800] GET "/574866afc423ab5c49a5e92b448ffd2adab7aa0b/store/fill/320/160/0f4a162a236026c6c5cc2dc1d559067c8c94a3c4c530d7d6542d99987b5d/test@3x.jpg" 200 163.5ms
```

Why nginx + passenger auto decode the url? Can I disable it?

**Comment by OnixGH** [comment]
Nginx supports URL rewriting and it auto decodes URLs in anticipation of that.

Since Passenger version [5.0.9](https://blog.phusion.nl/2015/06/04/phusion-passenger-5-0-9/), the undecoded URL is sent to applications, but only if nginx didn't do any rewriting on it. There's not much else we can do without breaking URL rewriting.

**Comment by tonilin** [comment]
But I didn't do any rewriting in my nginx config:

```nginx
server {
  listen      80;
  server_name project.com default_server;
  root        /home/project/current/public;

  access_log /home/project/shared/log/access.log;
  error_log  /home/project/shared/log/error.log;

  rails_env "staging";

  passenger_enabled on;

  location ~* ^/(assets|images)/ {
    expires 1y;
    add_header Cache-Control "public";

    if ($request_filename ~* ^.*?\.(eot|ttf|woff|svg|otf|woff2)$) {
      add_header Access-Control-Allow-Origin *;
    }
    break;
  }
}
```
