### ISSUE TITLE
docs: passenger_log_level wrong unit megabytes

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1597]
https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_log_level

> passenger_log_level megabytes;

That should probably say sth. like *number*, *integer* or *level*.

**Comment by felixbuenemann** [comment]
@OnixGH Ooops, didn't know about the passenger_library repo, otherwise I'd done a PR myself.

**Comment by OnixGH** [comment]
No worries, there's a big "edit this page" link at the bottom of every library page, but it's apparently still easy to miss (tips welcome :)).

**Comment by felixbuenemann** [comment]
The pages are very long, so put the button somewhere more easily visible, like at the top or int he sidebar.
