### ISSUE TITLE
Implement graceful in Passenger Standalone (builtin)

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1598]
Passenger Standalone does not currently support graceful shutdown. We should implement support for this. This may require changes in [daemon_controller](https://github.com/FooBarWidget/daemon_controller).
- When using the Nginx engine, this can be made to work by sending [SIGQUIT](http://nginx.org/en/docs/control.html) instead of SIGTERM.
- I have not yet investigated how this can be made to work with the builtin engine. Having said that, the ServerKit::HttpServer class supports graceful shutdown. We may not have properly integrated this in CoreMain.cpp or in the Watchdog.

**Comment by meoooh** [comment]
Any changes?

**Comment by CamJN** [comment]
No, there haven't been any changes on this front yet.

**Comment by PikachuEXE** [comment]
When will this be implemented...

**Comment by PikachuEXE** [comment]
Also `SIGQUIT` seems being used for printing 
https://github.com/phusion/passenger/blob/62a4d728b656b6bf385dcad6dff62ab4632c66d9/doc/users_guide_snippets/analysis_and_system_maintenance.txt#L35
a backtrace without aborting

**Comment by PikachuEXE** [comment]
Please look at #1956 for possible implementation for Nginx engine

**Comment by CamJN** [comment]
Added in 5.1.6
