### ISSUE TITLE
Application did not send a complete response

### ISSUE THREAD

**Issue by Nirupma** [phusion/passenger#1605]
Nginx Error log file

Passenger Gem Version - 5.0.13

App 28370 stderr: [ 2015-09-09 14:42:00.9612 28402/0x0000000ca634f0(Worker 1) utils.rb:85 ]: *** Exception RuntimeError in Passenger RequestHandler's client socket (can't modify string; temporarily locked) (process 28402, thread 0x0000000ca634f0(Worker 1)):
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/utils/unseekable_socket.rb:188:in `read'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/utils/unseekable_socket.rb:188:in `read'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/message_channel.rb:177:in `read_scalar'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler/thread_handler.rb:217:in `parse_session_request'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler/thread_handler.rb:143:in `accept_and_process_next_request'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
App 28370 stderr: [ 2015-09-09 14:42:00.9876 28402/0x0000000ca634f0(Worker 1) utils.rb:85 ]: *** Exception RuntimeError in Passenger RequestHandler's client socket (can't modify string; temporarily locked) (process 28402, thread 0x0000000ca634f0(Worker 1)):
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/utils/unseekable_socket.rb:188:in `read'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/utils/unseekable_socket.rb:188:in `read'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/message_channel.rb:177:in `read_scalar'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler/thread_handler.rb:217:in `parse_session_request'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler/thread_handler.rb:143:in `accept_and_process_next_request'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 28370 stderr:       from /usr/local/lib/ruby/gems/1.9.1/gems/passenger-5.0.13/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
[ 2015-09-09 14:42:00.9879 28332/7fe5aeffd700 age/Cor/Req/Utils.cpp:95 ]: [Client 5-647] Sending 502 response: application did not send a complete response

**Comment by FooBarWidget** [comment]
> Exception RuntimeError in Passenger RequestHandler's client socket (can't modify string; temporarily locked)

Which version of Ruby are you using? The above error message seems to indicate a bug in the Ruby interpreter. Try upgrading Ruby to the latest patchlevel.

**Comment by Nirupma** [comment]
Hi Hongli Lai,

My application is written in Rails 3.0.3 and we are using ruby 1.9.2-p290

**Comment by FooBarWidget** [comment]
1.9.2 is very old and has many bugs. Please upgrade to at least the latest 1.9.3 patchlevel. But even 1.9.3 has been end-of-lifed, so you really should upgrade to 2.2.2.

**Comment by thegranddesign** [comment]
@FooBarWidget I'm on 2.2.3 and am getting basically this same error.  What do you need to help get it tracked down?

```
App 20552 stderr: [ 2016-04-27 18:47:40.1021 7673/0x007ffa703fd6e0(Worker 1) utils.rb:87 ]: *** Exception Rack::Timeout::RequestTimeoutError (Request ran for longer than 15000ms) (process 7673, thread 0x007ffa703fd6e0(Worker 1)):
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/utils/unseekable_socket.rb:245:in `eof?'
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/utils/unseekable_socket.rb:245:in `eof?'
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/utils/tee_input.rb:198:in `socket_drained?'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:39:in `method_override_param'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:27:in `method_override'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:15:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/static.rb:116:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/rack-timeout-0.2.4/lib/rack/timeout.rb:108:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/skylight-0.7.1/lib/skylight/middleware.rb:61:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/engine.rb:518:in `call'
App 20552 stderr: 	from /var/cache/gems/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:165:in `call'
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
App 20552 stderr: 	from /opt/passenger/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
[ 2016-04-27 18:47:45.0078 20503/7f5faac24700 age/Cor/App/Poo/AnalyticsCollection.cpp:105 ]: Process (pid=7673, group=/var/www/myapp.com/rails_application/public (production)) no longer exists! Detaching it from the pool.
[ 2016-04-27 18:47:45.0080 20503/7f5faac24700 age/Cor/CoreMain.cpp:794 ]: Checking whether to disconnect long-running connections for process 7673, application /var/www/myapp.com/rails_application/public (production)
App 7739 stdout:
App 7739 stdout: source=rack-timeout id=0a9766a6514246db1757de68f828daaa timeout=15000ms state=ready
App 7739 stdout: Started GET "/lists?filter%5Bfeatured%5D=true" for 73.224.244.99 at 2016-04-27 18:51:16 +0000
App 7739 stdout: Processing by MyController#index as application/vnd.myapp
App 7739 stdout:   Parameters: {"filter"=>{"featured"=>"true"}}
App 7739 stdout: Completed 200 OK in 173ms (Views: 103.9ms | ActiveRecord: 65.2ms)
App 7739 stdout: source=rack-timeout id=0a9766a6514246db1757de68f828daaa timeout=15000ms service=323ms state=completed
```

**Comment by thegranddesign** [comment]
BTW, that request should come back in about 200ms (and does in development).

**Comment by thegranddesign** [comment]
@FooBarWidget it looks like it has something to do with HTTP/2.  If I disable HTTP/2 in the Nginx server, the request goes through as expected.

**Comment by thegranddesign** [comment]
Also, this _seems_ to only affect non-GET requests (although I could be wrong).

**Comment by FooBarWidget** [comment]
@thegranddesign Which Passenger version is that? If you are not on the latest, please try again on the latest version.

**Comment by thegranddesign** [comment]
@FooBarWidget I'm on 5.0.25 so it's a fairly recent version.  Only a couple months old.  I've got it burned into my image at 5.0.25 and would have to rebuild with the new version.  Probably won't be able to get to it for a week or so.

**Comment by OnixGH** [comment]
@thegranddesign actually, the error in your log is wildly different from the original report (`RuntimeError in Passenger RequestHandler's client socket (can't modify string; temporarily locked)` versus `RequestTimeoutError (Request ran for longer than 15000ms)`).

I suggest you open a new issue and fill in the associated information so we have a better picture of what your setup is. Furthermore, I'd advise you to run a trace with log level 7 to see exactly what the request data is and what's happening in the response.

**Comment by thegranddesign** [comment]
I can do that!
