### ISSUE TITLE
Passenger 5.0.18 not working with multiple vhosts/multiple rubies in apache2

### ISSUE THREAD

**Issue by tomvleonard** [phusion/passenger#1607]
I have a server running Apache 2 on Fedora 8. It hosts three rails websites. One is running 1.9.3-p551 and the other two are running 1.8.7-p374. Yes, it's quite the antique.

There are three vhost stanzas and each has it's own PassengerRuby entry. It's been working fine on Passenger 4.0.59. However, after upgrading to 5.0.18 only one of the websites, the rails app running 1.9.3, spun up. The other two showed apache test pages. When I downgraded back to Passenger 4.0.59 everything worked again.

Other possibly pertinent info:
- Whatever is failing is failing silently. I get no errors. Nothing in /var/log.
- The passenger apache2 module was installed with 1.8.7-p374 in both cases.
- The rubies are managed with RVM.
- I did not test this with incremental downgrades because this is a production server and had to get it operational asap. I couldn't tell you exactly which (presumably) minor release introduced the bug.

**Comment by FooBarWidget** [comment]
Maybe the 1.8.7 website is written in Rails <= 2.3? As documented in the release notes, Passenger 5 has dropped support for Rails versions earlier than 2.3. Rails 2.3 is still supported, but it is required that the app has a config.ru.

**Comment by tomvleonard** [comment]
Sorry for the delayed response. That is correct. The two websites that failed with Passenger 5.0.8 both run Rails 2.3. I'll look into setting up the Rails 2.3 applications with config.ru. Thank you very much!
