### ISSUE TITLE
Check Installation Issues

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#1611]
Cannot check the installation of Passenger.  5.0.18.  

		HQ:motherlode_ruby rich$ sudo passenger-config validate-install
		/Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'passenger' (>= 0) among 11 total gem(s) (Gem::LoadError)
		Checked in 'GEM_PATH=/var/root/.gem/ruby/2.2.0:/Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0', execute `gem env` for more information
			from /Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
			from /Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
			from /Users/rich/.rvm/gems/ruby-2.2.3/bin/passenger-config:22:in `<main>'
			from /Users/rich/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
			from /Users/rich/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
		HQ:motherlode_ruby rich$ sudo passenger-memory-stats
		/Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'passenger' (>= 0) among 11 total gem(s) (Gem::LoadError)
		Checked in 'GEM_PATH=/var/root/.gem/ruby/2.2.0:/Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0', execute `gem env` for more information
			from /Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
			from /Users/rich/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
			from /Users/rich/.rvm/gems/ruby-2.2.3/bin/passenger-memory-stats:22:in `<main>'
			from /Users/rich/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
			from /Users/rich/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
		HQ:motherlode_ruby rich$ brew info nginx --with-passenger
		nginx: stable 1.8.0 (bottled), devel 1.9.4, HEAD
		HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
		http://nginx.org/
		/usr/local/Cellar/nginx/1.8.0 (7 files, 3.0M) *
			Built from source with: --with-passenger
		From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nginx.rb
		==> Dependencies
		Required: pcre ✔
		Recommended: openssl ✔
		Optional: passenger ✔, libressl ✘
		==> Options
		--with-debug
			Compile with support for debug log
		--with-gunzip
			Compile with support for gunzip module
		--with-libressl
			Build with libressl support
		--with-passenger
			Compile with support for Phusion Passenger module
		--with-spdy
			Compile with support for SPDY module
		--with-webdav
			Compile with support for WebDAV module
		--without-openssl
			Build without openssl support
		--devel
			Install development version 1.9.4
		--HEAD
			Install HEAD version
		==> Caveats
		Docroot is: /usr/local/var/www

		The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
		nginx can run without sudo.

		nginx will load all files in /usr/local/etc/nginx/servers/.

		To activate Phusion Passenger, add this to /usr/local/etc/nginx/nginx.conf, inside the 'http' context:
			passenger_root /usr/local/opt/passenger/libexec/lib/phusion_passenger/locations.ini;
			passenger_ruby /usr/bin/ruby;

		To reload nginx after an upgrade:
			launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist
			launchctl load ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist
		Or, if you don't want/need launchctl, you can just run:
			nginx

**Comment by FooBarWidget** [comment]
You have two Passenger installations on your system, one via Homebrew, one via RubyGems. The RubyGems one is broken and is interfering. Uninstall it first with 'gem uninstall passenger'.

**Comment by daBee** [comment]
You just told me to use that to install it.  So at this point, I need to ask you which version should I use.  I don't mind using either, as long as it works with nginx in the nginx mode of multiple projects.

**Comment by OnixGH** [comment]
@daBee The point is to use only one, or only the other method, or they will interfere with each other. You could uninstall both, make sure they are gone, and then install via the method you want to use.

**Comment by daBee** [comment]
Yeah I tried that and now nginx uninstall has issues.  I even uninstalled Homebrew.  OSX package managers don't hold anything towards other platforms'.
