### ISSUE TITLE
Cannot access process.env.['PATH'] from within node

### ISSUE THREAD

**Issue by serkandurusoy** [phusion/passenger#1612]
I'm using nginx integration mode (5.0.18) and having trouble accessing `process.env.['PATH']` from within a node(0.10.40) app.

If I run the app manually (outside passenger) it is fine, but when I run it with passenger, it returns `undefined`

Is this something I should work around using other methods or is this a passenger bug/configuration?

**Comment by FooBarWidget** [comment]
That's because Nginx clears environment variables unless you explicitly whitelist it. Read up on the Nginx `env` configuration option.

**Comment by serkandurusoy** [comment]
Thank you, I'm doing that right now. You might perhaps want to make it more clear in the deployment articles in the library.

**Comment by serkandurusoy** [comment]
@FooBarWidget would you mind sharing the url to that article about environment variables being cleared. I do want to read up on it but the new library, although making it easier to follow along as guides, makes it kind of hard to find specific pieces of information :(

**Comment by OnixGH** [comment]
@serkandurusoy that's why we made the search box :) If you search for "environment" there it points you to the intended one: https://www.phusionpassenger.com/library/indepth/environment_variables.html

**Comment by serkandurusoy** [comment]
I've been using the search box of course. I'm dealing with a server so it shoud be evident I'm at least vaguely familiar with finding my way around in the web.

And with all due respect, that document (and I had already read the complete beast multiple times and I love it and [even promote it](https://forums.meteor.com/search?q=phusion%20passenger)) sounds like a general introduction to environment variables and if one knows how to set/read them, then it does not have much value.

The only part where it *slightly suggests* a hint at my problem is

> The per-process nature of environment variables some implications. When you set environment variables in your bashrc or other bash startup files…
> …the web server usually does not see them, because the web server tends to be started from init scripts, not from bash.

The "the web server usually does not see them" part here reads like "web servers in general, but hey we are passenger so this does not apply to us. And I'm still not sure if you meant to include passenger in that term "web servers" or not, and if you did, why don't you plainly say it.

Reading on to the nginx section of that document, there is no mention of clearing environment variables and required ones needing *explicit whitelisting* as suggested in the previous comment here. In fact, the notion of *whitelisting* is not even hinted to anywhere.

I also don't agree about having to go over to the nginx site for documentation. It is a *valid* way of ending the discussion here, but I'd expect higher from you guys, based on the evident quality of your past and current work, including documentation.

And well, yes, if we are configuring something nginx specific, of course, we shoud look in there, but then again the whole library concept there creates this feeling that this is my one stop shop everything passenger and should I actually need going over to another documentation, the friendly documentation should explicitly make that clear *where relevant*.

To be honest, I had never used nginx before passenger. I'm seeing (from a passenger user's perspective) nginx as some cool little package that comes bundled with passenger. I know it is stated multiple times elsewhere that passenger is not a web/app server, but a process manager (and I've quoted that many times in my aforementioned promotions), but it is a cheap shot when used as means to avoid documentation inquiries such as this one. Come on, now, I do know you *are* better than that.  Don't let me down!

So this whole long post, as much as it sounds like some sort of quirky rant, is a - rather peculiarly happy - statement of unmet expectation, whose level had already been set by you. So deal with it ;)

**Comment by OnixGH** [comment]
@serkandurusoy hehe, point taken on the expectations, thanks ;)

It's actually a question we see more often, but have not been able to catch in a way that accomodates various skill levels (believe me it varies a lot:)). And honestly, for all the time as we've invested in setting up the Passenger Library it could still use some more love, especially the in-depth section. In fact you're more then welcome to drop a few lines there that you think would have helped you in this :)

**Comment by serkandurusoy** [comment]
@OnixGH I'm silent only because I'm neck-deep in a project. But keeping this in my inbox as a to-do item.

I'm only experienced with Meteor, though. So I won't feel confident editing sections that are related to nginx and definitely not apache. So if I send a PR for the library, it definitely will be lacking its counterparts on other sections.

How should I proceed?

**Comment by serkandurusoy** [comment]
@OnixGH btw, if you are willing to use cookies or localstorage for the library, we could do a one time thing like this http://www.shiguenori.com/material/seekAttention/

**Comment by FooBarWidget** [comment]
I've opened a ticket in the `passenger_library` project as a reminder.

**Comment by serkandurusoy** [comment]
Great, thanks!
