### ISSUE TITLE
Passenger fails to compile (5.0.18 on Solaris x86/SPARC)

### ISSUE THREAD

**Issue by JamesTheBard** [phusion/passenger#1616]
Ruby version: 1.9.3p551
Passenger version: 5.0.18 (via RubyGem)
Operating System: Solaris 11.2 (SRU 14.5)
Architecture: AMD64

Steps to reproduce:
1) After ensuring that 'gcc' is installed, run the 'passenger-install-apache2-module' script and wait.
2) 'c++' errors out (error code 1)

Last part of the output for the build is here: https://gist.github.com/JamesTheBard/33567801b63aa8d96c34

The SPARC architecture compile seems to be stopping at the same place with the same error, but I don't have access to my `dev` server at the moment.

**Comment by FooBarWidget** [comment]
Can you paste the entire output? The output you have pasted is truncated and does not include enough information for us to analyze the problem.

**Comment by JamesTheBard** [comment]
@FooBarWidget, the entire installation run is attached as another gist.  The output was a touch large.
https://gist.github.com/JamesTheBard/fd934f05f45744d59458

**Comment by FooBarWidget** [comment]
Try re-running the installer with this environment variable

EXTRA_CXXFLAGS=-DBOOST_MATH_DISABLE_STD_FPCLASSIFY

**Comment by JamesTheBard** [comment]
Got a bit farther this time, however there's a new error. I appreciate the help. https://gist.github.com/JamesTheBard/b94bd18528d9dd30f05f

**Comment by FooBarWidget** [comment]
Sorry for the late response, I've been very busy lately.

To help me analyze this error, could you tell me what /usr/include/math.h line 13 says?

**Comment by JamesTheBard** [comment]
Sorry for the delay @FooBarWidget, here's the 13th line of math.h.

`#include <iso/math_c99.h>`

**Comment by FooBarWidget** [comment]
Hm, that line doesn't seem to explain the error. Maybe it's easier if I install Solaris myself and test things. Is Solaris freely available nowadays, or at least cheaply available without having to purchase hardware? Do you know how I can install your specific Solaris version? Or maybe can you help me gain access to a test system that exhibits the problem?

**Comment by JamesTheBard** [comment]
Right now, the issue is the same on both architectures so you could spool up an x86 VM with Solaris on it and be completely good.  They have a download to a Solaris 11.2 VM which would match what I've got running in my current VM.  I could also spool up a VM on my local ESXi server if need be.

**Comment by FooBarWidget** [comment]
Okay. I have schedule some time later this week, or some time next week if my plan doesn't work out, to install a Solaris VM.

**Comment by JamesTheBard** [comment]
I appreciate all of the help.  If there's anything I can do to help please let me know.

**Comment by FooBarWidget** [comment]
I have installed Solaris 11.2 x86_64 and used gcc/g++ 4.5.2 to compile Passenger. However I am not able to reproduce the problem. Compilation is totally successful. I didn't even have to set -DBOOST_MATH_DISABLE_STD_FPCLASSIFY.

However, I see that you are mixing up gcc and Sun Studio c++. Maybe it would help if you set `CXX=g++`?

Having said that, even if *I* mix up gcc and Sun Studio c++, I still don't get any compilation problems. Only if I use Sun Studio cc do I get compilation problems... with Solaris's own headers.

**Comment by JamesTheBard** [comment]
That is weird, I wonder if we're on the same SRU.  I'll take a look at the box and set the CXX to g++.

**Comment by JamesTheBard** [comment]
I ran through the module compilation with the CXX flag set to "g++", ran into the same error. I'm downloading the VirtualBox OVA for Solaris 11.2 and see what the difference between the two images are.

**Comment by JamesTheBard** [comment]
So, there are differences but I'm evidently not doing something correctly with respect to setup as I'm getting the same compilation error.  I installed `gcc-c++-48`, `ruby-21`, and `library/security/openssl`, the ran the `gem install passenger --no-rdoc --no-ri`.  Afterwards, it's the standard `passenger-install-apache2-module` and keep the defaults.

**Comment by FooBarWidget** [comment]
I didn't install gcc-c++-48 directly. Instead I installed the GNU development tools group which installed a whole bunch of tools, including gcc. Could that be related?

**Comment by JamesTheBard** [comment]
I'm spinning up a fresh Solaris 11.2 VM and installing `pkg:/group/feature/developer-gnu` to see if that changes my issue.

**Comment by JamesTheBard** [comment]
Alright, good news, then bad news.  The good news is that it compiled without issue on Solaris 11.2 SRU 14.5, the bad news is that `passenger-status` is throwing an error (`Errno::EBADF`).

https://gist.github.com/JamesTheBard/8a14e9c7203b43577dbd

**Comment by FooBarWidget** [comment]
It looks like Solaris does not support flock. I will find a solution for
that, maybe use fcntl locks.

As for SRU 14.5: you were on that version oroginally. So do you know what
causes the compilation problem? Did installing the gnu group fix it?

Sent from my Android phone.

Alright, good news, then bad news. The good news is that it compiled
without issue on Solaris 11.2 SRU 14.5, the bad news is that
passenger-status is throwing an error (Errno::EBADF).

https://gist.github.com/JamesTheBard/8a14e9c7203b43577dbd

—
Reply to this email directly or view it on GitHub
<https://github.com/phusion/passenger/issues/1616#issuecomment-149041421>.

**Comment by JamesTheBard** [comment]
Yeah, on both the "evaluation" VM and the fully updated VM it was due to the `pkg:/group/feature/developer-gnu` not being installed.  Once that was put onto the VMs it compiled like a charm.  I'm going to verify on the SPARC architecture today.

**Comment by FooBarWidget** [comment]
Let's move the discussion to #1643.

**Comment by JamesTheBard** [comment]
The SPARC compile worked, figured out the issue on Solaris on _when_ it won't compile: the server cannot have the `developer/gcc-4/gcc-*-48` and `system/library/gcc/gcc-*-48` libraries and packages installed.

**Comment by FooBarWidget** [comment]
Do you mean that developer/gcc-4/gcc-*-48 and system/library/gcc/gcc-*-48 are mutually incompatible? Or do you mean that neither developer/gcc-4/gcc-*-48 or system/library/gcc/gcc-*-48 may be installed, and that they're not actually part of group/feature/developer-gnu despite what their names imply?

**Comment by JamesTheBard** [comment]
They're not part of the `group/feature/developer-gnu` feature package.  I spooled up a virginal VM and installed the `group/feature/developer-gnu` package, and then compared it against the SPARC machine that I was working on and noticed that the new VM had no `gcc-*-48` packages whereas the SPARC one was loaded with them.  I went ahead and uninstalled all of the GCC 4.8 packages from the machine, ensured that GCC 4.5 was installed, and everything worked out perfectly.

**Comment by FooBarWidget** [comment]
So we can conclude that the gcc 4.8 package on Solaris 11.2 is broken, right?

**Comment by JamesTheBard** [comment]
I would say so, yes.  I want to try to remove the 4.5 packages and get a clean 4.8 setup on the VMs and see if that would work, but having the `gcc-*-48` packages installed on Solaris 11.2 makes the compile very angry.

**Comment by FooBarWidget** [comment]
Coming from a Linux world, it's very strange to hear that OS-packaged software doesn't work. Does Oracle support this? Will they fix this any time soon? If not, then it may be a good idea to put a check in Passenger that warns against such a broken compiler.

**Comment by JamesTheBard** [comment]
Honestly, I couldn't tell you the answer to that one.  Usually, the packages work as intended, but I do most of my development on other platforms.  Maybe having the `gcc-*-48` stuff installed confuses things if the standard `gcc-*` packages are installed?  It's one of the more unusual things I've encountered...
