### ISSUE TITLE
Stuck with Sessions: 1

### ISSUE THREAD

**Issue by JasonBarnabe** [phusion/passenger#1621]
Since upgrading to Passenger 5.0.18 (CentOS 6.6, Rails), my site has been going down every few days. In the nginx log, I see:

```
[ 2015-09-27 23:32:36.4234 17309/7f5e2abfd700 age/Cor/Req/CheckoutSession.cpp:236 ]: [Client 10-52676] Returning HTTP 503 due to: Request queue full (configured max. size: 100)
```
However, `passenger-status` reports nothing in the queue:
```
[www@mysite ~]$ passenger-status
Version : 5.0.18
Date    : 2015-09-27 23:32:48 +0000
Instance: 8MvPlgUW (nginx/1.8.0 Phusion_Passenger/5.0.18)

----------- General information -----------
Max pool size : 8
App groups    : 1
Processes     : 8
Requests in top-level queue : 0

----------- Application groups -----------
/home/www/mysite/public:
  App root: /home/www/mysite
  Requests in queue: 100
  * PID: 13478   Sessions: 1       Processed: 7499    Uptime: 8h 19m 20s
    CPU: 0%      Memory  : 327M    Last used: 7h 6m 17
  * PID: 20515   Sessions: 1       Processed: 2240    Uptime: 8h 2m 9s
    CPU: 0%      Memory  : 295M    Last used: 7h 6m 6s a
  * PID: 28619   Sessions: 1       Processed: 488     Uptime: 7h 39m 47s
    CPU: 0%      Memory  : 200M    Last used: 7h 6m 3s
  * PID: 29059   Sessions: 1       Processed: 83      Uptime: 7h 38m 19s
    CPU: 0%      Memory  : 187M    Last used: 7h 6m 2s
  * PID: 5537    Sessions: 1       Processed: 26      Uptime: 7h 15m 16s
    CPU: 0%      Memory  : 224M    Last used: 7h 6m 0s
  * PID: 9359    Sessions: 1       Processed: 194     Uptime: 7h 5m 58s
    CPU: 0%      Memory  : 208M    Last used: 7h 5m 29s
  * PID: 2652    Sessions: 1       Processed: 7329    Uptime: 43m 20s
    CPU: 9%      Memory  : 259M    Last used: 9m 56s ago
  * PID: 11210   Sessions: 1       Processed: 2172    Uptime: 23m 20s
    CPU: 5%      Memory  : 207M    Last used: 8m 44s ago
```
It also seems odd to have processes that haven't done anything in 7 hours.

Less than a minute before the "Request queue full" entries started, this was in the log, unsure if related:
```
App 11102 stderr: [ 2015-09-27 23:23:44.8973 11210/0x0000000775d878(Worker 1) utils.rb:86 ]: *** Exception Errno::ECONNRESET in Rack response body object (Connection 
reset by peer) (process 11210, thread 0x0000000775d878(Worker 1)):
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/utils/unseekable_socket.rb:114:in `write'
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/utils/unseekable_socket.rb:114:in `write'
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/rack/thread_handler_extension.rb:303:in `process_body'
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/rack/thread_handler_extension.rb:143:in `process_request'
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_n
ext_request'
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 11102 stderr:       from /home/www/.rvm/gems/ruby-2.2.2/gems/passenger-5.0.18/lib/phusion_passenger/utils.rb:112:in `block in create_thread_and_abort_on_exception
'
[ 2015-09-27 23:24:23.6833 17309/7f5e5a1fc700 age/Cor/Req/CheckoutSession.cpp:236 ]: [Client 5-52522] Returning HTTP 503 due to: Request queue full (configured max. s
ize: 100)
```
Results of `--show=` `backtraces`, `server`, and `union-station` at https://gist.github.com/JasonBarnabe/86128084d3a46efb2e2c

**Comment by FooBarWidget** [comment]
Are you using Union Station? If so, try upgrading to 5.0.20 which contains many Union Station related fixes.

**Comment by JasonBarnabe** [comment]
I'm not familiar with Union Station, so I'm guessing I don't use it.

**Comment by FooBarWidget** [comment]
According to the `passenger-status --show=requests` output, Passenger was waiting until the application has sent the response, but the application didn't even send out headers. What does /style do? Can it do anything that blocks for several hours? Were there any database or network issues?

Can you also try the tips at http://blog.phusion.nl/2012/09/21/the-right-way-to-deal-with-frozen-processes-on-unix/ to debug your stuck processes?

**Comment by JasonBarnabe** [comment]
No, there's nothing that _should_ block for that long, but I suppose it's possible that there were issues on the system. I also saw some resource shortages on the server, but I'm currently unsure if these are the cause or a symptom of this problem.

I will keep an eye on it and provide additional information if it reoccurs.

**Comment by tramuntanal** [comment]
We're having the same issue in one of the projects apache2 is serving through passenger, the whole site blocks but the server load is very low. The rest of the applications this very same passenger serves are working normally.
We're on passenger 5.0.18

**Comment by OnixGH** [comment]
@tramuntanal how did you conclude that this is the same issue? Are you getting "request queue full" messages? Did you look at the tips in the link that @FooBarWidget posted? Are you sure it's not just the one application that gets stuck?

**Comment by tramuntanal** [comment]
Hi @OnixGH,
Yes, we were getting "request queue full". Yesterday we moved to puma, with the same exact rails code, and we have not had any more blockages. Before we were having problems every 1 or 2 hours, depending on the number of requests.

**Comment by antoineco** [comment]
We just hit this issue as well. The load on our application is relatively low, nevertheless 6 out of 20 servers are in this state:

```
Version : 5.0.21
Date    : 2015-12-29 10:29:46 +0000
Instance: QFuuCiUG (nginx/1.8.0 Phusion_Passenger/5.0.21)

----------- General information -----------
Max pool size : 6
App groups    : 1
Processes     : 6
Requests in top-level queue : 0

----------- Application groups -----------
/app/public (production):
  App root: /app
  Requests in queue: 100
  * PID: 131     Sessions: 1       Processed: 405     Uptime: 10m 30s
    CPU: 1%      Memory  : 198M    Last used: 9m 47s ago
  * PID: 141     Sessions: 1       Processed: 1088    Uptime: 10m 30s
    CPU: 2%      Memory  : 201M    Last used: 8m 2s ago
  * PID: 151     Sessions: 1       Processed: 841     Uptime: 10m 29s
    CPU: 2%      Memory  : 209M    Last used: 7m 10s ago
  * PID: 167     Sessions: 1       Processed: 191     Uptime: 10m 29s
    CPU: 0%      Memory  : 189M    Last used: 7m 12s ago
  * PID: 179     Sessions: 1       Processed: 773     Uptime: 10m 29s
    CPU: 2%      Memory  : 206M    Last used: 5m 44s ago
  * PID: 198     Sessions: 1       Processed: 1451    Uptime: 10m 28s
    CPU: 3%      Memory  : 217M    Last used: 3m 41s ago
```

**Comment by OnixGH** [comment]
@antoineco the output you posted doesn't necessarily mean there is a problem with Passenger. For example, if your application stops returning responses, this will also happen.

Please make sure that it's not a problem in your application by following the steps outlined in: http://old.blog.phusion.nl/2012/09/21/the-right-way-to-deal-with-frozen-processes-on-unix/

If you do think it's a Passenger problem, please post information about your setup (platform, what language is your app, ruby/rails/nodejs/etc. versions, how often does it happen, anything in particular worth mentioning), and:
- the output of `passenger-status --show=requests` (on a stuck server)
- any errors from the logfile
- any other helpful output like backtraces from crash-watch

**Comment by antoineco** [comment]
Hi @OnixGH, I was not finger pointing, I just found this Issue by searching the repo and though we'd also fall in that category. I really appreciate your guidance and quick answer.

* The app is indeed stuck in a state where processes are `WAITING_FOR_APP_OUTPUT`: https://gist.github.com/antoineco/283c3fcd10a3dd1432a6
* No obvious error in the app logs
* The rest will require some deeper investigation

I'll post here any relevant information I find on that topic.

**Comment by antoineco** [comment]
So, crash-watch can not attach to my Passenger processes (it's a Ruby App btw), I can only attach to Passenger core, which doesn't show anything.

I managed to generate a backtrace by sending a SIGQUIT to one process though (see updated Gist)

**Comment by OnixGH** [comment]
@antoineco thanks, that's very helpful.

One trick with the `passenger-status --show=requests` output is that you can search for `"session_checkout_try" : 1`, which will lead you to the exact URLs that are blocked ("path", above it). In your case it looks like a typical "app got stuck while waiting for a third party".

**Comment by antoineco** [comment]
Indeed, Facebook to be more precise. Thanks for the article and info @OnixGH, I learned a lot from it :clap:
