### ISSUE TITLE
nginx rake task misses '-fPIC' compiler flag

### ISSUE THREAD

**Issue by antoineco** [phusion/passenger#1623]
The `nginx` rake task compiles the Passenger support files without the `-fPIC` compiler flag. This prevents `nginx-*` packages from being built with Passenger support against the [Debian nginx sources](http://anonscm.debian.org/cgit/collab-maint/nginx.git/).
```
/usr/bin/ld: /nginx/debian/modules/passenger/buildout/common/libpassenger_common/Logging.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/nginx/debian/modules/passenger/buildout/common/libpassenger_common/Logging.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
objs/Makefile:273: recipe for target 'objs/nginx' failed
make[3]: *** [objs/nginx] Error 1
```

The following compiler flags are used on Debian by default:
```
--with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-fPIE -pie -Wl,-z,relro -Wl,-z,now'
```

My workaround is to add the `-fPIC` flag in [`build/common_library.rb:256`](https://github.com/phusion/passenger/blob/master/build/common_library.rb#L256):
```
libboost_oxt_cflags = "-fPIC"
```

Does it sound reasonable enough to make this flag a default?

**Comment by FooBarWidget** [comment]
What you're actually looking for is `-fPIE`, not `-fPIC`. Debian sets the hardening flag `-fPIE` for address layout randomization in executables. `-fPIC` is only necessary for shared libraries.

`-fPIC`/`-fPIE` reduces performance on x86, so I'd rather not enable it by default. However you can pass that flag using `EXTRA_CXXFLAGS`: https://www.phusionpassenger.com/library/install/nginx/customizing_compilation_process.html#adding-additional-compiler-or-linker-flags

Speaking of Debian packages, have you considered merging our changes from https://github.com/phusion/passenger_apt_automation?

**Comment by antoineco** [comment]
Thanks for the detailed answer @Foobarwidget, I really appreciate it. I didn't know about Phusion's apt automation repo, it's definitely something I want to take a look at.

Cheers :+1:
