### ISSUE TITLE
brew install nginx --with-passenger fails with Passenger 5.0.20

### ISSUE THREAD

**Issue by ivdma** [phusion/passenger#1624]
`brew install nginx --with-passenger` does not install contents of `/usr/local/opt/passenger/libexec/lib` path which is required for nginx configuration. It happens on Yosemite as well on El Capitan with passenger 5.0.20.

**Comment by OnixGH** [comment]
Hey @ivdma :) This happened during an upgrade? There was an outdated path in the [brew formula](https://github.com/BrewTestBot/homebrew/commit/a50cbbab6680b114e47e1277256b2747ea2fcccb). which was recently fixed.

Can you check the `passenger_root` path in your install?

**Comment by ivdma** [comment]
@OnixGH it happened on `brew install nginx --with-passenger` on a clean OS X Yosemite. Did try it on my dirty El Capitan GM: no issues (`lib` folder was left where it was before 5.0.20). Did try `brew update && brew uninstall --force nginx passenger && brew prune && brew cleanup && brew install nginx --with-passenger` on Yosemite. Still instructions included `[..]/libexec/lib/phusion_passenger/passenger.ini`. So I guess BrewTestBot account was late testing the commit you mentioned, and we were stuck in the wrong place at the wrong time :) 

`passenger-config --root` did the trick :) `brew update && brew info nginx --with-passenger` is mentioning the right path again. Thanks for awesome support! Hope to see you soon at the meetup ;)

**Comment by OnixGH** [comment]
:+1:
