### ISSUE TITLE
DOCUMENT_ROOT no longer set

### ISSUE THREAD

**Issue by Benabik** [phusion/passenger#1626]
Just upgraded from 4.0.47 to 5.0.20 on Ubuntu 14.04.3 LTS, using Apache 2.

It seems that the DOCUMENT_ROOT environment variable is no longer set for Passenger apps.  Was able to work around by using SetEnv manually, but was wondering if this was deliberate or an oversight.

**Comment by FooBarWidget** [comment]
It was neither. `DOCUMENT_ROOT` was never a variable that we set officially. It just happened to be set for 4.x due to implementation side-effects.
