### ISSUE TITLE
Update logo in friendly error pages

### ISSUE THREAD

**Issue by simison** [phusion/passenger#1628]
This "Rails" thingy:

![image](https://cloud.githubusercontent.com/assets/87168/10253900/dfb1c8c6-6948-11e5-98df-03b2da59dba0.png)

and this at the footer:

> Powered by Phusion Passenger, mod_rails / mod_rack for Apache and Nginx.

...although running Nginx+Passenger to serve a _NodeJS_ app.

**Comment by FooBarWidget** [comment]
Yeah, we should update/remove that logo, it's getting old.

**Comment by FooBarWidget** [comment]
Fixed now.
