### ISSUE TITLE
passenger_base_uri not enough for nodejs apps in subpath

### ISSUE THREAD

**Issue by andrenarchy** [phusion/passenger#1629]
I have trouble deploying my app under the subpath `/backend/master` with the following nginx configuration (analogous to the [documentation](https://www.phusionpassenger.com/library/deploy/nginx/deploy/nodejs/)):
```
location ~ ^/backend/master(/.*|$) {
  alias /home/deploy/backend-dev/master/public$1;
  passenger_base_uri /backend/master;
  passenger_app_root /home/deploy/backend-dev/master;
  passenger_document_root /home/deploy/backend-dev/master/public;
  passenger_enabled on;
  passenger_app_type node;
  passenger_startup_file server.js;
}
```
Unfortunately, the node app receives requests with the prefix `/backend/master`.

In #1256, @Volox worked around the problem by adding a rewrite rule. However, this is not possible in my app because nginx then url-unescapes characters in the path, see [here](https://blog.phusion.nl/2015/06/04/phusion-passenger-5-0-9/).

Is there a way to use `passenger_base_uri` without rewrites (as mentioned in the documentation)?

**Comment by nschloe** [comment]
Same here. I bumped into this when debugging why users can't send strings like `10.1007%2Fs10714-015-1876-6` aka  `10.1007/s10714-015-1876-6` to our API -- nginx's `rewrite` unescapes the `%2F`, sends that to the backend, which then of course says that it can't find path `.../s10714-015-1876-6`. I'd love to remove the `rewrite`, but this Phusion bug prevents me from doing so. (We host the app from `https://example.com/sub/path/`.)

**Comment by OnixGH** [comment]
@andrenarchy @nschloe as @FooBarWidget mentioned in #1256, if you don't want rewriting rules then in nodejs apps you need to configure subpaths through the framework you're using. It's not actually a passenger bug but a nodejs limitation (we can't simply set something like `RAILS_RELATIVE_URL_ROOT` AFAIK).

Example solution in Express 4.0+ is to use the [router](http://expressjs.com/api#app.mountpath) (e.g. `app.use('/sub/path', router);`).

**Comment by OnixGH** [comment]
Added documentation in https://github.com/phusion/passenger_library/commit/9ba6a07d60f4a9b320f4b650e8e18290e3e5c2ae

**Comment by andrenarchy** [comment]
Thanks for pointing out that `passenger_base_uri` is not supported for nodejs! I tried to get it to work for hours...

I understand that nodejs does not have such a parameter because you can use all kinds of middlewares. But why can't passenger do the replacement? This could be done analogous to [nginx' proxy_pass](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) directive. I think this would be much cleaner than setting the path in the application. In my opinion, the application shouldn't need to know anything about the configuration of the HTTP server that sits in front of it. What do you think?

**Comment by FooBarWidget** [comment]
It's a good point. Let's create a new ticket for this.

**Comment by FooBarWidget** [comment]
See #1637.

**Comment by andrenarchy** [comment]
Thanks for picking up the idea!
