### ISSUE TITLE
Passenger source tarballs doesn't contain union_station submodules

### ISSUE THREAD

**Issue by msva** [phusion/passenger#1632]
Hi there!
Latest Passenger sources has a code to unconditionally load union_station libs, but at the same time the directories, where it supposed to load them from are empty in the passenger source tarball (so, they're also empty after the installation).

(Even despite of bad practice of calling `git` on tarball-based build) calling `git` to fetch them as submodules doesn't work, because release tarball is not a git repository.

**Comment by FooBarWidget** [comment]
That is strange, we have a test which explicitly tests whether the directory is non-empty. Maybe the test is broken. I'll have a look at this.

**Comment by FooBarWidget** [comment]
The source tarball does seem to contain the union_station libs:

    $ wget http://s3.amazonaws.com/phusion-passenger/releases/passenger-5.0.20.tar.gz
    $ tar tzf passenger-5.0.20.tar.gz.1 | grep union_station_hooks_core
    ...
    passenger-5.0.20/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core.rb
   ...

Does this directory not exist for you? How does your Passenger source tarball file list look like?

**Comment by msva** [comment]
Sorry for delay. I'm downloading tarballs from github tags:
```
$ curl -sL https://github.com/phusion/passenger/archive/release-5.0.20.tar.gz | tar -tzf- | grep union
passenger-release-5.0.20/resources/union_station_gateway.crt
passenger-release-5.0.20/src/cxx_supportlib/vendor-modified/boost/type_traits/is_union.hpp
passenger-release-5.0.20/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_core/
passenger-release-5.0.20/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_rails/
$
```

**Comment by FooBarWidget** [comment]
Oh. We don't support that. It is unfortunate that github does not include
submodules and we cannot do anything about it. You should use our official
tarballs.
