### ISSUE TITLE
Passenger allegedly dies on UTF-8 URLs

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1635]
An enterprise customer reported that Passenger "dies on UTF-8 URLs". This customer is using Nginx and Meteor, and on accessing URLs such as www.example.com/Café he gets a "400 Bad Request". This does not happen with a local Meteor development server.

Nginx logs this in access.log:

    31.13.99.120 - - [23/Sep/2015:09:05:48 +0200]  "GET /de/p/Caf\xC3\xA9_Basico HTTP/1.1" 400 11 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)" "www.example.com" 0.001

Error.log:

    2015/09/23 09:05:48 [error] 26944#0: *551 recv() failed (104: Connection reset by peer) while sending to client, client: 31.13.99.120, server: www.example.com, request: "GET /de/p/Café_Basico HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.ugPO0rG/agents.s/core:", host: „www.example.com“

The error log does not contain a crash log.

Operating system: Ubuntu Vivid 15.04
Linux www1 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Reference: email "passenger dies UTF8 urls" on September 21, 2015.

**Comment by fedebaier** [comment]
I have a Delphi desktop application that queries a RoR API that's running on Debian 7 with Passenger gem and Nginx.
I updated Passenger to 5.0.20 and this error started to appear whenever the desktop application tries to access an URL with UTF-8 characters. If I enter the same URL on my browser it works perfectly.
I had to go back to Passenger 4.0.59.

**Comment by FooBarWidget** [comment]
Federico, are you sure you get the exact same error as I stated in this
issue report? Or are you getting a different error message instead? When
the error occurs for you, do you see anything in the nginx error logs? Any
crash messages?

Any details would be much appreciated.

**Comment by fedebaier** [comment]
Yes @FooBarWidget, it looks like it's the exact same error.

**Nginx access.log:**
This is when I entered the URL in my browser
```
172.16.0.105 - - [14/Oct/2015:16:53:45 -0300] "GET /accounts/make_login?cn=GOMEZ+GUARISE,Sof%C3%ADa+Elizabeth&branch=student HTTP/1.0" 200 5433 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
```
And this is when the desktop application did the request
```
172.16.2.201 - - [14/Oct/2015:16:58:27 -0300] "GET /accounts/make_login?cn=GOMEZ+GUARISE,Sof\xC3\xADa+Elizabeth&branch=student HTTP/1.1" 400 11 "-" "Mozilla/3.0 (compatible; Indy Library)"
```

**Nginx error.log:**
The error only happened with the desktop application request
```
2015/10/14 16:58:22 [error] 4642#0: *42 recv() failed (104: Connection reset by peer) while sending to client, client: 172.16.2.201, server: www.example.com, request: "GET /accounts/make_login?cn=GOMEZ+GUARISE,Sofía+Elizabeth&branch=student HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.jcEl4mV/agents.s/core:", host: "www.example.com"
```

Please let me know if you need more information.

**Comment by fedebaier** [comment]
I've been testing the different versions of Passenger and can confirm that the error starts to appear in version 5.0.0.beta1.
In version 4.0.59 this error doesn't exist.
I hope this helps.

**Comment by FooBarWidget** [comment]
I can't reproduce this problem so far, but all the reported symptoms point to a problem in the Joyent HTTP parser. Maybe it doesn't handle UTF-8 characters correctly.

**Comment by FooBarWidget** [comment]
A test run with Valgrind on Linux did not find any errors.

@fedebaier Does Passenger crash on *every* URL that contains unescaped UTF-8 characters? Which operating system are you on and how did you install Passenger?

Do you see any Passenger crash logs in /var/tmp? If so, could you send the most recent one?

**Comment by fedebaier** [comment]
The Server OS is Debian 7
Linux cubert 3.2.0-4-amd64 #1 SMP Debian 3.2.41-2 x86_64 GNU/Linux

I use RVM. I installed Ruby 2.1.2, created a gemset and installed the Passenger gem inside that gemset.

No crash logs in /var/tmp.

I also can't reproduce the problem using the browser. It happens only when the desktop application (developed with Delphi 7) does the request (yes, on every request with UTF-8 characters). And, as I said, only with Passenger 5.0 and above.

**Comment by FooBarWidget** [comment]
The difference is that your Delphi app seems to send an HTTP request with raw UTF-8 characters in the URL. In contrast, your browser sends an HTTP request with *URI-escaped* UTF-8 characters in the URL.

Are you able to reproduce the problem with a development server? If so, could you set `passenger_log_level 7`, reproduce the problem, and send me a copy of your Nginx error logs?

**Comment by fedebaier** [comment]
Yes, I have a dev server.
I did what you asked me and here's the log for that request.
Keep in mind that this server has more than 10 APIs running, so there was a lot of logging and maybe not all the lines are for this API in particular.
I copied the logging that was made during the request.
```
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/Server.h:452 ]: [Client 1-769] Processing 464 bytes of client data
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/HttpServer.h:676 ]: [Client 1-769] Event: onClientDataReceived
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/HttpServer.h:679 ]: [Client 1-769] Request refcount increased; it is now 2
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/HttpServer.h:256 ]: [Client 1-769] Parsing 464 bytes of HTTP header: "GET /accounts/make_login?cn=GOMEZ,Joh\303\241na+Mic\303\243ela&branch=student HTTP/1.1\r\nConnection: close\r\nContent-Type: text/html\r\nHost: www.example.com\r\nAccept: text/html, */*\r\nUser-Agent: Mozilla/3.0 (compatible; Indy Library)\r\n!~: Se32HhpegwbAe6jbAUKWaQLg\r\n!~DOCUMENT_ROOT: /home/web/apis/account_api/public\r\n!~REMOTE_ADDR: 172.16.2.201\r\n!~REMOTE_PORT: 58507\r\n!~PASSENGER_APP_GROUP_NAME: /home/web/apis/account_api/public\r\n!~PASSENGER_APP_TYPE: rack\r\n!~PASSENGER_R"
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/HttpServer.h:267 ]: [Client 1-769] New request received: #769
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/FileBufferedChannel.h:1405 ]: [FBC 0x23169b0] Feeding 223 bytes
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/FileBufferedChannel.h:484 ]: [FBC 0x23169b0] pushBuffer() completed: nbuffers = 1, bytesBuffered = 223
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/FileBufferedChannel.h:552 ]: [FBC 0x23169b0] Reader: reading next
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/FileBufferedChannel.h:584 ]: [FBC 0x23169b0] Reader: found buffer, 223 bytes
[ 2015-10-21 09:38:48.3104 6129/7f79d5238700 Ser/FileBufferedChannel.h:491 ]: [FBC 0x23169b0] popBuffer() completed: nbuffers = 0, bytesBuffered = 0
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:592 ]: [FBC 0x23169b0] Reader: feeding buffer, 223 bytes
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:552 ]: [FBC 0x23169b0] Reader: reading next
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:559 ]: [FBC 0x23169b0] Reader: no more buffers. Transitioning to RS_INACTIVE
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:537 ]: [FBC 0x23169b0] Calling dataFlushedCallback
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:1405 ]: [FBC 0x23169b0] Feeding 11 bytes
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:484 ]: [FBC 0x23169b0] pushBuffer() completed: nbuffers = 1, bytesBuffered = 11
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:552 ]: [FBC 0x23169b0] Reader: reading next
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:584 ]: [FBC 0x23169b0] Reader: found buffer, 11 bytes
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:491 ]: [FBC 0x23169b0] popBuffer() completed: nbuffers = 0, bytesBuffered = 0
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:592 ]: [FBC 0x23169b0] Reader: feeding buffer, 11 bytes
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:552 ]: [FBC 0x23169b0] Reader: reading next
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:559 ]: [FBC 0x23169b0] Reader: no more buffers. Transitioning to RS_INACTIVE
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:537 ]: [FBC 0x23169b0] Calling dataFlushedCallback
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/HttpServer.h:1060 ]: [Client 1-769] Ending request
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:1449 ]: [FBC 0x23e8b00] Deinitialize
[ 2015-10-21 09:38:48.3105 6129/7f79d5238700 Ser/FileBufferedChannel.h:1405 ]: [FBC 0x23169b0] Feeding 0 bytes
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/FileBufferedChannel.h:484 ]: [FBC 0x23169b0] pushBuffer() completed: nbuffers = 1, bytesBuffered = 0
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/FileBufferedChannel.h:552 ]: [FBC 0x23169b0] Reader: reading next
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/FileBufferedChannel.h:564 ]: [FBC 0x23169b0] Reader: EOF encountered. Feeding EOF
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/FileBufferedChannel.h:580 ]: [FBC 0x23169b0] Reader: EOF fed. Transitioning to RS_TERMINATED
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/FileBufferedChannel.h:537 ]: [FBC 0x23169b0] Calling dataFlushedCallback
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/HttpServer.h:219 ]: [Client 1-769] Request refcount decreased; it is now 1
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/HttpServer.h:224 ]: [Client 1-769] Not keeping alive connection, disconnecting client
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/Server.h:902 ]: [Client 1-769] Disconnecting; there are now 0 active clients
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/FileBufferedChannel.h:1449 ]: [FBC 0x23169b0] Deinitialize
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/Server.h:912 ]: [Client 1-769] Closing client file descriptor: 33
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/Server.h:915 ]: File descriptor closed: 33
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/Server.h:923 ]: [Client 1-769] Refcount decreased; it is now 2
[ 2015-10-21 09:38:48.3106 6129/7f79d5238700 Ser/HttpServer.h:679 ]: [Client 1-769] Request refcount decreased; it is now 0
[ 2015-10-21 09:38:48.3107 6129/7f79d5238700 Ser/HttpServer.h:146 ]: [Client 1-769] Request object reached a reference count of 0
[ 2015-10-21 09:38:48.3107 6129/7f79d5238700 Ser/HttpServer.h:154 ]: [Client 1-769] Request object added to freelist (2 -> 3)
[ 2015-10-21 09:38:48.3107 6129/7f79d5238700 Ser/HttpServer.h:161 ]: [Client 1-769] Refcount decreased; it is now 1
[ 2015-10-21 09:38:48.3107 6129/7f79d5238700 Ser/Server.h:479 ]: [Client 1-769] 0 bytes of client data consumed in this callback
[ 2015-10-21 09:38:48.3107 6129/7f79d5238700 Ser/Server.h:528 ]: [Client 1-769] Refcount decreased; it is now 0
[ 2015-10-21 09:38:48.3107 6129/7f79d5238700 Ser/Server.h:378 ]: [Client 1-769] Client object reached a reference count of 0
[ 2015-10-21 09:38:48.3107 6129/7f79d5238700 Ser/Server.h:384 ]: [Client 1-769] Client object added to freelist (127 -> 128)
2015/10/21 09:38:48 [error] 6145#0: *1333 recv() failed (104: Connection reset by peer) while sending to client, client: 172.16.2.201, server: www.example.com, request: "GET /accounts/make_login?cn=GOMEZ,Johána+Micãela&branch=student HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.ndrr5Mp/agents.s/core:", host: "www.example.com"
[ 2015-10-21 09:38:49.7561 6134/7f4ce3a74700 age/Ust/Controller.h:709 ]: Flushing sinks that need flushing
[ 2015-10-21 09:38:49.7561 6134/7f4ce3a74700 age/Ust/Controller.h:723 ]: Done flushing sinks that need flushing
```

**Comment by FooBarWidget** [comment]
I think I know what's going on.

Raw UTF-8 characters are not allowed in URLs. You must percent-encode them. Sources:

 * RFC 3987, "6.4. Use of UTF-8 for Encoding Original Characters"
 * RFC 3986, "2.5. Identifying Data"
 * http://stackoverflow.com/a/913653/20816

So your you should update your Delphi application to send percent-encoded URLs instead.

The browser already sends UTF-8 characters in percent-encoding, so everything works there.

The Nginx HTTP parser happens to accept UTF-8 parsers, but the Joyent HTTP parser (used by Passenger) does not because it is more strict. As a result, Passenger rejects the request.

However, Passenger sends a "bad request" response and closes the socket before Nginx is done sending the request, so Nginx bails out with a "Connection reset by peer" error instead of forwarding the Passenger response. So the error message you see is just a red herring for the actual problem, namely that the original request is not allowed per the standards.

**Comment by fedebaier** [comment]
Ok, it seems that that's the right thing to do.

Thank you so much for your help.
