### ISSUE TITLE
Installing docs with 5.0.20 gem is all sorts of broken.

### ISSUE THREAD

**Issue by lilinye** [phusion/passenger#1640]
Below is just a tiny snippet of the errors/warnings that gem threw up. It took a long time to install and had approximately 5000 errors/warnings.

(eval):109: warning: invalid character syntax; use ?\s
(eval):118: warning: invalid character syntax; use ?\s
(eval):128: warning: invalid character syntax; use ?\s
(eval):141: warning: invalid character syntax; use ?\s
(eval):157: warning: invalid character syntax; use ?\s
(eval):165: warning: invalid character syntax; use ?\s
(eval):179: warning: invalid character syntax; use ?\s
(eval):190: warning: invalid character syntax; use ?\s
(eval):198: warning: invalid character syntax; use ?\s
(eval):206: warning: invalid character syntax; use ?\s
(eval):220: warning: invalid character syntax; use ?\s
(eval):230: warning: invalid character syntax; use ?\s
(eval):238: warning: invalid character syntax; use ?\s
(eval):251: warning: invalid character syntax; use ?\s
(eval):259: warning: invalid character syntax; use ?\s
(eval):271: warning: invalid character syntax; use ?\s
(eval):279: warning: invalid character syntax; use ?\s
(eval):289: warning: invalid character syntax; use ?\s
(eval):298: warning: invalid character syntax; use ?\s
(eval):311: warning: invalid character syntax; use ?\s
(eval):323: warning: invalid character syntax; use ?\s
(eval):18: warning: invalid character syntax; use ?\s
(eval):28: warning: invalid character syntax; use ?\s
(eval):45: warning: invalid character syntax; use ?\s
(eval):61: warning: invalid character syntax; use ?\s
(eval):75: warning: invalid character syntax; use ?\s
(eval):89: warning: invalid character syntax; use ?\s
(eval):5: warning: invalid character syntax; use ?\s
(eval):29: warning: invalid character syntax; use ?\s
(eval):55: warning: invalid character syntax; use ?\s
(eval):66: warning: invalid character syntax; use ?\s
(eval):101: warning: invalid character syntax; use ?\s
(eval):56: warning: circular argument reference - count
(eval):49: warning: circular argument reference - count
(eval):61: warning: circular argument reference - count
(eval):61: warning: circular argument reference - count
(eval):62: warning: circular argument reference - count
(eval):68: warning: string literal in condition
(eval):68: warning: string literal in condition
(eval):59: warning: found = in conditional, should be ==
(eval):23: warning: else without rescue is useless
Done installing documentation for passenger after 696 seconds
Parsing documentation for passenger-5.0.20
unable to convert "\x88" from ASCII-8BIT to UTF-8 for src/cxx_supportlib/vendor-modified/boost/thread/future.hpp, skipping
unable to convert "\x97" from ASCII-8BIT to UTF-8 for src/cxx_supportlib/vendor-modified/boost/utility/declval.hpp, skipping

**Comment by FooBarWidget** [comment]
Passenger does not actually contain any rdoc. Unfortunately, it is not possible to set a flag within the gem to tell RubyGems that "this gem has no rdoc". So you, the user, must tell that to RubyGems. Try installing the passenger gem from now on with `--no-rdoc --no-ri`, like this:

    gem install passenger --no-rdoc --no-ri

**Comment by lilinye** [comment]
It has NEVER been an issue before and I have been using passenger for quite a long time.

**Comment by FooBarWidget** [comment]
I understand, but I cannot do anything about problems in RubyGems.
