### ISSUE TITLE
Passenger Watchdog Fails Initialization due to SIGBUS on Solaris 11.2/SPARC

### ISSUE THREAD

**Issue by JamesTheBard** [phusion/passenger#1646]
Passenger version: 5.0.20
Operating system: Solaris 11.2
Architecture: SPARC/sun4v

The Passenger Watchdog crashes on initialization with a `SIGBUS/BUS_ADRALN` error.  I've linked to a gist of the log with additional details.

https://gist.github.com/JamesTheBard/89158878b662c4b657fa

**Comment by FooBarWidget** [comment]
Are you using the Apache, Nginx or Standalone mode?

**Comment by JamesTheBard** [comment]
Apache 2.2.29.

**Comment by hermannfilho** [comment]
Do you have any update/fix for this issue so far?

**Comment by OnixGH** [comment]
@hermannfilho no progress, so any additional information is welcome. It would be best to have some kind of temporary access to a solaris machine (or having commands executed through screen sharing).

**Comment by hermannfilho** [comment]
@OnixGH what would be the best approach to narrow down the issue an? From your initial thoughts is this something that would need to be changed on passenger source code itself or in the Solaris SPARC C studio compiler?
