### ISSUE TITLE
Can't run passenger-install-apache2-module

### ISSUE THREAD

**Issue by FallingSnow** [phusion/passenger#1653]
Passenger version: 5.0.6

configure: error: source directory already configured; run "make distclean" there first
rake aborted!
Command failed with status (1): [cd buildout/libev/ && sh /usr/lib/passenge...]

Tasks: TOP => apache2 => buildout/support-binaries/PassengerAgent => buildout/libev/.libs/libev.a => buildout/libev/Makefile
(See full trace by running task with --trace)

**Comment by FooBarWidget** [comment]
How did you install Passenger? Through RubyGems? Through source tarball?

**Comment by FallingSnow** [comment]
Installed it using the arch Linux package https://www.archlinux.org/packages/community/x86_64/passenger/

**Comment by FooBarWidget** [comment]
I'm afraid I cannot help you then. I don't know how their packages work. Try asking the packager.
