### ISSUE TITLE
rb_thread_blocking_region needs to be replaced with rb_thread_call_without_gvl family

### ISSUE THREAD

**Issue by CamJN** [phusion/passenger#1654]
see: https://github.com/ruby/ruby/blob/ruby_2_2/NEWS#L288 and https://github.com/nagachika/ruby-coreaudio/issues/18

Otherwise the following happens when you try and start passenger:
```
App 74285 stderr: dyld: lazy symbol binding failed: Symbol not found: _rb_thread_blocking_region
App 74285 stderr:   Referenced from: /usr/local/Cellar/passenger/5.0.21/libexec/buildout/ruby/ruby-2.2.3-x86_64-macosx/passenger_native_support.bundle
App 74285 stderr:   Expected in: flat namespace
App 74285 stderr: 
App 74285 stderr: dyld: Symbol not found: _rb_thread_blocking_region
App 74285 stderr:   Referenced from: /usr/local/Cellar/passenger/5.0.21/libexec/buildout/ruby/ruby-2.2.3-x86_64-macosx/passenger_native_support.bundle
App 74285 stderr:   Expected in: flat namespace
```

**Comment by FooBarWidget** [comment]
We already use rb_thread_call_without_gvl. But sometimes the Ruby native extension might not be built properly due to race conditions (#1570).

For now, try fixing that by recompiling native_support:

    rm -rf ~/.passenger/native_support && passenger-config build-native-support
