### ISSUE TITLE
`passenger-config restart-app --ignore-app-not-running` prints permission warning when one or more apps are running, but not the target app

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1655]
~~~
$ passenger-config restart-app /path-to-app --ignore-app-not-running
*** ERROR: You are not authorized to query the status for this Phusion Passenger instance. Please try again with 'sudo'.
~~~

The `restart-app` command already checks for the `pool-empty` header. Unfortunately this header doesn't do what we want. Maybe we should introduce an `app-not-found` header.

**Comment by vg-accrezion** [comment]
01 passenger-config restart-app /home/deploy/testsbm --ignore-app-not-running
while peforming "cap production deploy:

00:13 deploy:symlink:release
      01 ln -s /home/deploy/testsbm/releases/20190701061714 /home/deploy/testsbm/releases/current
    ✔ 01 deploy@159.89.164.231 0.049s
      02 mv /home/deploy/testsbm/releases/current /home/deploy/testsbm
    ✔ 02 deploy@159.89.164.231 0.054s
00:13 passenger:restart
      01 passenger-config restart-app /home/deploy/testsbm --ignore-app-not-running
      01 Restarting /home/deploy/testsbm/current (production)
    ✔ 01 deploy@159.89.164.231 0.223s
00:13 deploy:cleanup
      Keeping 5 of 6 deployed releases on 159.89.164.231
      01 rm -rf /home/deploy/testsbm/releases/20190629091236
    ✔ 01 deploy@159.89.164.231 0.062s
00:13 deploy:log_revision
      01 echo "Branch master (at 5639a4226f812f8ba48d2da7a87b36cb23c93015) deployed as release 20190701061714 by accrezion" >> /home/deploy/te…
    ✔ 01 deploy@159.89.164.231 0.056s
--------------
when we check the ip it shows
Error ID:
9e9f9679
Details:
Web application could not be started by the Phusion Passenger application server.

**Comment by CamJN** [comment]
@vg-accrezion your logs don't seem to indicate the issue described above, just that passenger couldn't start the new version of your app due to some error not included here. I suggest checking your application logs in addition to the passenger log.
