### ISSUE TITLE
Directory listing instead of Ruby on rails web interface

### ISSUE THREAD

**Issue by Drewshg312** [phusion/passenger#1656]
Hi!
I'm using Apache 2.4.17 and Passenger 5.0.21 under OS X 10.10.5
Virtual host for my Snorby (Ruby-on-rails application https://github.com/Snorby/snorby ):

```
<VirtualHost *:8443>
    ServerAdmin admin@server.snorby
    ServerName www.server.snorby
    ServerAlias server.snorby
    ErrorLog /usr/local/var/log/apache2/snorby_error.log
    LogLevel warn
    CustomLog /usr/local/var/log/apache2/snorby_access.log combined
    DocumentRoot /usr/local/var/www/snorby/public
    <Directory "/usr/local/var/www/snorby/public">
        Options Indexes FollowSymLinks Includes ExecCGI
        #Require all granted
        Order deny,allow
        Allow from all
        Options -MultiViews
    </Directory>
    ###-- SSL Certificates --###
    SSLEngine on
    SSLCertificateFile "/usr/local/etc/apache2/2.4/ssl-keys/ssl_server.crt"
    SSLCertificateKeyFile "/usr/local/etc/apache2/2.4/ssl-keys/ssl_server.key"
    SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown
    CustomLog /usr/local/var/log/apache2/snorby_ssl_request.log \
    "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"
</VirtualHost>
```

I've included the **passenger.conf** into my **httpd.conf**:

```
LoadModule passenger_module /usr/local/opt/passenger/libexec/buildout/apache2/mod_passenger.so
PassengerRoot /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
PassengerDefaultRuby /usr/local/var/rbenv/shims/ruby
    #PassengerDefaultRuby /usr/local/var/rbenv/versions/1.9.3-p551/bin/ruby
PassengerResolveSymlinksInDocumentRoot on
PassengerLogLevel 3
```

But after restart of httpd and navigating `https://server.snorby` getting the directory listing instead of Snorby web interface:

![1](https://cloud.githubusercontent.com/assets/10493450/10777536/cf3bb1c4-7cd9-11e5-9190-754176761ad0.jpg)

Please help!

Thank you!

**Comment by OnixGH** [comment]
Hi @Drewshg312, this sort of question is more suitable for the [forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger), unless you have a clear indication the issue is with passenger. I don't see anything wrong with your config, maybe you're not going to https://server.snorby:8443/ or there is another config interfering, or passenger isn't running (see logfile).
