### ISSUE TITLE
Crash after updating to 5.0.21

### ISSUE THREAD

**Issue by lohqua** [phusion/passenger#1660]
I just upgraded from 5.0.20.

I installed the gem, ran passenger-install-nginx, pointed passenger root to 5.0.21. 

Ran passenger-config restart-app.

Uninstalled the old passenger gem.

Got this in my browser:

`An internal error occurred while trying to spawn the application. Exception type: Passenger::RuntimeException Error message: Support binary PassengerAgent not found (tried: /usr/local/lib64/ruby/gems/2.2.0/gems/passenger-5.0.20/buildout/support-binaries/PassengerAgent and /root/.passenger/support-binaries/5.0.20/PassengerAgent) Backtrace: in 'void Passenger::SpawningKit::SmartSpawner::startPreloader()' (SmartSpawner.h:200) in 'virtual Passenger::SpawningKit::Result Passenger::SpawningKit::SmartSpawner::spawn(const Options&)' (SmartSpawner.h:777) in 'void Passenger::ApplicationPool2::Group::spawnThreadRealMain(const SpawnerPtr&, const Passenger::ApplicationPool2::Options&, unsigned int)' (SpawningAndRestarting.cpp:94) `

Passenger is running a rails 4.2 app

Rebooting the server fixed the issue. 

Is a server reboot now required for Passenger?

**Comment by OnixGH** [comment]
No, a reboot is not needed. But restart-app restarts your app, not passenger.

Since you upgraded, you needed to restart passenger instead.

**Comment by lohqua** [comment]
That's funny. This is the exact sequence I have used for dozens of passenger updates and never an issue. Ever.
