### ISSUE TITLE
Passenger standalone should be configurable by environment variables

### ISSUE THREAD

**Issue by scottjacobsen** [phusion/passenger#1661]
Especially on heroku, but in general, configuring standalone with command line switches or a json config file does not work well. 

A perfect example is configuring the union station key. I only want to set that in the production environment. If this could be set via an environment variable setup would be trivial - only set the UNION_STATION_KEY env var on the production servers.

As it stands I can only think of two was to only enable unionstation on production.

1. Have the Procfile call a wrapper script to start the webserver, and have the wrapper script check for the UNION_STATION_KEY and if it is there start passenger with the `--union-station-key` command line param.

2. Hack the nginx.conf.erb to only enable unionstation if that variable is defined.

**Comment by FooBarWidget** [comment]
Good point. We should definitely allow configuration through environment variables. The Union Station setup instructions should also contain a section for Heroku.

Ping @tinco so that he knows about this issue.

**Comment by FooBarWidget** [comment]
The feature has been implemented and will be part of 5.0.22. Passenger Standalone now accepts the `PASSENGER_UNION_STATION_KEY` environment variable. Environment variables override the config file.

**Comment by scottjacobsen** [comment]
:+1: :gem: :rainbow: :smile: You guys are the best.
