### ISSUE TITLE
New ByeBug release breaks Passenger Enterprise's loader.

### ISSUE THREAD

**Issue by phyllisstein** [phusion/passenger#1662]
Hey Passengers! Just noticed that the most recent update to ByeBug removes eager loading of the library (see deivid-rodriguez/byebug@b77855ccb2bd3f4e99175ed3c0e16b4a953e2538), so `Byebug.respond_to?(:actual_port)` is still false when Passenger Enterprise runs `before_loading_app_code_step2`. You'd have to actually call `Byebug.attach` before it'd be true, but that seems inutile. As an alternative, you might consider checking `Kernel.byebug`, which _would_ be defined: <https://github.com/deivid-rodriguez/byebug/blob/117a92184e8f37232a824945780643de9f7eb589/lib/byebug/attacher.rb#L28>.

I didn't actually have an urgent need for `passenger_debugger` to be on, so I disabled it and this isn't urgent, but thought the heads-up might be handy. Thanks for all your hard work on Passenger!

**Comment by FooBarWidget** [comment]
Thanks for reporting this. We'll try to fix this for 5.0.22.

**Comment by FooBarWidget** [comment]
The issue has been fixed and the fix will be part of 5.0.22.
