### ISSUE TITLE
SELinux labels for passenger_instance_registry_dir broken after YUM update

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1663]
Reported by Ryan from https://groups.google.com/forum/#!msg/phusion-passenger/e8QOJm_LYek/NyQtPkmkDwAJ:

I have a machine running CentOS7 + Phusion Passenger + Redmine.  I installed Passenger from the RPM.  A couple days ago it quit working after a YUM update.  The files in passenger_instance_registry_dir (/var/run/passenger-instreg) ended up being mislabelled after the update.

Ex (before reboot):

~~~
srw-rw-rw-. root root system_u:object_r:var_run_t:s0   core
srw-rw-rw-. root root system_u:object_r:var_run_t:s0   core_api
~~~

...vs (after reboot - same effect as 'reload httpd'):

~~~
srw-rw-rw-. root root system_u:object_r:httpd_var_run_t:s0 core
srw-rw-rw-. root root system_u:object_r:httpd_var_run_t:s0 core_api
~~~

...vs (reload httpd + restorecon -R /var/run):

~~~
srw-rw-rw-. root root system_u:object_r:var_run_t:s0   core
srw-rw-rw-. root root system_u:object_r:var_run_t:s0   core_api
~~~

...vs (a machine that hadn't updated yet):

~~~
srw-rw-rw-. root root system_u:object_r:passenger_instance_httpd_socket_t:s0 core
srw-rw-rw-. root root system_u:object_r:passenger_instance_content_t:s0 core_api
~~~

The update that caused the problem was:

~~~
================================================================================
 Package                    Arch      Version                  Repository  Size
================================================================================
Installing:
 kernel                     x86_64    3.10.0-229.20.1.el7      updates     31 M
Updating:
 gmp                        x86_64    1:6.0.0-12.el7_1         updates    280 k
 kernel-headers             x86_64    3.10.0-229.20.1.el7      updates    2.3 M
 kernel-tools               x86_64    3.10.0-229.20.1.el7      updates    1.5 M
 kernel-tools-libs          x86_64    3.10.0-229.20.1.el7      updates    1.4 M
 kpartx                     x86_64    0.4.9-77.el7_1.2         updates     56 k
 libnl3                     x86_64    3.2.21-9.el7_1           updates    197 k
 libnl3-cli                 x86_64    3.2.21-9.el7_1           updates     78 k
 rsyslog                    x86_64    7.4.7-7.el7_1.1          updates    556 k
 selinux-policy             noarch    3.13.1-23.el7_1.21       updates    360 k
 selinux-policy-targeted    noarch    3.13.1-23.el7_1.21       updates    3.9 M
~~~

I'm guessing it was the selinux-policy stuff that changed something, but it's only a guess.  Based on my brief testing, it looks like everything in passenger_instance_registry_dir/* could survive a relabel before the update.  Now it can't.

I just started running Redmine on CentOS with SELinux, so I don't know if this is something I should expect to deal with or not.  I can't seem to find much info on Google.  Any comments or suggestions?  Has anyone seen a related bug report in the last couple days?

**Comment by ryanjaeb** [comment]
Since it's [not possible](https://access.redhat.com/solutions/64069) to rollback `selinux-policy-*` updates I decided to manually apply the `selinux-policy-*` updates on an almost identical machine.

Check labels:

```
ls -lZ /var/run/ | grep passenger
```
```
drwxr-xr-x. root     root     system_u:object_r:passenger_instance_registry_t:s0 passenger-instreg
```

Then `restorecon`:

```
sudo restorecon -R /var/run
ls -lZ /var/run/ | grep passenger
```
```
drwxr-xr-x. root     root     system_u:object_r:passenger_instance_registry_t:s0 passenger-instreg
```

Then update:

```
Transaction ID : 23
Begin time     : Fri Nov  6 04:22:23 2015
Begin rpmdb    : 800:fdeeca1aba81b33eef7b600a6d1cfb04c61cda22
End time       :            04:23:14 2015 (51 seconds)
End rpmdb      : 800:6d61b6d78dab9dfa845b49b1c33c480e527af9f3
User           : Administrator <admin>
Return-Code    : Success
Command Line   : update selinux-policy
Transaction performed with:
    Installed     rpm-4.11.1-25.el7.x86_64                      @anaconda
    Installed     yum-3.4.3-125.el7.centos.noarch               @anaconda
    Installed     yum-metadata-parser-1.1.4-10.el7.x86_64       @anaconda
    Installed     yum-plugin-fastestmirror-1.1.31-29.el7.noarch @anaconda
Packages Altered:
    Updated selinux-policy-3.13.1-23.el7_1.18.noarch          @updates
    Update                 3.13.1-23.el7_1.21.noarch          @updates
    Updated selinux-policy-targeted-3.13.1-23.el7_1.18.noarch @updates
    Update                          3.13.1-23.el7_1.21.noarch @updates
```

Then check labels again:

```
ls -lZ /var/run/ | grep passenger
```
```
drwxr-xr-x. root     root     system_u:object_r:var_run_t:s0   passenger-instreg
```

Then `restorecon` again:

```
sudo restorecon -R /var/run
ls -lZ /var/run/ | grep passenger
```
```
drwxr-xr-x. root     root     system_u:object_r:var_run_t:s0   passenger-instreg
```

All other files below `/var/run/passenger-instreg/` are similarly mislabeled.

**Comment by FooBarWidget** [comment]
@ryanjaeb Have you checked whether reinstalling the Passenger packages helps? Our packages install an SELinux policy module in the postinstall script. It is possible that an upgrade of the base policy somehow removed our additional policy modules, in which case reinstalling the policy module may help.

**Comment by ryanjaeb** [comment]
@FooBarWidget Yes, reinstalling `passenger` seems to do the trick.  I reinstalled `passenger`, checked the labels, ran `restorecon -R /var/run`, and checked the labels again.  It looks good.

Is it possible to have those policies survive a reinstall of `selinux-policy-*`?

**Comment by FooBarWidget** [comment]
To be able to tell you that I'll have to investigate what selinux-policy-* exactly does on an upgrade. I'll schedule some investigation time for 5.0.22.

**Comment by tr3pan** [comment]
There is an upstream selinux module called passanger with filename [passenger.pp](https://git.fedorahosted.org/cgit/selinux-policy.git/tree/passenger.te?h=rawhide-contrib#n1) in selinux-policy-targeted package. When you update selinux the passenger module, that comes with passenger rpm is kicked out and the upstream module takes place. Workaround for that is 
* put SELinux in permissive mode`setenforce Permissive`
* update SELinux
* load again the passenger module `semodule -s targeted -i /usr/share/selinux/targeted/passenger.pp`
* relable `fixfiles -v -R passenger-enterprise restore` or `fixfiles -v -R passenger restore`.

To be sure everything is ok check(for nginx+passenger) check that passenger doesn't run with `httpd_t` selinux type with `ps -efZ | grep httpd_t` otherwise you have to (gracefully) restart nginx to run passenger with the proper context.

* check `grep AVC /var/log/audit/audit.log` to be 100% you don't have any errors
* set SELinux in Enforcing mode `setenforce Enforcing`

What is the permanent solution - put passenger module in upstream so there won't be any problems with updating selinux.

**Comment by ryanjaeb** [comment]
Thanks workaround suggested by @tr3pan allowed me to update without interrupting the process(es).

##### Stop Enforcing

```
sudo setenforce Permissive
```

##### YUM Update

```
sudo yum update selinux-policy*
```

##### Fix Labels

```
sudo semodule -s targeted -i /usr/share/selinux/targeted/passenger.pp
sudo fixfiles -v -R passenger restore
```

##### Check Processes

```
ps -efZ | grep -i passenger
```
Output:
```
system_u:unconfined_r:unconfined_t:s0 root 7148 7123  0 23:53 ?        00:00:00 Passenger watchdog
system_u:unconfined_r:unconfined_t:s0 root 7151 7148  0 23:53 ?        00:00:00 Passenger core
system_u:unconfined_r:unconfined_t:s0 nobody 7160 7148  0 23:53 ?      00:00:00 Passenger ust-router
system_u:unconfined_r:unconfined_t:s0 redmine 7225 1  0 23:54 ?        00:00:00 Passenger RubyApp: /opt/redmine/llr/redmine
```

##### Start Enforcing

```
sudo setenforce Enforcing
```

**Comment by OnixGH** [comment]
The [blog post](https://blog.phusion.nl/2015/11/06/fixing-passenger-rpm-issues-caused-by-recent-selinux-updates) has been updated with the info from this thread. Thanks, all!

**Comment by jrpatterson** [comment]
Can a bug be filed upstream with Red Hat regarding this issue?

**Comment by FooBarWidget** [comment]
I don't think Red Hat will accept this as a bug because it's caused by a third party (us). But it appears SELinux [supports priorities for modules](http://blog-bachradsusi.rhcloud.com/2015/06/05/selinux-modules-priority/). Maybe we can use that.

**Comment by FooBarWidget** [comment]
Looks like SELinux priorities are too new and we can't use that. But I've found a solution using RPM '%triggerin' scripts: upon installing or upgrading the system SELinux policy, the Passenger package will automatically reinstall its own SELinux policy.
