### ISSUE TITLE
Passenger Nginx Module can't pass environment variables.

### ISSUE THREAD

**Issue by froysm** [phusion/passenger#1664]
So I'm installing a new server with Nginx v. 1.8, Ruby 2.2.0, Rails 4.2 and Passenger v. 5.0.21 and I'm trying to send GeoIP variables to the application this way:

```nginx
passenger_env_var HTTP_GEOIP_COUNTRY_CODE US;
passenger_env_var HTTP_GEOIP_VISITING_COUNTRY $geoip_country_code;
````
The first variable is correctly defined in the ENV hash in the application, but the second variable is set to "$geoip_country_code" instead of the country code detected by the GeoIP library.

I know that GeoIP is properly configured because I created a log_format and logged the value of the $geoip_country_code variable with favorable results, that makes me think that this is a Passenger related issue, which seems odd because I'm pretty sure v. 4 worked fine with passenger_set_cgi_param.

Thanks.

**Comment by FooBarWidget** [comment]
System environment variables are static; they can only be set once during application startup, and cannot be set based on dynamic request-specific properties. See https://www.phusionpassenger.com/library/indepth/ruby/apache_per_request_envvars.html#the-env-object (the information was written for the Apache case, but applies to your Nginx case too).

You should use [passenger_set_header](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_set_header).
