### ISSUE TITLE
Is there a reason why Passenger standalone nginx doesn't enable sendfile by default?

### ISSUE THREAD

**Issue by kriansa** [phusion/passenger#1670]
I was wondering why isn't there such directive by default in `nginx.conf.erb` in Passenger Standalone, specially for rails asset pipeline block. Is it a recommended approach, or does it conflict with turbocaching?

**Comment by FooBarWidget** [comment]
Sendfile is actually a tricky feature. It is known to be broken on various platforms and under various conditions that are non-obvious. For this reason web servers like Apache and Nginx have a history of avoiding sendfile by default.

See https://blog.phusion.nl/2015/06/04/the-brokenness-of-the-sendfile-system-call/ for an example.

Unless you are sending a truly massive amount of static files and don't deal with dynamic content at all, I don't think enabling sendfile will make any difference in performance. So I don't see a good reason to enable it: it causes more problems than it solves.
