### ISSUE TITLE
Passenger worker stuck after "cache error: invalid %-encoding"

### ISSUE THREAD

**Issue by steveny** [phusion/passenger#1671]
Running passenger status I noticed that a session was active for over 17 hours:

`  * PID: 8672    Sessions: 1       Processed: 0       Uptime: 17h 32m 38s
    CPU: 0%      Memory  : 151M    Last used: 17h 29m`

A kill -QUIT reveals:
[sig_quit.txt](https://github.com/phusion/passenger/files/39126/sig_quit.txt)

When I try to detach the process.  It appears to then be stuck "shutting down..."

`  * PID: 8672    Sessions: 1       Processed: 0       Uptime: 17h 37m 44s
    CPU: 0%      Memory  : 151M    Last used: 17h 34m
    Shutting down...`

[shutting-down.txt](https://github.com/phusion/passenger/files/39131/shutting-down.txt)

**Comment by OnixGH** [comment]
I don't see a Passenger issue here, the normal behavior is to wait until an application has handled its sessions before force-killing it, and this application is still marked busy (Sessions: 1), so it's not force-killed.

The solution would be to fix the app or work around it with the (enterprise) [passenger_max_request_time option](https://www.phusionpassenger.com/library/config/reference/?a=passenger_max_request_time) that automatically kills apps after a while.

Btw. not related to this question but we recommend using the latest version, 5.0.21, especially if you're below 5.0.17.
