### ISSUE TITLE
Problems compiling Apache passenger 4 module on El Capitan

### ISSUE THREAD

**Issue by eric** [phusion/passenger#1673]
I am unable to compile the Apache module of passenger 4 on El Capitan.

The OpenSSL modules cannot be found unless they are downloaded by homebrew and referenced properly (I used the `env` stuff listed in #1630).

Once I've run that like this:

```
$ env EXTRA_CFLAGS=-I$HOME/homebrew/opt/openssl/include EXTRA_CXXFLAGS=-I$HOME/homebrew/opt/openssl/include EXTRA_LDFLAGS=-L$HOME/homebrew/opt/openssl/lib passenger-install-apache2-module
```

I get this error:

```
rm -f buildout/libev/libev.la
cd buildout/libev/ && make libev.la
/bin/sh ./libtool --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I/Users/eric/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/passenger-4.0.59/ext/libev     -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -fcommon -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -g -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -I/Users/eric/homebrew/opt/openssl/include -w -MT ev.lo -MD -MP -MF .deps/ev.Tpo -c -o ev.lo /Users/eric/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/passenger-4.0.59/ext/libev/ev.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I/Users/eric/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/passenger-4.0.59/ext/libev -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -fcommon -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -g -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -I/Users/eric/homebrew/opt/openssl/include -w -MT ev.lo -MD -MP -MF .deps/ev.Tpo -c /Users/eric/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/passenger-4.0.59/ext/libev/ev.c -o ev.o
/Users/eric/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/passenger-4.0.59/ext/libev/ev.c:970:42: error: '_Noreturn' keyword must precede
      function declarator
  ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                         ^~~~~~~~~~~~
  _Noreturn 
/Users/eric/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/passenger-4.0.59/ext/libev/ev.c:773:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
1 error generated.
make: *** [ev.lo] Error 1
rake aborted!
Command failed with status (2): [cd buildout/libev/ && make libev.la...]

Tasks: TOP => apache2 => buildout/agents/PassengerHelperAgent => buildout/libev/.libs/libev.a
(See full trace by running task with --trace)

--------------------------------------------

It looks like something went wrong

Please read our Users guide for troubleshooting tips:

   /Users/eric/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/passenger-4.0.59/doc/Users guide Apache.html
   https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html

If that doesn't help, please use our support facilities. We'll do our best to help you.

   https://www.phusionpassenger.com/documentation_and_support
```

**Comment by FooBarWidget** [comment]
This is a totally different issue from the Nginx one and doesn't have anything to do with OpenSSL. I suggest that you patch the codebase to make compilation work. Try editing ext/libev/ev.c. Look for this:

~~~
#if ECB_C11
  #define ecb_noreturn   _Noreturn
#else
  #define ecb_noreturn   ecb_attribute ((__noreturn__))
#endif
~~~

Replace with:

~~~
#define ecb_noreturn   ecb_attribute ((__noreturn__))
~~~

**Comment by eric** [comment]
Do you have any suggestion for how to make that work as part of the `passenger-install-apache2-module` process?

**Comment by FooBarWidget** [comment]
Unfortunately it is not possible to make this work without patching the code.

**Comment by eric** [comment]
Could you release an update of Passenger 4 that fixes this? Do you have a separate place for support requests for enterprise customers?

**Comment by FooBarWidget** [comment]
Due to various technical reasons, it is difficult to release a new Passenger 4 version with binaries. What I could do for you is to release a source-only hotfix release for you. However, I will need your assistance with testing because we do not have access to OS X El Capitan right now (the upgrader keeps crashing on us). Would that be ok?

We have a support ticket system for enterprise customers. Please email support@phusionpassenger.com while mentioning your order reference.

**Comment by eric** [comment]
A source-only hotfix release would be great.

**Comment by FooBarWidget** [comment]
Let me schedule this for the same time frame as 5.0.22.

I cannot find you in our customer database. Could you send us an enterprise support ticket?

**Comment by eric** [comment]
Just sent it. Thanks!

**Comment by FooBarWidget** [comment]
It's released: https://blog.phusion.nl/2015/12/07/passenger-4-0-60/

**Comment by eric** [comment]
Thanks!

**Comment by PikachuEXE** [comment]
Is this closed?
I am trying to run passenger open source 4.0.60 on OSX 10.10.5
From what I see in the [4.x source code of libev extension](https://github.com/phusion/passenger/blob/stable-4.0/ext/libev/ev.c#L772) the conditional is still there
Same for [4.x source code of libeio extension](https://github.com/phusion/passenger/blob/stable-4.0/ext/libeio/ecb.h#L277)

**Comment by OnixGH** [comment]
It's [closed](https://github.com/phusion/passenger/commit/2eb1c4c89e4e7889353f67a8c4de2c21b9049c64). Please post your issue if you have one.
