### ISSUE TITLE
Passenger deleting directory in Rails tmp dir after 5 minutes

### ISSUE THREAD

**Issue by botandrose** [phusion/passenger#1677]
Running Passenger 5.0.21 (via deb) with Apache 2.4 on Ubuntu Linux 15.04.

I have a Rails app that's serving an Ember app via EmberCLI-Rails. When the server starts, EmberCLI-Rails compiles the app into `tmp/ember-cli-[some-uuid-here]`, and then symlinks it into the Rails asset pipeline. Everything is fine, then exactly five minutes after the server has started, this directory disappears. This does not happen when running the same app with Webrick.

Note that this is the _Rails_ tmp dir, not the _system_ tmp dir, so I don't think a /tmp cleaning daemon is the culprit. However, I have no hypothesis for this behavior at present, so ¯\\\_(ツ)_/¯

Originally https://github.com/thoughtbot/ember-cli-rails/issues/304

**Comment by botandrose** [comment]
Okay, have a slightly better idea what's going on here. Took a look through the Passenger documentation for settings that are set to 5 minutes, and found that PassengerMaxPreloaderIdleTime defaults to 300 seconds. Indeed, setting this to 15 seconds caused the directory to be deleted 15 seconds after server start instead of five minutes.

However, I'm still not sure why the preloader shutting down would cause a directory to be deleted. Any ideas?

**Comment by botandrose** [comment]
Reproduce with this app: https://github.com/botandrose/ember_cli_rails_bug_repro

**Comment by OnixGH** [comment]
Hi @botandrose, good analysis so far. Given a high enough loglevel you will see something like "Garbage collect idle spawner:group=/your/app/ember_cli_rails_bug_repro", at which point the tmp folder disappears.

What I think happens is that you're running into one of the [caveats of smart spawning](https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/#smart-spawning-caveats), perhaps file desciptor sharing of the tmp folder.

The easiest way to deal with it would be to set `PassengerMaxPreloaderIdleTime 0`, if you're okay with slightly higher resource use (but with the advantages of smart spawning intact). You can also switch to direct spawning, which doesn't use the preloader but is a little slower in spawning.

**Comment by botandrose** [comment]
Hi @OnixGH, thanks for your response! Either one of those solutions is a reasonable workaround for myself. I will likely use the former.

However, I think EmberCLI-Rails breaking after five minutes for everyone with a default Passenger setup is pretty unfortunate. So if possible, I'd like to be able to contribute something upstream to EmberCLI-Rails to prevent this. If you don't mind, can you help me to make sure I understand the issue correctly:

1. The `tmp/ember-cli-[uuid]` dir is being created by the Rails app during bootup while its inside the preloader process, and thus the file descriptor belongs to the preloader process.
2. Subsequent requests go to a process forked from the preloader.
3. When the preloader process is killed after the idle timeout, the garbage collector kills the process, and thus the files it owns in `tmp` are deleted by some mechanism...?

This last part is the part I'm a little fuzzy on. Are the temporary files deleted by Passenger cleanup, Rails cleanup, or simply by virtue of shutting down a Unix fork?

It seems to me that a possible workaround in EmberCLI-Rails might be to compile the app on first request, not boot, if Passenger preloading is detected. But when that particular app instance is killed and another springs up, would the files in `tmp` be deleted again?

**Comment by botandrose** [comment]
Nevermind, the answer is "none of the above"... EmberCLI-Rails is performing the deletes itself on process exit: https://github.com/thoughtbot/ember-cli-rails/blob/7e8cd93/lib/ember-cli-rails.rb#L35

I think I have everything I need to address this issue now. Thanks again for your time!
