### ISSUE TITLE
Timestamp prefix for application output in logs

### ISSUE THREAD

**Issue by majgis** [phusion/passenger#1679]
Passenger 5.0.21(stand-alone) on CentOS 6.6:

Here is the current log file:
```
user@test:/opt/testapp (rpm-v4) $ cat logs/testapp.log 
[ 2015-11-23 21:53:54.8700 22518/7f626791f800 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2015-11-23 21:53:54.9002 22521/7f04f95a3800 age/Cor/CoreMain.cpp:957 ]: Starting Passenger core...
[ 2015-11-23 21:53:54.9045 22521/7f04f95a3800 age/Cor/CoreMain.cpp:234 ]: Passenger core running in multi-application mode.
[ 2015-11-23 21:53:54.9105 22521/7f04f95a3800 age/Cor/CoreMain.cpp:707 ]: Passenger core online, PID 22521
[ 2015-11-23 21:53:54.9320 22526/7f4620525800 age/Ust/UstRouterMain.cpp:504 ]: Starting Passenger UstRouter...
[ 2015-11-23 21:53:54.9342 22526/7f4620525800 age/Ust/UstRouterMain.cpp:317 ]: Passenger UstRouter online, PID 22526
App 22561 stdout: 
App 22561 stdout: Listening on port 23210
```

It would be very helpful if the application output lines had prefixes with timestamps similar to the following:

```
[ 2015-11-23 21:53:54.9345 22561 App stdout ]:
[ 2015-11-23 21:53:54.9348 22561 App stdout ]: Listening on port 23210
```

**Comment by OnixGH** [comment]
Wrapping the application output with a passenger core timestamp can be misleading because the timestamp will be that of when the log was received by the passenger core, not the time when the logline was generated.

These times are different, and there is even a difference between stderr and stdout. Can you comment on what you think about this, and why you wouldn't just use some logging framework within the app? Such a framework could probably also have log categories, etc.

**Comment by majgis** [comment]
My first impression was that passenger does so much up front for us, a more well formed log file out of the gate would also be nice.  I was also comparing against PM2 which inserts timestamps automatically.

I ended up going with bunyan for logging JSON to a separate file.  So for my use, this feature is no longer necessary, but you may want to consider it for the sake of first impressions compared against PM2 and other tools like it for Node.js, and fulfill the promise of passenger just working immediately.  At the time, I was wishing I didn't have to spend the extra time to figure out a custom logger.

In regard to the timestamp disparity, maybe the solution is hijacking each instances stdout and providing an optional, default logger, instead of pushing the burden onto every developer to find their own solution.

**Comment by OnixGH** [comment]
Thanks for the feedback, we appreciate the considerations.

I think PM2 timestamps suffer from the same inaccuracy, and from the Passenger perspective we also have to consider other app languages, but hijacking might at least be the most accurate solution from the Node perspective (that's actually how we did it for Passenger's [Node.js logging to Union Station](https://www.unionstationapp.com)).

**Comment by majgis** [comment]
It is easy enough to throw in a node.js logger, and yes Union Station is the easy button.  Time is probably better spent on other issues.  Thank you for your consideration. Sorry for the distraction, you can close this one.

**Comment by OnixGH** [comment]
No problem, there's probably others with this question so it's good to have the discussion up.
