### ISSUE TITLE
Standalone crashes when the unionstation key is set but hooks are not initialized

### ISSUE THREAD

**Issue by scottjacobsen** [phusion/passenger#1681]
When you specify your unionstation key, but haven't setup the unionstation hooks passenger displays a helpful error message - `The Union Station hooks are not initialized. Please ensure that you have an initializer file config/initializers/union_station.rb in which you call this:...` and crashes.

Passenger should continue to display the helpful message, but then run as though the key has not been specified.

**Comment by FooBarWidget** [comment]
Yes, this change is [planned for 5.0.22](https://github.com/phusion/passenger/issues/1639).
