### ISSUE TITLE
(Unreleased) abbreviated config template creates duplication errors

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger#1683]
The upcoming .22 release features an abbreviated config template, but you are not free to add options like passenger_log_level because they are already defined and you'll get a fatal: duplicate directive.

Example:
```
http {
    <%= include_passenger_internal_template('http.erb', 4) %>

    ### BEGIN your own configuration options ###
    passenger_log_level 5;

    ...
}
```
`nginx: [emerg] "passenger_log_level" directive is duplicate in ...`

**Comment by FooBarWidget** [comment]
This is how it is supposed to work. The log level is to be set through the `log_level` option. Any config options you add is only allowed in so far they aren't already set by Passenger.

If the user wants to have that level of control, he can get rid of the `<%= include_passenger_internal_template('http.erb', 4) %>` statement.

**Comment by OnixGH** [comment]
The template doesn't mention any of this, and it's not obvious for which options it works for and which it will error out. On top of that, it's not clear in which include file the duplicate statement is so you have to potentially search through multiple files. After that, you can't really just comment out the include since it also drops all the other options there, so you end up copy pasting the file back, which defeats the entire purpose, right?

Maybe Passenger can do the de-duplication itself, since it's composing the file anyway. It's probably tricky to ensure the right hierarchy (e.g. command line overriding config file while also taking into account defaults), but right now the old template seems less problematic.

**Comment by FooBarWidget** [comment]
Deduplication is problematic. Some options may not have duplicates, some other options are supposed to have duplicates.

**Comment by FooBarWidget** [comment]
Passenger Standalone now runs a sanity check on the configuration file, and prints an appropriate error message to help you debug the problem. The configuration template now also explicitly states that duplicates are not allowed, and points to the documentation to help you remove duplicates.

**Comment by OnixGH** [comment]
This takes the bite out of the issue and provides tools to solve it indeed, although I would still rate the manual solution as "not ideal" in the passenger spirit of "just working" for you.
