### ISSUE TITLE
Passenger 5.0.18 upgrade fails server with rails 4.2.4

### ISSUE THREAD

**Issue by imechemi** [phusion/passenger#1689]
When I upgraded to passenger 5, my server went down and started throwing 404. But when I revert the passenger to 4.0.59, everything starts working. Is there any issue about passenger with rails version 4.2.4, i didn't find any thing from issues. This is my confguration under `/sites-available/zombie.conf`. 
      
    <VirtualHost *:80>
        ServerName services.myhub.com

        DocumentRoot /opt/zombie/applications/my_app/public
        <Directory /opt/zombie/applications/my_app/public>
          AllowOverride all
          Order allow,deny
          Allow from all
          Options -MultiViews
        </Directory>

        <Location />
          PassengerAppRoot /opt/zombie/applications/my_app
          PassengerEnabled On
          Options -MultiViews
        </Location>

        Alias /zombie /opt/zombie/applications/my_app/public
        <Location /zombie>
          PassengerBaseURI /zombie
          PassengerAppRoot /opt/zombie/applications/my_app
          PassengerEnabled On
        </Location>

**Comment by FooBarWidget** [comment]
When you were running Passenger 5, did you look in the Apache error log? Were there any error messages in there?

**Comment by imechemi** [comment]
I see logs like these:

        "GET /zombie HTTP/1.1" 404 20 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5)

**Comment by OnixGH** [comment]
Are you sure you followed the [upgrade notes](https://www.phusionpassenger.com/library/install/apache/migrating/migrating_from_p4_to_p5.html) when going from Passenger 4 to 5?

In particular "To make Rails 2.3 apps work with Passenger 5, the app must have a config.ru".

**Comment by FooBarWidget** [comment]
@OnixGH He is on Rails 4 though.

**Comment by imechemi** [comment]
@OnixGH we upgraded from rails 4.2.0 to 4.2.4 before passenger upgrade. Passenger 4.0.59 had not issues with rails 4.2.4. 

In fact, one of our application is running with rails 4.2.4 and passenger 5.0.18 with no issues.

**Comment by OnixGH** [comment]
@imechemi I'm not sure what makes you think Passenger has a problem with rails 4.2.4 (especially since you have another app that is working in that setup), it sounds like a configuration problem.

You should post your configuration to our [support forum](https://groups.google.com/forum/#!forum/phusion-passenger) unless you have a more concrete indication that this is a Passenger issue.
