### ISSUE TITLE
Builds with nginx 1.9 missing

### ISSUE THREAD

**Issue by andrenarchy** [phusion/passenger#1697]
Is there a reason why the deb repository
```
deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main
```
only has the stable version of nginx (1.8.x) and not the mainline version (1.9.x)?

**Comment by FooBarWidget** [comment]
Because we prefer stability over features.

**Comment by andrenarchy** [comment]
The [nginx website](https://www.nginx.com/blog/nginx-1-6-1-7-released/) says:

> Note that stable does not mean more reliable or more bug-free. In fact, the mainline is generally regarded as more reliable because we port all bug fixes to it, and not just critical fixes as for the stable branch. On the other hand, changes in the stable branch are very unlikely to affect third-party modules. We don’t make the same commitment concerning the mainline, where new features can affect the operation of third-party modules.

and

> We recommend that in general you deploy the NGINX mainline branch at all times.

Do you mean stability for the API that passenger is using or stability of nginx? If you aim for the latter, then mainline/1.9 would probably be the right nginx version.

**Comment by FooBarWidget** [comment]
Hm, it used to be that the mainline branch was called the "unstable" branch. Apparently they changed that.

However, they say that in mainline they don't make any commitment to stability w.r.t. third-party modules. Passenger *is* a third-party module. What's more, our Debian Nginx package contains about 10 other third-party modules, in line with what Debian provides in their own Nginx package.
