### ISSUE TITLE
Mysql2::Error (Too many connections)

### ISSUE THREAD

**Issue by 42thcoder** [phusion/passenger#1699]
I got a Rails App runs on Passenger Enterprise. Here is my config:

```
        passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
        passenger_ruby /home/ubuntu/.rvm/gems/ruby-2.1.5/wrappers/ruby;
        passenger_max_request_queue_size 800;
        passenger_max_pool_size 8;
        passenger_max_instances 8;
        passenger_min_instances 8;
        passenger_rolling_restarts on;
        passenger_concurrency_model thread;
        passenger_max_request_time 10;
        passenger_memory_limit 7168;
        passenger_thread_count 25;
```

Here is my database.yml:

```
production:
  adapter: mysql2
  encoding: utf8
  database: pro
  pool: 25
```

And max connections my DB can handle is 300.

When the traffic is high, LOG shows lots of `Mysql2::Error (Too many connections)`, and half of requests failed. 

Do I set these configs correctly? Should I change pool of db from 25 to 100, or even higher?

**Comment by OnixGH** [comment]
In theory, the pool should be as big as the maximum allowed connections per process. In your case that would be the thread count (25), so the pool setting of 25 looks OK.

I don't have much experience in that area, but perhaps the used connections are not closed / released / garbage collected fast enough somehow, or multiple connections are used per request? 

You can try raising the pool setting as a workaround, but not that if your mysql max_connections is 300 then the highest value you can set the pool to is 300 / 8 = 37.

**Comment by OnixGH** [comment]
You can email enterprise support for further assistance specific to your setup.
