### ISSUE TITLE
Content-Length 0 with 204 responses with version 5.0.22

### ISSUE THREAD

**Issue by loivis** [phusion/passenger#1700]
just upgraded to 5.0.22, but we're still suffering from the issue of Content-Length 0 with 204 responses.

passenger status:
```
root@ip-10-254-132-225:~# passenger-status
Version : 5.0.22
Date    : 2015-12-09 11:15:02 +0000
Instance: LFEWpg5w (Apache/2.2.22 (Ubuntu) Phusion_Passenger/5.0.22)
```
header from a curl request:
```
HTTP/1.1 204 No Content
Date: Wed, 09 Dec 2015 11:29:11 GMT
Server: Apache
Cache-Control: no-cache
X-Runtime: 0.085184
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Request-Id: 9b508537-e699-4ad0-b1d2-1c93f53ad872
X-Powered-By: Phusion Passenger 5.0.22
Status: 204 No Content
Content-Length: 0
Content-Type: text/plain
```

any more information needed to further troubleshooting?

**Comment by FooBarWidget** [comment]
It is set by Apache. But isn't this ok? 204 No Content responses have no content so a Content-Length 0 should be fine.

**Comment by OnixGH** [comment]
The issue in #1595 was that a 204 contained both `Transfer-encoding` as well as a `Content-Length`  header, which is invalid. This is solved, also in your output, and I'm don't think just having Content-Length 0 is wrong (there is no body, after all).
