### ISSUE TITLE
passenger installation fails because old selinux version

### ISSUE THREAD

**Issue by soend** [phusion/passenger#1703]
Hei, im trying to install passenger to my server but im receiving this error:

```
Error: Package: passenger-5.0.22-8.el7.x86_64 (passenger)
           Requires: selinux-policy >= 3.13.1-60.el7
           Installed: selinux-policy-3.13.1-23.el7_1.21.noarch (@clearos-centos-updates)
```

The problem is there is no newer package available yet for clearos and forcing the update might break the system. So the question is how could i still install passenger, use older version or anything else?

**Comment by OnixGH** [comment]
Tere :) Just wondering, are you on CentOS 7? 
If yes, did you enable [CR](https://wiki.centos.org/AdditionalResources/Repositories/CR) (see: [Special notes about RPMs on CentOS](https://blog.phusion.nl/2015/12/07/passenger-5-0-22))?

**Comment by soend** [comment]
Yes, im running CentOS 7. Thanks for the link, I will try this next thing tomorrow morning.
