### ISSUE TITLE
Trusty apt sources Error to a 403

### ISSUE THREAD

**Issue by jamesbeedy** [phusion/passenger#1708]
Following the documentation here: https://www.phusionpassenger.com/library/install/nginx/install/oss/trusty/

I get: 

"Err https://oss-binaries.phusionpassenger.com trusty/main amd64 Packages       
  Received HTTP code 403 from proxy after CONNECT"

when trying to update after adding the phusionpassenger repo.

This is blocking deploys for my company! FIX ME PLEASE!

**Comment by FooBarWidget** [comment]
This is not a problem with our APT repository. It is a problem with whatever proxy your company is using. Contact your network administrator.
