### ISSUE TITLE
rack requires Ruby version >= 2.2.2

### ISSUE THREAD

**Issue by nictrix** [phusion/passenger#1710]
Rack recently pushed their 2.0.0 alpha version and passenger installs break on anything using ruby versions below 2.2.2

```
/usr/lib/ruby/ruby-2.1.3_x86_64/bin/gem install passenger -v=5.0.10
ERROR:  Error installing passenger:
	rack requires Ruby version >= 2.2.2.
```

Should passenger's gemspec require rack < 2.0.0 ?

**Comment by nictrix** [comment]
In case anyone is trying to fix this also, I worked around this problem by installing rack then installing passenger with the --conservative switch
```
gem install rack -v=1.6.4
gem install passenger -v=5.0.10 --conservative
```

But I think we should still fix passenger's gemspec runtime dependency

**Comment by FooBarWidget** [comment]
This is not a Passenger problem and we can't really do anything about this, so I'm closing this issue.

**Comment by bhafichuk-redfall** [comment]
Just wondering why this isn't a passenger problem? You're locking passenger to latest instead of a specific version. Even locking to a major version (1.x) would fix this specific issue.
In general not locking down to specific versions is a pervasive issue, its convenient to do as a developer but is a nightmare for operations teams.

@nictrix I appreciate the work around!

**Comment by FooBarWidget** [comment]
We're *not* locking Passenger to the latest version. We are, in fact, not locking Passenger to any specific version of Rack. RubyGems just happens to -- foolishly -- try to install the latest version of Rack, and then during installation finding out that it doesn't work with your Ruby version. That's not a Passenger problem, that's RubyGems not being smart enough to prevent the problem from happening.

If you use something more intelligent, such as Bundler, then this won't happen. Bundler is intelligent enough to foresee such problems, and will intelligently pick the versions that do work with your Ruby version. You mentioned that 'not locking down to specific versions' is an issue. But Bundler is the tool for solving the problem of version lockdowns. Passenger is the wrong place to solve the problem.

Finally, locking Passenger to a specific Rack version is not even the correct thing to do. Passenger is supposed to support any Rack version.

**Comment by peterept** [comment]
For anyone having the same issue, it is resolved in rubygems 2.3.0 which enables you to still use older versions of ruby.

The fix is here:

https://github.com/rubygems/rubygems/commit/0936ca6929172d28b15220dfef8526a9645a90ce

If you are using OpsWorks, in your Rails Layer, set RubyGems version to 2.3.0.

**Comment by aortez** [comment]
I am not sure that @peterept 's solution still works, as that referenced commit excludes prerelease versions and Rack 2.0.0 is no longer prerelease.

**Comment by gkellogg** [comment]
There are few direct dependencies on rack, most are '~> 1.6', including that from sinatra. However, it looks like webmock and rack-cache have '>= 0', which is likely the reason we're getting this. Given that we don't directly depend, we may just want to update the Gemfile. A few other gems are sloppy in their require of rack as well.

**Comment by gkellogg** [comment]
As it ends up, there's a broad move to depend on Ruby version >= 2.2.2, so unwinding this dependency is probably not worth the effort. I suggest going to 2.1.0 across the board. As most dependencies are '~> 2.0', this shouldn't cause too many headaches.

I also don't see any API changes; there's an open issue for [updating Rack history](https://github.com/rack/rack/issues/1092), but hard to see from the raw commits.
