### ISSUE TITLE
Installing the passenger 5 gem requires ruby 2.2

### ISSUE THREAD

**Issue by anfleene** [phusion/passenger#1712]
Due to passenger gem dependency on rack and [rack releasing](https://rubygems.org/gems/rack/versions/2.0.0.alpha) a ruby >= 2.2.2 only alpha causes a dependency install error unless you're using 2.2.2 or above. 
```bash
# on ruby 2.1
$ gem install passenger                                                                                                                                
Fetching: rack-2.0.0.alpha.gem (100%)
ERROR:  Error installing passenger:
	rack requires Ruby version >= 2.2.2.
$   
```                                                                                                                                                   

Can we pin passenger to the rack 1.6 line for the time being?

There is a workaround here you just have to install rack 1.6 first or if you're using bundler pin it to `~> 1.6`
Thanks!

**Comment by FooBarWidget** [comment]
This is not a Passenger problem. See the discussion at #1710.

> Can we pin passenger to the rack 1.6 line for the time being?

Use Bundler.

**Comment by anfleene** [comment]
Sorry about the duplicate :disappointed: . I guess I didn't search the issues very well.
