### ISSUE TITLE
FreeBSD 10.1 Installation PassengerRoot & PassengerRuby Wrong Directives on nginx

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#1715]
Generated directives for nginx on FreeBSD installation of Passenger:

    PassengerRoot /usr/local/lib/ruby/gems/2.1/gems/passenger-5.0.22
    PassengerRuby /usr/local/bin/ruby21

Config file not passing test, I'm thinking t should be:

    passenger_root /usr/local/lib/ruby/gems/2.1/gems/passenger-5.0.22
    passenger_ruby /usr/local/bin/ruby21

**Comment by OnixGH** [comment]
Where did you find these directives? The top ones are for Apache, not nginx.

**Comment by daBee** [comment]
There were no directives for nginx and the Apache directives were mentioned twice.

**Comment by OnixGH** [comment]
@daBee: URL?

**Comment by daBee** [comment]
http://pastebin.com/ZugfnPP2

**Comment by FooBarWidget** [comment]
That's a problem with the FreeBSD port. We can't do anything about this issue: we have no control over what the port does. You should contact the maintainer of that port about this issue.
