### ISSUE TITLE
mod_passenger.so: undefined symbol: ap_rputs

### ISSUE THREAD

**Issue by liepa** [phusion/passenger#1717]
Recently i have upgraded apache 2.2 => Apache/2.4.6 (Red Hat)
after that, i got this issue

OS is Red Hat Enterprise Linux Server release 6.7 (Santiago)
passenger (5.0.21)
Rails 4.1.7

user@server~$ httpd -k start -f /home/user/httpd/conf/httpd.conf
httpd: Syntax error on line 216 of /home/user/httpd/conf/httpd.conf: Syntax error on line 1 of /home/user/httpd/conf.d/passenger.load: Cannot load /home/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/passenger-5.0.21/buildout/apache2/mod_passenger.so into server: /home/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/passenger-5.0.21/buildout/apache2/mod_passenger.so: undefined symbol: ap_rputs

user@server~$ gem env
RubyGems Environment:

- RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.1.2 (2014-05-08 patchlevel 95) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
  - RUBY EXECUTABLE: /home/user/.rbenv/versions/2.1.2/bin/ruby
  - EXECUTABLE DIRECTORY: /home/user/.rbenv/versions/2.1.2/bin
  - SPEC CACHE DIRECTORY: /home/user/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/user/.rbenv/versions/2.1.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
     - /home/user/.gem/ruby/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/

**Comment by OnixGH** [comment]
Does recompiling the module by doing `passenger-install-apache2-module` help?

**Comment by liepa** [comment]
Problem was related do to the fact that passenger-install-apache2-module was using wrong(apache 2.2) APXS2.
I followed these steps (https://www.phusionpassenger.com/library/install/apache/customizing_compilation_process.html#forcing-location-of-command-line-tools-and-dependencies) to change APXS2 path to apache 2.4, and now recompiling the module everything worked.

Thanks!
