### ISSUE TITLE
dependency problem: rack 2.0.0alpha

### ISSUE THREAD

**Issue by pschrammel** [phusion/passenger#1718]
Hi,
I have an issue when installing the gem in a clean ruby environment (no rack installed). 
I think this is because of the release of rack-2.0.0alpha and the lack of version in the gemspec file. 

Can anybody verify this? I think the solution would be to give a maximum version of rack in the gemspec file.

**Comment by OnixGH** [comment]
Duplicate of https://github.com/phusion/passenger/issues/1710
