### ISSUE TITLE
mod_passenger install fails on CentOS 7.2 webserver (Requires: httpd-mmn = 20120211x8664)

### ISSUE THREAD

**Issue by CryptoSnippets** [phusion/passenger#1721]
Hello,

I've been following the install instructions at https://www.phusionpassenger.com/library/install/apache/install/oss/el7/ for my new server setup on CentOS 7 and the installation fails with the following message:

    Error: Package: mod_passenger-5.0.23-8.el7.x86_64 (passenger)
               Requires: httpd-mmn = 20120211x8664
     You could try using --skip-broken to work around the problem
     You could try running: rpm -Va --nofiles --nodigest

Thanks in advance for any help.

Alexis

**Comment by FooBarWidget** [comment]
As documented in the release notes, you need to ensure that CR is enabled. See https://blog.phusion.nl/2015/12/21/passenger-5-0-23/, section "Special notes about RPMs on CentOS".

**Comment by OnixGH** [comment]
@FooBarWidget I already said the same on the [forum](https://groups.google.com/forum/#!topic/phusion-passenger/FdMaVa6FdHE) but @CryptoSnippets correctly pointed out that in the blog we explicitely say the CR workaround must be turned OFF for 7.2+.

Furthermore turning it on didn't solve the issue.

**Comment by CryptoSnippets** [comment]
@OnixGH Cheers for catching that!

**Comment by CryptoSnippets** [comment]
Is there any disadvantage to installing the old way with the passenger gem?  I might try it that way for now as my old server goes offline in 48hrs and I can always change installation type later.

**Comment by OnixGH** [comment]
@CryptoSnippets In terms of passenger itself, no.

The packaged way is supposed to be easier to manage and less (setup) error-prone, if it works that is..

**Comment by CryptoSnippets** [comment]
Ah, good to know.  Thanks Daniel.

**Comment by FooBarWidget** [comment]
I've just confirmed that our RPMs work fine on CentOS 7. I don't get any dependency errors, even if I don't enable CR.

@CryptoSnippets I think you just need to clear your caches and install the latest YUM updates. Try `yum clean all && yum update`

**Comment by stwf** [comment]
I still get this error. Even after yum clean all && yum update

on CentOS 7.2

**Comment by FooBarWidget** [comment]
Did you add any third party repositories that may contain Apache packages?
Our RPMs only work with the official CentOS Apache packages. For example,
if you installed Apache through cPanel then our RPMs won't work.

**Comment by stwf** [comment]
I did have it working before, but I believe it was through the gem, and not the RPM's. Yes I am installing Apache through CPanel and WHM. And its too late to back out of that. I will go back to the old install method for now. thanks.

**Comment by CryptoSnippets** [comment]
I'm also using a WHM/Cpanel server.  WHM takes control of most server software but I don't think it uses a modified Apache.  If it did I would imagine most web servers will have this same issue then.

**Comment by FooBarWidget** [comment]
We have had at least one other reporter whose RPM installation problems were caused by the fact that he installed Apache through cPanel. We recommend that you use the RubyGems or tarball installation method instead.

**Comment by CryptoSnippets** [comment]
Cheers FooBarWidget, Yep, I've been running the 5.0.23 Gem without issue.

**Comment by stwf** [comment]
Hi, I'm back! OK, I upgraded my EasyApache install and I can no longer install passenger, even through the gem. I installed v v5.0.28 of the gem.
The install proceeds and alerts me I am missing the following dependencies:
Checking for Apache Portable Runtime (APR) development headers...
      Found: no
 * Checking for Apache Portable Runtime Utility (APU) development headers...
      Found: no

But following the instructions yum tells me that:
Package apr-devel-1.4.8-3.el7.x86_64 already installed and latest version
Package apr-util-devel-1.5.2-6.el7.x86_64 already installed and latest version
Nothing to do

Any ideas?

**Comment by OnixGH** [comment]
@stwf Please post the entire build output. For example, are you sure there aren't any errors before this?

**Comment by stwf** [comment]
OK, I got this to work. It turns out you just need to enter the right keywords into google in the right order to get your answer. lol.

So for me the following steps were necessary
yum remove httpd-tools
yum install ea-apache24-devel

**Comment by OnixGH** [comment]
Ha, I think I we probably found the same thread:
https://forums.cpanel.net/threads/easyapache-4-questions.502821/

**Comment by TheCuriousHacker** [comment]
This might become useful:

```
yum install “developer tools”

yum install centos-release-scl

yum list available rh-ruby23-\*

yum install rh-ruby23

yum install rh-ruby23-ruby-devel

scl enable rh-ruby23 bash

sudo yum list rh-ruby23\*

gem install rails -v 4.2.0  

gem install passenger
```

**Comment by mariohmol** [comment]
for those who is getting trouble with that, another way to solve https://webinove.wordpress.com/2017/09/16/mod_passenger-with-whm-centos7/
