### ISSUE TITLE
'passenger-config restart-app .' Doesn't worked as expected

### ISSUE THREAD

**Issue by baens** [phusion/passenger#1723]
This is with passenger 5.0.23

I am in the current directory that is running the passenger instance (so the passenger.300.pid exists)

I execute the following:

```bash
> passenger-config restart-app .
```

I get this output

```bash
It appears that multiple Phusion Passenger instances are running. Please select
a specific one by passing:

  --instance <NAME>

The following Phusion Passenger instances are running:

Name                       PID      Description
--------------------------------------------------------------------------
UjJHN4uu                   2919     nginx/1.8.0 Phusion_Passenger/5.0.23
```

I was expecting the instance to have been restarted. Am I reading the help document incorrectly and this isn't expected? Or was this a bug?

**Comment by OnixGH** [comment]
I can't tell from your output, but was there another passenger instance running or not? (i.e. was there another line below the 2919 instance?)

If not, what is the output of passenger-memory-stats? And can you tell us more about your setup? OS, what kind of application, etc?

**Comment by baens** [comment]
Oops sorry, I did leave out that. Yes there were multiple instances running this. I had one running at ~/app then another one running at /tmp/app. The idea was I wanted to restart the app from the current directory.

**Comment by OnixGH** [comment]
Aha, in that case it's the expected behavior. `passenger-config` doesn't technically know about applications, it just relays it to a passenger instance, so if there are multiple up, the current implementation just comes back to you.

It will happen as you expected if you just run a single passenger instance and let it handle both (or more) applications.
