### ISSUE TITLE
Request for more debugging information when a 500 response is being sent back to client.

### ISSUE THREAD

**Issue by baens** [phusion/passenger#1725]
We have an architecture where passenger is behind a few other processing boxes. For debugging purposes, we would like if there was a way to add a configuration flag to the nginx template that would dump some header information on a 500 response. This would help us track certain requests down the pipeline and allow us to try and debug across multiple servers. 

If this is already possible, please just point it out and I'll be happy to move along that path.

**Comment by OnixGH** [comment]
FYI: in Passenger 5.0.22 we added [HTTP 5xx header logging](https://blog.phusion.nl/2015/12/07/passenger-5-0-22) to [Union Station](https://www.unionstationapp.com).

**Comment by OnixGH** [comment]
Unfortunately we don't see this feature making its way into our priority list in the near future.

In theory you could raise the log level and apply your own analysis & filtering on it. There is also the mentioned Union Station workaround (if you do go for that route the Union Station team would be happy to assist if needed).
