### ISSUE TITLE
Add support for configuring `listen` backlog

### ISSUE THREAD

**Issue by jwilm** [phusion/passenger#1726]
The backlog is currently hardcoded to 1024 in IOUtils.cpp. Although `createServer` takes `backlog` as a parameter, it is not used in practice. It would be really nice if the backlog was configurable through nginx.conf and other nginx conf files.

Context
Our traffic sometimes arrives in large bursts, and increasing the backlog is desirable to avoid getting `ECONNREFUSED` during those times. The only way to control this important variable presently is to recompile passenger + nginx.

**Comment by FooBarWidget** [comment]
We deemed it not necessary to have a configurable backlog because the Passenger core server is evented. It should already be able to accept large bursts of new connections. Are you saying that your bursts arrive faster than the Passenger core server can accept then?

Can you show me a snippet of an error message that indicates that it's the Passenger core server's backlog that's overflown, and not some other component's backlog?

**Comment by jwilm** [comment]
This is what we see in our nginx error logs repeatedly when connections start getting dropped. I removed the IP addresses and HTTP path, but everything else is unchanged.

```
2016/01/18 09:06:35 [error] 12794#0: *1456128796 connect() to unix:/tmp/passenger.fLrr3pC/agents.s/core failed (11: Resource temporarily unavailable) while connecting to upstream, client: ..., server: ..., request: "PUT /... HTTP/1.0", upstream: "passenger:unix:/tmp/passenger.fLrr3pC/agents.s/core:", host: ...
```

**Comment by FooBarWidget** [comment]
Looks like that's indeed the Passenger core server's socket backlog being overflown.

**Comment by OnixGH** [comment]
@jwilm could you tell us something about what kind of setup & load you have that this is occurring? 

We're considering the option but it would be good to understand the conditions better to ensure we're solving the right problem.

**Comment by jwilm** [comment]
The conditions under which this occurred was with a load average over 40 on a 40 core machine. We have 400 Rails workers in passenger servicing over 110k RPM. The server also has a couple of high CPU processes so the load average is not exclusively consumed by passenger + workers.

Is there certain information that would be helpful? Not totally sure what you're looking for :).

**Comment by OnixGH** [comment]
@jwilm that's good enough, thanks.

What do you have your nginx `worker_connections` set to? I'm assuming you already upped that since it seems to me like the first limit that would be hit?

**Comment by jwilm** [comment]
worker_connections is set to 30000.

**Comment by OnixGH** [comment]
Doc: https://www.phusionpassenger.com/library/config/reference/?a=passenger_socket_backlog

**Comment by jwilm** [comment]
Thanks for the super quick implementation. You guys rock!
