### ISSUE TITLE
Implement the ability to shutdown individual Passenger apps

### ISSUE THREAD

**Issue by strugee** [phusion/passenger#1734]
I run several Passenger apps through Apache. I need to disable individual Passenger apps while I perform database migrations, but at the moment all I can do is stop all of Apache. This is unfortunate, so it would be great if I could turn off individual Passenger apps inside Apache.

**Comment by sae249833** [comment]
+1.  Also the ability to provide a "Down for Maintenance" page would be great!

**Comment by FooBarWidget** [comment]
You can already do that without an explicit Passenger feature. For example: https://github.com/capistrano/maintenance

**Comment by FooBarWidget** [comment]
Or are you two actually talking about two different issues? Maybe @strugee wants a way to shut down the application processes, while @sae249833 wants a 'down for maintenance page'?

**Comment by OnixGH** [comment]
@strugee just to be clear, this is what you can do:

Suppose you have Application A B and C and you want to do maintenance on B.
1. Put up the maintenance page specifically for application B (see the info @FooBarWidget linked to). This effectively "turns off B" (no new requests)
2. Now, wait until the current requests are drained (you can use `passenger-status` to see this)
3. Perform migration and/or app updates
4. Restart B if needed (`passenger-config restart-app`)
5. Remove maintenance page

**Comment by sae249833** [comment]
I agree @FooBarWidget that it can be done.  However, I'm implying that it would be nice to have it built into Passenger.  For example, just like the Capistrano-Maintenance gem works just have Passenger detect the presence of a maintenance page and switch to a "maintenance mode", sort of siimilar to how it detects an updated tmp/restart.txt.  This would be a lot simpler than reconfiguring the apache configs for each application on each server, installing the gem, cap deploying it for maintenance, etc...

@OnixGH, as an admin I would like the app owners to be able to put their websites in maintenance and be able to make changes without admin support.  You're procedure would require the app owners to be able to run as the user who is executing Passenger and know the Passenger commands to check status, restart, etc.  Again, I guess I'm saying it would be nice for Passenger to automatically detect that maintenance mode is configured for a particular app, allow app changes to occur, and then resume/restart once it detects maintenance mode is no longer needed.

So, in effect, I'm requesting an enhancement to the server.

**Comment by FooBarWidget** [comment]
I've split @sae249833's request to #1739.
