### ISSUE TITLE
Update to NGINX 1.8.1

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1736]
The binary packages and installers for the next release should default to nginx 1.8.1, which fixes several CVEs.

See [NGINX 1.8 Changes](http://nginx.org/en/CHANGES-1.8) for details on the fixed CVEs.

**Comment by OnixGH** [comment]
This is already made it to stable: https://github.com/phusion/passenger/commit/6eebafa484aab21a699bedd121ce5c03c8101d3d.

**Comment by felixbuenemann** [comment]
Thanks, forgot to check the changelog on master…

**Comment by felixbuenemann** [comment]
Btw. any reason that 5.0.24 has not yet been tagged / released?

**Comment by FooBarWidget** [comment]
It's scheduled for Monday.

**Comment by felixbuenemann** [comment]
Good to know, enjoy the weekend!
