### ISSUE TITLE
Upgrade nginx to 1.9.x

### ISSUE THREAD

**Issue by dmitry** [phusion/passenger#1737]
Is there are planned an upgrade of nginx to a version 1.9.x?

Asking, because I like the .deb packages, and don't want to compile everything by myself, but 1.9 version has a http2 support.

**Comment by OnixGH** [comment]
Duplicate of #1697.

Basically 1.9.x mainline doesn't make a stability commitment on third-party modules (i.e. Passenger and about 10 other third-party modules we use).
