### ISSUE TITLE
Passenger Standalone stopped setting X-Forwarded-Proto from version 5.0.22

### ISSUE THREAD

**Issue by losadaem** [phusion/passenger#1749]
I'm using Passenger Standalone behind an Apache reverse proxy with RoR. After updating to 5.0.22 (or higher) RoR doesn't detect ssl because of the missing X-Forwarded-Proto header. If I revert back to 5.0.21 everything works fine again.

**Comment by OnixGH** [comment]
Can you check that you are not depending on any headers with _ underscores? Due to a security fix in these are now filtered out starting from 5.0.22.

**Comment by losadaem** [comment]
I missed that! I was setting

```
RequestHeader set X_FORWARDED_PROTO 'https'
```

Changed it to X-FORWARDED-PROTO and everything's ok.

Thanks!
