### ISSUE TITLE
Crash with Error: CERT_HAS_EXPIRED when running standalone meteor

### ISSUE THREAD

**Issue by peterweck** [phusion/passenger#1750]
I'm running Phusion Passenger 5.0.24 in standalone mode with 10 node instances and a long pool_idle_time:

  "max_pool_size": 10,
  "min_instances": 10,
  "max_preloader_idle_time": 0,
  "pool_idle_time": 604800,

The instances are never idle for more than a minute. Every 15-45 minutes one of the instances is crashing with the following errors showing up in the log file:

App 21352 stderr: Error: CERT_HAS_EXPIRED
App 21352 stderr:     at SecurePair.<anonymous> (tls.js:1381:32)
App 21352 stderr:     at SecurePair.emit (events.js:92:17)
App 21352 stderr:     at SecurePair.maybeInitFinished (tls.js:980:10)
App 21352 stderr:     at CleartextStream.read [as _read] (tls.js:472:13)
App 21352 stderr:     at CleartextStream.Readable.read (_stream_readable.js:341:10)
App 21352 stderr:     at EncryptedStream.write [as _write] (tls.js:369:25)
App 21352 stderr:     at doWrite (_stream_writable.js:226:10)
App 21352 stderr:     at writeOrBuffer (_stream_writable.js:216:5)
App 21352 stderr:     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
App 21352 stderr:     at write (_stream_readable.js:602:24)
App 21352 stderr:     at flow (_stream_readable.js:611:7)
App 21352 stderr:     at Socket.pipeOnReadable (_stream_readable.js:643:5)
[ 2016-02-17 00:08:54.1639 2530/7f952f7fe700 age/Cor/Con/InternalUtils.cpp:105 ]: [Client 8-2330] Sending 502 response: application did not send a complete response
[ 2016-02-17 00:08:54.3516 2530/7f952de78700 age/Cor/CoreMain.cpp:794 ]: Checking whether to disconnect long-running connections for process 21352, application /var/www/sjeditor/prod/public (production)

The box has 12 cpus and 32GB of ram. Any suggestions on how to avoid this crash would be be very much appreciated.

**Comment by OnixGH** [comment]
This is not a Passenger crash, but something in your application. Judging from the top line, something in tls.js, maybe this: https://github.com/eleith/emailjs/issues/109

**Comment by peterweck** [comment]
Thanks. Appreciate the quick response. It looks like is the mysql package that is making the ssl call.
