### ISSUE TITLE
Passenger Enterprise 4.0.60 requires rack-2.0.0-alpha/ruby 2.2.2 now 

### ISSUE THREAD

**Issue by vrsean** [phusion/passenger#1751]
Apparently, there's no lock to a specific version for rack in Passenger Enterprise 4.0.60.  This installed fine for us a little while ago but now we are faced with the issue:

Fetching: rack-2.0.0.alpha.gem (100%)
ERROR:  Error installing /tmp/vrexec/passenger-enterprise-server-4.0.60.gem:
rack requires Ruby version >= 2.2.2.

We are unable to upgrade to 2.2.2 at this time.  Is there a chance a new version of 4.0.x can be locked to a version that doesn't need ruby 2.2.2?

**Comment by FooBarWidget** [comment]
Please see the discussion at https://github.com/phusion/passenger/issues/1710, that thread contains your solution.
