### ISSUE TITLE
Custom nginx rbenv passenger rake not found

### ISSUE THREAD

**Issue by dcalixto** [phusion/passenger#1753]
0
down vote
favorite
Someone is getting this kind of problem when try to compile passenger with a custom nginx install?

have any passenger version that compile without problem?

or is because of the rbenv?

thank's

 + ngx_pagespeed was configured
adding module in /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.19/src/nginx_module
*** The Phusion Passenger support files are not yet compiled. Compiling them for you... ***
*** Running 'rake nginx CACHING=false' in /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.19/src/nginx_module... ***
./configure: 28: /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.19/src/nginx_module/config: rake: not found
make[1]: *** [config.arch.full] Error 1
make[1]: Leaving directory `/home/ubuntu/build/nginx-1.9.10'
make: *** [build] Error 2

**Comment by OnixGH** [comment]
It doesn't look like a Passenger problem: `rake: not found`. Could be rbenv. Maybe rehash and install rake.

**Comment by dcalixto** [comment]
is inside passenger nginx module, how is not a passenger problem?

**Comment by FooBarWidget** [comment]
The Passenger Nginx module configure script requires Rake. As you can see in the error message, it could not find Rake. You need to ensure that Passenger's Nginx module configure script can find Rake; Passenger cannot do that for you.

**Comment by dcalixto** [comment]
right i updated the passenger:

**Comment by dcalixto** [comment]
and now:

-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -lpthread -lpthread -lcrypt -lpam -lexpat -lstdc++ /home/ubuntu/build/nginx-1.9.10/debian/modules/ngx_pagespeed-release-1.10.33.5-beta/psol/lib/Debug/linux/x64/pagespeed_automatic.a -lrt -pthread -lm /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Logging.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Exceptions.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Utils/SystemTime.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Utils/StrIntUtils.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Utils/StrIntUtilsNoStrictAliasing.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Utils/IOUtils.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Utils.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/WatchdogLauncher.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/AppTypes.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Utils/CachedFileStat.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/UnionStationFilterSupport.o /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libboost_oxt.a -lstdc++ -lpthread -lm -lrt -lpcre -lssl -lcrypto -ldl -lz -lxml2 -lxslt -lexslt -lgd -lGeoIP
/usr/bin/ld: /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Logging.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/passenger-5.0.25/buildout/common/libpassenger_common/Logging.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[3]: *** [objs/nginx] Error 1
make[3]: Leaving directory `/home/ubuntu/build/nginx-1.9.10/debian/build-full'
make[2]: *** [build] Error 2
make[2]: Leaving directory `/home/ubuntu/build/nginx-1.9.10/debian/build-full'
make[1]: *** [build.arch.full] Error 2
make[1]: Leaving directory `/home/ubuntu/build/nginx-1.9.10'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by dcalixto** [comment]
i'm using sudo dpkg-buildpackage -b command

**Comment by OnixGH** [comment]
Building passenger + nginx-1.9.10 + ngx_pagespeed-release-1.10.33.5-beta on Ubuntu works for me using the official way to install: `passenger-install-nginx-module`.

Please continue at the [support forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger) if that doesn't work for you.

**Comment by FooBarWidget** [comment]
@OnixGH Building the Passenger module through the normal Nginx configure + make process is [officially supported](https://www.phusionpassenger.com/library/install/nginx/install_as_nginx_module.html). I see that his compilation command includes `-fPIE`. I wonder how that got in there? Maybe he's using Nginx's new dynamic modules feature?

@dcalixto Can you show me the full './configure' invocation?

**Comment by FooBarWidget** [comment]
I think I know what's going on. You're building a Debian package, so you most likely set CFLAGS to include Debian's recommended hardening flags. That includes -fPIE, among other things. But if you do that then you need to ensure that Passenger is also compiled with -fPIE (and possibly other flags). Passenger does not respect the CFLAGS environment variable, but does respect other environment variables which you can set. It's documented here: https://www.phusionpassenger.com/library/install/nginx/customizing_compilation_process.html

Since you're doing something custom, you are responsible for ensuring that the correct flags are passed to the Passenger build system, whatever "correct" means in your context. Passenger is not able to figure out for you what you need.

**Comment by shisongsong** [comment]
@dcalixto I got the same problem, but update passenger didn't work for me.

**Comment by CamJN** [comment]
@shisongsong please open a separate issue, and fill in all the requested details.
