### ISSUE TITLE
Can't start server in Vagrant box: `flock': No locks available @ rb_file_flock - /tmp/pids/passenger.3000.pid.lock (Errno::ENOLCK)

### ISSUE THREAD

**Issue by cesc1989** [phusion/passenger#1755]
This is a Ruby(2.1.5p273) on Rails(4.2.0) app that runs on Phusion Passenger standalone in development environment. I run it in a Vagrant Ubuntu 14.04 based box in a MBP(at work) and a Linux Mint PC(home).

In gemfile: `gem 'passenger'`

Right now it is at `passenger (5.0.24)` but I've faced the same issue on version 5.0.25.

The command I normally use to start the rails server is `passenger start` which is in a Procfile.

    rails: passenger start
    sidekiq: bundle exec sidekiq

In the vagrant box I use in my home PC, when I issue the command `foreman start` or `passenger start` I get:

    /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller/lock_file.rb:67:in `flock': No locks available @ rb_file_flock - /vagrant/tmp/pids/passenger.3000.pid.lock (Errno::ENOLCK)
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller/lock_file.rb:67:in `block in exclusive_lock'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller/lock_file.rb:63:in `open'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller/lock_file.rb:63:in `exclusive_lock'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:219:in `start'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/standalone/start_command/nginx_engine.rb:49:in `start_engine_real'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/standalone/start_command.rb:322:in `start_engine'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/standalone/start_command.rb:63:in `run'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/src/ruby_supportlib/phusion_passenger/standalone/main.rb:51:in `run!'
    	from /home/vagrant/ruby/lib/ruby/gems/2.1.0/gems/passenger-5.0.25/bin/passenger:45:in `<top (required)>'
    	from /home/vagrant/ruby/bin/passenger:23:in `load'
    	from /home/vagrant/ruby/bin/passenger:23:in `<main>'

When I use the command `passenger-config restart-app` I get:

    *** ERROR: Phusion Passenger doesn't seem to be running. If you are sure that it
    is running, then the causes of this problem could be one of:
    
     1. You customized the instance registry directory using Apache's
        PassengerInstanceRegistryDir option, Nginx's
        passenger_instance_registry_dir option, or Phusion Passenger Standalone's
        --instance-registry-dir command line argument. If so, please set the
        environment variable PASSENGER_INSTANCE_REGISTRY_DIR to that directory
        and run this command again.
     2. The instance directory has been removed by an operating system background
        service. Please set a different instance registry directory using Apache's
        PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir
        option, or Phusion Passenger Standalone's --instance-registry-dir command
        line argument.

Env. variable `PASSENGER_INSTANCE_REGISTRY_DIR` is not set, so [following passenger's documentation](https://www.phusionpassenger.com/library/config/standalone/reference/#--instance-registry-dir-instance_registry_dir) I try to set it doing:

`export PASSENGER_INSTANCE_REGISTRY_DIR=/vagrant/tmp` or `export PASSENGER_INSTANCE_REGISTRY_DIR=tmp`

And then

`sudo -E passenger-status` but with this one I get `sudo: passenger-status: command not found`

As per [Hongli's answer](http://stackoverflow.com/a/31769807/1407371) in a SO thread with a similar situation, the command `sudo env PASSENGER_INSTANCE_REGISTRY_DIR=/tmp passenger-status` returns:

    env: passenger-status: No such file or directory

Finally, in my rails app tmp/ folder there are the passenger pid files:

- passenger.3000.pid
- passenger.3000.pid.lock

I'm really clueless. There's no log and everything I've searched and found didn't solve this.

**Comment by FooBarWidget** [comment]
ENOLCK means the operating system's lock table is full. I have no idea what's causing that or how to fix that though.

Sudo [nukes environment variables](https://www.phusionpassenger.com/library/indepth/environment_variables.html#environment-variables-and-sudo) so you need to specify the full path.

**Comment by cesc1989** [comment]
Hey, @FooBarWidget thanks for taking the time. You see, what you posted was really helpful as it served as a guide for what to lock.

My issue is with the NFS server installed in my home machine.
