### ISSUE TITLE
having problem installing passenger with puppet

### ISSUE THREAD

**Issue by kosewu** [phusion/passenger#1761]
Please help been battling this for hours
passenger version
/usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26/buildout/apache2/mod_passenger.so

ruby -v 
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]

Went into my /tmp/passenger-error-qBkEHX.html and this is what i get:
  <ul class="corporate_identity">
                                <li class="logo"><a href="https://www.phusionpassenger.com"><span>Phusion Passenger</span></a></li>
                        </ul>
                </div>
                <div id="site_body">
                        <h1 class="error_title">Web application could not be started</h1>
                        <div id="content">
                                <pre>cannot load such file -- puppet/application/master (LoadError)
  /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:<wbr>55:<wbr>in `require&apos;
  /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:<wbr>55:<wbr>in `require&apos;
  config.ru:<wbr>13:<wbr>in `block in &lt;main&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/rack-1.6.4/lib/rack/builder.rb:<wbr>55:<wbr>in `instance_eval&apos;
  /usr/local/share/ruby/gems/2.0/gems/rack-1.6.4/lib/rack/builder.rb:<wbr>55:<wbr>in `initialize&apos;
  config.ru:<wbr>1:<wbr>in `new&apos;
  config.ru:<wbr>1:<wbr>in `&lt;main&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>110:<wbr>in `eval&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>110:<wbr>in `preload_app&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>156:<wbr>in `&lt;module:<wbr>App&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>30:<wbr>in `&lt;module:<wbr>PhusionPassenger&gt;&apos;
  /usr/local/share/ruby/gems/2.0/gems/passenger-5.0.26//src/helper-scripts/rack-preloader.rb:<wbr>29:<wbr>in `&lt;main&gt;&apos;
</pre>

                                <dl>
                                <dt>Error ID</dt>
                                <dd>c0722536</dd>
                                <dt>Application root</dt>
                                <dd>/usr/share/puppet/rack/puppetmasterd</dd>
                                <dt>Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)</dt>
                                <dd>production</dd>

                                        <dt>Ruby interpreter command</dt>
                                        <dd><pre>/usr/bin/ruby</pre></dd>

                                <dt>User and groups</dt>
                                <dd><pre>uid=<wbr>52(puppet) gid=<wbr>52(puppet) groups=<wbr>52(puppet)
</pre></dd>
                                <dt>Environment variables</dt>
                                <dd><pre>TERM =<wbr> xterm
PATH =<wbr> /sbin:<wbr>/usr/sbin:<wbr>/bin:<wbr>/usr/bin
PWD =<wbr> /usr/share/puppet/rack/puppetmasterd
LANG =<wbr> C
SHLVL =<wbr> 2
_ =<wbr> /usr/sbin/httpd

**Comment by OnixGH** [comment]
This looks like an issue with your environment rather than Passenger, check that you have puppet installed for the ruby version you're using (2.0).

Questions about your setup can be posted at [the forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger).

**Comment by kosewu** [comment]
I do have puppet installed. Puppet is working fine with Webrick. And I'm
using ruby2.0. This issue I'm having occurs in aws. However if I install
using vmware, it seems to work perfectly. So you might be right

**Comment by kosewu** [comment]
I installed puppet version 3.8
