### ISSUE TITLE
Passenger-core at 100% CPU

### ISSUE THREAD

**Issue by veloutin** [phusion/passenger#1762]
I have had this issue happen during last night at around the same time on two machines, and on three machines today. All running passenger-5.0.20 with ruby1.9.

The process gets stuck at 100% CPU. strace -p PID gives me 

> select(11, [3 10], NULL, NULL, NULL

and nothing else.

backtrace:

> 0x00007fbba1fe1303 in select () from /lib64/libc.so.6
> Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.23-13.16.amzn1.x86_64 glibc-2.17-106.166.amzn1.x86_64 keyutils-libs-1.5.8-3.12.amzn1.x86_64 krb5-libs-1.12.2-14.43.amzn1.x86_64 libcom_err-1.42.12-4.40.amzn1.x86_64 libcurl-7.40.0-3.52.amzn1.x86_64 libidn-1.18-2.8.amzn1.x86_64 libselinux-2.1.10-3.22.amzn1.x86_64 libssh2-1.4.2-1.10.amzn1.x86_64 nspr-4.10.8-2.35.amzn1.x86_64 nss-3.19.1-7.74.amzn1.x86_64 nss-softokn-freebl-3.16.2.3-13.37.amzn1.x86_64 nss-util-3.19.1-4.47.amzn1.x86_64 openldap-2.4.23-34.25.amzn1.x86_64 openssl-1.0.1k-10.87.amzn1.x86_64 zlib-1.2.8-7.18.amzn1.x86_64
> (gdb) bt
> #0  0x00007fbba1fe1303 in select () from /lib64/libc.so.6
> #1  0x000000000069a277 in oxt::syscalls::select (nfds=11, readfds=0x7ffc1689cfd0, writefds=0x0, errorfds=0x0, timeout=0x0) at src/cxx_supportlib/oxt/system_calls.cpp:463
> #2  0x00000000004edc59 in waitForExitEvent () at src/agent/Core/CoreMain.cpp:850
> #3  0x00000000004ed605 in mainLoop () at src/agent/Core/CoreMain.cpp:778
> #4  0x00000000004ee9bd in runCore () at src/agent/Core/CoreMain.cpp:970
> #5  0x00000000004f2374 in coreMain (argc=3, argv=0xa9e7f0) at src/agent/Core/CoreMain.cpp:1199
> #6  0x000000000047780e in dispatchSubcommand (argc=3, argv=0x7ffc1689e488) at src/agent/AgentMain.cpp:83
> #7  0x0000000000477968 in main (argc=3, argv=0x7ffc1689e488) at src/agent/AgentMain.cpp:104
> (gdb)

The app keeps responding to requests for now, although last night one of the servers eventually ran out of open files and stopped responding.

Eventually, restart nginx got the process SIGKILL'ed when I restarted.

**Comment by FooBarWidget** [comment]
There was a 100% cpu bug a few releases ago. It has already been fixed.
Please upgrade.
