### ISSUE TITLE
Installer does not detect correct configuration in included Apache conf files

### ISSUE THREAD

**Issue by thenadz** [phusion/passenger#1766]
Apache module installer does not detect that the correct `LoadModule` call and `IfModule` block are present if they are under the correct location for such things -- `conf.d` and `conf.modules.d` respectively.

This encourages unmaintainable Apache config files and shouldn't be too difficult to resolve.

**Comment by FooBarWidget** [comment]
What is your distribution and version? What exact message do you see from Passenger?

**Comment by thenadz** [comment]
Shouldn't really matter... But Amazon Linux 2015.03 and the message is just the generic Apache config is not correct which shows up when the `IncludeModule` call and following `IfModule` calls are missing. I don't have the error in front of me, but it's nothing special.

Again, the above should not be relevant. The Installer just needs to follow all include paths in the central `httpd.conf`. That's the only valid fix and it shouldn't be distro-dependent.

**Comment by FooBarWidget** [comment]
It does matter,  because I don't understand the issue you are describing.
The installer *already* follows all the include directives. By providing
more information I can do a better analysis of the issue.

**Comment by thenadz** [comment]
Ah. My apologies then. I just assumed it was not. Let me collect that information and I'll get back to you momentarily.

**Comment by thenadz** [comment]
Whelp, I'm dumb. Was a syntax error related to bumping Apache version from 2.2 to 2.4. After resolving, Passenger correctly recognizes the configuration in included files.

Thanks for your help!
