### ISSUE TITLE
Crash on start, cause probably config

### ISSUE THREAD

**Issue by garygriswold** [phusion/passenger#1770]
I received the following error:

*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: [emerg] "gzip_types" directive The user specified by the 'default_user' option does not exist. in nginx.conf:123
    nginx: configuration file nginx.conf test failed

Personally, I doubt this is a bug in Passenger.  I think I have not done a correct configuration for Rails.  The passenger website gives instructions for Ruby, but that does not seem to be exactly correct for ruby

[deploy@localhost ecs_online]$ cat /tmp/passenger-standalone-x50171.log
##########################################################################
#  Passenger Standalone is built on the same technology that powers
#  Passenger for Nginx, so any configuration option supported by Passenger
#  for Nginx can be applied to Passenger Standalone as well. You can do
#  this by direct editing the Nginx configuration template that is used by
#  Passenger Standalone.
#
#  This file is the original template. DO NOT EDIT THIS FILE DIRECTLY.
#  Instead, make a copy of this file and pass the `--nginx-config-template`
#  parameter to Passenger Standalone.
#
#  Learn more about using the Nginx configuration template at:
#  https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template
#
#  *** NOTE ***
#  If you customize the template file, make sure you keep an eye on the
#  original template file and merge any changes. New Phusion Passenger
#  features may require changes to the template file.
##############################################################

master_process on;
daemon on;
error_log '/home/deploy/RAILS/ecs_online/log/passenger.80.log' ;
pid '/home/deploy/RAILS/ecs_online/tmp/pids/passenger.80.pid';

worker_processes 1;
events {
    worker_connections 4096;
}

http {
    log_format debug '[$time_local] $msec  "$request" $status conn=$connection sent=$bytes_sent body_sent=$body_bytes_sent';
    include '/home/deploy/.gem/ruby/gems/passenger-5.0.26/resources/mime.types';
    passenger_root '/home/deploy/.gem/ruby/gems/passenger-5.0.26';
    passenger_abort_on_startup_error on;
    passenger_ctl cleanup_pidfiles L3RtcC9wYXNzZW5nZXItc3RhbmRhbG9uZS41eGYwNjUvdGVtcF9kaXJfdG91Y2hlci5waWQ=;
    passenger_ctl integration_mode standalone;
    passenger_ctl standalone_engine nginx;
    passenger_user_switching off;
    passenger_ruby /usr/bin/ruby;
    passenger_user myappuser;
    passenger_default_user myappuser;
    passenger_analytics_log_user myappuser;
    passenger_log_level 3;

    ### BEGIN your own configuration options ###
    # This is a good place to put your own config
    # options. Note that your options must not
    # conflict with the ones Passenger already sets.
    # Learn more at:
    # https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template

    ### END your own configuration options ###

    default_type application/octet-stream;
    types_hash_max_size 2048;
    server_names_hash_bucket_size 64;
    client_max_body_size 1024m;
    access_log off;
    keepalive_timeout 60;
    underscores_in_headers on;
    gzip on;
    gzip_comp_level 3;
    gzip_min_length 150;
    gzip_proxied any;
    gzip_types text/plain text/css text/json text/javascript
        application/javascript application/x-javascript application/json
        application/rss+xml application/vnd.ms-fontobject application/x-font-ttf
        application/xml font/opentype image/svg+xml text/xml;

    

    
    server {
        server_name _;
        listen 0.0.0.0:80;
        root '/home/deploy/RAILS/ecs_online/public';
        passenger_app_root '/home/deploy/RAILS/ecs_online';
        passenger_enabled on;
        passenger_app_env 'production';
        passenger_spawn_method 'smart';
        passenger_load_shell_envvars off;

        # Rails asset pipeline support.
        location ~ "^/assets/.+-([0-9a-f]{32}|[0-9a-f]{64})\..+" {
            error_page 490 = @static_asset;
            error_page 491 = @dynamic_request;
            recursive_error_pages on;
        
            if (-f $request_filename) {
                return 490;
            }
            if (!-f $request_filename) {
                return 491;
            }
        }
        location @static_asset {
            gzip_static on;
            expires max;
            add_header Cache-Control public;
            add_header ETag "";
        }
        location @dynamic_request {
            passenger_enabled on;
        }

        ### BEGIN your own configuration options ###
        # This is a good place to put your own config
        # options. Note that your options must not
        # conflict with the ones Passenger already sets.
        # Learn more at:
        # https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template

        ### END your own configuration options ###
    }
    passenger_pre_start http://0.0.0.0/;
    

    
}

**Comment by OnixGH** [comment]
Hi @garygriswold, you can use our [support forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger) for questions about your configuration.

In this case it looks like Nginx is complaining that you filled in a user called `myappuser` that doesn't appear to exist.

**Comment by pl086p** [comment]
garygriswold and OnixGH, 

According to the hint and instruction you both provided, I made changes on Passengerfile.json:
     change port from 80 to 1024
     change user to my system login account.
Then I re-start the passenger with garygriswold's Nginx configuration instruction:
    $ passenger start --nginx-config-template nginx.config,erb

The passenger is started successfully. Thank you both.
