### ISSUE TITLE
Odd chunked response issue with 5.0.23?

### ISSUE THREAD

**Issue by rchady** [phusion/passenger#1771]
I recently upgraded our application to 5.0.23 and am now seeing an error I am not sure how to even start troubleshooting:

```[ 2016-03-10 21:48:12.3311 1978/7fa3bcab8700 Ser/Server.h:936 ]: [Client 2-44] Disconnecting client with error: error parsing app response chunked encoding: Chunked encoding size string parse error```

Is there some way to track down what the string it is trying to parse is?

**Comment by FooBarWidget** [comment]
You can set the log level to 7. That way Passenger will log all data sent from the app to Passenger.

**Comment by rchady** [comment]
Something is really messed up for me here.  If I run this through rackup, it works fine.  If I run it through passenger standalone, it pukes out the above error.  If I run it through nginx+passenger, it results in the remote server returning a 500 error -- this is a bit of proxy code that grabs data from another site.  Any suggestions on where to even begin looking?  The added logs were not of much help.

I'm trying to wrap my head around why OLD versions work fine (like passenger-3 era?), but the exact same thing in passenger-5 results in this behavior.

**Comment by OnixGH** [comment]
We can't really help without concrete information, maybe you can describe what the exact request is you're trying, what the response should be and post the log file of that going wrong?

Maybe the app is sending out something illegal that wasn't checked for in the older Nginx and/or Passenger versions.

**Comment by rchady** [comment]
Silly me, not providing anything... you'd think I had never been on the other end...*facepalm*

So, running this in passenger standalone, this is what I'm seeing:

```[ 2016-03-11 12:47:57.6693 5568/7facbdf49700 age/Cor/Con/ForwardResponse.cpp:206 ]: [Client 2-1] Processing 165 bytes of application data: "<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US" class="background_margin_mustang index single-franchise focus-blue-white ddc"
[ 2016-03-11 12:47:57.6693 5568/7facbdf49700 Ser/HttpChunkedBodyParser.h:183 ]: [Client 1] ChunkedBodyParser: parsing new chunk
[ 2016-03-11 12:47:57.6694 5568/7facbdf49700 Ser/HttpChunkedBodyParser.h:127 ]: [Client 1] ChunkedBodyParser: setting error: Chunked encoding size string parse error
[ 2016-03-11 12:47:57.6694 5568/7facbdf49700 Ser/Server.h:936 ]: [Client 2-1] Disconnecting client with error: error parsing app response chunked encoding: Chunked encoding size string parse error```

I'm not familiar with handling chunked encoding so I'm a little blind at the moment.  What exactly is it erroring out on there?

**Comment by FooBarWidget** [comment]
It means that your app claims that the response body is chunked (via the `Transfer-Encoding: chunked` response body), yet it is not actually sending a chunked response body, and so Passenger bails out. You need to investigate the  code in your application that generates the response, which may be a library of Rack middleware.

Here's what Passenger expects from the app: https://en.wikipedia.org/wiki/Chunked_transfer_encoding

**Comment by OnixGH** [comment]
@FooBarWidget raced me to it, but chunking is pretty simple, basically blocks of <size>\r\n<data>\r\n like:
```
4\r\n
Test\r\n
```

**Comment by rchady** [comment]
Really stinks this results in a total error now when it did not before.  Wouldnt it make more sense to detect this case and generate a warning and then continue on like it used to?  It seems odd to me that an older version of passenger worked fine with this, but the latest and greatest now throws an error and stops working.

**Comment by OnixGH** [comment]
I'm not sure what version you came from, but 5.0.23 is not the latest version. Anyway, you cut away most of your logs so we still can't see what your app is actually sending. If that is invalid then I doubt it worked before, maybe it just silently failed.

**Comment by rchady** [comment]
It is indeed working as I had to roll back to the old version.  Is there any way to send this privately rather than in a public forum?  I can explain more and show you more information then.

**Comment by FooBarWidget** [comment]
You can email us at team@phusionpassenger.com. Anyway, as for working before and not now: I'm actually puzzled why it worked for you before at all. It shouldn't have worked before. Here's the situation from our side:

The [Rack specification](http://www.rubydoc.info/github/rack/rack/file/SPEC) does not state, when 'Transfer-Encoding: chunked' is set, whether response bodies generated by the application should already be chunked or not. But a case study of code in the wild shows that pretty much everything expects the answer of that question to be "yes". For example, when Rails generates a chunked response, returns response bodies including chunking headers. The only case that I've found where that's not true, is [JRuby-Rack](https://github.com/jruby/jruby-rack) prior to version 1.1.13 (from 2013). So it seems that the entire ecosystem agrees that when the app advertises "Transfer-Encoding: chunked", its body must actually be chunked, as opposed to expecting the app server to do that for you.

Indeed, other app servers such as Unicorn also expect this. For example, consider the following Rack example app:

~~~ruby
app = lambda do |env|
  [200, { "Transfer-Encoding" => "chunked" }, ["non-chunked body\n"]]
end

run app
~~~

This example app is wrong. It returns a non-chunked body, even though it says it is chunked. If I run this in Unicorn and make a request in CURL, CURL complains about it:

~~~
$ curl -v http://127.0.0.1:3000
> GET / HTTP/1.1
> User-Agent: curl/7.30.0
> Host: 127.0.0.1:3000
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 14 Mar 2016 14:46:53 GMT
< Connection: close
< Transfer-Encoding: chunked
<
* Problem (2) in the Chunked-Encoded data
* Closing connection 0
curl: (56) Problem (2) in the Chunked-Encoded data
~~~

**Comment by rchady** [comment]
Email sent in, will continue discussion there.

**Comment by OnixGH** [comment]
Further analysis revealed that the application was indeed setting the Transfer-Encoding header without ensuring the body was correctly chunked, which is subsequently correctly rejected by Passenger 5.
