### ISSUE TITLE
Nginx multiple vhost SSL setup with SNI not working, no log

### ISSUE THREAD

**Issue by serkandurusoy** [phusion/passenger#1772]
Hi,

I have a setup on Passenger 5.0.20 nginx integration mode, on an ubuntu server, (SNI enabled, OpenSSL libraries installed) where there are 3 sites, 1 acting as a catch-all and the other serving from two specific addresses. I need the 2 specific apps to serve https (and also possibly force https) but the following sites-enabled/default configuration does not work:

passenger_log_level 4;

server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;
    listen 443;
    server_name localhost;
    return 301 http://www.example.com$request_uri;
}

server {
    server_name www.example.com;
    root /home/example/meteor-apps/example-website

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
    }
}

server {
    server_name app1.example.com;
    ssl on;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
    add_header X-Frame-Options DENY;
    ssl_certificate /home/example/meteor-apps/ssl/app1.example.com.crt;
    ssl_certificate_key /home/example/meteor-apps/ssl/app1.example.com.key;
    add_header Strict-Transport-Security 'max-age=31536000';
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    keepalive_timeout 70;
    root /home/example/meteor-apps/app1-build/bundle/public;
    passenger_enabled on;
    passenger_sticky_sessions on;
    passenger_env_var TZ Europe/Istanbul;
    passenger_env_var PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
    passenger_app_env production;
    passenger_env_var NODE_ENV production;
    passenger_env_var MONGO_URL mongodb://localhost:27017/app1;
    passenger_env_var MONGO_OPLOG_URL mongodb://localhost:27017/local;
    passenger_env_var ROOT_URL https://app1.example.com;
    passenger_env_var MAIL_URL smtp://user:pass@smtp-relay.gmail.com:587;
    passenger_env_var METEOR_SETTINGS '{ "public": { "APP": "APP1" } }';
    passenger_env_var HTTP_FORWARDED_COUNT 1;
    passenger_app_type node;
    passenger_startup_file main.js;
}

server {
    server_name app2.example.com;
    ssl on;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
    add_header X-Frame-Options DENY;
    ssl_certificate /home/example/meteor-apps/ssl/app2.example.com.crt;
    ssl_certificate_key /home/example/meteor-apps/ssl/app2.example.com.key;
    add_header Strict-Transport-Security 'max-age=31536000';
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    keepalive_timeout 70;
    root /home/example/meteor-apps/app2-build/bundle/public;
    passenger_enabled on;
    passenger_sticky_sessions on;
    passenger_env_var TZ Europe/Istanbul;
    passenger_env_var PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
    passenger_app_env production;
    passenger_env_var NODE_ENV production;
    passenger_env_var MONGO_URL mongodb://localhost:27017/app2;
    passenger_env_var MONGO_OPLOG_URL mongodb://localhost:27017/local;
    passenger_env_var ROOT_URL https://app2.example.com;
    passenger_env_var MAIL_URL smtp://user:pass@smtp-relay.gmail.com:587;
    passenger_env_var METEOR_SETTINGS '{ "public": { "APP": "APP2" } }';
    passenger_env_var HTTP_FORWARDED_COUNT 1;
    passenger_app_type node;
    passenger_startup_file main.js;
}

where, visiting either one of app1.example.com or app2.example.com just waits endlessly. When I revert back to the original config without SSL, it works:

passenger_log_level 4;

server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;
    server_name localhost;
    return 301 http://www.example.com$request_uri;
}

server {
    server_name www.example.com;
    root /home/example/meteor-apps/example-website

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
    }
}

server {
    server_name app1.example.com;
    root /home/example/meteor-apps/app1-build/bundle/public;
    passenger_enabled on;
    passenger_sticky_sessions on;
    passenger_env_var TZ Europe/Istanbul;
    passenger_env_var PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
    passenger_app_env production;
    passenger_env_var NODE_ENV production;
    passenger_env_var MONGO_URL mongodb://localhost:27017/app1;
    passenger_env_var MONGO_OPLOG_URL mongodb://localhost:27017/local;
    passenger_env_var ROOT_URL http://app1.example.com;
    passenger_env_var MAIL_URL smtp://user:pass@smtp-relay.gmail.com:587;
    passenger_env_var METEOR_SETTINGS '{ "public": { "APP": "APP1" } }';
    passenger_env_var HTTP_FORWARDED_COUNT 1;
    passenger_app_type node;
    passenger_startup_file main.js;
}

server {
    server_name app2.example.com;
    root /home/example/meteor-apps/app2-build/bundle/public;
    passenger_enabled on;
    passenger_sticky_sessions on;
    passenger_env_var TZ Europe/Istanbul;
    passenger_env_var PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
    passenger_app_env production;
    passenger_env_var NODE_ENV production;
    passenger_env_var MONGO_URL mongodb://localhost:27017/app2;
    passenger_env_var MONGO_OPLOG_URL mongodb://localhost:27017/local;
    passenger_env_var ROOT_URL http://app2.example.com;
    passenger_env_var MAIL_URL smtp://user:pass@smtp-relay.gmail.com:587;
    passenger_env_var METEOR_SETTINGS '{ "public": { "APP": "APP2" } }';
    passenger_env_var HTTP_FORWARDED_COUNT 1;
    passenger_app_type node;
    passenger_startup_file main.js;
}

The logs show absolutely nothing. I know the SSL certificates are good because I used them on Meteor's native hosting platform Galaxy before deciding to migrate to a self-hosted setup.

I'd love any pointers.

Thanks.

**Comment by OnixGH** [comment]
Please use the [support forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger) for configuration questions.

At first I would set the log level to 7 to see if the request is arriving in Passenger at all, if not I'd suspect a problem in the Nginx config.

**Comment by serkandurusoy** [comment]
Oh, I posted it there now, thank you.
