### ISSUE TITLE
passenger_max_requests no longer supported in Standalone with nginx.config.erb?

### ISSUE THREAD

**Issue by nightsurge** [phusion/passenger#1773]
With the new changes to the config.erb, my app is now saying that "max_requests" is an invalid option when stopping/starting passenger standalone. How do I regain this functionality or what is the new proper way to modify the config to add back these custom options? I could not find any documentation on this.

`*** WARNING: Passengerfile.json: configuration key 'max_requests' is not supported`
I used to use an option like this in nginx.config.erb:
`<%= nginx_option :passenger_max_requests, :max_requests %>`
but I tried re-adding this to the new template copy and it keeps throwing the error above.

**Comment by OnixGH** [comment]
It's not that `max_requests` is not supported anymore in `Passengerfile.json`, it was [never supported](https://www.phusionpassenger.com/library/config/standalone/reference/) there. In 5.0.26 we added a warning for any options that Passenger doesn't recognize so for the first time you're alerted that you're trying to do something that doesn't work :).

But you're almost there. You can just write `passenger_max_requests <number>;` [in the template](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_max_requests) to use the functionality in standalone.

**Comment by nightsurge** [comment]
@OnixGH You are correct that `max_requests` was a custom alias I added which was just a reference to `passenger_max_requests` in the `nginx.config.erb`. Per my original post, this used to be fully supported in older versions of passenger.

However, with the recent changes to the `config.erb` file/template, and the lack of documentation available on how to customize `nginx.config.erb`, I was not sure how to include this option once again. I want to be able to set the option from `Passengerfile.json` like I've always been able to, seeing as that is much easier than having to edit the `nginx.config.erb` file. Is this still possible somehow on the newer versions of passenger? And if not, could you point me to documentation on HOW/WHERE to include this option in the new template `nginx.config.erb` file?

Thanks!

**Comment by OnixGH** [comment]
The warning just means that the Passenger parser does not recognize the option and doesn't have any (default) facilities to project the option to a known one. In the majority of cases it will be some typo that needs to be fixed.

But just because the warning is there doesn't mean that your passthrough doesn't work anymore, did you check the actual composed template (`passenger start --debug-nginx-config`)?.

The passthrough is not officially supported (thus no documentation) but in your case I would think it still works and you can safely ignore the warning.

**Comment by nightsurge** [comment]
@OnixGH I do believe that the setting still works based on how I've implemented it. After posting this issue, I did confirm that my server processes are clearing up at the expected timeframes. I was just concerned that I was not implementing them properly in the new `nginx.config.erb` file but apparently it is still working.

**Comment by OnixGH** [comment]
There's no need to assume anything, just execute what I said (`passenger start --debug-nginx-config`) and you can see immediately whether passenger_max_requests is there or not.
