### ISSUE TITLE
5.0.26 not building native support so but 5.0.25 did

### ISSUE THREAD

**Issue by wlipa** [phusion/passenger#1778]
After upgrading passenger to 5.0.26, I am seeing errors from passenger about building the native support so file.

    App 14490 stdout:
    App 14490 stderr:  [passenger_native_support.so] trying to compile for the current user (ops) and Ruby interpreter...
    App 14490 stderr:
    App 14490 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
    App 14490 stderr:
    App 14490 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
    App 14490 stderr:
    App 14490 stderr:      /tmp/passenger_native_support-9k2168.log
    App 14490 stderr:
    App 14490 stderr:  [passenger_native_support.so] not downloading because passenger wasn't installed from a release package
    App 14490 stderr:
    App 14490 stderr:  [passenger_native_support.so] will not be used (can't compile or download)
    App 14490 stderr:
    App 14490 stderr:   --> Passenger will still operate normally.
    App 14490 stderr:

I'm not sure why it says that "passenger wasn't installed from a release package" because we are using the passenger PPA with ubuntu 12.04 LTS and 14.04 LTS, in conjunction with ruby 2.2 from the bright box PPA for ruby.

In the /tmp file log, the error looks like:

    # current user is: ops
    # mkdir -p /usr/lib/buildout/ruby/ruby-2.2.4-x86_64-linux
    Encountered permission error, trying a different directory...
    -------------------------------
    # mkdir -p /home/ops/.passenger/native_support/5.0.26/ruby-2.2.4-x86_64-linux
    # cd /home/ops/.passenger/native_support/5.0.26/ruby-2.2.4-x86_64-linux
    # /usr/bin/ruby2.2 /usr/lib/src/ruby_native_extension/extconf.rb
    /usr/bin/ruby2.2: No such file or directory -- /usr/lib/src/ruby_native_extension/extconf.rb (LoadError)

A working log file from 5.0.25 looks like:

    # current user is: ops
    # mkdir -p /home/ops/.passenger/native_support/5.0.25/ruby-2.2.4-x86_64-linux
    # cd /home/ops/.passenger/native_support/5.0.25/ruby-2.2.4-x86_64-linux
    # /usr/bin/ruby2.2 /usr/share/passenger/ruby_extension_source/extconf.rb
    checking for alloca.h... yes
    checking for ruby/version.h... yes
    checking for ruby/io.h... yes
    checking for ruby/thread.h... yes
    checking for ruby_version... no
    checking for rb_thread_io_blocking_region() in ruby/io.h... yes
    checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
    creating Makefile
    # make
    compiling /usr/share/passenger/ruby_extension_source/passenger_native_support.c
    linking shared-object passenger_native_support.so

On these machines there is no /usr/lib/src at all.  5.0.26 is trying to look in there, but 5.0.25 didn't.  The ruby2.2-dev package is installed.

I tried to look at the diff from 5.0.25 to .26 but github wouldn't generate the full diff because it was too large.

**Comment by OnixGH** [comment]
Thanks. We're [aware of this one](https://github.com/phusion/passenger/issues/1763) and were planning to fix it in 5.0.27.

In short, `ruby_native_extension` isn't the correct folder, but as a temporary fix to get the compilation going you could just copy the necessary files there anyway, e.g.:
`cp -dpR /usr/share/passenger-enterprise/ruby_extension_source /usr/lib/src/ruby_native_extension`

**Comment by FooBarWidget** [comment]
@wlipa Could you help me by providing more information? I'm having trouble reproducing this problem.

Are you on Ubuntu 12.04 LTS or 14.04?

You said you used the "Passenger PPA". What is its URL?

Could you tell me what you see if you run this?

~~~
passenger-config --root
cat $(passenger-config --root)
~~~

**Comment by wlipa** [comment]
The same problem happens on both Ubuntu 12.04 LTS and 14.04.

The line I'm using to load the sources is:

    deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main

Here's the output you requested:

    $ passenger-config --root
    /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini

    $ cat $(passenger-config --root)
    [locations]
    packaging_method=deb
    bin_dir=/usr/bin
    support_binaries_dir=/usr/lib/passenger/support-binaries
    lib_dir=/usr/lib/passenger
    helper_scripts_dir=/usr/share/passenger/helper-scripts
    resources_dir=/usr/share/passenger
    include_dir=/usr/share/passenger/include
    doc_dir=/usr/share/doc/passenger
    ruby_libdir=/usr/lib/ruby/vendor_ruby
    node_libdir=/usr/share/passenger/node
    apache2_module_path=/usr/lib/apache2/modules/mod_passenger.so
    ruby_extension_source_dir=/usr/share/passenger/ruby_extension_source
    nginx_module_source_dir=/usr/share/passenger/ngx_http_passenger_module

**Comment by FooBarWidget** [comment]
@wlipa Which integration mode are you using? Apache, Nginx or Standalone?

**Comment by FooBarWidget** [comment]
Never mind, I've been able to find the cause of the issue. :)
