### ISSUE TITLE
Passenger compiled with Xcode 7.3.0 crashes (BackgroundIOCapturer::capture() + 180 in trace)

### ISSUE THREAD

**Issue by sesam** [phusion/passenger#1780]
## Issue report
On a Macbook Pro, after updating Xcode to 7.3 and OS X to 10.11.4, newly compiled passenger fails to start with bad_alloc malloc error. More exactly; passenger standalone starts and runs seemingly normally _once_, but after that neither standalone nor the apache module can be started. 

Expected: can install and start and restart passenger as is normal 
Actual: SIGSEGV malloc bad_alloc
Crashlog: http://pastebin.com/mW1bEC8A

Repro: Install passenger on OS X 10.11.4 with Xcode 7.3 (and same problem appears with gcc-5.3.0 from homebrew), start and stop or otherwise restart passenger. It fails with malloc error.

**Passenger version and integration mode**:
  open source 5.0.26, reproducible both standalone and apache module

Mac OX S 10.11.4 x86_64

**Question 4: Passenger installation method**:
Your answer:

- [X] RubyGems + Gemfile
- [ ] RubyGems, no Gemfile
- [ ] OS X Homebrew <-- WORKAROUND FOUND :) Using Homebrew to get precompiled binaries, most works (just need to get log outputs again)
- [ ] source tarball

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
rvm rubies
=* ruby-2.2.3 [ x86_64 ]   and .ruby-version also says 2.2.3

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
Problem started occurring after updating OS X + Xcode. Rebooting, fiddling with Xcode, googling found no hints, other than some people having passenger malloc problems many months ago.

**Comment by OnixGH** [comment]
According to your crashlog you have built passenger with ruby 2.2.4, not 2.2.3?
` /Users/shuttle/.rvm/gems/ruby-2.2.4/gems/passenger-5.0.26/buildout/support-binaries/PassengerAgent`

**Comment by shuttle842** [comment]
Hi,
we tried first with 2.2.3 and then with 2.2.4. Results were the same

**Comment by OnixGH** [comment]
Ok, so @shuttle842 and @sesam, you're working together on this? And you're not associated to [this forum report](https://groups.google.com/forum/#!topic/phusion-passenger/scZHVn73fzc)?

**Comment by shuttle842** [comment]
Yes, we are working together and we are not associated to mentioned report.

**Comment by Coeur** [comment]
@OnixGH I did the linked forum report. Should I open a new issue on the tracker?

**Comment by OnixGH** [comment]
@Coeur that's not needed at this moment, let's continue here until we know whether it's a separate issue or not.

**Comment by Coeur** [comment]
Because the bug is related to Xcode 7.3, here is my current workaround:
1) install Xcode 7.2 under a different name, like Xcode72.app
2) temporary select Xcode 7.2: `sudo xcode-select -switch /Applications/Xcode72.app/Contents/Developer`
3) reinstall Passenger and Nginx: `gem uninstall passenger` + `gem install passenger` + `passenger-install-nginx-module`
4) switch back to Xcode 7.3: `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`

For me, it works :D

**Comment by sesam** [comment]
[image: Mic Drop]
Nice workaround :)

**Comment by OnixGH** [comment]
We've reproduced this on our own OSX test system. We can also confirm that compiling with the latest 7.2.1 can be used as a workaround (you can download 7.2.1 [here](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_7.2.1/Xcode_7.2.1.dmg)).

As far as we can tell, `system_calls.cpp` throws a `boost::thread_interrupted()`, but the `try { } catch (..)` we have in place appears to be bypassed or ignored somehow in the 7.3-compiled version.

**Comment by Coeur** [comment]
Apple released Xcode 7.3.1, but I have no time to test it: https://developer.apple.com/xcode/download/
Can someone check if the issue is affecting 7.3.1?

**Comment by OnixGH** [comment]
We just tested Passenger (5.0.26 as well as 5.0.27) built with XCode 7.3.1 GM, and it doesn't crash with this error anymore!
