### ISSUE TITLE
Disconnecting long-running connections for process #####

### ISSUE THREAD

**Issue by rchady** [phusion/passenger#1781]
Please follow the steps below if you have found an **issue with Passenger**, or would like to request a feature.

Post to the [support forum](http://groups.google.com/group/phusion-passenger) instead if you are not sure, or have a question about your configuration.

---

## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Are you sure this is a bug in Passenger?**
Please read our troubleshooting and debugging guides first:
https://www.phusionpassenger.com/library/admin/troubleshooting/
https://www.phusionpassenger.com/library/admin/

**Question 1: What is the problem?**

Passenger is logging 'Disconnecting long-running connections for process ####' messages, even though passenger_pool_idle_time is set to 0.

- What is the expected behavior?

On servers with passenger_pool_idle_time set to 0, passenger will not fill up the logs with these messages.

- What is the actual behavior?

My logs are getting filled with these messages, even though passenger_pool_idle_time is set to 0.

- How can we reproduce it? The easier you make it for us to reproduce the issue, the better we can help you.

Be as detailed as possible, describe the context, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what it is and how it would help you)

Your answer:

I just have a simple application being served by passenger/nginx with the configuration setting passenger_pool_idle_time 0;

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:

Open source 5.0.23/nginx

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:

Debian 8, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:

Ruby 2.1.5

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:

Nope.

**Question 7: Anything else about your setup that we should know?**

Your answer:

Nope, pretty basic.  I found another issue on this topic and it also said to set passenger_pool_idle_time to 0, but it is not working for me.  

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by OnixGH** [comment]
Sorry, I can't reproduce this with your information. The `passenger_pool_idle_time 0` keeps processes alive for me in 5.0.23, so it is probably an issue with your configuration.

You can use the support forum for further help with that.

**Comment by rchady** [comment]
Before you close this, here is my entire http {} block from my configuration.  Nothing fancy.

```http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        server_tokens off;

        server_names_hash_bucket_size 64;
        server_names_hash_max_size 512;

        # Logging
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        add_header X-Clacks-Overhead "GNU Terry Pratchett";

        large_client_header_buffers 4 32k;
        log_format  proxy  '{'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"scheme":"$scheme",'
        '"host":"$host",'
        '"uri":"$request_uri",'
        '"status":"$status",'
        '"size":"$body_bytes_sent",'
        '"referer":"$http_referer",'
        '"forwarded_for":"$http_x_forwarded_for",'
        '"request_time":"$request_time"'
          '}';
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        types_hash_max_size 2048;
        gzip_http_version 1.1;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml;
        gzip_buffers 16 8k;
        gzip_disable "msie6";

        client_max_body_size 250M;

        # Configuration options for Phusion Passenger
        passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
        passenger_ruby /usr/bin/ruby;

        passenger_max_pool_size 75;
        passenger_pool_idle_time 0;

        passenger_buffers 8 16k;
        passenger_buffer_size 32k;

        # Virtual Hosts Configs
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}```

Is there any chance that one of the other settings conflicts with this?

**Comment by adler99** [comment]
same thing here:
age/Cor/CoreMain.cpp:907 ]: Checking whether to disconnect long-running connections for process 8740, application XXXX

Setup: Rails, Apache/2.4.18 (Ubuntu), Phusion_Passenger/5.1.2
