### ISSUE TITLE
Disable passenger_friendly_error_pages unless development

### ISSUE THREAD

**Issue by shaicoleman** [phusion/passenger#1782]
passenger_friendly_error_pages can leak sensitive environment variables (e.g. application secrets, database passwords, etc.).

By default passenger_friendly_error_pages will be enabled in all environments except "staging" and "production".
https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_friendly_error_pages

A blacklist approach is inherently insecure. Other environments, e.g. "beta", "demo", "rollout", etc. would have such secrets exposed.

Instead a whitelist approach would be better, and only whitelist the "development" environment by default.

Passenger 5.0.23/nginx on Ubuntu 14.04 64 bit

**Comment by shaicoleman** [comment]
Thanks!

Don't forget to update the docs to reflect this change

**Comment by OnixGH** [comment]
They're already updated, or did you still find something?

**Comment by shaicoleman** [comment]
Yes, it is updated, thanks
