### ISSUE TITLE
Unable to forward traffic from http to https with passenger 5.0.27

### ISSUE THREAD

**Issue by 34code** [phusion/passenger#1791]
---

## Issue report

I was previously able to forward traffic from one port in localhost to another using an nginx conf

**Are you sure this is a bug in Passenger?**
Yes

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
- forwarding http traffic one one port to https traffic on another port should work
- What is the actual behavior?
- only https traffic works

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.27 standalone;

Your answer: open source 5.0.27 standalone;

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Mac OSX El Capitan

Your answer: Mac OSX El Capitan

**Question 4: Passenger installation method**:

Your answer:
[*] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.2.3, RVM, Rails 4.2.6; 

Your answer: Ruby 2.2.3, RVM, Rails 4.2.6; 

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-nope

Your answer: Docker official passenger -- but this is happening on dev env locally

**Question 7: Anything else about your setup that we should know?**

Your answer:

using a custom nginx conf file and starting app like this:

```rake assets:precompile RAILS_ENV=development; passenger start -e development -b 0.0.0.0 -p 7000 --ssl --ssl-certificate ./certs/cert.pem --ssl-certificate-key ./certs/cert.key --nginx-config-template ./nginx.conf.erb'```

relevant `nginx.conf.erb` stuff below:

# Port Mover
    server {
        listen   9000;
        server_name  localhost;
        rewrite ^(.*) https://$host$1 permanent;

        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Proto https;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_hide_header X-Powered-By;
          proxy_hide_header X-Runtime; 
          
          add_header Strict-Transport-Security "max-age=31536000";
        }
    }

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by OnixGH** [comment]
Can you please answer all the questions so we don't have to guess at what you're doing/using? 

Also, which version did it work on?

**Comment by 34code** [comment]
hi @OnixGH sorry i filled out the details by overwriting the "for example" parts instead of putting it under "your answer" ..

Any way this is a false positive -- which occurred due to improper shutdown (not graceful) on passenger 5.0.26 -- so upon upgrading to 5.0.27 , passenger hadn't properly fully shutdown and this was causing problems. please close ticket unless you want to solve graceful shutdown issues post 5.0.26..

**Comment by OnixGH** [comment]
Aha, I see. Yeah, the current way for Github to do this entry questionnaire is kind of awkward unfortunately (though better for us than nothing).

What do you mean by improper shutdown? The only issue we're aware of at this point related to shutdown is https://github.com/phusion/passenger/issues/1678. If you're getting any other problems with shutdown we're certainly interested in info on what you did, what happened vs. expected etc. in a new issue report. Or did it only happen because in combination with the upgrade?

I'll close this one since it was a false positive.

**Comment by 34code** [comment]
I don't actually remember why the shutdown occurred but i will definitely try to provide more detail in a separate issue if it happens again.
