### ISSUE TITLE
Passenger 5.0.22 Enterprise/Apache assertion error + crash-watch GDB issues

### ISSUE THREAD

**Issue by MasonM** [phusion/passenger#1799]
**Question 1: What is the problem?**

On 2016/04/08 at about 1:58AM, one of our webservers become unresponsive. When this was investigated at 8:18AM, it was found that there was a gdb process attached to a Passenger process that was taking up 100% of the CPU, and had been running approximately since the downtime. When Apache was restarted, the issue was resolved.

Looking at the Apache error logs, we found that Passenger hit an assertion error (`(Expected request->httpState to be 9, got 2)`), which then launched crash-watch, which launched gdb. Here's the relevant excerpt from /var/log/httpd/error_log: https://gist.github.com/MasonM/ab584aa03a2a6904edc06a9fc76a0cbc
(note that this contains everything in the /var/tmp/passenger-crash-log.1460094937 crash dump log it references)

This is the first issue we've run into with Passenger in over a year, and it hasn't cropped up again yet. I've added `SetEnv PASSENGER_DUMP_WITH_CRASH_WATCH false` to our Apache config just in case. 

**Question 2: Passenger version and integration mode**:
Your answer: Passenger 5.0.22 Enterprise/Apache 2.4.16

**Question 3: OS or Linux distro, platform (including version)**:
Your answer: CentOS 6.6 Final, Linux 4.1.5-x86_64-linode61

**Question 4: Passenger installation method**:
Your answer: RubyGems with the official passenger-enterprise-server-5.0.22 gem.

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer: Ruby 2.2.2, Rails 4.1.142, Rbenv 0.4.0-151

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer: No, just a VPS.

**Question 7: Anything else about your setup that we should know?**
Your answer: /usr/bin/gdb has version 7.2-75.el6

**Comment by OnixGH** [comment]
Thanks for the report. Do the 300 MB memory-limit-shutdowns happen a lot on the server? Could you let us know if this starts occuring more than just this once? 

If it does happen again it would be interesting to know whether the core still goes to 100% CPU if GDB is not trying to attach (as well as the log of what happened leading up to the crash).

**Comment by OnixGH** [comment]
And just to make sure;  /var/tmp/ doesn't contain any other passenger-crash-log files (or other traces of  "crash" in your logfiles)?

**Comment by MasonM** [comment]
> Do the 300 MB memory-limit-shutdowns happen a lot on the server?

Unfortunately, yes. Our Rails app has a memory leak that we've having trouble tracking down. On average, a process hits the limit every few minutes.

> Could you let us know if this starts occuring more than just this once? 

Will do. Haven't have any other problems so far, so feel free to close this.

> And just to make sure; /var/tmp/ doesn't contain any other passenger-crash-log files

Nope, there's just `/var/tmp/passenger-crash-log.1460094937 `, which is duped in the Apache error log.

Also, here's a screenshot from Newrelic of the processes running around the time of the crash, in case that helps (it says GDB takes 16.7% because the server has 6 cores, and it was using 100% of one):

![web_node4_04082016_crash](https://cloud.githubusercontent.com/assets/651224/14642097/27cab328-0617-11e6-87f9-ba2ef0e4cf3c.png)

**Comment by CamJN** [comment]
Has this recurred yet?

**Comment by MasonM** [comment]
I've moved jobs since this bug was filed, so I'm afraid I don't know. @shawnpyle, could you answer this?

**Comment by shawnpyle** [comment]
@MasonM & @CamJN, no, to my knowledge, it hasn't happened since. I suspect setting `PASSENGER_DUMP_WITH_CRASH_WATCH` to `false`, as @MasonM mentioned in the first post, also would have prevented any other occurrence.

**Comment by MasonM** [comment]
okay, I'll close this then @shawnpyle
