### ISSUE TITLE
Unable to install Passenger and Nginx on Red Hat 7 

### ISSUE THREAD

**Issue by sleepingstu** [phusion/passenger#1800]
Am following the instructions found [here](https://www.phusionpassenger.com/library/install/nginx/install/oss/el7/) to install Passenger and Nginx on Red Hat 7 but am getting the following error when trying to do the install.

```sh
yum install -y nginx passenger
Loaded plugins: rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
passenger/7Server/x86_64/signature                                                                                                                                                 |  836 B  00:00:00
passenger/7Server/x86_64/signature                                                                                                                                                 | 1.0 kB  00:00:00 !!!
passenger-source/7Server/signature                                                                                                                                                 |  836 B  00:00:00
passenger-source/7Server/signature                                                                                                                                                 | 1.0 kB  00:00:00 !!!
Package 1:nginx-1.8.1-8.p5.0.27.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package passenger.x86_64 0:5.0.27-8.el7 will be installed
--> Processing Dependency: rubygem(rake) for package: passenger-5.0.27-8.el7.x86_64
--> Processing Dependency: rubygem(rack) for package: passenger-5.0.27-8.el7.x86_64
--> Finished Dependency Resolution
Error: Package: passenger-5.0.27-8.el7.x86_64 (passenger)
           Requires: rubygem(rake)
Error: Package: passenger-5.0.27-8.el7.x86_64 (passenger)
           Requires: rubygem(rack)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

The server I'm trying to install this on is pretty much a fresh install of Red Hat 7, so it is more than likely a dependencies issue but I'm not able to find any info on the problem so hoping someone can help.

**Comment by OnixGH** [comment]
This looks like an issue with EPEL. We found this note on the [EPEL site](https://fedoraproject.org/wiki/EPEL): 

"You need to also enable the 'optional' repository to use EPEL packages as they depend on packages in that repository. This can be done by enabling the RHEL optional subchannel for RHN-Classic. For certificate-based subscriptions see Red Hat Subscription Management Guide. For EPEL 7, in addition to the 'optional' repository (rhel-7-server-optional-rpms), you also need to enable the 'extras' repository (rhel-7-server-extras-rpms)."

This should solve your problem. I added a [report](https://github.com/phusion/passenger_library/issues/45) to add these instructions to the Passenger Library.

**Comment by OnixGH** [comment]
FYI: our documentation (the URL you referred to) has been updated with the necessary commands.

**Comment by sleepingstu** [comment]
That did the trick! Many thanks, that was a big help.

**Comment by robwold** [comment]
I've had this same problem.  The tricky thing for me is that I'm using RHEL on an Amazon ec2 instance, so I can't use the given commands because I don't have a RHEL username or password. There seems to be a partial workaround based on a dedicated repo for amazon RHEL users (described [here](https://forums.aws.amazon.com/thread.jspa?messageID=551601) ) but running 
` yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
sudo yum install -y mod_passenger || sudo yum-config-manager --enable cr && sudo yum install -y mod_passenger`
produced this error:
`Error: Package: passenger-5.2.1-1.el7.x86_64 (passenger)
           Requires: rubygem(rack)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest`

**Comment by CamJN** [comment]
Perhaps you need to replace REGION with your aws region code?

**Comment by robwold** [comment]
I thought that too, but `sudo yum repolist all` lists repos with REGION explicitly in the name ?

**Comment by cku-github** [comment]
I had the same issue with rhel7.5 and using the newer passenger-5.2.3 version.
Running the command
sudo yum install -y nginx passenger || sudo yum-config-manager --enable cr && sudo yum install -y nginx passenger
the log threw the following error:
Error: Package: passenger-5.2.3-1.el7.x86_64 (passenger)
Requires: rubygem(rack)
manually installing ruby and rubygems-rake didn't help.
It worked after I manually installed epel:
sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

possibly my earlier rubygems-rake install also helped then.

**Comment by FooBarWidget** [comment]
@cku-github Itr's rubygems-rack not rubygems-rake.

**Comment by cku-github** [comment]
Thanks for the correction. Had my rake(s) and rack(s) mixed.

**Comment by terryjray** [comment]
I also ran into this on a RHEL 7.5 EC2 instance. I attempted to run the steps described above and here: [https://fedoraproject.org/wiki/EPEL](url)

I then attempted to re-run the commands outlined here beginning with Step 2: [https://www.phusionpassenger.com/library/install/nginx/install/oss/el7/](url)

I still got the same result.

`Error: Package: passenger-5.3.3-1.el7.x86_64 (passenger)`
`           Requires: rubygem(rake)`

FYI, gem is installed at /usr/bin/gem.

Anyone find an alternate solution that's working?

**Comment by terryjray** [comment]
As a follow up, I also tried what @robwold suggested above except prefixed with sudo, so:

`sudo yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional sudo yum install -y mod_passenger || sudo yum-config-manager --enable cr && sudo yum install -y mod_passenger`

In my case, this worked and passenger was installed as expected. All the files referenced in the /etc/nginx/conf.d/passenger.conf file were in the locations expected.

**Comment by jeff1evesque** [comment]
@terryjray, your suggestion also seems to fix my problems. Thank you very much for posting this.
