### ISSUE TITLE
Passenger Enterprise V5.0.22 was crashing when launching in standalone mode.

### ISSUE THREAD

**Issue by sebastienliu** [phusion/passenger#1802]
We are using Passenger Enterprise 5.0.22 on Ubuntu 14.04 with Ruby 2.2.2.

The step to install Nginx was like that:

RUN bin/bundle exec passenger-config install-standalone-runtime --force
 ---> Running in 0a84a57af34e
Downloading a Phusion Passenger agent binary for your platform

Copying agent-x86_64-linux.tar.gz from /usr/local/bundle/gems/passenger-enterprise-server-5.0.22/download_cache...
Download OK!
Extracting precompiled agent binary to /usr/local/bundle/gems/passenger-enterprise-server-5.0.22/buildout/support-binaries...
Checking whether the downloaded binary is usable...
The downloaded binary is usable.
Agent binary successfully download and installed.

Downloading an Nginx 1.8.0 engine for your platform

Copying nginx-1.8.0-x86_64-linux.tar.gz from /usr/local/bundle/gems/passenger-enterprise-server-5.0.22/download_cache...
Download OK!
Extracting precompiled Nginx 1.8.0 engine to /usr/local/bundle/gems/passenger-enterprise-server-5.0.22/buildout/support-binaries
Checking whether the downloaded engine is usable...
The downloaded engine is usable.
Nginx 1.8.0 engine successfully download and installed.

But when I launched 'passenger start', I got the following errors:

 --> passenger_native_support.so successfully loaded.
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: [emerg] unexpected ";" in nginx.conf:80
    nginx: configuration file nginx.conf test failed

This probably means that you have found a bug in Phusion Passenger Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues

In the bug report, please include this error message, as well as the contents of the file /tmp/passenger-standalone-1f16bie.log

**Comment by OnixGH** [comment]
Known issue with the standalone template that was already fixed. Please upgrade Passenger.
