### ISSUE TITLE
running rvmsudo

### ISSUE THREAD

**Issue by pearlygurlee** [phusion/passenger#1803]
To Whom It Concerns,
I am running the following tutorial: https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/apache/oss/install_language_runtime.html#heads-up-sudo-vs-rvmsudo
I am trying to figure out how i completed a certain part of this recently as I am doing a college report on it. At the Heads-up: sudo vs rvmsudo section of this page it gives a link to the rvm site about changing sudo to rvmsudo: https://rvm.io/integration/sudo however this information was of no use to me. I know I was either able to find a link on the phusionpassenger site of the rvm site with steps on how to change from sudo to rvmsudo and for the life of me i can't find it. Can anyone possibly direct me to a link on one of these sites with steps on how to do this. I've checked for hours. please advise. bare in mind im a student so im new to this. Kindest regards, 
Jen.

**Comment by FooBarWidget** [comment]
When the document says "changing sudo to rvmsudo", it really means "**type** sudo instead of rvmsudo". It doesn't mean that you need to change some config option.

So when you read instructions like this...

    sudo bundle install

...and you are also using RVM, then you are expected to type this instead:

    rvmsudo bundle install
