### ISSUE TITLE
1x PassengerPreStart no error but no prespawn, 2x PassengerPreStart gives error (still no prespawn(s))

### ISSUE THREAD

**Issue by viewty** [phusion/passenger#1811]
I'm having a problem with PassengerPreStart not working in either combination. 

**Server details:**
Centos 7, Passenger 5.0.28, Apache 2.4.6
Passenger installed with yum. It is working (passenger-status shows expected output when used) ok, both sites work fine.

First, a single vhost and 1 PassengerPreStart use:

**vhost.conf:**
```
<VirtualHost 172.16.198.57:80>
  ServerName operations.example.co
  DocumentRoot /home/redmine/app/public
  <Directory /home/redmine/app/public>
    AllowOverride all
    Options -MultiViews
    Require all granted
  </Directory>

  PassengerFriendlyErrorPages on
  PassengerBaseURI /home/redmine/app/public
  PassengerMinInstances 1
</VirtualHost>
PassengerPreStart http://operations.example.co/
```

I start apache, all starts ok, no errors. Passenger is started.

`passenger-status` shows 0 app groups, 0 processes.

I then go to 172.16.198.57, wait 20 seconds, the page loads.

`passenger-status` shows 1 app group, 1 process for /home/redmine/app.

So no error but it didn't seem to work.

I then added a second vhost:

```
<VirtualHost 172.16.198.57:82>
  ServerName operations.example.co
  DocumentRoot /home/tracks/app/public
  <Directory /home/tracks/app/public>
    AllowOverride all
    Options -MultiViews
    Require all granted
  </Directory>

  PassengerFriendlyErrorPages on
  PassengerBaseURI /home/tracks/app/public
  PassengerMinInstances 1
</VirtualHost>
PassengerPreStart http://operations.example.co:82/
```

Now when I restart httpd, error log shows:

```
/usr/share/passenger/helper-scripts/prespawn:131:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /usr/share/passenger/helper-scripts/prespawn:131:in `new'
	from /usr/share/passenger/helper-scripts/prespawn:131:in `rescue in connect'
	from /usr/share/passenger/helper-scripts/prespawn:129:in `connect'
	from /usr/share/passenger/helper-scripts/prespawn:89:in `socket'
	from /usr/share/passenger/helper-scripts/prespawn:108:in `head_request'
	from /usr/share/passenger/helper-scripts/prespawn:171:in `<main>'
```

Both scenarios produce the same results regardless of adding `127.0.0.1 operations.example.co` to **/etc/hosts** or not (no idea if that's relevant, but thought I should try!).

Any suggestions / ideas please? Hope I've included all the relevant information, sorry if I missed anything.

**Comment by OnixGH** [comment]
Please post to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for help with your configuration. In this case I would suggest prestarting the same way you load the page, with 172.16.198.57 not localhost.

**Comment by viewty** [comment]
Ok I'll copy to the support forum but thought it might warrant being here as if I do as you suggested I get the same result (single entry no error no spawn, 2 entries same error, no spawn).

**Comment by OnixGH** [comment]
In most cases the configuration is the problem rather than a Passenger issue. You also didn't fill out the new issue report form with all the details that help show it's a Passenger issue (and us to reproduce it) rather than just a simple misconfiguration.
