### ISSUE TITLE
passenger-status -v --show=xml outputting non-machine readable output

### ISSUE THREAD

**Issue by sparrc** [phusion/passenger#1816]
## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Question 1: What is the problem?**
- What is the expected behavior?

`passenger-status -v --show=xml` should produce machine-readable output. 

- What is the actual behavior?

if the system doesn't have `xmllint` installed, it will output this at the end of the output:

```
</server_socket></server_sockets></process></processes></group></groups></info> *** Tip: if you install the 'xmllint' command then the XML output will be indented.
```

which is not valid xml.

**Question 2: Passenger version and integration mode**:
Your answer: any? not sure

**Question 3: OS or Linux distro, platform (including version)**:
Your answer: Debian Squeeze LTS

**Question 4: Passenger installation method**:
Your answer: unsure

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer: Go

**Comment by OnixGH** [comment]
The tip is output via STDERR, whereas the xml output is sent to STDOUT.

Thus, if you read only from STDOUT you always get machine-readable output. For example, you can hide the tip with `passenger-status --show=xml 2>/dev/null`
