### ISSUE TITLE
Installation fails with EasyApache4

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger#1820]
After upgrading to EasyApache4, `passenger-install-apache2` no longer works. The first error it reports is:
```
cannot open /usr/local/apache/build/config_vars.mk: No such file or directory at /usr/bin/apxs line 203.
```

Eventually it recommends installing apache2, but that doesn't help because it is already installed (just not found).

**Comment by OnixGH** [comment]
We support the official CentOS package, which works, and we don't have control over EasyApache4. If anyone finds a workaround we can see if we can incorporate it somehow, but the issue is closed / can't fix for now.

**Comment by stwf** [comment]
Posting here for completeness. This solved the problem for me.

yum remove httpd-tools
yum install ea-apache24-devel
