### ISSUE TITLE
EasyApache 3: mod_passenger crashes at start

### ISSUE THREAD

**Issue by oshchukin** [phusion/passenger#1821]
EasyApache + mod_passenger crashes at Apache start -

```
Program received signal SIGABRT, Aborted.
0x00007ffff5ea55f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install expat-2.1.0-8.el7.x86_64 glibc-2.17-106.el7_2.6.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libcom_err-1.42.9-7.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libidn-1.28-4.el7.x86_64 liblve-1.4-1.3.el7.cloudlinux.x86_64 libselinux-2.2.2-6.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 libuuid-2.23.2-26.el7_2.2.x86_64 nss-softokn-freebl-3.16.2.3-14.2.el7_2.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00007ffff5ea55f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff5ea6ce8 in abort () from /lib64/libc.so.6
#2  0x00007ffff5ee5327 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff5eed053 in _int_free () from /lib64/libc.so.6
#4  0x00007ffff2690802 in boost::checked_array_delete<char> (x=0x3552b90 "\022\025VariantMap")
    at src/cxx_supportlib/vendor-modified/boost/core/checked_delete.hpp:41
#5  0x00007ffff268eb45 in boost::scoped_array<char>::~scoped_array (this=0x7fffffffc200, __in_chrg=<optimized out>)
    at src/cxx_supportlib/vendor-modified/boost/smart_ptr/scoped_array.hpp:69
#6  0x00007ffff268eaec in Passenger::writeArrayMessageEx<std::vector<std::string, std::allocator<std::string> > > (fd=3140,
    args=std::vector of length 51, capacity 51 = {...}, timeout=0x0) at src/cxx_supportlib/Utils/MessageIO.h:458
#7  0x00007ffff267e97a in Passenger::writeArrayMessage (fd=3140, args=std::vector of length 51, capacity 51 = {...}, timeout=0x0)
    at src/cxx_supportlib/Utils/MessageIO.h:468
#8  0x00007ffff267f783 in Passenger::VariantMap::writeToFd (this=0x7fffffffc3e0, fd=3140, messageName=...) at src/cxx_supportlib/Utils/VariantMap.h:455
#9  0x00007ffff2685c89 in Passenger::WatchdogLauncher::start(std::string const&, Passenger::VariantMap const&, boost::function<void ()> const&) (
    this=0x3550cc0, passengerRoot="/opt/passenger", extraParams=..., afterFork=...) at src/cxx_supportlib/WatchdogLauncher.h:450
#10 0x00007ffff268cbbe in Hooks::Hooks (this=0x3550c70, pconf=0x78f138, plog=0x7cccb8, ptemp=0x7d0cd8, s=0x7cee60) at src/apache2_module/Hooks.cpp:1345
#11 0x00007ffff267c0f2 in init_module (pconf=0x78f138, plog=0x7cccb8, ptemp=0x7d0cd8, s=0x7cee60) at src/apache2_module/Hooks.cpp:1610
#12 0x0000000000464b2a in ap_run_post_config ()
#13 0x000000000043770f in main ()
```

**Question 2: Passenger version and integration mode**: open source 5.0.26/EasyApache 3
**Question 3: OS or Linux distro, platform (including version)**:  CloudLinux 6.8 x86_64
**Question 4: Passenger installation method**: source tarball
**Question 5: Your app's programming language (including any version managers) and framework (including versions)**: No app has been loaded yet by the moment of crash 
**Question 6: Are you using a PaaS and/or containerization? If so which one?**: LVE containerization code has not been activated yet by the moment of crash

**Question 7: Anything else about your setup that we should know?**

```
Server version: Apache/2.4.18 (Unix)
Server built: Jun 1 2016 12:16:16
Cpanel::Easy::Apache v3.32.14 rev9999 +cloudlinux
Server's Module Magic Number: 20120211:52
Server loaded: APR 1.5.2, APR-UTIL 1.5.4
Compiled using: APR 1.5.2, APR-UTIL 1.5.4
Architecture: 64-bit
Server MPM: event
threaded: yes (fixed thread count)
forked: yes (variable process count)
Server compiled with....
-D APR_HAS_SENDFILE
-D APR_HAS_MMAP
-D APR_HAVE_IPV6 (IPv4-mapped addresses disabled)
-D APR_USE_SYSVSEM_SERIALIZE
-D APR_USE_PTHREAD_SERIALIZE
-D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
-D APR_HAS_OTHER_CHILD
-D AP_HAVE_RELIABLE_PIPED_LOGS
-D DYNAMIC_MODULE_LIMIT=256
-D HTTPD_ROOT="/usr/local/apache"
-D SUEXEC_BIN="/usr/local/apache/bin/suexec"
-D DEFAULT_PIDLOG="logs/httpd.pid"
-D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
-D DEFAULT_ERRORLOG="logs/error_log"
-D AP_TYPES_CONFIG_FILE="conf/mime.types"
-D SERVER_CONFIG_FILE="conf/httpd.conf"
```

**Comment by OnixGH** [comment]
Does the same happen with 5.0.28?

**Comment by oshchukin** [comment]
Hello. We have scheduled Passenger 5.0.29 repack for EasyApache to re-test 5.0.29 with this issue. The crash happens on every start but on this one server only. That server is a PROD for our client. Although, the client gently provides us a maintenance window to collect the core and other details for the crash.

**Comment by OnixGH** [comment]
5.0.29 was released yesterday, let us know if you have the results of the re-test!

**Comment by oshchukin** [comment]
Hello, we asked the client to re-test with 5.0.29 which was previously available in 'stable' branch. But the client sticks to 4.0.58 and seems to be not interested in experimenting, as far it means downtime for his server.

**Comment by OnixGH** [comment]
Thanks @oshchukin. If someone else experiences it or they still want to switch at some point in the future we can reopen.

**Comment by moorem** [comment]
Not able to install Passenger


root@ws1 [~]# passenger-install-apache2-module
Welcome to the Phusion Passenger Apache 2 module installer, v5.1.3.

This installer will guide you through the entire installation process. It
shouldn't take more than 3 minutes in total.

Here's what you can expect from the installation process:

 1. The Apache 2 module will be installed for you.
 2. You'll learn how to configure Apache.
 3. You'll learn how to deploy a Ruby on Rails application.

Don't worry if anything goes wrong. This installer will advise you on how to
solve any problems.

Press Enter to continue, or Ctrl-C to abort.


--------------------------------------------

Which languages are you interested in?

Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Ruby
   ⬢  Python
   ⬡  Node.js
   ⬡  Meteor

--------------------------------------------

Checking for required software...

 * Checking for C compiler...
      Found: yes
      Location: /usr/bin/cc
 * Checking for C++ compiler...
      Found: yes
      Location: /usr/bin/c++
 * Checking for Curl development headers with SSL support...
      Found: yes
      curl-config location: /usr/bin/curl-config
      Usable: yes
      Header location: /usr/include/curl/curl.h
      Version: libcurl 7.29.0
      Supports SSL: yes
 * Checking for OpenSSL development headers...
      Found: yes
      Location: /usr/include/openssl/ssl.h
 * Checking for Zlib development headers...
      Found: yes
      Location: /usr/include/zlib.h
 * Checking for Apache 2...
      Found: yes
      Apache version: 2.4.12
      Location of httpd: /usr/sbin/httpd
 * Checking for Apache 2 development headers...
      Found: no
 * Checking for Rake (associated with /usr/local/rvm/gems/ruby-1.8.7-head/wrappers/ruby)...
      Found: yes
      Location: /usr/local/rvm/gems/ruby-1.8.7-head/wrappers/rake
 * Checking for OpenSSL support for Ruby...
      Found: yes
 * Checking for RubyGems...
      Found: yes
 * Checking for Ruby development headers...
      Found: yes
      Location: /usr/local/rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/x86_64-linux/ruby.h
 * Checking for rack...
      Found: yes

Some required software is not installed.
But don't worry, this installer will tell you how to install them.
Press Enter to continue, or Ctrl-C to abort.

--------------------------------------------

Installation instructions for required software

 * To install Apache 2 development headers:
   Please install it with yum install httpd-devel

If the aforementioned instructions didn't solve your problem, then please take
a look at our documentation for troubleshooting tips:

  https://www.phusionpassenger.com/library/install/apache/
  https://www.phusionpassenger.com/library/admin/apache/troubleshooting/
root@ws1 [~]# yum install httpd-devel
Loaded plugins: fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
 * cpanel-addons-production-feed: 85.13.201.2
 * base: mirror.mhd.uk.as44574.net
 * extras: mirror.as29550.net
 * updates: ftp.rezopole.net
No package httpd-devel available.
Error: Nothing to do
root@ws1 [~]#

**Comment by CamJN** [comment]
The Passenger 5.1.3 release did not go well and we're working on pushing out 5.1.4 as soon as we can fix the problems. Until then please use 5.1.2.
