### ISSUE TITLE
Load balancing is not fair, without sticky sessions

### ISSUE THREAD

**Issue by fernandoluizao** [phusion/passenger#1826]
Hi,

Seems like I have the same problem of #1322, but I'm not using sticky sessions, it's a Rails application with uses Devise for authentication. The requests seems to always been placed on the originating process.

Environment
Ubuntu 14.04 64 bits (4 core, 8GB mem)
Passenger 5.0.28/Apache 2.4.7 (installed from Phusion APT repo, opensource version)
Ruby 2.2.4, Rails 4.2.6

Steps to reproduce:

1. Create a slow Rails action, which takes 5s to return;
2. "Warm up" passenger, with at least 5 processes;
3. Run passenger-status, take note of processed count;
4. Fire 5 requests in a row to this action;
5. Run passenger-status again, comparing processed count;

- What is the expected behavior?
Requests being balanced between 5 processes.

- What is the actual behavior?
The requests are stacked on the first process, and the other 4 processes are idle.

I'm having a hard time tracking this down... I have read the guide about [request balancing](https://www.phusionpassenger.com/library/indepth/ruby/request_load_balancing.html), the troubleshooting guide, but don't get any clues about what is happening.

I'm missing something, or when the user is authenticated the requests goes to the same process?

Thanks

**Comment by OnixGH** [comment]
Does the same thing happen if you space the 5 requests by 1 second?

**Comment by fernandoluizao** [comment]
Yes, same behavior.

**Comment by OnixGH** [comment]
Can you: 
- post your apache configuration
and additionally:
- execute a test with log level to 7
- post the output of `passenger-status` before and during the test
- post the log

**Comment by fernandoluizao** [comment]
Here's a gitst of apache conf and passenger-status output: 

https://gist.github.com/fernandoluizao/f6a06e5a7cab2bff7e2765c7025b957e

The apache configuration is pretty standard, I haven't changed much from ubuntu default install, just added PassengerMaxPoolSize, PassengerMinInstances, and configured vhost.

By execute with log level 7 you mean 

`
LogLevel trace7
`

?

**Comment by OnixGH** [comment]
With log level 7 I mean: [PassengerLogLevel 7](https://www.phusionpassenger.com/library/config/apache/reference/#passengerloglevel)

**Comment by OnixGH** [comment]
I tried this and am unable to reproduce it. After the warmup request, `passenger-status` tells me:

```
  Requests in queue: 0
  * PID: 18223   Sessions: 0       Processed: 1       Uptime: 15s
    CPU: 0%      Memory  : 40M     Last used: 15s ago
  * PID: 18230   Sessions: 0       Processed: 0       Uptime: 15s
    CPU: 0%      Memory  : 25M     Last used: 15s ago
  * PID: 18237   Sessions: 0       Processed: 0       Uptime: 15s
    CPU: 0%      Memory  : 18M     Last used: 15s ago
  * PID: 18244   Sessions: 0       Processed: 0       Uptime: 14s
    CPU: 0%      Memory  : 18M     Last used: 14s ago
  * PID: 18251   Sessions: 0       Processed: 0       Uptime: 14s
    CPU: 0%      Memory  : 18M     Last used: 14s ago
  * PID: 18258   Sessions: 0       Processed: 0       Uptime: 14s
    CPU: 0%      Memory  : 2M      Last used: 14s ago
```

Then I execute `curl http://localhost:3000/slow/index?sleep=5 & curl http://localhost:3000/slow/index?sleep=5 & curl http://localhost:3000/slow/index?sleep=5 & curl http://localhost:3000/slow/index?sleep=5 & curl http://localhost:3000/slow/index?sleep=5 & sleep 1; passenger-status`:

```
  Requests in queue: 0
  * PID: 18223   Sessions: 1       Processed: 1       Uptime: 26s
    CPU: 0%      Memory  : 40M     Last used: 1s ago
  * PID: 18230   Sessions: 1       Processed: 0       Uptime: 26s
    CPU: 0%      Memory  : 25M     Last used: 1s ago
  * PID: 18237   Sessions: 1       Processed: 0       Uptime: 26s
    CPU: 0%      Memory  : 18M     Last used: 1s ago
  * PID: 18244   Sessions: 1       Processed: 0       Uptime: 25s
    CPU: 0%      Memory  : 18M     Last used: 1s ago
  * PID: 18251   Sessions: 1       Processed: 0       Uptime: 25s
    CPU: 0%      Memory  : 18M     Last used: 1s ago
  * PID: 18258   Sessions: 0       Processed: 0       Uptime: 25s
    CPU: 0%      Memory  : 2M      Last used: 25s ago
```

Requests are distributed as expected. And finally, `passenger status` again shows everything is handled OK:

```
  Requests in queue: 0
  * PID: 18223   Sessions: 0       Processed: 2       Uptime: 36s
    CPU: 0%      Memory  : 40M     Last used: 11s ago
  * PID: 18230   Sessions: 0       Processed: 1       Uptime: 36s
    CPU: 0%      Memory  : 34M     Last used: 11s ago
  * PID: 18237   Sessions: 0       Processed: 1       Uptime: 36s
    CPU: 0%      Memory  : 28M     Last used: 11s ago
  * PID: 18244   Sessions: 0       Processed: 1       Uptime: 35s
    CPU: 0%      Memory  : 28M     Last used: 11s ago
  * PID: 18251   Sessions: 0       Processed: 1       Uptime: 35s
    CPU: 0%      Memory  : 28M     Last used: 11s ago
  * PID: 18258   Sessions: 0       Processed: 0       Uptime: 35s
    CPU: 0%      Memory  : 2M      Last used: 35s ago
```

One thing I noticed is that you posted configuration that shows `PassengerMaxPoolSize 10` but actually your `passenger-status` output shows `Max pool size : 8`. That suggests you've changed something in between or there is some other configuration still active..

**Comment by fernandoluizao** [comment]
I will close this, since it looks like a problem with my environment, not passenger itself.

I will do more tests to understand what happened.

Thank you for your help.
