### ISSUE TITLE
Support setting scheme to HTTPS via passenger_set_header

### ISSUE THREAD

**Issue by avkarenow** [phusion/passenger#1827]
Hello,

since 5.x wsgi.url_scheme doesn't change to 'https' when HTTP_HTTPS header is set (but it works on Passenger 4.x).

I attached a patch which solve this issue.

[helper-scripts__wsgi-loader.py.patch.txt](https://github.com/phusion/passenger/files/316287/helper-scripts__wsgi-loader.py.patch.txt)

**Comment by OnixGH** [comment]
When I start Passenger 5.0.28 (standalone) with `--ssl` etc., I don't see the `HTTP_HTTPS` header in the `env`, just the `HTTPS` header, and the `wsgi.url_scheme` is correctly set to `https`.

Can you explain why you need the `HTTP_HTTPS` header?

**Comment by avkarenow** [comment]
I have proxy from HTTPS (which send header SSL with info about HTTPS) -> HTTP nginx/passenger
In my nginx config:
passenger_set_header HTTPS $http_SSL; # from upstream

4.x set env as HTTPS (via passenger_set_cgi_param HTTPS $http_SSL;) but 5.x set this header as HTTP_HTTPS.

**Comment by OnixGH** [comment]
Hmm, I understand your use case, but this implementation introduces a vulnerability:
Clients can simply add the `HTTPS: on` header in their request and fool Passenger into setting `wsgi.url_scheme: https` when it is not. We'll have to think about this some more.

**Comment by OnixGH** [comment]
Some relevant thoughts & workaround:
https://groups.google.com/forum/#!topic/phusion-passenger/Nn-HehmWt28

**Comment by avkarenow** [comment]
I reconfigured my Nginx's virtual host to works with SSL and non-SSL (proxy to two ports) - now it sets HTTPS environment variable for SSL requests.

**Comment by CamJN** [comment]
Glad you got it working, closing for now.
