### ISSUE TITLE
Ubuntu signature uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by xdmx** [phusion/passenger#1832]
I've added the key with `apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7` to a clean Ubuntu 16.04 and after every `apt update` it says `W: https://oss-binaries.phusionpassenger.com/apt/passenger/dists/xenial/Release.gpg: Signature by key 16378A33A6EF16762922526E561F9B9CAC40B2F7 uses weak digest algorithm (SHA1)`

**Comment by OnixGH** [comment]
We've upgraded to SHA-256 signatures. You will probably need to clean your local cache to have it take effect though. On Ubuntu, that's something like:
```
rm /var/lib/apt/lists/oss-binaries.phusionpassenger.com_apt_passenger*.gpg
```
