### ISSUE TITLE
GPG Errors on apt-get update

### ISSUE THREAD

**Issue by ChayD** [phusion/passenger#1834]
**Question 1: What is the problem?**
New install, attempting to add passenger repos, after importing keys, we get error:

W: GPG error: https://oss-binaries.phusionpassenger.com wheezy Release: The following signatures were invalid: BADSIG 561F9B9CAC40B2F7 Phusion Automated Software Signing (Used by automated tools to sign software packages) <auto-software-signing@phusion.nl>

Removing and re-adding keys thusly didn't work either:

apt-key del 561F9B9CAC40B2F7
gpg --delete-keys AC40B2F7
gpg --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
gpg --armor --export 561F9B9CAC40B2F7 | apt-key add -

Remaining questions don't appear to be relevant as Passenger not even installed.

**Comment by OnixGH** [comment]
Can't reproduce this on a clean Debian 7 "Wheezy" box. Did you follow the [instructions from the Passenger Library](https://www.phusionpassenger.com/library/install/nginx/install/oss/)?

**Comment by ChayD** [comment]
Our installs are automated with puppet, so didn't execute these manually, however the puppet scripts do install all the deps required: ca-certificates, apt-transport-https, then pulls the cert from ubuntu keyserver and imports into apt as above commands. We've put in a workaround so we can get the box deployed to so no longer an issue. I assume something at our end was having problems, but unable to determine. Thanks for investigating.
