### ISSUE TITLE
Passenger Standalone: envvars not working for METEOR_SETTINGS

### ISSUE THREAD

**Issue by mking200** [phusion/passenger#1837]
When you deploy the app using Passengerfile.json file, the json format variable of METEOR_SETTINGS is being converted into a single string with the "envvars" settings, so Meteor won't recognize this as a valid json format upon deployment.

Can this be fixed to retain the json format of METEOR_SETTINGS like this example:

`"envvars": { 
      METEOR_SETTINGS: { "public": { "service1": { "key1": "value1", "key2": "value2" } }, 
                                            "service2": { "key1": "value1", "key2": "value2" } 
                                            }
 }`

Currently, the example above is being converted into something like this: `"publicservice1key1value1key2value2service2key1value1key2value2"`

**Comment by CamJN** [comment]
Setting the value of METEOR_SETTINGS as a string works in my test example.

`"envvars": { "METEOR_SETTINGS": "{ \"public\": { \"service1\": { \"key1\": \"value1\", \"key2\": \"value2\" } }, \"service2\": { \"key1\": \"value1\", \"key2\": \"value2\" } }" }`

**Comment by mking200** [comment]
Hi @CamJN, thanks for this solution.
