### ISSUE TITLE
Passenger hangs with Rails5 + meta_request gem

### ISSUE THREAD

**Issue by shaicoleman** [phusion/passenger#1838]
---

When running passenger with meta_request gem, passenger completes process the request, but doesn't return a response, the socket just hangs there.
When running with other webservers, the requests completes as normal.

To replicate I've created a blank Rails 5 app, and added the meta_request gem.

Rails 5.0.0
Ruby 2.3.1
Passenger 5.0.29/nginx via RubyGems (no Gemfile)
RVM head 1.27.0 (master)
Ubuntu 14.04 x64 (kernel 4.4.0)
meta_request 0.4.0

vhost:
```
server {
    server_name rails5.dev;
    listen 80;
    listen 443 ssl;
    root /home/user/rails5/public;
    passenger_enabled on;
    passenger_ruby /home/user/.rvm/gems/ruby-2.3.1@rails5/wrappers/ruby;
    rails_env development;
}
```

```
$ curl --max-time 10 http://rails5.dev/
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
```

Request appear as processed in passenger-status:
```
# passenger-status
Version : 5.0.29
Date    : 2016-07-11 18:53:31 +0100
Instance: kPpLckGw (nginx/1.10.1 Phusion_Passenger/5.0.29)

----------- General information -----------
Max pool size : 4
App groups    : 1
Processes     : 2
Requests in top-level queue : 0

----------- Application groups -----------
/home/user/rails5/public (development):
  App root: /home/user/rails5
  Requests in queue: 0
  * PID: 14894   Sessions: 1       Processed: 0       Uptime: 2m 43s
    CPU: 0%      Memory  : 29M     Last used: 2m 43s ago
  * PID: 15372   Sessions: 0       Processed: 5       Uptime: 16s
    CPU: 0%      Memory  : 28M     Last used: 12s ago
```

**Comment by OnixGH** [comment]
Haven't tried this, but the status shows 6 requests, of which 5 completed and 1 appears to be hung. What exactly did you do there?

Could you:
1. Set the loglevel to 7 and start Passenger fresh
2. Run the curl

And then paste the output of `passenger-status --show=server` as well as the (level 7) Passenger log?

**Comment by shaicoleman** [comment]
passenger-status log: https://paste.ee/r/fM1zO
passenger log: https://paste.ee/r/I9yOA

**Comment by CamJN** [comment]
fixed in https://github.com/phusion/passenger/pull/1840
