### ISSUE TITLE
Running passenger standalone as arbitrary uid

### ISSUE THREAD

**Issue by jperville** [phusion/passenger#1849]
## Issue report

**Question 1: What is the problem?**

Your answer: I am trying to run a simple Rack application with passenger standalone as an arbitrary uid using docker container.

Inside the container, the `passenger start` process will fail with the following stacktrace:

```
/usr/share/ruby/vendor_ruby/phusion_passenger.rb:323:in `getpwuid': can't find user for 100001 (ArgumentError)
    from /usr/share/ruby/vendor_ruby/phusion_passenger.rb:323:in `home_dir'
    from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/config_utils.rb:46:in `global_config_file_path'
    from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/command.rb:58:in `load_and_merge_global_options'
    from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/command.rb:40:in `parse_options'
    from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/start_command.rb:49:in `run'
    from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/main.rb:51:in `run!'
    from /usr/bin/passenger:44:in `<main>'
```

I would expect passenger standalone to start serving the Rack application instead of crashing.

You can reproduce by writing a sample Rack application (eg. sinatra) and packaging it with its ruby bundle inside a docker image; the COMMAND of the container should be executing something like "passenger start --port 4000" using the directory where the `config.ru` files resides as its WORKDIR.

As long as the USER running the `passenger start` is listed in /etc/passwd then it works (both root and non-root user), but if we force an arbitrary uid (that is not listed in /etc/passwd) then it fails with the above stacktrace

Running docker image under arbitrary uid is easy as:

``` sh
docker run --rm -u 10001 mydockerimage
```

Why am trying this? Because I am building an OpenShift 3 builder image for running Ruby web applications using passenger 5 standalone; I need the arbitrary user because that is how OpenShift 3 will run the containers (for security reasons); In OpenShift 3, the applications are usually compiled under user of uid 1001, then run as arbitrary uid (such as 10001) which cannot write anything in the container, just execute code. If needed, that policy can be relaxed (by editing the OpenShift Security Context Constraints) and the container can run as user 1001 but that is not the default and that is IMO less secure than running as arbitrary uid.

**Question 2: Passenger version and integration mode**:
Your answer: open source 5.0.30 standalone

**Question 3: OS or Linux distro, platform (including version)**:
Your answer: Centos 7, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ X] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer: Ruby 2.2.2 (taken from centos SCL repository), using bundler 1.12.5; no special framework, just a plain sinatra application.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer: docker image built using a custom "sourcetoimage" builder image

**Comment by CamJN** [comment]
Can you provide a sample Dockerfile? I've found one place where this issue occurs, but I'd like to check for any others.

**Comment by jperville** [comment]
@CamJN create the following `Dockerfile`:

```
FROM openshift/base-centos7

EXPOSE 8080

# Install phusion passenger 5.x following https://www.phusionpassenger.com/library/install/nginx/install/oss/el7/
RUN yum install -y epel-release yum-utils && \
    yum-config-manager --enable epel && \
    yum install -y pygpgme curl && \
    curl --fail -sSLo /etc/yum.repos.d/passenger.repo https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo && \
    yum install -y passenger passenger-devel

RUN chown -R 1001:0 /opt/app-root && chmod -R ug+rwx /opt/app-root

USER 1001

CMD ["passenger", "start", "--port", "8080"]
```

Build the image with `docker build -t test .` then run the following commands:
```sh
# running as well-known non-root user => works
docker run --rm -ti --name=test -u 1001 test
# running as arbitrary non-root user (with no /etc/password entry) => breaks
docker run --rm -ti --name=test -u 100100 test
```

**Comment by jperville** [comment]
Thank you very much @CamJN
