### ISSUE TITLE
Crash El Capitan - Assertion failed: STAILQ_NEXT(mbuf_block, next) == NULL

### ISSUE THREAD

**Issue by kpmueller** [phusion/passenger#1852]
## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Are you sure this is a bug in Passenger?**

Pretty sure

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

I'm running the latest

**Question 1: What is the problem?**

Your answer:

We make a web request to a Rails app rendered by Passenger. Unfortunately, I don't have a use case I can make public. 

**Question 2: Passenger version and integration mode**:

Open Source 5.0.30, nginx version is 1.10.1

**Question 3: OS or Linux distro, platform (including version)**:

MacOS El Capitan 10.11.6, Xcode 7.3.1

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[X] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer:

An old ruby, 1.8.7-p375 on rails 2.3.8 

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer:

No

**Question 7: Anything else about your setup that we should know?**

We compile from source to make it similar to our AWS ubuntu 14.04 deployment.

Thanks!
[passenger-5.0.30-crash.txt](https://github.com/phusion/passenger/files/402391/passenger-5.0.30-crash.txt)

**Comment by FooBarWidget** [comment]
You say you are running 5.0.30, but the crash log says you are running 5.0.28. We specifically fixed this bug in 5.029.

**Comment by kpmueller** [comment]
You're right, I think somehow it didn't get the new path in our config. Sorry about that! I'll close this, and re-open if necessary

**Comment by OnixGH** [comment]
(was a duplicate of #1794)
