### ISSUE TITLE
Rename `passenger-config` tool

### ISSUE THREAD

**Issue by cmckni3** [phusion/passenger#1853]
Would it be possible to rename the `passenger-config` tool that helps manage instances of passenger?

https://github.com/Homebrew/brew/issues/646

**Comment by CamJN** [comment]
We discussed it, but can't justify the work and breakage it would cause for our users & customers, and we don't believe we're violating any standards.

Also when I run brew doctor I don't get that error, how did you install passenger?

**Comment by cmckni3** [comment]
I used `gem install passenger`

Homebrew is complaining for me because:

1. It contains `-config` in the name as mentioned before
2. `~/.rbenv/shims` is included in `$PATH`

**Comment by CamJN** [comment]
One option is to install passenger via homebrew, then the homebrew doctor won't complain about it.

**Comment by cmckni3** [comment]
@CamJN I think that's a better solution. Thanks!

**Comment by FlowerWrong** [comment]
[install nginx + passenger on mac](https://www.phusionpassenger.com/library/install/nginx/install/oss/osx/)

**Comment by CamJN** [comment]
@FlowerWrong That link is from our documentation, where we recommend using homebrew to install passenger. I'm not sure if you were just trying to provide a helpful link or something more.
