### ISSUE TITLE
Add ability to hide passenger X-Powered-By header (patch)

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#186]
_From [paul06@4email.net](https://code.google.com/u/118330917436940099397/) on June 10, 2008 08:24:11_

For security reasons some users may prefer that their server configuration
is not exposed through Apache. The apache directive "ServerSignature Off"
is often used to hide Apache information.

Currently Passenger exposes itself in the X-Powered-By HTTP header it sends.

There are a few potential solutions for this:

1) Support mod_header in .htaccess to unset headers. For example:

Header unset "X-Powered-By"

2) Have an apache config directive such as ExposePassenger which could be
set similar to the PHP php.ini configuration option expose_php ( http://www.php.net/security.hiding ).

I looked into writing a patch but I do not know the Apache internals and it
looked like I would have to change many method signatures, for example in
the SpawnManager class, to let the ruby Spawner know about the Apache
directive.

3) The third and most simple approach would be to allow users to set a
constant in their environment.rb files to tell passenger not to send the
header. I have attached a patch (git formatted) that achieves this.

**Attachment:** [expose_passenger.patch](http://code.google.com/p/phusion-passenger/issues/detail?id=85)

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=85_

**Comment by akshay-vishnoi** [comment]
@FooBarWidget - The info you provided explains how to remove the version number of the tool from the headers.

Can you please also tell me how can we remove headers from the response completely?

**Comment by CamJN** [comment]
If you want to completely remove the `X-Powered-By` header, then in Apache you can use `Header unset X-Powered-By` from http://httpd.apache.org/docs/2.2/mod/mod_headers.html#header.

**Comment by simison** [comment]
In case anyone comes searching here, to completely remove `X-Powered-By` and `Server` headers from Nginx+Passenger, add this to your `http` block in `nginx.conf`:
```
server_tokens off;
more_clear_headers Server;
more_clear_headers X-Powered-By;
```

You could also set your own:
```
more_set_headers "Server: ACME";
```

Remember to restart the server for these to take affect. You should test your config before restart though: `sudo nginx -t`.

[via](https://calvin.my/posts/hiding-server-identity-and-signature-for-nginx-and-passenger)

**Comment by majgis** [comment]
I'm using Phusion Passenger Standalone 5.1.1.
The ngx_headers_more module is not included therefore I get errors like these:

    nginx: [emerg] unknown directive "more_set_headers" in nginx.conf:146

Is ngx_headers_more module included in more recent versions of Phusion Passenger Standalone?
Is there an alternative method to completely removing these headers?

**Comment by rajatbansal93** [comment]
@majgis you can install Nginx from source and include  [headers-more-nginx-module](https://github.com/openresty/headers-more-nginx-module) plugin. 
After this, you can use 'more_clear_headers' command to completely remove the headers you want.

**Comment by simison** [comment]
@majgis `more_set_headers` is Nginx directive, not Phusion passenger option.

**Comment by mathieujobin** [comment]
I didn't have much luck with the other solutions mentioned above.
I also tried to override with this one
https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_set_header

I can manipulate X-Powered-By easily, but nginx keep setting 'Server: nginx' at the minimum


I tried `server_tokens off;`,  `more_set_headers`, `add_header` and `passenger_set_header` to replace them

I am using the phusion-passenger-ruby docker image.

**Comment by Tofandel** [comment]
This is still an issue, even with the `server_tokens off;` and `passenger_show_version_version_in_header off;` the headers are still present

<html><body>


server | nginx + Phusion Passenger(R)
-- | --
x-powered-by | Phusion Passenger(R)



</body>
</html>

And `more_clear_headers` requires the `nginx-extras` package to be installed, which is really way overkill for this and cannot be installed if you have a custom nginx binary anyways (like it's the case for plesk)

**Comment by jpmermoz** [comment]
Any solution for this issue? We need to prevent Banner Grabbing from potential hackers.
