### ISSUE TITLE
Error when run: bundle exec passenger start

### ISSUE THREAD

**Issue by pl086p** [phusion/passenger#1861]
## Issue report

How does it happen?
   Run:    bundle exec passenger start     
   on:   passenger standalone  (v5.0.30) on CentOS 7

Error message:

In the bug report, please include this error message, as well as the contents of the file /tmp/passenger-standalone-wh91i4.log
[user88@user88 projTest1]$ bundle exec passenger start
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: [emerg] "gzip_types" directive The user specified by the 'default_user' option does not exist. in nginx.conf:123
    nginx: configuration file nginx.conf test failed

This probably means that you have found a bug in Phusion Passenger Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues

**Comment by OnixGH** [comment]
Duplicate, see #1770
