### ISSUE TITLE
Solaris 11.1 Passenger Enterprise 

### ISSUE THREAD

**Issue by CirrusThink** [phusion/passenger#1862]
Not sure what the issue is but I keep getting this when I 
rvmsuo passenger-install-nginx

Same issue with 4.0.29 and 5.0.30

Undefined      			first referenced
 symbol        			    in file
__cxa_throw_bad_array_new_length    buildout/agents/PassengerHelperAgent.o
_ZSt24__throw_out_of_range_fmtPKcz  buildout/common/libboost_oxt.a(instances.o)
_ZNSt8__detail15_List_node_base11_M_transferEPS0_S1_ buildout/agents/PassengerHelperAgent.o
_ZNSt8__detail15_List_node_base9_M_unhookEv buildout/agents/PassengerHelperAgent.o
_ZNSt8__detail15_List_node_base7_M_hookEPS0_ buildout/agents/PassengerHelperAgent.o
ld: fatal: symbol referencing errors. No output written to buildout/agents/PassengerHelperAgent
rake aborted!
Command failed with status (1): [c++ buildout/agents/PassengerHelperAgent.o -o buildout/agents/PassengerHelperAgent buildout/common/libpassenger_common/Logging.o buildout/common/libpassenger_common/Exceptions.o buildout/common/libpassenger_common/Utils/SystemTime.o buildout/common/libpassenger_common/Utils/StrIntUtils.o buildout/common/libpassenger_common/Utils/IOUtils.o buildout/common/libpassenger_common/Utils.o buildout/common/libpassenger_common/Utils/Base64.o buildout/common/libpassenger_common/Utils/CachedFileStat.o buildout/common/libpassenger_common/Utils/LargeFiles.o buildout/common/libpassenger_common/ApplicationPool2/Implementation.o buildout/common/libpassenger_common/ApplicationPool2/AppTypes.o buildout/common/libpassenger_common/AgentsBase.o buildout/common/libpassenger_common/Utils/MD5.o buildout/common/libpassenger_common/Utils/fib.o buildout/common/libpassenger_common/Utils/jsoncpp.o buildout/common/libboost_oxt.a   buildout/libev/.libs/libev.a buildout/libeio/.libs/libeio.a -lcurl -L/usr/lib -L/usr/lib -L/usr/lib -lidn -lssl -lcrypto -lsldap -lldap -lsocket -lnsl -lgss -lssl -lcrypto -lz -std=gnu++11 -lxnet -lsocket -lnsl -lpthread -lrt   ]

Tasks: TOP => nginx => nginx_without_native_support => buildout/agents/PassengerHelperAgent
(See full trace by running task with --trace)

**Comment by CirrusThink** [comment]
update to 11.2 developer/gcc installed

rvm ruby-2.3.1@global
rvmsudo EXTRA_CXXFLAGS=-DBOOST_MATH_DISABLE_STD_FPCLASSIFY CC=/usr/bin/gcc passenger-install-nginx-module


<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/math.h:13:0,
                 from src/cxx_supportlib/vendor-modified/boost/math/special_functions/fpclassify.hpp:14,
                 from src/cxx_supportlib/vendor-modified/jsoncpp/jsoncpp.cpp:207:
src/cxx_supportlib/vendor-modified/jsoncpp/jsoncpp.cpp: In function ‘std::string Json::valueToString(double)’:
src/cxx_supportlib/vendor-modified/jsoncpp/jsoncpp.cpp:3463:22: error: expected unqualified-id before ‘__extension__’
    if (!boost::math::isfinite(value)) {
                      ^
src/cxx_supportlib/vendor-modified/jsoncpp/jsoncpp.cpp:3463:22: error: expected ‘)’ before ‘__extension__’
rake aborted!
Command failed with status (1): [c++ -o buildout/common/libpassenger_common/jsoncpp.o  -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Isrc/cxx_supportlib/vendor-copy/libuv/include -O2 -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -feliminate-unused-debug-symbols -feliminate-unused-debug-types -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -ggdb -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -std=gnu++11 -Wno-unused-local-typedefs -DHASH_NAMESPACE="__gnu_cxx" -DHASH_MAP_HEADER="<hash_map>" -DHASH_MAP_CLASS="hash_map" -DHASH_FUN_H="<hash_fun.h>" -pthreads -D__EXTENSIONS__ -D__SOLARIS__ -D_FILE_OFFSET_BITS=64 -DBOOST_HAS_STDINT_H -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -c src/cxx_supportlib/vendor-modified/jsoncpp/jsoncpp.cpp]

Tasks: TOP => nginx => nginx_without_native_support => buildout/support-binaries/PassengerAgent => buildout/common/libpassenger_common/jsoncpp.o
(See full trace by running task with --trace)
--------------------------------------------

It looks like something went wrong

Please read our documentation for troubleshooting tips:

   https://www.phusionpassenger.com/library/install/nginx/
   https://www.phusionpassenger.com/library/admin/nginx/troubleshooting/

**Comment by CirrusThink** [comment]
Please label for enterprise customer

**Comment by CirrusThink** [comment]
any updates here ?

**Comment by CirrusThink** [comment]
also what do these message indicate ?
In file included from src/cxx_supportlib/vendor-modified/boost/config/platform/solaris.hpp:17:0,
                 from src/cxx_supportlib/vendor-modified/boost/config.hpp:57,
                 from src/cxx_supportlib/vendor-modified/boost/thread/detail/config.hpp:11,
                 from src/cxx_supportlib/vendor-modified/boost/thread/tss.hpp:8,
                 from src/cxx_supportlib/oxt/system_calls.hpp:28,
                 from src/agent/Shared/Base.cpp:15:
src/cxx_supportlib/vendor-modified/boost/config/posix_features.hpp:27:0: warning: "BOOST_HAS_STDINT_H" redefined
 #        define BOOST_HAS_STDINT_H
 ^
<command-line>:0:0: note: this is the location of the previous definition

**Comment by CamJN** [comment]
Not yet, the "BOOST_HAS_STDINT_H" redefined messages mean exactly what they say, the macro was defined more than once.

Is there a reason you're setting the BOOST_MATH_DISABLE_STD_FPCLASSIFY macro?

**Comment by CirrusThink** [comment]
I was told in the past to set this in order to compile on Solaris 11.2, so far that seems not to be the case. I will try again without the option and gits you the results

**Comment by CirrusThink** [comment]
Here it is https://gist.github.com/CirrusThink/b2be35eda792a4c9f7196351cd22d207

**Comment by CirrusThink** [comment]
tried again , besides all errors it seems to not be able to find some symbols, any indication to what to search for?

**Comment by CamJN** [comment]
The missing symbol is from the c++ std library, so perhaps try setting the CXX environment variable to the path to gcc's c++ executable, in case another version is being called. Also you could check if you have an appropriate lib32stdc++ or lib64stdc++ installed.

**Comment by CirrusThink** [comment]
That suggestion helped fix the issue!
I did some digging and was able to determine that the C++ developer pkg was not installed. I did the following:

sudo pkg install developer/gcc/gcc-c++ 
rvmsudo CC=/usr/bin/gcc CXX=/usr/bin/c++ passenger-install-nginx-module

Is there a place where we can document the pkg 's that need to be installed for Solaris 11.x deployments ?

**Comment by CamJN** [comment]
I'm glad that you solved it. We're looking into creating a Solaris installation walkthrough. It would be helpful if you listed the packages that you had to install to build passenger, and we'll include them in the walkthrough.

**Comment by CamJN** [comment]
I'm going to close this issue, but feel free to comment with the packages you needed to install to get this working.
