### ISSUE TITLE
Disconnecting long-running connections for process with Rails and 'passenger_pool_idle_time 0' has no effect on the situation

### ISSUE THREAD

**Issue by DanTaiko** [phusion/passenger#1865]
**Question 1: What is the problem?**

We currently use open-source Passenger (installed as a gem) with NGINX. There are two Rails apps running on two different Ruby (1.9.3 and 2.2.2) with RVM support.

One rails app (on 1.9.3 ruby) runs fine, but another one (on 2.2.2 Ruby) runs slow. Each http-request to the 2.2.2 Ruby app throws the following lines into the passenger log:
> App 23060 stdout:
> [ 2016-08-28 17:36:44.8355 22569/7fe699e5a700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 22961, application /u/apps/example/current/public
> App 23084 stdout:

Trying to handle that, I had put the ‘passenger_pool_idle_time 0;’ into the NGINX config like this:
```
http {

    passenger_root /home/webadmin/.rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.30;

    passenger_log_file /u/apps/passenger.log;

    passenger_pool_idle_time 0;
```

And even after NGINX restarting it has no effect on the situation.
Please, advice.

**Question 2: Passenger version and integration mode**:
Open-source Passenger 5.0.30 (installed as a gem) with NGINX

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 14.04.3 LTS, x86_64

**Question 4: Passenger installation method**:
RubyGems, no Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
RVM
Rails 4.2.6

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
My NGINX config:
```
user  webadmin;
worker_processes  6;

events {
    worker_connections  1024;
}

http {
    passenger_root /home/webadmin/.rvm/gems/ruby-1.9.3-p551/gems/passenger-5.0.30;
    passenger_ruby /home/webadmin/.rvm/gems/ruby-1.9.3-p551/wrappers/ruby;
	passenger_log_file /u/apps/passenger.log;
    passenger_pool_idle_time 0;

    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    ...
    
    server {
      listen 443 ssl;
      server_name speakers.example.ru;
      ssl_certificate     /home/webadmin/ssl/example.chained.crt;
      ssl_certificate_key /home/webadmin/ssl/example.key;
      error_log /u/apps/example/shared/log/nginx.error.log;
      access_log /u/apps/example/shared/log/nginx.access.log; #charset koi8-r;
      root /u/apps/example/current/public;
      passenger_ruby /home/webadmin/.rvm/gems/ruby-2.2.2@example/wrappers/ruby;
      passenger_enabled on;
    }
    
    ...
} 
```

**Comment by OnixGH** [comment]
"Each http-request to the 2.2.2 Ruby app throws the [disconnecting long running]".

Does it always happen? From the very start? Can you post the entire log as well as the output of `passenger-status` and `passenger-status --show=requests`?

**Comment by DanTaiko** [comment]
Thanks for fast reply.

Yes, each and every http-request to the 2.2.2 Ruby app throws the [Checking whether to disconnect long-running connections for process]". See the Passenger log from the Passenger restart:

> [ 2016-08-29 11:08:15.6999 32284/7f12e46e77c0 age/Wat/WatchdogMain.cpp:1291 ]: Starting Passenger watchdog...
> [ 2016-08-29 11:08:15.7076 32287/7f2cf92717c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
> [ 2016-08-29 11:08:15.7078 32287/7f2cf92717c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
> [ 2016-08-29 11:08:15.7104 32287/7f2cf92717c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 32287
> [ 2016-08-29 11:08:15.7593 32292/7fcc1e6677c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
> [ 2016-08-29 11:08:15.7603 32292/7fcc1e6677c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 32292
> App 32328 stdout: 
> App 32397 stdout: 
> App 32328 stderr: /u/apps/ruby193_app/shared/bundle/ruby/1.9.1/gems/tlsmail-0.0.1/lib/net/smtp.rb:806: warning: already initialized constant SMTPSession
> App 32328 stderr: /u/apps/ruby193_app/shared/bundle/ruby/1.9.1/gems/tlsmail-0.0.1/lib/net/pop.rb:687: warning: already initialized constant POP
> App 32328 stderr: /u/apps/ruby193_app/shared/bundle/ruby/1.9.1/gems/tlsmail-0.0.1/lib/net/pop.rb:688: warning: already initialized constant POPSession
> App 32328 stderr: /u/apps/ruby193_app/shared/bundle/ruby/1.9.1/gems/tlsmail-0.0.1/lib/net/pop.rb:689: warning: already initialized constant POP3Session
> App 32328 stderr: /u/apps/ruby193_app/shared/bundle/ruby/1.9.1/gems/tlsmail-0.0.1/lib/net/pop.rb:702: warning: already initialized constant APOPSession
> App 32474 stdout: 
> App 32328 stderr: /u/apps/ruby193_app/releases/20160826141842/config/initializers/mailer.rb:5: warning: already initialized constant VERIFY_PEER
> App 32498 stdout: 
> [ 2016-08-29 11:08:33.1264 32287/7f2ccbfff700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 32474, application /u/apps/ruby222_app/current/public
> App 32509 stdout: 
> App 32588 stdout: 
> [ 2016-08-29 11:08:41.8716 32287/7f2ccb5fe700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 32588, application /u/apps/ruby222_app/current/public
> App 32603 stdout: 
> App 32683 stdout: 
> [ 2016-08-29 11:08:47.2958 32287/7f2ccabfd700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 32683, application /u/apps/ruby222_app/current/public
> App 32695 stdout: 
> App 306 stdout: 


Further see the ‘passenger-status’ below:

> Version : 5.0.30
> Date    : 2016-08-29 11:10:45 +0300
> Instance: 4UiWInGn (nginx/1.10.1 Phusion_Passenger/5.0.30)
> 
> ----------- General information -----------
> Max pool size : 6
> App groups    : 2
> Processes     : 2
> Requests in top-level queue : 0
> 
> ----------- Application groups -----------
> /u/apps/ruby222_app/current/public:
>   App root: /u/apps/222ruby_app/current
>   Requests in queue: 0
>   * PID: 306     Sessions: 0       Processed: 1       Uptime: 1m 54s
>     CPU: 0%      Memory  : 42M     Last used: 1m 54s ago
> 
> /u/apps/ruby193_app/current/public:
>   App root: /u/apps/ruby193_app/current
>   Requests in queue: 0
>   * PID: 32498   Sessions: 0       Processed: 7       Uptime: 2m 13s
>     CPU: 1%      Memory  : 45M     Last used: 1m 15s ago

‘passenger-status --show=requests’:

> Version : 5.0.30
> Date    : 2016-08-29 11:10:49 +0300
> Instance: 4UiWInGn (nginx/1.10.1 Phusion_Passenger/5.0.30)
> 
> {
>    "thread1" : {
>       "active_client_count" : 0,
>       "active_clients" : {},
>       "client_accept_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 10.680
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.060
>          }
>       },
>       "disconnected_client_count" : 0,
>       "disconnected_clients" : {},
>       "free_client_count" : 128,
>       "free_request_count" : 1,
>       "mbuf_pool" : {
>          "active_blocks" : 0,
>          "active_memory" : {
>             "bytes" : 0,
>             "human_readable" : "0 bytes"
>          },
>          "chunk_size" : 4096,
>          "free_blocks" : 2,
>          "offset" : 4048,
>          "spare_memory" : {
>             "bytes" : 8192,
>             "human_readable" : "8.0 KB"
>          }
>       },
>       "peak_active_client_count" : 1,
>       "pid" : 32287,
>       "request_begin_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 10.680
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.060
>          }
>       },
>       "server_state" : "ACTIVE",
>       "total_bytes_consumed" : 3792,
>       "total_clients_accepted" : 2,
>       "total_requests_begun" : 2,
>       "turbocaching" : {
>          "fetches" : 0,
>          "hit_ratio" : null,
>          "hits" : 0,
>          "store_success_ratio" : null,
>          "store_successes" : 0,
>          "stores" : 0
>       }
>    },
>    "thread2" : {
>       "active_client_count" : 0,
>       "active_clients" : {},
>       "client_accept_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 10.680
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.060
>          }
>       },
>       "disconnected_client_count" : 0,
>       "disconnected_clients" : {},
>       "free_client_count" : 128,
>       "free_request_count" : 1,
>       "mbuf_pool" : {
>          "active_blocks" : 0,
>          "active_memory" : {
>             "bytes" : 0,
>             "human_readable" : "0 bytes"
>          },
>          "chunk_size" : 4096,
>          "free_blocks" : 3,
>          "offset" : 4048,
>          "spare_memory" : {
>             "bytes" : 12288,
>             "human_readable" : "12.0 KB"
>          }
>       },
>       "peak_active_client_count" : 1,
>       "pid" : 32287,
>       "request_begin_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 10.680
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.060
>          }
>       },
>       "server_state" : "ACTIVE",
>       "total_bytes_consumed" : 2909,
>       "total_clients_accepted" : 2,
>       "total_requests_begun" : 2,
>       "turbocaching" : {
>          "fetches" : 0,
>          "hit_ratio" : null,
>          "hits" : 0,
>          "store_success_ratio" : null,
>          "store_successes" : 0,
>          "stores" : 0
>       }
>    },
>    "thread3" : {
>       "active_client_count" : 0,
>       "active_clients" : {},
>       "client_accept_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.050
>          }
>       },
>       "disconnected_client_count" : 0,
>       "disconnected_clients" : {},
>       "free_client_count" : 128,
>       "free_request_count" : 1,
>       "mbuf_pool" : {
>          "active_blocks" : 0,
>          "active_memory" : {
>             "bytes" : 0,
>             "human_readable" : "0 bytes"
>          },
>          "chunk_size" : 4096,
>          "free_blocks" : 2,
>          "offset" : 4048,
>          "spare_memory" : {
>             "bytes" : 8192,
>             "human_readable" : "8.0 KB"
>          }
>       },
>       "peak_active_client_count" : 1,
>       "pid" : 32287,
>       "request_begin_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.050
>          }
>       },
>       "server_state" : "ACTIVE",
>       "total_bytes_consumed" : 3675,
>       "total_clients_accepted" : 2,
>       "total_requests_begun" : 2,
>       "turbocaching" : {
>          "fetches" : 0,
>          "hit_ratio" : null,
>          "hits" : 0,
>          "store_success_ratio" : null,
>          "store_successes" : 0,
>          "stores" : 0
>       }
>    },
>    "thread4" : {
>       "active_client_count" : 0,
>       "active_clients" : {},
>       "client_accept_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.07000000000000001
>          }
>       },
>       "disconnected_client_count" : 0,
>       "disconnected_clients" : {},
>       "free_client_count" : 128,
>       "free_request_count" : 1,
>       "mbuf_pool" : {
>          "active_blocks" : 0,
>          "active_memory" : {
>             "bytes" : 0,
>             "human_readable" : "0 bytes"
>          },
>          "chunk_size" : 4096,
>          "free_blocks" : 3,
>          "offset" : 4048,
>          "spare_memory" : {
>             "bytes" : 12288,
>             "human_readable" : "12.0 KB"
>          }
>       },
>       "peak_active_client_count" : 1,
>       "pid" : 32287,
>       "request_begin_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.07000000000000001
>          }
>       },
>       "server_state" : "ACTIVE",
>       "total_bytes_consumed" : 2695,
>       "total_clients_accepted" : 2,
>       "total_requests_begun" : 2,
>       "turbocaching" : {
>          "fetches" : 0,
>          "hit_ratio" : null,
>          "hits" : 0,
>          "store_success_ratio" : null,
>          "store_successes" : 0,
>          "stores" : 0
>       }
>    },
>    "thread5" : {
>       "active_client_count" : 0,
>       "active_clients" : {},
>       "client_accept_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.07000000000000001
>          }
>       },
>       "disconnected_client_count" : 0,
>       "disconnected_clients" : {},
>       "free_client_count" : 128,
>       "free_request_count" : 1,
>       "mbuf_pool" : {
>          "active_blocks" : 0,
>          "active_memory" : {
>             "bytes" : 0,
>             "human_readable" : "0 bytes"
>          },
>          "chunk_size" : 4096,
>          "free_blocks" : 3,
>          "offset" : 4048,
>          "spare_memory" : {
>             "bytes" : 12288,
>             "human_readable" : "12.0 KB"
>          }
>       },
>       "peak_active_client_count" : 1,
>       "pid" : 32287,
>       "request_begin_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.07000000000000001
>          }
>       },
>       "server_state" : "ACTIVE",
>       "total_bytes_consumed" : 2695,
>       "total_clients_accepted" : 2,
>       "total_requests_begun" : 2,
>       "turbocaching" : {
>          "fetches" : 0,
>          "hit_ratio" : null,
>          "hits" : 0,
>          "store_success_ratio" : null,
>          "store_successes" : 0,
>          "stores" : 0
>       }
>    },
>    "thread6" : {
>       "active_client_count" : 0,
>       "active_clients" : {},
>       "client_accept_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.090
>          }
>       },
>       "disconnected_client_count" : 0,
>       "disconnected_clients" : {},
>       "free_client_count" : 128,
>       "free_request_count" : 1,
>       "mbuf_pool" : {
>          "active_blocks" : 0,
>          "active_memory" : {
>             "bytes" : 0,
>             "human_readable" : "0 bytes"
>          },
>          "chunk_size" : 4096,
>          "free_blocks" : 2,
>          "offset" : 4048,
>          "spare_memory" : {
>             "bytes" : 8192,
>             "human_readable" : "8.0 KB"
>          }
>       },
>       "peak_active_client_count" : 1,
>       "pid" : 32287,
>       "request_begin_speed" : {
>          "1h" : {
>             "averaged_over" : "1 hour",
>             "per" : "minute",
>             "value" : 0.090
>          },
>          "1m" : {
>             "averaged_over" : "1 minute",
>             "per" : "minute",
>             "value" : 0.090
>          }
>       },
>       "server_state" : "ACTIVE",
>       "total_bytes_consumed" : 2846,
>       "total_clients_accepted" : 2,
>       "total_requests_begun" : 2,
>       "turbocaching" : {
>          "fetches" : 0,
>          "hit_ratio" : null,
>          "hits" : 0,
>          "store_success_ratio" : null,
>          "store_successes" : 0,
>          "stores" : 0
>       }
>    },
>    "threads" : 6
> }
> 

The 2.2.2 Ruby / 4.2.3 Rails app runs fine in development mode, but it runs slow in production. Maybe it has to do with this app specifics, that is a Multiple DB Connections. I had set the Multiple DB Connections according to the [Rails Multi-Database Best Practices Roundup](http://technology.customink.com/blog/2015/06/22/rails-multi-database-best-practices-roundup/)

This is my **database.yml**:
> production:
>   adapter: postgresql
>   database: app_db
>   username: user
>   password: pass 
> user_database_production:
>   adapter: postgresql
>   database: users_db
>   username: user
>   password: pass 

And my **ApplicationController**:

> class ApplicationController < ActionController::Base
> 
>   around_filter :cache_other_db_connections
> 
>   private
> 
>   def cache_other_db_connections
>     UserBase.connection.cache { yield }
>   end
> 
> end

Please, advice.

**Comment by OnixGH** [comment]
Thanks for the info. How many requests did you send to the 2.2.2 app. during this log?

Unfortunately it's not really clear what is going on. If you could set the log level to 7 and show us the result from that (restart + few requests) it might give some hints. It would also help to have your full configuration, right now it doesn't even show you configured 2 apps for example.

**Comment by DanTaiko** [comment]
You're really fast with reply. Thanks.

Since the time of my first post I had re-installed the Passenger + Nginx according to your instructions.
But the situation doesn't change at all.

See my NGINX configs below:

**passenger.conf**
> passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
> passenger_ruby /usr/bin/passenger_free_ruby;
> passenger_log_file /u/apps/passenger.log;
> passenger_pool_idle_time 0;
> passenger_max_preloader_idle_time 0;
> passenger_force_max_concurrent_requests_per_process 0;
> passenger_log_level 7;

**ruby193app.conf**
> server {
>     listen 80;
>     server_name  "~^(?<site>\w+)\.example\.ru$";
>     rewrite ^ https://$site.example.ru$request_uri? permanent;
> }
> server {
>     listen 443 ssl;
>     server_name ruby193app.example.ru;
>     ssl_certificate     /home/webadmin/ssl/example.chained.crt;
>     ssl_certificate_key /home/webadmin/ssl/example.key;
>     error_log /u/apps/ruby193app/shared/log/nginx.error.log;
>     access_log /u/apps/ruby193app/shared/log/nginx.access.log; #charset koi8-r;
>     root /u/apps/ruby193app/current/public;
>     passenger_enabled on;
>     passenger_ruby /home/webadmin/.rvm/gems/ruby-1.9.3-p551/wrappers/ruby;
> }

**ruby222app.conf**
> server {
>     listen 443 ssl;
>     server_name ruby222app.example.ru;
>     ssl_certificate     /home/webadmin/ssl/example.chained.crt;
>     ssl_certificate_key /home/webadmin/ssl/example.key;
>     error_log /u/apps/ruby222app/shared/log/nginx.error.log;
>     access_log /u/apps/ruby222app/shared/log/nginx.access.log; #charset koi8-r;
>     root /u/apps/ruby222app/current/public;
>     passenger_enabled on;
>     passenger_ruby /home/webadmin/.rvm/gems/ruby-2.2.2@ruby222app/wrappers/ruby;
> }

Please, see the Passenger log (restart + few requests) in my next port.
Thanks in advance.

**Comment by DanTaiko** [comment]
[passenger.log.txt](https://github.com/phusion/passenger/files/442243/passenger.log.txt)

**Comment by OnixGH** [comment]
Your log contains 2x message about long-running, both times you can find before it:
`[ 2016-08-29 13:18:33.0226 6481/7f924a1fc700 age/Cor/App/Gro/SpawningAndRestarting.cpp:303 ]: Restarting group /u/apps/ruby222app/current/public`

Are you sure you are not using a `restart.txt` or restart signal?

**Comment by DanTaiko** [comment]
Thanks for help.

To my shame I found the 'always_restart.txt' in the 'tmp/sockets/'.
:-(

After deleting it the app runs fine.

**Comment by ip2k** [comment]
In case anyone else has trouble with this on AWS, ELB also has a default idle timeout of 60 seconds:
![image](https://cloud.githubusercontent.com/assets/401146/20547509/588bcc26-b0d1-11e6-88b8-41f5b6e0b777.png)

This was the problem we were having.

**Comment by tboyko** [comment]
@ip2k Would you mind elaborating on the issue you had with AWS and how you resolved it?
