### ISSUE TITLE
Compiling PassengerAgent on Alpine Linux / musl libc fails

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1870]
Currently (5.0.30) compiling the Passenger Agent on Alpine Linux fails, because the source code assumes that running on linux means glibc is used so the check for `LIBC_HAS_BACKTRACE_FUNC` wrongly detect backtrace support on musl, which then fails because `execinfo.h` does not exist.

A possible solution could be to check for the `__GNU_LIBRARY__` macro instead of `__linux__` when setting the `LIBC_HAS_BACKTRACE_FUNC` define in [src/agent/Shared/Base.cpp:51](https://github.com/phusion/passenger/blob/727cb50fd31cac199ff88395c9f45175d1422f17/src/agent/Shared/Base.cpp#L51).

Way to reproduce with docker:

```sh
docker run --rm -it alpine:3.4 /bin/sh
apk update
apk add ruby ruby-irb ruby-rake ruby-dev build-base linux-headers curl curl-dev pcre-dev
gem install --no-document passenger
passenger-config install-standalone-runtime --auto
# Compilation fails with:
src/agent/Shared/Base.cpp:55:23: fatal error: execinfo.h: No such file or directory
```

I'm currently working around the issue with the following hack:

```
echo "#undef LIBC_HAS_BACKTRACE_FUNC" > /usr/include/execinfo.h
```

**Comment by FooBarWidget** [comment]
Looks good to me. @CamJN can you make the change?

**Comment by nikolay** [comment]
@FooBarWidget Should we use the workaround above for the time being?

**Comment by FooBarWidget** [comment]
Yes the workaround is fine.

**Comment by nikolay** [comment]
@FooBarWidget Unfortunately, it didn't work for me due to `libcurl` issue. The only thing that works for me is actually by using the `edge` repository (v3.5), which has `libexecinfo` in it:

```Bash
echo "http://alpine.gliderlabs.com/alpine/edge/main" > /etc/apk/repositories
```

**Comment by nikolay** [comment]
Here's the package info: http://pkgs.alpinelinux.org/package/edge/main/x86_64/libexecinfo

**Comment by felixbuenemann** [comment]
@nikolay What do mean with "libcurl issue"?

**Comment by nikolay** [comment]
@felixbuenemann The issue is that the prerequisites check of Passenger failed for `libcurl`. Let me try your Dockerfile. Maybe the issue is that I used `FROM ruby:alpine` instead of using the base Alpine Linux image.

**Comment by felixbuenemann** [comment]
You are likely missing the curl-dev package.

**Comment by nikolay** [comment]
@felixbuenemann I do have it - it said thought that it is installed, but not usable. I think this Ruby Dockerfile could be used as a base as it's the official one and it still uses `alpine:3.4` as the base.
