### ISSUE TITLE
Version: 5.0.30: passenger-config --root does not return path required by passenger_root

### ISSUE THREAD

**Issue by john-999** [phusion/passenger#1871]
```$ passenger-config --root```

returns ```/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini``` instead of the path I need to determine for ```passenger_root``` in the ```nginx.conf```

    $cat /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
    [locations]
    packaging_method=deb
    bin_dir=/usr/bin
    support_binaries_dir=/usr/lib/passenger/support-binaries
    lib_dir=/usr/lib/passenger
    helper_scripts_dir=/usr/share/passenger/helper-scripts
    resources_dir=/usr/share/passenger
    include_dir=/usr/share/passenger/include
    doc_dir=/usr/share/doc/passenger
    ruby_libdir=/usr/lib/ruby/vendor_ruby
    node_libdir=/usr/share/passenger/node
    apache2_module_path=/usr/lib/apache2/modules/mod_passenger.so
    ruby_extension_source_dir=/usr/share/passenger/ruby_extension_source
    nginx_module_source_dir=/usr/share/passenger/ngx_http_passenger_module

**Comment by FooBarWidget** [comment]
Did you install Passenger through the Debian packages? Then `/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini` *is* the path you need for `passenger_root`.

**Comment by john-999** [comment]
Thank you very much for your speedy help!
