### ISSUE TITLE
Problem running Passenger Standalone on IPv6

### ISSUE THREAD

**Issue by Manfred** [phusion/passenger#1873]
I was trying to start passenger standalone on my Mac (Mac OS 10.11.6) with the following command:

```
sudo passenger start --address ::1 --port 80
```

and it errors out with the following message:

```
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: [emerg] the INET6 sockets are not supported on this platform in "[::1]:80" of the "listen" directive in nginx.conf:79
    nginx: configuration file nginx.conf test failed

This probably means that you have found a bug in Phusion Passenger Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues

In the bug report, please include this error message, as well as the contents of the file /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/passenger-standalone-1iywaq6.log
```

I would expect the server to start, but I guess IPv6 support is not compiled in? I tried using other local IPv6 addresses (e.g. `::` and a full address) but they all have the same result.

This is not a major issue, I was just surprised because I though IPv6 was supported.

---
- open source 5.0.30 standalone
- Mac OS 10.11.6
- Rbenv, RubyGems, no Gemfile
- ruby 2.3.1p112

**Comment by OnixGH** [comment]
Technically it's Nginx that needs to be compiled with ipv6 support, not Passenger. But it's true that we don't add the ipv6 flag in the build (the workaround being to use passenger-install-nginx, choosing option " 2. No: I want to customize my Nginx installation." and adding the `--with-ipv6` flag).

We can have a look at whether to incorporate this by default.

**Comment by FooBarWidget** [comment]
I have no problems with enabling IPv6 by default.

**Comment by OnixGH** [comment]
@FooBarWidget it doesn't work for me either (Ubuntu), not sure what you tested?

**Comment by FooBarWidget** [comment]
With "no problems" I meant "no objections", not "it works".

**Comment by OnixGH** [comment]
Update: nginx (mainline) 1.11.5 removed the `--with-ipv6` flag because it has ipv6 configured by default. So switching to mainline would also take care of this.
