### ISSUE TITLE
Python + Hug: issue with post "content-type: multipart/form-data "

### ISSUE THREAD

**Issue by koolay** [phusion/passenger#1874]
I have a problem that can not get form data.  

**\- first case**
 `hug`  + passager nginx   

**\- second case**
 `hug` + gunicorn + nginx  proxy 

`hug` is a web framework of python.

On the first case, can not get form data, but the second case is ok.
When post with  `application/x-www-form-urlencoded` , everything is ok.

**Comment by CamJN** [comment]
Would it be possible to put together a minimal reproducible test app?

**Comment by OnixGH** [comment]
@koolay we're unable to reproduce this, and it seems you have a working solution. Closing for now, we can reopen if you have an example.
