### ISSUE TITLE
Meteor Deploy giving error on Websocket connection

### ISSUE THREAD

**Issue by mariohmol** [phusion/passenger#1876]
Hi,

have a meteor projec, i'm trying to deploy and getting this error:

```
3205508….js?meteor_js_resource=true:57 WebSocket connection to 'ws://app.brigadistacivil.com.br/sockjs/361/ahglfyhe/websocket' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1
 ```

Here is more info: https://github.com/meteor/meteor/issues/7802

Thanks

**Comment by OnixGH** [comment]
From your config it appears you are using the Apache integration mode. This [will not work](https://github.com/phusion/passenger/issues/1202) reliably. You can use either the standalone (Nginx) mode or run Passenger [as a reverse proxy behind Apache](https://www.phusionpassenger.com/library/deploy/standalone/reverse_proxy.html).

Also, 4.0.19 is very old, the latest version is 5.0.30 which has a number of fixes for security issues as well as websockets.

**Comment by mariohmol** [comment]
As Meteor just work with websockets, shouldnt this docs be deleted?

https://www.phusionpassenger.com/library/deploy/apache/deploy/meteor/

Lost some days researching something that do not work.. but official docs says that works..

**Comment by OnixGH** [comment]
We have a warning up in the Passenger + Apache installation [walkthrough](https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/ownserver/integration_mode.html), which you should encounter before getting to the doc you mentioned.

Nevertheless it is a good point, we're in the process of updating the Meteor-specific docs anyway and we'll look into this part as well. I [created an issue](https://github.com/phusion/passenger_library/issues/53) on the passenger library tracker.

**Comment by mariohmol** [comment]
Some updates:

I had problem making this work on `apache2.2` because of wstunnel is not supported, just by `apache2.4` . 

If you use passanger standalone works but if is a new meteor project with ionic2, you have to call the `gulp build` and copy `www/` folder to a `public/` folder inside the `api/` folder. 

Here is a link with a example project: https://github.com/mariohmol/brigadistas
