### ISSUE TITLE
Phusion Passenger doesnt' start - some permission error

### ISSUE THREAD

**Issue by zedherle** [phusion/passenger#1885]
Hi Team, 

We are having this repetitive issue with passenger. 
bewotsrvadmin@btsrv5:~$ passenger -v
Phusion Passenger 5.0.30

1. We were installing redmine from the below link 
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_25x_on_Ubuntu_1404_with_Apache2_Phusion_Passenger_MySQL_and_Subversion

2. All steps were followed as is and could launch the site too.. However after two days, after the apache restart - passenger does not come up at all. 

I checked it in apache2 error log
bewotsrvadmin@btsrv5:/var/log/apache2$ tail -100 error.log
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  /usr/share/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

[ 2016-10-24 11:51:01.7230 15169/7ffb4f7fe700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 678bf4c1. Please see earlier logs for details about the error.
App 15281 stdout:
App 15281 stderr:  [passenger_native_support.so] trying to compile for the current user (www-data) and Ruby interpreter...
App 15281 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 15281 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
App 15281 stderr:      /tmp/passenger_native_support-1g9l5xf.log
App 15281 stderr:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 15281 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 15281 stderr:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 15281 stderr:      Trying next mirror...
App 15281 stderr:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.30/rubyext-ruby-2.3.1-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 15281 stderr:  [passenger_native_support.so] will not be used (can't compile or download)
App 15281 stderr:   --> Passenger will still operate normally.
App 15281 stderr: /var/lib/gems/2.3.0/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: key "inodot" is duplicated and overwritten on line 466
App 15281 stdout:
[ 2016-10-24 11:51:46.6431 15169/7ffb543f1700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /usr/share/redmine: An error occurred while starting up the preloader.
  Error ID: 96e030cc
  Error details saved to: /tmp/passenger-error-FTMFVM.html
  Message from application: (<unknown>): did not find expected key while parsing a block mapping at line 68 column 2 (Psych::SyntaxError)
  /var/lib/gems/2.3.0/gems/psych-2.1.1/lib/psych.rb:379:in `parse'
  /var/lib/gems/2.3.0/gems/psych-2.1.1/lib/psych.rb:379:in `parse_stream'
  /var/lib/gems/2.3.0/gems/psych-2.1.1/lib/psych.rb:327:in `parse'
  /var/lib/gems/2.3.0/gems/psych-2.1.1/lib/psych.rb:254:in `load'
  /usr/share/redmine/lib/redmine/configuration.rb:86:in `load_from_yaml'
  /usr/share/redmine/lib/redmine/configuration.rb:42:in `load'
  /usr/share/redmine/lib/redmine/configuration.rb:67:in `[]'
  /usr/share/redmine/lib/redmine/thumbnail.rb:25:in `<module:Thumbnail>'
  /usr/share/redmine/lib/redmine/thumbnail.rb:22:in `<module:Redmine>'
  /usr/share/redmine/lib/redmine/thumbnail.rb:21:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  /usr/share/redmine/lib/redmine.rb:48:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  /usr/share/redmine/config/initializers/30-redmine.rb:6:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  /usr/share/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

[ 2016-10-24 11:51:46.6491 15169/7ffb4effd700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 96e030cc. Please see earlier logs for details about the error.

4. And from the passenger log

# current user is: www-data
# mkdir -p /var/www/.passenger/native_support/5.0.30/ruby-2.3.1-x86_64-linux
Encountered permission error, but no more directories to try. Giving up.

Please help me to resolve this issue.

**Comment by OnixGH** [comment]
This doesn't appear to be a problem with Passenger. It starts fine, but reports the application has trouble starting:

```
[ 2016-10-24 11:51:01.7230 15169/7ffb4f7fe700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. 
```

The reason is:
```
Message from application: (): did not find expected key while parsing a block mapping at line 68 column 2 (Psych::SyntaxError)
```

The error about native support is not related to this and can be ignored, as Passenger says:
```
App 15281 stderr: [passenger_native_support.so] will not be used (can't compile or download)
App 15281 stderr: --> Passenger will still operate normally.
```

**Comment by OnixGH** [comment]
You can try posting to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for help with your configuration (we recommend posting your full config to avoid wasting time with guessing).

**Comment by luizhenriquesoares** [comment]
Some solution to resolve this problem ?
