### ISSUE TITLE
Standalone - option parsing issue with empty environment variables

### ISSUE THREAD

**Issue by OscarBarrett** [phusion/passenger#1886]
When an empty environment variable is used as an argument to a command line option, Passenger doesn't always throw an error - if another option follows the empty variable, the following argument may used for the previous option.

Normal behaviour:
```bash
$ unset ENV
$ bundle exec passenger start -p 3000 -e $ENV
*** ERROR: missing argument: -e
Usage: passenger start [DIRECTORY] [OPTIONS]
...
```

When another option follows the empty variable:
```bash
$ unset ENV
$ bundle exec passenger start -p 3000 -e $ENV --max-pool-size 5
 --> Downloading a Phusion Passenger agent binary for your platform

 --> Installing Nginx 1.10.1 engine

--------------------------

 [passenger_native_support.so] trying to compile for the current user (root) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Compilation successful. The logs are here:
     /tmp/passenger_native_support-1yjixln.log
 [passenger_native_support.so] successfully loaded.
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: the configuration file nginx.conf syntax is ok
    nginx: [emerg] open() "/app/5/passenger.3000.pid" failed (2: No such file or directory)
    nginx: configuration file nginx.conf test failed
...
```

Passenger version: open source 5.0.30 standalone
[Simple example](https://github.com/OscarBarrett/passenger-env-test) (tested with Docker 1.12.1, image ruby:2.3 - Linux 4.4.20-moby, x86_64 GNU/Linux)

**Comment by FooBarWidget** [comment]
This is not a bug, this is how Unix software is supposed to behave. If you pass $SOMETHING to a command then bash will skip that argument altogether when it is empty. The best way to solve this problem is to detect the empty environment variable before calling Passenger, or to make sure the environment variable is not empty, like this:

    passenger start -e ${ENV:-development} --something-else

This makes $ENV default to 'development' when empty.
