### ISSUE TITLE
Passenger support-binaries nginx-1.10.1 issue

### ISSUE THREAD

**Issue by JamesYuan** [phusion/passenger#1888]
I have tried everything I can checked, but no luck.

OS is Ubuntu 14.04.5 LTS and ensure it is the latest libs etc. But I still got the following issue. I think is should be a panssenger issue because " /usr/lib/passenger/support-binaries".

root@iZm5e7yehfzdrkr13qxblqZ:/var/www/portal/current/public# passenger start
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    /usr/lib/passenger/support-binaries/nginx-1.10.1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/passenger/support-binaries/nginx-1.10.1)
    /usr/lib/passenger/support-binaries/nginx-1.10.1: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/passenger/support-binaries/nginx-1.10.1)
    /usr/lib/passenger/support-binaries/nginx-1.10.1: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/passenger/support-binaries/nginx-1.10.1)
    /usr/lib/passenger/support-binaries/nginx-1.10.1: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/passenger/support-binaries/nginx-1.10.1)
    /usr/lib/passenger/support-binaries/nginx-1.10.1: /lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/passenger/support-binaries/nginx-1.10.1)

This probably means that you have found a bug in Phusion Passenger Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues

In the bug report, please include this error message, as well as the contents of the file /tmp/passenger-standalone-1pk25lp.log

Thanks,
James.

**Comment by OnixGH** [comment]
As the error message says: "In the bug report, please include this error message, as well as the contents of the file /tmp/passenger-standalone-1pk25lp.log".

Can you supply this? We can't conclude anything from this error message by itself.

**Comment by OnixGH** [comment]
Also, you skipped some questions when you opened the issue, can you please fill in the missing information?

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:

**Question 7: Anything else about your setup that we should know?**

Your answer:

**Comment by JamesYuan** [comment]
Thank you feedback.
Please check the attached file.
[passenger-standalone-1pk251p.tar.gz](https://github.com/phusion/passenger/files/588133/passenger-standalone-1pk251p.tar.gz)

Question 2: Passenger version and integration mode:

For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx
Your answer: Phusion Passenger 5.0.30/nginx

Question 4: Passenger installation method:

Your answer:
[ ] RubyGems + Gemfile

Question 5: Your app's programming language (including any version managers) and framework (including versions):

For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4
Your answer: ruby 2.2.1p85, RVM, Rails 4.2.7, Node.js v0.10.25 with no Express.

Question 6: Are you using a PaaS and/or containerization? If so which one?

For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker
Your answer: No, just a Linux VM. Ubuntu 14.04.5 LTS.

`uname -a':
Linux iZm5e7yehfzdrkr13qxblqZ 3.13.0-101-generic #148-Ubuntu SMP Thu Oct 20 22:08:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Question 7: Anything else about your setup that we should know?

Your answer: 

###########My steps begin##################
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7

sudo apt-get install -y apt-transport-https ca-certificates

# Add our APT repository
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main > /etc/apt/sources.list.d/passenger.list'

sudo apt-get update

# Install Passenger + Nginx
sudo apt-get install -y nginx-extras passenger

sudo service nginx start
sudo service nginx stop
sudo service nginx restart

# edit /etc/nginx/nginx.conf and comment out
include /etc/nginx/passenger.conf;

# edit /etc/nginx/nginx.conf and add in the first line
env PATH;

# new /etc/nginx/sites-enabled/your_project_name.conf
server {
  listen 80;
  server_name MY_VM_IP;

  root /var/www/portal/current/public;
  passenger_enabled on;

  passenger_min_instances 1;

  location ~ ^/assets/ {
    expires 1y;
    add_header Cache-Control public;
    add_header ETag "";
    break;
   }
}

#
sudo service nginx restart
###########My steps end##################


Thanks for your help.
James.

**Comment by OnixGH** [comment]
You said you installed passenger via:
[ ] RubyGems + Gemfile

But your commands says you installed via APT:
sudo apt-get install -y nginx-extras passenger

That means that you need to check if you installed from the correct APT repository:
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger **xenial** main > /etc/apt/sources.list.d/passenger.list'

And that's wrong: you wrote you're on Ubuntu 14.04 Trusty, but you used the repository for Ubuntu 16.04 Xenial instead. You should uninstall Passenger, use the correct repo, and reinstall.

**Comment by JamesYuan** [comment]
yes, you are right. I didn't notice that the specific version that just copied from other's guide.

thank you.
James.
