### ISSUE TITLE
Debian package download policy?

### ISSUE THREAD

**Issue by mk-pmb** [phusion/passenger#1889]
## Issue report

**Are you sure this is a bug in Passenger?**

It's more about policy than about the software, but I don't agree to the Google Groups ToS so I hope it fits here, too.

**Question 1: What is the problem?**

I'm trying to set up a local mirror of the Debian package repo, so I can install Passenger independent from network uplink, PackageCloud maintenance etc.

> - What is the expected behavior?

  * Mirror bot: downloads lots of files.
  * robots.txt: either no exclusions, or with annotations telling me where I can read about the download policy.
  * passenger library search for "packagecloud": finds download policy
  * passenger library search for "robots": finds download policy

> - What is the actual behavior?

  * Mirror bot reports that robots.txt says I'm not allowed to.
  * robots.txt: denies all bots, with no explanation at all.
  * passenger library search for "packagecloud": no download policy hints
  * passenger library search for "robots": no download policy hints

> - How can we reproduce it?

Visit https://oss-binaries.phusionpassenger.com/robots.txt

**Question 2: Passenger version and integration mode**:

I'd like to use the latest open source deb package with Ubuntu's latest nginx.

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 14.04.5 LTS trusty i686

**Question 4: Passenger installation method**:
[x] Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
unrelated

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No.

**Question 7: Anything else about your setup that we should know?**

**Comment by FooBarWidget** [comment]
The robots.txt is there to prevent the site from being indexed by search engines. We don't want users to find oss-binaries.phusionpassenger.com directly and download random files there and getting confused; we want them to go through the proper documentation so that they don't end up downloading the wrong thing or installing things wrong. The robots.txt is not there to prevent things like mirroring tools, and until today I didn't even think those tools respect robots.txt.

**Comment by mk-pmb** [comment]
Thanks! I can indeed configure my mirror tool to ignore it. Would be nice if some hint (e.g. link to this issue) could be added to the robots.txt.
