### ISSUE TITLE
Add support for Crystal language

### ISSUE THREAD

**Issue by igorkasyanchuk** [phusion/passenger#1894]
Not sure if possible, but do you plan to add in near future support for Crystal language https://crystal-lang.org/? It has many web frameworks.

It can significantly increase popularity of this language. Many people from Ruby world can use it for high-performance apps.

Thanks

**Comment by CamJN** [comment]
Thanks for the suggestion, it looks like Crystal compiles to native binaries. In which case we're working on a feature that may allow you to use Crystal inside Passenger. We'll also keep an eye on Crystal and add more support at some later time.
