### ISSUE TITLE
Nginx 1.10.2 RPM overrides Passenger Nginx in CentOS 7 / RHEL 7 package update

### ISSUE THREAD

**Issue by OnixGH** [phusion/passenger#1895]
Since Nov 21th, EPEL has the following packages:

nginx = 1:1.10.2-1.el7
nginx-filesystem = 1:1.10.2-1.el7

These override the nginx packages from the Passenger repo:

nginx = 1:nginx-1.10.1-8.p5.0.30.el7.x86_64
nginx-filesystem = 1:nginx-filesystem-1.10.1-8.p5.0.30.el7.noarch

The override occurs because the CentOS 7 / RHEL 7 packages have increased the epoch number to 1 (compared to CentOS 6 / RHEL 6), so that the epoch number in the [Passenger package](https://github.com/phusion/passenger_rpm_automation/blob/master/specs/nginx/nginx.spec.erb#L37) is no longer larger.

The solution would be to increase the epoch number in the next release, probably best to set it much higher to avoid this issue in the future.

One workaround for 5.0.30 is to lock to the Passenger repo-provided version:

```
# remove the 1.10.2 upgrade (root or sudo)
yum remove nginx nginx-filesystem

# to enable version locking
yum -y install yum-plugin-versionlock

# lock
yum versionlock add 1:nginx-1.10.1-8.p5.0.30.el7.*
yum versionlock add 1:nginx-filesystem-1.10.1-8.p5.0.30.el7.*

# install versionlocked (from passenger repo)
yum -y install nginx

#Installed:
#  nginx.x86_64 1:1.10.1-8.p5.0.30.el7
#Dependency Installed:
#  nginx-filesystem.noarch 1:1.10.1-8.p5.0.30.el7
```

To fully undo the workaround:

```
# yum versionlock list can be used for listing
yum versionlock delete nginx nginx-filesystem

yum update

yum remove yum-plugin-versionlock
```

**Comment by jmaitrehenry** [comment]
I just test the workarround and it should be (centos7 with passenger enterprise repo `baseurl=https:/[user:pass@]www.phusionpassenger.com/enterprise_yum/el/$releasever/$basearch`)
```
yum versionlock add 1:nginx-1.10.1-9.p5.0.30.el7.*
yum versionlock add 1:nginx-filesystem-1.10.1-9.p5.0.30.el7.*
```

(1.10.1-9 not 1.10.1-8)

**Comment by OnixGH** [comment]
Thanks for the addition concerning Enterprise @jmaitrehenry.

**Comment by milleroff** [comment]
Had today the same problem.

Fixed it by adding to

> vim /etc/yum.repos.d/epel.repo

the following statement:

> exclude=nginx*

so it looks like:

> [epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
exclude=nginx*
