### ISSUE TITLE
Disabling colorized output

### ISSUE THREAD

**Issue by vad1m** [phusion/passenger#1902]
I don't see switch to disable color output in ```passenger-install-apache2-module``` command (I installed fresh version 5.0.30 via ```gem install passenger```, my ruby version is 2.2.5). By default with commandline ```$ passenger-install-apache2-module --auto --languages ruby``` it produces colorized output, no matter if it's a interactive session or cloud init script (I see colorized logs in second case, which corrupting all further output from other commands). Please add switch ```--no-colors``` or disable color output by default. Thanks in advance!

**Comment by FooBarWidget** [comment]
It will disable colors automatically if you stdout isn't a TTY. For example this automatically disables colors:

    passenger-install-apache2-module --auto --languages ruby | cat

**Comment by vad1m** [comment]
hm, I've tried your example from my shell, and I have colors anyway.

```$ passenger-install-apache2-module --auto --languages=ruby | cat```
I don't think that cloud init make something special, this is the first tool which forces color output. It's also strange that you have explicit swith to force color output, but don't have explicit switch to disable colors.

Can you check one more time this ticket?

**Comment by FooBarWidget** [comment]
All right, I have opened this ticket. This might be something specific to your system.

During the creation of [a new issue](https://github.com/phusion/passenger/issues/new), you were supplied a standard form that asks you a bunch of questions, which as which OS you are running. Can you fill in that form?

**Comment by vad1m** [comment]
Sure, please find it below:

**Question 1: What is the problem?**
Expected:
```$ passenger-install-apache2-module --auto --languages=ruby```
output without colors when TTY is not used
Achieved:
I have colorized output with any configuration -- running command inside script, inside cloud init script, or even in TTY using pipeline (```$ passenger-install-apache2-module --auto --languages=ruby | cat```).

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

opensource 5.0.30/apache2

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Amazon Linux AMI release 2016.09, x86_64

**Question 4: Passenger installation method**:

[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
tried both options

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.2.5

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

no

**Question 7: Anything else about your setup that we should know?**

Nothing special

**Comment by vad1m** [comment]
hi guys, any news on that issue ? Looking forward for your fix!

**Comment by FooBarWidget** [comment]
No update as of yet. We have a lot of things on our todo list; for example we've been preparing for the 5.1.0 release for 2 weeks now because CentOS, macOS and RHEL broke things in the past month so we had to give those issues our full attention. After the 5.1.0 release there are various other tasks that we need to work on. We'll get to your issue eventually but I can't give you an estimate of when that will be.

**Comment by CamJN** [comment]
I can confirm though that I see the colour even when piping through cat, so when we get to this we will be able to reproduce the issue which speeds up finding a fix.

**Comment by CamJN** [comment]
in the meantime you could try piping through `sed -r s/\x1b\[[^@-~]*[@-~]//g` which _should_ remove all escape codes.

**Comment by jbeima** [comment]
@FooBarWidget : I opened ticket #1900, in regards to Passenger crashing being broken on Fedora. Where over the last month Passenger was broken and crashing on Fedora. Fedora IS RedHat, your team acted like they were unaware of that. "DNF" is replacing "YUM". If your already doing a fix compile for Cent & RHEL, why not do a release for Fedora or at least help us to get it fixed.

**Comment by FooBarWidget** [comment]
@jbeima Thank you for your feedback with regard to #1900. In order to keep the issue tracker clean, please confine discussions inside the relevant ticket. The current ticket, 1902, should be related to "Disabling colorized output" only.

**Comment by jbeima** [comment]
@Hongli

You commented on RedHat/Cent breaking Passenger, I was simply letting you know they broke Fedora as well. :) Since they all go hand in hand.
