### ISSUE TITLE
Dedicated gem for deployment operations (e.g. restart)

### ISSUE THREAD

**Issue by ioquatix** [phusion/passenger#1906]
It would be really nice to have a gem for restarting passenger websites without building any native extensions. Perhaps, a gem called `passenger-control`.

In my mind, `passenger-control` would be a gem which can, initially, restart a website, almost identical to `passenger-config`.

The difference would be:

- Gem doesn't compile any native dependencies.
- Works with multiple versions of passenger correctly.
- Can silently ignore when passenger is not running, and/or print a warning, by default.

The main reason, is to simplify the deployment of websites to a server using passenger, without having to know what version of passenger is installed or operating (within reason), and to track this dependency as a gem. Ideally, you'd also provide an api, e.g.

```ruby

require 'passenger/control`

Passenger::Control.restart(dir, ignore_not_running: true)

```

This would simplify scripting interactions with Passenger.

The usage would be something like this

In your `website/Gemfile`:

```ruby
group :production do
    gem "passenger-control"
end
```

In `website/tasks/deploy.rake`

```ruby

task :deploy do
    require 'passenger/control'
    Passenger::Control.restart(File.dirname(__dir__), ignore_not_running: true)
end
```

Other things that could be useful, would be programmatic APIs for the memory usage, and other things like that.

Thanks

**Comment by ioquatix** [comment]
I personally don't mind having a go at implementing this, provided someone can point me at the right API to use. Is there a RPC API for this?

**Comment by CamJN** [comment]
Hi @ioquatix thanks for the suggestion. There's currently no public API for such things. Could you describe the pain-points you've experienced with passenger-config, so we can better understand where you're coming from?

Thanks.

**Comment by CamJN** [comment]
You may also be interested in `passenger-config restart-app --ignore-app-not-running`

**Comment by ioquatix** [comment]
Yes, so that's what we are currently using `passenger-config restart-app --ignore-app-not-running`. But `passenger-config` isn't in $PATH by default when deploying via git post-receive hook. That's because it lives inside `/usr/lib/passenger/bin`.

So, to be more explicit, we have:

```ruby
group :production do
    gem "passenger", "= $VERSION_ON_SERVER"
end
```

This allows us to do, essentially, `bundle exec passenger-config ...`. It's modelled explicitly in the gem file that production depends on passenger.. so that when we want to restart we know this will never fail (unless something is horrendously wrong with the server).

There is really only one problem with this approach. The version of passenger in the Gemfile should match exactly the version installed on the server. For simple tasks such as "restart" this seems irrelevant to a certain extent. It also means that we can't deploy the same code to a test server with a different version of passenger, for example. Or, we can, but we just risk that the command will fail because of version incompatibilities.

The second issue, is a nice to have: the ability to invoke the functionality without invoking the shell. There is less chance of things going wrong, easier handling of failure cases, etc.

So, my idea is to provide a command/api which works independently of Passenger. It could use semantic versioning for compatibility, or even work across multiple versions, e.g. `gem "passenger-control", "~> 5.0"` would be acceptable, but `gem "passenger-control"` which works for as many versions of passenger as possible would be awesome.

**Comment by CamJN** [comment]
Thanks for the clarification.

**Comment by ioquatix** [comment]
The other option is that we simply revert back to `touch tmp/restart.txt` but that approach seems really crappy. It would be awesome to have more feedback from the deployment process e.g. "Restart this app and let me know if anything has failed" vs "Restart this app in the background". Exposing a high level API would make this possible, e.g.

```ruby
require 'passenger/control'

control = Passenger::Control.new("website-dir")

if control.running?
    control.restart!
end
```

**Comment by ioquatix** [comment]
Sorry, just to add, in an ideal world, we'd have some platform-netural server-neutral task to do things like "restart this web app". So, I'm proposing a gem that is specific to passenger. That's because passenger is the defacto. But, it would be nice to even be generic, e.g. "restart this website, even if it's running webrick, passenger, puma" etc. Although I'm not really interested in this use case, I think it would be a good level of abstraction w.r.t. how the `passenger/control` interface is designed.

**Comment by ioquatix** [comment]
Finally, I don't know if this is a good idea or not. It's just something which is a pain point for us right now, but it might be better handled by modifying $PATH, not using gem "passenger", or something else. I'm still exploring the solution space :)

**Comment by ioquatix** [comment]
Closing in favour of https://github.com/phusion/passenger/issues/2208
