### ISSUE TITLE
Can update Nginx apt-package without necessary update to Passenger apt-package

### ISSUE THREAD

**Issue by knopkodav** [phusion/passenger#1908]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
Spawn a process with preloaded application.

- What is the actual behavior?
Passenger spawn process not started, but the Passenger watchdog, core and ust-router started successfully
/var/log/nginx/error.log contains errors:

```
[ 2016-12-21 21:02:10.6305 10723/7fcb350df7c0 age/Wat/WatchdogMain.cpp:1291 ]: Starting Passenger watchdog...
[ 2016-12-21 21:02:10.6461 10726/7fd0e5c027c0 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-12-21 21:02:10.6462 10726/7fd0e5c027c0 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-12-21 21:02:10.6487 10726/7fd0e5c027c0 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 10726
[ 2016-12-21 21:02:10.6586 10731/7f44ea0dc7c0 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-12-21 21:02:10.6597 10731/7f44ea0dc7c0 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 10731
2016/12/21 21:02:10 [alert] 10722#10722: could not create /tmp/passenger.wREPAja/web_server_info/control_process.pid (2: No such file or directory)
```

```
# ll /tmp/passenger.wREPAja/
total 44
drwxr-xr-x  4 root root  4096 Dec 21 21:02 ./
drwxrwxrwt 12 root root 12288 Dec 21 21:32 ../
drwxr-xr-x  2 root root  4096 Dec 21 21:02 agents.s/
drwx-wx-wt  2 root root  4096 Dec 21 21:02 apps.s/
-rw-r--r--  1 root root     5 Dec 21 21:02 core.pid
-rw-r--r--  1 root root     0 Dec 21 21:02 creation_finalized
-rw-------  1 root root    24 Dec 21 21:02 full_admin_password.txt
-rw-r--r--  1 root root     0 Dec 21 21:02 lock
-rw-r--r--  1 root root   300 Dec 21 21:02 properties.json
-rw-------  1 root root    24 Dec 21 21:02 read_only_admin_password.txt
-rw-r--r--  1 root root     5 Dec 21 21:02 watchdog.pid
```

```
# passenger-status
Version : 5.0.30
Date    : 2016-12-21 21:29:25 +0000
Instance: 4lWqcxNs (nginx/1.10.2 Phusion_Passenger/5.0.30)

----------- General information -----------
Max pool size : 4
App groups    : 0
Processes     : 0
Requests in top-level queue : 0

----------- Application groups -----------
[empty]
```

```
# ps auxf | grep -P '(nginx|Passenger)'
root     10927  0.0  0.0  13180  1856 pts/0    S+   21:31   0:00                          \_ grep --color=auto -P (nginx|Passenger)
root     10722  0.0  0.7 144280 16028 ?        S    21:02   0:00 nginx: master process /usr/sbin/nginx
root     10723  0.0  0.4 446764  8800 ?        Ssl  21:02   0:00  \_ Passenger watchdog
root     10726  0.0  0.4 800272  9608 ?        Sl   21:02   0:00  |   \_ Passenger core
nobody   10731  0.0  0.4 455184  9760 ?        Sl   21:02   0:00  |   \_ Passenger ust-router
www-data 10747  0.0  0.4 145212 10088 ?        S    21:02   0:00  \_ nginx: worker process
www-data 10748  0.0  0.4 145212 10088 ?        S    21:02   0:00  \_ nginx: worker process
```

- How can we reproduce it?
Try the latest (5.1.0) Passenger version on 14.04 LTS installed from the official repository.

**Question 2: Passenger version and integration mode**:
nginx/1.10.2 + Phusion_Passenger/**5.0.30** (which is strange because repository says I should have 5.1.0)
```
# passenger -v
Phusion Passenger 5.0.30
```
```
# apt-cache policy nginx
nginx:
  Installed: 1:1.10.2-8.5.1.0~trusty1
  Candidate: 1:1.10.2-8.5.1.0~trusty1
  Version table:
 *** 1:1.10.2-8.5.1.0~trusty1 0
        500 https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.10.1-8.5.0.30~trusty1 0
        500 https://oss-binaries.phusionpassenger.com/apt/passenger/ trusty/main amd64 Packages
```

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 14.04.5 LTS
```
# uname -a
Linux [stripped] 4.4.0-42-generic #62~14.04.1-Ubuntu SMP Fri Oct 7 23:15:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.3.1, Rails 4.x

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
no

**Question 7: Anything else about your setup that we should know?**
Please ask details in comments.

**Comment by OnixGH** [comment]
It seems like you have multiple versions of Passenger installed, maybe you also have it installed as a gem?

**Comment by ahmadfarahat** [comment]
Hello, 
I have the same issue exactly after updating nginx to 1.10.2

**Comment by OnixGH** [comment]
@ahmadfarahat please post the answers to the questions in the opening post for your system so that we can verify it's the same problem. Do you also have 2 passengers installed?

**Comment by ahmadfarahat** [comment]
I just fixed it after upgrading to Phusion Passenger 5.1.0 and updating the root dir in /etc/nginx/conf.d/passenger.conf to 
`passenger_root /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.1.0;
`

**Comment by OnixGH** [comment]
@ahmadfarahat 

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:

**Question 7: Anything else about your setup that we should know?**

Your answer:

**Comment by cbellanca67** [comment]
I do have the same issue.
I installed passenger as a gem using the following commands:
>gem install passenger
>rvmsudo passenger-install-nginx-module

The symptom is the same described in this thread.
In actual fact my web app is not started by nginx server and a similar error is reported on the /opt/nginx/logs/error.log file 
[alert] 11935#0: could not create /tmp/passenger.NPLTZPM/web_server_info/control_process.pid (2: No such file or directory)

OS: Linux fh-app-server 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
nginx version: nginx/1.10.2
gem passenger version: 5.1.1

I alread uninstalled passengers gems and reinstalled them trying to fix the problem with no luck.

**Comment by knopkodav** [comment]
Sorry for late response, guys.

`apt-get install passenger` solves the problem.
The problem appears when you suddenly update the `nginx` package (e.g. by puppet). APT updates the package without errors, but the `passenger` package has not been updated.

Perhaps, a kind of package dependencies should be written to be sure `nginx` and `passenger` packages has the same version. But I know you're the smart guys has a reason didn't to do it yet :)

This is from my point of view, but perhaps the problem is deeper than it seems.

**Comment by CamJN** [comment]
Ok I'm going to label this as a packaging problem.

**Comment by dduvnjak** [comment]
> `apt-get install passenger` solves the problem.
This didn't help until I rebooted the machine.
