### ISSUE TITLE
--disable-security-update-check ignored

### ISSUE THREAD

**Issue by majgis** [phusion/passenger#1909]
**Question 1: What is the problem?**
- What is the expected behavior?
The `--disable-security-update-check` option prevents the following from being logged:
```
[ 2016-12-21 16:01:23.9719 5377/7f9e0d21f700 age/Cor/SecurityUpdateChecker.h:348 ]: Security update check: no update found (next check in 24 hours)
```

- What is the actual behavior?
The `--disable-security-update-check` option is used and the following is still being logged:
```
[ 2016-12-21 16:01:23.9719 5377/7f9e0d21f700 age/Cor/SecurityUpdateChecker.h:348 ]: Security update check: no update found (next check in 24 hours)
```

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) 

```
passenger start \
  --disable-security-update-check \
  --max-pool-size ${max_processes} \
  --min-instances ${max_processes} \
  --app-type node \
  --startup-file ${start_file} \
  --environment ${environment} \
  --port ${port} \
  --daemonize \
  --user ${user} \
  --static-files-dir ${static_dir} \
  --log-file ${passenger_log_file} \
  --nginx-config-template ${nginx_config_file}
```

**Question 2: Passenger version and integration mode**:
open source 5.1.0 standalone

**Question 3: OS or Linux distro, platform (including version)**:
8.el6.centos.12.3

**Question 4: Passenger installation method**:
source tarball

**Question 5: Your app's programming language (including any version managers) and framework** Node.js v6.9.2 with Express 4.13.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?** 
Internal test server

**Question 7: Anything else about your setup that we should know?**
The `--nginx-config-template` is carried over from the previous passenger version, I'm looking now to see what is different, but I assume it would be unrelated.

**Comment by OnixGH** [comment]
If you are using the pre-refactored config template, then that would be the cause.

This is the refactored one that should carry over the option through includes: `$(passenger-config about resourcesdir)/templates/standalone/config.erb`

**Comment by majgis** [comment]
Thank you, I will give it a try.

**Comment by majgis** [comment]
Updating to the new refactored config template addressed the issue.  Thank you for your help.

Also, kudos on the new config template, it is clean and my customizations fit well into the predefined sections.  It should be easy to automate future updates.
