### ISSUE TITLE
passenger compiling nginx even if not needed

### ISSUE THREAD

**Issue by hadmut** [phusion/passenger#1910]
Hi, 
I just installed the passenger gem on a small ARM computer in order to have it run standalone without a Webserver. 

But when starting /usr/local/bin/passenger, it starts to compile a lot of things and even downloads nginx code.

This is bad and evil. A gem should not, never, download code from unknown sources without asking, especially when the code is not needed.

**Comment by CamJN** [comment]
Passenger Standalone uses an integrated Nginx which must be compiled for your platform. It's fetched over https and is well documented and completely open to inspection in our repo (or in the gem code if you like). Furthermore if you don't want to use Nginx you can use the `--engine builtin` flag.

**Comment by FooBarWidget** [comment]
Having said that, we *should* make Passenger Standalone not compile the Nginx engine if the user is only using the builtin engine.

Also, you can pass `--no-install-runtime` and `--no-compile-runtime` to `passenger start`.
