### ISSUE TITLE
Passenger standalone: system ruby version used

### ISSUE THREAD

**Issue by siegy22** [phusion/passenger#1913]
### My Setup

* Centos 7
* Ruby 2.4.0, using rbenv
* Phusion Passenger 5.1.1
---

Hi there, I ran into an issue when running the passenger standalone from `/etc/rc.local` (as described [here](https://www.phusionpassenger.com/library/deploy/standalone/reverse_proxy.html))

When I navigate to my project folder, I can start passenger using `passenger start --daemonize --port 5000` and it will use the right ruby version. (The ruby version is saved in the `.ruby-version` file). But if I'm using the `/etc/rc.local` script to start passenger, it will use the system ruby 😐 

Here's my `/etc/rc.local`: 
```bash
cd /home/my_user/project
passenger start --daemonize --port 5000 --user my_user
```

I didn't find any help in the troubleshooting guides of passenger :grin:
Keep up the good work 🍻

**Comment by OnixGH** [comment]
Have a look at https://www.phusionpassenger.com/library/config/standalone/reference/#--ruby-ruby

Please use our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for further help with your configuration.

**Comment by siegy22** [comment]
Thanks very much 👍
