### ISSUE TITLE
Unable to download native binaries

### ISSUE THREAD

**Issue by ckorhonen** [phusion/passenger#1918]
**Question 1: What is the problem?**
- What is the expected behavior?

Expect Passenger to start without error messages.

- What is the actual behavior?

Starting Passenger process throws the following error message. Application does not start.

```
14:49:35 web.1                   | [ 2017-02-02 14:49:35.1883 14686/0x70000187a000 age/Cor/App/Implementation.cpp:289 ]: Could not spawn process for application /Users/ckorhonen/Repos/minibar-web: An error occurred while starting up the preloader: it did not write a startup response in time.
14:49:35 web.1                   |   Error ID: 55658c07
14:49:35 web.1                   |   Error details saved to: /var/folders/y_/hm78ky1912qclbflgtjrpjkc0000gn/T//passenger-error-O9dLvy.html
14:49:35 web.1                   |   Message from application: An error occurred while starting up the preloader: it did not write a startup response in time. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
14:49:35 web.1                   | <h2>Raw process output:</h2>
14:49:35 web.1                   | <pre>
14:49:35 web.1                   |  [passenger_native_support.bundle] trying to compile for the current user (ckorhonen) and Ruby interpreter...
14:49:35 web.1                   |      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
14:49:35 web.1                   |      Warning: compilation didn&apos;t succeed. To learn why, read this file:
14:49:35 web.1                   |      /var/folders/y_/hm78ky1912qclbflgtjrpjkc0000gn/T/passenger_native_support-cdq428.log
14:49:35 web.1                   |  [passenger_native_support.bundle] finding downloads for the current Ruby interpreter...
14:49:35 web.1                   |      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
14:49:35 web.1                   |      Could not download https://oss-binaries.phusionpassenger.com/binaries/enterprise-NQLVwRlu10n13/by_release/5.1.2/rubyext-ruby-2.3.3-x86_64-macosx.tar.gz: The requested URL returned error: 404 Not Found
14:49:35 web.1                   |      Trying next mirror...
14:49:35 web.1                   |      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/enterprise-NQLVwRlu10n13/by_release/5.1.2/rubyext-ruby-2.3.3-x86_64-macosx.tar.gz: The requested URL returned error: 403 Forbidden
14:49:35 web.1                   |  [passenger_native_support.bundle] will not be used (can&apos;t compile or download) 
14:49:35 web.1                   |   --&gt; Passenger will still operate normally.
14:49:35 web.1                   | </pre>
```

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Both of the URL's return 4xx's:

https://oss-binaries.phusionpassenger.com/binaries/enterprise-NQLVwRlu10n13/by_release/5.1.2/rubyext-ruby-2.3.3-x86_64-macosx.tar.gz
https://s3.amazonaws.com/phusion-passenger/binaries/enterprise-NQLVwRlu10n13/by_release/5.1.2/rubyext-ruby-2.3.3-x86_64-macosx.tar.gz

**Question 2: Passenger version and integration mode**:
Enterprise 5.1.2 Standalone

**Question 3: OS or Linux distro, platform (including version)**:
 OS X 10.12.3 Sierra, x86_64

**Question 4: Passenger installation method**:
RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
For example: Ruby 2.3.3, RBEnv, Rails 4.2.7.1 

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Heroku, though experiencing this on local dev environment.

**Comment by OnixGH** [comment]
Native support is optional and does not prevent Passenger from starting / working:
> [passenger_native_support.bundle] will not be used (can't compile or download) 14:49:35 web.1                   |   >Passenger will still operate normally.

So this warning message is not related to why your application isn't starting; you should look at the log again to find the error message.
