### ISSUE TITLE
Error when loading passenger

### ISSUE THREAD

**Issue by svergeylen** [phusion/passenger#1919]
From a new install, phusion passenger 5.1.2 cannot start on apache2...

(Rails 5.0.1, Ruby 2.3.0)

In /var/log/apache2/error.log, we can read "Could not spawn process for application /home/openproject/openproject-ce: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger."   Error ID: d7c36934

<pre>App 16601 stderr: 
App 16601 stderr: 
App 16601 stderr: [NOTE]
App 16601 stderr: You may have encountered a bug in the Ruby interpreter or extension libraries.
App 16601 stderr: Bug reports are welcome.
App 16601 stderr: For details: http://www.ruby-lang.org/bugreport.html
App 16601 stderr: 
[ 2017-02-04 15:02:09.7203 12902/7f14a40c6700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/openproject/openproject-ce: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: d7c36934
  Error details saved to: /tmp/passenger-error-6j1ETa.html
  Message from application: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>

Raw process output:

/home/openproject/openproject-ce/app/seeders/random_data/work_package_seeder.rb:84: warning: key :user is duplicated and overwritten on line 87
/home/openproject/openproject-ce/vendor/bundle/ruby/2.3.0/gems/grape-0.17.0/lib/grape/api/helpers.rb:3: [BUG] Segmentation fault at 0x000000003a4c20
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
</pre>

I took a look at https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems but it is quite difficult to understand and nearly impossible to know in which of the 4 cases I am.

I hardcoded the SECRET_KEY_BASE  in config/secret.yml to prevent any isue on that side...
I is then not that issue that is preventing passenger to start up :-( 

On another installation with phusion-passenger 5.1.1 it i working...

**Comment by OnixGH** [comment]
> /home/openproject/openproject-ce/vendor/bundle/ruby/2.3.0/gems/grape-0.17.0/lib/grape/api/helpers.rb:3: [BUG] Segmentation fault at 0x000000003a4c20

This log message shows that your application fails to start because the grape gem crashes. Passenger appears to work fine, and I would guess that the reason the other install works is because it's probably using a different ruby or grape version and/or a different configuration.

Please post to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for further help with your configuration.
