### ISSUE TITLE
--nginx-tarball is still ignored in 5.1.2 (passenger-config install-standalone-runtime)

### ISSUE THREAD

**Issue by Cervajz** [phusion/passenger#1920]
## Issue report

**Question 1: What is the problem?**

Unable to install passenger in standalone mode when path to NGINX binary tarball is provided.

This patch from @OnixGH does not work:

https://github.com/phusion/passenger/commit/632cfc45f6a0a230e6fec1099a775862dbe75696

- What is the expected behavior?

Generally to be able to install passenger **without internet connection** by providing all necessary binaries (agent & nginx). We are deploying to banking environment where there is zero internet connectivity on application servers.

- What is the actual behavior?

`--nginx-tarball` and `--nginx-version` are ignored when used with `passenger-config install-standalone-runtime`

`passenger start` still trying to download the nginx engine/binary.

- How can we reproduce it?

Please use attached zip file. **Turn off your internet connection**. I apologize for using screenshots, but I really tested it without connection (no ssh) and there's no way how to easily copy text from VNC/vbox screen :)

[passenger.zip](https://github.com/phusion/passenger/files/759010/passenger.zip)

### Install Passenger from gem file (with dependencies)

```bash
$ unzip passenger.zip

$ gem install --local --no-doc --no-ri passenger/gems/rack-2.0.1.gem passenger/gems/rake-12.0.0.gem
Successfully installed rack-2.0.1
Successfully installed rake-12.0.0
2 gems installed

$ gem install --local --no-doc --no-ri passenger/gems/passenger-5.1.2.gem
Building native extensions.  This could take a while...
Successfully installed passenger-5.1.2
1 gem installed

$ passenger --version
Phusion Passenger 5.1.2
```

### Install standalone runtime

Parameters taken from `$ passenger-config install-standalone-runtime --help`

There's also a hack with the `file:///root/passenger` to be able to install agent without internet connection. **Absolute path must be specified** - change it based on your current directory - it's the same path where you extracted attached zip file. (Off topic: Is there better way how to provide the agent binary? It feels awkward :) )

```bash
$ passenger-config install-standalone-runtime --url-root file:///root/passenger --nginx-version 1.10.2 --nginx-tarball passenger/5.1.2/nginx-1.10.20-x86_64-linux.tar.gz
```

Output:

![screenshot 2017-02-07 21 53 48](https://cloud.githubusercontent.com/assets/344227/22711034/f503fde0-ed7f-11e6-9d67-e80b39485876.png)

There's no information at all about using provided nginx tarball. Also the nginx binary is missing from within the gem directory:

![screenshot 2017-02-07 22 02 51](https://cloud.githubusercontent.com/assets/344227/22711383/47e259ca-ed81-11e6-8c63-c05196a6501b.png)

### Try to run passenger 

```bash
passenger start
```

Output :

![screenshot 2017-02-07 21 56 33](https://cloud.githubusercontent.com/assets/344227/22711162/7c257466-ed80-11e6-812e-b3daa0b4c250.png)

Now it falls back to compiling nginx from source code.

![screenshot 2017-02-07 21 57 35](https://cloud.githubusercontent.com/assets/344227/22711238/b7324d2c-ed80-11e6-9793-35eb025cde05.png)

### Workaround solution

I found this solution by browsing Passenger's ruby source code:

https://github.com/phusion/passenger/blob/stable-5.1/src/ruby_supportlib/phusion_passenger/config/download_nginx_engine_command.rb

```bash
passenger-config install-standalone-runtime --url-root file:///root/passenger/
passenger-config download-nginx-engine --url-root file:///root/passenger/
```
Then it works, but honestly it does not feel right.

![screenshot 2017-02-07 22 18 43](https://cloud.githubusercontent.com/assets/344227/22711979/6f5a8750-ed83-11e6-807c-fa60d4b327ca.png)

![screenshot 2017-02-07 22 19 26](https://cloud.githubusercontent.com/assets/344227/22711994/8278fbd2-ed83-11e6-805e-69e1d8254943.png)

**Question 2: Passenger version and integration mode**:

open-source 5.1.2 standalone

**Question 3: OS or Linux distro, platform (including version)**:

RHEL 7.3 x86_64 / CentOS 1611 x86_64

**Question 4: Passenger installation method**:

[X] Other, please specify:

Installed from local gems, see above the answer for "How can we reproduce it?"

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.3.1 from Red Hat software collections

```bash
$ whereis ruby
ruby: /opt/rh/rh-ruby23/root/usr/bin/ruby

$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

$ gem --version
2.5.1
```

https://www.softwarecollections.org/en/scls/rhscl/rh-ruby23/

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No

**Question 7: Anything else about your setup that we should know?**

No

**Comment by OnixGH** [comment]
Thanks for the extensive report. Patch https://github.com/phusion/passenger/commit/632cfc45f6a0a230e6fec1099a775862dbe75696 was tested and does work, however, what you are seeing is the effect of a regression caused by a later patch (https://github.com/phusion/passenger/issues/1910).

We discovered this yesterday and are busy fixing it in: https://github.com/phusion/passenger/compare/fix_engine_logic.

The workaround that counters the issue is to specify `--engine nginx`, i.e.:
`passenger-config install-standalone-runtime --engine nginx --nginx-tarball /.... --nginx-version ...`
