### ISSUE TITLE
Apache/macOS Private Keychain Breaks Time Capsule Backups

### ISSUE THREAD

**Issue by jriesen** [phusion/passenger#1922]
## Issue report

**Question 1: What is the problem?**

A few weeks ago, my Mac stopped backing up to the external USB HDD I have attacked to my Apple Time Capsule.  When alerted to the problem, I noticed that I could view the drive normally via Finder, but that Time Machine had 'forgotten' the login to the device.  When I tried to re-add the device as my Time Machine backup, I typed in the device password for the Time Capsule and received the following error:

`Keychain error -25307 occurred while creating a System Keychain entry for the username "Joseph Riesen" and URL "afp://Joseph%20Riesen@Joseph's%20Airport%20Extreme._afpovertcp._tcp.local./Super%20Backup%20Disk".
`

<img width="421" alt="screen shot 2017-02-12 at 11 58 18 am" src="https://cloud.githubusercontent.com/assets/4395377/22865704/8863ba84-f11e-11e6-9a9e-1d1397018b23.png">

After some internet research, I discovered that this appears to be a problem with making a modification to /Library/Preferences/com.apple.security.plist, as the latest version of Passenger now does to make a private keychain (as described at https://blog.phusion.nl/2017/01/24/passenger-5-1-2/).  Apparently this exact same problem was caused back in 2013 by a program called iStat Server when they updated com.apple.security.plist to add a custom keychain -- you can see a discussion thread at https://arstechnica.com/civis/viewtopic.php?t=1225417

According to that thread, the iStat Server team apparently fixed this problem with version 2.21.  (Mind you, this was back in 2013.)  I'm not sure what change they made in their software to resolve the problem.

If I remove the DLDBSearchList and DefaultKeychain sections entirely (leaving SecItemSynchronizable as-is), the problem is resolved.  If _either_ the DLDBSearchList or DefaultKeychain sections are present, the problem reoccurs.  (And yes, I'm deleting both the key and value array elements.)  As such, if I revert my file back to its original form, everything works correctly again:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>SecItemSynchronizable</key>
	<true/>
</dict>
</plist>
```

Naturally, I expect this will break the custom keychain functionality in Passenger, so I consider this a temporary workaround.  Also, the lines are automatically re-added to the file whenever I reboot Apache, causing my next scheduled Time Machine backup to fail. 

**Question 2: Passenger version and integration mode**:

Phusion Passenger 5.1.2 via Homebrew, installed in Apache/2.4.23 (the current built-in version from Apple)

**Question 3: OS or Linux distro, platform (including version)**:

macOS Sierra 10.12.3

**Question 4: Passenger installation method**:

OS X Homebrew

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

I run a Rails development website on this system.  Looks like it's Rails 4.2.7.1 on Ruby 2.3.1p112, but I don't believe this is relevant to the problem.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No.

**Question 7: Anything else about your setup that we should know?**

N/A

Thank you for your help!

**Comment by CamJN** [comment]
Thanks for reporting this and providing a very helpful writeup. I've reproduced the issue locally and am digging into this.

**Comment by kennwilson** [comment]
Came here to post about this very issue but couldn't state it any better than this. 

I'm running the same versions of Mac OS, with Ruby 2.3.3 installed via Homebrew. I'm seeing the same problem with my Time Machine backups (only in my case backing up to OS X Server via SMB) and a possibly related VPN connection issue.

**Comment by CamJN** [comment]
Yes, until I can fix this in Passenger here's a workaround:
```
sudo apachectl stop
sudo defaults delete /Library/Preferences/com.apple.security.plist DLDBSearchList
sudo defaults delete /Library/Preferences/com.apple.security.plist DefaultKeychain
```
Then edit your apache config to include `PassengerDisableSecurityUpdateCheck on`
Then you can start Apache again and not experience this issue. I'm working on fixing this properly, but so far don't have anything reliable to share.

**Comment by kennwilson** [comment]
Perfect, thank you!

**Comment by vFragosop** [comment]
I don't know if this information is helpful, but I accidentally deleted my passenger keychain during a clean up. After that, my whole keychain stopped working and couldn't store any new password. The error message I was getting was: `Keychain "passenger" cannot be found to store "xxxxxxxxx"`.

Creating a `passenger` keychain didn't solve the issue. Resetting all my keychains didn't help either and the only solution was to delete those `com.apple.security.plist` entries as @CamJN replied above.

In my opinion, passenger shouldn't be messing with `DLDBSearchList` and `DefaultKeychain`.

**Comment by kcrawford** [comment]
This also affects other system level functionality including connections to Active Directory and 802.1X networks.  We deploy passenger with puppet so now after each puppet run we have to fix the system's com.apple.security.plist.

**Comment by mhw** [comment]
I ran into this with Passenger running under Nginx, both installed from Homebrew and with Nginx running as a system service (i.e. started as root on system startup). The workaround is the same as in https://github.com/phusion/passenger/issues/1922#issuecomment-280155027, except you need to add `passenger_disable_security_update_check on;` to `/usr/local/etc/nginx/nginx.conf`.

Was really confused about what had caused TimeMachine to stop working until I saw the blog post about the Passenger issue.

For me the keychain error was slightly different too: "Keychain error -25308 occurred while creating a System Keychain entry..." I'm not convinced the -25308 is meaningful though now.

**Comment by timraasveld** [comment]
Nginx users can use @CamJN's fix, but the config param's name is in underscore rather than camelcase.

These are the steps I took for a Homebrew-installed nginx:
```
sudo defaults delete /Library/Preferences/com.apple.security.plist DLDBSearchList
sudo defaults delete /Library/Preferences/com.apple.security.plist DefaultKeychain
sed -i '' $'s/passenger_root/passenger_disable_security_update_check on;\\\n    passenger_root/' /usr/local/etc/nginx/nginx.conf
```

Restarting was unnecessary.
