### ISSUE TITLE
TruffleRuby via rvm is coming!

### ISSUE THREAD

**Issue by ylluminate** [phusion/passenger#1923]
Thought you'd want to be aware of the following as it's fast approaching and very likely will be hugely impactful to everyone in the world of Ruby:
https://github.com/jruby/jruby/issues/3768#issuecomment-279880405

Clearly this is fast approaching and will breath a renaissance into using Ruby and the "benchmark wars."

**Comment by CamJN** [comment]
Thanks for sharing.

**Comment by ylluminate** [comment]
Very welcome. Knew you guys would want to keep this on the radar.
