### ISSUE TITLE
passenger 5.1 on centos 5.3

### ISSUE THREAD

**Issue by naox** [phusion/passenger#1924]
I'm trying to compile passenger 5.1 apache module  on old centos 5.3. 
Passenger 5.0 compiles and works fine. 5.1 does not:

```
src/cxx_supportlib/Crypto.cpp: In member function ‘bool Passenger::Crypto::encryptRSA(unsigned char*, size_t, std::string, unsigned char**, size_t&)’:
src/cxx_supportlib/Crypto.cpp:818:2: error: ‘EVP_PKEY_CTX’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp:818:16: error: ‘ctx’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp:837:44: error: ‘EVP_PKEY_CTX_new’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp:842:37: error: ‘EVP_PKEY_encrypt_init’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp:846:68: error: ‘EVP_PKEY_CTX_set_rsa_padding’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp:873:24: error: ‘EVP_PKEY_CTX_free’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp: In member function ‘bool Passenger::Crypto::verifySignature(std::string, char*, int, std::string)’:
src/cxx_supportlib/Crypto.cpp:907:78: error: ‘EVP_DigestVerifyInit’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp:912:69: error: ‘EVP_DigestVerifyUpdate’ was not declared in this scope
src/cxx_supportlib/Crypto.cpp:917:87: error: ‘EVP_DigestVerifyFinal’ was not declared in this scope
rake aborted!
Command failed with status (1): [/opt/rh/devtoolset-1.1/root/usr/bin/g++ -o buildout/common/libpassenger_common/Crypto.o  -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Isrc/cxx_supportlib/vendor-copy/libuv/include -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -feliminate-unused-debug-symbols -feliminate-unused-debug-types -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -Wno-attributes -ggdb -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -std=gnu++11 -Wno-unused-local-typedefs -DHASH_NAMESPACE="__gnu_cxx" -DHASH_MAP_HEADER="<hash_map>" -DHASH_MAP_CLASS="hash_map" -DHASH_FUN_H="<hash_fun.h>" -c src/cxx_supportlib/Crypto.cpp]
```

Centos 5.3 has openssl 0.9.8 in system libs but I have newer versions available on custom location
Is this problem related to old version of openssl or something else? How can I specify custom openssl location? (so far every try with EXTRA_CFLAGS gave same error).

Maybe there is a way to compile passenger without openssl support? (since I only want it as apache module so I why would it need it?)

**Comment by CamJN** [comment]
Yes, those are Openssl errors, you'll need the development headers and the main library as well. You can provide a custom path to `openssl` by passing in additional flags to the compiler as described here: https://www.phusionpassenger.com/library/install/nginx/customizing_compilation_process.html#adding-additional-compiler-or-linker-flags .

You will also run into problems with the curl that is available on CentOS 5.3, as Passenger 5.1 requires a newer version of curl than Passenger 5.0 did.

**Comment by naox** [comment]
I have new curl compiled with new openssl (on custom location) and passenger recognizes it because I replaced /usr/bin/curl-config with a file from new curl

So far I was not able to use additional flags to point to new openssl version. I'm not convinced these errors are related to openssl since not a single line of compilation output contains "openssl" except for 
```
CC=/opt/rh/devtoolset-1.1/root/usr/bin/gcc CXX=/opt/rh/devtoolset-1.1/root/usr/bin/g++ VERBOSE=1 ./passenger-install-apache2-module 2>&1  |grep openssl -i

* Checking for OpenSSL support for Ruby...
```

If passenger were linking to openssl output should contain somethign about that

```
export EXTRA_CFLAGS=-I/usr/openssl-1.0.2e-fpic/include && export EXTRA_CXXFLAGS=-I/usr/openssl-1.0.2e-fpic/include & export EXTRA_LDFLAGS=-L/usr/openssl-1.0.2e-fpic/lib 
CC=/opt/rh/devtoolset-1.1/root/usr/bin/gcc CXX=/opt/rh/devtoolset-1.1/root/usr/bin/g++ VERBOSE=1 ./passenger-install-apache2-module 
```

same error

**Comment by CamJN** [comment]
The error you posted earlier is saying that symbols are missing; and those symbols are supposed to come from openssl, the fact that they are missing means that the compiler is picking up the old openssl not your new one. You could try adding `-nostdinc` and `-nostdinc++` however the `-I` flag is supposed to take precedence over any standard include paths.

Taking a step back, we don't support CentOS 5.* anymore (see https://www.phusionpassenger.com/library/install/supported_operating_systems_and_languages.html), so it isn't surprising that you experience trouble compiling on that OS.

**Comment by CamJN** [comment]
There is no way to compile Passenger without openssl support as it is used for several internal functions such as the security update checker.
