### ISSUE TITLE
unknown directive "passenger_temp_dir"

### ISSUE THREAD

**Issue by craigcarnell** [phusion/passenger#1929]
## Issue report

**Question 1: What is the problem?**
nginx error log:

/tmp/passenger.V3ivZAU/web_server_info/control_process.pid (13: Permission denied)

So I tried setting passenger_temp_dir to /var/cache/nginx/passenger_temp in nginx.conf in the http section:

```
http {
  passenger_root     /usr/share/ruby/vendor_ruby/phusion_passenger/locations.ini;
  passenger_ruby     /opt/rh/rh-ruby23/root/usr/bin/ruby;
  passenger_temp_dir /var/cache/nginx/passenger_tmp;
```

Error restarting nginx:

```
nginx: [emerg] unknown directive "passenger_temp_dir" in /etc/nginx/nginx.conf:68
```

**Question 2: Passenger version and integration mode**:
nginx with passenger via yum
```
nginx version: nginx/1.10.2
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-pcre --with-pcre-jit --with-google_perftools_module --add-module=/builddir/build/BUILD/nginx-1.10.2/passenger-5.1.2/src/nginx_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'
```

**Question 3: OS or Linux distro, platform (including version)**:
CentOS 7

**Question 4: Passenger installation method**:
[x] Phusion YUM repo

gem list as nginx:
```
*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (1.10.6)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
passenger (5.1.2)
psych (2.0.17)
rack (2.0.1)
rake (10.4.2)
rdoc (4.2.1)
```

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
redmine

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
No

**Comment by FooBarWidget** [comment]
I think you are using Passenger 5. As documented in the [migration notes](https://www.phusionpassenger.com/library/install/nginx/migrating/migrating_from_p4_to_p5.html), `passenger_temp_dir` has been replaced by two config options: `passenger_instance_registry_dir` and `passenger_data_buffer_dir`.

**Comment by craigcarnell** [comment]
@FooBarWidget you are right! thanks

**Comment by craigcarnell** [comment]
@FooBarWidget this works for me however I now see:

```
2017/02/23 10:30:39 [crit] 22795#0: *3 connect() to unix:/var/cache/nginx/passenger-instreg/passenger.eZia7eN/agents.s/core failed (13: Permission denied) while connecting to upstream, client: xxx, server: xxx, request: "GET / HTTP/1.1", upstream: "passenger:unix:/var/cache/nginx/passenger-instreg/passenger.eZia7eN/agents.s/core:", host: "xxx"

```

srw-rw-rw-. 1 root root 0 Feb 23 10:30 /var/cache/nginx/passenger-instreg/passenger.eZia7eN/agents.s/core is being created as root, not nginx user

**Comment by FooBarWidget** [comment]
I think that's an SELinux permission denial. The SELinux policy for Nginx only allows it to connect the default Passenger instance registry dir. But since you customized it, it is up to you to modify the SELinux policy to allow Nginx to connect to your custom directory.

**Comment by craigcarnell** [comment]
@FooBarWidget But my instance isn't able to connect to the default passenger instance registry dir

**Comment by craigcarnell** [comment]
Aha I got it

I've set it to /var/run/passenger-instreg

and it works

**Comment by craigcarnell** [comment]
@FooBarWidget I have one more question

I deploy my files using a deploy user
I then run nginx as nginx

This normally works for me, but I doubt it will work in this scenario. Is it better to deploy the files as nginx user?

As bin/rake etc is created a deploy user, which the nginx user cannot run

**Comment by OnixGH** [comment]
@craigcarnell please use our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for questions about your configuration.
