### ISSUE TITLE
Unable to compile passenger for apache2 in ubuntu

### ISSUE THREAD

**Issue by demonmind** [phusion/passenger#1931]
I get always a missing file when i try to run the passenger coflig:

deploy@dev2:~/.rvm/gems/ruby-2.4.0@atomized/gems/passenger-5.1.0$ rake apache2
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - buildout/libuv/.libs/libuv.la
/home/deploy/.rvm/gems/ruby-2.4.0@atomized/gems/passenger-5.1.0/build/common_library.rb:219:in `initialize'
/home/deploy/.rvm/gems/ruby-2.4.0@atomized/gems/passenger-5.1.0/build/common_library.rb:219:in `open'
/home/deploy/.rvm/gems/ruby-2.4.0@atomized/gems/passenger-5.1.0/build/common_library.rb:219:in `libuv_libs'
/home/deploy/.rvm/gems/ruby-2.4.0@atomized/gems/passenger-5.1.0/build/agent.rb:89:in `block in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => apache2 => buildout/support-binaries/PassengerAgent
(See full trace by running task with --trace)

**Comment by OnixGH** [comment]
Why are you running rake inside the gems? To install for apache you can use: `passenger-install-apache2-module`.

**Comment by demonmind** [comment]
I tried both nothing worked. The issue though was not with passenger. RVM installed ruby 2.4.0 incorrectly and reinstalling ruby fixed the issues.
