### ISSUE TITLE
starting my django app 

### ISSUE THREAD

**Issue by elba7r** [phusion/passenger#1933]
An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read this article for more information about this problem.
Raw process output:

Traceback (most recent call last):
  File "/opt/passenger/helper-scripts/wsgi-loader.py", line 320, in <module>
    app_module = load_app()
  File "/opt/passenger/helper-scripts/wsgi-loader.py", line 61, in load_app
    return imp.load_source('passenger_wsgi', startup_file)
  File "passenger_wsgi.py", line 9, in <module>
    application = wsgi.application
AttributeError: 'module' object has no attribute 'application'
Error ID
1ed85723

**Comment by OnixGH** [comment]
Please post to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for help with your configuration (we recommend posting your full config to avoid wasting time with guessing).
