### ISSUE TITLE
Pure TCPServer doesn't connect with Passenger

### ISSUE THREAD

**Issue by dr-dimitru** [phusion/passenger#1940]
## Issue report

**Are you sure this is a bug in Passenger?**
No, it's lack of documentation.

**Question 1: What is the problem?**
- What is the expected behavior? - *App should respond to incoming http requests*
- What is the actual behavior? - *http requests via passenger+nginx is timeouted. While direct (by random port) has response*
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem. - *See code below*

**Question 2: Passenger version and integration mode**:
- open source nginx/1.10.2 Phusion_Passenger/5.1.2

**Question 3: OS or Linux distro, platform (including version)**:
- Debian 8.7, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- ruby 2.4.1p111 (build from source), no rails, no sinatra, no thin, no other gems

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- No

**Question 7: Anything else about your setup that we should know?**

Nginx File:
```nginx
server {
  listen localhost:3045;
  server_name localhost;

  root /var/www/app/public;

  passenger_enabled on;
  passenger_app_type ruby;
  passenger_startup_file main.rb;
  passenger_sticky_sessions off;
}
```

Gemfile:
```gemfile
# frozen_string_literal: true
source "https://rubygems.org"

gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"
gem "json"
```

After deploy I've ran (as app user):
```shell
su -s /bin/bash appuser
gem install passenger bundle --no-document
passenger-config build-native-support
bundle install --deployment --without development test
```

`/var/www/app/main.rb`:
```ruby
server = TCPServer.new(0)
#!/usr/bin/env ruby
require 'rubygems'
require 'socket'
require 'json'

server = TCPServer.new(0)

loop do
  Thread.start(server.accept) do |socket|
    begin
      request = socket.gets

      if request.include? "/"
        _res = {}
        _res[:status] = "OK"
        response = _res.to_json
      else
        response = '{"error": "Nothing here!"}'
      end

      socket.print "HTTP/1.1 200 OK\r\n" +
                   "Content-Type: application/json; charset=UTF-8\r\n" +
                   "Content-Length: #{response.bytesize}\r\n" +
                   "Connection: close\r\n"

      socket.print "\r\n"
      socket.print response
      socket.close
    rescue Exception => e
      # puts e
    end
  end
end
```

`/var/log/nginx/error.log`:
```plain
App [pid] stdout:
```

**Comment by CamJN** [comment]
This is expected, Ruby webapps must provide the rack interface to work with Passenger.

**Comment by dr-dimitru** [comment]
@CamJN thank you for reply.
This should be mentioned in at least in CAPS ON EVERY PASSENGER-RUBY DOCS PAGE.
Sorry for expression, but I've wasted 20 hours trying to figure out this.

For any one who run into the same conditions:
```ruby
#!/usr/bin/env ruby
require 'rubygems'
require 'thread'
require 'json'

app = lambda do |env|
  env['rack.hijack'].call
  socket = env['rack.hijack_io']
  request = env['REQUEST_URI']

  begin
    if request.include? "/"
      _res = {}
      _res[:status] = "OK"
      response = _res.to_json
    else
      response = '{"error": "Nothing here!"}'
    end

    socket.write "HTTP/1.1 200 OK\r\n" +
                 "Content-Type: application/json; charset=UTF-8\r\n" +
                 "Content-Length: #{response.bytesize}\r\n" +
                 "Connection: close\r\n"

    socket.write "\r\n"
    socket.write response
    socket.close
  ensure
    socket.close
  end
end

run app
```

Inspired by [this post](http://blog.phusion.nl/2013/01/23/the-new-rack-socket-hijacking-api/)

@CamJN if you have any suggestions/comments to approach above - it will be very welcome. As I'm using "vanilla" Ruby to write thin and lightweight APIs, and not familiar with any framework solutions, even rack (*I know it's de-facto for ruby...*)

**Comment by CamJN** [comment]
Just that hijacking the socket shouldn't be needed. Here's a minimal example:
```
app = lambda do |env|
                [200, { "Content-Type" => "text/plain" }, ["ok"]]
              end
run app
```

**Comment by dr-dimitru** [comment]
@CamJN 

Thank you. I guess it's just more clean code solution, without performance pros/cons?
My tests via `wkr` has only `-0.3%` decrease (*which is OK due to measurement method*) over your approach.

**Comment by CamJN** [comment]
I suggested it due to the increased ease of use. If you hijack the socket then you are doing passenger's job yourself.

**Comment by dr-dimitru** [comment]
@CamJN is there any possibility to avoid rack usage, like using `passenger` gem directly, does it have such low-level API? Asking, as rack decreases throughput for `-17%`, quick guess - due to processing/parsing?

This API is  for very thin app layer each request/response is less than 0.7KB of data and it depends from speed and throughput very much.

**Comment by CamJN** [comment]
I can't say I've ever felt that the overhead that rack incurs wasn't worth the ease of use. As an example I have an app that serves a simple api which responds within the margin of error of static file requests (~8ms) which uses rack.

However to answer your question, right now there is no api for ruby apps to avoid rack, however there is a feature that is expected to be available as a beta in June that could help you.

**Comment by dr-dimitru** [comment]
> however there is a feature that is expected to be available as a beta in June that could help you.

Sounds, great, thank you.
As always - thanks for great product!
BTW will it cover #1898 as well?

**Comment by CamJN** [comment]
I'm not sure what-all the first feature set will include.

**Comment by dr-dimitru** [comment]
Hello @CamJN ,

> However to answer your question, right now there is no api for ruby apps to avoid rack, however there is a feature that is expected to be available as a beta in June that could help you.

Is this delivered already?

**Comment by CamJN** [comment]
@dr-dimitru sorry no, it hasn't been landed on stable-5.1 branch yet. We still intend to release it but the timeline has been drawn out, unfortunately.

**Comment by dr-dimitru** [comment]
@CamJN thank you for update on this one.

**Comment by dr-dimitru** [comment]
Hello @CamJN ,

> However to answer your question, right now there is no api for ruby apps to avoid rack, however there is a feature that is expected to be available as a __beta in June__ that could help you.

Any news around it? Waiting for this feature...

**Comment by FooBarWidget** [comment]
Yes, sorry for the long but, but this time we have good news. We've started implementation and already have a working prototype. We're still working on documentation, tests and general quality assurance.

The feature in question is dubbed "generic language support". Passenger is to support all programming languages, not just Ruby/Python/Node.js. This is achieved by communicating with apps through regular HTTP. In other words, Passenger will be able to serve any app that is able to speak HTTP on a port that Passenger designates, and Passenger won't care how you implement the HTTP protocol, or what language you use. You could use a custom-written TCP server, or you could use Thin or Puma or whatever you want.

**Comment by dr-dimitru** [comment]
@FooBarWidget Sounds great, can't wait. We just updated to latest Passenger, happy to see you've set communication to Unix sockets by default. Noticed [new application loaders](https://github.com/phusion/passenger/tree/stable-5.3/src/helper-scripts), and thought maybe "generic language support" is implemented.

Thank you for the quick reply, looking forward "generic language support", best wishes to all team, Phusion Passenger - great project!
