### ISSUE TITLE
v5.1.3 Nginx built without ngx_http_v2_module

### ISSUE THREAD

**Issue by dr-dimitru** [phusion/passenger#1943]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior? - *Support `http2` on default_server*
- What is the actual behavior? - *Daemon throws an error `nginx: [emerg] the "http2" parameter requires ngx_http_v2_module`*
- How can we reproduce it?
*Install phusion passenger `v5.1.3` via `apt-get` on Debian 8, with next config:*
```nginx
# /etc/nginx/sites-available/default
server {
  listen 443 default_server ssl http2 deferred reuseport;
  listen [::]:443 default_server ssl http2 deferred reuseport ipv6only=on;
  server_name _;

  return 444;
}
```

**Question 2: Passenger version and integration mode**:
- open source 5.1.3/nginx

**Question 3: OS or Linux distro, platform (including version)**:
-  Debian 8, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- Node.js 4.8.2 with Meteor

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- No

**Question 7: Anything else about your setup that we should know?**
Nothing special, everything was working fine until we decided to `apt-get upgrade`.
Unless `http2` option is removed from default_server.

**Comment by CamJN** [comment]
We are working on a new release to fix the issues in 5.1.3. We may need to pull 5.1.3 in the meantime to save people headaches.

**Comment by CamJN** [comment]
5.1.4 has been released please verify if this addresses your issue.

**Comment by xeron** [comment]
Updated several days ago, these versions work for me.
```
ii  nginx-common         1:1.10.3-8.5.1.4~jessie1
ii  nginx-extras         1:1.10.3-8.5.1.4~jessie1
ii  passenger            1:5.1.4-1~jessie1
ii  passenger-dev        1:5.1.4-1~jessie1
ii  passenger-doc        1:5.1.4-1~jessie1
```

**Comment by dr-dimitru** [comment]
Thank you. Upgraded successfully, up and running with `http2`. Solved.
