### ISSUE TITLE
Latest nginx-extras from passenger repo missing http2 module

### ISSUE THREAD

**Issue by xeron** [phusion/passenger#1944]
## Issue report

After the latest update nginx fails to start for me because it's missing `http2` support. Previous version works as expected.

```
May 04 00:03:25 website_name systemd[1]: Starting A high performance web server and a reverse proxy server...
May 04 00:03:25 website_name nginx[13508]: nginx: [emerg] the "http2" parameter requires ngx_http_v2_module in /etc/nginx/sites-enabled/website_name:8
May 04 00:03:25 website_name nginx[13508]: nginx: configuration file /etc/nginx/nginx.conf test failed
May 04 00:03:25 website_name systemd[1]: nginx.service: control process exited, code=exited status=1
May 04 00:03:25 website_name systemd[1]: Failed to start A high performance web server and a reverse proxy server.
May 04 00:03:25 website_name systemd[1]: Unit nginx.service entered failed state.
```

**Question 1: What is the problem?**
- What is the expected behavior?

nginx starts.

- What is the actual behavior?

nginx fails to start due to missing `http2` support.

- How can we reproduce it?

* Install `nginx-extras` and `passenger` from Phusion apt repo
* Add server which does `listen 443 ssl http2`
* Start `nginx`

**Question 2: Passenger version and integration mode**:

 Open-source, `passenger 1:5.1.3-1~jessie1`, `nginx-extras 1.10.3-8.5.1.3~jessie1`.

**Question 3: OS or Linux distro, platform (including version)**:

Debian GNU/Linux 8.7 (jessie), x86_64

**Question 4: Passenger installation method**:

Phusion APT repo.

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.4.1, compiled by hands, Rails 5.1.0.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No.

**Question 7: Anything else about your setup that we should know?**

Probably no.

**Comment by xeron** [comment]
Looks like someone else just reported the same issue: https://github.com/phusion/passenger/issues/1943

Feel free to close one of the reports.

**Comment by CamJN** [comment]
Dup of #1943 as mentioned.
