### ISSUE TITLE
http2 ALPN support for bundled nginx (APT)

### ISSUE THREAD

**Issue by dhampik** [phusion/passenger#1945]
## Feature request
Current version of bundled nginx (when passenger is a module of nginx) is built with OpenSSL 1.0.1k 8 Jan 2015. That does not allow to have ALPN support and that means that http2 cannot be used in modern browsers, e.g. Chrome has dropped NPN support a year ago.
It would be really nice if Passenger is bundled with new versions of nginx (e.g. 1.13.0 supports TLS 1.3) which are built with OpenSSL 1.0.2+

Previously, as I remember, Passenger always provided most up-to-date version of nginx and now it's way behind the latest version :disappointed: .

**Are you sure this is a bug in Passenger?**
That is not a bug in passenger, but a feature request to ship it with an nginx built with OpenSSL 1.0.2+

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
Your answer:
- Expected behavior: Nginx should be built with a newer version of OpenSSL to support ALPN negotiation, so that browsers used http2 talking to the server.
- Actual behavior: Nginx that is bundled with passenger is built with OpenSSL 1.0.1k
- Running `nginx -v` and `passenger -v` is enough to see the versions. Another option is to add `http2` to `listen` directive and see that sites still fallback to http/1.1

**Question 2: Passenger version and integration mode**:
Your answer: passenger 5.1.2 with nginx 1.10.2 built with OpenSSL 1.0.1k (community version)

**Question 3: OS or Linux distro, platform (including version)**:
Your answer: Debian 8.7

**Question 4: Passenger installation method**:
Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[v] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer: Ruby 2.4.0, rvm, rails 5

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer: I'm using VPS server

**Comment by CamJN** [comment]
The modules we include are not yet updated for Nginx 1.12.0. However I'll leave this open for the future releases.

**Comment by dhampik** [comment]
Well, I'm not an expert in nginx, but it seems to me that it could be possible to build current bundled version of nginx which is 1.10.2 with with OpenSSL 1.0.2+. That will enable ALPN support. Though I'm not sure how it will work with standard openssl package that comes with OS, e.g. my Debian 8.7 has OpenSSL version 1.0.1t  3 May 2016 installed from standard repositories. It could be so that openssl of a new version should be bundled as well and that could have a whole bunch of other dependencies, not sure.

**Comment by CamJN** [comment]
We'll have to discuss whether having openssl 1.0.2* is worth the extra difficulty for our users of requiring jessie-backports packages.

**Comment by arpu** [comment]
same problem on centos 7.3 
[root@rs001976 ~]# dnf list installed | grep nginx
nginx.x86_64                          100:1.10.3-1.p5.1.4.el7            @System
nginx-filesystem.noarch               100:1.10.3-1.p5.1.4.el7            @System
[root@rs001976 ~]# dnf list installed | grep openssl
openssl.x86_64                        1:1.0.1e-60.el7_3.1                @System
openssl-devel.x86_64                  1:1.0.1e-60.el7_3.1                @System
openssl-libs.x86_64                   1:1.0.1e-60.el7_3.1                @System

**Comment by arpu** [comment]
@CamJN  should i open a new bug on this problem for centos 7.3?

**Comment by CamJN** [comment]
@arpu no need, the system openssl is up to the distro, and we'll upgrade nginx to 1.12.0 across all versions at the same time.

**Comment by toncid** [comment]
Passenger 5.1.8 ships with nginx 1.12.1 and OpenSSL 1.0.2l. Looks sufficient for HTTP2.

Any chance of enabling HTTP2 in the default server template or via `Passengerfile.json`?

**Comment by toncid** [comment]
Hello @FooBarWidget @OnixGH, 

Is there any feedback regarding this issue/request?

**Comment by toncid** [comment]
Hello @FooBarWidget @CamJN, 

Is there any feedback regarding this issue/request?

**Comment by CamJN** [comment]
Unfortunately, since you have the option of editing the nginx template, this doesn't have the highest priority. We'll see if we can fit it into the next release but it may not make the cut.

**Comment by toncid** [comment]
Well, you are right, but the `server.erb` template with `server` directives is quite large (many variables and further template includes), so it is likely something will break due to it being unmaintained.

Not to mention HTTP/2 would look great in a release note... ;)

**Comment by CamJN** [comment]
If you'd like to help you can test this branch: https://github.com/phusion/passenger/tree/GH1945_http2

**Comment by toncid** [comment]
Haha, no need to test it, it is already live on our system (edited gem's `server.erb` under the gem home folder and restarted the app). 

Not really a best practice, but it will work until a new Passenger version comes, when the file change will have to be re-applied.
