### ISSUE TITLE
Passenger could not be installed on my server

### ISSUE THREAD

**Issue by yuri-zubov** [phusion/passenger#1946]
Hello guys!

I usually use this script for installing passenger
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
sudo apt-get install apt-transport-https
sudo sh -c "echo 'deb https://oss-binaries.phusionpassenger.com/apt/passenger $(lsb_release -sc) main' >> /etc/apt/sources.list.d/passenger.list"
sudo chown root:root /etc/apt/sources.list.d/passenger.list
sudo chmod 600 /etc/apt/sources.list.d/passenger.list
sudo apt-get update
sudo apt-get install nginx-full passenger
```
but today I have a problem with it. if I try to execute this script I will get error 
```
E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/xenial/main/binary-amd64/Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
What's happening in your repository???

Additional information:
```
OS: 16.04.2 LTS (GNU/Linux 4.4.0-1013-aws x86_64)
```

**Comment by arothian** [comment]
I've seen 404 issues with installing from apt repo this morning for Ubuntu Trusty. There is also reports on the google support forum. This is a blocker for building new vm images.

**Comment by CamJN** [comment]
We are aware and working on it.

**Comment by yuri-zubov** [comment]
thank you for your answer

**Comment by CamJN** [comment]
tested and fixed on xenial, checking trusty next

**Comment by CamJN** [comment]
trusty is working as well.

**Comment by tierra** [comment]
This appears to be an issue again, at least with the trusty index.

**Comment by OnixGH** [comment]
@tierra Known issue, being worked on.

**Comment by boethius** [comment]
For anyone who's experiencing the same problems, it seems to be working on and off. If it doesn't work, go get some coffee and come back.
