### ISSUE TITLE
Question - Future plans - DotNetCore Support

### ISSUE THREAD

**Issue by andreujuanc** [phusion/passenger#1948]
Are you guys planning to include DotNetCore? It'd be amazing D:

Cheers!

**Comment by CamJN** [comment]
We are working on a way of supporting apps written in any language, which should be available as a beta in the coming months.

**Comment by andreujuanc** [comment]
+1 
I will be happy to test this on beta.

**Comment by ylluminate** [comment]
So this was an excellent request and with the release of Passenger 6 it looks like you've finally reached the goal! 

Can you guys throw out a .NET guide for Passenger 6? 

This would really be fantastic.

**Comment by CamJN** [comment]
https://www.phusionpassenger.com/docs/advanced_guides/gls/dotnetcore.html

**Comment by developertemur** [comment]
#bug #error in asp.net core 8 with passanger has 400 error with http 3.0 protocol
