### ISSUE TITLE
cannot start server after installing Passenger 5.1.4

### ISSUE THREAD

**Issue by nateguy** [phusion/passenger#1949]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:

Getting the following error when starting server with `foreman s` when using Phusion Passenger 5.1.3 or 5.1.4:

09:14:43 web.1                                       | Could not start the Nginx engine:
09:14:43 web.1                                       | nginx: [alert] Unable to start the Phusion Passenger watchdog: it seems to have been killed with signal SIGTRAP during startup (-1: Unknown error)
09:14:44 web.1                                       | exited with code 1

No issues with Passenger 5.1.2

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer: Phusion Passenger 5.1.2 (open source)

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer: OS X 10.10.5

**Question 4: Passenger installation method**:

Your answer:
[ X ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:
Ruby 2.4.0, Rails 5.0.3

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:
 Amazon Container Services

**Comment by CamJN** [comment]
Can you show us what command the procfile has for starting passenger? And would it be possible to increase the log level to 7 to get more detail about the failure?

**Comment by tz-hmc** [comment]
Hello,
I had the same error with the same setup. I then reinstalled passenger, restarted nginx, and the error message changed to:

> *** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:
> 
>     nginx: the configuration file nginx.conf syntax is ok
>     nginx: [emerg] open() "/etc/apache2/other/passenger.3000.pid" failed (13: Permission denied)
>     nginx: configuration file nginx.conf test failed
> 
> This probably means that you have found a bug in Phusion Passenger Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues
> 
> In the bug report, please include this error message, as well as the contents of the file /var/folders/sk/1p18npyd7w92qtb8vz7xlq640000gp/T/passenger-standalone-ntpnp8.log
[passenger-standalone-ntpnp8.log.zip](https://github.com/phusion/passenger/files/1013023/passenger-standalone-ntpnp8.log.zip)

I have the correct nginx.conf as the installation guide describes [here](https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/nginx/oss/osx/deploy_app.html#rails_login-to-your-server-create-a-user-for-the-app)
so I don't understand the nginx error " open() "/etc/apache2/other/passenger.3000.pid" failed "
especially since that path doesn't even exist on my system. If anyone understands these bugs, please let me know.

**Comment by CamJN** [comment]
Ensuring that you only have one instance of Nginx running and one copy of Passenger installed is good advice.

**Comment by nateguy** [comment]
this is my command:

passenger start -p ${PORT:-80} --max-pool-size=${PASSENGER_MAX_POOL_SIZE:-3} --min-instances=${PASSENGER_MIN_INSTANCES:-1} --concurrency-model=${PASSENGER_CONCURRENCY_MODEL:-process} --thread-count=${PASSENGER_THREAD_COUNT:-1} --nginx-config-template=${PASSENGER_NGINX_CONFIG_TEMPLATE:-nginx.conf.erb}

**Comment by CamJN** [comment]
That looks fine can you post the output of running the following: 
```
passenger start -p ${PORT:-80} --max-pool-size=${PASSENGER_MAX_POOL_SIZE:-3} --min-instances=${PASSENGER_MIN_INSTANCES:-1} --concurrency-model=${PASSENGER_CONCURRENCY_MODEL:-process} --thread-count=${PASSENGER_THREAD_COUNT:-1} --nginx-config-template=${PASSENGER_NGINX_CONFIG_TEMPLATE:-nginx.conf.erb} --debug-nginx-config
```

**Comment by JakeLaCombe** [comment]
Is there any update on this issue? I appear to be running into the same issue as well after I upgraded an application from rails 4 to 5.0.3

**Comment by JakeLaCombe** [comment]
Looks like Passenger 5.1.2 worked, but 5.1.4 gave me an error. For further details, here is my setup.

Ruby-2.4.0
Rails-5.0.3
OSX 10.11.6

**Comment by CamJN** [comment]
@JakeLaCombe can you post your generated nginx config? And the exact error you see?

**Comment by JakeLaCombe** [comment]
Where could I find that file by chance? I'm using the standalone component with Rails, and I'm not sure where I would be able to find that file. This is what's displayed when I use this version.

    09:14:43 web.1 | Could not start the Nginx engine:
    09:14:43 web.1 | nginx: [alert] Unable to start the Phusion Passenger watchdog: it seems to have   
    been killed with signal SIGTRAP during startup (-1: Unknown error)

**Comment by CamJN** [comment]
You add the `--debug-nginx-config` flag to the end of your `passenger start` command.

**Comment by JakeLaCombe** [comment]
Thanks!

`master_process on;
daemon on;
error_log '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/log/passenger.3000.log' ;
pid '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/tmp/pids/passenger.3000.pid';


worker_processes 1;
events {
    worker_connections 1024;
}

http {
    log_format debug '[$time_local] $msec  "$request" $status conn=$connection sent=$bytes_sent body_sent=$body_bytes_sent';
    include '/Users/jl021230/.rvm/gems/ruby-2.4.0/gems/passenger-5.0.25/resources/mime.types';
    passenger_root '/Users/jl021230/.rvm/gems/ruby-2.4.0/gems/passenger-5.0.25';
    passenger_abort_on_startup_error on;
    passenger_ctl cleanup_pidfiles L3Zhci9mb2xkZXJzL2RkLzl5eXc0OWYxMW1zZDY5NmZybjhnMXpyZG5uN3Z2aC9UL3Bhc3Nlbmdlci1zdGFuZGFsb25lLjFlY3V6bHAvdGVtcF9kaXJfdG91Y2hlci5waWQ=;
    passenger_ctl integration_mode standalone;
    passenger_ctl standalone_engine nginx;
    passenger_user_switching off;
    passenger_ruby /Users/jl021230/.rvm/gems/ruby-2.4.0/wrappers/ruby;
    passenger_user jl021230;
    passenger_default_user jl021230;
    passenger_analytics_log_user jl021230;
    passenger_socket_backlog 1024;
    passenger_log_level 3;


    ### BEGIN your own configuration options ###
    # This is a good place to put your own config
    # options. Note that your options must not
    # conflict with the ones Passenger already sets.
    # Learn more at:
    # https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template

    ### END your own configuration options ###

    default_type application/octet-stream;
    types_hash_max_size 2048;
    server_names_hash_bucket_size 64;
    client_max_body_size 1024m;
    access_log off;
    keepalive_timeout 60;
    underscores_in_headers on;
    gzip on;
    gzip_comp_level 3;
    gzip_min_length 150;
    gzip_proxied any;
    gzip_types text/plain text/css text/json text/javascript
        application/javascript application/x-javascript application/json
        application/rss+xml application/vnd.ms-fontobject application/x-font-ttf
        application/xml font/opentype image/svg+xml text/xml;

    

    
    server {
        server_name _;
        listen 0.0.0.0:3000;
        root '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/public';
        passenger_app_root '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard';
        passenger_enabled on;
        passenger_app_env 'development';
        passenger_spawn_method 'smart';
        passenger_load_shell_envvars off;

        # Rails asset pipeline support.
        location ~ "^/assets/.+-([0-9a-f]{32}|[0-9a-f]{64})\..+" {
            error_page 490 = @static_asset;
            error_page 491 = @dynamic_request;
            recursive_error_pages on;
        
            if (-f $request_filename) {
                return 490;
            }
            if (!-f $request_filename) {
                return 491;
            }
        }
        location @static_asset {
            gzip_static on;
            expires max;
            add_header Cache-Control public;
            add_header ETag "";
        }
        location @dynamic_request {
            passenger_enabled on;
        }


        ### BEGIN your own configuration options ###
        # This is a good place to put your own config
        # options. Note that your options must not
        # conflict with the ones Passenger already sets.
        # Learn more at:
        # https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template

        ### END your own configuration options ###
    }
    passenger_pre_start http://0.0.0.0:3000/;
    

    
}
`

**Comment by JakeLaCombe** [comment]
Also, I'm getting a new another issue as well. Activerecord seems to be hanging with passenger when used with Rails 5 in conjunction

`
Processing by Api::Neighborhood::VacancyController#index as HTML
  Parameters: {"filters"=>["demo_needed"], "id"=>"187"}
  Neighborhood Load (0.2ms)  SELECT  "neighborhoods".* FROM "neighborhoods" WHERE "neighborhoods"."id" = ? LIMIT ?  [["id", 187], ["LIMIT", 1]]
`

`
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql 
  encoding: unicode 
  pool: 5 
  timeout: 5000 
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # please see the update below about using hostnames to 
  # access linked services via docker-compose
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
`

`
@neighborhood ||= Neighborhood.find(@neighborhood_id)
`

**Comment by CamJN** [comment]
@JakeLaCombe you are getting a config generated by passenger 5.0.25 you should check your path for extra copies of passenger. You'll want to check the output of at least the following:
```
which passenger
echo $PATH | tr : '\n'
```

**Comment by OnixGH** [comment]
@JakeLaCombe I'm assuming your issue was found.

@nateguy is it resolved for you as well?

**Comment by JakeLaCombe** [comment]
Sorry for late posting. I'll be more proactive in helping resolve this.

I reconfigured my passenger, and I still get the error. I looked at the config file, and I believe it's using passenger 5.1.4 now. I see this in the debug output.

    include '/Users/jl021230/.rvm/gems/ruby-2.4.0/gems/passenger-5.1.4/resources/mime.types';
    passenger_root '/Users/jl021230/.rvm/gems/ruby-2.4.0/gems/passenger-5.1.4';

**Comment by OnixGH** [comment]
@JakeLaCombe can you post your entire config, and also a Passenger log file at level 7 (containing the start up to the error you're experiencing)?

**Comment by JakeLaCombe** [comment]
Hope this helps

Start up Command
```
Neighborhood-Dashboard git:(master) ✗ rails server
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/Users/jl021230/.rvm/gems/ruby-2.4.0", "/Users/jl021230/.rvm/gems/ruby-2.4.0@global"]}) was passed in from bin/rails:5:in `load'
=> Booting Passenger application server
=> Rails 5.0.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options

> neighborhood-dashboard@1.0.0 webpack-dev-server /Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard
> webpack && webpack-dev-server --config webpack.hot.config.js --hot --progress --inline

Could not start the Nginx engine:
nginx: [alert] Unable to start the Phusion Passenger watchdog: it seems to have been killed with signal SIGTRAP during startup (-1: Unknown error)
Exiting
/Users/jl021230/.rvm/gems/ruby-2.4.0/gems/passenger-5.1.4/src/ruby_supportlib/phusion_passenger/rack_handler.rb:47:in `run': Error starting Passenger (RuntimeError)
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/rack-2.0.3/lib/rack/server.rb:297:in `start'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/railties-5.0.4/lib/rails/commands/server.rb:104:in `start'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/bin/rails:32:in `require'
	from /Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/bin/rails:32:in `<top (required)>'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/jl021230/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/bin/spring:13:in `require'
	from /Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/bin/spring:13:in `<top (required)>'
	from bin/rails:5:in `load'
	from bin/rails:5:in `<main>'

```

Start up passenger (passenger start --debug-nginx-config)
```
Could not start the Nginx engine:
nginx: [alert] Unable to start the Phusion Passenger watchdog: it seems to have been killed with signal SIGTRAP during startup (-1: Unknown error)
```

Start up passenger with debug 
```
##########################################################################
#  Passenger Standalone is built on the same technology that powers
#  Passenger for Nginx, so any configuration option supported by Passenger
#  for Nginx can be applied to Passenger Standalone as well. You can do
#  this by direct editing the Nginx configuration template that is used by
#  Passenger Standalone.
#
#  This file is the original template. DO NOT EDIT THIS FILE DIRECTLY.
#  Instead, make a copy of this file and pass the `--nginx-config-template`
#  parameter to Passenger Standalone.
#
#  Learn more about using the Nginx configuration template at:
#  https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template
#
#  *** NOTE ***
#  If you customize the template file, make sure you keep an eye on the
#  original template file and merge any changes. New Phusion Passenger
#  features may require changes to the template file.
##############################################################

master_process on;
daemon on;
error_log '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/log/passenger.3000.log' ;
pid '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/tmp/pids/passenger.3000.pid';


worker_processes 1;
events {
    worker_connections 4096;
}

http {
    log_format debug '[$time_local] $msec  "$request" $status conn=$connection sent=$bytes_sent body_sent=$body_bytes_sent';
    include '/Users/jl021230/.rvm/gems/ruby-2.4.0/gems/passenger-5.1.4/resources/mime.types';
    passenger_root '/Users/jl021230/.rvm/gems/ruby-2.4.0/gems/passenger-5.1.4';
    passenger_abort_on_startup_error on;
    passenger_ctl cleanup_pidfiles L3Zhci9mb2xkZXJzL2RkLzl5eXc0OWYxMW1zZDY5NmZybjhnMXpyZG5uN3Z2aC9UL3Bhc3Nlbmdlci1zdGFuZGFsb25lLjF5cmRhZDUvdGVtcF9kaXJfdG91Y2hlci5waWQ=;
    passenger_ctl integration_mode standalone;
    passenger_ctl standalone_engine nginx;
    passenger_user_switching off;
    passenger_log_level 3;


    ### BEGIN your own configuration options ###
    # This is a good place to put your own config
    # options. Note that your options must not
    # conflict with the ones Passenger already sets.
    # Learn more at:
    # https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template

    ### END your own configuration options ###

    default_type application/octet-stream;
    types_hash_max_size 2048;
    server_names_hash_bucket_size 64;
    client_max_body_size 1024m;
    access_log off;
    keepalive_timeout 60;
    underscores_in_headers on;
    gzip on;
    gzip_comp_level 3;
    gzip_min_length 150;
    gzip_proxied any;
    gzip_types text/plain text/css text/json text/javascript
        application/javascript application/x-javascript application/json
        application/rss+xml application/vnd.ms-fontobject application/x-font-ttf
        application/xml font/opentype image/svg+xml text/xml;

    

    
    server {
        server_name _;
        listen 0.0.0.0:3000;
        root '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/public';
        passenger_app_root '/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard';
        passenger_enabled on;
        passenger_app_env 'development';
        passenger_spawn_method 'smart';
        passenger_load_shell_envvars off;

        # Rails asset pipeline support.
        location ~ "^/assets/.+-([0-9a-f]{32}|[0-9a-f]{64})\..+" {
            error_page 490 = @static_asset;
            error_page 491 = @dynamic_request;
            recursive_error_pages on;
        
            if (-f $request_filename) {
                return 490;
            }
            if (!-f $request_filename) {
                return 491;
            }
        }
        location @static_asset {
            gzip_static on;
            expires max;
            add_header Cache-Control public;
            add_header ETag "";
        }
        location @dynamic_request {
            passenger_enabled on;
        }


        ### BEGIN your own configuration options ###
        # This is a good place to put your own config
        # options. Note that your options must not
        # conflict with the ones Passenger already sets.
        # Learn more at:
        # https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template

        ### END your own configuration options ###
    }
    passenger_pre_start http://0.0.0.0:3000/;
    

    
}
```

**Comment by JakeLaCombe** [comment]
Is this what you refer to as level 7?

**Comment by OnixGH** [comment]
@JakeLaCombe no, in your config it shows `passenger_log_level 3;`, this is the log level that should be set to 7. And then we need the Passenger log file, which is specified via the error_log option ('/Users/jl021230/Documents/CodeForAmerica/Neighborhood-Dashboard/log/passenger.3000.log' ;)

**Comment by JakeLaCombe** [comment]
I did look at the error log, and this is what it shows.

```
[ 2017-07-04 10:22:59.8097 67938/0x7fff76e94000 age/Wat/WatchdogMain.cpp:1281 ]: Starting Passenger watchdog...
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/jl021230/.passenger/support-binaries/5.1.4/PassengerAgent
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/jl021230/.passenger/support-binaries/5.1.4/PassengerAgent
  Expected in: /usr/lib/libSystem.B.dylib

2017/07/04 10:22:59 [alert] 67937#0: Unable to start the Phusion Passenger watchdog: it seems to have been killed with signal SIGTRAP during startup (-1: Unknown error)
```

**Comment by JakeLaCombe** [comment]
As for bumping to level 7, I'm not sure how to do that. I'm on the standalone passenger that generates the config file when rails server or passenger start is inputted.

**Comment by CamJN** [comment]
Ah the `/usr/lib/libSystem.B.dylib` bit might be relevant, do you have xcode installed, and if so do you also have the CLT package installed? Which exact build of xcode, macOS, and the CLT do you have (for those that are installed, anyway)?

**Comment by JakeLaCombe** [comment]
Sure do.

xcode-select version 2343.
Mac OSX 10.11.6 (15G1004)
CLT version: 8.2.0.0.1.1480973914

**Comment by OnixGH** [comment]
@JakeLaCombe the Passenger related options in that file can also be set through command line options or environment variables: https://www.phusionpassenger.com/library/config/standalone/reference/

**Comment by JakeLaCombe** [comment]
Thanks!

I have to step away from my machine for a while, so I'll update when I can.
There isn't a big rush on this issue btw. And thanks again for looking into
this!

**Comment by CamJN** [comment]
This is the same problem as described here: https://github.com/tarantool/tarantool/issues/1777
The solution is for Apple to release developer tools that aren't broken. But since xcode has been semi broken for **ALL OF SIERRA** I wouldn't get my hopes up.

**Comment by scopej** [comment]
Hey is this still being looked at? 
My team just tried upgrading to passenger 5.1.5 and found we can't run passenger on El Capitan machines for local development due to these errors.

**Comment by CamJN** [comment]
@scopej can you provide your installation method, and the logs of the error? I just want to confirm whether or not you are seeing the same `clock_gettime` problem.

**Comment by CamJN** [comment]
We're planning on building the prebuilt binaries used by the gem on el-capitan in the next release . In the meantime the homebrew bottles are all built on their install platform and should work fine.

**Comment by CamJN** [comment]
Does this issue still occur?

**Comment by OnixGH** [comment]
Closing as probably resolved. Feel free to reopen if not.
