### ISSUE TITLE
Passenger Standalone temporary directory does not get cleaned up if it fails to start

### ISSUE THREAD

**Issue by radamanthus** [phusion/passenger#1953]
## Issue report

**Question 1: What is the problem?**

- What is the expected behavior?
passenger-standalone should clean up the /tmp/passenger-standalone.xxxxxxx directory it creates

- What is the actual behavior?
If passenger-standalone fails to start (e.g. the port is already in use, or the given PID file matches the PID of an already running Passenger process) then the passenger-standalone.xxxxxxx directory does not get cleaned up

- How can we reproduce it? 

1) Start a passenger-standalone process. This is the command I used:

```
/usr/local/bin/passenger start current --daemonize --port 8000 --environment production --max-pool-size 6 --min-instances 6 --pid-file /data/todo/shared/pids/passenger.8000.pid --log-file /data/todo/shared/log/passenger.8000.log
```

(the Rails application is in `/data/todo`)

2) Verify that a passenger-standalone directory was created in `/tmp`

3) Run another standalone process with the same command:

```
/usr/local/bin/passenger start current --daemonize --port 8000 --environment production --max-pool-size 6 --min-instances 6 --pid-file /data/todo/shared/pids/passenger.8000.pid --log-file /data/todo/shared/log/passenger.8000.log
```

The output will be something like:

```
Phusion Passenger Standalone is already running on PID 1103.
```

Run `ls -lah /tmp` and verify that a new passenger-standalone directory was created

4) Repeat Step 3 multiple times. You’ll see that each time a /tmp/passenger-standalone.* directory is created and not cleaned up

5) Try to run passenger-standalone on the same port but with a different PID file and log file (note the different parameters passed to --pid-file and --log-file):

```
/usr/local/bin/passenger start current --daemonize --port 8000 --environment production --max-pool-size 6 --min-instances 6 --pid-file /data/todo/shared/pids/passenger.8000.b.pid --log-file /data/todo/shared/log/passenger.8000.b.log
```

The output will be something like:

```
Could not start the Nginx engine:
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
nginx: [emerg] still could not bind()
```

Run `ls -lah /tmp`. Just like with step 3 you'll see that a new passenger-standalone directory was created and not cleaned up

**Question 2: Passenger version and integration mode**:

open source 5.1.4 standalone

**Question 3: OS or Linux distro, platform (including version)**:

Engine Yard Gentoo Linux 2016.06
https://support.cloud.engineyard.com/hc/en-us/articles/222896468-Engine-Yard-Gentoo-16-06-Technology-Stack

**Question 4: Passenger installation method**:

[X] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.3.3p222 MRI
Rails 4.2.0

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No

**Question 7: Anything else about your setup that we should know?**

Passenger is setup on Engine Yard Gentoo 16.06 using this chef recipe: https://github.com/engineyard/ey-cookbooks-stable-v5/tree/next-release/cookbooks/passenger5

Passenger Standalone is started by this monit script:

```
check process passenger_todo_8000
  with pidfile /data/todo/shared/pids/passenger.8000.pid
  start program = "/engineyard/bin/app_todo start" as uid deploy and gid deploy
  stop program = "/engineyard/bin/app_todo stop" as uid deploy and gid deploy
  if mem > 255.0 MB for 2 cycles then restart
  group todo
```

The monit script runs `/engineyard/bin/app_todo` which looks like this: https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/passenger5/templates/default/app_control.erb

monit checks Passenger and if it detects that it is not running then it attempts to start Passenger. This happens every 30 seconds. If there is a failure somewhere then monit can end up repeatedly starting Passenger, and left like this over time there will be thousands of passenger-standalone.* directories and can lead up to exhaustion of disk inodes.

The problem can be avoided by improving the monit check and adding some checks in the `/engineyard/bin/app_todo` script. But under the principle of "Passenger should clean up after itself" I believe this is also a Passenger bug that needs to be reported and addressed.

**Comment by CamJN** [comment]
This does look like something we could improve on.

**Comment by scottsherwood** [comment]
Hi @CamJN 

Has there been any progress on this. 

We too have experienced issues with this causing the site to fail and are keen to get a fix put in place.

Thanks
Scott

**Comment by CamJN** [comment]
I've got a branch with a fix for this now: https://github.com/phusion/passenger/tree/GH1953_temp_dir_cleanup hopefully it can get merged before the next release.

**Comment by scottsherwood** [comment]
That's great, thanks @CamJN
