### ISSUE TITLE
APT package for Debian 7 wheezy Moved Permanently

### ISSUE THREAD

**Issue by cptncrnch** [phusion/passenger#1957]
I am attempting to install passenger through APT and am getting an error during `apt-get update` that says: 

> Failed to fetch http://oss-binaries.phusionpassenger.com/apt/passenger/dists/wheezy/main/binary-armhf/Packages  301  Moved Permanently

In order for APT to hit the package I changed the entry in `/etc/apt/sources.list.d/passenger.list` to HTTP `http://oss-binaries.phusionpassenger.com/apt/passenger wheezy main` because HTTPS causes another error: `Unable to locate package passenger`.

I have installed the Phusion Passenger PGP keys, `apt-transport-https`, and `ca-certificates`. I have tried `apt-get clean`.

passenger open source + nginx 1.10.1
Debian 7 (Raspberry Pi 2)
Passenger installation method: Phusion APT repo
Ruby 1.9.3, RVM 1.26.11

**Comment by CamJN** [comment]
The response codes are a bit annoying but the root problem is that we don't create arm packages.
