### ISSUE TITLE
Passenger says Cert in Keychain "can't be removed"... but it's not there in the first place, "function parameters not valid" error

### ISSUE THREAD

**Issue by lydianblues** [phusion/passenger#1958]
Running Mac OS Sierra (10.12.5), and my Keychain Access app shows that there is NO Passenger Certificate installed.  Passenger generates a few error messages in the apache2 error_log:

Mac OS Sierra:                                 10.12.5
Keychain Access app:                      9.0 (55208.60.1)
Phusion Passenger Open Source:   5.1.5
Apache2:                                           2.4.25

Perhaps the telling line is the last one: "Parameters passed to a function were not valid"...
Here is the apache2 log:

[ 2017-06-22 09:28:45.8381 13956/0x7fffbc8063c0 age/Cor/CoreMain.cpp:1080 ]: Starting Passenger core...
[ 2017-06-22 09:28:45.8390 13956/0x7fffbc8063c0 age/Cor/CoreMain.cpp:248 ]: Passenger core running in multi-application mode.
[ 2017-06-22 09:28:45.8567 13956/0x7fffbc8063c0 age/Cor/CoreMain.cpp:830 ]: Passenger core online, PID 13956
[ 2017-06-22 09:28:45.8689 13958/0x7fffbc8063c0 age/Ust/UstRouterMain.cpp:537 ]: Starting Passenger UstRouter...
[ 2017-06-22 09:28:45.8728 13958/0x7fffbc8063c0 age/Ust/UstRouterMain.cpp:350 ]: Passenger UstRouter online, PID 13958
[Thu Jun 22 09:28:45.875402 2017] [mpm_prefork:notice] [pid 26943] AH00163: Apache/2.4.25 (Unix) PHP/7.1.6 Phusion_Passenger/5.1.5 configured -- resuming normal operations
[Thu Jun 22 09:28:45.875427 2017] [core:notice] [pid 26943] AH00094: Command line: '/usr/local/apache2/bin/httpd'
[ 2017-06-22 09:28:47.8806 13956/0x700000d6a000 Crypto.cpp:987 ]: Passenger client certificate was found  in the keychain unexpectedly, skipping security update check. Please remove the private key from the certificate labeled Phusion Passenger Open Source in your keychain.
[ 2017-06-22 09:28:47.8807 13956/0x700000d6a000 age/Cor/SecurityUpdateChecker.h:344 ]: Security update check failed: Problem with the local SSL certificate at /opt/passenger/passenger-5.1.5/resources/update_check_client_cert.p12 (try upgrading or reinstalling Passenger) (next check in 24 hours)
[ 2017-06-22 09:28:47.8809 13956/0x700000d6a000 Crypto.cpp:987 ]: Removing Passenger Cert from keychain  failed: One or more parameters passed to a function were not valid.. Please remove the certificate labeled Phusion Passenger Open Source in your keychain.

**Comment by CamJN** [comment]
It's possible that the certificate/private key pair diverged in your keychain, can you check your "keys" section of your keychain for one or more keys whose names are just 8 hexadecimal characters? If you find any, you can trying this procedure:

- stop apache
- for each key:
  - open the key's "get info" window in keychain
  - switch to the "access control" tab
  - if the application list includes PassengerAgent:
    - close the "get info" window
    - delete the key

**Comment by lydianblues** [comment]
Yes, CAmJN's comment fixed the problem.  Thank-you.  How did that key get there in the first place, this is a brand-new mac...

**Comment by CamJN** [comment]
Honestly there is a very long list of reasons that can cause it, the keychain api is very hard to use robustly. Usually I find that my problem is related to having upgraded passenger while apache is running and cleaned up the old install.

**Comment by cpanderson** [comment]
I've updated to Passenger 5.2, removed the key, but it generates a new one and still gives the error.

**Comment by CamJN** [comment]
@cpanderson which version of macOS are you on?

**Comment by cpanderson** [comment]
High Sierra 10.13.3

**Comment by CamJN** [comment]
Hmm odd, so am I, which integration mode are you using? And how did you install Passenger?

**Comment by cpanderson** [comment]
I installed it originally via bundler then just now did bundle update passenger to get 5.2. I have it listed in my Gemfile under development group.

**Comment by CamJN** [comment]
Hmm, the gem uses a binary compiled on an El-Cap box, I wonder if there's an issue with the security framework being different. The good news is I am moving High Sierra off of the keychain soon because it has an openssl backed curl (mavericks through sierra had a secure transport backed curl).

The bad news is that you'd have to build Passenger on High Sierra to see the benefit, which means either compiling from source or using homebrew.

**Comment by cpanderson** [comment]
Thanks for the quick replies. Whatever you think is the best solution is fine with me :) ok to live with the warning message until then.
