### ISSUE TITLE
Support for Debian stretch

### ISSUE THREAD

**Issue by lichtamberg** [phusion/passenger#1960]
Any estimations when debian stretch will be supported? It's published since ~2 weeks and now the stable version of debian. I tried already to set the sources.list.d entry to stretch, but it didn't work.

Any hints? I would need it really soon :/

**Comment by CamJN** [comment]
I don't have an estimate for you, but the changes to the way nginx is packaged in stretch are proving to be a lot of work, and are requiring significant modifications to our packaging code which is why the stretch packages are not yet available.

**Comment by lichtamberg** [comment]
Sad to hear, but thanks for your answer though..

**Comment by OnixGH** [comment]
Closed via https://github.com/phusion/passenger/commit/bab2dd09bd5804960d6c75b927d72962e00f559d

**Comment by lichtamberg** [comment]
Thank you very much!

**Comment by joaumg** [comment]
Am I missing how to get it ?

Adding `odeb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main` to `/etc/apt/sources.list.d/passenger.list` results in:

> E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger stretch Release' does not have a Release file.

And using the default passenger provided by Debian 9, I get the `5.0.30-1+b1` version... :confused:

**Comment by FooBarWidget** [comment]
The Debian 9 packages aren't released yet.

**Comment by OnixGH** [comment]
@joaumg the packages are set to be released together with the upcoming Passenger 5.1.6 release (see milestone), which we're busy working on getting out.

**Comment by CamJN** [comment]
For stretch we do not provide the nginx package, just the dynamic module. You install the regular system nginx in this case.

**Comment by sevikl** [comment]
guess you need to try to do it by yourself, 'cause, as i was saying - guide not working, regular system nginx 1.10.2 from stretch fails to load all stuff related to passenger.

**Comment by CamJN** [comment]
I just followed the instructions from the guide on a brand new debian 9 install, step by step with the only change being I installed the nginx package at the same time as passenger `sudo apt-get install -y libnginx-mod-http-passenger nginx` and it worked fine, if you'd like to report the errors you see then we can look into this further.

**Comment by CamJN** [comment]
The only errors I see are pointing out that apache isn't installed, which makes sense since you are using nginx. I did reformat the comment a bit since it was hard to read.

**Comment by sevikl** [comment]
yes, sorry about it, it is WSL issue with copying from terminal.

looks like things have changed compare to debian jessie, and simple copying previous configs not worked for me, but step-by-step reconfiguration did help. passenger start spawning processes.

so, sorry to bother you, and big thanks for assistance!
