### ISSUE TITLE
Passenger does not clean socket after shutdown

### ISSUE THREAD

**Issue by olafz** [phusion/passenger#1969]
## Issue report

**Question 1: What is the problem?**
We use passenger enterprise in standalone version and let it listen on a unix socket instead of TCP. To achieve that, the startup line is (shortened):
```
passenger start /path/to/application -e [environment] --socket /path/to/sockets/passenger.sock (...)
```
When passenger starts, it creates this socket. When passenger is shutdown, it _leaves_ the socket in place. This creates the situation that when we start passenger again, it fails with

```
Could not start the Nginx engine:
nginx: [emerg] bind() to unix:/path/to/sockets/passenger.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/path/to/sockets/passenger.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/path/to/sockets/passenger.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/path/to/sockets/passenger.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/path/to/sockets/passenger.sock failed (98: Address already in use)
nginx: [emerg] still could not bind()
```

This is behaviour that seems to have been introduced in Passenger 5.1.x, since it does not happen on Passenger 5.0.x (tested with Passenger Enterprise 5.0.30).

**Question 2: Passenger version and integration mode**:
Passenger Enterprise standalone 5.1.6

**Question 3: OS or Linux distro, platform (including version)**:
Debian Wheezy, Debian Jessie

**Question 4: Passenger installation method**:
RVM, RubyGems

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.4.1, RVM, Various rails versions (does not make a difference for issue)

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
Nope; this is it :)

**Comment by CamJN** [comment]
Looks like this is a side-effect of switching to graceful shutdown for nginx. (https://unix.stackexchange.com/a/198477)

**Comment by olafz** [comment]
Thanks for fixing the issue. Could you give an estimate when version 5.1.8 is being released?

**Comment by CamJN** [comment]
we don't currently have a date set for the 5.1.8 release. There are more changes that are being considered for inclusion which need more testing before we can set a timeline.
