### ISSUE TITLE
not passenger issue (was: ActionCable would not work on production with Passenger)

### ISSUE THREAD

**Issue by taharushain** [phusion/passenger#1971]
My ActionCable setup works perfectly in the development environment but it fails in production. I don't get any errors or something, even the logs show that the broadcast was generated but no such broadcast is received at the client. Maybe the consumer is not being created.

For the server, I am using Nginx and Passenger to manage and deploy my app into Amazon Lightsail VM.

I have been through this passenger guide and many others [Integrating Action Cable with Passenger + Nginx ](https://www.phusionpassenger.com/library/config/nginx/action_cable_integration/#running-the-action-cable-server-on-a-different-host-or-port) but the problem still persists.

My cable.yml looks like this

```
production:
  adapter: redis
  url: redis://localhost:6379

local: &local
  adapter: redis
  url: redis://localhost:6379

development: *local
test: *local
```

My routes.rb has this line
	`mount ActionCable.server => '/cable'`

My Nginx virtual host looks like this

```
server {

    server_name www.lordwaiter.com lordwaiter.com;
    listen 80;
    listen [::]:80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /var/www/lordwaiter/code/public;

    # Turn on Passenger
    passenger_enabled on;
    passenger_ruby /usr/local/rvm/gems/ruby-2.4.0/wrappers/ruby;

    ssl on;
    ssl_certificate /etc/ssl/cert_chain.crt;
    ssl_certificate_key /etc/ssl/private.key;

    location /cable {
        passenger_app_group_name lordwaiter_action_cable;
        passenger_force_max_concurrent_requests_per_process 0;
    }


}

```
My cable.js file looks like this

```
(function() {
  this.App || (this.App = {});

  App.cable = ActionCable.createConsumer("/cable");

}).call(this);
```

My production.rb has these lines

```
config.action_cable.url = 'ws://lordwaiter.com/cable'

config.action_cable.allowed_request_origins = [ 'https://www.lordwaiter.com','https://lordwaiter.com','http://www.lordwaiter.com','http://lordwaiter.com', /http:\/\/lordwaiter.*/ ]
```

**Comment by CamJN** [comment]
Can you set the [log level](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_log_level) to 7 and provide some logs of the issue occurring?

**Comment by taharushain** [comment]
@CamJN When I try to set the log level I get an exception and nginx fails to start

Exception:
`[emerg] 29373#29373: "passenger_log_level" directive is not allowed here in /etc/nginx/sites-enabled/lordwaiter.conf:16`

My host file:

```
server {

    server_name www.lordwaiter.com lordwaiter.com;
    listen 80;
    listen [::]:80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /var/www/lordwaiter/code/public;


    # Turn on Passenger
    passenger_enabled on;
    passenger_ruby /usr/local/rvm/gems/ruby-2.4.0/wrappers/ruby;
    passenger_log_level 7;

    ssl on;
    ssl_certificate /etc/ssl/cert_chain.crt;
    ssl_certificate_key /etc/ssl/private.key;

    location /cable {
        passenger_app_group_name lordwaiter_action_cable;
        passenger_force_max_concurrent_requests_per_process 0;
    }


}

```

**Comment by CamJN** [comment]
Per the docs: `passenger_log_level` goes in the http block not the server block.

**Comment by taharushain** [comment]
@CamJN Please have a look at these logs https://pastebin.com/GNinw7Ez

**Comment by DaniG2k** [comment]
Follow. Experiencing the same problem here.

**Comment by CamJN** [comment]
@taharushain so no requests made it to the ws uri. Does your browser's js console print any errors when the ws connection is attempted?

**Comment by taharushain** [comment]
No, there is nothing on my browsers. Normally, when I run it locally in the development environment, I could see a WebSocket connection being made in the Networks tab but even that does not happen and there are no errors on the console.

**Comment by CamJN** [comment]
If there's no connection made then it is almost certainly a case of your browser blocking the connection to the websocket for security reasons. WS connections are heavily scrutinized and are only allowed in very specific configurations. Which browser are you testing with primarily?

**Comment by taharushain** [comment]
I am using Google Chrome, Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by CamJN** [comment]
One thing I notice is that your websocket url is unencrypted (ws://lordwaiter.com/cable) and your nginx config is using https, that isn't allowed. They both have to be encrypted (or both not). You want to use the wss protocol.

**Comment by DaniG2k** [comment]
I can also confirm I am using `config.action_cable.url = 'wss://my_app.com/cable'` and it seems to be ok now.

**Comment by taharushain** [comment]
@CamJN I removed all the SSH settings from my configurations so that everything is unencrypted but still no luck.

**Comment by taharushain** [comment]
@DaniG2k I don't have sidekiq in my application so I don't think that should prevent actioncable to work

**Comment by CamJN** [comment]
@taharushain I assume you mean SSL settings, SSH is something else. As for why it's still not working, that could be any number of things, I highly recommend reading about the restrictions browsers place on websockets. Chrome (and other browsers) will "preflight" a complex cross-origin request by sending an OPTIONS request. Perhaps because you server your site both with and without the `www` subdomain, you may be running into that issue. A quick google says that websockets do not require CORS headers in Chrome, but the OPTIONS request certainly will, and it's a prerequisiste to the websocket request.

**Comment by taharushain** [comment]
Oh yes, I meant SSL and it was a typo. Thanks for pointing that out. Supposing I would need to serve my site with both www and without www sub-domain, what would you suggest that I could do given my situation?

**Comment by CamJN** [comment]
As I mentioned, you'll need to send the CORS headers in response to the OPTIONS request.
