### ISSUE TITLE
debian 8 jessie Hash Sum mismatch error

### ISSUE THREAD

**Issue by antonovga** [phusion/passenger#1972]
Hi,
there is some problem updating passenger repository on debian jessie

`W: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch`

I've tried 

- updating apt
- apt-get clean 
- manually removing apt partials
- reinstalling keys as written in installation guide here https://www.phusionpassenger.com/library/install/nginx/install/oss/jessie/

nothing helped.

So question is how to upgrade passenger on debian 8?
Thanks in advance.

**Comment by OnixGH** [comment]
We just released 5.1.8 and there were still some old values cached by the repo software. Should be OK now.

**Comment by antonovga** [comment]
Tried again: everything works as intended.
Thank you.
