### ISSUE TITLE
Not a Passenger Issue (was: error when running alt-mod-passenger along with apache in cloudlinux OS)

### ISSUE THREAD

**Issue by hendranata** [phusion/passenger#1974]
## Issue report

**Question 1: What is the problem?**
the problem is cant run nodejs with mod_passenger

**Question 2: Passenger version and integration mode**:

Your answer: i am using passenger-5.0.30-5.el7.cloudlinux

**Question 3: OS or Linux distro, platform (including version)**:

Your answer: cloudlinux 7.3

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ x] Other, please specify: using cpanel/WHM from easyapache4

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer: node.js 6.11.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer: no

**Question 7: Anything else about your setup that we should know?**

Your answer: here is the error message:
<pre>
module.js:471
    throw err;
    ^

Error: Cannot find module &apos;vendor-copy/network-byte-order&apos;
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (/opt/passenger-5.0.30-5.el7.cloudlinux/src/nodejs_supportlib/phusion_passenger/ustrouter_connector.js:29:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
</pre>

i dont know why.. we just simply run hello world script.
```
var http = require('http');
var server = http.createServer(function(req, res) {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end("hello world!\n");
});
```

**Comment by CamJN** [comment]
You can see the `ustrouter_connector.js` is being loaded, which tries to load the `network-byte-order` module from `/opt/passenger-5.0.30-5.el7.cloudlinux/src/nodejs_supportlib/vendor-copy/network-byte-order`. That should be in the path because of the line `module.paths.unshift(__dirname + "/../src/nodejs_supportlib");` in the node loader. You should investigate the node environment and why the module paths are wrong.

A few things, we don't provide support EasyApache, or packages we did not create, and the current version of Passenger is 5.1.8.

**Comment by hendranata** [comment]
there is no folder in here /opt/passenger-5.0.30-5.el7.cloudlinux/src/nodejs_supportlib/vendor-copy/

i have update passanger version: passenger-5.1.6-1.el7.cloudlinux

ane run here: /opt/alt/ruby24/bin/ruby /opt/passenger-5.1.6-1.el7.cloudlinux/bin/passenger-install-apache2-module

and error message here:
Compiling and installing Apache 2 module...
cd /opt/passenger-5.1.6-1.el7.cloudlinux
# env NOEXEC_DISABLE=1 /opt/alt/ruby24/bin/ruby /opt/alt/ruby24/bin/rake RELEASE=yes apache2:clean apache2
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)

--------------------------------------------

It looks like something went wrong

**Comment by CamJN** [comment]
It looks like the package isn't properly made, since `/opt/passenger-5.0.30-5.el7.cloudlinux/src/nodejs_supportlib/vendor-copy/` doesn't exist, and then the rakefile is missing in the newer version.

I'd recommend reporting this to cloudlinux who maintains those packages.

**Comment by hendranata** [comment]
does anyone face same situation?

i also try another possibility and run this "/opt/passenger-5.0.30-5.el7.cloudlinux/bin/passenger-install-apache2-module"

error message:

Compiling and installing Apache 2 module...
cd /opt/passenger-5.0.30-5.el7.cloudlinux
# env NOEXEC_DISABLE=1 /usr/local/rvm/gems/ruby-2.4.0/wrappers/rake RELEASE=yes apache2:clean apache2
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
