### ISSUE TITLE
Request not load balancing well

### ISSUE THREAD

**Issue by choonggg** [phusion/passenger#1976]
## Issue report

Request not being load balanced well, I shared a screenshot of our status below.

The requests get piled up for a few moments then start dropping after a few seconds. Somethings it stays there for a few seconds before starting to process the request, you can see there are processes idling while request piles up.

We've been getting the occasional 504 timeouts from our users.

<img width="631" alt="screen shot 2017-09-07 at 12 35 36 pm" src="https://user-images.githubusercontent.com/3957744/30146224-695419f6-93c9-11e7-94ab-f23c4cdc135a.png">

Passenger version: 5.1.3 open source
Ruby: 2.3.3
Rails: 4.2.8

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
4.4.0-93-generic

Using cloud66 as PaaS to deploy

**Comment by CamJN** [comment]
Does this still occur with Passenger 5.1.8?

**Comment by choonggg** [comment]
our PaaS isn't flexible in upgrading so we were unable to move forward to 5.1.8. We've moved to another server and we're stable now. Cheers
