### ISSUE TITLE
Support for new Gemfile name (gems.rb)

### ISSUE THREAD

**Issue by dhampik** [phusion/passenger#1982]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
Rails application should work when `gems.rb` and `gems.locked` files are used instead of `Gemifle` and `Gemfile.lock`. Please refer to https://github.com/bundler/bundler/issues/694 regarding support of new filenames.
- What is the actual behavior?
Rails application does not start with passenger
- How can we reproduce it?
Just run any rails app under nginx+passenger and rename `Gemfile` -> `gems.rb` and `Gemfile.lock` -> `gems.locked`. Then restart web-server and application will fail to start with an error like
~~~
App 14417 stdout:
[ E 2017-09-22 22:46:57.0110 14383/Tb age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application ****************/current: An error occurred while starting up the preloader.
  Error ID: 6586ac10
  Error details saved to: /tmp/passenger-error-BN6KYJ.html
  Message from application: cannot load such file -- rack (LoadError)
  ****************/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  ****************/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:102:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
~~~
As soon as files are renamed back everything works fine. Locally under puma web-server application works fine with gems.rb and gems.locked

**Question 2: Passenger version and integration mode**:
open source 5.1.28 standalone, nginx 1.12.1

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
Debian 8 jessy

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[v] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.4.2, RVM, Rails 5.1.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No containerization, vps

**Comment by FooBarWidget** [comment]
Implemented now. Will be released soon as part of 5.1.9.
