### ISSUE TITLE
passenger-standalone : max-requests option seems ignored

### ISSUE THREAD

**Issue by gleonet** [phusion/passenger#1984]
## Issue report
Hi,

It seems the command line option `max-requests`is ignored since we have updated our passenger to the version 5.1.6. (we use the docker image phusion/passenger-ruby23)

We set the option max-requests to 50,000 but in the output of `passenger-status` I see some instances have served a lot more than this 50,000 requests

```
$ passenger-status 
Using /usr/local/rvm/gems/ruby-2.3.3
Version : 5.1.6
Date    : 2017-09-29 12:46:16 +0000
Instance: zKh6zChr (Phusion_Passenger/5.1.6)

----------- General information -----------
Max pool size : 14
App groups    : 1
Processes     : 14
Requests in top-level queue : 0

----------- Application groups -----------
/home/app/pointguard:
  App root: /home/app/pointguard
  Requests in queue: 0
  * PID: 295     Sessions: 0       Processed: 191418   Uptime: 2d 17h 6m 15s
    CPU: 2%      Memory  : 311M    Last used: 1s a
  * PID: 302     Sessions: 0       Processed: 33226   Uptime: 2d 17h 6m 15s
    CPU: 0%      Memory  : 132M    Last used: 1s ag
  * PID: 309     Sessions: 0       Processed: 4213    Uptime: 2d 17h 6m 15s
    CPU: 0%      Memory  : 125M    Last used: 31s a
...
```

**Passenger version and integration mode**:
open source 5.1.6 standalone (provided in docker image phusion/passenger-ruby2.3)

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 16.04.2 LTS

**Comment by OnixGH** [comment]
This is [already fixed](https://github.com/phusion/passenger/commit/890c294f70302d373166ed7f18804b9f052f9476) in 5.1.8.
