### ISSUE TITLE
Passenger not starting with `rails server`

### ISSUE THREAD

**Issue by iainbeeston** [phusion/passenger#1987]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:

After removing `puma` and adding `passenger` to the Gemfile on a ruby on rails project, running `bin/rails server` in a should start phusion passenger. This is mentioned in several places on the phusion passenger documentation site (eg. [here](https://www.phusionpassenger.com/library/walkthroughs/basics/ruby/fundamental_concepts.html#passenger-and-rails-server)).

Instead running `bin/rails server` starts the default webserver (webrick) instead. Even if it's not selected as the default webserver, it should be possible to select it as the webserver by running `bin/rails server phusion_passenger`, but that doesn't work either and I get the following error:

    /Users/iain/.gem/ruby/2.4.2/gems/rack-2.0.3/lib/rack/handler.rb:74:in `require': cannot load such file -- rack/handler/phusion_passenger (LoadError)

Running passenger manually using the `passenger start` command works fine.

I've reproduced in a sample app [here](https://github.com/iainbeeston/passenger-test). Check it out, run `bundle install` then `bin/rails server` should start passenger.

It seems that the passenger rack handler is not loaded by default. If instead I explicitly tell bundler to load the rack handler (ie. add `gem 'passenger', require: ['phusion_passenger', 'phusion_passenger/rack_handler']` to the gemfile) then it works.

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:

> passenger --version
Phusion Passenger 5.1.8

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:

Mac OS Sierra 10.12.6.

**Question 4: Passenger installation method**:

Your answer:
[x] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:

Ruby 2.4.2, Rails 5.1.4, ruby-install 0.6.1, chruby 0.3.9

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:

No, I'm running this through the Terminal app of my mac, in development.

**Question 7: Anything else about your setup that we should know?**

Your answer:

I don't think so.

**Comment by OnixGH** [comment]
Did you add [the full line that is necessary](https://www.phusionpassenger.com/library/walkthroughs/start/ruby.html#updating-your-gem-bundle) to your Gemfile?

**Comment by iainbeeston** [comment]
Sorry, my bad - I had read the instructions [here](https://www.phusionpassenger.com/library/walkthroughs/basics/ruby/fundamental_concepts.html#passenger-and-rails-server) which said it should work automatically. As mentioned in my issue report, adding that line does fix the problem

**Comment by OnixGH** [comment]
No problem, in the page you pointed to we assume that you've read the previous tutorial (Quickstart) where it is explained what adding Passenger to the Gemfile entails, but to make it extra clear I've [added a backlink](https://github.com/phusion/passenger_library/commit/05a6f45e21f864b5d1c3ac1a475d9ec2de58ede4) now.
