### ISSUE TITLE
Update the Wiki please

### ISSUE THREAD

**Issue by rorschach217** [phusion/passenger#1988]
Phusion Passenger: Meteor tutorial wiki  

4. Deploying to production  
Uploading a Meteor bundle:  

```
meteor bundle leaderboard.tar.gz
```

this section needs to be updated because meteor 1.5.x.x tells meteor bundle is deprecated.

**Comment by CamJN** [comment]
What's the url of the page with the problem?

**Comment by OnixGH** [comment]
I think he means the GitHub wiki: https://github.com/phusion/passenger/wiki/Phusion-Passenger%3A-Meteor-tutorial

**Comment by CamJN** [comment]
Done
