### ISSUE TITLE
Passenger 5.1.11 Ubuntu 12.04 Precise Packages

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1992]
It would be great if Ubuntu 12.04 Precise packages for Passenger 5.1.11 could be released.

Precise packages are currently still at 5.1.10, while 5.1.11 for Xenial was release a few days ago.

**Comment by OnixGH** [comment]
The minimum Ubuntu version that is publicly supported by Canonical is 14.04 (12.04 was EOL'd), our packages mirror that.

**Comment by felixbuenemann** [comment]
@OnixGH 12.04 was EOL'd in April 2017 (and still gets security updates through ESM), 5.1.10 was releases 8 days ago and is available for Precise, 5.1.11 contains an important security fix, so I can't quite follow your reasoning.

**Comment by OnixGH** [comment]
Yeah it looks a little weird because (special exception) we released the fix first for Enterprise only (5.1.10 Open Source == 5.1.8).

We had already dropped support a while ago in stable, and that change was released together with the other accumulated work in 5.1.11.
