### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by TemporarilyOffline** [phusion/passenger#1993]
## Issue report

Following the instructions on the official website results in a non-running installation.   Sometimes I will get a message "Unknown directive 'passenger_root'", sometimes not.

**Question 1: What is the problem?**
pooched install
- What is the expected behavior?
happy install
- What is the actual behavior?
ugly error messages
- How can we reproduce it? 

Follow these instructions:

https://www.phusionpassenger.com/library/install/nginx/install/oss/zesty/

**Question 2: Passenger version and integration mode**:

$ passenger -v
Phusion Passenger 5.1.11

**Question 3: OS or Linux distro, platform (including version)**:

Ubuntu 17.04

**Question 4: Passenger installation method**:

https://www.phusionpassenger.com/library/install/nginx/install/oss/zesty/

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby/Rails, but haven't gotten that far yet.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No

**Question 7: Anything else about your setup that we should know?**

This is a clean install of Ubuntu 17.04
---

**Comment by CamJN** [comment]
What does your `/etc/nginx/conf.d/mod-http-passenger.conf` file contain? And what does `nginx -t -c /etc/nginx/nginx.conf` print?

**Comment by TemporarilyOffline** [comment]
I figured it out, thanks!
