### ISSUE TITLE
Signal.trap USR2 doesn't work with Passenger

### ISSUE THREAD

**Issue by kevgrig** [phusion/passenger#1997]
## Issue report

**Question 1: What is the problem?**

`kill -USR2 ${PID_OF_PASSENGER}` causes Passenger to restart instead of allowing my Rails app to handle it.

I have the following code in Rails to enhance diagnostics by allowing a SIGUSR2 signal to dump all thread stacks:

    Signal.trap "USR2" do
      # Thread might be needed because of https://bugs.ruby-lang.org/issues/7917
      Thread.new do
        Rails.logger.warn{"kill -USR2 received @ #{Time.now}"}
        ObjectSpace.each_object(Thread) do |th|
          Rails.logger.warn{"ThreadInfo id: #{th}, name: #{th.name}, status: #{th.status}\n\t" + th.backtrace.join("\n\t")}
        end
      end
    end

Running `kill -USR2 ${PID}` works fine on my local `Thin` development server and also on the same production box where Passenger is running a background [delayed_job](https://github.com/collectiveidea/delayed_job/) raw Ruby process.

First, find a Passenger RubyApp process:

```
# ps -elf | grep Passenger | grep -v grep | awk '{print $4,$15,$16}'
9747 Passenger watchdog
9750 Passenger core
9842 Passenger RubyApp:
9867 Passenger RubyApp:
```

Next, send USR2 to one of them:

    # kill -USR2 9842

There is no Rails output; instead, `passenger.log` shows the following and the RubyApp worker restarts:

```
[ W 2017-10-28 18:14:10.0243 9750/Tb age/Cor/App/Poo/AnalyticsCollection.cpp:102 ]: Process (pid=9842, group=[...]) no longer exists! Detaching it from the pool.
[ N 2017-10-28 18:14:10.0244 9750/Tb age/Cor/CoreMain.cpp:994 ]: Checking whether to disconnect long-running connections for process 9842, application [...]
```

Searching both [phusionpassenger.com](https://encrypted.google.com/search?hl=en&q=site%3Aphusionpassenger.com%20%22usr2%22) and [Github](https://github.com/phusion/passenger/search?utf8=%E2%9C%93&q=%22USR2%22&type=) shows no results for Passenger handling USR2.

**Question 2: Passenger version and integration mode**:

Open source 5.1.11/nginx

**Question 3: OS or Linux distro, platform (including version)**:

Linux 4.4.0-97-generic <span>#</span>120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[X] Other, please specify:

```
gem install passenger -N
./configure --user=nginx --group=nginx --prefix=${nginx_root} \
        --with-http_ssl_module --with-pcre --with-http_gzip_static_module \
        --add-module=$(passenger-config --nginx-addon-dir) \
        --add-module=/usr/local/src/nginx-upload-module \
        --with-debug
```

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.3.1, Rails 5.1.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No, just a VPS on Digital Ocean

**Question 7: Anything else about your setup that we should know?**

```
# passenger-config about version
Phusion Passenger 5.1.11
```

`passenger.conf`:

```
passenger_root ${cubevar_nginx_passenger_root};
passenger_ruby /usr/bin/ruby;
passenger_max_pool_size ${cubevar_app_rails_threads_per_node};
passenger_min_instances ${cubevar_app_rails_threads_per_node};

# https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/
# Easier to reason about memory usage with direct
passenger_spawn_method direct;

passenger_buffer_response on;
passenger_max_instances_per_app 0;
passenger_pool_idle_time 300;
passenger_max_requests 0;
passenger_instance_registry_dir /var/run/;
passenger_pre_start http://127.0.0.1/;
passenger_start_timeout 240;
passenger_user root;
passenger_group root;
```

**Comment by OnixGH** [comment]
Are you aware of the [backtrace functionality](https://www.phusionpassenger.com/library/admin/nginx/overall_status_report.html#dealing-with-common-request-related-problems) (using SIGQUIT) already in Passenger?

**Comment by CamJN** [comment]
While your exact commands seem fine, some of your description seems a bit loose with respect to which processes are app processes. Specifically these sections:
> `kill -USR2 ${PID_OF_PASSENGER}` causes Passenger to restart instead of allowing my Rails app to handle it.

> Next, send USR2 to one of them

You need to target an app process not just a Passenger process. You can be sure you are dealing with an app process with `passenger-memory-stats | fgrep Ruby | awk '{print $1}'`. 

A restart on USR2 is the default behavior of nginx, so the signal handling is being inherited from there. Luckily like @OnixGH said, you can use SIGQUIT instead.

**Comment by kevgrig** [comment]
Wonderful, I wasn't aware of the `SIGQUIT` support. Thanks!
