### ISSUE TITLE
Since 5.1.8 - Passenger in docker images isn't logging Rails logs to STDOUT

### ISSUE THREAD

**Issue by fourseven** [phusion/passenger#1999]
**Question 1: What is the problem?**

Your answer:
- What is the expected behavior?
Passenger logs rails logs to STDOUT
- What is the actual behavior?
There are no rails logs on STDOUT
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) 
I will try and create a repo as a testcase, but in the meantime it's worth logging, because we'd love to stick with Passenger (NGINX integration in a gem is awesome), but can't upgrade to the security-fix release because of the logging changes in 5.1.8. I have also tested the change from #1990 but that doesn't resolve it for us.

**Question 2: Passenger version and integration mode**:

Your answer: 
Open source 5.1.8 (gem, standalone) and greater (works in 5.1.5, for example)

**Question 3: OS or Linux distro, platform (including version)**:

Your answer:
Official ruby docker images (2.3.4 in particular)

**Question 4: Passenger installation method**:

Your answer:
[x] RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer: 
Ruby 2.3.4, Rails 5.1.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**]

Your answer:
Docker (Elastic beanstalk multi-container), based on official ruby 2.3.4 images. Can reproduce with our built docker image, locally.

**Question 7: Anything else about your setup that we should know?**

Your answer:
We're using lograge, and docker logs are set up to log to logentries via syslog (in production). Again, can reproduce it locally without the amazon infra as well.

---

**Comment by fourseven** [comment]
Adding to myself, I'm building a minimal testcase but can't reproduce it with a clean 5.1.4 install, so I'll update when I know more (perhaps a couple of gems are interfering with logging)... Always the way!

**Comment by fourseven** [comment]
Okay, I have isolated it to `rails_stdout_logging` - which didn't conflict in earlier versions, but does from 5.1.8 onwards. Feel free to close, it's not needed from Rails 5.x anyway (but hadn't been removed in our case). Hopefully if someone else encounters this the suggested resolution (remove `rails_stdout_logging`) will help.

**Comment by fourseven** [comment]
To add to this, having the `RAILS_LOG_TO_STDOUT` env variable set with standard logging configuration (see https://github.com/heroku/rails_stdout_logging#migrating-to-rails-5 ) breaks it too.

**Comment by fourseven** [comment]
Here's my demo repo - it currently logs, but the readme shows two ways to (unexpectedly) break it - https://github.com/fourseven/passenger-logging

**Comment by CamJN** [comment]
You have the log level set to 1/error in your Passengerfile.json, that log level does not include app logs, if you set the log level to 3/notice it will work, even with `RAILS_LOG_TO_STDOUT`.
