### ISSUE TITLE
Passenger + nginx not working 

### ISSUE THREAD

**Issue by psantos10** [phusion/passenger#2001]
## Issue report

Today I setup a server with Nginx and Passenger to run a Rails app.
When I try to visit the app URL, I see this: `We're sorry, but something went wrong.`.

So I go check the logs: `/var/log/nginx/error.log` and I found this:

> [ E 2017-11-22 18:08:01.7099 3567/Ta age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-19] Cannot checkout session because a spawning error occurred. The identifier of the error is 1197f7ce. Please see earlier logs for details about the error.
> 2017/11/22 18:08:01 [error] 3581#3581: *116 recv() failed (104: Connection reset by peer) while reading upstream, client: xxx.xxx.xxx.xxx, server: my.domain.com, request: "POST / HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.pImcPYe/agents.s/core:", host: "xxx.xxx.xxx.xxx"
> App 4908 stdout:
> App 4908 stderr:  [passenger_native_support.so] trying to compile for the current user (USERNAME) and Ruby interpreter...
> App 4908 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
> App 4908 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
> App 4908 stderr:      /tmp/passenger_native_support-1l5gohi.log
> App 4908 stderr:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
> App 4908 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
> App 4908 stderr:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.1.11/rubyext-ruby-2.4.2-x86_64-linux.tar.gz: no download tool found (curl or wget required)
> App 4908 stderr:      Trying next mirror...
> App 4908 stderr:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.1.11/rubyext-ruby-2.4.2-x86_64-linux.tar.gz: no download tool found (curl or wget required)
> App 4908 stderr:  [passenger_native_support.so] will not be used (can't compile or download)
> App 4908 stderr:   --> Passenger will still operate normally.
> App 4908 stderr: sh: 1: env: not found
> App 4908 stdout:
> [ E 2017-11-22 18:08:03.3107 3567/T3b age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/username/myapps/blog/current: An error occurred while starting up the preloader.
>   Error ID: 59e69c39
>   Error details saved to: /tmp/passenger-error-sjyBYQ.html
>   Message from application: There was an error while trying to load the gem 'uglifier'.
> Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
> Backtrace for gem load error is:
> /home/username/myapps/blog/shared/bundle/ruby/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'

What I can see in this log is... first, it is complans that curl or wget is not installed (`no download tool found (curl or wget required)`). But it is. I was able to confirm: 

> username@hostname:~$ curl --version
> => curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3

and

> username@hostname:~$ wget --version
> => GNU Wget 1.17.1 built on linux-gnu.

Second, it says: `sh: 1: env: not found`. But also I can confirm that `env` exists:

> username@hostname:~$ which env
> => /usr/bin/env
> username@hostname:~$ env --version
> => env (GNU coreutils) 8.25

Third, it also says: `Could not find a JavaScript runtime`. but I have nodejs installed:

> username@hostname:~$ node -v
> => v8.9.1
> username@hostname:~$ nodejs -v
> => v8.9.1
> username@hostname:~$ npm -v
> => 5.5.1

I followed the instructions described here: https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/nginx/oss/xenial/install_passenger.html 
The difference is that I am using rbenv instead of rvm.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

**Question 2: Passenger version and integration mode**:
- Open source 5.1.11/nginx

**Question 3: OS or Linux distro, platform (including version)**:
- Ubuntu 16.04 LTS Xenial

**Question 4: Passenger installation method**:

[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- Ruby 2.4.2, rbenv 1.1.1-6-g2d7cefe, Rails 5.1.4; Node.js 8.9.1

**Question 7: Anything else about your setup that we should know?**
- This is not the first time to setup a server with nginx + passenger. but it is the first time getting this error. I always follow the same steps. I cant figure out what I am missing

**Comment by CamJN** [comment]
Looks like the `PATH` envvar got clobbered, please set the `passenger_log_level` (https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_log_level) to 7 and look for the logs of the bash scripts that are executed before the webapp is started.

**Comment by psantos10** [comment]
@CamJN  this is the result:

> [ D 2017-11-22 18:40:30.3437 6644/Tn age/Cor/Spa/SmartSpawner.h:280 ]: Preloader process forked for appRoot=/home/username/myapps/blog/current: PID 6756
> App 6756 stderr: + '[' '' ']'
> App 6756 stderr: + '[' -d /etc/profile.d ']'
> App 6756 stderr: + for i in '/etc/profile.d/*.sh'
> App 6756 stderr: + '[' -r /etc/profile.d/bash_completion.sh ']'
> App 6756 stderr: + . /etc/profile.d/bash_completion.sh
> App 6756 stderr: ++ '[' -n '4.3.48(1)-release' -a -n '' -a -z '' ']'
> App 6756 stderr: + for i in '/etc/profile.d/*.sh'
> App 6756 stderr: + '[' -r /etc/profile.d/cedilla-portuguese.sh ']'
> App 6756 stderr: + . /etc/profile.d/cedilla-portuguese.sh
> App 6756 stderr: ++ '[' '' = pt -a '' '!=' pt ']'
> App 6756 stderr: + unset i
> App 6756 stderr: + '[' -n '4.3.48(1)-release' ']'
> App 6756 stderr: + '[' -f /home/username/.bashrc ']'
> App 6756 stderr: + . /home/username/.bashrc
> App 6756 stderr: ++ case $- in
> App 6756 stderr: ++ return
> App 6756 stderr: + PATH=/home/username/bin:/home/username/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.
> App 6756 stderr: + exec /usr/lib/passenger/support-binaries/PassengerAgent spawn-preparer /home/username/myapps/blog/current SU5fUEFTU0VOR0VSADEAUFlUSE9OVU5CVUZGRVJFRAAxAE5PREVfUEFUSAAvdXNyL3NoYXJlL3Bhc3Nlbmdlci9ub2RlAFJBSUxTX0VOVgBwcm9kdWN0aW9uAFJBQ0tfRU5WAHByb2R1Y3Rpb24AV1NHSV9FTlYAcHJvZHVjdGlvbgBOT0RFX0VOVgBwcm9kdWN0aW9uAFBBU1NFTkdFUl9BUFBfRU5WAHByb2R1Y3Rpb24A /home/username/.rbenv/versions/2.4.2/bin/ruby /home/username/.rbenv/versions/2.4.2/bin/ruby /usr/share/passenger/helper-scripts/rack-preloader.rb
> App 6756 stdout:
> [ D 2017-11-22 18:40:30.4691 6644/Tn age/Cor/Spa/Spawner.h:706 ]: [App 6756 stdout] !> I have control 1.0
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] You have control 1.0
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] passenger_root: /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] ruby_libdir: /usr/lib/ruby/vendor_ruby
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] passenger_version: 5.1.11
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] UNIX_PATH_MAX: 108
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] connect_password: PaEa6w3pSve8hhcg
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] instance_dir: /tmp/passenger.JLpCXGE
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] socket_dir: /tmp/passenger.JLpCXGE/apps.s
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] app_root: /home/username/myapps/blog/current
> [ D 2017-11-22 18:40:30.4693 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] app_group_name: /home/username/myapps/blog/current
> [ D 2017-11-22 18:40:30.4694 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] app_type: rack
> [ D 2017-11-22 18:40:30.4694 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] start_command: /home/username/.rbenv/versions/2.4.2/bin/ruby	/usr/share/passenger/helper-scripts/rack-loader.rb
> [ D 2017-11-22 18:40:30.4694 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] startup_file: /home/username/myapps/blog/current/config.ru
> [ D 2017-11-22 18:40:30.4694 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] process_title: Passenger RubyApp
> [ D 2017-11-22 18:40:30.4694 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] log_level: 7
> [ D 2017-11-22 18:40:30.4694 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] start_timeout: 90000
> [ D 2017-11-22 18:40:30.4694 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] environment: production
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] base_uri: /
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] spawn_method: smart
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] default_user: nobody
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] default_group: nogroup
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] integration_mode: nginx
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] ruby: /home/username/.rbenv/versions/2.4.2/bin/ruby
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] python: python
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] nodejs: node
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] ust_router_username: logging
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] debugger: false
> [ D 2017-11-22 18:40:30.4695 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] analytics: false
> [ D 2017-11-22 18:40:30.4696 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>] api_key: PaEa6w3pSve8hhcg
> [ D 2017-11-22 18:40:30.4696 6644/Tn age/Cor/Spa/SmartSpawner.h:388 ]: [App 6756 stdin >>]
> App 6756 stderr:  [passenger_native_support.so] trying to compile for the current user (username) and Ruby interpreter...
> App 6756 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
> App 6756 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
> App 6756 stderr:      /tmp/passenger_native_support-99x18v.log
> App 6756 stderr:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
> App 6756 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)

**Comment by psantos10** [comment]
I dont know it this is the corrent way, but addinf `env PATH` at the top of `/var/nginx/nginx.conf` file, solved the problem
