### ISSUE TITLE
Hash Sum mismatch error on Passenger Jessie installation

### ISSUE THREAD

**Issue by anthonydjones** [phusion/passenger#2002]
**Question 1: What is the problem?**

When trying to install Passenger on Debian 8 I encounter a 'Hash Sum mismatch' error downloading the index.

The installation is following the guide in the Passenger Library.

Here is a Dockerfile to help reproduce and the resulting error.
```
FROM debian:jessie
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates dirmngr gnupg
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 && \
		sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger jessie main > /etc/apt/sources.list.d/passenger.list' && \
		apt-get update && \
		apt-get install -y nginx-extras passenger
```
```
W: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Question 2: Passenger version and integration mode**:

Latest Passenger version in the repo.

**Question 3: OS or Linux distro, platform (including version)**:

Debian 8, x86_64

**Question 4: Passenger installation method**:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

N/A

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Using Docker 17.09.0-ce.

**Comment by OnixGH** [comment]
Verified fixed now (we just release Passenger 5.1.12, and the cache clear was still pending).
