### ISSUE TITLE
With install Ruby 2.4.3 and Passenger 5.1.12 ALL sites will fail to open

### ISSUE THREAD

**Issue by Sega100500** [phusion/passenger#2010]
With install Ruby 2.4.3 and Passenger 5.1.12 ALL sites will fail to open:

**Incomplete response received from application**

OS: Debian Linux 8.10

log-file attached (from Apache log)
[passenger.zip](https://github.com/phusion/passenger/files/1562193/passenger.zip)
[passenger.zip](https://github.com/phusion/passenger/files/1562195/passenger.zip)

**Comment by OnixGH** [comment]
Hi, this doesn't look like an issue with Passenger, but instead with Ruby, see the error message:
```
App 21106 stderr: 
  /home/ruby/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.3/lib/v8/context.rb:99: [BUG] Segmentation fault at 0x0000000000000000
App 21106 stderr: ruby 2.4.3p205 (2017-12-14 revision 61247) 
...
App 21106 stderr: [NOTE]
App 21106 stderr: You may have encountered a bug in the Ruby interpreter or extension libraries.
App 21106 stderr: Bug reports are welcome.
App 21106 stderr: For details: http://www.ruby-lang.org/bugreport.html
````

**Comment by Sega100500** [comment]
@OnixGH 

https://bugs.ruby-lang.org/issues/14188

**Comment by Sega100500** [comment]
problem still exists
https://github.com/phusion/passenger/issues/2012

**Comment by CamJN** [comment]
@Sega100500 both the above error and the error in #2012 are not Passenger errors. I highly recommend reading the errors that you see, and making an attempt to understand what they are telling you. It will be very helpful on an ongoing basis to be able to understand where a problem is coming from so you can try and find a solution from the correct developers.

**Comment by paulomcnally** [comment]
https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.1.12/rubyext-ruby-2.4.3-x86_64-linux.tar.gz

404
