### ISSUE TITLE
Exception with no backtrace causing error

### ISSUE THREAD

**Issue by PikachuEXE** [phusion/passenger#2011]
## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Are you sure this is a bug in Passenger?**
Please read our troubleshooting and debugging guides first:
https://www.phusionpassenger.com/library/admin/troubleshooting/
https://www.phusionpassenger.com/library/admin/

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
Your answer:
Error raised from within https://github.com/phusion/passenger/blob/stable-5.1/src/helper-scripts/rack-preloader.rb#L41
Since `e.backtrace` is `nil`

**Sample app**
https://github.com/PikachuEXE/passenger_issue_2011

**How to reproduce**
- Install ruby 2.5.0rc1 (or later)
- `bundle install`
- `passenger start`

**Question 2: Passenger version and integration mode**:
Your answer:
open source 5.1.12 standalone

**Question 3: OS or Linux distro, platform (including version)**:
Your answer:
OS X 10.12.6, x86_64

**Question 4: Passenger installation method**:

Your answer:
[x] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:
Ruby 2.5.0rc1 (2017-12-14 trunk 61243) [x86_64-darwin16], RVM, Rails 5.0.6

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:
NOPE

**Question 7: Anything else about your setup that we should know?**

Your answer:
NOPE

**Comment by PikachuEXE** [comment]
Sample app added

This bug is found due to and error mentioned in this issue:
https://github.com/plataformatec/devise/issues/4719

**Comment by PikachuEXE** [comment]
a similar issue:
https://github.com/rails/spring/issues/550

**Comment by dux** [comment]
remove `binding_of_caller` in ruby 2.5, whenever defined. that could help (helped me)
