### ISSUE TITLE
passenger-install-apache2-module compilation fails with 'No rule to make target' for passenger_native_support.o

### ISSUE THREAD

**Issue by jamesbebbington** [phusion/passenger#2015]
Hi,

**Question 1: What is the problem?**
Having upgraded from Sierra to High Sierra and attempting to update from Passender 4.X to 5.X via Homebrew, when attempting to upgrade the apache 2 module I'm receiving the following error:

```
$ passenger-install-apache2-module

…

Checking whether there are multiple Apache installations...
Only a single installation detected. This is good.

--------------------------------------------
Compiling and installing Apache 2 module...

…

cd 'buildout/ruby/ruby-2.3.3-universal-macosx/' && make
make: *** No rule to make target `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby.h', needed by `passenger_native_support.o'.  Stop.
rake aborted!
Command failed with status (2): [cd 'buildout/ruby/ruby-2.3.3-universal-mac...]
/usr/local/Cellar/passenger/5.1.12/libexec/build/ruby_extension.rb:50:in `block in <top (required)>'
Tasks: TOP => apache2 => buildout/ruby/ruby-2.3.3-universal-macosx/passenger_native_support.bundle
```

**Question 2: Passenger version and integration mode**:
Open Source 5.1.12/Apache

**Question 3: OS or Linux distro, platform (including version)**:
macOS High Sierra 10.13.2

**Question 4: Passenger installation method**:
OS X Homebrew

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
ruby 2.3.3p222 
rvm 1.29.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No.

**Question 7: Anything else about your setup that we should know?**
Nothing that springs to mind.

Thanks.

**Comment by OnixGH** [comment]
Did you check the [install documentation](https://www.phusionpassenger.com/library/install/apache/)?

**Comment by jamesbebbington** [comment]
Hey @OnixGH, I did check out the [Migrating from Passenger 4 to 5 (Apache version)](https://www.phusionpassenger.com/library/install/apache/migrating/migrating_from_p4_to_p5.html) guide but there's nothing in there I can see that helps. Is there something else I should be looking at?

**Comment by jamesbebbington** [comment]
Possibly also relevant is that I did initially install the latest version of passenger via rubygems, before remembering that I had transitioned to homebrew for passenger 4.x. I then uninstalled the gem and updated passenger via homebrew.

**Comment by OnixGH** [comment]
DId you follow what I linked?

**Comment by jamesbebbington** [comment]
Yup. I also checked out [Upgrading Passenger + Apache](https://www.phusionpassenger.com/library/install/apache/upgrade/oss/).

Actually, should I not need to compile the apache 2 module if I'm installing via homebrew?

I got to this point as having updated passenger I was still suffering from the [fork crash](https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/) so figured that perhaps the old module was still being used. I've since tried a full apache `start` / `stop` instead of a `restart` but that hasn't helped.

**Comment by jamesbebbington** [comment]
Actually, looking properly at my apache error log, it does appear that I'm using the passenger 5.1.12 module:

```
[Mon Jan 08 12:49:11.472315 2018] [mpm_prefork:notice] [pid 103] AH00163: Apache/2.4.28 (Unix) PHP/7.1.7 Phusion_Passenger/5.1.12 configured -- resuming normal operations
[Mon Jan 08 12:49:11.472794 2018] [core:notice] [pid 103] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[ N 2018-01-08 12:49:15.7390 692/T5 age/Cor/SecurityUpdateChecker.h:374 ]: Security update check: no update found (next check in 24 hours)
objc[696]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[696]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

So is it perhaps more likely the case that it's just the `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` workaround isn't working as expected?

**Comment by CamJN** [comment]
You need to add the env var to launchd if you want to use that workaround, as apachectl uses launchd to start httpd behind the scenes. This involves disabling SIP or booting from another drive.

And since the crash is in apache code: https://github.com/phusion/passenger/issues/1986 it would be very helpful to file a bug report with apple. They prioritize duplicated bugs.

**Comment by jamesbebbington** [comment]
> …since the crash is in apache code: #1986 it would be very helpful to file a bug report with apple. They prioritize duplicated bugs.

Will do!

> You need to add the env var to launchd if you want to use that workaround, as apachectl uses launchd to start httpd behind the scenes. This involves disabling SIP or booting from another drive.

Neither booting from another drive or disabling SIP sound like a particularly appealing option. Should I open another issue to address the fact that the workaround that passenger 5.1.11 added isn't working for me?

**Comment by jamesbebbington** [comment]
> …since the crash is in apache code: #1986 it would be very helpful to file a bug report with apple. They prioritize duplicated bugs.

Bug reports submitted to Apple,

**Comment by jamesbebbington** [comment]
Closing issue, thanks all. The `fork()`-related crash I'm seeing looks to be a dupe of #1986.
