### ISSUE TITLE
nginx_module compile fails with: 'SecTransformRef not declared' on OSX 10.12.6

### ISSUE THREAD

**Issue by eiked** [phusion/passenger#2017]
The nginx module failed to compile on OSX for me
but it did compile successfully on Linux.

Problem is:
```
src/cxx_supportlib/Crypto.cpp: In member function 'OSStatus Passenger::Crypto::copyIdentityFromPKCS12File(const char*, const char*, const char*)':
src/cxx_supportlib/Crypto.cpp:113:2: error: 'SecTransformRef' was not declared in this scope
```

Versions:
- Phusion Passenger 5.1.12
- OSX 10.12.6, Xcode 9.2
- nginx-1.13.8
- current macports in my path

I compile from within the nginx configure:
`./configure --prefix=/usr/local/nginx --conf-path=/srv/nginx/conf/nginx.conf --with-openssl=/usr/local/src/openssl-1.1.0f --with-http_ssl_module --with-http_gzip_static_module --with-cc-opt=-Wno-error --with-http_ssl_module --with-http_v2_module --add-module=../headers-more-nginx-module --add-module=../ngx_brotli --add-module=/opt/local/lib/ruby2.5/gems/2.5.0/gems/passenger-5.1.12/src/nginx_module
`

It fails at:
```
c++ -o buildout/common/libpassenger_common/Crypto.o  -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Isrc/cxx_supportlib/vendor-copy/libuv/include -Wno-deprecated-declarations -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -feliminate-unused-debug-symbols -feliminate-unused-debug-types -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -std=gnu++11 -Wno-unused-local-typedefs -DHAS_UNORDERED_MAP -c src/cxx_supportlib/Crypto.cpp
src/cxx_supportlib/Crypto.cpp: In member function 'OSStatus Passenger::Crypto::copyIdentityFromPKCS12File(const char*, const char*, const char*)':
src/cxx_supportlib/Crypto.cpp:113:2: error: 'SecTransformRef' was not declared in this scope
```

This did compile within my Linux setup but fails on my OSX setup.

My first guess would be, that the declaration of 'SecTransformRef'
is not included in the sources of the passenger nginx_module,
but depends on some external requirement.

**Comment by CamJN** [comment]
Indeed it does, this is a type defined in the Security Framework. We include the Security framework when building on macOS via `src/ruby_supportlib/phusion_passenger/platform_info/crypto.rb` so I'm not sure why it's being left out when you build Passenger. You can see how we determine what os we are building on in `src/ruby_supportlib/phusion_passenger/platform_info/operating_system.rb`, perhaps there's something about your system that doesn't match our expectations?

**Comment by eiked** [comment]
Solved

The passenger_nginx_module needs to be compiled with the apple system cc/c++
(not with a gcc from macports which was is in my path at /opt/local/bin/c++)

`env CC=/usr/bin/CC CXX=/usr/bin/c++ ...
`

The macOS Security Framework needs __BLOCKS__ support for SecTransform,
which is not available in stock gcc

```
/System/Library/Frameworks/Security.framework/Versions/A/Headers/Security.h
#ifdef __BLOCKS__
#include <Security/SecTransform.h>
```
AFAIK support of blocks needs some runtime support,
so linking a passenger_nginx_module taht was compiled with apple cc
into an nginx that was compiled with a stock gcc might be problematic.

You might want to check for
`${CXX} -E -dM - </dev/null|grep __BLOCKS__
`
or more easily in src/cxx_supportlib/Crypto.h:

```
#if BOOST_OS_MACOS
# if ! __BLOCKS__
#  error compiling on macOS needs blocks support, recompile with apple cc/c++
# endif
```

Alt 1:
pulling in <Security/SecTransform.h> manually might help,
but could fail misserably if it really needs blocks support.

Alt 2:
use a custom boost (but compiling that is a drag)

**Comment by eiked** [comment]
A new issue:

When compiling from within nginx/configure,
the CC/CXX env does not make it to the passenger module compile

from within nginx src:
`env CC=/usr/bin/cc CXX=/usr/bin/c++ ./configure ...
`
still uses c++ from path instead of using ${CXX} for the nginx module

while from within passenger/build:
`env CC=/usr/bin/cc CXX=/usr/bin/c++ rake nginx
`
worked as expected

**Comment by CamJN** [comment]
Yes, we only support the apple provided compilation tools on macOS.

**Comment by eiked** [comment]
Hi CamJN,

I fully agree with you about the tools

- I suggest to test this explicitely in ./configure

BTW: We need to get rid of this macos special

**Comment by CamJN** [comment]
Compiler check added in https://github.com/phusion/passenger/tree/macOS_QOL_improvements
