### ISSUE TITLE
jessie+apache: upgrade to libapache2-mod-passenger#1:5.2.0-1~jessie1 breaks installation

### ISSUE THREAD

**Issue by mameier** [phusion/passenger#2019]
## Issue report

I'm using passenger on debian jessie with apache.
After Upgrading from 
libapache2-mod-passenger#1:5.1.12-1~jessie1 to libapache2-mod-passenger#1:5.2.0-1~jessie1
my applications didn't start any longer.

**Are you sure this is a bug in Passenger?**
Pretty shure.
Nothing else was updated.
Reverting passenger back to 1:5.1.12-1~jessie1 made everything work again.

**Question 1: What is the problem?**

The error log shows:
...public/.htaccess: RailsEnv not allowed here

apache reports a 500 server error.

**Question 2: Passenger version and integration mode**:
open source 5.1.2 apache

**Question 3: OS or Linux distro, platform (including version)**:
Debian 8, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.1.5, RVM, Rails 4.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
no

**Question 7: Anything else about your setup that we should know?**

content of .htaccess (path shortend):

RailsEnv production
PassengerRuby /..user_home.../.rvm/wrappers/ruby-2.1.5/ruby

**Comment by CamJN** [comment]
This is expected behaviour in Passenger 5.2.0, you can read about the change here: https://blog.phusion.nl/2018/01/29/passenger-5-2-0/#breakingchangeoverview
