### ISSUE TITLE
Passenger 5.2: Start Apache: WARNING: PassengerPreStart cannot occur within <VirtualHost> section

### ISSUE THREAD

**Issue by Sega100500** [phusion/passenger#2021]
Passenger 5.2: Start Apache: **WARNING: PassengerPreStart cannot occur within VirtualHost section**

Linux Debian 8 Jessise
Apache 2.4.10
Ruby 2.5.0 and Ruby 2.3.6 - different sites on different Ruby versions
different versions of Ruby on Rails

**Comment by CamJN** [comment]
Thanks for pointing out that the docs needed to be updated, this is expected behaviour in 5.2.0.

**Comment by acosonic** [comment]
What about this? Where should I put those directives instead? I am having multi-user hosting...

**Comment by CamJN** [comment]
Unfortunately we don't currently have a replacement for shared hosting setup.

**Comment by acosonic** [comment]
But you moved those features to Enterprize?

**Comment by n3rve** [comment]
I got a slightly different warning after upgrading Passenger:

> WARNING: PassengerDefaultUser cannot occur within <VirtualHost> section

Moving this outside the virtual host stops the warning from showing. How do I get those directives to take effect for a specific virtual host?

**Comment by FooBarWidget** [comment]
> Moving this outside the virtual host stops the warning from showing. How do I get those directives to take effect for a specific virtual host?

You don't. PassengerDefaultUser has always been a global option that cannot be customized on a per-entity basis. It's just that we didn't used to warn you when your config was wrong.

Try PassengerUser instead, *that* one can be customized per vhost/location.

**Comment by arianf** [comment]
@CamJN Has this feature been added anywhere (enterprise or free) versions of passenger?

**Comment by CamJN** [comment]
Unfortunately not.
