### ISSUE TITLE
Changelog in master is out of sync with changelog on 5.x branches

### ISSUE THREAD

**Issue by deoren** [phusion/passenger#2025]
Is the intention to merge the changelog entries back into the master branch once a stable branch is retired, or was this just missed? I'll be happy to submit a PR for this if you like.

I see that PRs should be submitted against the latest stable branch, but wasn't sure what the intent was regarding the changelog.

Thanks.

**Comment by CamJN** [comment]
The master branch will get synced eventually, I've just been busy. :)

**Comment by deoren** [comment]
> @CamJN: The master branch will get synced eventually, I've just been busy. :)

Alright. If you'd like a PR with the changes from the other branches just let me know.

**Comment by FooBarWidget** [comment]
Thanks for reporting this issue. I've fixed it by fast-forwarding the master branch to the latest release.
