### ISSUE TITLE
Passenger 5.2 won't boot "unknown response type"

### ISSUE THREAD

**Issue by excid3** [phusion/passenger#2026]
**Question 1: What is the problem?**

When this application launches, we see it print out a message from a gem, but then Passenger seems to claim it's ready and then crashes.

```
App 6416 stdout:
App 6416 stdout: [2018-01-30 22:04:13] Forest 🌳🌳🌳  A newer version of Forest liana exists, you should upgrade for a better experience. Run the following command to upgrade: bundle update --source forest_liana
App 6416 stdout: !> Ready
[ E 2018-01-30 22:04:14.4454 6168/Th age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/deploy/redwood/current: An error occurred while starting up the preloader. It sent an unknown response type "socket: unix:/tmp/passenger.llywlW1/apps.s/preloader.b1b85s\n".
  Error ID: dea17e3a
  Error details saved to: /tmp/passenger-error-A36Xy7.html
  Message from application: An error occurred while starting up the preloader. It sent an unknown response type &quot;socket: unix:/tmp/passenger.llywlW1/apps.s/preloader.b1b85s\n&quot;.<br>
<h2>Raw process output:</h2>
<pre>
&#27;[33m[2018-01-30 22:04:13] Forest 🌳🌳🌳  A newer version of Forest liana exists, you should upgrade for a better experience. Run the following command to upgrade: bundle update --source forest_liana
&#27;[0m!&gt; Ready
</pre>

[ E 2018-01-30 22:04:14.4623 6168/Ta age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is dea17e3a. Please see earlier logs for details about the error.
```

**Question 2: Passenger version and integration mode**:

I've tried both 5.2.0/nginx and 5.1.12/nginx

**Question 3: OS or Linux distro, platform (including version)**:

Ubuntu 16.04 x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework 

Rails 5.1.0 and Ruby 2.3.5 (rbenv)

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Hosted on DigitalOcean

**Question 7: Anything else about your setup that we should know?**

I've manually started the app and the Rails console and both work and are able to server requests and connect to the database. We can also see that Passenger ran some Ruby code because of the upgrade warning from Forest admin.

**Comment by excid3** [comment]
I forgot to mention, `/tmp/passenger.llywlW1/apps.s/preloader.b1b85s` does exist on the filesystem.

**Comment by CamJN** [comment]
this output looks suspicious:
```
App 6416 stdout:
App 6416 stdout: [2018-01-30 22:04:13] Forest 🌳🌳🌳  A newer version of Forest liana exists, you should upgrade for a better experience. Run the following command to upgrade: bundle update --source forest_liana
App 6416 stdout: !> Ready
```

`!> Ready ` should be the first output from the app, is there a way to suppress that upgrade notice?

**Comment by excid3** [comment]
I was wondering if maybe that was interfering with things. It's a client app so I'll see if I can surpress that or update the version and see if that works.

**Comment by excid3** [comment]
Sure enough, upgraded to the latest version of the gem and that let Passenger boot immediately. I'll file a bug with them to get that improved. I'm not sure Passenger needs to handle this situation, but it was pretty weird to track down.

**Comment by CamJN** [comment]
Well, this is expected behaviour so I'm going to close the bug.

**Comment by Lukasz-Ziemnicki** [comment]
Hi, I'm having the same problem but upgrading Forest Liana did not solve the problem. Do you have any ideas where to look for?
