### ISSUE TITLE
Double encoding problem in Persian URIs

### ISSUE THREAD

**Issue by mghadam** [phusion/passenger#2033]
I found that passenger does a 'double encoding' in persian URIs which cause such URLs to break. For example when the URL is requested : 

`http://mydomain/تیتر/`
the web browser encodes this URL and sends it to the web server so the web server would get :

`http://mydomain/%d8%aa%db%8c%d8%aa%d8%b1/`

and sends it to the script. phusion does a second encoding on "%" chars in the above URL `% -> %25` and converts it to : 

`http://mydomain/%25d8%25aa%25db%258c%25d8%25aa%25d8%25b1/`

which would not work in the script . 

Tested with the last version of passenger from git repo.

**Comment by CamJN** [comment]
Is your app python, js, or ruby?

**Comment by mghadam** [comment]
It's python, we tested with django, to reproduce the problem install the latest version of django and use the following URL pattern : 

```
urlpatterns = [
#       path('admin/',admin.site.urls),
    path(r'تیتر/', admin.site.urls),
]
```

`http://mydomain/تیتر/` should show the admin panel, which worked fine when I tested on gunicorn and it returned a 404 error on mod_passenger with the double encoded URL in the debug page `http://mydomain/%25d8%25aa%25db%258c%25d8%25aa%25d8%25b1/` .

**Comment by CamJN** [comment]
Sounds like a dup of https://github.com/phusion/passenger/issues/1828, would you agree?

**Comment by mghadam** [comment]
indeed, thanks
