### ISSUE TITLE
Support for Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by kule** [phusion/passenger#2036]
## Issue report

I came across this issue trying to get our Rails app running on a colleagues Windows machine.  I know it's probably low priority (can't imagine there's a huge amount of users with this setup) but thought I'd post it incase it's something that's worth fixing (or at least be of use for the next person trying to find a fix).

I worked around this by forcing Passenger to use tcp sockets instead of unix sockets by setting _PASSENGER_FORCE_HTTP_SESSION to true.

( fyi https://stackoverflow.com/questions/48160275/cannot-start-rails-app-on-nginx-with-passenger-and-https-under-wsl-port-in-use/49009318#49009318 )

**Question 1: What is the problem?**
Passenger fails with Address already in use when running under Ubuntu WSL

```
Address already in use - listen(2) (Errno::EADDRINUSE)
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:303:in `listen'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:303:in `block in create_unix_socket_on_filesystem'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:65:in `block in retry_at_most'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:63:in `times'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:63:in `retry_at_most'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:299:in `create_unix_socket_on_filesystem'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:101:in `initialize'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:135:in `new'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:135:in `negotiate_spawn_command'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```
**Question 2: Passenger version and integration mode**:
We tried with open source 5.1.11 standalone and via Apache 2.4.18
(also tried with the latest 5.2.0 standalone and had the same issue)

**Question 3: OS or Linux distro, platform (including version)**:
Windows 10 Pro. v 1709. build 16299.192
Windows Subsystem for Linux (using Ubuntu)

**Question 4: Passenger installation method**:

Your answer:
[X] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.4.2
Rails 4.2.10
Node.js 8.9.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Windows Subsystem for Linux (using Ubuntu)

**Comment by OnixGH** [comment]
Thanks for sharing! I renamed it as a feature request since it's not an officially supported setup, but it's very useful to see your experiences.

**Comment by kule** [comment]
@OnixGH thanks, yeah not expected much on this one.

Just to add it looks like I was a bit too quick on the workaround above - it seems to stall on ajax post requests.

**Comment by meixiaofei** [comment]
@kule yes, sure it is, it's still not work with the request method post...
and you have any solution? thanks a lot for your share, QaQ

**Comment by kule** [comment]
@meixiaofei I've updated my pull request - if you manually make the changes I did there it'll work in WSL.

**Comment by CamJN** [comment]
We've tinkered around with this a bit, and haven't found Passenger on WSL to be stable enough yet to merge at this time. @FooBarWidget might be able to elaborate if he has a second.

**Comment by kule** [comment]
@CamJN thanks for the update.  The pull request works for us, but it's only for limited development purposes.

It'd save some hassle if it could work out of the box, however, I can imagine it's a whole other issue to pull it in and having users expect it to be production-worthy and have to support something that doesn't work in all cases.

I don't work on Windows usually but if there's something you need me to change let me know I'll have a look at the Pull Request again.

**Comment by CamJN** [comment]
in WSL2 passenger should "just work", can someone verify this?

**Comment by somesayinice** [comment]
> in WSL2 passenger should "just work", can someone verify this?

Appears to be working. Thanks for this reply. Was about to give up on passenger for wsl.

**Comment by CamJN** [comment]
PR is merged
