### ISSUE TITLE
Ruby 2.5.0 crash with Passenger 5.1 / 5.2 gem + Apache

### ISSUE THREAD

**Issue by Sega100500** [phusion/passenger#2040]
Linux Debian 8.10 Jessie
Apache/2.4.10 (Debian)
Ruby 2.5.0 and Ruby 2.3.6

passenger.log
```
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:79: [BUG] Segmentation fault at 0x0000000000001246
App 23373 stderr: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
App 23373 stderr:
App 23373 stderr: -- Control frame information -----------------------------------------------
App 23373 stderr: c:0007 p:----
App 23373 stderr: s:0034 e:000033 CFUNC  :detach_process
App 23373 stderr: c:0006 p:0270 s:0030 e:000029 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_su
pportlib/phusion_passenger/preloader_share
App 23373 stderr: c:0005 p:0288 s:0022 e:000021 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_su
pportlib/phusion_passenger/preloader_share
App 23373 stderr: c:0004 p:0143 s:0009 e:000008 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/helper-
scripts/rack-preloader.rb:157
App 23373 stderr: c:0003 p:0011 s:0006 e:000005 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/helper-
scripts/rack-preloader.rb:30
App 23373 stderr: c:0002 p:0038 s:0004 E:001b60 EVAL   /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/helper-
scripts/rack-preloader.rb:29 [FINISH]
App 23373 stderr: c:0001 p:0000 s:0002 E:002430 (none) [FINISH]
App 23373 stderr:
App 23373 stderr: -- Ruby level backtrace information ----------------------------------------
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:29:in `<mai
n>'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:30:in `<mod
ule:PhusionPassenger>'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/helper-scripts/rack-preloader.rb:157:in `<mo
dule:App>'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:140:in `run_main_loop'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:79:in `accept_and_process_next_client'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:79:in `detach_process'
App 23373 stderr:
App 23373 stderr: -- Machine register context ------------------------------------------------
App 23373 stderr:  RIP: 0x0000000000001246 RBP: 0x000000000000b7ef RSP: 0x00007ffe5e5948a8
App 23373 stderr:  RAX: 0x0000000000000000 RBX: 0x0000563b56fd56d0 RCX: 0x00007fe847770108
App 23373 stderr:  RDX: 0x00007fe84548f460 RDI: 0x000000000000001e RSI: 0x000000000000b7ef
App 23373 stderr:   R8: 0x0000000000000003  R9: 0x0000563b574e82c8 R10: 0x0000563b577e4f20
App 23373 stderr:  R11: 0x0000000000000206 R12: 0x0000000000018000 R13: 0x0000563b574e82c8
App 23373 stderr:  R14: 0x0000563b574e8c28 R15: 0x0000000000000001 EFL: 0x0000000000010202
App 23373 stderr:
App 23373 stderr: -- C level backtrace information -------------------------------------------
App 23543 stdout:
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38: [BUG] Segmentation fault at 0x0000000000001306
App 23373 stderr: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
App 23373 stderr:
App 23373 stderr: -- Control frame information -----------------------------------------------
App 23373 stderr: c:0008 p:---- s:0044 e:000043 CFUNC  :split_by_null_into_hash
App 23373 stderr: c:0007 p:0018 s:0040
App 23373 stderr: e:000039 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_pass
enger/utils/native_su
App 23373 stderr: c:0006 p:0053 s:0036 e:000035 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_su
pportlib/phusion_passenger/request_handler
App 23373 stderr: c:0005 p:0131 s:0027 e:000026 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_su
pportlib/phusion_passenger/request_handler
App 23373 stderr: c:0004 p:0098 s:0017 e:000016 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_su
pportlib/phusion_passenger/request_handler
App 23373 stderr: c:0003 p:0065 s:0009 e:000008 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_su
pportlib/phusion_passenger/request_handler
App 23373 stderr: c:0002 p:0030
App 23373 stderr: s:0005 e:000004 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusi
on_passenger/utils.rb:113 [FINISH]
App 23373 stderr: c:0001 p:---- s:0002 e:000001 (none) [FINISH]
App 23373 stderr:
App 23373 stderr: -- Ruby level backtrace information ----------------------------------------
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/utils.rb:1
13:in `block in create_thread_and_abort_on_exception'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/request_ha
ndler.rb:416:in `block (3 levels) in start_threads'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/request_ha
ndler/thread_handler.rb:113:in `main_loop'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/request_ha
ndler/thread_handler.rb:146:in `accept_and_process_next_request'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/request_ha
ndler/thread_handler.rb:224:in `parse_session_request'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38:in `split_by_null_into_hash'
App 23373 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.1/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38:in `split_by_null_into_hash'
App 23373 stderr:
App 23373 stderr: -- Machine register context ------------------------------------------------
App 23373 stderr:  RIP: 0x0000000000001306
App 23373 stderr:  RBP: 0x00007fe83c001a84 RSP: 0x00007fe83bcf63c8
App 23373 stderr:  RAX: 0x0000000000000000 RBX: 0x00007fe83c001880 RCX: 0x00007fe83bcf8158
App 23373 stderr:  RDX: 0x00007fe84548f590 RDI: 0x0000563b574e8c28 RSI: 0x0000563b57208918
App 23373 stderr:   R8: 0x0000000000000003  R9: 0x0000563b574e8638 R10: 0x0000563b577e4f20
App 23373 stderr:  R11: 0x00007fe83bcf8198 R12: 0x00007fe83c001880 R13: 0x0000563b57208918
App 23373 stderr:  R14: 0x0000563b574e8c28 R15: 0x0000000000000001 EFL: 0x0000000000010206
App 23373 stderr:
App 23373 stderr: -- C level backtrace information -------------------------------------------
[ W 2018-02-28 16:56:19.6157 23344/T7 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 1-1] Sending 502 response: application did not send a comp
lete response
```

**Comment by OnixGH** [comment]
Hi, thanks for the report. This looks like a Ruby issue. How exactly did you install Passenger?

I tried with Debian 8.10 + passenger 5.2.1 installed as gem in Ruby 2.5.0 (rvm), and then passenger-install-apache2-module --auto to my Apache/2.4.10, but I don't get any crash.

You mentioned Ruby 2.3.6 but the traces only show a test with Passenger installed in 2.5.0. Can you try to install Passenger in 2.3.6 (also update `PassengerRoot`, `PassengerDefaultRuby`) and use it from there?

**Comment by Sega100500** [comment]
I use ```rbenv```. I use gem passenger and install with ```passenger-install-apache2-module```
Sites don't crash, but in log these error report.
On server many sites: some use Ruby 2.5.0, some - 2.3.6. Use ```PassengerRuby``` in config of sites to specify which ruby is used.
Main used gem passanger with Ruby 2.5.0

**Comment by OnixGH** [comment]
A `Segmentation fault` (in your log) indicates a crash.

Can you confirm the issue is solved if you install Passenger in 2.3.6 instead of 2.5.0?

**Comment by Sega100500** [comment]
No. I install on Ruby 2.5.0. All work.
But! In log these messages is present. **Problem is exists**. 
And, by the way, already in several versions of passenger there is this error.

**Comment by CamJN** [comment]
Have you tried rebuilding ruby 2.5 via rbenv or disabling the passenger native extensions? If not please do so and let us know whether either thing has any effect on whether this continues to happen.

**Comment by Sega100500** [comment]
No, I can not conduct experiments on my server. Commercial sites.
Try to simulate the situation yourself.

**Comment by CamJN** [comment]
We have, and cannot reproduce it. That's why we are asking for more information.

**Comment by Sega100500** [comment]
More information? Only this log.
You write the system ```passenger```. The system reports errors in the log file. You should know better what can work wrong.

**Comment by CamJN** [comment]
While it is true that we know more about how Passenger works than your average person, that doesn't help as much as you'd think. There are a lot of relevant details that are unique to each installation and you know your server better than anyone. And since this issue is only happening on your server, and we cannot reproduce it locally, the only way for us to learn about the issue is to ask you. If you aren't interested in working on this issue that's fine, but we will not be able to move forward.

**Comment by Sega100500** [comment]
A typical web server. Without any tricks. Only simultaneously work sites on different versions of Ruby.

Linux Debian 8.10 Jessie
Apache/2.4.10 (Debian)
Ruby 2.5.0 and Ruby 2.3.6

Ruby on Rails 3.2.x, 4.0.x, 4.1.x, 5.1.x

**Comment by Sega100500** [comment]
Why should I make my server where commercial sites work, a test server for you? Just because you yourself are not able to simulate a similar configuration.

**Comment by CamJN** [comment]
Because you'd like this issue fixed. It is generally a good idea to use a staging server, which is identical to a production server except it does not receive outside traffic and which you use to test out changes on before pushing them to production, does the issue occur in such a scenario? Or is it only on the one server?

**Comment by OnixGH** [comment]
@Sega100500 I'm afraid I can't reproduce your issue, I've tried with several Ruby versions and I don't get this error.

>No. I install on Ruby 2.5.0. All work.
>But! In log these messages is present.

I don't understand what you are saying here. What I asked is to `gem uninstall passenger` in your Ruby 2.5.0 and to `gem install passenger` on Ruby 2.3.6, and then `passenger-install-apache2-module`.

We're not asking you to experiment on a live server, just to reinstall Passenger in a different Ruby to see if that solves the crashes. So far all we know is that it looks like a crash in your *Ruby* installation, which is code we do not control.

**Comment by Sega100500** [comment]
It is only ONE server. This is LIVE server, for COMMERCIAL use!
I can't experiment on it.

If you are the developers of the ```passenger``, you should have test servers.

**Comment by OnixGH** [comment]
@Sega100500 We have test servers, and we are also running Passenger in production.

**Comment by Sega100500** [comment]
@OnixGH 
You must have servers for testing, if you are developing.

**Comment by OnixGH** [comment]
@Sega100500 I think you didn't read my message? We have test servers, and we are also running Passenger in production.

But the issue doesn't happen there, and no other user has reported this issue to us, so unfortunately at the moment it seems we can't help you further :(

**Comment by Sega100500** [comment]
I would be happy to help! But I have already described the situation. I can not conduct experiments on the my production server.

**Comment by CamJN** [comment]
And we've said it's fine to spin up a testing server to do experiments on. But when we setup a testing server ourselves, with the information you've provided: such as that it's a debian jessie server running apache 2.4.10 and Ruby 2.5.0 and 2.3.6 from rbenv we do not see the issue. We believe that you'd be able to setup a server which is closer to your production server and get the issue to reproduce on that testing server which would then make the experiments useful.

**Comment by Sega100500** [comment]
I upgrade gems on sites which works with Ruby 2.3.6.
In ```Gemfile.lock``` now used ```passenger (5.2.1)``` and NO ERROR MESSAGES in log-file.
I apologize for my inattention.

**Comment by ms-ati** [comment]
@CamJN As a drive-by observer in public, I commend you on many aspects of your responses here. If you will grant me your permission, I'd love to link to this issue in slides and other media when discussing support of open source and commercial software?
