### ISSUE TITLE
[alert]: Unable to start the Phusion Passenger watchdog: it seems to have crashed during startup for an unknown reason, with exit code 1 (-1: Unknown error)

### ISSUE THREAD

**Issue by alexxis** [phusion/passenger#2042]
I have the FreeBSD 11.1-STABLE with nginx, ruby and passenger. Until last update all works properly. But I receive an error after today update nginx.

Passenger version and integration mode:
- 5.1.12_2/nginx

OS or Linux distro, platform (including version):
- FreeBSD 11.1-STABLE, amd64

Passenger installation method:

[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[X] Other, please specify:

- from ports

Your app's programming language (including any version managers) and framework (including versions):
- Ruby 2.4.3,1

Are you using a PaaS and/or containerization? If so which one?
- no, just VPS

Anything else about your setup that we should know?
- no

**Comment by CamJN** [comment]
Please set log level to 7 (https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_log_level) and provide a full log of the problem occurring.

**Comment by alexxis** [comment]
Done.
And after restart nginx we see in /var/log/passenger.log:
``[ E 2018-03-12 17:10:59.5706 87657/T1 age/Sha/Fun/Initialization.cpp:572 ]: *** ERROR: Unexpected empty message received from channel
     in 'void Passenger::VariantMap::readFrom(int, const Passenger::StaticString &)' (VariantMap.h:153)
     in 'Passenger::VariantMap Passenger::Agent::Fundamentals::initializeAgent(int, char ***, const char *, Passenger::Agent::Fundamentals::OptionParserFunc, Passenger::Agent::Fundamentals::PreinitializationFunc, int)' (Initialization.cpp:541)
``

**Comment by CamJN** [comment]
It looks like the nginx module doesn't match the Passenger version. We don't maintain the ports-provided Passenger, so I'm not sure if it is providing a dynamic nginx module or statically compiling the module into nginx. If it's a dynamic module there will be a line in the nginx config that includes `load_module` and a path that mentions Passenger. Please let us know, and we'll provide more instructions on checking that the versions match.

**Comment by alexxis** [comment]
Nginx has the dynamic module. And I have the string in the nginx config: 
``load_module /usr/local/libexec/nginx/ngx_http_passenger_module.so;``

**Comment by CamJN** [comment]
Ok in that case you can check if the following commands output versions that match:
`strings /usr/local/libexec/nginx/ngx_http_passenger_module.so | fgrep '+ Phusion Passenger'`
and
`passenger --version`

**Comment by alexxis** [comment]
1. ``nginx/1.12.2 + Phusion Passenger``
``nginx + Phusion Passenger``
``nginx/1.12.2 + Phusion Passenger 5.2.1``
``nginx + Phusion Passenger 5.2.1``

and

2. ``Phusion Passenger 5.1.12``

**Comment by FooBarWidget** [comment]
@alexxis It is as we expected. The Passenger dynamic module that you load into Nginx is not of the same version as the Passenger instance that you've installed. You should update your Passenger Nginx dynamic module to the exact same version.

**Comment by renchap** [comment]
If some other people are having the same problem: the `www/rubygem-passenger` port has been updated to use the new flavors system: https://svnweb.freebsd.org/ports/head/www/rubygem-passenger/Makefile?revision=459684&view=markup&pathrev=459684
If you want to build the `nginx` flavor with poudriere, you need to build `www/rubygem-passenger@nginx`, which will create the `rubygem-passenger-nginx` package.

**Comment by jaswinder97** [comment]
This works for me-
> mkdir /tmp
> mkdir /tmp/passenger.crhjf4
> passenger-config compile-agent --force
