### ISSUE TITLE
Multiple passenger_base_uri no longer works in passenger 5.2.0 and 5.2.1

### ISSUE THREAD

**Issue by remomueller** [phusion/passenger#2043]
**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

In 5.1.12, I used to be able to load multiple `passenger_base_uri`s, but as of passenger 5.2.0 and 5.2.1, I am no longer able to run two or more web applications on the same server at once. (This may simply be a change in the configuration of this setup, but I haven't found how to do this in 5.2.0).

In my configuration (and working as of 5.1.12), I include two or more Rails apps mounted in different locations:

```
  server {
    listen       80;
    server_name  localhost;

    root /path/to/webserver;

    passenger_base_uri /dev/rails-app-1;
    passenger_base_uri /dev/rails-app-2;

    location /dev {
      passenger_enabled on;
      passenger_app_env development;
    }
    # ...
  }
```

I expect to be able to be able to load both http://localhost/dev/rails-app-1 and http://localhost/dev/rails-app-2 in my browser, but only the second (last) configuration seems to load (even if typing in the first URL).

In 5.1.12, this worked with multiple Rails apps, in 5.2.0 and 5.2.1, this no longer works. (Has the configuration changed for multiple Rails apps running on one server?

Edit: Also looking at the documentation, this [should still be possible](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_base_uri).

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer: open source, 5.2.1/nginx using [setup](https://github.com/remomueller/documentation/blob/master/macos/171-install-nginx-with-extra-modules.md) and [configuration](https://github.com/remomueller/documentation/blob/master/macos/173-nginx-configuration.md)

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer: I've tried the configuration on CentOS 6 and Mac OS 10.13.3, and neither work. I don't think it's platform specific.

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[X] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

Passenger installed with RubyGems, no Gemfile: installation
 [step 1](https://github.com/remomueller/documentation/blob/master/macos/160-passenger.md)
 [step 2](https://github.com/remomueller/documentation/blob/master/macos/171-install-nginx-with-extra-modules.md#start-the-passenger-installer)

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer: This is using Ruby 2.5.0 (RVM), Rails 5.2.0.rc1, Node.js 6.12.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer: No, this is built on Mac OS (in development) and CentOS 6 (staging/production).

**Question 7: Anything else about your setup that we should know?**

Your answer: Let me know if you require additional information!

**Comment by OnixGH** [comment]
Expected behavior is that it should still work. Thanks for reporting!

**Comment by FooBarWidget** [comment]
Problem confirmed and analyzes. A fix is available in the branch GH-2043-fix. Analysis of the cause of the problem can be found in the commit message. @CamJN could you review this?

**Comment by CamJN** [comment]
sure thing

**Comment by remomueller** [comment]
Just tried out passenger 5.2.2 on CentOS, and the fix works as expected, thanks!
