### ISSUE TITLE
Unable to set file descriptor ulimit:  Operation not permitted (errno=1)

### ISSUE THREAD

**Issue by jackbit** [phusion/passenger#2045]
I use monit to run passenger standalone from a bash file which contains this command:

```
/home/deploy/.rvm/gems/ruby-2.3.1/bin/passenger start --instance-registry-dir $APP --log-file $LOG_FILE --socket $SOCKET_FILE --pid-file $PID_FILE --core-file-descriptor-ulimit 100000 --app-file-descriptor-ulimit 100000 --max-request-queue-size 100000
```

Then it is failed to set file descriptor (but work if run out of monit / directly command line)

```
[ 2018-03-10 22:45:42.6455 31963/7efeff91d740 age/Cor/CoreMain.cpp:282 ]: Unable to set file descriptor ulimit to 100000: Operation not permitted (errno=1)
[ 2018-03-10 22:45:42.6515 31970/7f5ce7b28740 age/Ust/UstRouterMain.cpp:211 ]: Unable to set file descriptor ulimit to 100000: Operation not permitted (errno=1)
App 32007 stderr: Unable to set file descriptor ulimit to 100000: Operation not permitted (errno=1)
```

any idea? thank you.

**Comment by jackbit** [comment]
problem is solved by upgrading monit to 5.25.1 
https://mmonit.com/monit/changes/

**Comment by jackbit** [comment]
sorry i have to open again, the issue is still there through monit.

**Comment by jackbit** [comment]
another error:

```
[ E 2018-03-11 07:51:21.2780 18186/T1 age/Cor/CoreMain.cpp:318 ]: Unable to set file descriptor ulimit to 100000: Operation not permitted (errno=1)
*** TempDirToucher error: cannot set effective user to 1001 for touching files: Operation not permitted (errno 1)
```

why it uses user 1001?

**Comment by jackbit** [comment]
issue is solved. 

Previously my configuration:

```
check process passenger1 with pidfile /home/deploy/www/current/tmp/pids/passenger1.pid
  group dev
  start program = "/home/deploy/config/server/monit/bin/passenger/start 1"
    as uid deploy and gid dev
  stop program = "/home/deploy/config/server/monit/bin/passenger/stop 1"
    as uid deploy and gid dev

  if failed host "127.0.0.1" port 80 with timeout 5 seconds for 3 cycles then restart
  if memory usage > 90% for 3 cycles then restart
  if cpu usage > 85% for 3 cycles then restart
```

the *start* script run the following command:

```
/home/deploy/.rvm/gems/ruby-2.3.1/bin/passenger start --instance-registry-dir $APP --log-file $LOG_FILE --socket $SOCKET_FILE --pid-file $PID_FILE --core-file-descriptor-ulimit 100000 --app-file-descriptor-ulimit 100000 --max-request-queue-size 100000
```

It seems the script was failed to run file descriptor under user *deploy*, so file descriptor ulimit use default 1024. I only can assume that file descriptor is set before the user is set and it doesnt have permission to set file descriptor operation.

After many hours debugging and upgrading version, playing configuration, the solution is sticked to this :

```
check process passenger1 with pidfile /home/deploy/www/current/tmp/pids/passenger1.pid
  start program = "/home/deploy/config/server/monit/bin/passenger/start 1"
  stop program = "/home/deploy/config/server/monit/bin/passenger/stop 1"

  if failed host "127.0.0.1" port 80 with timeout 5 seconds for 3 cycles then restart
  if memory usage > 90% for 3 cycles then restart
  if cpu usage > 85% for 3 cycles then restart
```

and then the *start* script run the following command:

```
USER="deploy"
CMD="cd $APP && /home/deploy/.rvm/gems/ruby-2.3.1/bin/passenger start --instance-registry-dir $APP --log-file $LOG_FILE --socket $SOCKET_FILE --pid-file $PID_FILE --core-file-descriptor-ulimit 100000 --app-file-descriptor-ulimit 100000 --max-request-queue-size 100000"

su - $USER -c "$CMD"
```

The usage of `cd $APP` is required or it will set wrong application directory. Now, I can get the correct  file-descriptor-ulimit from monit execution.

I keep it open, so i think you can remove the code from my error and analisys in `/Cor/CoreMain.cpp:282`

**Comment by FooBarWidget** [comment]
The problem is that you start Passenger without root privileges. Processes without root privileges are not able to increase their ulimit compared to the system default, only decrease it. That's why you get the "operation not permitted" error. Try running `passenger start` itself as root while passing `--user` -- that way Passenger will lower its privileges *after* having changed the ulimit.
