### ISSUE TITLE
Rate limiting subscriptions in Meteor app stops app working

### ISSUE THREAD

**Issue by Shelagh-Lewins** [phusion/passenger#2057]
**Question 1: What is the problem?**
I'm running a Meteor app and the Mongodb database is responding very slowly. No errors are showing in the Passenger log but Mongodb is quitting at times and the Mongodb log is showing a large number of repeated subscriptions from the same connections, up to 20 per second.

So I used https://atmospherejs.com/meteor/ddp-rate-limiter to put a rate limit on my publications by putting the following code at the end of my publications file:

```
const testPublication = {
    type: 'subscription',
    name: 'mycollection',
};

DDPRateLimiter.addRule(testPublication, 1, 100);
```

I tested this locally by running the following code on the client:

```
for (let i = 0; i < 250; i++) {
      console.log(`i ${i}`);
      Meteor.subscribe('mycollection', {'i': i});
    }
  });
```

and this code in the publish function:

`console.log(`i ${params.i}`)`

This worked fine locally; with the rate limit in place, the server log only showed the correct number of subscriptions.

However when I deployed the app to my server, it immediately failed with the following output in the passenger log file:

```
[ N 2018-04-08 15:42:11.2935 6913/Ta age/Cor/SecurityUpdateChecker.h:517 ]: Security update check: no update found (next check in 24 hours)
[ N 2018-04-08 17:25:57.6674 6913/T8 age/Cor/CoreMain.cpp:1075 ]: Checking whether to disconnect long-running connections for process 6929, application /var/www/myapp/bundle (production)
App 9962 stdout:
App 9962 stdout: Exception from sub recent_mycollection id redacted Error: write EPIPE
App 9962 stdout:     at _errnoException (util.js:1022:11)
App 9962 stdout:     at WriteWrap.afterWrite (net.js:880:14)
App 9962 stdout: Exception while polling query {"collectionName":"mycollection","selector":{"$or":[{"private":{"$ne":true}},{"created_by":"redacted"}]},"options":{"transform":null}}: MongoError: connection 3 to localhost:27017 closed
App 9962 stdout:     at Function.MongoError.create (/var/www/myapp/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:29:11)
App 9962 stdout:     at Socket.<anonymous> (/var/www/myapp/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:212:22)
App 9962 stdout:     at Object.onceWrapper (events.js:315:30)
App 9962 stdout:     at emitOne (events.js:116:13)
App 9962 stdout:     at Socket.emit (events.js:211:7)
App 9962 stdout:     at TCP._handle.close [as _onclose] (net.js:567:12)
App 9962 stdout: Exception while polling query {"collectionName":"users","selector":{"_id":"redacted"},"options":{"transform":null,"fields":{"profile":1,"username":1,"emails":1}}}: Error: write EPIPE
App 9962 stdout:     at _errnoException (util.js:1022:11)
App 9962 stdout:     at WriteWrap.afterWrite (net.js:880:14)
[ W 2018-04-08 17:26:57.0531 6913/Tk age/Cor/App/Gro/ProcessListManagement.cpp:342 ]: Detached process (pid=6929, group=/var/www/myapp/bundle (production)) didn't shut down within 1 minute. Forcefully killing it with SIGKILL.
[ W 2018-04-08 17:28:56.9520 6913/T5 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 1-355] Sending 502 response: application did not send a complete response
```

Is this a bug in Passenger, that you can't rate limit subscriptions? Or is there a way I can do this?

Many thanks.

**Question 2: Passenger version and integration mode**:
Phusion Passenger 5.2.3 standalone

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 16.04 on a Digital Ocean droplet

**Question 4: Passenger installation method**:

I followed this tutorial:
https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/
sudo apt-get install -y nginx-extras passenger

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
METEOR@1.6.0.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**

I don't think so

**Comment by Shelagh-Lewins** [comment]
I think the problem is caused by something else, internal to the database.

**Comment by FloorD** [comment]
Thank you for closing the issue @Shelagh-Lewins!
