### ISSUE TITLE
Docker build failing Enterprise

### ISSUE THREAD

**Issue by alexi21** [phusion/passenger#2061]
Docker Build Failing for phusion/passenger-full

This is critical as we cannot deploy our production server until this is fixed.

Ruby on Rails, ruby-2.2.8, rails 4.2.8

Thanks for your help.

### Docker File:

FROM phusion/passenger-full:0.9.26
ENV HOME /root
CMD ["/sbin/my_init"]
ADD passenger-enterprise-license /etc/passenger-enterprise-license
RUN echo deb https://download:<MYKEY>@www.phusionpassenger.com/enterprise_apt xenial main > /etc/apt/sources.list.d/passenger.list
RUN apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" passenger-enterprise nginx-extras

....Fails at this last step so the rest of the file etc. does not seem relevant.

### Error:

Sending build context to Docker daemon  185.4MB
Step 1/38 : FROM phusion/passenger-full:0.9.26
 ---> 447621f4f66a
Step 2/38 : ENV HOME /root
 ---> Using cache
 ---> ccd4ce067a67
Step 3/38 : CMD ["/sbin/my_init"]
 ---> Using cache
 ---> 274aabf6c829
Step 4/38 : ADD passenger-enterprise-license /etc/passenger-enterprise-license
 ---> Using cache
 ---> 32f8c8344cbb
Step 5/38 : RUN echo deb https://download:bf2f7736c8047b62ecfd9d3e0673be914272f6c94ba52d3727849689e525b21a@www.phusionpassenger.com/enterprise_apt xenial main > /etc/apt/sources.list.d/passenger.list
 ---> Using cache
 ---> 9cbfb4830eaf
Step 6/38 : RUN apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" passenger-enterprise nginx-extras
 ---> Running in c3f0f66e3913
Get:1 https://deb.nodesource.com/node_7.x xenial InRelease [4,634 B]
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Ign:3 https://www.phusionpassenger.com/enterprise_apt xenial InRelease
Get:4 https://deb.nodesource.com/node_7.x xenial/main Sources [758 B]
Get:5 https://www.phusionpassenger.com/enterprise_apt xenial Release [23.0 kB]
Get:6 https://deb.nodesource.com/node_7.x xenial/main amd64 Packages [969 B]
Get:7 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Err:8 https://www.phusionpassenger.com/enterprise_apt xenial Release.gpg
  The following signatures were invalid: NODATA 2
Get:9 http://security.ubuntu.com/ubuntu xenial-security/main Sources [147 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/restricted Sources [2,243 B]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [77.7 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [1,493 B]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [602 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial/main Sources [1,103 kB]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:18 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [430 kB]
Get:19 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,492 B]
Get:20 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [5,179 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9,802 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial/multiverse Sources [215 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,558 kB]
Get:24 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:25 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9,827 kB]
Get:26 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:27 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [383 kB]
Get:28 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2,684 B]
Get:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [251 kB]
Get:30 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [8,519 B]
Get:31 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [975 kB]
Get:32 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:33 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [798 kB]
Get:34 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.5 kB]
Get:35 http://archive.ubuntu.com/ubuntu xenial-backports/main Sources [3,514 B]
Get:36 http://archive.ubuntu.com/ubuntu xenial-backports/universe Sources [6,198 B]
Get:37 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5,153 B]
Get:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7,734 B]
Reading package lists...
E: GPG error: https://www.phusionpassenger.com/enterprise_apt xenial Release: The following signatures were invalid: NODATA 2
The command '/bin/sh -c apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" passenger-enterprise nginx-extras' returned a non-zero code: 100

**Comment by FloorD** [comment]
For anyone still experiencing this issue: unfortunately some gpg keys were not properly imported when we migrated to a new server yesterday. The issue should be resolved now, but if you are still experiencing issues, try running `apt clean && rm -rf /var/lib/apt/lists/* && apt update` 

This will clear the local apt cache and retry the apt update.

**Comment by alexi21** [comment]
This issue appears to be resolved. Will close tomorrow if still open.

**Comment by FloorD** [comment]
We would have left it open for another week before closing it @alexi21, but thank you.

**Comment by alexi21** [comment]
no problem
