### ISSUE TITLE
Passenger 5.2.3 agent fails to initialize in nginx 

### ISSUE THREAD

**Issue by jamesbebbington** [phusion/passenger#2063]
## Issue report

**Are you sure this is a bug in Passenger?**
As far as can tell, nginx reports an issue in `Passenger::Agent::Fundamentals::initializeAgent` and refuses to start.

**Please try with the newest version of Passenger to avoid issues that have already been fixed**
Issue occurred after upgrading to 5.2.3 (latest version).

**Question 1: What is the problem?**
- What is the expected behavior?
Nginx to serve requests through passenger.

- What is the actual behavior?
NGinx fails to start and reports:
```
[ E 2018-04-11 17:38:57.8972 285/T1 age/Sha/Fun/Initialization.cpp:613 ]: *** ERROR: EOF encountered before a full scalar message could be read
     in 'void Passenger::Agent::Fundamentals::initializeAgent(int, char ***, const char *, ConfigKit::Store &, const ConfigKit::Translator &, OptionParserFunc, const LoggingKitPreInitFunc &, int)' (Initialization.cpp:582)
```
- How can we reproduce it? 
Attempt upgrade of passenger to 5.2.3 (from 5.1.12) via homebrew with nginx 1.12.2_1. Note error in log after nginx restart.

**Question 2: Passenger version and integration mode**:
open source 5.2.3/nginx.

**Question 3: OS or Linux distro, platform (including version)**:
macOS 10.13.4.

**Question 4: Passenger installation method**:
OS X Homebrew.

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.4.4, RVM, Rails 5.1.5.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No.

**Question 7: Anything else about your setup that we should know?**
None that springs to mind.

**Comment by FooBarWidget** [comment]
This is probably caused by having a Passenger Nginx module whose version does not match the actual Passenger version. Can you try `brew upgrade nginx --with-passenger`?

**Comment by jamesbebbington** [comment]
Thanks for the quick response. Yeah I did wonder whether that was necessary, but when I tried I got:

```
$  brew install nginx --with-passenger
Error: nginx 1.12.2_1 is already installed
To upgrade to 1.13.11, run `brew upgrade nginx`
```

Should I try updating nginx?

**Comment by jamesbebbington** [comment]
Yup, that fixed it, thanks @FooBarWidget.

**Comment by FooBarWidget** [comment]
Cool, glad to be of help.

By the way have you checked out [Fuse Panel](https://www.phusionpassenger.com/fuse-panel) yet? Please have a look and give us some feedback!
