### ISSUE TITLE
Passenger Standlone/NGINX 5.1.11 Freeze 

### ISSUE THREAD

**Issue by akil-rails** [phusion/passenger#2068]
Production . Passenger Standalone/NGINX 5.1.11 , installed via ruby-gems.
RHEL 6.0 

After requests in queue reach 200 (the maximum configured), passenger freezes, and does not recover (even after new requests are stopped).

passenger-status shows : 
Max pool size : 50
Requests in top-level queue : 0

Application Groups : 
Request in queue : 200

The only recourse is to restart passenger, and the cycle repeats after 20-30 mins.

The app has been running for a couple of years, in the past when the max pool was breached, the app would recover, but it has stopped recovering since yesterday.

**Comment by CamJN** [comment]
Seems like a dup of https://github.com/phusion/passenger/issues/2044
