### ISSUE TITLE
Passenger 5.3.0 crashes on start after upgrading from 5.2.3

### ISSUE THREAD

**Issue by bradland** [phusion/passenger#2078]
## Issue report

**Question 1: What is the problem?**

Our rails application crashes on launch after upgrading Passenger from 5.2.3 to 5.3.0. The Apache error log show the error message:

`App 4954 output: Assertion failed! src/agent/SpawnEnvSetupper/SpawnEnvSetupperMain.cpp:756: void execNextCommand(const Passenger::SpawnEnvSetupper::Context&, const string&): !shell.empty()`

The Passenger error report saved to tmp contains full details:

[Passenger Error Report Gist](https://gist.github.com/bradland/580ee008a748945edc3ec9b4c3c9462b#file-passenger-error-html)

**Question 2: Passenger version and integration mode**:

open source 5.3.0 Apache module

**Question 3: OS or Linux distro, platform (including version)**:

Ubuntu 14.04 LTS (Trusty)

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ X ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

- ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-linux-gnu]
- Ruby installed from Brightbox PPA
- Rails 4.2.5.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No, just a Linode VPS.

**Question 7: Anything else about your setup that we should know?**

Nothing out of the ordinary.

**Comment by FooBarWidget** [comment]
It looks like your app is being run under the `easi` user. Our code assumes that each user account has a shell configured, but in your case the `easi` account is configured with no shell.

We'll fix this assumption. In the mean time you can avoid this crash by using `usermod` to setup a shell for `easi`.

**Comment by dr-dimitru** [comment]
@FooBarWidget in our case users who runs apps are limited via `rbash`, and usually has no access to shell for security and sandboxing reasons. Hope this small highlight will help to maintain future versions.

**Comment by FooBarWidget** [comment]
Yes thank you. Most people set such sandboxed accounts' shell to /bin/false though.
