### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by flip111** [phusion/passenger#2080]
3 years ago i used this software for the first time. It worked great but i was a bit disappointed that PHP was not supported. Now there is NGINX Unit which supports Go, Perl, PHP, Python, and Ruby and they are considering to add support for node.js and java. Feels like this software is making quicker progress on the supported languages.

Please consider supporting more language .. even if it is just a shallow integration with a guide about how to make it work together. It would also be nice if there was a facility to support webservers which are compiled into a binary. Not having to write daemons for them and so ..

**Comment by CamJN** [comment]
Generic language support will be coming in the short term, it is currently slated for release in Q3 2018.

**Comment by FooBarWidget** [comment]
It's almost there. See issue #2135 and this blog post: https://blog.phusion.nl/2018/11/06/how-passenger-6-generic-language-support-is-implemented/
