### ISSUE TITLE
Add ngx_brotli module to Phusion APT nginx

### ISSUE THREAD

**Issue by aried3r** [phusion/passenger#2085]
## Feature request

**Question 1: What is the request?**
It would be nice if the shipped nginx version that comes from the Phusion APT repository would include the [ngx_brotli](https://github.com/google/ngx_brotli) module.

Additional resource:
https://caniuse.com/#feat=brotli
http://www.instantshift.com/2018/03/02/gzip-vs-brotli-compression/

**Comment by CamJN** [comment]
Thanks for the suggestion, we'll keep it in mind.

**Comment by felixbuenemann** [comment]
This would be great.

Note that the maintained fork is at: https://github.com/eustas/ngx_brotli

**Comment by SimonHausdorf** [comment]
+1 for brotli support!

**Comment by CamJN** [comment]
We're moving away from providing statically linked nginx packages, in favour of providing passenger as a dynamic module package compatible with the distro provided nginx package. So we won't be in a position to do this going forward.
