### ISSUE TITLE
Preloader Issue After Passenger 5.3.1 Upgrade on Mac El Capitan

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2086]
## Issue report

I updated a working `Passenger` to `5.3.1` (last version was `5.2.something`) and I now have an error with the preloader for some reason.

    An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger.

I've checked all possible exits from my syntax that hasn't changed in `.profile`, `.bashrc` and `.bash_profile` and nothing is there.  Nothing has changed.  This problem should have existed before, as the reference material given for this issue was written in 2014.  I do not redirect `stdout` anywhere.  

**Are you sure this is a bug in Passenger?**

I believe so.  Nothing else has changed.  

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

That's what brought on the problem to begin with.  

**Question 1: What is the problem?**
- What is the expected behavior?

For Passenger to work with nginx just fine, and the app to load properly.  

- What is the actual behavior?

The error code saying the preloader was not completed for some reason, pointing to a method.  

	/usr/local/Cellar/passenger/5.3.1/libexec/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:941:in `try_write_file': undefined method `try_write_file' for #<Hash:0x00007f825b9dbf68> (NoMethodError)
		from /usr/local/Cellar/passenger/5.3.1/libexec/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:522:in `dump_envvars'
		from /usr/local/Cellar/passenger/5.3.1/libexec/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:464:in `dump_all_information'
		from /usr/local/Cellar/passenger/5.3.1/libexec/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:394:in `about_to_abort'
		from /usr/local/Cellar/passenger/5.2.3/libexec/src/helper-scripts/rack-preloader.rb:90:in `rescue in init_passenger'
		from /usr/local/Cellar/passenger/5.2.3/libexec/src/helper-scripts/rack-preloader.rb:73:in `init_passenger'
		from /usr/local/Cellar/passenger/5.2.3/libexec/src/helper-scripts/rack-preloader.rb:155:in `<module:App>'
		from /usr/local/Cellar/passenger/5.2.3/libexec/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
		from /usr/local/Cellar/passenger/5.2.3/libexec/src/helper-scripts/rack-preloader.rb:29:in `<main>'

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

I can't publish this.  It's an error.  

**Question 2: Passenger version and integration mode**:
Open Source Version: 5.3.1, nginx: stable 1.13.12 (bottled), HEAD, with nginx integration mode

**Question 3: OS or Linux distro, platform (including version)**:
OS X 10.11.6 El Capitan, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ x ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin15]

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Nope

**Question 7: Anything else about your setup that we should know?**

Not that I know of.

**Comment by FooBarWidget** [comment]
Thanks for reporting this. Judging from the error message it indeed looks like a bug.

**Comment by daBee** [comment]
A restart fixed it.  Sorry about that.  I should have tried this earlier.

**Comment by FooBarWidget** [comment]
I just reviewed the code and it does not appear that it's a bug in our code. And seeing that this error is ephemeral, I suspect that this is a bug in Ruby 2.5.

**Comment by daBee** [comment]
Just so that you know, Ruby 2.5 was installed and under use all this time.
