### ISSUE TITLE
passenger-irb is broken

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#2087]
`passenger-irb` is broken, the xml it is parsing in `find_socket` doesn't contain a `name` tag that it expects to be there. Looks like `0184e44a` probably broke it.

I'm guessing that the fix should be in `Process.h`, but adding the description tag there (it's the name tag replacement) doesn't seem to come across in `passenger-irb`

**Comment by CamJN** [comment]
Fixed in enterprise repo.
