### ISSUE TITLE
Understanding passenger_pool_idle_time

### ISSUE THREAD

**Issue by mobitar** [phusion/passenger#2088]
I'm having an issue where setting `passenger_pool_idle_time` to any nonzero value does not automatically shut down processes after that time has passed.

Given this config:

```
http {
    passenger_max_pool_size 18;
    passenger_pool_idle_time 60;
}
```

My expectation is that for any given process, if 60s elapses (as given by `passenger-status` "Last used: 61s ago"), then that process is to be shut down immediately.

However, I'm simply not seeing this result. Several minutes will pass for any given instance where it will not have been used, and the process will remain alive.

The example in the documentation leads me to believe that there is some gotchas around this:

> If a user visits foo, but there are no processes for foo, and at the same time there are lots of application processes for bar (as many as the pool limit), then Passenger will wait until one of those bar processes is no longer handling a request. At time time, that process will be shutdown so that Passenger can spawn a foo process.

This example makes it seem like the only way an idle process will be killed is if another application is requiring freed up resources. I can go into more technical detail about my set up, but it may help to first understand which of the following is the intended behavior:

1. Idle processes are killed immediately once they are inactive for passenger_pool_idle_time, or 
2. Application processes are killed when there is pressure for them to be killed and they are inactive for passenger_pool_idle_time.

---
**Passenger version and integration mode**:
Phusion Passenger 5.1.4 open source

**OS or Linux distro, platform (including version)**:
Linux version 4.9.27-14.31.amzn1.x86_64

**Passenger installation method**:
RubyGems + Gemfile

**Your app's programming language (including any version managers) and framework (including versions)**:
Rails 5.1

**Are you using a PaaS and/or containerization? If so which one?**
No

**Comment by mobitar** [comment]
Ok, figured out what the issue was.

Apparently `passenger_pool_idle_time` only kills processes _above_ `passenger_min_instances`. Since `passenger_min_instances` defaults to 1, this means that if a process is spawned, it will not be killed no matter how much time passes.

The solution was to set `passenger_min_instances` to 0 in the top level http config, and override this in the particular server configs to 1 if necessary.

[This is](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_min_instances) what helped lead to this finding:

> Suppose that you have the following configuration:

```
http {
    ...
    passenger_max_pool_size 15;
    passenger_pool_idle_time 10;

    server {
        listen 80;
        server_name foobar.com;
        root /webapps/foobar/public;
        passenger_min_instances 3;
    }
}
```

> When you start Nginx, there are 0 application processes for 'foobar.com'. Things will stay that way until someone visits 'foobar.com'. Suppose that there is only one visitor. One application process will be started immediately to serve the visitor, while two will be spawned in the background. After 10 seconds, when the idle timeout has been reached, these 3 application processes will not be cleaned up.

> Now suppose that there's a sudden spike of traffic, and 100 users visit 'foobar.com' simultaneously. Passenger will start 12 more application processes (15 - 3 = 12). After the idle timeout of 10 seconds has passed, Passenger will clean up 12 application processes, keeping 3 processes around.

**Comment by elduglas** [comment]
> Ok, figured out what the issue was.
> 
> Apparently `passenger_pool_idle_time` only kills processes _above_ `passenger_min_instances`. Since `passenger_min_instances` defaults to 1, this means that if a process is spawned, it will not be killed no matter how much time passes.
> 
> The solution was to set `passenger_min_instances` to 0 in the top level http config, and override this in the particular server configs to 1 if necessary.
> 
> [This is](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_min_instances) what helped lead to this finding:
> 
> > Suppose that you have the following configuration:
> 
> ```
> http {
>     ...
>     passenger_max_pool_size 15;
>     passenger_pool_idle_time 10;
> 
>     server {
>         listen 80;
>         server_name foobar.com;
>         root /webapps/foobar/public;
>         passenger_min_instances 3;
>     }
> }
> ```
> 
> > When you start Nginx, there are 0 application processes for 'foobar.com'. Things will stay that way until someone visits 'foobar.com'. Suppose that there is only one visitor. One application process will be started immediately to serve the visitor, while two will be spawned in the background. After 10 seconds, when the idle timeout has been reached, these 3 application processes will not be cleaned up.
> 
> > Now suppose that there's a sudden spike of traffic, and 100 users visit 'foobar.com' simultaneously. Passenger will start 12 more application processes (15 - 3 = 12). After the idle timeout of 10 seconds has passed, Passenger will clean up 12 application processes, keeping 3 processes around.

:+1:
