### ISSUE TITLE
PassengerAgent checkAndLogSecurityUpdate seems to have crashed briefly

### ISSUE THREAD

**Issue by ianmcmahon** [phusion/passenger#2090]
We had a total web outage across several different types of webserver all running Passenger for several minutes, and postmortem revealed a whole lot of these core dumps that seem to point to 'checkAndLogSecurityUpdate' crashing:

`Jun 13 00:25:25 web-1 systemd-coredump[21701]: Process 21564 (PassengerAgent) of user 0 dumped core.

                                               Stack trace of thread 21568:
                                               #0  0x00007f2c30bb2428 __GI_raise (libc.so.6)
                                               #1  0x00007f2c30bb402a __GI_abort (libc.so.6)
                                               #2  0x00007f2c30bf47ea __libc_message (libc.so.6)
                                               #3  0x00007f2c30bff13e malloc_printerr (libc.so.6)
                                               #4  0x00007f2c30c01184 __GI___libc_malloc (libc.so.6)
                                               #5  0x00007f2c314f3e78 _Znwm (libstdc++.so.6)
                                               #6  0x0000000000471fc8 _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag (PassengerAgent)
                                               #7  0x00007f2c31587c4c _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_ (libstdc++.so.6)
                                               #8  0x0000000000571687 _ZN9Passenger21SecurityUpdateChecker25checkAndLogSecurityUpdateEv (PassengerAgent)
                                               #9  0x000000000056e83f _ZN9Passenger21SecurityUpdateChecker10threadMainEv (PassengerAgent)
                                               #10 0x00000000005b9b33 _ZNK5boost4_mfi3mf0IvN9Passenger21SecurityUpdateCheckerEEclEPS3_ (PassengerAgent)
                                               #11 0x00000000005b64e2 _ZN5boost3_bi5list1INS0_5valueIPN9Passenger21SecurityUpdateCheckerEEEEclINS_4_mfi3mf0IvS4_EENS0_5list0EEEvNS0_4typeIvEERT_RT0_i (Passenger
                                               #12 0x00000000005af666 _ZN5boost3_bi6bind_tIvNS_4_mfi3mf0IvN9Passenger21SecurityUpdateCheckerEEENS0_5list1INS0_5valueIPS5_EEEEEclEv (PassengerAgent)
                                               #13 0x00000000005a7a06 _ZN5boost6detail8function26void_function_obj_invoker0INS_3_bi6bind_tIvNS_4_mfi3mf0IvN9Passenger21SecurityUpdateCheckerEEENS3_5list1INS3_5v
                                               #14 0x000000000047a9bb _ZNK5boost9function0IvEclEv (PassengerAgent)
                                               #15 0x000000000073cc41 _ZN3oxt6thread11thread_mainEN5boost8functionIFvvEEENS1_10shared_ptrINS_20thread_local_contextEEE (PassengerAgent)
                                               #16 0x00000000005398ab _ZN5boost3_bi5list2INS0_5valueINS_8functionIFvvEEEEENS2_INS_10shared_ptrIN3oxt20thread_local_contextEEEEEEclIPFvS5_SA_ENS0_5list0EEEvNS0_4
                                               #17 0x000000000053941a _ZN5boost3_bi6bind_tIvPFvNS_8functionIFvvEEENS_10shared_ptrIN3oxt20thread_local_contextEEEENS0_5list2INS0_5valueIS4_EENSC_IS8_EEEEEclEv (P
                                               #18 0x0000000000535f6e _ZN5boost6detail11thread_dataINS_3_bi6bind_tIvPFvNS_8functionIFvvEEENS_10shared_ptrIN3oxt20thread_local_contextEEEENS2_5list2INS2_5valueIS
                                               #19 0x000000000072fc9a thread_proxy (PassengerAgent)
                                               #20 0x00007f2c322c06ba start_thread (libpthread.so.0)
                                               #21 0x00007f2c30c8441d __clone (libc.so.6)
` 

**Question 2: Passenger version and integration mode**:
opensource 5.1.5/nginx-1.9.15

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 16.04.2 LTS
**Question 4: Passenger installation method**:

Your answer:
[X] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.5.1, Rails 3.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
no

**Comment by ralfizzle** [comment]
Getting the same issue.

**Comment by natemueller** [comment]
I can confirm that setting `passenger_disable_security_update_check on` in our nginx config fixed the issue.

**Comment by richardevs** [comment]
Same here, all 10+ servers dead at the same time.

We updated the version for now and it is back working.

**Comment by zacblazic** [comment]
This is the same as #2089

**Comment by martinseener** [comment]
I can confirm this issue with Passenger 5.1.2 (and nginx) and we also found out ourselves yesterday that `passenger_disable_security_update_check on` fixed the problem for us

**Comment by FooBarWidget** [comment]
This is most definitely a duplicate of #2089.

Please see https://github.com/phusion/passenger/issues/2089#issuecomment-396699740 for actionable advice.
