### ISSUE TITLE
Passenger injects an additional, unnecessary, lower-case Content-Type header

### ISSUE THREAD

**Issue by risen** [phusion/passenger#2100]
We noticed in one of our rails apps (v4.2.7) that we were receiving the wrong Content-Type.

This is using Apache 2.4.25 + Passenger 5.0.30 on Debian; We've tried upgrading Passenger to 5.3.3 (using the phusion apt repos), but the issue persisted. This happens with POSTs and DELETEs, but not with GET.

```
DELETE /tests/3 HTTP/1.1
Accept: */*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,nl;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 0
Cookie: _xxx_session=XXX
Host: xxx.xxx
Origin: https://xxx
Pragma: no-cache
Referer: https://xxx/yyy
X-CSRF-Token: XXX==
X-Requested-With: XMLHttpRequest

HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 126
Content-Type: text/html; charset=windows-1252,text/javascript; charset=utf-8
Date: Thu, 12 Jul 2018 14:38:59 GMT
ETag: W/"47e363de6d5614870d832368a19f703d-gzip"
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.25 (Debian)
Status: 200 OK
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: 317b7e3e-0766-4321-a6d5-098038627437
X-Runtime: 0.496302
X-XSS-Protection: 1; mode=block

$('XXX').some_jquery_function();
```

In trying to figure out which component had the issue, we did the same request locally, talking to the passenger instance directly using `X-Passenger-Connect-Password`

```
DELETE /tests/3 HTTP/1.1
Accept: */*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,nl;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 0
Cookie: _xxx_session=XXX
Host: localhost:36629
Origin: https://xxx.xxx
Pragma: no-cache
Referer: https://xxx/yyy
X-CSRF-Token: XXX==
X-Passenger-Connect-Password: XXX
X-Requested-With: XMLHttpRequest



HTTP/1.1 200 Whatever
Cache-Control: max-age=0, private, must-revalidate
Connection: close
Content-Type: text/javascript; charset=utf-8
ETag: W/"27419a1cdbd2ea89ffba14dec4a840ad"
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: a854eef5-a0ab-463d-878a-956b5e9fac7d
X-Runtime: 0.065233
X-XSS-Protection: 1; mode=block
content-type: text/html; charset=windows-1252

$('XXX').some_jquery_function();
```

As you see, there's two Content-Type headers:
`Content-Type: text/javascript; charset=utf-8`
and
`content-type: text/html; charset=windows-1252`

We have no idea where the second one comes from. Apache seems to merge the headers (correctly), but there's no reason why the second one should be injected. Any idea what might be causing this?

Thank you.

**Comment by FooBarWidget** [comment]
I suspect that either the app or a Rack middleware generates this extra header. Passenger does not inject any extra Content-Type headers, certainly not in lower-case.

**Comment by risen** [comment]
I don't think so, because when I test by connecting directly to thin on port 3000 (`bundle exec rails s -e production -b 0.0.0.0`), I get this response.

```
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Connection: close
Content-Type: text/javascript; charset=utf-8
ETag: W/"a529c35c9fec6256e6a1eb29cdbdea13"
Server: thin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 45656bdf-283b-4f7c-90c8-a2043823df08
X-Runtime: 0.739981
X-XSS-Protection: 1; mode=block

$('XXX').some_jquery_function();
```

… as you can see, no lower case `content-type: text/html; charset=windows-1252` in sight.

**Comment by FooBarWidget** [comment]
Shall we do a little debugging? Please edit $(passenger-config --root)/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb.

Look for this line:

~~~ruby
status, headers, body = @app.call(env)
~~~

Right after that, add:

~~~ruby
File.open('/tmp/dump.txt', 'w') do |f|
  f.write(headers.inspect)
end
~~~

Then restart Passenger, then talk to a Passenger instance directly, then look in /tmp/dump.txt. What do you see?

**Comment by risen** [comment]
Thanks for the help; turns out I get this:
```*** Exception Errno::EACCES in Rack application object (Permission denied @ rb_sysopen - /tmp/dump.txt) (process 23369, thread 0x0056303c5fdcd8(Worker 1))```
… even though /tmp is world-writable.

So I just did `STDERR.puts(headers.inspect)` instead, and checked the log file:

```
App 30589 output: {"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "content-type"=>"text/html; charset=windows-1252", "Content-Type"=>"text/javascript; charset=utf-8", "ETag"=>"W/\"a529c35c9fec6256e6a1eb29cdbdea13\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"9c92e373-4e7d-43c9-a386-c6c82dd984a7", "X-Runtime"=>"0.019732"}
```

… so it seems you were right: passenger gets `"content-type"=>"text/html; charset=windows-1252"` from somewhere in the app.

I tried running:
```
bundle exec rackup -o 0.0.0.0 -p 3000 -E production
```
instead of:
```
bundle exec rails s -e production -b 0.0.0.0
```

and as it turns out, I see the wrong `content-type` with the former too, just like with passenger (but not in the latter). Not sure what the difference is between these two, but it seems clear now it's not passenger. The search goes on…

Thank you, and sorry for wasting your time.
