### ISSUE TITLE
Server start malloc failed error on MacOS High Sierra

### ISSUE THREAD

**Issue by jsheffel-athn** [phusion/passenger#2101]
Also posted to: https://stackoverflow.com/questions/51406942/phusion-passenger-malloc-failed-error-on-macos-high-sierra

---

## Issue report

Starting passenger with:

$ LOAD_FAST=true passenger start --pid-file tmp/x.pid

results in the following error:

App 65478 output: PassengerAgent(65481,0x7fffb856e380) malloc: *** mach_vm_map(size=1048576) failed (error code=268435459)
App 65478 output: PassengerAgent(65481,0x7fffb856e380) malloc: *** error: can't allocate region securely
App 65478 output: PassengerAgent(65481,0x7fffb856e380) malloc: *** set a breakpoint in malloc_error_break to debug
Yet, most of the time the passenger server continues to run and serve the application. Of the 16GB RAM, there is usually 3GB available.

Here is some configuration information:

$ brew info passenger
     passenger: stable 5.3.3 (bottled), HEAD
     Server for Ruby, Python, and Node.js apps via Apache/NGINX
     https://www.phusionpassenger.com/
     /usr/local/Cellar/passenger/5.2.3 (4,380 files, 179.2MB)
       Poured from bottle on 2018-04-06 at 14:33:38
     /usr/local/Cellar/passenger/5.3.3 (4,380 files, 181MB) *
       Poured from bottle on 2018-07-17 at 14:42:01
     From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/passenger.rb
     ==> Dependencies
     Required: pcre ✔, openssl ✔
     ==> Requirements
     Required: macOS >= 10.7 ✔
     ==> Caveats
     To activate Phusion Passenger for Nginx, run:
       brew install nginx --with-passenger
    /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
              PassengerDefaultRuby /usr/bin/ruby

$ /Users/developer/.rvm/gems/ruby-2.3.5@athn_web/bin/passenger-config about make-locations-ini   # update reference to new passenger
[locations]
packaging_method=unknown
bin_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/bin
support_binaries_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/buildout/support-binaries
lib_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/buildout
helper_scripts_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/src/helper-scripts
resources_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/resources
include_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/src
doc_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/doc
ruby_libdir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/src/ruby_supportlib
node_libdir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/src/nodejs_supportlib
apache2_module_path=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/buildout/apache2/mod_passenger.so
ruby_extension_source_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/src/ruby_native_extension
nginx_module_source_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/src/nginx_module
build_system_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3
download_cache_dir=/Users/developer/.rvm/gems/ruby-2.3.5@athn_web/gems/passenger-5.3.3/download_cache

$ passenger-status                                                                                                                                                   (/Users/developer/.rvm/gems/ruby-2.4.1) -I-
Version : 5.3.3
Date    : 2018-07-18 10:33:31 -0600
Instance: qXs24Ztd (nginx/1.14.0 Phusion_Passenger/5.3.3)

----------- General information -----------
Max pool size : 6
App groups    : 1
Processes     : 1
Requests in top-level queue : 0

----------- Application groups -----------
/Users/developer/workspace/advoy-rails (development):
  App root: /Users/developer/workspace/advoy-rails
  Requests in queue: 0
  * PID: 65519   Sessions: 0       Processed: 1       Uptime: 36m 15s
    CPU: 0%      Memory  : 148M    Last used: 36m 15s ago

**Comment by CamJN** [comment]
We're aware of these warnings. They are currently harmless, though annoying. They're difficult to reproduce under a debugger, and I don't currently have time to do so, given that they don't actually cause any issues besides logspam.
