### ISSUE TITLE
Passenger Dependency Issues With Ubuntu 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by blackstarESP** [phusion/passenger#2109]
I've been following the installation process located here: https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/

and I continue to receive this dependency issue when I run `sudo apt-get install -y libnginx-mod-http-passenger`: 
The following packages have unmet dependencies:
libnginx-mod-http-passenger : Depends: passenger (= 1:5.3.4-1~bionic1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I really cannot think of a way around this and have no decent ideas about what could be going wrong.  I'm running Ubuntu 18.04, NGINX, RVM with Ruby 2.0.0 and Rails 4.1.4.

**Comment by blackstarESP** [comment]
Found the solution here:https://github.com/phusion/passenger/issues/2076.  Sorry for the inconvenience if any.

**Comment by CamJN** [comment]
What happens if you install `nginx` at the same time as `ibnginx-mod-http-passenger`?

**Comment by michaelburtonray** [comment]
@blackstarESP I am getting the same error. Did you find a solution?

@CamJN When I do `sudo apt-get install -y nginx libnginx-mod-http-passenger` I still get the error

**Comment by blackstarESP** [comment]
Sorry for not responding sooner.

@michaelburtonray  @CamJN  Here is the answer: https://stackoverflow.com/questions/51778272/unable-to-install-phusion-passenger-on-ubuntu-server-18-04

You have to update `sudo nano /etc/apt/source.list` with the Gist in the accepted answer at that link.  Just paste everything below the 3 existing lines in the file, and you should be good.

Don't forget to `sudo apt update` and ` sudo apt upgrade`

**Comment by firien** [comment]
I only needed these 2 lines from the [gist](https://gist.github.com/jackw1111/d31140946901fab417131ff4d9ae92e3):

    deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
    deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe

**Comment by JPaulMora** [comment]
gist died. :/

**Comment by sircollins** [comment]
This worked for me

sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'

**Comment by jimfangx** [comment]
if you are running into this issue and looking for the gist it is on archive.org (use the earliest snapshot)

https://stackoverflow.com/a/11798274/9108905 this stack answer worked for me - leaving it here in case it helps.
