### ISSUE TITLE
Video linked in readme 410/Gone

### ISSUE THREAD

**Issue by tibbon** [phusion/passenger#2120]
Clicked on the video in the readme, which links to https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/4984/8/224923750/789267447.mp4?token=1520274300-0xc6893cd7e4a119105d32dd731bf4a34928c2c1c8

Result is a 410/gone:

```
Error 410 Gone
Gone

Guru Mediation:
Details: cache-bos8222-BOS 1537387547 227039103

Varnish cache server
```

**Comment by FooBarWidget** [comment]
Thanks for the report, this has been fixed.
