### ISSUE TITLE
Impossible to not Buffer Request Body with NGINX

### ISSUE THREAD

**Issue by SecurityInsanity** [phusion/passenger#2121]
## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Are you sure this is a bug in Passenger?** Yes. Passenger does not expose a way to configure this flag for the nginx module.

**Question 1: What is the problem?**

When attempting to process a request in a streaming fashion NGINX is currently buffering the entire request, before making a connection to the downstream app. This is controlled by the setting: `request_body_no_buffering`.

This seems to default to 1 [HERE](https://github.com/nginx/nginx/blob/4bf4650f2f10f7bbacfe7a33da744f18951d416d/src/http/ngx_http_request.h#L487). However, if you notice there's this handy: `if` statement that seems to set it to 0, if there's any request body: [HERE](https://github.com/nginx/nginx/blob/4bf4650f2f10f7bbacfe7a33da744f18951d416d/src/http/ngx_http_request_body.c#L44).

There's a couple NGINX modules that then set it _back_ to 1 to support streaming. For example [HERE](https://github.com/nginx/nginx/blob/372b624627b3f943ffd1227ff8aacbae7b42880f/src/http/modules/ngx_http_proxy_module.c#L927) in the proxy module.

However passenger doesn't seem to reference this setting anywhere, even when just grepping the repo:

```text
$  rg 'request_body_no_buffering' .
$
```

This leads to the request always being buffered in nginx. Since this functionally defaults to 0 in nginx. This should happen with any architecture, but we've provided a reproduction with a simple nodejs app.

- What is the expected behavior?

Passenger with nginx should expose a setting to allow nginx to not buffer requests before sending it on.

- What is the actual behavior?

Passenger does not expose this setting.

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:

[HERE](https://gist.github.com/SecurityInsanity/e37f47d1e7b6ecfd00ec76a74052dd5f) is a gist for the nginx configuration/single node app file.
I've also provided a dockerfile in this app which installs everything to the app.

All I do is startup the docker file by building it, and then running it:

```bash
docker build . -t passenger-test && docker run --rm -p 8080:80 -i -t passenger-test
```

Then in another terminal I generate an empty large file (easy to see with files 15GB or more), and try to upload it:

```bash
dd if=/dev/zero of=output.dat  bs=1M  count=15000
curl -H "Transfer-Encoding: chunked" -d @output.dat -XPOST http://localhost:8080
```

You'll notice that even though curl is actively doing work. The server won't log the connection exists for quite awhile. This is because passenger is buffering the full file before passing it on to the node application.

**Question 2: Passenger version and integration mode**
Your answer:

- Passenger Version: 5.3.3, Nginx v1.14.0

**Question 3: OS or Linux distro, platform (including version)**:
Your answer:

- Ubuntu 18.04 bionic beaver, NodeJS v10

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer:

- NodeJS v10, ExpressJS v4.16.3

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer:

- Docker

**Question 7: Anything else about your setup that we should know?**

Your answer: Not that I can think of.

**Comment by FooBarWidget** [comment]
One use case for this is receiving large uploads as streams, where the app must begin a response before the request is finished so that the load balancer doesn't timeout the request.

**Comment by FooBarWidget** [comment]
I have scheduled this for the next version, 5.3.6.

**Comment by FooBarWidget** [comment]
Work has begun on this issue.

Initial investigation reveals that implementing this features requires not only setting the `request_body_no_buffering ` flag (as the reporter mentions). It is also necessary to rechunk any body data that Nginx passes to the Passenger Core, otherwise it'll break Transfer-Encoding chunked requests. Implementing a data rechunker in the Nginx module is not easy and would take quite a bit of work.

**Comment by FooBarWidget** [comment]
The investigation today revealed that part of the reason why my change from last time did not work, is due to a bug in Nginx itself. Specifically, https://github.com/nginx/nginx/commit/62821f1c99f3bdb79ddbef2386060a6deb192605, which is part of version 1.15.3. This means that if we implement this feature request, then we need to bump our minimum supported Nginx version to 1.15.3.

**Comment by FooBarWidget** [comment]
One complication is that Ubuntu 18.04 does not supply such a recent Nginx version. So implementing this feature request also presents packaging challenges.

**Comment by CamJN** [comment]
This is fixed in Passenger 6.
