### ISSUE TITLE
Ubuntu 18.04 packages fail to install

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#2122]
We should release the next version asap and rebuild our packages.

~~~
The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (= 1.14.0-0ubuntu1) but 1.14.0-0ubuntu1.1 is to be installed
E: Unable to correct problems, you have held broken packages.
~~~

**Comment by theos-space** [comment]
Having the same issue on Ubuntu 18.04.01 LTS

**Comment by hamiltonc** [comment]
As a workaround while the rebuild passenger, you can install the old version with:
sudo apt install \
libnginx-mod-http-auth-pam=1.14.0-0ubuntu1 \
libnginx-mod-http-cache-purge=1.14.0-0ubuntu1 \
libnginx-mod-http-dav-ext=1.14.0-0ubuntu1 \
libnginx-mod-http-echo=1.14.0-0ubuntu1 \
libnginx-mod-http-fancyindex=1.14.0-0ubuntu1 \
libnginx-mod-http-geoip=1.14.0-0ubuntu1 \
libnginx-mod-http-headers-more-filter=1.14.0-0ubuntu1 \
libnginx-mod-http-image-filter=1.14.0-0ubuntu1 \
libnginx-mod-http-lua=1.14.0-0ubuntu1 \
libnginx-mod-http-ndk=1.14.0-0ubuntu1 \
libnginx-mod-http-perl=1.14.0-0ubuntu1 \
libnginx-mod-http-subs-filter=1.14.0-0ubuntu1 \
libnginx-mod-http-uploadprogress=1.14.0-0ubuntu1 \
libnginx-mod-http-upstream-fair=1.14.0-0ubuntu1 \
libnginx-mod-http-xslt-filter=1.14.0-0ubuntu1 \
libnginx-mod-mail=1.14.0-0ubuntu1 \
libnginx-mod-nchan=1.14.0-0ubuntu1 \
libnginx-mod-stream=1.14.0-0ubuntu1 \
nginx-common=1.14.0-0ubuntu1 \
nginx-core=1.14.0-0ubuntu1 \
nginx=1.14.0-0ubuntu1

**Comment by nleo** [comment]
Same problem 

```
xxx:~# apt install libnginx-mod-http-passenger
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (= 1.14.0-0ubuntu1.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
xxx:~# aptitude install libnginx-mod-http-passenger
The following NEW packages will be installed:
  libnginx-mod-http-passenger{b} passenger{a} passenger-dev{a} passenger-doc{a} ruby-rack{a} 
0 packages upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 6,823 kB of archives. After unpacking 50.9 MB will be used.
The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (= 1.14.0-0ubuntu1.1) but it is not going to be installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     libnginx-mod-http-passenger [Not Installed]        



Accept this solution? [Y/n/q/?] ^C
xxx:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

```

**Comment by nleo** [comment]
After `apt install nginx-common` message looks like `libnginx-mod-http-passenger : Depends: nginx-common (= 1.14.0-0ubuntu1.1) but 1.14.0-0ubuntu1.2 is installed`

**Comment by richjdsmith** [comment]
Like @nleo , I'm also running into the issue, today with a fresh install of **Ubuntu 18.04.1 LTS** after following the install instructions on the PhusionPassenger website here:

https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/


Here's my output:
```
deploy@localhost:~$ sudo apt-get install -y libnginx-mod-http-passenger
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (= 1.14.0-0ubuntu1.1) but 1.14.0-0ubuntu1.2 is to be installed
E: Unable to correct problems, you have held broken packages.
deploy@localhost:~$ The following packages have unmet dependencies:
```

**Comment by excid3** [comment]
Ditto, same issue here.

**Comment by richjdsmith** [comment]
Oh boy. It's not good when I see @excid3 show up with the same isse as me :/

I tried following @hamiltonc 's instructions above 👆 and while it appears to have installed no problem, I am unable to start NGINX.

```
deploy@localhost:~$ sudo apt install \
> libnginx-mod-http-auth-pam=1.14.0-0ubuntu1 \
> libnginx-mod-http-cache-purge=1.14.0-0ubuntu1 \
> libnginx-mod-http-dav-ext=1.14.0-0ubuntu1 \
> libnginx-mod-http-echo=1.14.0-0ubuntu1 \
> libnginx-mod-http-fancyindex=1.14.0-0ubuntu1 \
> libnginx-mod-http-geoip=1.14.0-0ubuntu1 \
> libnginx-mod-http-headers-more-filter=1.14.0-0ubuntu1 \
> libnginx-mod-http-image-filter=1.14.0-0ubuntu1 \
> libnginx-mod-http-lua=1.14.0-0ubuntu1 \
> libnginx-mod-http-ndk=1.14.0-0ubuntu1 \
> libnginx-mod-http-perl=1.14.0-0ubuntu1 \
> libnginx-mod-http-subs-filter=1.14.0-0ubuntu1 \
> libnginx-mod-http-uploadprogress=1.14.0-0ubuntu1 \
> libnginx-mod-http-upstream-fair=1.14.0-0ubuntu1 \
> libnginx-mod-http-xslt-filter=1.14.0-0ubuntu1 \
> libnginx-mod-mail=1.14.0-0ubuntu1 \
> libnginx-mod-nchan=1.14.0-0ubuntu1 \
> libnginx-mod-stream=1.14.0-0ubuntu1 \
> nginx-common=1.14.0-0ubuntu1 \
> nginx-core=1.14.0-0ubuntu1 \
> nginx=1.14.0-0ubuntu1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
Setting up libnginx-mod-mail (1.14.0-0ubuntu1) ...
Setting up libxpm4:amd64 (1:3.5.12-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up libnginx-mod-http-xslt-filter (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-http-upstream-fair (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-http-geoip (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-http-ndk (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-http-perl (1.14.0-0ubuntu1) ...
Setting up libwebp6:amd64 (0.6.1-2) ...
Setting up libnginx-mod-http-lua (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-http-uploadprogress (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-http-fancyindex (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-stream (1.14.0-0ubuntu1) ...
Setting up libnginx-mod-http-echo (1.14.0-0ubuntu1) ...
Setting up libgd3:amd64 (2.2.5-4ubuntu0.2) ...
Setting up libnginx-mod-http-image-filter (1.14.0-0ubuntu1) ...
Setting up nginx-core (1.14.0-0ubuntu1) ...
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-11-08 15:53:24 UTC; 13ms ago
     Docs: man:nginx(8)
  Process: 10420 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
 Main PID: 968 (code=exited, status=0/SUCCESS)

Nov 08 15:53:24 localhost systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 08 15:53:24 localhost nginx[10420]: nginx: [emerg] unknown directive "passenger_root" in /etc/nginx/conf.d/mod-http-passenger.conf:1
Nov 08 15:53:24 localhost nginx[10420]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 08 15:53:24 localhost systemd[1]: nginx.service: Control process exited, code=exited status=1
Nov 08 15:53:24 localhost systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 08 15:53:24 localhost systemd[1]: Failed to start A high performance web server and a reverse proxy server.
dpkg: error processing package nginx-core (--configure):
 installed nginx-core package post-installation script subprocess returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by excid3** [comment]
I was able to get things going by going all the way back to Passenger 5.3.4. 

```
sudo apt install libnginx-mod-http-auth-pam=1.14.0-0ubuntu1 libnginx-mod-http-cache-purge=1.14.0-0ubuntu1 libnginx-mod-http-dav-ext=1.14.0-0ubuntu1 libnginx-mod-http-echo=1.14.0-0ubuntu1 libnginx-mod-http-fancyindex=1.14.0-0ubuntu1 libnginx-mod-http-geoip=1.14.0-0ubuntu1 libnginx-mod-http-headers-more-filter=1.14.0-0ubuntu1 libnginx-mod-http-image-filter=1.14.0-0ubuntu1 libnginx-mod-http-lua=1.14.0-0ubuntu1 libnginx-mod-http-ndk=1.14.0-0ubuntu1 libnginx-mod-http-perl=1.14.0-0ubuntu1 libnginx-mod-http-subs-filter=1.14.0-0ubuntu1 libnginx-mod-http-uploadprogress=1.14.0-0ubuntu1 libnginx-mod-http-upstream-fair=1.14.0-0ubuntu1 libnginx-mod-http-xslt-filter=1.14.0-0ubuntu1 libnginx-mod-mail=1.14.0-0ubuntu1 libnginx-mod-nchan=1.14.0-0ubuntu1 libnginx-mod-stream=1.14.0-0ubuntu1 nginx-common=1.14.0-0ubuntu1 nginx=1.14.0-0ubuntu1 nginx-extras=1.14.0-0ubuntu1 libnginx-mod-http-passenger=1:5.3.4-1~bionic1 passenger=1:5.3.4-1~bionic1
```

**Comment by VincentSC** [comment]
Going back to Passenger 5.3.4 also worked for me.

**Comment by HLFH** [comment]
I had to uninstall nginx & passenger, before installing the last nginx & passenger.

'''bash
apt autoremove --purge  libnginx-mod* nginx python-certbot-nginx python3-certbot-nginx
sudo apt-get install -y dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt-get install -y apt-transport-https ca-certificates
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'
sudo apt-get update
sudo apt-get install -y libnginx-mod-http-passenger
'''

**Comment by brendan-pike** [comment]
Eeek, what a mess. Hopefully we get a fresh release asap.

**Comment by FooBarWidget** [comment]
We're aware of the issue and are working on a fix.

**Comment by richjdsmith** [comment]
Any chance you could reopen the issue for those poor people struggling to figure out why they're unable to install Passenger?

**Comment by jaspertandy** [comment]
I had this problem on the docker images and fixed by rolling back to phusion/passenger-ruby25:0.9.35 rather than latest, just in case anyone else is having a similar issue.

**Comment by FooBarWidget** [comment]
A fix has been found and committed. Will release asap.

**Comment by richjdsmith** [comment]
Any update so far?

**Comment by FooBarWidget** [comment]
The new packages have already been released on Sunday.

**Comment by richjdsmith** [comment]
Awesome, thanks for getting on this so quickly! 😊

**Comment by VincentSC** [comment]
And working correctly

**Comment by tbonz** [comment]
@CamJN thank you I was able to get this to work with the default nginx version 1.14.0 on bionic.  However, when I try updating to the the latest version of nginx mainline 1.15.8 I run into issues and am unable to upgrade.  Are there additional steps needed to get nginx to upgrade to the latest along with passenger module?

**Comment by CamJN** [comment]
@tbonz how are you installing nginx 1.15.8? Ubuntu only ships 1.14.0. Our nginx module package targets the ubuntu provided nginx package, if you want to target another nginx, you can use the instructions here: https://www.phusionpassenger.com/library/install/nginx/install_as_nginx_module.html.

**Comment by excid3** [comment]
Might be using the Nginx repos? https://www.nginx.com/resources/wiki/start/topics/tutorials/install/#official-debian-ubuntu-packages

**Comment by cferry322** [comment]
> Going back to Passenger 5.3.4 also worked for me.

Can you post steps for doing this?

**Comment by fernandoluizao** [comment]
I'm having the same problem, fresh ubuntu 18.04.2 LTS install. Followed the steps described in the docs:

```
sudo apt-get install -y dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt-get install -y apt-transport-https ca-certificates
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'
sudo apt-get update
sudo apt-get install -y libnginx-mod-http-passenger nginx
```

```
# apt-get install -y libnginx-mod-http-passenger nginx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: passenger (= 1:6.0.2-1~bionic1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I'm not using any custom repositories for nginx:
```
# apt-cache policy nginx
nginx:
  Installed: (none)
  Candidate: 1.14.0-0ubuntu1.2
  Version table:
     1.14.0-0ubuntu1.2 500
        500 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     1.14.0-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```
Any clues?

**Comment by fernandoluizao** [comment]
I dont know the reason, but my /etc/apt/sources.list was missing these lines:

deb http://archive.ubuntu.com/ubuntu/ bionic universe
deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe

After added, the instalation succeded.

**Comment by monsterooo** [comment]
I lowered the system version to 10.4.

everything is normal

😴

**Comment by voordev** [comment]
Still not working...

Solution?
Modification to the docs?
Time wasted on this...

**Comment by activestylus** [comment]
Still broken on a fresh ubuntu install. Very disappointing. Looks like I'm going back to puma. It's a pain with config but at least it works!

**Comment by CamJN** [comment]
@activestylus You haven't described what you did or what output you saw. But I can assure you that installing passenger and nginx on a fresh bionic (title of this issue) install does work if you follow the instructions: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/nginx/

I've just gone through the process myself to verify it.

**Comment by fernandoluizao** [comment]
@activestylus please take a look at my comment:

https://github.com/phusion/passenger/issues/2122#issuecomment-468668676

Not sure why, but in a fresh install, I didn't have universe repositories enabled. Not passenger's fault IMO.

**Comment by phpduck** [comment]
This is a nightmare to install, I'm getting the same error as the opener.

None of the mentioned solutions worked for me.

**Comment by CamJN** [comment]
@phpduck the versions mentioned in your error message must be different because we released the version of passenger compatible with the nginx in the first comment. Please include your actual output.

**Comment by faisalraza** [comment]
Facing same issue on Ubuntu 19.04.

**Comment by CamJN** [comment]
Ubuntu 19.04 is blocked on our migration to a new linux package host.

**Comment by faisalraza** [comment]
@CamJN Is there a possibility to get support soon so that I can install Passenger/Nginx on Ubuntu 19.04?
It'd be great if you can please share the alternative solution for the installation.

**Comment by CamJN** [comment]
You can build from the tarball method: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/nginx/

I'm close to finishing the repo migration, so it shouldn't be much longer before I can get a proper 19.04 release out.

**Comment by blueMesaEngineering** [comment]
Hello

I have one.  I am using a Linode Ubuntu 18.04 LTS instance. 

I have 
`deb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main
`
in passenger.list and I have
`deb http://nginx.org/packages/ubuntu/ bionic nginx
deb-src http://nginx.org/packages/ubuntu/ bionic nginx
`
in nginx.list.

My error:
`sudo apt-get install -y libnginx-mod-http-passenger
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (>= 1.10.3-1+deb9u2) but it is not going to be installed
                               Depends: nginx-common (< 1.10.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

I have done this successfully on AWS before a few months ago by following the documentation provided. I searched and found this here so I thought since it was active, I would post.

Any suggestions? I'm considering going back to an older version - that could work.

Thanks

**Comment by fernandoluizao** [comment]
@blueMesaEngineering  please take a look at my comment:

https://github.com/phusion/passenger/issues/2122#issuecomment-468668676

Not sure why, but in a fresh install, I didn't have universe repositories enabled. Looks like you have the same problem.

**Comment by blueMesaEngineering** [comment]
> @blueMesaEngineering please take a look at my comment:
> 
> [#2122 (comment)](https://github.com/phusion/passenger/issues/2122#issuecomment-468668676)
> 
> Not sure why, but in a fresh install, I didn't have universe repositories enabled. Looks like you have the same problem.

Hi Fernando - thanks for the response.

Here is the pertinent info in my sources.list:
deb http://mirrors.linode.com/ubuntu/ bionic universe
# deb-src http://mirrors.linode.com/ubuntu/ bionic universe
deb http://mirrors.linode.com/ubuntu/ bionic-updates universe
# deb-src http://mirrors.linode.com/ubuntu/ bionic-updates universe

So I assumed these would be the same as the ones you suggested in your comment, since "bionic universe" and "bionic-updates universe".  However, it's a mirror on Linode, so maybe it's different.

I'll try with the archive repos you suggested and see what happens.

Thanks

**Comment by blueMesaEngineering** [comment]
Heyo,

After a couple installation cycle and purges of nginx, I'm still getting a similar response:
sudo apt-get install libnginx-mod-http-passenger
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: passenger (= 1:6.0.2-1~stretch1) but it is not going to be installed
                               Depends: nginx-common (>= 1.10.3-1+deb9u2) but it is not going to be installed
                               Depends: nginx-common (< 1.10.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I guess perhaps I'll have to tinker with installing older versions :/

Thanks

**Comment by Davidtsang** [comment]
In the end, I solved this problem. It is my fault, my system is 16.04, I thought it was 18.04, the installation method is different...

**Comment by sanjayojha** [comment]
I get the same error on ngnix 1.17.4 and Ubuntu 18.04 (aws ec2). How can I fix it?

**Comment by CamJN** [comment]
@sanjayojha and anyone else that still has issues, please file a new bug this one is too crowded to keep track of what each person is experiencing.

**Comment by DallasFett** [comment]
> 
> 
> @activestylus You haven't described what you did or what output you saw. But I can assure you that installing passenger and nginx on a fresh bionic (title of this issue) install does work if you follow the instructions: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/nginx/
> 
> I've just gone through the process myself to verify it.

05/05/2020 and this is still an issue, followed every piece of instructions specially this, still same error. 

[https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/nginx/](url)

**Comment by aivils** [comment]
Under Ubuntu 18.04 LTS
```
apt install aptitude
aptitude install -y libnginx-mod-http-passenger
```
aptitude instead of stopping will downgrade nginx to appropriate version. nginx will be older but working with passenger.
