### ISSUE TITLE
Leaking database connections with 5.3.5

### ISSUE THREAD

**Issue by rmc3** [phusion/passenger#2125]
**Question 1: What is the problem?**

- What is the expected behavior?

In well-behaved deployments of our Ruby on Rails application, we see several Postgres database connections from Ruby processes that scale up and down with load on the application. In relatively idle deployments, this number is usually between 4 and 10.

- What is the actual behavior?

As each Ruby process spawns, it opens a Postgres database connection that remains open indefinitely and appears to remain idle. With a pool of 40 workers, instead of 4 to 10 connections open we end up seeing 44 to 50.

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

This has only been reproducible with two of our many microservices, and only in docker containers built with specific versions of the open source passenger Nginx and Passenger packages from the Phusion APT repositories. There's nothing obvious in the logs that indicates what's causing this behavior. The issue became evident as soon as we deployed images built with these new Nginx and Passenger packages. There were no code changes associated with this behavior; the first time it was observed was after a daily redeploy of the environment.

**Question 2: Passenger version and integration mode**:

This issue was observed with:

Open source Passenger with Nginx, with the following packages from the Phusion APT repositories:

- passenger=1:5.3.5-1~trusty1
- nginx-common=1:1.14.0-8.5.3.5~trusty1
- nginx-extras=1:1.14.0-8.5.3.5~trusty1

We've worked around this issue by deploying new images built with the following:

Open source Passenger with Nginx, with the following packages from the Phusion APT repositories:

- passenger=1:5.3.4-1~trusty1
- nginx-common=1:1.14.0-8.5.3.4~trusty1
- nginx-extras=1:1.14.0-8.5.3.4~trusty1

**Question 3: OS or Linux distro, platform (including version)**:

- Ubuntu 14.04 Docker images running on Ubuntu 14.04 Docker hosts in AWS ECS, connected to AWS RDS Postgres 9.6.

**Question 4: Passenger installation method**:

[x] Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.4.2, rbenv, Rails 4.2.8

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

AWS ECS hosts created with custom Ubuntu 14.04 images running Docker 17.12.1-ce

**Comment by CamJN** [comment]
Can you please check whether this issue persists in 5.3.7?

**Comment by rmc3** [comment]
@CamJN This issue appears to be resolved with 5.3.7. Thanks!
