### ISSUE TITLE
Passenger on Apache not initializing, even when it is running

### ISSUE THREAD

**Issue by orksomrc** [phusion/passenger#2126]
I have Passenger version 5.3.5 installed on my RHEL 7.5 instance with Apache 2.4. `passenger_module` is loaded. 

When I run `passenger-status` I get the following response:

    ERROR: Phusion Passenger doesn't seem to be running. If you are sure that it is running, then the causes of this problem could be:
    
    1. You customized the instance registry directory using Apache's PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir option, or Phusion Passenger Standalone's --instance-registry-dir command line argument. If so, please set the environment variable PASSENGER_INSTANCE_REGISTRY_DIR to that directory and run passenger-status again.
    2. The instance directory has been removed by an operating system background service. Please set a different instance registry directory using Apache's PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir option, or Phusion Passenger Standalone's --instance-registry-dir command line argument.

I ran `passenger start` in a new `screen` and then restarted apache, it had the following error in the Apache error log:

    Wed Oct 10 20:38:43.450704 2018] [passenger:error] [pid 23780] *** Passenger could not be initialized because of this error: Unable to start Phusion Passenger: 

    Support binary PassengerAgent not found (tried: /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.19/buildout/support-binaries/PassengerAgent and /root/.passenger/support-binaries/5.3.5/PassengerAgent). There may be different causes for this:
    - Your 'PassengerRoot' setting is set to the wrong value. Please see https://www.phusionpassenger.com/library/config/apache/reference/#passengerroot to learn how to fix the value.
    
    - The PassengerAgent binary is not compiled. Please run this command to compile it: /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.19/bin/passenger-config compile-agent
    
    - Your Passenger installation is broken or incomplete. Please reinstall Passenger.

I ran `passenger start` in `screen` and ran `passenger status` outside the screen, which gave the following result:

        Version : 5.3.5
    Date    : 2018-10-10 21:46:34 +0000
    Instance: R9CNUKQy (nginx/1.14.0 Phusion_Passenger/5.3.5)
    
    ----------- General information -----------
    Max pool size : 6
    App groups    : 0
    Processes     : 0
    Requests in top-level queue : 0
    
    ----------- Application groups -----------

I then restarted restarted apache, but there was a fresh entry in the apache error log for the same `PassengerAgent not found`. 

The output of `passenger-memory-stats`:

    ------- Apache processes --------
    
    ### Processes: 0
    ### Total private dirty RSS: 0.00 MB
    
    
    -------- Nginx processes --------
    
    ### Processes: 0
    ### Total private dirty RSS: 0.00 MB
    
    
    ----- Passenger processes -----
    PID    VMSize    Private  Name
    -------------------------------
    11612  355.2 MB  2.2 MB   Passenger watchdog
    11615  650.0 MB  5.7 MB   Passenger core
    11631  86.7 MB   0.8 MB   /usr/lib64/passenger/support-binaries/PassengerAgent temp-dir-toucher /tmp/passenger-standalone.on9i3i --cleanup --daemonize --pid-file /tmp/passenger-standalone.on9i3i/temp_dir_toucher.pid --log-file /home/ec2-user/passenger.3000.log --nginx-pid 11626
    ### Processes: 3
    ### Total private dirty RSS: 8.74 MB

What's going on here? Should I be running Passenger this way at all? Shouldn't it run automatically because of `passenger_module` being loaded by apache?

[My `httpd.conf` file][1] 

  [1]: https://pastebin.com/Q2bbj8jS

**Comment by CamJN** [comment]
You have a few problems:

Your apache config has an error (though not in the part you included in your link, look for `passenger.conf`), it's looking for passenger 3.0.19: `/usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.19/buildout/support-binaries/PassengerAgent`. Try clearing out all but the newest install of Passenger, then check your apache config with `passenger-config validate-install`.

You are running apache and passenger standalone at the same time, don't do that it's not necessary. Apache will start passenger if you configured it correctly.

**Comment by orksomrc** [comment]
I placed the line `LoadModule passenger_module modules/mod_passenger.so` on top of the `passenger.conf` file, and then restarted apache again. The error from `validate-install` disappeared. 

However `passenger status` is still showing the error that Passenger Standalone is not running. 

And the output now of `sudo passenger-memory-stats` is:

```
Version: 5.3.5
Date   : 2018-10-11 04:39:26 +0000

------- Apache processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


-------- Nginx processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


---- Passenger processes -----
PID   VMSize    Private  Name
------------------------------
3157  354.9 MB  2.0 MB   Passenger watchdog
3161  649.8 MB  5.5 MB   Passenger core
### Processes: 2
### Total private dirty RSS: 7.58 MB
```

**Comment by orksomrc** [comment]
I found this from `cat /home/ec2-user/passenger.3000.log | grep error`
```
2018/10/10 21:46:13 [error] 11629#0: *4 "/home/ec2-user/public/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "HEAD / HTTP/1.1", host: "0.0.0.0"
```

I have purposefully not placed any file in that directory because the Django app running behind the WSGI daemon process should be the home, not the one in EC2's home page.

**Comment by orksomrc** [comment]
Another update after rebooting my EC2 box:

`passenger status`:

```
*** Cleaning stale instance directory /tmp/passenger.LEeDTna
Version : 5.3.5
Date    : 2018-10-11 14:44:38 +0000
Instance: qE63Kzed (Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/5.4.16 mod_python/3.5.0- Python/2.7.5 mod_wsgi/3.4 Phusion_Passenger/5.3.5)

Phusion Passenger is currently not serving any applications.

```

`passenger-memory-stats`:

```
Version: 5.3.5
Date   : 2018-10-11 14:45:21 +0000

------- Apache processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


-------- Nginx processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


---- Passenger processes -----
PID   VMSize    Private  Name
------------------------------
3157  354.9 MB  ?        Passenger watchdog
3161  649.8 MB  ?        Passenger core
### Processes: 2
### Total private dirty RSS: 0.00 MB (?)
*** WARNING: Please run this tool with sudo. Otherwise the private dirty RSS (a reliable metric for real memory usage) of processes cannot be determined.
```

**Comment by CamJN** [comment]
`passenger status` is not the same as `passenger-status`, you want the latter, as you saw. 

Is apache running in the last `passenger-memory-stats` output? if not you should start apache.

If apache can't start check `apachectl -t` to validate the apache config.

**Comment by orksomrc** [comment]
@CamJN here is the output for memory stats:

```
Version: 5.3.5
Date   : 2018-10-11 21:56:34 +0000

------- Apache processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


-------- Nginx processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


---- Passenger processes -----
PID   VMSize    Private  Name
------------------------------
3157  354.9 MB  2.0 MB   Passenger watchdog
3161  649.8 MB  5.6 MB   Passenger core
### Processes: 2
### Total private dirty RSS: 7.63 MB
```

It appears apache is not running, but upon checking `systemctl status httpd` it says it is running. 

Also output of `apachectl -t` is `Syntax OK`

What seems to be the issue for 0 passenger processes running on apache?

**Comment by CamJN** [comment]
That's a separate issue which we are aware of, given the output you are seeing it is likely that passenger is operating normally, you can check with curl if you like.

**Comment by orksomrc** [comment]
Okay thanks.
