### ISSUE TITLE
Use ruby from RVM

### ISSUE THREAD

**Issue by flip111** [phusion/passenger#2128]
Hello. I installed rvm and ruby with root user using the following commands:

```
apt-add-repository -y ppa:rael-gc/rvm
apt update
apt install -y rvm
rvm install ruby
adduser root rvm
```

When installing phusion passenger i noticed it downloads ruby2.3 from the system repository. Is there a way to avoid this and use the already installed ruby? Or if ruby2.3 is required specifically (instead of 2.5.*) use rvm to install it?

**Comment by CamJN** [comment]
Passenger only installs ruby for you if you install from a rpm or deb package. If you install Passenger from the gem, you can avoid pulling in another ruby.
