### ISSUE TITLE
Documentation to deploy rails app with Capistrano is not correct

### ISSUE THREAD

**Issue by jedrekdomanski** [phusion/passenger#2136]
## Issue report

**Question 1: What is the problem?**

Your answer: I have followed step-by-step your official instructions how to set up Passenger with Nginx and Capistrano and did EXACTLY as you said and it does not work. I spent the whole day trying to debug it and it led me to the trace where the issue is. 
```
sudo strace -p 17962 -e trace=file -f
strace: Process 17962 attached
stat("/home/deploy/bikeramp/current/public/", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/home/deploy/bikeramp/current/public/index.html", 0x5597e1411da0) = -1 ENOENT (No such file or directory)
stat("/home/deploy/bikeramp/current/passenger_wsgi.py", 0x5597e13f2f20) = -1 ENOENT (No such file or directory)
stat("/home/deploy/bikeramp/current/config.ru", {st_mode=S_IFREG|0664, st_size=130, ...}) = 0
```
[Here](https://www.phusionpassenger.com/library/deploy/nginx/automating_app_updates/ruby/#configure-passenger) you said:

> "As configured in config/deploy.rb, Capistrano will deploy app releases to /var/www/myapp/releases, with /var/www/myapp/current pointing to the latest release. So Passenger must be configured to serve the app from /var/www/myapp/current/public.
> 
> Open the Nginx configuration file in which your app's virtual host is defined. Modify the root directive, and point it to /var/www/myapp/current/public. Notice the public part after /var/www/myapp/current. When done, restart Nginx."

I have my app at `/home/deploy/bikeramp` and it looks like Nginx is looking for `index.html` file there and it doesn't find it.

`/etc/nginx/nginx.conf`
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	##
	# Phusion Passenger config
	##
	# Uncomment it if you installed passenger or passenger-enterprise
	##
	
	include /etc/nginx/passenger.conf;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```
##/etc/nginx/passenger.conf
```
passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby /usr/bin/passenger_free_ruby;
```
## /etc/nginx/sites-enabled/bikeramp.conf
```
server {
    listen 80;
    server_name somedomain.com;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /home/deploy/bikeramp/current/public;

    # Turn on Passenger
    passenger_enabled on;
    passenger_ruby /home/deploy/.rvm/gems/ruby-2.5.1/wrappers/ruby;
}
```
Capistrano passes all the steps but on the end it says this:
```
00:42 passenger:restart
      01 passenger-config restart-app /home/deploy/bikeramp --ignore-app-not-running
      01 There are no Phusion Passenger-served applications running whose paths begin with '/home/deploy/bikeramp
      01
    ✔ 01 deploy@54.38.36.242 0.579s
```
`ls /home/deploy/bikeramp` #=>current  releases  repo  revisions.log  shared
`ls /home/deploy/bikeramp/current/public` #=>assets  robots.txt  system  uploads

Am i missing something?

**Question 2: Passenger version and integration mode**:

 Open source standalone the latest version

**Question 3: OS or Linux distro, platform (including version)**:

 Ubuntu 16.04 Xenial

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

 RVM Ruby 2.3.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer: No

**Question 7: Anything else about your setup that we should know?**

Your answer:
I followed all your instructions on installation of Nginx and Passenger from [here](https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/) and they do not work.
Passenger installation verification check returns 'Eveything looks good :-)', nginx return its homepage correctly, passenger and nginx are running, I have restarted them several times.
I am out of ideas. Please help.

**Comment by CamJN** [comment]
The `There are no Phusion Passenger-served applications running whose paths begin with '/home/deploy/bikeramp` message is a red-herring, the `--ignore-app-not-running` flag causes it to not be an issue. Can you provide the nginx and passenger logs please?

**Comment by jedrekdomanski** [comment]
Well, I did everything exactly as you said in the docs but it never worked and then I decided to compile Nginx from source and install passenger as a gem and only then did it create proper Nginx configuration files and it worked.
