### ISSUE TITLE
Ubuntu/debian packages, version pinning and major versions

### ISSUE THREAD

**Issue by sandstrom** [phusion/passenger#2138]
I've found it tricky to handle version pinning with Nginx + Passenger.

> Version '1.14.0-0ubuntu1.1' for 'nginx-extras' was not found [example]
> Version '1:5.3.5-1~bionic1' for 'libnginx-mod-http-passenger' was not found [another example]

With packages in linux distributions, pinning to versions is hard. As I've understood it, most packages choose to bake the version into the apt-repository path instead. That way you get the guarantee of no major bumps, but there may be minor updates.

Have you considered moving to such a model?

Right now, if we'd drop the pinning, we can't know if passenger will update to a new major version on some future deploy. But with version pinning, installs will fail and we need to update the pin (see examples above).

Ubuntu: 18.04
Passenger: 5.3.5 (nginx mode)

**Comment by nleo** [comment]
Same problem. Relates https://github.com/phusion/passenger/issues/2122

**Comment by siasmj** [comment]
I am able to reproduce this issue on multiple servers running Ubuntu 18.04.1.

**Comment by CamJN** [comment]
We recently implemented this: https://github.com/phusion/passenger_apt_automation/commit/804c1dac554f2fa975c8c335a69a15caadb10270 will this work for you, and if not what still doesn't work? Thanks!
