### ISSUE TITLE
Installation on Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by rwky** [phusion/passenger#2140]
This appears to be the same issue as #2122 which is now closed

```
 libnginx-mod-http-passenger : Depends: nginx-common (= 1.14.0-0ubuntu1.1) but 1.14.0-0ubuntu1.2 is to be installed
```
Have you thought about using a >= in the control file instead of = ?

**Comment by FooBarWidget** [comment]
Nginx has no stable ABI, so >= does not ensure compatibility. Having said that, I'm trying to come up with a way to lock down to a specific minor version of Nginx while ignoring distro-specific patch versions (i.e. locking down to nginx-common >= 1.14.0, < 1.14.1)

**Comment by rwky** [comment]
You should be able to do something like this:

`nginx-common >= 1.14.0, nginx-common << 1.14.1` that should do the trick

**Comment by FooBarWidget** [comment]
Thanks @rwky. Will release asap.
