### ISSUE TITLE
Container autodetect fails when not running in docker

### ISSUE THREAD

**Issue by SniperCZE** [phusion/passenger#2143]
Passenger looks for existing of .dockerenv file to check if running in container:
https://github.com/phusion/passenger/blob/7d9fda06ebf1360537bdb60f82e60fea600b0d49/src/cxx_supportlib/SystemTools/ContainerHelpers.h#L25
Not all containers are docker, we have LXC/LXD here and this check will fail on it. You should use multiple checks, like environment variable container (see https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker/20010626#20010626) to determinate if passenger is running inside container.

Steps to reproduce:
1) Run passenger in another container environment than docker
2) Call autoDetectInContainer() function

Actual result:
False is returned

Exceptected result:
True is returned

**Comment by CamJN** [comment]
I agree that the existing check is definitely too docker specific. Being somewhat less familiar with LXC/LXD I wonder if you could confirm some things for me.

Do LXC/LXD containers prevent modifying the OOM score of processes in the container?
What are the contents of `/proc/1/cgroups` in your container?
Is the `container` the official method of determining containerization status of an LXC/LXD container? Are there docs anywhere to this effect, or is it an unofficial standard? 

Thanks!

**Comment by SniperCZE** [comment]
OOM score cannot be adjusted if unprivileged container. it is hard kernel limitation - unprivileged container cannot set higher than current value to prevent users start unkillable processes (unprivileged containers can be started by normal users).

I don't know if container envvar is official way to detect, but it works. Content of `/proc/1/cgroup` is not reliable anymore, at least for LXD on Ubuntu 18 is same for container and host. Systemd has systemd-detect-virt util, which can detect multiple virtualisation technology, maybe you should look over their solution (I believe systemd is reliable source of kernel hacks).

**Comment by CamJN** [comment]
Can you build and test the `GH-2143_container_autodetection` branch under your setup? I've implemented the logic from the systemd container detector more or less.
