### ISSUE TITLE
Add find by PID support to `passenger-status`

### ISSUE THREAD

**Issue by saveriomiroddi** [phusion/passenger#2146]
In my company, we perform some scripted operations, which involve `passenger-status`.

Currently, `passenger-status` uses the instance name to identify the Passenger processes. This is OK, however, working with instance names in a shell scripting context is more complex than with PIDs.

I think adding a `-p`/`--pid` option to `passenger-status` would add this functionality in a non-intrusive and consistent way, while still being consistent both with the tool UX and the internals (`Instance` carries the PID).

I can easily open a PR for this; with this issue I wanted to know if this addition is acceptable or not :smile:.

**Comment by CamJN** [comment]
This seems fine to me, @FloorD would you like to point out the contributing agreement & whatnot?
