### ISSUE TITLE
checking for GD library in /opt/local/ ... not found ( Application failed

### ISSUE THREAD

**Issue by gaukhush** [phusion/passenger#2148]
When using ngx_mruby to build application it fails as below.

checking for GD library in /usr/local/ ... not found
checking for GD library in /usr/pkg/ ... not found
checking for GD library in /opt/local/ ... not found

./configure: error: the HTTP image filter module requires the GD library.
You can either do not enable the module or install the libraries.

It looks like something went wrong

Please read our documentation for troubleshooting tips:

https://www.phusionpassenger.com/library/install/nginx/
https://www.phusionpassenger.com/library/admin/nginx/troubleshooting/

If that doesn't help, please use our support facilities. We'll do our best to help you.

https://www.phusionpassenger.com/support

**Comment by CamJN** [comment]
The nginx image lib seems to need gd, which is this project https://libgd.github.io/ perhaps try installing it? I’m pretty sure this isn’t a dependency we introduced.

**Comment by gaukhush** [comment]
@CamJN we tried to install dependency like ( libgd, libgeoip, libatomic_ops) we see this fails at

objs/src/misc/ngx_cpp_test_module.o \
objs/addon/nginx_module/ngx_http_passenger_module.o \
objs/addon/nginx_module/Configuration.o \
objs/addon/nginx_module/ContentHandler.o \
objs/addon/nginx_module/StaticContentHandler.o \
objs/ngx_modules.o \
-Wl,-E -ldl -lpthread -lcrypt /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/LoggingKit.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Exceptions.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/PathManip.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/FileManip.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/PathSecurityCheck.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/ProcessManagement/Spawn.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/ProcessManagement/Utils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/SystemTime.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/StrIntUtils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/StrIntUtilsNoStrictAliasing.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/IOUtils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/Hasher.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/jsoncpp.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/WatchdogLauncher.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/AppTypes.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/Utils/CachedFileStat.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/JsonTools/CBindings.o /usr/local/shopmatic/passenger/buildout/common/libpassenger_common/FileTools/PathManipCBindings.o /usr/local/shopmatic/passenger/buildout/common/libboost_oxt.a -lstdc++ -lpthread -lm -lrt -L/usr/local/shopmatic/ngx_mruby/mruby/build/host/lib -L/usr/local/lib -lmruby -lm -lreadline -lcrypto -lpthread -lpthread -lrt -lpthread -lrt /usr/local/shopmatic/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/lib/libhiredis.a -L -lmruby -lstdc++ -lpcre -lssl -lcrypto -ldl -lpthread -lz -lxml2 -lxslt -lexslt -lgd -lGeoIP -latomic_ops \
-Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lc -lcrypt \
-Wl,-E
/usr/bin/ld: cannot find -lperl
collect2: error: ld returned 1 exit status
objs/Makefile:349: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '/usr/local/shopmatic/ngx_mruby/build_dynamic/nginx-1.15.7'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

Your help to fix this highly appreciated.

**Comment by CamJN** [comment]
`cannot find -lperl` means you need perl too as a dependency.

**Comment by gaukhush** [comment]
@CamJN thanks but when tried see in internet we see a lot of results to install and also when checked in server we have perl version 5 22 installed. Can you provide some link or command to fix ?

**Comment by CamJN** [comment]
if you `export LD_DEBUG=all` before trying to compile you'll get better output from the linker about what exactly went wrong when it tried to link perl.

But as a first guess, is there a `perl.so` or `perl.a` in `/usr/lib/x86_64-linux-gnu/perl/5.22/CORE` and is it readable by the user which is doing the compilation?

**Comment by gaukhush** [comment]
@CamJN will post you updated on monday ..stepped out.

**Comment by gaukhush** [comment]
@CamJN 

I did this to fix passenger success. 

cd /usr/local
sudo wget https://github.com/libgd/libgd/releases/download/gd-2.2.5/libgd-2.2.5.tar.gz
sudo tar -xvof libgd-2.2.5.tar.gz
sudo mv libgd-2.2.5.tar.gz /tmp
cd libgd-2 .2.5
sudo ./configure
sudo make
sudo make install

sudo wget http://www.maxmind.com/app/c
sudo wget https://github.com/maxmind/geoip-api-c/releases/download/v1.6.11/GeoIP-1.6.11.tar.gz
sudo tar -xvof GeoIP-1.6.11.tar.gz
sudo mv GeoIP-1.6.11.tar.gz /tmp
cd GeoIP-1.6.11
sudo ./configure
sudo make
sudo make install

sudo wget https://github.com/ivmai/libatomic_ops/releases/download/v7.6.8/libatomic_ops-7.6.8.tar.gz
sudo tar -xvof libatomic_ops-7.6.8.tar.gz
sudo mv libatomic_ops-7.6.8.tar.gz /tmp
cd libatomic_ops-7.6.8
sudo ./configure
sudo make
sudo make install

sudo apt install libgd-dev
sudo apt install libwebp-dev
sudo apt install libgd-lua
sudo apt install libperl-dev
cd /usr/local/libgd-2.2.5
sudo ./configure --with-webp
sudo make
sudo make install
cd /usr/local/shopmatic
sudo rm -rf *
sudo ~/saturn/nginx/build_all.sh
