### ISSUE TITLE
Not a passenger issue (was: how to spawn completely independent child proces)

### ISSUE THREAD

**Issue by Tectract** [phusion/passenger#2149]
I have a Ruby-on-Rails app being served by Passenger under apache2. 

In one of my ruby controllers, a function is called which is supposed to spawn / fork a child process. It works fine.

Now, the problem comes when I do an apache restart. The spawned child process also dies.

I've tried things like 

    result = `((myChildScript.sh &)&)`

and

    (pid = fork) ? Process.detach(pid) : exec("nohup myChildScript.sh &");

but the dang child is still always getting killed when apache is restarted. How do I make Passenger-served app able to fork off an independent process that can live past an apache restart?

**Comment by CamJN** [comment]
Have you considered allowing the separate process to be started by your init system? Is there a reason it must be started by your rails app?

**Comment by Tectract** [comment]
Hi there. I was able to solve this issue. The solution was actually luckily pretty easily, and also a little surprising. It goes back to the very heart of what a deamon process is, in linux.

I was able to get my child ruby to completely drop any relationship to it's parent and become an "independent child" by **deamonizing** it explicitly within the script itself, by wrapping the internal "loop begin" function call within a deamonization routine, as such:

    begin
      # deamonize this process right here...
      pid = fork do
        exit if fork
        Process.setsid
        exit if fork
        startLoop    # call the to internal script logic here
      end
    rescue Exception => e
      print = "rescued exception: #{e}\n"
    end


Now I am able to call this function within my ruby controller, using either of the above listed methods, and the script launches a child which then deamonizes itself and becomes independent of apache, allowing me to do my apache-restarts when I need to without killing all my client's launched children processes :)

Cheers~
