### ISSUE TITLE
underscores_in_headers on not work(passenger 6.0.0)

### ISSUE THREAD

**Issue by labolado** [phusion/passenger#2157]
I migrated from puma, and everything is ok except the underscores_in_headers directive not working. 

It's easy to update the serverside code, but it's impossible to upgrade all the client apps.
what shall I do know?

**Comment by CamJN** [comment]
Both Nginx and Passenger filter underscores as it's a security issue, so both need to be adjusted. The first line below does Nginx, the second does Passenger.
```
underscores_in_headers on;
passenger_set_header X-MY-HEADER-NAME $http_x_my_header_name;
```


# Note this is a bad idea and people should try not to do this.
