### ISSUE TITLE
Passenger 3.x Standalone Binaries Connection Timeout

### ISSUE THREAD

**Issue by jediballono** [phusion/passenger#2159]
Hi! I am trying to test our gem for Passenger 3.x support but whenever I try to run my application using **bundle exec passenger start** and install the needed data for the Passenger (3.0.21) Standalone Binaries, I am getting a connection time out error. 

**OS:** Ubuntu 18.04
**Ruby Version:** Ruby 2.3.0
**Rails Version:** Rails 3.2.22
**Rbenv Version:** rbenv 1.1.1-39-g59785f6

```
# wget -O /tmp/passenger.20190118-7642-1mmkq5k/support.tar.gz http://standalone-binaries.modrails.com/3.0.21-x86_64-ruby2.3.0-linux-gcc7.3.0-1011/support.tar.gz
--2019-01-18 15:08:12--  http://standalone-binaries.modrails.com/3.0.21-x86_64-ruby2.3.0-linux-gcc7.3.0-1011/support.tar.gz
Resolving standalone-binaries.modrails.com (standalone-binaries.modrails.com)... 72.232.173.34
Connecting to standalone-binaries.modrails.com (standalone-binaries.modrails.com)|72.232.173.34|:80... failed: Connection timed out.
Retrying.
    
--2019-01-18 15:10:24--  (try: 2)  http://standalone-binaries.modrails.com/3.0.21-x86_64-ruby2.3.0-linux-gcc7.3.0-1011/support.tar.gz
Connecting to standalone-binaries.modrails.com (standalone-binaries.modrails.com)|72.232.173.34|:80... failed: Connection timed out.
Retrying.
```

I got this 3.0.21 version (source tarball) from your [Github Releases.][1]

  [1]: https://github.com/phusion/passenger/releases?after=release-3.0.21
It seems like the site is already down, if so, are there any mirrors for the Passenger 3.x versions? Any thoughts on how else I could test my gem on older versions of Passenger?

Thank you!

**Comment by CamJN** [comment]
Wow, that IS very old. I'll see what I can dig up, but we [don't officially support](https://www.phusionpassenger.com/support#passenger) such old versions of Passenger.

**Comment by CamJN** [comment]
Unfortunately we don't have any binaries lying around. But Passenger falls back to compiling the binaries from source so you could build your own if you like.
