### ISSUE TITLE
PassengerFriendlyErrorPages cannot occur within <If> section

### ISSUE THREAD

**Issue by isodude** [phusion/passenger#2160]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:
- What is the expected behavior?
It should work according to documentation, allowing PassengerFriendlyErrorPages inside an If section.
- What is the actual behavior?
It doesn't allow it, nor does it allow that statement in .htaccess.

The following error is printed.
```
AH00526: Syntax error on line XXX of /etc/apache2/conf/httpd.conf:
PassengerFriendlyErrorPages cannot occur within <If> section
```
- How can we reproduce it? 
Add the following in an .htaccess or in a VirtualHost statement, try syntax checking (httpd -t)
```
<If "-R '127.0.0.1'">
     PassengerFriendlyErrorPages on
</If>
```

**Question 2: Passenger version and integration mode**:
Your answer:
- alt-mod-passenger-5.3.7-1.el7.cloudlinux.x86_64;ea-apache24-2.4.37-1.el7.cloudlinux.x86_64
- open source 5.3.7-1/apache

**Question 3: OS or Linux distro, platform (including version)**:

Your answer:
- CloudLinux 7.6, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:
[x] CloudLinux YUM repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:
- Not related

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:
- QEMU with KVM

**Question 7: Anything else about your setup that we should know?**

Your answer:
- It's a cPanel with CloudLinux install.
---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**More information**
I did solve it by editing the code.

I reverted this line https://github.com/phusion/passenger/commit/40b92dd4482b8ff5b2d0de242c44f2f61db0ad54#diff-1d1e7dfbbb1ffdeb57d38e0c71c470a8L149
and if I added :context => :location in config_options.rb for PassengerFriendlyErrorPages it will work properly.

It feels like it was left out during commit 40b92dd4482b8ff5b2d0de242c44f2f61db0ad54, because now it defaults to application context and not location context which it should have according to documentation.

I could supply a PR if this is an actual bug.

The latest known version to work is alt-mod-passenger-5.1.12-1.el7.cloudlinux.x86_64. Master version is also affected.

Maybe related to #2021

**Comment by CamJN** [comment]
This is a bug in our documentation. This was changed in Passenger 5.2: https://blog.phusion.nl/2018/01/29/passenger-5-2-0/

**Comment by isodude** [comment]
It should be possible to set the setting per VirtualHost right? Even though the listen on the same IP?

**Comment by CamJN** [comment]
Yes you could us the same ip in both virtualhosts, but then you need to differentiate some other way, such as hostname.

**Comment by isodude** [comment]
Thanks that will work out I think.
