### ISSUE TITLE
Unable to Install Passenger module for Apache2

### ISSUE THREAD

**Issue by rsbabu** [phusion/passenger#2166]
Steps : 

1. I was following the tutorial mentioned in : https://www.vultr.com/docs/how-to-install-redmine-on-ubuntu-16-04

2. I could smoothly install upto :  
a. Create Redmine user, DB, postgres dependencies 
b. sudo apt -y install libpqx-dev protobuf-compiler

3. Install Ruby : 
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt update

4. sudo apt -y install rvm
 echo "source /etc/profile.d/rvm.sh" | tee -a /etc/profile
source /etc/profile.d/rvm.sh

5. rvm install 2.6.0

rvm use 2.6.0 --default

ruby -v is ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

7. gem install bundler is successful.

8. gem install passenger is successful.

9. While trying to install passenger-install-apache2-module, I get series of errors as attached in the file.

Can you please help how to install 

[PassengerError.txt](https://github.com/phusion/passenger/files/2783399/PassengerError.txt)

**Comment by CamJN** [comment]
Note: `virtual memory exhausted: Cannot allocate memory.` You ran out of address space while compiling. Since I see evidence of a 64 bit system, can you tell me if you are using docker or any other tech that would limit the memory available to the compiler?

**Comment by rsbabu** [comment]
Hi, 

I am using a VPS from ISP.  Also, can you please see the compiler errors in WatchdogMain.o..

Below are the memory stats :  

              total        used        free      shared  buff/cache   available
Mem:           1993         868         747          21         376         962
Swap:             0           0           0
Total:         1993         868         747

**Comment by rsbabu** [comment]
Dear CamJN,

Thank you for the advise.  I have added Swap as follows and got the closure output as given below.  Attached are the Errors & Warnings. Especially warning: mangled name for ***  at many places.  

Is this normal or Am I missing something.  TIA
[updatedPassenger.txt](https://github.com/phusion/passenger/files/2783804/updatedPassenger.txt)
 for the help please.


              total        used        free      shared  buff/cache   available
Mem:           1993         545        1035          14         413        1292
Swap:          2047         380        1667
Total:         4041         925        2703

I could get this message after running the passenger command : 

/usr/share/rvm/gems/ruby-2.6.0/wrappers/ruby /usr/share/rvm/gems/ruby-2.6.0/gems/passenger-6.0.1/bin/passenger-install-apache2-module --apxs2-path='/usr/bin/apxs'

--------------------------------------------
Almost there!

Please edit your Apache configuration file, and add these lines:

   LoadModule passenger_module /usr/share/rvm/gems/ruby-2.6.0/gems/passenger-6.0.1/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /usr/share/rvm/gems/ruby-2.6.0/gems/passenger-6.0.1
     PassengerDefaultRuby /usr/share/rvm/gems/ruby-2.6.0/wrappers/ruby
   </IfModule>

After you restart Apache, you are ready to deploy any number of web
applications on Apache, with a minimum amount of configuration!

Press ENTER when you are done editing.

**Comment by CamJN** [comment]
The `mangled name for *** ` warnings are normal, that's a change that is upcoming in c++17 which the compiler is warning us we will need to be aware of in the future.

That message means your build succeeded, and you just need to edit your apache config to load the passenger module.
