### ISSUE TITLE
Unable to use apt repository from Bionic

### ISSUE THREAD

**Issue by vcsjones** [phusion/passenger#2167]
Running a `apt-get clean && apt-get update` from the `phusion/passenger-customizable` docker image as part of our Dockerfile, we get the following output:

<pre>
Err:6 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release
  503  Service Unavailable [IP: 109.107.35.58 443]
Reading package lists... Done
E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' does not have a Release file.
</pre>

We can work around this in our docker images by removing the passenger apt repository, but this is obviously a temporary workaround.

**Comment by CamJN** [comment]
We're aware of the issue and are working on it.

**Comment by CamJN** [comment]
See https://github.com/phusion/passenger-docker/issues/240 as well.

**Comment by postables** [comment]
Also getting this issue

**Comment by CamJN** [comment]
Ok I think we got this under control, can you check on your end too @postables and @vcsjones?

**Comment by vcsjones** [comment]
Seems OK for us for now. Thanks!
