### ISSUE TITLE
OSX Conflicting Permissions Requirements

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2178]
## Issue report
**Question 1: What is the problem?**
Created a new site on my workstation and ran into multiple warnings from Passenger indicating my __/usr/local/__ directory was not secure.  So I chowned it as __root/admin__.  Now I can't get to my nginx logs and other items, and __Passenger__ still won't work, throwing an error 403.  

It seems Passenger doesn't like my loose workstation permissions, but I'm the dev on my workstation and I need access for other applications to read my logs, maintain files, etc., inside __/usr/local/__.  

It is working for other sites I have, however I still can't see the logs nor this new site.  I expect the new site to work just fine.  I get the error on an __nginx__ restart.  

Not replicable on your end, from what I can gather.  Here is the original error that took me down this path:

     - /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini is not secure: it can be modified by user rich
     - /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger is not secure: it can be modified by user rich
     - /usr/local/opt/passenger/libexec/src/ruby_supportlib is not secure: it can be modified by user rich
     - /usr/local/opt/passenger/libexec/src is not secure: it can be modified by user rich
     - /usr/local/opt/passenger/libexec is not secure: it can be modified by user rich
     - /usr/local/opt/passenger is not secure: it can be modified by user rich
     - /usr/local/opt is not secure: it can be modified by user rich
     - /usr/local is not secure: it can be modified by user rich

    Please either fix up the permissions for the insecure paths, or install Passenger in a different location that can only be modified by root.
    [ N 2019-02-04 14:31:42.5716 86401/T1 age/Cor/CoreMain.cpp:1014 ]: Passenger core online, PID 86401
    2019/02/04 14:31:41 [notice] 62#0: start worker processes
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86403
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86404
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86405
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86406
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86407
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86408
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86409
    2019/02/04 14:31:41 [notice] 62#0: start worker process 86410
    [ N 2019-02-04 14:31:42.7325 86314/T1 age/Cor/CoreMain.cpp:1324 ]: Passenger core shutdown finished
    2019/02/04 14:31:42 [notice] 86316#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 86320#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 86317#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 86318#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 62#0: signal 23 (SIGIO) received
    2019/02/04 14:31:42 [notice] 86319#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 62#0: signal 23 (SIGIO) received
    2019/02/04 14:31:42 [notice] 86316#0: exiting
    2019/02/04 14:31:42 [notice] 62#0: signal 20 (SIGCHLD) received from 86312
    2019/02/04 14:31:42 [notice] 86322#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 62#0: signal 23 (SIGIO) received from 86321
    2019/02/04 14:31:42 [notice] 86319#0: exiting
    2019/02/04 14:31:42 [notice] 86320#0: exiting
    2019/02/04 14:31:42 [notice] 86322#0: exiting
    2019/02/04 14:31:42 [notice] 86318#0: exiting
    2019/02/04 14:31:42 [notice] 86321#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 86317#0: exiting
    2019/02/04 14:31:42 [notice] 86321#0: exiting
    2019/02/04 14:31:42 [notice] 86323#0: gracefully shutting down
    2019/02/04 14:31:42 [notice] 86323#0: exiting
    2019/02/04 14:31:42 [notice] 86316#0: exit
    2019/02/04 14:31:42 [notice] 86319#0: exit
    2019/02/04 14:31:42 [notice] 86317#0: exit
    2019/02/04 14:31:42 [notice] 86322#0: exit
    2019/02/04 14:31:42 [notice] 86320#0: exit
    2019/02/04 14:31:42 [notice] 86321#0: exit
    2019/02/04 14:31:42 [notice] 86323#0: exit
    2019/02/04 14:31:42 [notice] 86318#0: exit
    2019/02/04 14:31:42 [notice] 62#0: signal 20 (SIGCHLD) received from 86320
    2019/02/04 14:31:42 [notice] 62#0: worker process 86322 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: worker process 86320 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: worker process 86319 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: worker process 86317 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: worker process 86316 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: signal 23 (SIGIO) received
    2019/02/04 14:31:42 [notice] 62#0: signal 23 (SIGIO) received
    2019/02/04 14:31:42 [notice] 62#0: signal 20 (SIGCHLD) received from 86318
    2019/02/04 14:31:42 [notice] 62#0: worker process 86323 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: worker process 86321 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: worker process 86318 exited with code 0
    2019/02/04 14:31:42 [notice] 62#0: signal 23 (SIGIO) received
    2019/02/04 14:31:42 [notice] 62#0: signal 23 (SIGIO) received
    [ E 2019-02-04 14:31:44.6025 86401/T5 Sec/Crypto.cpp:990 ]: Loading Passenger Cert failed: The specified keychain could not be found.
    Please check for a certificate labeled: Phusion Passenger Open Source in your keychain, and remove the associated private key. For more help please read: https://www.phusionpassenger.com/library/admin/standalone/mac_keychain_popups.html
    [ E 2019-02-04 14:31:44.6026 86401/T5 Sec/Crypto.cpp:990 ]: Pre authorizing the Passenger client certificate failed: The specified keychain could not be found.
    [ E 2019-02-04 14:31:44.6027 86401/T5 age/Cor/SecurityUpdateChecker.h:507 ]: Security update check failed: Problem with the local SSL certificate at /usr/local/Cellar/passenger/6.0.1/libexec/resources/update_check_client_cert.p12 (try upgrading or reinstalling Passenger) (next check in 24 hours)
    [ E 2019-02-04 14:31:44.6146 86401/T5 Sec/Crypto.cpp:990 ]: Finding Passenger Cert failed: The specified item could not be found in the keychain.

**Question 2: Passenger version and integration mode**:

Open Source Passenger 6.0.1
nginx/1.15.8
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin15]

**Question 3: OS or Linux distro, platform (including version)**:

OSX 10.11.6 El Capitan

**Question 4: Passenger installation method**:

[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[X] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin15]
Sinatra 2.0.5

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

None

**Question 7: Anything else about your setup that we should know?**

Not that I know of.

**Comment by CamJN** [comment]
The warning we print about loose permissions is intended for production environments, you can ignore it in development.
