### ISSUE TITLE
passenger-config restart-app fails during /tmp cleanup as unprivileged user

### ISSUE THREAD

**Issue by SeanSith** [phusion/passenger#2182]
## Issue report

When executing a `passenger-config restart-app [appdir] --ignore-app-not-running` under Passenger 6.0.1, the restart fails with 

```*** Cleaning stale instance directory /tmp/passenger.hSq6lXh
/usr/local/ruby/2.6.1/lib/ruby/2.6.0/fileutils.rb:698:in `rescue in remove_entry_secure': uninitialized constant FileUtils::EISDIR (NameError)
	from /usr/local/ruby/2.6.1/lib/ruby/2.6.0/fileutils.rb:688:in `remove_entry_secure'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:112:in `cleanup'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:52:in `block (2 levels) in list'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:45:in `each'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:45:in `block in list'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:44:in `each'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:44:in `list'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/config/utils.rb:63:in `select_passenger_instance'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/config/restart_app_command.rb:45:in `run'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/config/main.rb:79:in `run!'
	from /usr/bin/passenger-config:37:in `<main>'
/usr/local/ruby/2.6.1/lib/ruby/2.6.0/fileutils.rb:695:in `chown': Operation not permitted @ rb_file_chown - /tmp/passenger.hSq6lXh/. (Errno::EPERM)
	from /usr/local/ruby/2.6.1/lib/ruby/2.6.0/fileutils.rb:695:in `block in remove_entry_secure'
	from /usr/local/ruby/2.6.1/lib/ruby/2.6.0/fileutils.rb:689:in `open'
	from /usr/local/ruby/2.6.1/lib/ruby/2.6.0/fileutils.rb:689:in `remove_entry_secure'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:112:in `cleanup'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:52:in `block (2 levels) in list'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:45:in `each'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:45:in `block in list'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:44:in `each'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:44:in `list'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/config/utils.rb:63:in `select_passenger_instance'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/config/restart_app_command.rb:45:in `run'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/config/main.rb:79:in `run!'
	from /usr/bin/passenger-config:37:in `<main>'
```

Executing the same command with `sudo` prepended allows the restart to occur correctly.

While we primarily do this through capistrano-passenger, running the commands by hand as the unprivileged user results in the same error messages.

**Are you sure this is a bug in Passenger?**
Pretty certain. We're running 5.3.x in other environments and have never had to configure the deploy process to use `sudo` or a privileged user in order to issue a restart.

**Please try with the newest version of Passenger to avoid issues that have already been fixed**
This is a newly built system using the Phusion apt packages of Passenger 6.0.1.

**Question 1: What is the problem?**
- What is the expected behavior?
The application restarts properly
- What is the actual behavior?
See description and log above.
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.
Amazon EC2 using Ubuntu 18.04 image in us-east-2
Installed Ruby 2.6.1 using ruby_build through the Chef ruby_build cookbook.
Installed latest Passenger (6.0.1) using the Chef 'nginx' cookbook with the following relevant settings:
```
default['nginx']['repo_source'] = 'passenger'
default['nginx']['package_name'] = 'nginx-extras'
default['nginx']['passenger']['install_method'] = 'package'
default['nginx']['passenger']['root'] = '/usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini'
```
According to the cookbook, this should result in the installation of the latest Passenger and Nginx with some add-on modules using the apt package manager.

Your answer:

**Question 2: Passenger version and integration mode**:
- open source 6.0.1/nginx

**Question 3: OS or Linux distro, platform (including version)**:
- Amazon EC2 x86_64, Ubuntu 18.04

**Question 4: Passenger installation method**:

Your answer:
[x] Phusion APT repo
As noted above, we utilized the Nginx Chef cookbook to accomplish the install, which uses the Phusion APT repo for the package installation.

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- Ruby 2.6.1, Rails 5.2.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- Amazon EC2

**Question 7: Anything else about your setup that we should know?**
Nginx, Passenger core, and Passenger watchdog all run as `root` as expected. The Passenger AppPreloader runs as the unprivileged user `deploy`.

**Comment by CamJN** [comment]
Looks like this: https://bugs.ruby-lang.org/issues/15577

**Comment by SeanSith** [comment]
This is confirmed as fixed in Ruby 2.6.2.

**Comment by crimson-knight** [comment]
I've just recently started reviewing this error.

*** Cleaning stale instance directory /tmp/passenger.Leg1cQc
      01     Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.Leg1cQc/.

I get a series of these when I deploy with Capistrano. It still deploys, but the list of permissions errors grow all of the time. I can log into my server and run `sudo passenger-config restart-app /home/app/app_name --ignore-app-not-running` and it will restart and clean up successfully.

I'm using Ruby 2.6.3, upgraded from 2.6.2 after the errors started appearing. I'm also using Rails 6rc1, and Passenger 6.0.2

**Comment by CamJN** [comment]
@crimson-knight that's a different problem, please open a separate issue and fill in the complete report.

**Comment by hopewise** [comment]
@crimson-knight did you solve your issue? I have the same as yours..

**Comment by jwhitmarsh** [comment]
@hopewise & @crimson-knight did you solve this? I have the same issue.

**Comment by crimson-knight** [comment]
@jwhitmarsh & @hopewise pretty sure I just added `set :use_sudo, true` in my deploy.rb file.

I'll see if I can duplicate the issue and confirm. Just make sure your deploy user is actually in the sudoers group. Pretty sure the issue is because Nginx/Passenger is run as root (assuming you haven't customized this) and the tmp files are created using root privileges.

**Comment by richhollis** [comment]
Just in case it helps anyone else that is using a deployment user for their deployment:

I just needed to add a rule to sudoers (visudo to edit the file) for the deployment user:

`/usr/bin/env passenger-config restart-app YOUR_WEBAPP_PATH_GOES_HERE --ignore-app-not-running`

Note: You can find the above line when you run your capistrano deployment, as it is echoed out to the console

I did not need to use set :passenger_restart_with_sudo, true - just adding the exception to sudoers was sufficient. The error is now gone and the deploy works as expected.
