### ISSUE TITLE
brew install nginx --with-passenger => Error: invalid option: --with-passenger

### ISSUE THREAD

**Issue by ssk** [phusion/passenger#2187]
The installation document is out of date.

I just installed homebrew (2.0.2) on my mac. 

$ brew install nginx --with-passenger
Error: invalid option: --with-passenger

Please update the installation guid.

**Comment by CamJN** [comment]
I'm working on updating the docs, in the meantime you can just use `brew install nginx passenger`.

**Comment by CamJN** [comment]
docs are updated

**Comment by mkastner** [comment]
Not here (at time of this writing):

https://www.phusionpassenger.com/library/install/nginx/upgrade/oss/

**Comment by CamJN** [comment]
The maintained version of our docs is at the /docs/ subURI: https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/apache/upgrade.html

**Comment by mkastner** [comment]
I apologize, I wasn't aware of that. I got fooled by google and landed the old version.

**Comment by amirmujkic** [comment]
@CamJN Thanks for the update!
