### ISSUE TITLE
ngx_http_passenger_module.so Version is Wrong

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2194]
## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Are you sure this is a bug in Passenger?**
It seems as if there's a Passenger module version error, so yes.  

**Please try with the newest version of Passenger to avoid issues that have already been fixed**
I think that's what brought this on.  

**Question 1: What is the problem?**
- What is the expected behavior?
It should work.  

- What is the actual behavior?
nginx won't start due to this issue.  Log entry:

nginx: [emerg] module `"/usr/local/opt/passenger/libexec/modules/ngx_http_passenger_module.so" version 1015009 instead of 1015010 in /usr/local/etc/nginx/nginx.conf:5`

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.
I don't know if you can reproduce this.

**Question 2: Passenger version and integration mode**:
- Latest Passenger open source, 6.0.2 on El Capitan Mac OS X
- nginx integration mode

**Question 3: OS or Linux distro, platform (including version)**:
- El Capitan 10.11.6

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[X ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- rvenv Ruby 2.5.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- nope

**Question 7: Anything else about your setup that we should know?**
Was working before updating homebrew, gems.

**Comment by CamJN** [comment]
https://github.com/Homebrew/homebrew-core/issues/38391
https://github.com/Homebrew/homebrew-core/pull/38435
