### ISSUE TITLE
Ruby 2.6 support for Passenger 5.3.4

### ISSUE THREAD

**Issue by StephenEsser** [phusion/passenger#2195]
## Feature Request

Requesting native extension support for Ruby 2.6.1 and Ruby 2.6.2 be added for passenger 5.3.4.

https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.4/

Our applications are currently uplifting to Ruby 2.6 and when attempting to build native support for passenger it fails because these extensions do not exist for this version of passenger. 

The following command fails. 

`passenger-config build-native-support`

```
 [passenger_native_support.so] trying to compile for the current user (root) and Ruby interpreter...

     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)

     Warning: compilation didn't succeed. To learn why, read this file:

     /tmp/passenger_native_support-aelt40.log

 [passenger_native_support.so] finding downloads for the current Ruby interpreter...

     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)

     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.4/rubyext-ruby-2.6.1-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
```

Is it possible to install these extensions a separate way? Or is upgrading to Passenger 6 the only way to build using Ruby 2.6?

**Comment by CamJN** [comment]
can you include the contents of passenger_native_support-aelt40.log?

**Comment by StephenEsser** [comment]
Hi @CamJN, sure thing. Thanks for the quick reply.

```
# current user is: root
# mkdir -p /opt/passenger/buildout/ruby/ruby-2.6.1-x86_64-linux
# cd /opt/passenger/buildout/ruby/ruby-2.6.1-x86_64-linux
# /usr/local/bin/ruby /opt/passenger/src/ruby_native_extension/extconf.rb
/usr/local/bin/ruby: No such file or directory -- /opt/passenger/src/ruby_native_extension/extconf.rb (LoadError)
```

**Comment by CamJN** [comment]
You are correct that we haven't built native extensions for the combination of Passenger 5.3.4 and Ruby 2.6. However Passenger will fall back to building the extensions locally if they aren't available for download (and if that fails it won't stop Passenger from working, it just causes log spam). How did you install Passenger, and what distro are you running? It's weird that `src/ruby_native_extension/extconf.rb` is missing, we include that in our releases.

**Comment by StephenEsser** [comment]
It looks like we removed a few of the files to trim down the base image. 

I've added back the ruby_native_extensions extconf and it appears to be working. 

Do you see any issues with allowing passenger to fall back to building the extensions locally if they are not available from [here](https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.4/)?

In this case we will be building and shipping passenger 5.3.4 with Ruby 2.6.1 even though it's not a built extension from the passenger registry.

**Comment by CamJN** [comment]
There's no problem with building the extensions yourself. We only ship them for use with platforms where you cannot compile things, like Heroku.

**Comment by StephenEsser** [comment]
Thanks for looking into this, @CamJN.
