### ISSUE TITLE
Ubuntu 19.04 support

### ISSUE THREAD

**Issue by cajuncooks** [phusion/passenger#2197]
## Issue report

**Question 1: What is the problem?**
Cloned from the repository to run `passenger-install-nginx-module` on Ubuntu 19.04 (because the disco repository isn't available yet and I upgraded prematurely like a dope), and encountered a one-character fix needed for compilation with cc 8.3.0:

```
$ git diff .
diff --git a/src/nginx_module/ContentHandler.c b/src/nginx_module/ContentHandler.c
index 7a9b1c5a4..f2bcd7127 100644
--- a/src/nginx_module/ContentHandler.c
+++ b/src/nginx_module/ContentHandler.c
@@ -999,7 +999,7 @@ construct_request_buffer(ngx_http_request_t *r, passenger_loc_conf_t *slcf,
      */
 
     PUSH_STATIC_STR("!~FLAGS: CD");
-    if (slcf->autogenerated->buffer_upload) {
+    if (slcf->autogenerated.buffer_upload) {
         PUSH_STATIC_STR("B");
     }
     #if (NGX_HTTP_SSL)
```

**Question 2: Passenger version and integration mode**:
open source ed2f164a5e6a476a932a5178e69f88b25b775269

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 19.04 Server

**Question 4: Passenger installation method**:
source tarball

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
rbenv, Ruby 2.4.5

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
no

**Question 7: Anything else about your setup that we should know?**
Everything else worked great! I assume this is due to 19.04 shipping with a new version of cc or something. Happy to open a PR if you want, or not.

**Comment by CamJN** [comment]
Nah it's due to a new feature in passenger+nginx that hasn't been released yet, and which had a legit typo. Well spotted, and the fix [has been committed](https://github.com/phusion/passenger/commit/970964b53e0ba86959acdf40f06c99b0c4a128ca).
