### ISSUE TITLE
Passenger nginx module always run as root and subprocess run as normal user, but new created log file attribute is root:root

### ISSUE THREAD

**Issue by zw963** [phusion/passenger#2202]
Please see following two screenshot.

Passenger core

![image](https://user-images.githubusercontent.com/549126/57370414-b2de0680-71c2-11e9-9b92-1ee43363efa0.png)

Passenger subprocess
![image](https://user-images.githubusercontent.com/549126/57370502-e3be3b80-71c2-11e9-81a3-d505eb7bbe01.png)

I get following error:

```sh
fatal: Not a git repository (or any of the parent directories): .git
Error: The application encountered the following error: Permission denied @ rb_sysopen - log/httparty.log (Errno::EACCES)
    /usr/local/lib/ruby/2.6.0/logger.rb:744:in `initialize'
    /usr/local/lib/ruby/2.6.0/logger.rb:744:in `open'
    /usr/local/lib/ruby/2.6.0/logger.rb:744:in `open_logfile'
    /usr/local/lib/ruby/2.6.0/logger.rb:736:in `set_dev'
    /usr/local/lib/ruby/2.6.0/logger.rb:671:in `initialize'
    /usr/local/lib/ruby/2.6.0/logger.rb:387:in `new'
```

Yes, this new created log/httparty.log is created by root user.

```sh
# ls -alh
total 16K
drwxr-xr-x 2 container_user container_user 4.0K May  8 20:15 .
drwxrwxrwx 1 container_user container_user 4.0K May  8 19:32 ..
-rw-r--r-- 1 root           root             66 May  8 20:15 httparty.log
```

I thought it created by passenger core, so i have two question:

1.  Passenger core should run by root, right?  so , i expect httparty.log should create
by subprocess, but it not.

2.  if passenger core should not run by root, How to run passenger core with normal user?

I use Ubuntu 18.04,  libnginx-mod-http-passenger.

Thanks

**Comment by CamJN** [comment]
Can you share your nginx/passenger config? And the precise way you specified the log file to your app? Thanks.

**Comment by zw963** [comment]
> Can you share your nginx/passenger config?

### /etc/nginx/sites-enabled/web.conf
```
# Those file should add config to nginx http context

server {
    listen 80;
    listen [::]:80;

    server_name *.Airhost.Co;
    root /app/public;

    passenger_enabled on;
    passenger_app_env production;
    passenger_friendly_error_pages on;
    passenger_ruby /usr/local/bin/ruby;
    passenger_user container_user;
    passenger_group container_user;
    # passenger_default_user container_user;
    # passenger_default_group container_user;

    location /cable {
        passenger_app_group_name myapp_websocket;
        passenger_force_max_concurrent_requests_per_process 0;
    }

    # Allow uploads up to 100MB in size
    client_max_body_size 100m;

    location ~ ^/(assets|packs) {
        expires max;
        gzip_static on;
    }
}
```

> And the precise way you specified the log file to your app? 

This maybe a little special, the log is come from a gem in Gemfile, not from web app.

```rb
path './lib/components/ota' do
  gem 'airhost_ota'
end
```
Above gem use httparty.

```rb
module OTA::Adapters
  class HttpPartyWithLog
    include HTTParty
    logger ::Logger.new("log/httparty.log"), :debug, :curl
  end
end
```

Thank you.

**Comment by CamJN** [comment]
Your config looks reasonable, if you delete the log is it recreated with a root owner?

**Comment by zw963** [comment]
Sorry for confusing, This issue resolved now.

Yes, it is my fault, "log/httparty.log" is created when run "rake assets:precompile, and i run that step with root user.

Thank you for help.
