### ISSUE TITLE
OS level environment variable could not be load by passenger.

### ISSUE THREAD

**Issue by zw963** [phusion/passenger#2203]
I use Debian GNU/Linux 9 + nginx + passenger module (nginx/1.10.3 Phusion_Passenger/6.0.2) which used as docker container, run a rails 5.2 app.

The current issue is:

Passenger no way to load OS-level environment variable(at least, i don't know how to do it)

e.g. when i start nginx, i got following ENV.

![image](https://user-images.githubusercontent.com/549126/57525751-25371e00-735e-11e9-8a10-44dbe5a1dffd.png)

But,  this OS have a OS-level environment variable ($BUNDLE_PATH) not in above env list.
this issue cause current bundler not working. (app need bundler ~> 2.0.0, but system is 1.17.2)

The only way i know to resolve this is follow passenger document, create a nginx config, like this:

```
env BUNDLE_PATH=/usr/local/bundle
...
env ...
```

But, this way pollutaed the nginx env scope, that not good.

So, i guess there maybe exist a more robust way to load ENV only when passenger load rails app.

Thanks.

**Comment by CamJN** [comment]
There are several options available to you:

- Nginx's env vars as you mentioned
- The [passenger_env_var](https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_env_var) config option, which sets an env var just for Passenger apps
- Or the [passenger_load_shell_envvars](https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_load_shell_envvars) mechanism (on by default), where env vars set in your `.bashrc` file are passed to your app. (You can set [passenger_log_level ](https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_log_level) to 7 to see how your `.bashrc` file is interpreted in Passenger (it will be printed to the log file as it is executed), one common gotcha is that Passenger loads bash non-interactively so an interactivity check in your `.bashrc` may stop evaluation of later commands)

**Comment by zw963** [comment]
Thank you.

But, i see a Ubuntu host, in .bashrc, we can see first line is:

```sh
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

.....
```

I guess all code blow that not be executed.

But, the env defined in `/etc/profile.d/environ.sh` (with execute attribute set)
is get loaded into passenger, maybe there have a more options?

**Comment by CamJN** [comment]
You can set the env var above the interactivity check, or in any other location that is run by bash. Deciding where you want to put it is up to your discretion.

**Comment by zw963** [comment]
> or in any other location that is run by bash

So, AFAIU, passenger never search ~/.bashrc or ~/.zshrc
or,  files in `etc/profile.d/*.sh` with execute attribute.

instead, all those env is determinate by a bash non-login shell, right?

For research, i check in Ubuntu (env is loaded) and Debian9(container, env is not load)

I found, Ubuntu $0 is "-bash",  Debian9 in container $0 is "/bin/sh", and it link to `dash`,
So, i guess because this, passenger not load any env in debian9, right?

Thank.

**Comment by CamJN** [comment]
Correct, we don't search  `~/.bashrc` or `~/.zshrc`, etc. We rely on the shell to load itself correctly. Whether the env is inherited from the shell or not is determined by the [passenger_load_shell_envvars](https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_load_shell_envvars) config option, and relies on a sh-like shell, you can see the logic for choosing the shell [here](https://github.com/phusion/passenger/blob/stable-6.0/src/agent/SpawnEnvSetupper/SpawnEnvSetupperMain.cpp#L727-L748).

**Comment by zw963** [comment]
I see now, Thank you very much.

> the passenger_load_shell_envvars config option,

An extra question(no bug), is there exist a way(command line tools or error log)
 to see all take effected passenger nginx's module option?

 i know i can get those value default from [document](https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_load_shell_envvars), but, if there exist a way can fetch
those, that will appreicated.

**Comment by zw963** [comment]
I see the real reason which cause this.

```sh
service nginx start
exec tail -f /var/log/nginx/*.log
```

I use `service nginx start` to start nginx, this load way make
environment is not available for passenger.

after change to following code, it worked.

```sh
nginx
exec tail -f /var/log/nginx/*.log
```
I will close this, and add above questiion in a new issue.


Thank you very much.
