### ISSUE TITLE
Generic interface for restarting process/supervisor IPC.

### ISSUE THREAD

**Issue by ioquatix** [phusion/passenger#2208]
If this isn't something you are interested in, please feel free to close this issue.

I've been thinking about how application deployment works with different application servers, e.g. Passenger, Puma, Falcon, Nginx, etc.

I've been wondering if it makes sense to have some kind of cross-server IPC mechanism for restarting applications (and perhaps other functionality).

Right now, I've been implementing a unix pipe under the application root (e.g. `/srv/http/myapp/supervisor.ipc`). This pipe could receive JSON formatted requests to restart the application server. Ideally it can do more (e.g. statistics on running processes/applications/requests processed), but the very basic requirement was this.

Ideally, we could have a shared specification (and perhaps implementation), so it works for all supported application servers. In this case, Puma, Falcon and Passenger. That would make it easier for app deployment to restart the server on deployment without having to figure out or be configured what server and what specific command to use.

The only shared interface that sort of exists is `touch tmp/restart.txt` but that's such a crappy interface I'd really rather avoid it.

**Comment by ioquatix** [comment]
Here is a rough idea - we could make a shared gem called, e.g. `supervisor`, and then have that interface using, say, msgpack, to `supervisor.ipc`, which has a fairly straight forward and "standardised" interface with a bunch of useful commands - restart (can implement rolling restart depending on server), statistics, and personally, I'd really like to see some kind of dashboard.

**Comment by ioquatix** [comment]
For the dashboard, some standardised things I'd like to present include:

- histogram of IP address.
- histogram of latency.
- cpu and memory usage history (real time ascii graph), etc.

**Comment by CamJN** [comment]
Is this going anywhere? Can you link to other issues you've opened?

**Comment by ioquatix** [comment]
I can write a spec for this functionality before the end of this year if I don’t please ping the issue I am making progress on my end, but busy at the moment..

**Comment by ioquatix** [comment]
Okay, so I've come to the conclusion that per-gem tasks make a lot of sense.

I've implemented this in falcon, e.g.

https://github.com/socketry/falcon/commit/0612bf31848ebc1a9b96c99fa892184a6b697422

For more information about using `bake`, see https://github.com/ioquatix/bake

I'll add support for aliases to `bake` so it should be super easy to link these things together as required.
