### ISSUE TITLE
Phusion Passenger Rails Apache forking and doesn't seem to be running

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [phusion/passenger#2209]
## Issue report

I just deploy a rails application to my server with phusion, we configured all the essentials but even when the app appear to be running when we try to restart for some changes it shows:

    *** ERROR: Phusion Passenger doesn't seem to be running. If you are sure that it
    is running, then the causes of this problem could be one of:
    
     1. You customized the instance registry directory using Apache's
        PassengerInstanceRegistryDir option, Nginx's
        passenger_instance_registry_dir option, or Phusion Passenger Standalone's
        --instance-registry-dir command line argument. If so, please set the
        environment variable PASSENGER_INSTANCE_REGISTRY_DIR to that directory
        and run this command again.
     2. The instance directory has been removed by an operating system background
        service. Please set a different instance registry directory using Apache's
        PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir
        option, or Phusion Passenger Standalone's --instance-registry-dir command
        line argument. 

Our apache configuration looks like:

    <VirtualHost *:80>
        ServerName ourdomain
        DocumentRoot  /var/www/siege/public
    
        PassengerRuby /usr/local/rvm/gems/ruby-2.5.1/wrappers/ruby
        <Directory  /var/www/siege/public>
          Allow from all
          Options -MultiViews
          # Uncomment this if you're on Apache >= 2.4:
          Require all granted
        </Directory>
    	RewriteEngine On
    	RewriteCond %{HTTP:X-Forwarded-Proto} =http
    	RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
    <IfModule mod_passenger.c>
        PassengerMaxPoolSize 12
        PassengerMinInstances 0
        PassengerMinInstances 3
    </IfModule>
    </VirtualHost>

And actually the app is running, when we run `passenger-memory-stats` it shows always forking the same path:

    Version: 6.0.2
    Date   : 2019-06-18 21:44:29 +0000
    
    --------- Apache processes ---------
    PID   PPID  VMSize    Private  Name
    ------------------------------------
    1028  1     170.2 MB  0.6 MB   /usr/sbin/apache2 -k start
    1097  1028  836.9 MB  1.8 MB   /usr/sbin/apache2 -k start
    1098  1028  837.0 MB  2.0 MB   /usr/sbin/apache2 -k start
    ### Processes: 3
    ### Total private dirty RSS: 4.48 MB
    
    
    -------- Nginx processes --------
    
    ### Processes: 0
    ### Total private dirty RSS: 0.00 MB
    
    
    ---- Passenger processes -----
    PID   VMSize    Private  Name
    ------------------------------
    1033  389.9 MB  2.5 MB   Passenger watchdog
    1068  675.4 MB  4.0 MB   Passenger core
    2342  558.3 MB  67.4 MB  Passenger AppPreloader: /var/www/siege (forking...)
    2362  491.3 MB  21.9 MB  Passenger AppPreloader: /var/www/siege (forking...)
    2381  557.3 MB  22.0 MB  Passenger AppPreloader: /var/www/siege (forking...)
    ### Processes: 5
    ### Total private dirty RSS: 117.82 MB

**Are you sure this is a bug in Passenger?**
I really don't know

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
- What is the expected behavior?
  - Be enabled for restart the application
- What is the actual behavior?
 - It stuck on "forking"

Passenger version and integration mode:
open source standalone/ apache

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 18.04.2 LTS

**Question 4: Passenger installation method**:
RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.5.1, RVM, Rails 5.2.3; Node.js v12.4.0

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No, just EC2 AWS

**Comment by CamJN** [comment]
We don't rename the process to remove the `(forking...)` label anymore, it's on the list of things to do but is fairly low priority. If the processes aren't able to serve anything, then look at the passenger log (by default in the apache error log) and your application logs. 

If the processes are able to serve requests, then read more about helping `passenger-status` find the instance dir here: https://www.phusionpassenger.com/docs/references/config_reference/apache/#passengerinstanceregistrydir nb. if systemd is launching apache, it may assign a unique tmpdir for it, and you may need to specify the instancedir to use in your apache/passenger config.

**Comment by ulisescarreonalvarez** [comment]
Hi @CamJN, the project is actually serving i can access normaly on the web with apache.

The problem is that i can't restart the application, when i run "passenger-config restart-app" it shows:

*** ERROR: Phusion Passenger doesn't seem to be running. If you are sure that it
is running, then the causes of this problem could be one of:
```

 1. You customized the instance registry directory using Apache's
    PassengerInstanceRegistryDir option, Nginx's
    passenger_instance_registry_dir option, or Phusion Passenger Standalone's
    --instance-registry-dir command line argument. If so, please set the
    environment variable PASSENGER_INSTANCE_REGISTRY_DIR to that directory
    and run this command again.
 2. The instance directory has been removed by an operating system background
    service. Please set a different instance registry directory using Apache's
    PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir
    option, or Phusion Passenger Standalone's --instance-registry-dir command
    line argument.
```

If i run 'passenger-status' it shows the same.

When i run 'passenger-memory-stats' it shows:

```
Version: 6.0.2
Date   : 2019-06-19 15:17:47 +0000

--------- Apache processes ---------
PID   PPID  VMSize    Private  Name
------------------------------------
8354  1     170.2 MB  0.6 MB   /usr/sbin/apache2 -k start
8373  8354  837.1 MB  2.2 MB   /usr/sbin/apache2 -k start
8374  8354  837.3 MB  2.2 MB   /usr/sbin/apache2 -k start
### Processes: 3
### Total private dirty RSS: 5.02 MB


-------- Nginx processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


---- Passenger processes -----
PID   VMSize    Private  Name
------------------------------
8357  389.9 MB  2.5 MB   Passenger watchdog
8361  674.9 MB  4.0 MB   Passenger core
8442  493.3 MB  54.0 MB  Passenger AppPreloader: /var/www/merci-siege
8502  560.4 MB  57.9 MB  Passenger AppPreloader: /var/www/merci-siege (forking...)
### Processes: 4
### Total private dirty RSS: 118.40 MB
```

Even when it appers that apache is serving correctly the application i'm unable to restart the aplication.

On the validation always show "Everything looks good. :-)"

Any advice for the application restart without restarting apache everytime.

**Comment by CamJN** [comment]
Ah sorry, i've been seeing so many people with `passenger-status` issues recently my brain slipped into that mode. How are you restarting the app? Via capistrano, manually, something else, and as which user? And when you run `passenger-status` which works, what user are you doing so as?

**Comment by ulisescarreonalvarez** [comment]
@CamJN @orkuva  it appear that in Ubuntu 18.04 and apache the export of the configuration "export PASSENGER_INSTANCE_REGISTRY_DIR=/var/run/passenger-instreg/" doesn't work, even adding on the rails application on the enviorment.

For solving the problem i added the configuration on the virtual host like:

```
<VirtualHost *:80>
    ServerName siege.merci.network
    DocumentRoot  /var/www/siege/public

    PassengerRuby /usr/local/rvm/gems/ruby-2.5.1/wrappers/ruby
    PassengerInstanceRegistryDir /run/passenger-instreg/
    <Directory  /var/www/siege/public>
      Allow from all
      Options -MultiViews
      # Uncomment this if you're on Apache >= 2.4:
      Require all granted
    </Directory>
	RewriteEngine On
	RewriteCond %{HTTP:X-Forwarded-Proto} =http
</VirtualHost>
```
I created the path and give the permissions and now i can restart the app

The funny thing is only for that we can't use "passenger-status"

**Comment by ulisescarreonalvarez** [comment]
For the record, before the fix i restart the app with "service apache2 restart" the hard way.
I deploy manually the app and is running on AWS EC2.

**Comment by CamJN** [comment]
So passenger in apache will only look at the `PassengerInstanceRegistryDir` config, and the `TMPDIR` envvar; and failing to find those two, will fall back to `/tmp`, and systemd often sets a unique `TMPDIR` envvar per daemon (you can check the systemd unit file to verify if it was doing this).

`passenger-config` and `passenger-status` will look in the `TMPDIR` and `PASSENGER_INSTANCE_REGISTRY_DIR` envvars, and then fall back to either `/tmp` or `/var/run/passenger-instreg` if the envvars were unset. And the envvars are specific to the shell session you are using when running these commands.

All of these must agree on what the path to the instance registry dir is to work together. It looks like you've gotten the `passenger-config` command to agree with apache/passenger about the correct dir, to get the `passenger-status` command to work too, it should be enough to ensure the `PASSENGER_INSTANCE_REGISTRY_DIR` envvar is set to `/run/passenger-instreg/`, which may require an export in your shell. nb the lack of `/var/` at the beginning of the path is likely why `passenger-status` doesn't find the dir automatically. You can see how we pick what dirs to look in here: https://github.com/phusion/passenger/blob/stable-6.0/src/ruby_supportlib/phusion_passenger/admin_tools/instance_registry.rb#L94

**Comment by ulisescarreonalvarez** [comment]
So is "/var/run/passenger-instreg" and not "/run/passenger-instreg" or its ok anyway?

**Comment by CamJN** [comment]
Both are fine, but if you want to run `passenger-status` without setting the `PASSENGER_INSTANCE_REGISTRY_DIR` envvar, then `/var/run/passenger-instreg` is the one to pick. That said, you must have set the `PASSENGER_INSTANCE_REGISTRY_DIR` envvar properly for `passenger-config` to work, so you can do the same for `passenger-status`.

**Comment by ulisescarreonalvarez** [comment]
Thanks a lot for the info.

**Comment by bretweinraub** [comment]
2020, Ubuntu 20.04, same issue.

Passenger installed via apt.   Runs fine, but passenger-status and passenger-restart are inoperable [same error].

Apache 2.4.21

Setting 

PassengerInstanceRegistryDir /run/passenger-instreg/

has no effect.

**Comment by Strada-EricFr** [comment]
> So passenger in apache will only look at the `PassengerInstanceRegistryDir` config, and the `TMPDIR` envvar; and failing to find those two, will fall back to `/tmp`, and systemd often sets a unique `TMPDIR` envvar per daemon (you can check the systemd unit file to verify if it was doing this).
> 
> `passenger-config` and `passenger-status` will look in the `TMPDIR` and `PASSENGER_INSTANCE_REGISTRY_DIR` envvars, and then fall back to either `/tmp` or `/var/run/passenger-instreg` if the envvars were unset. And the envvars are specific to the shell session you are using when running these commands.
> 
> All of these must agree on what the path to the instance registry dir is to work together. It looks like you've gotten the `passenger-config` command to agree with apache/passenger about the correct dir, to get the `passenger-status` command to work too, it should be enough to ensure the `PASSENGER_INSTANCE_REGISTRY_DIR` envvar is set to `/run/passenger-instreg/`, which may require an export in your shell. nb the lack of `/var/` at the beginning of the path is likely why `passenger-status` doesn't find the dir automatically. You can see how we pick what dirs to look in here: https://github.com/phusion/passenger/blob/stable-6.0/src/ruby_supportlib/phusion_passenger/admin_tools/instance_registry.rb#L94

Regarding the tmp we had this when we start the Passenger with systemd service.
We had to set the following:

PrivateTmp=no

As, if not (depending on the OS ) it was unable to create a file in /tmp  and setting : PrivateTmp=no
 in the service definition solve some issue.

**Comment by bretweinraub** [comment]
In this example, PassengerInstanceRegistryDir was set in the virtual host and my version of Apache 2.4.x would not allow that.

I moved it to apache.conf, apache starts just fine but Passenger no longer runs my app.

**Comment by bretweinraub** [comment]
This doesn't work either:

PASSENGER_INSTANCE_REGISTRY_DIR=/tmp/passenger.ZY6kdPH passenger-status

Although I can verify via lsof that this is where passenger is nesting.
