### ISSUE TITLE
Error during WebSocket handshake: 'Connection' header is missing when using pussion passenger

### ISSUE THREAD

**Issue by syed-shibli** [phusion/passenger#2212]
**Are you sure this is a bug in Passenger?**
looks Like

**Question 1: What is the problem?**
WebSocket handshake is failing when using the Pushion passenger for Rails action cable setup. Whereas it is working with puma etc.

**Error during WebSocket handshake: 'Connection' header is missing** 

To upgrade connection from HTTP to WebSocket client sent below two headers along with other application specific headers and if the server replies back with the same header then handshake is successful.

**Upgrade:websocket
Connection:Upgrade**

- What is the expected behavior?

The response that I am expecting from the server for a handshake is

```
Sec-WebSocket-Accept:+/zbSswOvE7fwpUWN19gZDUMBfA=
Sec-WebSocket-Protocol:actioncable-v1-json
Server:Apache/2.4.29 (Ubuntu)
Status:101 Switching Protocols
Transfer-Encoding:chunked
Upgrade:websocket
Connection:Upgrade
```

- What is the actual behavior?

Actual Response is and **Connection header** is missing here
```
Sec-WebSocket-Accept:+/zbSswOvE7fwpUWN19gZDUMBfA=
Sec-WebSocket-Protocol:actioncable-v1-json
Server:Apache/2.4.29 (Ubuntu)
Status:101 Switching Protocols
`Transfer-Encoding:chunked`
Upgrade:websocket

```

 **How can we reproduce it?** 

Setup the most basic example of Rails Action Cable and serve it using Apache + pushing Passenger

I checked the server log which saying handshake successful at the backend.

```
Started GET "/cable/" [WebSocket] for -------IP----- at 2019-06-28 13:20:59 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
```

**Question 2: Passenger version and integration mode**:
Phusion Passenger 6.0.2
Web Server: Apache/2.4.29 (Ubuntu)
Rails version:5.2
Ruby version:2.6.0

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 16/18 

**Question 4: Passenger installation method**:
 Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby version:2.6.0, Rails version:5.2

**Comment by CamJN** [comment]
Is this different from https://github.com/phusion/passenger/issues/1202 ?

**Comment by syed-shibli** [comment]
I tried the  Pussion Passenger with Nginx which is working as expected. looks like the issue is with apache + Pushion passenger.

**Comment by CamJN** [comment]
Yup, apache doesn't really support websockets right now, so this is a dup of #1202
