### ISSUE TITLE
Fails to build on FreeBSD 11.3 with Clang 8

### ISSUE THREAD

**Issue by VVD** [phusion/passenger#2213]
**Question 1: What is the problem?**
passenger 6.0.2 fails to build on FreeBSD 11.3 with Clang 8:
```
c++ -o buildout/apache2/module_libpassenger_common/LoggingKit.o  -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -I/usr/include/libuv -O3 -fPIC -I/usr/local/include/apr-1 -I/usr/local/include/apr-1 -I/usr/include -I/usr/local/include -I/usr/local/include/db6 -pipe -march=core2 -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -I/usr/local/include/apache24 -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -Wno-unused-local-typedefs -Wno-format-nonliteral -DHAS_UNORDERED_MAP -c src/cxx_supportlib/LoggingKit/Implementation.cpp                                                          
In file included from src/cxx_supportlib/LoggingKit/Implementation.cpp:46:                                                      
In file included from src/cxx_supportlib/oxt/thread.hpp:28:                                                                     
In file included from src/cxx_supportlib/vendor-modified/boost/thread.hpp:17:                                                   
In file included from src/cxx_supportlib/vendor-modified/boost/thread/once.hpp:26:                                              
In file included from src/cxx_supportlib/vendor-modified/boost/thread/pthread/once_atomic.hpp:20:
In file included from src/cxx_supportlib/vendor-modified/boost/atomic.hpp:12:
In file included from src/cxx_supportlib/vendor-modified/boost/atomic/atomic.hpp:20:
In file included from src/cxx_supportlib/vendor-modified/boost/atomic/fences.hpp:21:
In file included from src/cxx_supportlib/vendor-modified/boost/atomic/detail/operations.hpp:17:
In file included from src/cxx_supportlib/vendor-modified/boost/atomic/detail/operations_lockfree.hpp:21:
In file included from src/cxx_supportlib/vendor-modified/boost/atomic/detail/ops_gcc_atomic.hpp:24:
src/cxx_supportlib/vendor-modified/boost/atomic/detail/ops_gcc_x86_dcas.hpp:408:16: error: address argument to atomic builtin
      cannot be const-qualified ('const volatile boost::atomics::detail::gcc_dcas_x86_64::storage_type *' (aka
      'const volatile unsigned __int128 *') invalid)
        return __sync_val_compare_and_swap(&storage, value, value);
               ^                           ~~~~~~~~
1 error generated.
```

**Question 2: Passenger version and integration mode**:
6.0.2.

**Question 3: OS or Linux distro, platform (including version)**:
FreeBSD 11.3 amd64.

**Question 4: Passenger installation method**:
Your answer:
[X] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[X] Other, please specify: FreeBSD ports

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Any - it's build issue, not runtime issue.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No.

**Question 7: Anything else about your setup that we should know?**
FreeBSD 11.3 release 7th of July: https://www.freebsd.org/news/newsflash.html#event20190709:01
https://www.freebsd.org/releases/11.3R/announce.html
> The clang, llvm, lld, lldb, and compiler-rt utilities as well as libc++ have been updated to upstream version 8.0.0.

The cause of this error is old version of embedded boost 1.67 in passenger 6.0.2.
Support of the Clang 8 was added in the boost 1.68, current version of the boost is 1.70, release of 1.71 planned on 14th Aug: https://www.boost.org/development/index.html.

Related links:
Bugreport in the FreeBSD's bugtracker: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239150
Bugreport in the boost's bugtracker: https://github.com/boostorg/atomic/issues/15
Commit in the boost source code with support of the Clang 8: https://github.com/boostorg/atomic/commit/6e14ca24dab50ad4c1fa8c27c7dd6f1cb791b534

**Comment by CamJN** [comment]
Same issue and solution as https://github.com/phusion/passenger/issues/2199

**Comment by VVD** [comment]
Thanks.
When is the next release planned?

**Comment by VVD** [comment]
Is 6.0.3 soon?

**Comment by CamJN** [comment]
6.0.3 is released

**Comment by VVD** [comment]
Thanks, I know.
6.0.4 released too already.
