### ISSUE TITLE
libnginx-mod-http-passenger missing in Debian 10 repo

### ISSUE THREAD

**Issue by istana** [phusion/passenger#2216]
## Issue report

**Question 1: What is the problem?**

Hi, I upgraded the system to Debian 10 (Buster), changed Passenger repository to

`deb https://oss-binaries.phusionpassenger.com/apt/passenger buster main`

and ran `apt-get update`

the problem is that the repository seems to be active, but the package with Nginx integration is missing

```
# apt-cache search passenger
libapache2-mod-passenger - Rails and Rack support for Apache2
passenger - Rails and Rack support
passenger-doc - Documentation for Passenger application server
```

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:

open source 6.x/nginx

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:

Debian 10, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by CamJN** [comment]
This is blocked on our migration to a new linux package host.

**Comment by istana** [comment]
ok, thanks for the information

**Comment by gorn** [comment]
I am stuck with this one as well. Is there a ETA when this will be resolved / any suggested worarounds?

**Comment by istana** [comment]
@gorn I've used Apache 2 instead of nginx

**Comment by gorn** [comment]
@istana  that might save me - good idea. However it is very suboptimal, because we just finished migration of everything to nginx (from apache) :(

**Comment by gorn** [comment]
Could you provide .deb package for debian 10 for download in the meantime?

**Comment by mbautista** [comment]
Hello,
Is there any solution to compile only libnginx-mod-http-passenger on Debian 10 ?
Or maybe a deb file ?
Thank you :)

**Comment by gorn** [comment]
AFAIK you should recompile whole nginx

**Comment by mbautista** [comment]
@gorn 
It seems that we can just compile the dynamic module only :
1. Note your nginx version with `nginx -v` (mine is 1.14.2)
2. Download nginx source code : ` cd /opt && wget http://nginx.org/download/nginx-1.14.2.tar.gz`
3. Extract archive : `tar -zxvf nginx-1.14.2.tar.gz && cd /opt/nginx-1.14.2`
4. Get your configure options with `nginx -V` and remove all other dynamic modules (as explained here https://gorails.com/blog/how-to-compile-dynamic-nginx-modules )
5. Append the dynamic module option `-add-dynamic-module=$(passenger-config --nginx-addon-dir)` as explained here https://www.phusionpassenger.com/library/install/nginx/install_as_nginx_module.html#dynamic-module
6. Execute configure (mine is `./configure --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-sWHVb6/nginx-1.14.2=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_secure_link_module --with-http_sub_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --add-dynamic-module=$(passenger-config --nginx-addon-dir)` )
7. Install module as explained here https://gorails.com/blog/how-to-compile-dynamic-nginx-modules :
```
mv objs/ngx_http_passenger_module.so /usr/lib/nginx/modules
echo 'load_module /usr/lib/nginx/modules/ngx_http_passenger_module.so;' | sudo tee /etc/nginx/modules-enabled/50-mod-http-passenger.conf
nginx -t
service nginx restart
```
Unfortunately it seems that the passenger package in Debian 10 is not shipped with `/usr/share/passenger/ngx_http_passenger_module` so the configure does not complete. I think we have to remove the passenger package and to compile passenger so we can have this file. I'll update this procedure if I can make it work.

**Comment by mbautista** [comment]
Sorry, I think you are right : compiling passenger implies compiling nginx as well... This is really a pain :( https://www.phusionpassenger.com/library/install/nginx/install/oss/tarball/

**Comment by mbautista** [comment]
Or we can configure nginx as reverse proxy for passenger standalone so we don't need the nginx module : https://www.phusionpassenger.com/library/deploy/standalone/reverse_proxy.html

**Comment by mbautista** [comment]
I've ended installing passenger + nginx from tarball :
https://www.phusionpassenger.com/library/install/nginx/install/oss/tarball/#starting-nginx
I'll replace this when the package is available :/

**Comment by CamJN** [comment]
If one were to compile the nginx module for Debian 10 one would need to make sure the flags used to configure nginx match the ones used in the source package: http://deb.debian.org/debian/pool/main/n/nginx/nginx_1.14.2-2.debian.tar.xz otherwise the module won't load even once configured. 

That said I'm working on the repo migration as quickly as I can, and just have some small bits left around ensuring only our CI can make changes, and testing. So you shouldn't have to be patient much longer.

**Comment by mbautista** [comment]
Thank you very much :)
I'm not in a hurry anymore, but I guess more and more people would need it soon.
Have a nice day :)

**Comment by gorn** [comment]
I will try putting standalone passenger beyond nginx https://www.phusionpassenger.com/library/deploy/standalone/reverse_proxy.html

It might not be optimal, but I can keep nginx installed from dep packages and make the apps working after the upgrade to debian 10 while waiting for upgraded repo.

The only thing I am not sure about, if standalone passenger has the capability of serving more then one rails app, like the passanges+nginx combo does.

**Comment by gonace** [comment]
Hi, is there any ETA for Debian 10 support for `libnginx-mod-http-passenger`?

**Comment by randoum** [comment]
@CamJN Thanks for your work, we are all waiting very impatiently I'm sure. This is a serious drawback. Do you have any ETA to communicate ? Regards

**Comment by HOSTED-POWER** [comment]
not really an option for us, any eta on the support for it on Debian 10? Would be great to take that into account for our planning :=)

**Comment by HOSTED-POWER** [comment]
Any update? We're about to start from scratch with Debian Stretch :/

**Comment by CamJN** [comment]
I've got the OSS version of Passenger packages for debian working, just working on the enterprise now. 

If you don't want to wait, you can build yourself some packages with this process (requires docker):

1. clone (recursively) the passenger repo stable6.0 branch
2. in the passenger/packaging/debian directory run `make -C docker-images buildbox`
3. in the passenger/packaging/debian directory run `./build -c /tmp/cache -w /tmp/work -p /path/to/passenger_repo -o ~/output -d buster pkg:all`

Your packages will be in ~/output.

Otherwise I expect to have a release by end of week.

**Comment by CamJN** [comment]
6.0.4 is released

**Comment by HOSTED-POWER** [comment]
Wow that's fast, I justed wanted to thank you yesterday already since we could compile the packages as you proposed :)

**Comment by gonace** [comment]
I'm not sure what I'm doing wrong or if I just misunderstood you @CamJN but I'm getting `Package 'libnginx-mod-http-passenger' has no installation candidate`

```
gonace@obscured-mrtg:/etc/apt/sources.list.d# sudo apt-get install -y libnginx-mod-http-passenger
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libnginx-mod-http-passenger is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libnginx-mod-http-passenger' has no installation candidate
```
```
root@obscured-mrtg:/etc/apt/sources.list.d# cat passenger.list
deb https://oss-binaries.phusionpassenger.com/apt/passenger buster main
```

I understood that this should have been released a few hours ago? :)

**Comment by CamJN** [comment]
@gonace yes, i can see that. It looks like there are a few packages that are taking longer to propagate through into our repos, they say they are still indexing so I'll keep an eye on it and update when they are done. My apologies.

**Comment by net1957** [comment]
Thanks for your work, but same problem here:
sudo cat /etc/apt/sources.list.d/passenger.list

`deb https://oss-binaries.phusionpassenger.com/apt/passenger buster main`

sudo apt-get install -y libnginx-mod-http-passenger

`'libnginx-mod-http-passenger' has no installation candidate`

Will retry tomorrow

**Comment by gonace** [comment]
@CamJN I can verify that it works for me using Debian 10 (Buster) now, many thanks :)

**Comment by net1957** [comment]
hello! Get this message:
` sudo apt-get update && sudo apt-get install -y libnginx-mod-http-passenger`


`
...
Ign:6 https://oss-binaries.phusionpassenger.com/apt/passenger buster InRelease
Get:7 https://oss-binaries.phusionpassenger.com/apt/passenger buster Release [22.6 kB]
Get:8 https://oss-binaries.phusionpassenger.com/apt/passenger buster Release.gpg [819 B]
Reading package lists... Done
E: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger buster Release' changed its 'Origin' value from 'https://packagecloud.io/phusion/passenger' to 'packagecloud.io/phusion/passenger'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
`

any clue?

**Comment by net1957** [comment]
Never mind! Have to use apt update, accept change and voila! It's installed.

Thanks for your work.

**Comment by CamJN** [comment]
Yes the indexing seems to have completed without further interference from me. Should be good now.

**Comment by gorn** [comment]
It works great so far, thanks a lot @CamJN

For me the you debian support is really essential. 

Back on track and happy :)
