### ISSUE TITLE
How to auto-start all node apps with restart Nginx?

### ISSUE THREAD

**Issue by TTATPuOT** [phusion/passenger#2217]
Hello!
I have a problem with auto-starting node.js apps with restarting of Nginx.
When i restart Nginx with `sudo systemctl reload nginx` - it works, but node.js apps dont start yet. If i go to any app in browser its starts and works fine. But i need to alls apps from Nginx config starts automatically. Its possible?

Passenger version - 6.0.2 with Nginx 1.14.0, Ubuntu 18.04.
Installed from Phusion APT repo.
Node.js 10.16.0

Nginx site config:
```
server {
	listen 443;

	server_name class.easyforus.ru;
	root /var/www/class.easyforus.ru;
    passenger_enabled on;

	location / {
		try_files $uri $uri/ /index.html;
	}

	location ~ ^/api(/.*|$) {
		alias /var/www/class.easyforus.ru/api$1;

		passenger_enabled on;
		passenger_base_uri /api;
    	passenger_app_root /var/www/class.easyforus.ru/api;
		passenger_app_type node;
		passenger_startup_file app.js;
    	passenger_app_env production;
	}
}
```

**Comment by CamJN** [comment]
You want [passenger_pre_start](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_pre_start).
