### ISSUE TITLE
Debase Debugger support broken in Enterprise

### ISSUE THREAD

**Issue by gr8bit** [phusion/passenger#2224]
## Issue report
**Question 1: What is the problem?**
- What is the expected behavior?
I want to debug passenger (inside docker) with RubyMine. Therefore I added the gems `ruby-debug-ide` and, as that module requests `debase` to my Gemfile.

- What is the actual behavior?
Passenger throws an error on startup and doesn't start:
```
App 5484 output: Error: The application encountered the following error: undefined method `start_remote' for Debase:Module
App 5484 output: Did you mean?  start_server (NoMethodError)
App 5484 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:356:in `before_handling_requests'
App 5484 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:143:in `block in negotiate_spawn_command'
App 5484 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:418:in `run_block_and_record_step_progress'
App 5484 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:142:in `negotiate_spawn_command'
App 5484 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:195:in `<module:App>'
App 5484 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:14:in `<module:PhusionPassenger>'
App 5484 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:13:in `<main>'
```

To reproduce, simply add `gem 'ruby-debug-ide', '0.7.0'` and `gem 'debase', '0.2.4.1'` to your Gemfile and start the app.

**Question 2: Passenger version and integration mode**:
passenger-docker image `phusion/passenger-ruby26:1.0.8` (version 1.0.8, passenger 6.0.4 with ruby 2.6.3)

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 18.04

**Question 4: Passenger installation method**:
Docker passenger-ruby26:1.0.8 image

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Rails 5.2.3
Ruby 2.6.3 and rvm from your docker image

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Docker with an image based on passenger-docker

**Question 7: Anything else about your setup that we should know?**
No

**Answer 1: Start of the fix**
Here's the cause:
In file `/usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb` (remember this is an Enterprise bug, this section does not exist in the normal Passenger, [see here](https://github.com/phusion/passenger/blob/release-6.0.4/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb)) there's this section:
```
      if options["debugger_support"]
        if defined?(Debugger)
          Debugger.start_remote('127.0.0.1', [0, 0])
          Debugger.start
        else
          Byebug.start_server('127.0.0.1', 0)
        end
      end
```
It just looks for Debugger, but Debase also defines Debugger but is incompatible to this (old?) API. The code should rather check for Debase first and call `Debugger.start_server('127.0.0.1', 0)` then.
There are some other changes to be made to require Debase in that file, maybe also some checks that check for the existence of Debugger only.

I cannot do a PR as this is Enterprise only.

**Comment by CamJN** [comment]
Thanks for the report, seems easy enough to fix.

**Comment by gr8bit** [comment]
I just started that, seems it's in more places...
```
$ grep -ri debugger_support
request_handler.rb:      if options["debugger_support"]
loader_shared_helpers.rb:      if options["debugger_support"]
loader_shared_helpers.rb:      if options["debugger_support"]
```

**Comment by CamJN** [comment]
I fixed the crash, but I don't think debase is popular enough to add auto loading (that also adds the headache of trying to know when the user would want debase over byebug).

**Comment by gr8bit** [comment]
@CamJN thank you for the fix, I will test it tomorrow. I use debase only because I want to use _real_ step debugging with my IDE (RubyMine) inside the container - so far I haven't gotten it to work. That's where debase comes in now. :)

**Comment by gr8bit** [comment]
@CamJN I tested it extensively now and ran into the following issues: `byebug` is (literally) required.
```
app_1       | App 666 output: Error: The application encountered the following error: cannot load such file -- byebug (LoadError)
app_1       | App 666 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:244:in `require'
app_1       | App 666 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:244:in `load_byebug_gem'
app_1       | App 666 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:224:in `before_loading_app_code_step2'
app_1       | App 666 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:76:in `preload_app'
app_1       | App 666 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:173:in `block in <module:App>'
app_1       | App 666 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:418:in `run_block_and_record_step_progress'
app_1       | App 666 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:172:in `<module:App>'
app_1       | App 666 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:14:in `<module:PhusionPassenger>'
app_1       | App 666 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:13:in `<main>'
```
So there's currently no way around including byebug in the Gemfile. I read somewhere Byebug and Debase don't play well though...

That, however, leads to the next error (don't mind the debase beta version, I checked it with the stable mainly):
```
app_1       | App 965 output: Fast Debugger (ruby-debug-ide 0.7.2, debase 0.2.5.beta1, file filtering is supported) listens on 127.0.0.1:0
app_1       | App 965 output: Error: The application encountered the following error: undefined method `cmd_port' for Debase:Module (NoMethodError)
app_1       | App 965 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:124:in `initialize'
app_1       | App 965 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:148:in `new'
app_1       | App 965 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:148:in `block in negotiate_spawn_command'
app_1       | App 965 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:418:in `run_block_and_record_step_progress'
app_1       | App 965 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:147:in `negotiate_spawn_command'
app_1       | App 965 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:195:in `<module:App>'
app_1       | App 965 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:14:in `<module:PhusionPassenger>'
app_1       | App 965 output:     /usr/share/passenger-enterprise/helper-scripts/rack-preloader.rb:13:in `<main>'
```

I don't know where the cmd_port (or even start_server) calls originate from, but here's the code attempting to (how I understand it) determine the port the Debugger chose to open:
```
      if options["debugger_support"]
        if defined?(Debugger)
          @server_sockets[:ruby_debug_cmd] = {
            :address     => "tcp://127.0.0.1:#{Debugger.cmd_port}",
            :protocol    => :ruby_debug_cmd,
            :concurrency => 1
          }
          @server_sockets[:ruby_debug_ctrl] = {
            :address     => "tcp://127.0.0.1:#{Debugger.ctrl_port}",
            :protocol    => :ruby_debug_ctrl,
            :concurrency => 1
          }
        else
       ...
```

What I don't fully understand is that the Debase seems to listen on port 0: `Fast Debugger [...] listens on 127.0.0.1:*0*` - which, in my knowledge, is meant to be replaced by a valid free port when used. I just can't figure out where Debase stores this information (if, at all).

I just want to be able to step-debug my rails app running in passenger-docker using RubyMine, so if there's another way to do that, please let me know! Otherwise please help me getting this to work! <3

P.S.: There's really no other way than using Debase for RubyMine integration as per https://www.jetbrains.com/help/ruby/debugging-code.html

P.P.S.: Regarding the port, it seems ruby-debug-ide doesn't support the "0" port if "no dispatcher should be notified of the debug server" (quoted because that's what I read from the code but am not sure what it means). So I suggest omitting the port parameter. Also, it doesn't seem to have a method to get the allocated port number (except for the dispatcher notification mechanism mentioned before). I followed this call: https://github.com/ruby-debug/ruby-debug-ide/blob/d92045574298f984cfbd87b7677cb538d006985d/lib/ruby-debug-ide.rb#L76
