### ISSUE TITLE
Add http_geoip_module to Nginx in Standalone RPM

### ISSUE THREAD

**Issue by bryantcj52** [phusion/passenger#2227]
## Issue report

Passenger standalone in RPM does not include Nginx flag --with-http_geoip_module, yet installing manually via Ruby Gems does. Also, if you remove /usr/lib64/passenger/support-binaries/nginx-1.17.3 and start an app, it grabs a differently compiled nginx with geoip enabled.

**Question 1: What is the problem?**
- What is the expected behavior?
--with-http_geoip_module should be enabled and consistent with other installs
- What is the actual behavior?
GeoIP is not enabled when installing via RPM

**Question 2: Passenger version and integration mode**:

Standalone Phusion Passenger 6.0.4 nginx/1.17.3

**Question 3: OS or Linux distro, platform (including version)**:

Centos 7 3.10.0-957.5.1.el7.x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[X] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Nodejs 10

**Comment by CamJN** [comment]
Red Hat has dropped support for the `GeoIP-devel` package in el8 (CentOS, RHEL, and related Fedora), so it's likely we will be migrating to a dynamic module based package in the next release which will simply integrate into the epel nginx.
