### ISSUE TITLE
Unknown public listening ports

### ISSUE THREAD

**Issue by romulus010689** [phusion/passenger#2229]
## Passenger Apache 2 Module opens randomly public listeningports for each process

**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

We are running the Apache Passenger Module, since Passenger 6, all the Machines opening randomly assigned higher ports for each process started by passenger:

i.e.:
We have two App instances started by passenger:

```
~# passenger-status
Version : 6.0.4
Date    : Wed Oct 23 09:55:45 +0200 2019
Instance: wCqrhk9f (Apache/2.4.18 (Ubuntu) Phusion_Passenger/6.0.4)

----------- General information -----------
Max pool size : 20
App groups    : 1
Processes     : 2
Requests in top-level queue : 0

----------- Application groups -----------
/var/www/app/current (production):
  App root: /var/www/app/current
  Requests in queue: 0
  * PID: 8514    Sessions: 0       Processed: 1       Uptime: 15m 37s
    CPU: 0%      Memory  : 98M     Last used: 15m 37s ago
  * PID: 8533    Sessions: 0       Processed: 0       Uptime: 15m 37s
    CPU: 0%      Memory  : 93M     Last used: 15m 37s ago
```

Additionally there are immediatly two ports opened by passenger:

```
~# netstat -tulpen | grep current
tcp        0      0 0.0.0.0:32840           0.0.0.0:*               LISTEN      1000       492133765   8533/current (forki
tcp        0      0 0.0.0.0:41487           0.0.0.0:*               LISTEN      1000       492133704   8514/current (forki
```

I analysed those ports by using tcpdump and curl, to find out what they are good for, however if I could trust tcpdump, there is not traffic going over those ports and when I send a curl to the ports I get a HTTP/1.1 answer with a 400 error.

Since the usual policy should be to have only listening the things public, that you really need, for security purposed in a first place, it would be nice if this port will not listen at 0.0.0.0 by default, instead maybe 127.0.0.1 if it is neccessary for passenger to work.

Your answer:

**Question 2: Passenger version and integration mode**:
open source 6.0.4 apache-module; Server version: Apache/2.4.18 (Ubuntu)

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 16.04.6 LTS

Kernel:
Linux app 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.3.1, rbenv, Rails 4.2.9

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No, running in a VM without any containerization

**Question 7: Anything else about your setup that we should know?**

**Comment by CamJN** [comment]
This change was due to this PR: https://github.com/phusion/passenger/pull/2173 to get a response you'll need to send the correct auth creds (generated on each run of passenger). If you have further concerns feel free to follow up.

**Comment by Victor-D** [comment]
Same behavior with nginx web server.
