### ISSUE TITLE
Raspberry Pi Zero Support?

### ISSUE THREAD

**Issue by mawise** [phusion/passenger#2233]
## Issue report

I'm trying to figure out if Passenger with Nginx will run on a Raspberry Pi Zero.  Your documentation doesn't include information about Debian Buster, so I'm using Debian Stretch (https://www.phusionpassenger.com/library/install/nginx/install/oss/stretch/) but when I run `$ sudo apt-get install -y libnginx-mod-http-passenger` I get: `E: Unable to locate package libnginx-mod-http-passenger`

**Question 1: What is the problem?**
- What is the expected behavior?
Passenger Installs from the passenger apt repository
- What is the actual behavior?
`E: Unable to locate package libnginx-mod-http-passenger`
- How can we reproduce it? 
Build a raspberry pi zero w with Raspian Stretch, then follow your install instructions for Debian Stretch: https://www.phusionpassenger.com/library/install/nginx/install/oss/stretch/

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer: Whatever is in the latest Apt repository for Debian Stretch

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer: Raspian Stretch Lite from Raspberry Pi.

**Question 4: Passenger installation method**:

Your answer:

- [ ] RubyGems + Gemfile
- [ ] RubyGems, no Gemfile
- [x] Phusion APT repo
- [ ] Phusion YUM repo
- [ ] OS X Homebrew
- [ ] source tarball
- [ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer: Ruby 2.4.1, rbenv

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer: No.

**Question 7: Anything else about your setup that we should know?**

Your answer:  

```
pi@raspberrypi:~ $ apt search passenger
Sorting... Done
Full Text Search... Done
endless-sky/oldstable 0.8.11-1+b1 armhf
  space exploration and combat game

endless-sky-data/oldstable 0.8.11-1 all
  data files for Endless Sky

libapache2-mod-passenger/oldstable 5.0.30-1+deb9u1 armhf
  Rails and Rack support for Apache2

passenger/oldstable 5.0.30-1+deb9u1 armhf
  Rails and Rack support

passenger-doc/stretch 1:6.0.4-1~stretch1 all
  Documentation for Passenger application server

puppet/oldstable 4.8.2-5 all
  configuration management system

puppet-master/oldstable 4.8.2-5 all
  configuration management system, master service

puppet-master-passenger/oldstable 4.8.2-5 all
  configuration management system, scalable master service

puppetmaster-passenger/oldstable 4.8.2-5 all
  configuration management system, scalable master service - transitional package

ruby-passenger/oldstable 5.0.30-1+deb9u1 all
  transitional dummy package for passenger

ruby-passenger-doc/oldstable 5.0.30-1+deb9u1 all
  transitional dummy package for passenger-doc

simutrans/oldstable 120.1.3+repack-3+deb9u1 armhf
  transportation simulator

simutrans-data/oldstable 120.1.3+repack-3+deb9u1 all
  transportation simulator (base data)

simutrans-makeobj/oldstable 120.1.3+repack-3+deb9u1 armhf
  data file compiler for Simutrans

simutrans-pak128.britain/oldstable 1.17-1 all
  transportation simulator (data files)

simutrans-pak64/oldstable 120.1.2-1 all
  transportation simulator (data files)

pi@raspberrypi:~ $
```

**Comment by CamJN** [comment]
We don't host an ARM package of Passenger, you'd have to compile it yourself or get debian to build a package.

**Comment by kevinvalk** [comment]
It would be nice to have arm/arm64 packages. In my case I am using Scaleway ARM64 instances (VPS) and I would like to run passenger.

Now I am building from source, but I think that is a suboptimal solution.

**Comment by kevinvalk** [comment]
I made it "work" semi automatic using https://github.com/kevinvalk/debian-passenger-build

Not really liking it because it will prevent you from upgrading Nginx normally. The best optimal solution would be to trigger these builds automatically on Nginx, Debian or Passenger changes and put them on a hosted apt repository.

However, for my solution it is too many moving parts/hacks that I need to maintain. For now I will move back to uWSGI for hosting Python on ARM64.

I really like Passenger so I hope you can add official support soon TM, thanks for all the work!
