### ISSUE TITLE
Sending 502 response: application did not send a complete response

### ISSUE THREAD

**Issue by hassanrafay** [phusion/passenger#2237]
Yes, the issue is with Nginx/passenger. I don't see anything wrong with anything but sometimes, we receive the following message "application did not send a complete response" out of nowhere while using the application and when I refresh the same page, the page works. 

Open source Phusion Passenger 5.3.5, nginx/1.16.1
OS: Ubuntu 18.04
Passenger installation method**: 
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

Meteor 1.9.3
The app is deployed on VPS and I am not using docker or anything.

**Comment by CamJN** [comment]
Set the passenger log level to 7 and see what it says when the issue happens. There's not enough info here to work with.

**Comment by benkruger-neyborly** [comment]
I am having this same issue. How do I set the passenger log level to 7?

**Comment by CamJN** [comment]
In the case of the nginx integration mode you use: https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_log_level

**Comment by hassanrafay** [comment]
@CamJN where and how to set the log level to 7. the link you have shared, it is just providing details about the log levels.

**Comment by CamJN** [comment]
The link does say to put it in the `http` context of your nginx config.

**Comment by rekDen** [comment]
Hi guys,
@hassanrafay was so kind to set up Log to 7.

Afterwards the log file with the error looks that way:

`[ D 2019-12-20 13:21:47.5051 83951/Ta Ser/Server.h:881 ]: [ServerThr.2] 1 new client(s) accepted; there are now 1 active client(s)
[ D3 2019-12-20 13:21:47.5051 83951/Ta Ser/HttpServer.h:769 ]: [Client 2-3674] Event: onClientAccepted
[ D3 2019-12-20 13:21:47.5051 83951/Ta Ser/HttpServer.h:310 ]: [Client 2-3674] Refcount increased; it is now 3
[ D3 2019-12-20 13:21:47.5051 83951/Ta Ser/FileBufferedChannel.h:1460 ]: [FBC 0x7ffbc800a860] Deinitialize
[ D3 2019-12-20 13:21:47.5051 83951/Ta Ser/HttpServer.h:186 ]: [ServerThr.2] Checking out request object from freelist (43 -> 42)
[ D3 2019-12-20 13:21:47.5052 83951/Ta Ser/Server.h:568 ]: [Client 2-3674] Processing 2471 bytes of client data
[ D3 2019-12-20 13:21:47.5052 83951/Ta Ser/HttpServer.h:777 ]: [Client 2-3674] Event: onClientDataReceived
[ D3 2019-12-20 13:21:47.5052 83951/Ta Ser/HttpServer.h:780 ]: [Client 2-3674] Request refcount increased; it is now 2
[ D3 2019-12-20 13:21:47.5052 83951/Ta Ser/HttpServer.h:331 ]: [Client 2-3674] Parsing 2471 bytes of HTTP header: “GET /cdn/storage/uploadedFiles/N8srDXQzbDBeYCzxe/original/N8srDXQzbDBeYCzxe.pdf HTTP/1.1\r\nConnection: close\r\nAccept: text/html, application/xhtml+xml, */*\r\nAccept-Language: de-DE\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko\r\nAccept-Encoding: gzip, deflate\r\nHost: a.testDomain.de\r\nDNT: 1\r\nConnection: Keep-Alive\r\n!~: 00mMtOIkVHRfLwKgcE4UDZPb\r\n!~DOCUMENT_ROOT: /var/www/vhosts/testDomain.de/a.testDomain.de/MeteorApp/build/bundle/programs/server/assets\r\n!~REMOTE_ADDR: 217.247.70.46\r\n!~REMOTE_PORT: 22107\r\n!~PASSENGER_APP_GROUP_NAME: /var/www/vhosts/testDomain.de/a.testDomain.de/MeteorApp/build/bundle/programs/server (production)\r\n!~PASSENGER_APP_TYPE: nodejs\r\n!~PASSENGER_RUBY: ruby\r\n!~PASSENGER_PYTHON: python\r\n!~PASSENGER_NODEJS: /opt/plesk/node/8/bin/node\r\n!~PASSENGER_APP_ENV: production\r\n!~PASSENGER_FRIENDLY_ERROR_PAGES: t\r\n!~PASSENGER_MIN_PROCESSES: 1\r\n!~PASSENGER_START_TIMEOUT: 90\r\n!~PASSENGER_USER: b3rk0v\r\n!~PASSENGER_GROUP: psacln\r\n!~PASSENGER_APP_ROOT: /var/www/vhosts/testDomain.de/a.testDomain.de/MeteorApp/build/bundle/programs/server\r\n!~PASSENGER_DEBUGGER: f\r\n!~PASSENGER_MAX_PRELOADER_IDLE_TIME: 300\r\n!~PASSENGER_LOAD_SHELL_ENVVARS: t\r\n!~PASSENGER_MAX_REQUEST_QUEUE_SIZE: 100\r\n!~PASSENGER_STARTUP_FILE: startupSL.js\r\n!~PASSENGER_RESTART_DIR: tmp\r\n!~PASSENGER_ABORT_WEBSOCKETS_ON_PROCESS_SHUTDOWN: t\r\n!~PASSENGER_FORCE_MAX_CONCURRENT_REQUESTS_PER_PROCESS: 20\r\n!~PASSENGER_MAX_REQUESTS: 0\r\n!~PASSENGER_REQUEST_QUEUE_OVERFLOW_STATUS_CODE: 503\r\n!~PASSENGER_STICKY_SESSIONS: t\r\n!~PASSENGER_STICKY_SESSIONS_COOKIE_NAME: _passenger_route\r\n!~PASSENGER_ENV_VARS: Uk9PVF9VUkwAaHR0cHM6Ly80Yy5wZmxlZ2xpc29mdC5kZQBNT05HT19VUkwAbW9uZ29kYitzcnY6Ly9yb290OlUxZnlZR2VRUTZJZkl6WmZAcGZsZWdsaXNvZnQtdjItYWZiZ2cubW9uZ29kYi5uZXQvbWV0ZW9yNGM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5AEFQUF9FTlYAbGl2ZQBNRVRFT1JfU0VUVElOR1MAeyJwcml2YXRlIjp7ImltYXAiOnsiY29uZmlnIjp7Imhvc3QiOiJlbWFpbC5wZmxlZ2xpc29mdC5kZSIsInBvcnQiOjE0MywidGxzIjpmYWxzZX19LCJzbXRwIjp7ImNvbmZpZyI6eyJob3N0IjoiZW1haWwucGZsZWdsaXNvZnQuZGUiLCJwb3J0Ijo1ODcsInNlY3VyZSI6ZmFsc2V9fSwicGxlc2siOnsiaG9zdCI6IjgyLjE2NS4xMTYuMTYxIiwidXNlciI6InJvb3QiLCJwYXNzd29yZCI6Ik1uN2ZqNTVKOGsiLCJhZXNLZXkiOiIxMjN8YTEyMzc5OTIzMTkzMTIzQCYiLCJkZWZhdWx0UGFzc3dvcmQiOiIoQVc/OntdKiJ9LCJhZG1pbiI6eyJzZWNyZXQiOiJ0aGlzIGlzIHRoZSBzZWNyZXQgbXkgZHVkZS4ifX0sInB1YmxpYyI6e319AFBBU1NFTkdFUl9DT01QSUxFX05BVElWRV9TVVBQT1JUX0JJTkFSWQAwAFBBU1NFTkdFUl9ET1dOTE9BRF9OQVRJVkVfU1VQUE9SVF9CSU5BUlkAMAA=\r\n!~FLAGS: DCS\r\n\r\n”
[ D2 2019-12-20 13:21:47.5053 83951/Ta Ser/HttpServer.h:342 ]: [Client 2-3674] New request received: #3674
[ D2 2019-12-20 13:21:47.5053 83951/Ta age/Cor/Con/InitRequest.cpp:453 ]: [Client 2-3674] Initiating request
[ D2 2019-12-20 13:21:47.5053 83951/Ta age/Cor/Con/InitRequest.cpp:87 ]: [Client 2-3674] Dechunk flag detected
[ D2 2019-12-20 13:21:47.5053 83951/Ta age/Cor/Con/InitRequest.cpp:93 ]: [Client 2-3674] HTTPS flag detected
[ D2 2019-12-20 13:21:47.5053 83951/Ta age/Cor/Con/InitRequest.cpp:96 ]: [Client 2-3674] Stripping 100 Continue header
[ D2 2019-12-20 13:21:47.5053 83951/Ta age/Cor/Con/InitRequest.cpp:109 ]: [Client 2-3674] Turbocaching: trying to reply from cache (key “Sa.testDomain.de\n/cdn/storage/uploadedFiles/N8srDXQzbDBeYCzxe/original/N8srDXQzbDBeYCzxe.pdf”)
[ D2 2019-12-20 13:21:47.5053 83951/Ta age/Cor/Con/InitRequest.cpp:110 ]: [Client 2-3674] Turbocache entries:
 #0: valid=0, hash=3880331411, expiryDate=1608384033, keySize=94, key=“Sa.testDomain.de\n/cdn/storage/uploadedFiles/F6Tg6x9j2po7Tm2FH/original/F6Tg6x9j2po7Tm2FH.pdf”
 #1: valid=0, hash=0, expiryDate=0, keySize=0, key=“”
 #2: valid=0, hash=0, expiryDate=0, keySize=0, key=“”
 #3: valid=0, hash=0, expiryDate=0, keySize=0, key=“”
 #4: valid=0, hash=0, expiryDate=0, keySize=0, key=“”
 #5: valid=0, hash=0, expiryDate=0, keySize=0, key=“”
 #6: valid=0, hash=0, expiryDate=0, keySize=0, key=“”
 #7: valid=0, hash=0, expiryDate=0, keySize=0, key=“”

[ D2 2019-12-20 13:21:47.5053 83951/Ta age/Cor/Con/InitRequest.cpp:126 ]: [Client 2-3674] Turbocaching: cache miss: NOT_FOUND (key “Sa.testDomain.de\n/cdn/storage/uploadedFiles/N8srDXQzbDBeYCzxe/original/N8srDXQzbDBeYCzxe.pdf”)
[ D2 2019-12-20 13:21:47.5054 83951/Ta age/Cor/Con/CheckoutSession.cpp:56 ]: [Client 2-3674] Checking out session: appRoot=/var/www/vhosts/testDomain.de/a.testDomain.de/MeteorApp/build/bundle/programs/server
[ D3 2019-12-20 13:21:47.5054 83951/Ta age/Cor/Con/CheckoutSession.cpp:70 ]: [Client 2-3674] Request refcount increased; it is now 3
[ D2 2019-12-20 13:21:47.5054 83951/Ta age/Cor/App/Poo/Miscellaneous.cpp:49 ]: asyncGet(appGroupName=/var/www/vhosts/testDomain.de/a.testDomain.de/MeteorApp/build/bundle/programs/server (production))
[ D2 2019-12-20 13:21:47.5054 83951/Ta age/Cor/App/Poo/Miscellaneous.cpp:56 ]: Found existing Group
[ D 2019-12-20 13:21:47.5054 83951/Ta age/Cor/App/Gro/SessionManagement.cpp:330 ]: Session checked out from process (pid=105813, group=/var/www/vhosts/testDomain.de/a.testDomain.de/MeteorApp/build/bundle/programs/server (production))
[ D2 2019-12-20 13:21:47.5054 83951/Ta age/Cor/App/Poo/Miscellaneous.cpp:61 ]: asyncGet() finished
[ D 2019-12-20 13:21:47.5054 83951/Ta age/Cor/Con/CheckoutSession.cpp:139 ]: [Client 2-3674] Session checked out: pid=105813, gupid=191022f-h2auNcQ5hU
[ D3 2019-12-20 13:21:47.5054 83951/Ta age/Cor/App/Socket.h:178 ]: Socket unix:/tmp/passenger.qpbAlmM/apps.s/node.1chim4: checking out connection from connection pool (1 -> 0 items). Current total number of connections: 1
[ D 2019-12-20 13:21:47.5054 83951/Ta age/Cor/Con/CheckoutSession.cpp:199 ]: [Client 2-3674] Session initiated: fd=40
[ D2 2019-12-20 13:21:47.5055 83951/Ta age/Cor/Con/SendRequest.cpp:88 ]: [Client 2-3674] Sending headers to application with http protocol
[ D3 2019-12-20 13:21:47.5055 83951/Ta age/Cor/Con/SendRequest.cpp:639 ]: [Client 2-3674] Header data: “GET /cdn/storage/uploadedFiles/N8srDXQzbDBeYCzxe/original/N8srDXQzbDBeYCzxe.pdf HTTP/1.1\r\nConnection: close\r\nuser-agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko\r\naccept-encoding: gzip, deflate\r\ndnt: 1\r\naccept: text/html, application/xhtml+xml, */*\r\naccept-language: de-DE\r\nhost: a.testDomain.de\r\nX-Forwarded-Proto: https\r\n!~Passenger-Proto: https\r\nX-Forwarded-For: 217.247.70.46\r\n!~Passenger-Client-Address: 217.247.70.46\r\n!~Passenger-Envvars: Uk9PVF9VUkwAaHR0cHM6Ly80Yy5wZmxlZ2xpc29mdC5kZQBNT05HT19VUkwAbW9uZ29kYitzcnY6Ly9yb290OlUxZnlZR2VRUTZJZkl6WmZAcGZsZWdsaXNvZnQtdjItYWZiZ2cubW9uZ29kYi5uZXQvbWV0ZW9yNGM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5AEFQUF9FTlYAbGl2ZQBNRVRFT1JfU0VUVElOR1MAeyJwcml2YXRlIjp7ImltYXAiOnsiY29uZmlnIjp7Imhvc3QiOiJlbWFpbC5wZmxlZ2xpc29mdC5kZSIsInBvcnQiOjE0MywidGxzIjpmYWxzZX19LCJzbXRwIjp7ImNvbmZpZyI6eyJob3N0IjoiZW1haWwucGZsZWdsaXNvZnQuZGUiLCJwb3J0Ijo1ODcsInNlY3VyZSI6ZmFsc2V9fSwicGxlc2siOnsiaG9zdCI6IjgyLjE2NS4xMTYuMTYxIiwidXNlciI6InJvb3QiLCJwYXNzd29yZCI6Ik1uN2ZqNTVKOGsiLCJhZXNLZXkiOiIxMjN8YTEyMzc5OTIzMTkzMTIzQCYiLCJkZWZhdWx0UGFzc3dvcmQiOiIoQVc/OntdKiJ9LCJhZG1pbiI6eyJzZWNyZXQiOiJ0aGlzIGlzIHRoZSBzZWNyZXQgbXkgZHVkZS4ifX0sInB1YmxpYyI6e319AFBBU1NFTkdFUl9DT01QSUxFX05BVElWRV9TVVBQT1JUX0JJTkFSWQAwAFBBU1NFTkdFUl9ET1dOTE9BRF9OQVRJVkVfU1VQUE9SVF9CSU5BUlkAMAA=\r\n\r\n”
[ I 2019-12-20 13:21:47.5055 83951/Ta age/Cor/Con/SendRequest.cpp:1070 ]: [Client 2-3674] App socket write error: the application closed the socket prematurely (Broken pipe; errno=32)
[ D3 2019-12-20 13:21:47.5055 83951/Ta age/Cor/Con/ForwardResponse.cpp:64 ]: [Client 2-3674] Event: onAppSourceData
[ D 2019-12-20 13:21:47.5055 83951/Ta age/Cor/Con/ForwardResponse.cpp:131 ]: [Client 2-3674] Application sent EOF before finishing response headers
[ W 2019-12-20 13:21:47.5055 83951/Ta age/Cor/Con/InternalUtils.cpp:96 ]: [Client 2-3674] Sending 502 response: application did not send a complete response
[ D3 2019-12-20 13:21:47.5056 83951/Ta Ser/FileBufferedChannel.h:1416 ]: [FBC 0x7ffbc800a860] Feeding 223 bytes`

**Comment by CamJN** [comment]
As you can see in the log (`App socket write error: the application closed the socket prematurely (Broken pipe; errno=32)`), your app is closing the socket before writing a complete response, or more likely crashing.
