### ISSUE TITLE
504 error or not being able to spawn the process

### ISSUE THREAD

**Issue by hassanrafay** [phusion/passenger#2239]
Yes, the issue is with Nginx/passenger. I have the same configuration running on my local ubuntu Machine but it is not working on the server, I am receiving an error 504 or sometimes passenger's is not able to spawn the process. I have added the backtrace at the bottom. 

Open source Phusion Passenger 5.3.5, nginx/1.16.1
OS: Ubuntu 18.04
Passenger installation method**:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

Meteor 1.9.3
The app is deployed on VPS and I am not using docker or anything.

Backtrace
```
     in 'bool Passenger::SpawningKit::HandshakePerform::checkCurrentState()' (Perform.h:257)
     in 'void Passenger::SpawningKit::HandshakePerform::waitUntilSpawningFinished(boost::unique_lock<boost::mutex>&)' (Perform.h:213)
     in 'Passenger::SpawningKit::Result Passenger::SpawningKit::HandshakePerform::execute()' (Perform.h:1752)
     in 'Passenger::SpawningKit::Result Passenger::SpawningKit::DirectSpawner::internalSpawn(const AppPoolOptions&, Passenger::SpawningKit::Config&, Passenger::SpawningKit::HandshakeSession&, const Passenger::Json::Value&, Passenger::SpawningKit::JourneyStep&)' (DirectSpawner.h:211)
     in 'virtual Passenger::SpawningKit::Result Passenger::SpawningKit::DirectSpawner::spawn(const AppPoolOptions&)' (DirectSpawner.h:261)
     in 'void Passenger::ApplicationPool2::Group::spawnThreadRealMain(const SpawnerPtr&, const Passenger::ApplicationPool2::Options&, unsigned int)' (SpawningAndRestarting.cpp:95)
```

**Comment by CamJN** [comment]
While you are correct that Passenger is unable to spawn the app process, you'll need to provide logs from your app or something for me to be able to try and figure out why your app isn't starting as expected. It would also be useful to include the output from the passenger log with the passenger_log_level set to 7. https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_log_level
