### ISSUE TITLE
Passenger Enterprise runs app in wrong folder (multi tenancy related)

### ISSUE THREAD

**Issue by pauljohn32** [phusion/passenger#2251]
I have 2 Python apps using graphic display with plotly and dash and the passenger demo app in folders like this:

```
/var/www/dashboard
/var/www/miso
/var/www/passenger-python-flask-demo
```

The goal is to run the app in `/var/www/dashboard` when the user opens `http://myserver.com` or `myserver.com/kceg`, or to run the one in the folder `/var/www/miso` when the user opens `http://myserver.com/energy`.  Or to run `/var/www/passenger-python-flask-demo` when user runs `http://myserver.com/demo`.  So far, I can get the `demo` to run, or one of the Python plotly apps.

I followed the sub uri instructions for nginx.

```
server {
    listen 80;
    server_name example.com;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /var/www/dashboard/public;

    passenger_app_type wsgi;
    passenger_startup_file passenger_wsgi.py;
    # Turn on Passenger
    passenger_enabled on;
    passenger_python /var/www/dashboard/venv/bin/python3.7;

    location ~ ^/kceg(/.*|$) {
        alias /var/www/dashboard/public$1;
	passenger_python /var/www/dashboard/venv/bin/python3.7;
	passenger_base_uri /kceg;
        passenger_app_root /var/www/dashboard;
        passenger_document_root /var/www/dashboard/public;
        passenger_enabled on;
        passenger_app_env development;
   }    

   location ~ ^/energy(/.*|$) {
        alias /var/www/miso/public$1;
        passenger_python /var/www/miso/venv/bin/python3.7;
        passenger_base_uri /energy;
        passenger_app_root /var/www/miso;
        passenger_document_root /var/www/miso/public;
        passenger_enabled on;
	passenger_startup_file miso_wsgi.py;
        passenger_app_env development;
   }

   location ~ ^/demo(/.*|$) {
        alias /var/www/passenger-python-flask-demo/public$1;
        passenger_python /var/www/passenger-python-flask-demo/venv/bin/python3.7;
        passenger_base_uri /demo;
        passenger_app_root /var/www/passenger-python-flask-demo;
        passenger_document_root /var/www/passenger-python-flask-demo/public;
        passenger_enabled on;
	passenger_app_env development;
        passenger_startup_file demo_wsgi.py;
   }
}
```

If I browse to /demo, then the demo app displays correctly.

However, I'm not able to control which Python plotly app runs by the URL.  The same one always runs. Note at the top in this case, I have the lines:

```
    passenger_enabled on;
    passenger_python /var/www/dashboard/venv/bin/python3.7;
```

If that stanza has /var/www/dashboard, then the app in that folder always runs. The location stanza for "energy" seemed to be ignored, I thought.

I thought that the location stanza was being completely ignored, but I inserted a coding error in the energy app and turned on passenger development mode.  This caused the Web browser to show the errors in the app itself. The display has a helpful three pane display that clearly shows it is going into the location directory.  Now the **bad** part.  After correcting those self-imposed errors, then I refresh the browser.  The tab momentarily shows the name of the energy program, but then the `kceg` app displays on the screen.

I've tested this quite a bit, re-naming files in the subfolders.  At the beginning, all of my Python programs were named "app.py" and the wsgi config files in the subdirectories were "passenger_wsgi.py".  I wondered if NGINX/Passenger were confused by the same-ness of the app names.  When I trigger an error in one of the apps, I can see that Passenger is clearly following the location and using the correct app file.  However, when I fix the app, then we are back to the problem that the one mentioned in the top of the config file always runs. 

---

**Are you sure this is a bug in Passenger?**
Please read our troubleshooting and debugging guides first:
https://www.phusionpassenger.com/library/admin/troubleshooting/
https://www.phusionpassenger.com/library/admin/

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 2: Passenger version and integration mode**:

Passenger Enerprise 6.0.4-2, Nginx, 

**Question 3: OS or Linux distro, platform (including version)**:

Ubuntu 18.04 LTS

**Question 4: Passenger installation method**:

Your answer:
[X ] Phusion APT repo
[
**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Python 3.7

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer:

I am testing this on a VM in the Azure cloud, not using their app-deploy system. 

**Question 7: Anything else about your setup that we should know?**

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by pauljohn32** [comment]
https://github.com/phusion/passenger/issues/1256#issuecomment-95261834 mentions same symptom. First path found runs, location section is not followed at very last moment.

**Comment by CamJN** [comment]
I believe you might be seeing a variant of this issue: https://github.com/phusion/passenger/issues/2117 can you try the patch provided there?

**Comment by pauljohn32** [comment]
You mean this patch here?  https://github.com/phusion/passenger/issues/2117#issuecomment-573854232.  How to use it?
I'm familiar with patching and compiling debian patches, but appears that the enterprise passenger source server will not allow:

```
$ apt-get source libnginx-mod-http-passenger-enterprise
Reading package lists... Done
Picking 'passenger-enterprise' as source package instead of 'libnginx-mod-http-passenger-enterprise'
Need to get 11.8 MB of source archives.
Err:1 https://www.phusionpassenger.com/enterprise_apt bionic/main passenger-enterprise 6.0.4-2~bionic1 (tar)
  401  Unauthorized [IP: 167.99.102.244 443]
Err:2 https://www.phusionpassenger.com/enterprise_apt bionic/main passenger-enterprise 6.0.4-2~bionic1 (diff)
  401  Unauthorized [IP: 167.99.102.244 443]
Err:3 https://www.phusionpassenger.com/enterprise_apt bionic/main passenger-enterprise 6.0.4-2~bionic1 (dsc)
  401  Unauthorized [IP: 167.99.102.244 443]
E: Failed to fetch https://www.phusionpassenger.com/enterprise_apt/pool/bionic/main/p/passenger-enterprise/passenger-enterprise_6.0.4.orig.tar.gz  401  Unauthorized [IP: 167.99.102.244 443]
```

If you point me on how to apply the patch to enterprise passenger, I'm willing to try.

If you put Debian package somewhere, let me know, I will install.

I'm testing this on an Azure VM that does not have all of the compilers and such, so it is somewhat tedious.

**Comment by pauljohn32** [comment]
I have a workaround that succeeds for Python Plotly apps using the Dash framework.  The app needs to be told the suburi on which it needs to listen.

In the app.py file, there is a line like this:

```
app = dash.Dash(__name__,
    meta_tags=[
        {
            "name": "viewport",
            "content": "width=device-width"
        }
    ]
)
```

and it should change to look like this:

```
app = dash.Dash(__name__,
    meta_tags=[
        {
            "name": "viewport",
            "content": "width=device-width"
        }
    ],
    requests_pathname_prefix='/energy/'
)
app.config.suppress_callback_exceptions = True
```

In one example, I did this differently, with a separate stanza like:

```
app.config.update({
    'routes_pathname_prefix': '',
    'requests_pathname_prefix': '/energy/'
})
```

but that method fails when a user authentication component is introduced with dash_auth.

I've confirmed this with several Plotly apps in Python. 

I notice that the Phusion Passenger doc section on sub-URI deployment with node.js warns about this kind of app-specific change (https://www.phusionpassenger.com/library/deploy/nginx/deploy/nodejs/):

```
Sub-URI deployments in Node.js require framework-specific adjustments in the application. For example, in Express 4.0+, you should use a router. An alternative is to use url rewriting to avoid the need for sub-URIs altogether. 
```

I'm just lucky I found a simple change to fix the Plotly app.  I am asking in separate issue for help on node.js.
