### ISSUE TITLE
please explain "use url rewriting to avoid need for sub-URIs altogether."

### ISSUE THREAD

**Issue by pauljohn32** [phusion/passenger#2254]
There is a 2015 thread about uri rewriting (https://github.com/phusion/passenger/issues/1256), but I don't understand all of the details how to do this.  I wish you would put instructions in your document.

In the deployment manual (https://www.phusionpassenger.com/library/deploy/nginx/deploy/nodejs/), there is the following comment:

```
Sub-URI deployments in Node.js require framework-specific adjustments in the application. For example, in Express 4.0+, you should use a router. An alternative is to use url rewriting to avoid the need for sub-URIs altogether. 
```

It does not appear workable to change the apps themselves, they are supplied by other team members. So I need to understand your comment "use url rewriting to avoid the need for sub-URIs altogether."

I need to run several node.js apps in folders like

```
/var/www/node1
/var/www/node2
```

but all of the apps are written as if they are in the webroot of a single server.  

Could you please add a few paragraphs and a working example about "use url rewriting" in your documentation?  Or point at a working example.

**Question 2: Passenger version and integration mode**:
- Open source 6/nginx

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
-
Your answer: Ubuntu 18.04 on Azure VM

**Question 4: Passenger installation method**:

Your answer:
[ ] Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer:
Node.js 13

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer: Folder on Azure VM web server /var/www/node1 is offered by nginx and Passenger. No docker container. 

**Question 7: Anything else about your setup that we should know?**

Your answer: I'm learning as I go. I succeeded in delivering Python/Plotly apps with Passenger, but node is proving more difficult. 
---

**Comment by CamJN** [comment]
If you are using nginx or standalone the config options you need to use are `proxy_pass`, `sub_filter`, and `sub_filter_once`.

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
http://nginx.org/en/docs/http/ngx_http_sub_module.html#sub_filter

`proxy_pass` will allow you to redirect from one url to another, and `sub_filter` will allow you to fix urls on the page.

**Comment by pauljohn32** [comment]
Can you paste in one working example nginx .conf file. I have tried and do not understand your expression 'fix urls'. If you give one example,  I bet I can get it.

**Comment by CamJN** [comment]
As an example this works for me:

```
server {
    listen 8443 ssl http2;
    server_name baseuri.phusionpassenger.dev;
    ssl_certificate /etc/nginx/server.crt;
    ssl_certificate_key /etc/nginx/server.key;

    location /testy {
        proxy_pass http://localhost:8000/;
    }
}

server {
    listen 8000;
    server_name localhost;

    sub_filter 'baseuri.phusionpassenger.dev/' 'baseuri.phusionpassenger.dev/testy';
    sub_filter 'href="/' 'href="/testy';
    sub_filter 'src="/' 'src="/testy';
    sub_filter_once off;

    root /Users/camdennarzt/Developer/Javascript/testapp/www;
    passenger_enabled on;
}

```
