### ISSUE TITLE
Starting Node.js program with specific UMask when Sandboxing is enabled, Passenger Nginx integration

### ISSUE THREAD

**Issue by Jungack** [phusion/passenger#2255]
Hello,
Noob here, sorry ! I looked everywhere but was unable to find how we can set default UMask when starting a Node.js app from Nginx. Nginx is running as `www-data`, whereas the app is running as `user` because of sandboxing feature enabled. The default files and folders created by the app are owned by `user`, and permissions are 755. How can I set them by default to 770 ?
When I'm logged in with `user`, I can set `umask=007` to make It work.
I'm on Debian 10 if this is useful.
Sorry for this stupid question...

**Comment by CamJN** [comment]
there are several ways, but perhaps the easiest would be to set the umask is user's bash startup config (before any interactive check) as by default passenger will source your user's bash env before starting your app (but in non-interactive mode).
