### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by ashrafalzyoud** [phusion/passenger#2263]
when passenger can added ubuntu 20.04

**Comment by ignl** [comment]
Second that, tried to update Ubuntu and installing from passenger apt not possible as focal version doesn't exist and bionic version is not compatible with new nginx version. Only few weeks left until final 20.04 release.

**Comment by nraju-nyros** [comment]
The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: passenger (= 1:6.0.4-1~bionic1) but it is not going to be installed
                               Depends: nginx-common (>= 1.14.0-0ubuntu1.6) but 1.10.3-0ubuntu0.16.04.5 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by ashrafalzyoud** [comment]
What version nginx and passenger used to work in Ubuntu 20.04

**Comment by CamJN** [comment]
If you want to speed up the process you can make a PR that adds 20.04 support. Here's the instructions: https://github.com/phusion/passenger_apt_automation/#adding-support-for-a-new-distribution

**Comment by CamJN** [comment]
We are working on some changes to our repos, but the work to support ubuntu focal has been done, and will be in the next release.

**Comment by gordonbisnor** [comment]
> We are working on some changes to our repos, but the work to support ubuntu focal has been done, and will be in the next release.

Any idea of the ETA on that release? Wondering if I should create a new machine with Ubuntu 18 or 20...

**Comment by msheakoski** [comment]
@gordonbisnor If you start from 18.04, you can install passenger/nginx, then update to 20.04 and everything still works. If you are starting from 20.04 however, the compatible packages such as older versions of ruby/nginx will not be available to successfully install passenger.

**Comment by gordonbisnor** [comment]
Thanks for the heads up!

**Comment by njosefbeck** [comment]
Hello! I'm following the Passenger installation instructions here: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/enterprise/digital_ocean/ruby/nginx/

```
# Install our PGP key and add HTTPS support for APT
sudo apt-get install -y dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt-get install -y apt-transport-https ca-certificates

# Add our APT repository
unset HISTFILE
sudo sh -c 'echo machine www.phusionpassenger.com/enterprise_apt login download password YOUR_DOWNLOAD_TOKEN >> /etc/apt/auth.conf'
sudo sh -c 'echo deb https://www.phusionpassenger.com/enterprise_apt bionic main > /etc/apt/sources.list.d/passenger.list'
sudo chown root: /etc/apt/sources.list.d/passenger.list
sudo chmod 644 /etc/apt/sources.list.d/passenger.list
sudo chown root: /etc/apt/auth.conf
sudo chmod 600 /etc/apt/auth.conf
sudo apt-get update

# Install Passenger Enterprise + Nginx module
sudo apt-get install -y libnginx-mod-http-passenger-enterprise
```

I've replaced the line `deb https://www.phusionpassenger.com/enterprise_apt bionic main` with `deb https://oss-binaries.phusionpassenger.com/apt/passenger-testing focal main` as mentioned above, and everything seems to work fine until I get to installing `libnginx-mod-http-passenger-enterprise`, and I get the below error.

```
E: Unable to locate package libnginx-mod-http-passenger-enterprise
```

Do I need to update other places to use the testing repo, or do I just need to wait for the next Passenger release to drop w/ Ubuntu 20.04 support? Any help would be much appreciated! Thanks!

**Comment by CamJN** [comment]
Focal packages will be added in the next release, there aren't any yet. They have been blocked on a repo migration that is being finished up today, so the new release should be soon.

**Comment by njosefbeck** [comment]
@CamJN Thanks so much for the speedy reply! I'll hang tight then. Looking forward to using Passenger :).

**Comment by CamJN** [comment]
6.0.5 is out with focal support

**Comment by njosefbeck** [comment]
Thanks for this! Was able to use the updated instructions to get passenger set up, so much appreciated!

**Comment by davidfilip** [comment]
@CamJN I've tried to install the passenger using sudo apt-get install -y libnginx-mod-http-passenger

and got following error:

```
The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (< 1.14.1) but 1.17.10-0ubuntu1 is to be installed
```

**Comment by CamJN** [comment]
@davidfilip wow that is really unlucky timing with it changing since friday, I'll see if I can release a new version asap.

**Comment by CamJN** [comment]
@davidfilip actually it looks like we specified the correct nginx for focal. here's my apt info output:
```
# apt info libnginx-mod-http-passenger 
Package: libnginx-mod-http-passenger
Version: 1:6.0.5-1~focal1
Priority: optional
Section: ruby
Source: passenger
Maintainer: Phusion <info@phusion.nl>
Installed-Size: 1831 kB
Depends: libc6 (>= 2.17), libgcc-s1 (>= 3.0), libstdc++6 (>= 9), passenger (= 1:6.0.5-1~focal1), nginx-common (>= 1.17.10-0ubuntu1), nginx-common (<< 1.17.11)
Homepage: https://www.phusionpassenger.com/
Download-Size: 421 kB
APT-Manual-Installed: yes
APT-Sources: https://oss-binaries.phusionpassenger.com/apt/passenger focal/main amd64 Packages
Description: Nginx integration for Passenger application server
 Passenger is an application server for Ruby, Node.js, Python, Meteor.
 It makes deployment of web apps very easy and robust. Passenger is a
 Phusion product.
 .
 This package contains the Nginx module for integration with Passenger.
```

As you can see it depends on `nginx-common (>= 1.17.10-0ubuntu1), nginx-common (<< 1.17.11)`.
What does your `apt info` say?

**Comment by davidfilip** [comment]
@CamJN My apt info say:
$ apt info libnginx-mod-http-passenger 

```
Package: libnginx-mod-http-passenger
Version: 1:6.0.5-1~bionic1
Priority: optional
Section: ruby
Source: passenger
Maintainer: Phusion <info@phusion.nl>
Installed-Size: 1,719 kB
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libstdc++6 (>= 5.2), passenger (= 1:6.0.5-1~bionic1), nginx-common (>= 1.14.0-0ubuntu1.7), nginx-common (<< 1.14.1)
Homepage: https://www.phusionpassenger.com/
Download-Size: 410 kB
APT-Sources: https://oss-binaries.phusionpassenger.com/apt/passenger bionic/main amd64 Packages
```

**Comment by msheakoski** [comment]
@davidfilip Make sure your `cat /etc/apt/sources.list.d/passenger.list` looks like this (with focal, not bionic):

```
deb https://oss-binaries.phusionpassenger.com/apt/passenger focal main
```

and then run `apt update`

It looks like [the docs](https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/node/nginx/) show the correct instructions, so you might have accidentally selected the bionic instructions or had it left over from a previous install.

**Comment by mwlalata** [comment]
> Not install passenger ! What the solution ?
> sudo apt-get install -y libnginx-mod-http-passenger
> 
> Error
> The following packages have unmet dependencies:
> libnginx-mod-http-passenger : Depends: passenger (= 1:6.0.4-1~bionic1) but it is not going to be installed
> Depends: nginx-common (>= 1.14.0-0ubuntu1.6) but 1.10.3-0ubuntu0.16.04.5 is to be installed
> E: Unable to correct problems, you have held broken packages.

same problem

**Comment by mwlalata** [comment]
> apt update

this worked. dankeschön!

**Comment by happychriss** [comment]
Missing i386 packages on focal rep:
https://oss-binaries.phusionpassenger.com/apt/passenger/dists/focal/ only contains packages for amd64, i386 package is missing (sames is valid for test repository)

As of this I am not able to install on 20.04 on 
linux zo 5.4.0-37-generic  x86_64 x86_64 x86_64 GNU/Linux

**Comment by CamJN** [comment]
@happychriss that is because canonical has dropped support for 32 bit packages we depend on. So we cannot provide a 32 bit passenger package on focal.

You can read a bit about it here:
https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts

**Comment by happychriss** [comment]
@CamJN : Thank you for clarification. Actually my Linux is amd64 and it worked after adding amd64 as below in sources.list. Not sure, why this is needed in my case, not related to passenger :-) All is working nicely now.
`deb [arch=amd64] https://oss-binaries.phusionpassenger.com/apt/passenger focal main`

**Comment by ghost** [comment]
Same issue here.
```
$ cat /etc/apt/sources.list.d/passenger.list
deb https://oss-binaries.phusionpassenger.com/apt/passenger focal main

$ sudo sudo apt-get install -y libnginx-mod-http-passenger
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (< 1.17.11) but 1.18.0-0ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Is there any workaround?

Thanks.

**Comment by CamJN** [comment]
https://github.com/phusion/passenger/issues/2291

**Comment by zsid** [comment]
I am having the same problem and I am getting
```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://oss-binaries.phusionpassenger.com/apt/passenger focal InRelease' doesn't support architecture 'i386'
```
I have checked my `/etc/apt/sources.list.d/passenger.list` and it has the correct text `deb https://oss-binaries.phusionpassenger.com/apt/passenger focal main`. When I run `apt update` I am getting the above error.

I am using `Ubuntu 20.4`. Is there a resolution?

**Comment by CamJN** [comment]
@zsid https://github.com/phusion/passenger/issues/2263#issuecomment-643644412

**Comment by alexventuraio** [comment]
> @davidfilip Make sure your `cat /etc/apt/sources.list.d/passenger.list` looks like this (with focal, not bionic):
> 
> ```
> deb https://oss-binaries.phusionpassenger.com/apt/passenger focal main
> ```
> 
> and then run `apt update`
> 
> It looks like [the docs](https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/node/nginx/) show the correct instructions, so you might have accidentally selected the bionic instructions or had it left over from a previous install.

I do confirm it works with Ubuntu 20.04!
Thanks 👍🏻

**Comment by cbrhex** [comment]
# Install our PGP key and add HTTPS support for APT
sudo apt-get install -y dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt-get install -y apt-transport-https ca-certificates

# Add our APT repository
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger focal main > /etc/apt/sources.list.d/passenger.list'
sudo apt-get update

# Install Passenger + Nginx module
sudo apt-get install -y libnginx-mod-http-passenger
