### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ashrafalzyoud** [phusion/passenger#2264]
redmine@172:/etc/nginx/conf.d$ passenger start -
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: the configuration file nginx.conf syntax is ok
    nginx: [emerg] open() "/etc/nginx/conf.d/passenger.3000.pid" failed (13: Permission denied)
    nginx: configuration file nginx.conf test failed

This probably means that you have found a bug in Phusion Passenger Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues

In the bug report, please include this error message, as well as the contents of the file /tmp/passenger-standalone-1fgw9og.log

**Comment by CamJN** [comment]
You should run `passenger start` from in your app's directory if you want to use passenger standalone, otherwise if you want to use nginx then you do not need to use the `passenger start` command, as nginx will start it for you.
