### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nraju-nyros** [phusion/passenger#2266]
Not install passenger ! What the solution ?
sudo apt-get install -y libnginx-mod-http-passenger

Error
The following packages have unmet dependencies:
libnginx-mod-http-passenger : Depends: passenger (= 1:6.0.4-1~bionic1) but it is not going to be installed
Depends: nginx-common (>= 1.14.0-0ubuntu1.6) but 1.10.3-0ubuntu0.16.04.5 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by CamJN** [comment]
`nginx-common 1.10.3-0ubuntu0.16.04.5` is a Xenial package: https://launchpad.net/ubuntu/+source/nginx/1.10.3-0ubuntu0.16.04.5 you are trying to install a bionic package of passenger. That won't work. Choose ubuntu xenial from the dropdown on this page for instructions: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/nginx/
