### ISSUE TITLE
Centos-8 yum installation ruby scripts unable to require phusion_passenger.rb

### ISSUE THREAD

**Issue by sanichi** [phusion/passenger#2269]
## Issue report

After installing passenger via **yum** on **Centos-8**, the ruby scripts (passenger, passenger-config, passenger-status, passenger-memory-status) aren't working.

**Question 1: What is the problem?**

    $ cat /etc/centos-release # CentOS Linux release 8.1.1911 (Core)
    $ sudo yum install passenger
    $ passenger-status # ... cannot load such file -- phusion_passenger (LoadError)

I think `phusion_passenger.rb` can't be loaded because `LOAD_PATH` (set in the scripts) is wrong.

    $ sudo find / -name phusion_passenger.rb
    /usr/share/passenger/phusion_passenger.rb
    $ grep -B5 phusion_passenger `which passenger-status`
    $LOAD_PATH.unshift("#{source_root}/src/ruby_supportlib")
    begin
        require 'rubygems'
    rescue LoadError
    end
    require 'phusion_passenger'
    $ sudo find / -name ruby_supportlib # nothing

**Question 2: Passenger version and integration mode**:

open source 6.0.4

**Question 3: OS or Linux distro, platform (including version)**:

Centos 8, x86_64

**Question 4: Passenger installation method**:

YUM repo.

**Question 5: Your app's programming language?**

Not relevant.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No.

**Question 7: Anything else about your setup that we should know?**

    $ yum info passenger
    Installed Packages
    Name         : passenger
    Version      : 6.0.4
    Release      : 2.el8
    Architecture : x86_64
    Size         : 7.5 M
    Source       : passenger-6.0.4-2.el8.src.rpm

Also, hand editing the scripts and replacing:

    require 'phusion_passenger'

with

    require '/usr/share/passenger/phusion_passenger'

fixed them.

**Comment by CamJN** [comment]
We haven't released Passenger for centos 8 yet, I'm not sure what repo you are referring to.

**Comment by sanichi** [comment]
https://centos.pkgs.org/8/epel-x86_64/passenger-6.0.4-2.el8.x86_64.rpm.html

**Comment by CamJN** [comment]
That repo is not maintained by us, so we cannot vouch for its contents. We're working on a CentOS 8 package which will be available from our repos when we are done.
