### ISSUE TITLE
passenger-status error on Debian Strech + Apache2

### ISSUE THREAD

**Issue by carlosbustillordguez** [phusion/passenger#2270]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?

```sh
passenger-status
Version : 6.0.4
Date    : 2020-04-15 13:16:16 -0400
Instance: ToDAjPoS (Apache/2.4.25 (Debian) Phusion_Passenger/6.0.4)

----------- General information -----------
Max pool size : 6
App groups    : 0
Processes     : 0
Requests in top-level queue : 0
```

- What is the actual behavior?

```sh
passenger-status
ERROR: Phusion Passenger doesn't seem to be running. If you are sure that it is running, then the causes of this problem could be:

1. You customized the instance registry directory using Apache's PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir option, or Phusion Passenger Standalone's --instance-registry-dir command line argument. If so, please set the environment variable PASSENGER_INSTANCE_REGISTRY_DIR to that directory and run passenger-status again.
2. The instance directory has been removed by an operating system background service. Please set a different instance registry directory using Apache's PassengerInstanceRegistryDir option, Nginx's passenger_instance_registry_dir option, or Phusion Passenger Standalone's --instance-registry-dir command line argument.
```

- How can we reproduce it? 

After installing Passenger + Apache2 following the official documentation, when I run `passenger-status` fails... but `passenger-memory-stats` works fine.

I noted if Apache2 service has `PrivateTmp=true` in the service configuration `passenger-status` fails, but changing to `PrivateTmp=false`, then reloading the systemctl daemon config and restarting the apache2 service can fix the issue.

Is possible to run `passenger-status` alone with `PrivateTmp=true`.

**Question 2: Passenger version and integration mode**:

Your answer:
- Apache/2.4.25 (Debian) Phusion_Passenger/6.0.4

**Question 3: OS or Linux distro, platform (including version)**:

Your answer:
- Debian GNU/Linux 9.12 (stretch) x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer:
- Ruby 2.3.3p222

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer:
- No.

**Question 7: Anything else about your setup that we should know?**

Your answer:

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by CamJN** [comment]
This is the result of systemd giving apache a private tmp dir into which passenger is putting its instance registry. You need to tell the `passenger-status` command where the instance registry is with the `PASSENGER_INSTANCE_REGISTRY_DIR` env var. This can be quite difficult if you leave the default value for the instance registry config value as according to other bug reports systemd does not let you find this directory even as root, however if you set the `PassengerInstanceRegistryDir` config option in your apache config, then you can set the path to somewhere outside `/tmp` and set the same value in the env var.

**Comment by carlosbustillordguez** [comment]
@CamJN thanks for your quick reply!! Following your recommendations I did:

- Add `PassengerInstanceRegistryDir` to the Apache2 config:

```sh
$ sudo mkdir /var/run/passenger-instreg

$ sudo cat <<EOF >> /etc/apache2/conf-available/sr-custom-configs.conf
PassengerInstanceRegistryDir /var/run/passenger-instreg
EOF

$ sudo ln -s /etc/apache2/conf-available/sr-custom-configs.conf /etc/apache2/conf-enabled/sr-custom-configs.conf

$ sudo systemctl restart apache2
```

- To ensure root temp dir for `PassengerInstanceRegistryDir` is not removed after a system reboot, add the following config to `/etc/tmpfiles.d`:

```sh
$ sudo cat <<EOF > /etc/tmpfiles.d/passenger.conf
D /var/run/passenger-instreg 0755 root root
EOF
```

- Add PASSENGER_INSTANCE_REGISTRY_DIR at the system level:

```sh
$ sudo cat <<EOF >> /etc/environment
export PASSENGER_INSTANCE_REGISTRY_DIR=/var/run/passenger-instreg
EOF
```

Now passenger-status and all relative commands are working fine!!
