### ISSUE TITLE
Make 501/502 responses in InternalUtils configurable

### ISSUE THREAD

**Issue by joankaradimov** [phusion/passenger#2278]
## Issue report

**Question 1: What is the problem?**

This is a feature request.

I have several APIs exposed via a rails app - REST/GQL/etc. Nothing too fancy. They all render JSON responses. Under certain conditions passenger renders 502 with the response body `<h2>Incomplete response received from application</h2>`. And it's natural that sometimes it does.

However, this creates an inconsistency - a client requests JSON, but gets HTML response. The clients for these APIs can sometimes be blackbox libraries. And even worse - they might be outside my organization. So ideally I would want to consistently send JSON responses to the clients; e.g.:
```json
{"error": "Incomplete response received from application"}
```

However, these responses are hard-coded:
https://github.com/phusion/passenger/blob/b30bdbe66b3f41d108f160e22778549ef82184d3/src/agent/Core/Controller/InternalUtils.cpp#L99
https://github.com/phusion/passenger/blob/b30bdbe66b3f41d108f160e22778549ef82184d3/src/agent/Core/Controller/InternalUtils.cpp#L110
https://github.com/phusion/passenger/blob/b30bdbe66b3f41d108f160e22778549ef82184d3/src/agent/Core/Controller/InternalUtils.cpp#L139

Would it be possible to expose a way to configure these strings? Maybe based on a regex that matches the path in the request. Or maybe based on the `Accept` header.

**Question 2: Passenger version and integration mode**:
Your answer: N/A

**Question 3: OS or Linux distro, platform (including version)**:
Your answer: N/A

**Question 4: Passenger installation method**:
Your answer: N/A

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer: N/A

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer: N/A

**Question 7: Anything else about your setup that we should know?**
Your answer: N/A

**Comment by CamJN** [comment]
thanks for the suggestion
