### ISSUE TITLE
Passenger reloads Django application on every request

### ISSUE THREAD

**Issue by eeintech** [phusion/passenger#2286]
## Issue report

**Question 1: What is the problem?**
Looking into the passenger application log (`passenger.XXXX.log`) every request is reloading my Django application from scratch.
Normally, a new request would appear like below:
```[25/Jun/2020 14:49:03] "GET /index/ HTTP/1.1" 200 17955```
But instead the log shows:
```
App 93849 output: /usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 93849 output:   import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 93849 output: App running in DEBUG mode
App 93849 output: ...
```
Which is the output for when the application is first loaded.

Here is the content of my `Passengerfile.json` (replaced sensitive information):
```
{
  // Tell Passenger that this is a Python app.
  // Replace "passenger_wsgi.py" with your app's WSGI entry point file.
  "app_type": "wsgi",
  "startup_file": "/home/user/application/passenger_wsgi.py",
  // Run the app in a production environment. The default value is "development".
  "environment": "production",
  // Run Passenger on port 80, the standard HTTP port.
  "port": 80,
  // Tell Passenger to daemonize into the background.
  "daemonize": true,
  // Tell Passenger to run the app as the given user. Only has effect
  // if Passenger was started with root privileges.
  "user": "user",
  // CUSTOM
  "python": "/home/user/application/venv/bin/python",
  "port": 3001,
  "pid_file": "/home/user/application/passenger/passenger.3001.pid",
  "log_file": "/home/user/application/passenger/passenger.3001.log"
}
```

Could you please help me understand why is the application reloading/restarting on every request? How can I prevent it?
Thanks for the help!

**Question 2: Passenger version and integration mode**:
Standalone install:
```
$ passenger --version
Phusion Passenger 6.0.5
```

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 20.04 LTS (Linux 5.4.0-37-generic x86_64)

**Question 4: Passenger installation method**:
[ X] Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Django 3.0.7 with Python 3.8.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Virtual environment only (no container)

**Question 7: Anything else about your setup that we should know?**
There is NO `always_restart.txt` file anywhere on the server (in reference to: https://www.phusionpassenger.com/library/walkthroughs/basics/ruby/reloading_code.html#tmp-always_restart-txt)

**Comment by CamJN** [comment]
Set the [passenger log level](https://www.phusionpassenger.com/docs/references/config_reference/standalone/#--log-level-log_level) to 7 and provide the log, there's not enough info in the log as is to know.

**Comment by eeintech** [comment]
Here is a level 7 log where I loaded 3 different pages (3 different GET request):
[passenger_django_reload_debug_lvl7.log](https://github.com/phusion/passenger/files/4846073/passenger_django_reload_debug_lvl7.log)

**Comment by CamJN** [comment]
My first impression is that your requests contain both of these headers:
`Connection: close`
`Connection: keep-alive`
I wonder if your app and Passenger have different expectations of what they are supposed to do. Passenger is not keep-aliving the connection, perhaps your application shuts down when it's unexpectedly hung up on?

**Comment by eeintech** [comment]
@CamJN Not sure I understand, do you mean the Django application itself is requesting Passenger to shut down?
Running the same application locally with the Django server does not shut it down, I'm not sure why would this happen with Passenger... Any leads?

**Comment by CamJN** [comment]
I mean that the browser is sending conflicting headers to Passenger, and Passenger is only reading the first value: `close`. So, when the application finishes sending a response, Passenger closes the connection to the application. If the application was expecting the connection to stay open due to the `keep-alive` value, perhaps it decides something went wrong and shuts down. Normally the connection staying open is a separate issue to the application being shut down, but if your application sees it as a problem, that could lead to this result. I'm not familiar enough with django to say with certainty.

**Comment by eeintech** [comment]
@CamJN Thanks for the detailed explanation. I read a bit to understand HTTP headers and started looking into the headers for this application. 

Using the developer tools in Chrome, all headers (JSON, JS, CSS, etc.) seem to be set to `Connection: keep-alive` in their response:
![image](https://user-images.githubusercontent.com/4020546/86037321-d090af80-ba04-11ea-806d-ee8a987f160b.png)

However, and as you pointed out, the level 7 log shows:
```\r\nConnection: close\r\nHost: 10.20.1.144:3000\r\nConnection: keep-alive```
Which means passenger gets two value for `Connection` which may confuse Passenger, what do you think?

Now I have **no** idea why would the header response that is printed by Passenger contain `Connection: close` when Chrome does not see it. Do you still think it is on the application side? I'm not sure how to debug further though.

**Comment by eeintech** [comment]
@CamJN Sorry to bug you again with this 😬 
Would you have any more ideas on the Passenger side to help debug this further? Or do you think I should look for support from the Django community?

**Comment by CamJN** [comment]
Unfortunately no, I do not have any further ideas at this time.

**Comment by eeintech** [comment]
@CamJN Ok thanks, I'll close this ticket for now.
