### ISSUE TITLE
nginx is not starting

### ISSUE THREAD

**Issue by ASRdesignHouse** [phusion/passenger#2289]
ginx.service - SYSV: Nginx is an HTTP(S) server, HTTP(S) reverse proxy and IMAP/POP3 proxy server
   Loaded: loaded (/etc/rc.d/init.d/nginx; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-06-27 22:40:37 UTC; 8s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 15424 ExecStart=/etc/rc.d/init.d/nginx start (code=exited, status=1/FAILURE)

**Comment by CamJN** [comment]
@ASRdesignHouse there should be a log file from nginx somewhere like `/var/log/nginx/error.log`, that will have more information.
