### ISSUE TITLE
Ubuntu 20.04 Focal now ships NGINX 1.18.0

### ISSUE THREAD

**Issue by excid3** [phusion/passenger#2291]
Tried installing Passenger this morning got the following error:

```bash
 libnginx-mod-http-passenger : Depends: nginx-common (< 1.17.11) but 1.18.0-0ubuntu1 is to be installed
```

It seems that `nginx-common` in Ubuntu has now been updated to 1.18.0.

```bash
# apt-cache showpkg nginx-common
Package: nginx-common
Versions:
1.18.0-0ubuntu1 (/var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal-updates_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal_main_binary-amd64_Packages
                  MD5: 9e23931d84d07adbee5412aefdad8a90
 Description Language: en
                 File: /var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal_main_i18n_Translation-en
                  MD5: 9e23931d84d07adbee5412aefdad8a90
 Description Language:
                 File: /var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal-updates_main_binary-amd64_Packages
                  MD5: 9e23931d84d07adbee5412aefdad8a90

1.17.10-0ubuntu1 (/var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal_main_binary-amd64_Packages
                  MD5: 9e23931d84d07adbee5412aefdad8a90
 Description Language: en
                 File: /var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal_main_i18n_Translation-en
                  MD5: 9e23931d84d07adbee5412aefdad8a90
 Description Language:
                 File: /var/lib/apt/lists/mirrors.digitalocean.com_ubuntu_dists_focal-updates_main_binary-amd64_Packages
                  MD5: 9e23931d84d07adbee5412aefdad8a90
```

Will you guys be compiling and releasing an updated package against this version soon?

**Comment by CamJN** [comment]
Yes, we will.

**Comment by corneverbruggen** [comment]
In the meantime, is there a known workaround to get nginx and passenger installed on Ubuntu 20.04?

**Comment by excid3** [comment]
@corneverbruggen Yeah, specifically install the old version of nginx.

I'm using nginx-extras so I have to specify quite a few packages.

```bash
sudo apt install libnginx-mod-http-passenger nginx-extras=1.17.10-0ubuntu1 libnginx-mod-http-auth-pam=1.17.10-0ubuntu1 libnginx-mod-http-cache-purge=1.17.10-0ubuntu1 libnginx-mod-http-dav-ext=1.17.10-0ubuntu1 libnginx-mod-http-echo=1.17.10-0ubuntu1 libnginx-mod-http-fancyindex=1.17.10-0ubuntu1 libnginx-mod-http-geoip=1.17.10-0ubuntu1 libnginx-mod-http-geoip2=1.17.10-0ubuntu1 libnginx-mod-http-headers-more-filter=1.17.10-0ubuntu1 libnginx-mod-http-image-filter=1.17.10-0ubuntu1 libnginx-mod-http-lua=1.17.10-0ubuntu1 libnginx-mod-http-perl=1.17.10-0ubuntu1 libnginx-mod-http-subs-filter=1.17.10-0ubuntu1 libnginx-mod-http-uploadprogress=1.17.10-0ubuntu1 libnginx-mod-http-upstream-fair=1.17.10-0ubuntu1 libnginx-mod-http-xslt-filter=1.17.10-0ubuntu1 libnginx-mod-mail=1.17.10-0ubuntu1 libnginx-mod-nchan=1.17.10-0ubuntu1 libnginx-mod-stream=1.17.10-0ubuntu1 nginx-common=1.17.10-0ubuntu1 libnginx-mod-http-ndk=1.17.10-0ubuntu1
```

**Comment by corneverbruggen** [comment]
Thanks, @excid3

**Comment by raphaelc0elh0** [comment]
Having the same problem here :(
Any updates yet?

**Comment by CamJN** [comment]
6.0.6 released, with nginx 1.18.0 compat.

**Comment by Procuria** [comment]
<img width="674" alt="2020-07-29_23h56_38" src="https://user-images.githubusercontent.com/37988494/88858058-b4488400-d1f7-11ea-95b3-b0cf06e10adc.png">
 
Hello, sorry for opening this again.

I'm on Ubuntu 20.04.1 LTS and using the NGINX-Repos (not the Ubuntu ones). As you can see in the screenshot, I'm on NGINX 1.18.0 and encounter the same problem as described above. I triple checked my passenger.list and I am on focal there as well. Would you be so kind to point me the direction ?

**Comment by CamJN** [comment]
@Procuria yup: If you want to use our packaged Nginx module, you must use your distro's provided Nginx package. Since you have the repo provided by NGINX setup, you will instead need to compile a dynamic module compatible with that Nginx. Here are instructions to get you started: https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#dynamic-module

**Comment by Procuria** [comment]
@CamJN thank you very much for your fast, kind, detailed and helpful reply. It opens the possibilty to learn something new, which I like very much. I'd say case closed :)
