### ISSUE TITLE
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: , HTTP_UPGRADE: )

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [phusion/passenger#2292]
Hello, I'm using passenger 6.0.5 with nginx and i'm trying to enable ActionCable with it, I've added 
```
### INSERT THIS!!! ###

    location /cable {
        passenger_app_group_name YOUR_APP_NAME_HERE_action_cable;
        passenger_force_max_concurrent_requests_per_process 0;
    }
```

to my server block but i keep getting the error `Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: , HTTP_UPGRADE: )`

**Comment by CamJN** [comment]
The error looks like the header got split somehow, note the comma before `HTTP_UPGRADE` and the colon afterwards. Can you check the headers in your browser to see if they are correct?

**Comment by AhmedAliIbrahim** [comment]
I fixed it by configuring nginx as below

```
upstream socket_server {
    server <your_ip>:<your_port>;
  }

  location /cable {
     proxy_pass http://socket_server;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
  }
```
