### ISSUE TITLE
Disable PID in logs for Builtin engine

### ISSUE THREAD

**Issue by bryantcj52** [phusion/passenger#2293]
References:
https://github.com/phusion/passenger/issues/1915
https://github.com/phusion/passenger/pull/2176

It seems this feature was added for apache and niginx but it does not work for the builtin engine:
`passenger start --disable-log-prefix
Could not start the server engine:
ERROR: unrecognized argument --disable-log-prefix. Please type '/usr/lib64/passenger/support-binaries/PassengerAgent watchdog --help' for usage.`

It doesn't work in the Passengerfile.json either.

passenger --version
Phusion Passenger 6.0.6

**Comment by BretFisher** [comment]
The [documentation](https://www.phusionpassenger.com/docs/references/config_reference/standalone/#--disable-log-prefix-disable_log_prefix) says this works for `PASSENGER_ENGINE=builtin` but it doesn't. Had to switch to `nginx` to get it working.
