### ISSUE TITLE
Does Passenger work with libcurl4?

### ISSUE THREAD

**Issue by skillmatic-co** [phusion/passenger#2295]
On my server, I have multiple sites. Another site of mine uses libcurl4. It seems when I install libcurl4, Passenger breaks. And when I install libcurl3, my other site that uses libcurl4 breaks.

Can Passenger use libcurl4?

**Comment by skillmatic-co** [comment]
Here is what I get when I try to install Passenger on Ubuntu 18.04:

```
sudo apt-get install passenger
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcurl3 passenger-dev
The following packages will be REMOVED:
  libcurl4
The following NEW packages will be installed:
  libcurl3 passenger passenger-dev
0 upgraded, 3 newly installed, 1 to remove and 74 not upgraded.
Need to get 6194 kB of archives.
After this operation, 46.5 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```
Does open source Passenger not work with libcurl4?

**Comment by CamJN** [comment]
Passenger can use libcurl4, however it has to be linked against that library when it is built. The deb package we provide for Bionic is linked against libcurl3. You can build Passenger yourself to link against your preferred libcurl version.

**Comment by skillmatic-co** [comment]
@CamJN Is there any documentation on how to do that?

**Comment by CamJN** [comment]
There are, in order to point you to the correct directions, can you tell me what your desired setup looks like? ie is it integrated with either apache or nginx, is it a .deb you can install on other servers, etc.

**Comment by skillmatic-co** [comment]
@CamJN Digital Ocean VPS running Ubuntu 18.04 and Apache.

**Comment by CamJN** [comment]
Huh, in testing the instructions I was going to send you I found that our Passenger package does not depend on libcurl4 on Bionic anymore. What repo are you using and is it up to date? The instructions here: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/apache/ result in libcurl4 and not libcurl3 installed in my fresh bionic vm.

**Comment by skillmatic-co** [comment]
`cat /etc/apt/sources.list.d/passenger.list` returns:

`deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main`

**Comment by CamJN** [comment]
You need to update trusty to bionic, since that's your OS.

**Comment by skillmatic-co** [comment]
That was it, thank you!
