### ISSUE TITLE
passenger-config deployment user lacks permissions to clean-up /tmp files

### ISSUE THREAD

**Issue by mzagaja** [phusion/passenger#2298]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
When running `passenger-config restart app /var/www/XXX --ignore-app-not-running` as an app deployment user, that user should be able to cleanup relevant/related files in `/tmp`.

- What is the actual behavior?
```sh
vote@parkville:/var/www/vote/releases/20200719230105$ passenger-config restart-app /var/www/vote --ignore-app-not-running
*** Cleaning stale instance directory /tmp/passenger.w9hzzGP
    Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.w9hzzGP/.
*** Cleaning stale instance directory /tmp/passenger.drY9c7c
    Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.drY9c7c/.
*** Cleaning stale instance directory /tmp/passenger.n2Rim69
    Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.n2Rim69/.
*** Cleaning stale instance directory /tmp/passenger.0VCITNx
    Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.0VCITNx/.
*** Cleaning stale instance directory /tmp/passenger.OLgLWek
    Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.OLgLWek/.
```
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine)
This occurs on Ubuntu 18.04.5 lts using nginx and passenger where each rails application has its own otherwise unprivileged deployment user.

**Question 4: Passenger installation method**:

Your answer:
- [X] Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.7.1, RVM, Rails 6.0.0, Capistrano 3.

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Comment by CamJN** [comment]
This is expected behaviour, documented here: https://www.phusionpassenger.com/docs/advanced_guides/troubleshooting/apache/restart_app.html#security Passenger's core process is run as root when started by Nginx, so `passenger-config restart-app` must be run as root as well.

**Comment by mzagaja** [comment]
Ah I see what you're saying, and appreciate the pointer. I would humbly suggest adding a copy or link of that section to [sandboxing apps with Unix user accounts (nginx)](https://www.phusionpassenger.com/docs/advanced_guides/deployment_and_scaling/nginx/user_sandboxing.html#caveats-troubleshooting), potentially with a sentence about `/tmp` permissions, so that this is more easily discoverable to other nginx users as well as Apache users.
