### ISSUE TITLE
passenger cpanel deploy flask project 404 not found

### ISSUE THREAD

**Issue by pocupine** [phusion/passenger#2299]
Sorry I am a newbie on flask. I was trying to find some good tutorials but all samples online were just simple hello world which didn't help.
I am using cpanel to set up a python app. I don't have root access. Using the "setup python apps" function creates an app folder, a virtualenv and passenger_wsgi.py automatically. I then SSH into my account and pip install -r requirements.txt. The project structure is like below:

microblog
 ---public(folder)
 ---tem(folder)
 ---app(folder)
 --------templates(folder)
 --------------index.html
 --------------login.html
 --------__init__.py
 --------forms.py
 --------models.py
 --------routes.py
 ---microblog.py
 ---config.py
 ---passenger_wsgi.py

I followed some tutorials online like https://blog.ouseful.info/2016/09/17/creating-a-simple-python-flask-app-running-on-reclaim-hosting/ to modify the passenger_wsgi.py to:
from app import application

The index.html showed correctly but any links on the front page returns 404 not found error. I tested it previously on my windows without any problem but the links are dead after deploy on Linux server(I was think OS difference might be the problem but can't find any info online).I am wondering what have I done wrong? Thanks.

Regards Clement

**Comment by CamJN** [comment]
You'll be better off asking for help on stackoverflow, this bug tracker is for reporting bugs in Passenger.
