### ISSUE TITLE
Running Passenger without /proc

### ISSUE THREAD

**Issue by domelek** [phusion/passenger#2300]
Hi guys,
I'm trying to run Passenger in standalone mode for node.js apps. My environment is a custom lxc container with no /proc filesystem mounted (and I don't want to change that). Passenger starts inside the container and runs my app, but it floods stdout with the following error:
`Error, do this: mount -t proc proc /proc
[ W 2020-08-21 17:13:00.0129 36/T3 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: The 'ps' command failed
  Backtrace:
     in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:142)
     in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)`

Is it possible to run Passenger without the /proc? Are the /proc informations needed for any core related tasks or only for statistical / monitoring purposes? Does the Apache module needs the /proc too?

Passenger v. 6.0.6

**Comment by CamJN** [comment]
For node apps, Passenger only needs `ps` for statistical & analytics monitoring, however there is no way to turn that off ATM.

**Comment by domelek** [comment]
Thanks. Finally I mounted procfs with lxcfs and apparmor to hide unnecesary files.
