### ISSUE TITLE
1019001 -> 1019002 Update Version Issue in nginx Module

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2301]
**Are you sure this is a bug in Passenger?**

Yes

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
Update to ngx_http_passenger_module.so 1019002 throws error:

    nginx: [emerg] module "/usr/local/opt/passenger/libexec/modules/ngx_http_passenger_module.so" version 1019001 instead of 1019002 in /usr/local/etc/nginx/nginx.conf:5

    nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed

It is expected to work and not throw version errors. 

You can replicate it by installing it and seeing the error.  I updated 1019001 to 1019002 and the module is now throwing an error. 

`Mac OS El Capitan`.  `Passenger 6.0.6`, HEAD

**Question 2: Passenger version and integration mode**:

passenger: stable 6.0.6, HEAD

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Mac OS El Capitan

**Question 4: Passenger installation method**:
OS X Homebrew installation

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.7.0

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No

**Question 7: Anything else about your setup that we should know?**

Not sure what to say.  Nothing notable that I would expect.

**Comment by CamJN** [comment]
Which nginx? Homebrew rebuilds passenger against every release of nginx, so if you use the latest nginx and passenger they should be compatible.

**Comment by daBee** [comment]
`nginx version: nginx/1.19.2`

For some reason the error has gone away.  I reinstalled `nginx` which might have fixed it.
