### ISSUE TITLE
Missing modules error when starting passenger.

### ISSUE THREAD

**Issue by DimitarDevP** [phusion/passenger#2311]
I am using the `passenger` to deploy a `Flask` REST API on an `apache` server.

Here is my `Apache` conf file:

```
<VirtualHost *:80>
    ServerName demo.app.com

    DocumentRoot /var/www/demo.app.com/backend # Backend is my venv
    PassengerAppRoot /var/www/demo.app.com/backend/public # Public is where my code lives

    PassengerPython /usr/bin/python3.8
    PassengerAppType wsgi
    PassengerStartupFile passenger_wsgi.py

    <Directory /var/www/demo.worxmanager.com/backend>
        Allow from all
        Options -MultiViews
    </Directory>
</VirtualHost>
```

So I go inside the backend folder and execute the following commands:
```
. ./bin/activate
pip3 install -r ./requirements.txt
```

Everything installs successfully. I go inside my `public` folder, and inside app.py i write the following code: 

```
from flask import Flask
#I have more imports and routes, but didn't think they are relevant to my error.

@app.route('/api/user/register', methods=['POST'])
def register():
    return user.register(request)

if __name__ == '__main__':
    app.run()
```

And finally, here is my `passenger_wsgi.py` file:

`from app import app as application`

When I try to run it or go to demo.app.com, I get the following error:

```
App 12676 output: /usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 12676 output:   import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
App 12676 output: Traceback (most recent call last):
App 12676 output:   File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
App 12676 output:     app_module = load_app()
App 12676 output:   File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
App 12676 output:     return imp.load_source('passenger_wsgi', startup_file)
App 12676 output:   File "/usr/lib/python3.8/imp.py", line 171, in load_source
App 12676 output:     module = _load(spec)
App 12676 output:   File "<frozen importlib._bootstrap>", line 702, in _load
App 12676 output:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
App 12676 output:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
App 12676 output:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
App 12676 output:   File "/var/www/demo.app.com/backend/public/passenger_wsgi.py", line 1, in <module>
App 12676 output:     from app import app as application
App 12676 output:   File "/var/www/demo.app.com/backend/public/app.py", line 1, in <module>
App 12676 output:     from Flabstraction.connect import *
App 12676 output:   File "/var/www/demo.app.com/backend/public/Flabstraction/connect.py", line 1, in <module>
App 12676 output:     from Flabstraction.Flabstraction import FlaskCFG, Pysqlalchemy
App 12676 output:   File "/var/www/demo.app.com/backend/public/Flabstraction/Flabstraction.py", line 2, in <module>
App 12676 output:     from flask import Flask
App 12676 output: ModuleNotFoundError: No module named 'flask'
[ E 2020-09-25 12:51:05.3383 12637/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/demo.app.com/backend/public: The application process exited prematurely.
  Error ID: 3611ba4d
  Error details saved to: /tmp/passenger-error-6RDF9C.html

[ E 2020-09-25 12:51:05.3535 12637/T9 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 3611ba4d. Please see earlier logs for details about the error.
```
Which is weird because I have installed all the requirements on both the venv and the system itself.

**Comment by DimitarDevP** [comment]
I solved it. 

Make sure that you do not have multiple python versions installed.

I had installed python 2.x, 3.6 and 3.8 in the system, and I had specified with `PassengerPython` that Passenger should use 3.8. However, the python pip with which I had installed Flask was 3.6. 

So I changed `PassengerPython` from 3.8 to 3.6 and now it works fine.

I am still using a `venv`, so if anyone knows how to use the python site-packages from that `venv`, please let me know since that would make it easier to move to another machine.

**Comment by residentcode** [comment]
1 year now still no answers no fix I have the same issue ,
/opt/cpanel/ea-ruby27/root/usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
App 17075 output:   import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno

I tried cloudlinux and cpanel and cpanel without cloudlinux , python3.8 python3.9 I can't use older ver.
tried Flask, django 
tried to have only 1 ver of python 
all same issue so 100% is Passenger problem and did not even care about it.
Wierd.

**Comment by odehDanOps** [comment]
Error still persist 

/usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
Traceback (most recent call last):
  File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
    app_module = load_app()
  File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
    return imp.load_source('passenger_wsgi', startup_file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/api/folder/passenger_wsgi.py", line 6, in <module>
    from run import app as application
  File "/api/folder/run.py", line 4, in <module>
    from app import create_app
  File "/api/folder/app/__init__.py", line 73, in <module>
    from flask_seeder import FlaskSeeder
ModuleNotFoundError: No module named 'flask_seeder'

What is the possible fix?
