### ISSUE TITLE
passenger 6.0.6 +ubuntu 20.04 + ruby 2.6.6

### ISSUE THREAD

**Issue by ashrafalzyoud** [phusion/passenger#2312]
i have redmine its last relase support ruby (2.4-2.6)
when i install passenger  in this page
https://www.phusionpassenger.com/docs/tutorials/installation/meteor/
chose ubuntu 20.04
its download ruby2.7
this mean in my system have 2 ruby versions ruby 2.7 and rbenv 2.6.6
```
root@172:~# ru
ruby                   run-mailcap            runsv
ruby2.7                run-one                runsvchdir
```
**what i do to install passenger with ubuntu 20.4 with ruby 2.6.6**????
```
     Remove the following packages:                               
1)     libnginx-mod-http-passenger [1:6.0.6-1~focal1 (focal, now)]
2)     passenger [1:6.0.6-1~focal1 (focal, now)]                  
3)     passenger-dev [1:6.0.6-1~focal1 (focal, now)]              
4)     ruby [1:2.7+1 (focal, now)]                                
5)     ruby-rack [2.0.7-2 (focal, now)]                           

     Leave the following dependencies unresolved:                 
6)     passenger recommends passenger-dev (= 1:6.0.6-1~focal1)    
```

**Comment by CamJN** [comment]
If you want to not have the distro provided ruby on your system at all, then you will need to either install Passenger as a gem from your preferred ruby install, or build Passenger from a tarball.
