### ISSUE TITLE
Passenger is not reading RAILS_MASTER_KEY - more question than issue

### ISSUE THREAD

**Issue by imegory** [phusion/passenger#2313]
I started a new Rails project using Rails version 6 and deployed the project to a Ubuntu 20 instance that was installed with the latest NGINX and Passenger (literally yesterday following the Passenger website cookbook). I can also add that I have been using Passenger for the longest time. Now and this time around, Passenger could not start Rails because of a missing RAILS_MASTER_KEY. Eventually, I got it to work by adding "passenger_env_var RAILS_MASTER_KEY key_value”. That said, I am asking whether this is the right way of doing it. And why I have not encountered this issue in the two other Rails 6 projects (deployed to other instances). 

Finally, let me make the comment that I would like to set RAILS_MASTER_KEY value in one place. To me it looks like, NGINX user is the issue, but I am not sure. Can someone please help shed light on this issue? I am not sure at the moment if this is an NGINX or passenger issue or question. Thanks.

**Comment by CamJN** [comment]
So there are several places that you could set that env var. And which is appropriate for your setup is something only you can decide. However some choices are: 

In the nginx config with passenger_env_var, just like you already do.
In the bashrc file of the app user that runs your app
In the /etc/default/nginx file (keep in mind, nginx filters out most env vars and you need to whitelist them: http://wiki.nginx.org/CoreModule#env)
Putting the master.key file in the config dir.

As for why you didn't encounter the issue with the other projects, I could only speculate. But I'd look for config differences between the projects. Perhaps they were migrated from an older version of rails and are still using secrets.yml or maybe they accidentally had master.key committed, or your deploy script put the file in place for those other projects.
