### ISSUE TITLE
PassengerAgent Asking for Approval

### ISSUE THREAD

**Issue by msuzoagu** [phusion/passenger#2322]
**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
Using the passenger gem in rails app. I run `passenger start` and I keep get a prompt to enter my password because: 
```
PassengerAgent wants to sign using key "Phusion Passenger Open Source" in your keychain. 

The authenticity of "PassengerAgent" cannot be verified. To allow this, enter "login" keychain password
```

Since I can't find any documentation for this behavior after reading through [here](https://github.com/phusion/passenger/blob/e0c47b3ee85612d3b315bba71dc4e487ce38a476/src/ruby_supportlib/phusion_passenger.rb) or anywhere on the internet I click deny and terminal displays: 
```
[ E 2020-11-22 19:19:19.7259 10672/T5 age/Cor/SecurityUpdateChecker.h:507 ]: Security update check failed: SSL connect error while connecting to https://securitycheck.phusionpassenger.com/v1/check.json (if this error persists check your connection security or try upgrading Passenger) (next check in 24 hours)
[ E 2020-11-22 19:19:19.7697 10672/T5 Sec/Crypto.cpp:990 ]: Removing Passenger private key from keychain failed: Write permissions error.. Please remove the private key from the certificate labeled Phusion Passenger Open Source in your keychain.
```

- What is the expected behavior?
   - running `passenger start` shouldn't prompt for approval. 
   - Approvals like this such be documented somewhere easily searchable so that folks like me can 
figure out what is happening and why approval is need. 

**Question 2: Passenger version and integration mode**:
- Phusion Passenger 6.0.7 (opensource)

**Question 3: OS or Linux distro, platform (including version)**:
- MacBook Pro (10.15.7)

**Question 4: Passenger installation method**:
[x ] RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: ruby 2.6.3p62, RVM, Rails 6.0.3.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- NO

**Question 7: Anything else about your setup that we should know?**
 - NO

**Comment by CamJN** [comment]
Our macOS binaries are built on a High Sierra Mac, one quirk of that OS is that early versions used the secure transport backend for curl, which doesn't support client certificates, which are used for the security update check. I tried to work around this by adding the client cert to the keychain but that sometimes causes the auto prompts you see. While they did revert to OpenSSL at some point in the high Sierra life cycle, for us to support high Sierra we can't assume that's available. If you install from homebrew or build from source, you should get a version that doesn't use the keychain.

**Comment by msuzoagu** [comment]
@CamJN thanks for providing feedback on this; much appreciated :)
