### ISSUE TITLE
Passenger Core eats up 100% CPU

### ISSUE THREAD

**Issue by tfl** [phusion/passenger#2325]
Phusion Passenger 6.0.7 installed via passenger-install-apache2-module
Apache Apache/2.4.46
Archlinux

From time to time (few seconds, to minutes) Passenger core is spawning a new process and this process eats up 100% CPU.
If I kill the process I see something like this in my apache error log:
```
[ W 2020-12-09 16:17:17.1704 823/T3 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: The 'ps' command failed
Backtrace:
in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:142)
in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)
```

s'tracing the process shows flooding `close(957779812) = -1 EBADF (Bad file descriptor)` messages

This behaviour started a few days ago. I run two simple Sinatra apps where I keep all modules up to date with bundler.

Here is my passenger config:
```
LoadModule passenger_module /srv/ruby/gems/gems/passenger-6.0.7/buildout/apache2/mod_passenger.so
<IfModule mod_passenger.c>
  PassengerRoot /srv/ruby/gems/gems/passenger-6.0.7
  PassengerRuby /srv/ruby/gems/bin/passenger-wrapper.sh
  PassengerPoolIdleTime 0
  PassengerDisableSecurityUpdateCheck on
  RailsEnv production
</IfModule>
```

with the wrapper script as
```
#!/bin/sh
export GEM_HOME=/srv/ruby/gems
export PATH=$PATH:$GEM_HOME/bin
exec "/usr/bin/ruby" "$@"
```

I run this config for three or more years without problems... (with modified version numbers of course)

**Comment by joelchornik** [comment]
Same distro, apache and passenger_version, same issue here.

**Comment by tfl** [comment]
I gave up waiting for a solution and stopped using Passenger a month ago. I now use Puma as my application server and Nginx as proxy in front of it. This gives me the ability to restart each service separately without touching the other one.
