### ISSUE TITLE
Passenger Error while uploading the files

### ISSUE THREAD

**Issue by bharath8281** [phusion/passenger#2327]
**Problem:** Not able to upload the files  
**Expected behavior:** Should be able to upload the files and get 200 responses back. ( Maximum size of the file allowing is 20 MB)
**Actual behavior:** We are getting passenger errors while uploading the files. 

Technical Details
**Passenger Version:** 4.0.59
**Apache Version :** 2.4.23
**OS :** CentOS Linux release 7.5.1804 (Core)

**Passenger installation method**
RubyGems, no Gemfile

**Programming languages:**
Ruby 2.7.1p83, RVM-1.26.11, Rails 6.0.3.3; Node.js- v12.18.1
I have attached the screenshots for the same error we are getting at the apache level.

![image (13)](https://user-images.githubusercontent.com/53555636/102453668-ad18fa00-4062-11eb-81b2-a6828c43c0b5.png)

**Comment by CamJN** [comment]
Support for Passenger 4.* is limited to enterprise customers with a support contract.
