### ISSUE TITLE
Fails to build on Ruby 2.7.2 with etc-1.2 (works with etc-1.1)

### ISSUE THREAD

**Issue by svoop** [phusion/passenger#2329]
## Issue

**Question 1: What is the problem?**

`gem install passenger` fails with `undefined symbol: rb_deprecate_constant` on Ruby 2.7.2 when current version 1.2 of the `etc` gem is installed. (Default für this Ruby is 1.1, no problem with that version.)

```
# cat /usr/local/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0-static/passenger-6.0.7/gem_make.out

current directory: /usr/local/lib/ruby/gems/2.7.0/gems/passenger-6.0.7/src/helper-scripts/download_binaries
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r ./siteconf20210104-21174-1bpv7qz.rb extconf.rb
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': /usr/local/lib/ruby/gems/2.7.0/gems/etc-1.2.0/lib/etc.so: undefined symbol: rb_deprecate_constant - /usr/local/lib/ruby/gems/2.7.0/gems/etc-1.2.0/lib/etc.so (LoadError)
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/local/lib/ruby/gems/2.7.0/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger.rb:269:in `infer_install_spec'
	from /usr/local/lib/ruby/gems/2.7.0/gems/passenger-6.0.7/src/ruby_supportlib/phusion_passenger.rb:103:in `locate_directories'
	from extconf.rb:46:in `<main>'
extconf failed, exit code 1
```

**Question 2: Passenger version and integration mode**:

open source 6.0.7 nginx

**Question 3: OS or Linux distro, platform (including version)**:

Gentoo x86_64, kernel 5.4.80

**Question 4: Passenger installation method**:

via Rubygems

## Workaround

Downgrade `etc` to 1.1:

```
gem uninstall etc   # keeps the default etc-1.1
gem install passenger
```

**Comment by CamJN** [comment]
This seems to be an issue with the etc gem itself: https://github.com/ruby/etc/issues/12

**Comment by svoop** [comment]
@CamJN Oh, my bad, I didn't see that from the message. I'll at least check the Issues of the offending Gem next time. 🔭
