### ISSUE TITLE
connect (113: No route to host) Ubuntu Server 20.04.1

### ISSUE THREAD

**Issue by elduglas** [phusion/passenger#2332]
Hi.

Error with host after run command sudo apt update.

Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/focal/InRelease  Could not connect to oss-binaries.phusionpassenger.com:443 (109.107.35.58). - connect (113: No route to host)

https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/apache/install/oss/focal.html

**Comment by CamJN** [comment]
This is almost certainly an issue with your network, as the instructions work here in a fresh focal vm. The DNS lookup worked in your case, so it's likely a routing issue. Should there be a proxy configured?

**Comment by elduglas** [comment]
> This is almost certainly an issue with your network, as the instructions work here in a fresh focal vm. The DNS lookup worked in your case, so it's likely a routing issue. Should there be a proxy configured?

I @CamJN, I'm so sorry, my error was with the line gateway4 at /etc/netplan/01-netcfg.yaml.

Thanks so much!!!
