### ISSUE TITLE
mod_passenger.so: no suitable image found on Apple M1 Mac Mini

### ISSUE THREAD

**Issue by aperfect** [phusion/passenger#2333]
**Question 1: What is the problem?**
I'm attempting to migrate to a new M1 Mac Mini server from an older Intel Mac Mini, setting up clean Apache, Passenger installs through Homebrew. 

After adding passenger.conf to the Apache config, apachectl throws the following error:
`httpd: Syntax error on line 505 of /opt/homebrew/etc/httpd/httpd.conf: Syntax error on line 1 of /opt/homebrew/etc/httpd/extra/passenger.conf: Cannot load /opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so into server: dlopen(/opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so, 10): no suitable image found.  Did find:\n\t/opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so: no matching architecture in universal wrapper\n\t/opt/homebrew/Cellar/passenger/6.0.7_3/libexec/buildout/apache2/mod_passenger.so: no matching architecture in universal wrapper`

**Question 2: Passenger version and integration mode**:
Open source 6.0.7, Apache

**Question 3: OS or Linux distro, platform (including version)**:
macOS 11.1 Big Sur (M1/arm Mac Mini)

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[x] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 2.7.2, rbenv, Rails 5.2.4.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**

**Comment by CamJN** [comment]
What does `file` report for both `mod_passenger.so` and the `httpd` binary? It looks like homebrew may have installed the wrong architecture by accident.

**Comment by aperfect** [comment]
Thanks for the quick reply. Both look like they should be fine for arm64 to me:

```
$ file /opt/homebrew/Cellar/httpd/2.4.46/bin/httpd
/opt/homebrew/Cellar/httpd/2.4.46/bin/httpd: Mach-O 64-bit executable arm64

$ file /opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so
/opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64e]
/opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so (for architecture x86_64):	Mach-O 64-bit bundle x86_64
/opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so (for architecture arm64e):	Mach-O 64-bit bundle arm64e
```

**Comment by CamJN** [comment]
My only concern is that one is `arm64` and the other is `arm64e`, which has more instructions added than base `arm64`. Can you check some arbitrary system binary for which arch is used normally?

**Comment by aperfect** [comment]
Binaries in /usr/sbin generally seem to be arm64e

**Comment by CamJN** [comment]
Ok I just checked and it looks like `arm64e` does need to be used in both the main binary and all libraries or not at all. So either the Apache formula needs to be fixed/rebuilt, or you'll need to use the system Apache.

I'd open an issue in the homebrew repo, but I'm banned from doing so.

**Comment by aperfect** [comment]
OK, thanks for your help, I'll look into that.
