### ISSUE TITLE
Enterprise-Apt Repository "Heavy Load" Errors

### ISSUE THREAD

**Issue by lvangool** [phusion/passenger#2337]
## Issue report

The Phusion Passenger Enterprise apt repo www.phusionpassenger.com/enterprise_apt is having intermittent load issues.
Apart from new installations failing, this is causing all apt update commands to fail too. 

See the below sample error output from `apt update`
```
Err:10 https://www.phusionpassenger.com/enterprise_apt bionic Release
  503  Service Unavailable [IP: xxx.xxx.xxx.xxx 443]
```
This is what I see when visiting the apt repo directly:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/1216012/107689821-3cc4d880-6ca1-11eb-9e7e-ced234286549.png">

Please can someone investigate ASAP?
Many thanks

**Comment by CamJN** [comment]
We are investigating, thanks.

**Comment by CamJN** [comment]
@FooBarWidget

**Comment by CamJN** [comment]
We believe we've identified the cause of the 503s, and have put a mitigation in place. Thanks for the report. Please let us know if anything weird happens again!

**Comment by lvangool** [comment]
Many thanks for the quick turnaround! Yes, will let you know if see any further issues regarding this.
