### ISSUE TITLE
Public key not available for Ubuntu Bionic (same as #2142)

### ISSUE THREAD

**Issue by nicolopez77** [phusion/passenger#2342]
Same as issue #2142

When doing apt-get update:

W: GPG error: https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 561F9B9CAC40B2F7
E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' is not signed.

**Comment by CamJN** [comment]
What did `apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7` output when you ran that?

**Comment by nicolopez77** [comment]
@CamJN that is the workaround I had to use to move forward as the issue was not being solved.

**Comment by CamJN** [comment]
That isn't a workaround, it's the proper process. You need to have run that to get the key in the first place. It's in our instructions for setting up the passenger apt repo.

**Comment by shakerlxxv** [comment]
Please re-open this issue the Passenger instructions for Ubuntu installations are no longer valid as Ubuntu has deprecated the following command:

    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7

Using this command will result in warnings everytime you subsequently `apt-get update`. It would be good to update your instructions for more current versions of Ubuntu.  I'm running Ubuntu 22.04.4 LTS

**Comment by CamJN** [comment]
The instructions are updated for the new method. eg:

```
curl https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/phusion.gpg >/dev/null

# Add our APT repository
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger mantic main > /etc/apt/sources.list.d/passenger.list'
sudo apt-get update
```
