### ISSUE TITLE
Passenger on apache expects nginx.conf?

### ISSUE THREAD

**Issue by tsirilson** [phusion/passenger#2344]
I followed [the tutorial](https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/apache/oss/install_passenger_main.html) for installing Passenger for Ubuntu 18.04+Apache, everything seems fine until I try to run `passenger start`, when I get this error:

```
*** ERROR: the Nginx configuration that Phusion Passenger Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    nginx: the configuration file nginx.conf syntax is ok
    nginx: [emerg] open() "[redacted]/log/passenger.3000.log" failed (13: Permission denied)
    nginx: configuration file nginx.conf test failed
```

`passenger-config validate-install` only recognizes "Passenger itself" and "Apache", so it verifies that I didn't install some ngnix stuff by accident. 

I also ran `passenger-config about ruby-command` as required, and used the Apache config option in my conf file.

Also, nginx is not installed on my server at all.

**Comment by tsirilson** [comment]
Giving global writing permissions to log/passenger.3000.log avoids this error, but the fact it looks for nginx config is still a bug. Closing for now.

**Comment by CamJN** [comment]
Nowhere in the apache tutorial does it say to run `passenger start`, because that is not how you start passenger with apache. Once you've installed and enabled the apache module, apache starts passenger for you.
