### ISSUE TITLE
An operating system error occurred while preparing to spawn an application process: Cannot lstat("/var/www/myapp/bundle/programs/main.js")

### ISSUE THREAD

**Issue by Shelagh-Lewins** [phusion/passenger#2345]
I have a Meteor app deployed via Passenger under nginx. The app works but I am seeing frequent errors in the logfile and when I run my app update script, the step to restart the app intermittently fails with a similar error.

**Versions**
Ubuntu 20.04.2 LTS (Digital Ocean droplet)
nginx/1.18.0 (Ubuntu)
Phusion Passenger 6.0.7 (open source)
Meteor 2.0

**Question 1: What is the problem?**
The app is running OK, but the logs show repeated errors like this:

```
[ E 2021-03-20 08:07:14.7713 130726/T6 age/Cor/Con/CheckoutSession.cpp:274 ]: [Client 1-285] Cannot checkout session because a spawning error occurred. The identifier of the error is 8771bf24. Please see earlier logs for details about the error.
2021/03/20 08:13:04 [error] 130739#130739: *2594 access forbidden by rule, client: 185.191.171.8, server: myapp.org, request: "GET /robots.txt HTTP/1.1", host: "myapp.org"
[ E 2021-03-20 09:55:18.3724 130726/Tu age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/myapp/bundle/programs: An operating system error occurred while preparing to spawn an application process: Cannot lstat("/var/www/myapp/bundle/programs/main.js"): No such file or directory (errno=2)
  Error ID: 7e481a39
  Error details saved to: /tmp/passenger-error-bey8v6.html
```

I think the "access forbidden by rule" is because of an external probe, which is failing because of the nginx rules in my config - that's fine, that's what I expected. But why is Passenger trying to spawn a process here and why is it failing? When I visit the site, my app seems to be running fine despite these errors; however I assume something must be wrong that should be fixed...

Here's my configuration:

```
server {
    listen 443 ssl http2;
    server_name myapp.org;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /var/www/myapp/bundle/public;

    # Turn on Passenger
    passenger_enabled on;

    # Tell Passenger that your app is a Meteor app
    passenger_app_type node;
    passenger_startup_file main.js;

    # deny all paths by default
    location / {
        deny all;
    }

    # allow main routes
    location = / { }
    ...

}
```

The 'root' setting seems to be magic (symlinks?) because there is no /bundle/public folder in my app, but if I change that setting the app stops working. This is where my startup file lives:

`/var/www/myapp/bundle/main.js`

As well as seeing frequent errors in the log file, I also sometimes (but not always) see similar errors when I run my deployment script which ends with this line:

`passenger-config restart-app --ignore-app-not-running --ignore-passenger-not-running $RESTART_ARGS $APP_DIR/bundle`

Although Passenger fails to restart the app and my app is then down, I can restart it with:

```
sudo service nginx stop
sudo service nginx start
```

which always works.

Again, if my configuration is wrong, how come it works some of the time?

I've read a bunch of bug reports and tutorials and can't work this one out; I assume that if my conf file was wrong, the app wouldn't work at all. I'll be very grateful for any insight into this!

**Comment by CamJN** [comment]
The `root` config options should point to the static files for your site. As a convenience we infer that the app's startup file is likely in the parent directory of the static files. So that's why changing root breaks things for you, because `/var/www/myapp/bundle/public` - `public` + `main.js` = `/var/www/myapp/bundle/programs/main.js`. You can tell passenger more explicitly where your app code is using https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_app_root and then you can set `root` to whatever you like, ideally the path to some static files you'd like served.

I notice that there's an addition of `programs` in the path: `/var/www/myapp/bundle/programs/main.js` which is seeing the error, which doesn't match your config, any ideas what that might be about?

**Comment by Shelagh-Lewins** [comment]
Hi @CamJN I also noticed the addition of `programs` in the path in the error message, and no, I do not have any idea what that is about. I would guess it is connected to the problem but I do not know where it comes from!
I don't think I need to set `passenger_app_root` because my startup file is in the default location, and `sudo service nginx start `always works. But `passenger-config restart-app` usually fails. Something must be different between the two processes?

**Comment by CamJN** [comment]
Can you describe how you package your meteor app? I think I have an idea what has happened.

**Comment by Shelagh-Lewins** [comment]
Thank you!

I based my app update scripts on the tutorial (https://www.phusionpassenger.com/docs/advanced_guides/deployment_and_scaling/nginx/automating_app_updates/meteor/) but with some updates and loading server IP address from a separate file called .env.

I have found that one one server the script will work perfectly and on another with the same configuration I will see the problem. So I am very confused!

initiate.sh
```
#!/bin/bash
set -e

# use to reference other scripts in the same directory as this one
my_dir=`dirname $0`

# load environment variables: SERVER
. $my_dir/.env

### Configuration ###
APP_DIR=/var/www/myapp
KEYFILE=
REMOTE_SCRIPT_PATH=/tmp/deploy-myapp.sh
WORK_SCRIPT_PATH=.deploy/myserver/work.sh

### Library ###

function run()
{
  echo "Running: $@"
  "$@"
}

### Automation steps ###

if [[ "$KEYFILE" != "" ]]; then
  KEYARG="-i $KEYFILE"
else
  KEYARG=
fi

run meteor build --server-only ../output
mv ../output/*.tar.gz ./package.tar.gz

run scp $KEYARG package.tar.gz $SERVER:$APP_DIR/
run scp $KEYARG $WORK_SCRIPT_PATH $SERVER:$REMOTE_SCRIPT_PATH
echo
echo "---- Running deployment script on remote server ----"
run ssh $KEYARG $SERVER bash $REMOTE_SCRIPT_PATH
```
work.sh
```
#!/bin/bash
set -e

### Configuration ###

APP_DIR=/var/www/myapp
RESTART_ARGS=

### Automation steps ###

set -x

# Extract newly uploaded package
mkdir -p $APP_DIR/tmp
cd $APP_DIR/tmp
tar xzf $APP_DIR/package.tar.gz
rm -f $APP_DIR/package.tar.gz

# Install dependencies
cd $APP_DIR/tmp/bundle/programs/server
npm install --production
npm prune --production

# Copy over persistent files
if [[ -e $APP_DIR/bundle/Passengerfile.json ]]; then
  cp $APP_DIR/bundle/Passengerfile.json $APP_DIR/tmp/bundle/
fi

# Switch directories, restart app
mv $APP_DIR/bundle $APP_DIR/bundle.old
mv $APP_DIR/tmp/bundle $APP_DIR/bundle
passenger-config restart-app --ignore-app-not-running --ignore-passenger-not-running $RESTART_ARGS $APP_DIR/bundle
rm -rf $APP_DIR/bundle.old
```

**Comment by CamJN** [comment]
I just created a test env with a trivial mongo app and passenger. And am not reproducing the issue, which makes me think it's an environment issue. What's in your `Passengerfile.json` and your shell's `env` when you run `passenger-config`?

**Comment by Shelagh-Lewins** [comment]
The .env file on my local machine contains the just the SERVER variable:

```
#!/usr/bin/env bash

export SERVER='myapp@x.x.x.x'
```

I am not sure what you mean by Passengerfile.json? The only json file I'm aware of is package.json. Do you mean the nginx conf file, myapp.conf? The conf file looks like this:

/etc/nginx/sites-enabled/myapp.conf
```
# don't prefix log entries with App PID stdout
passenger_disable_log_prefix on;

# don't show Passenger version
passenger_show_version_in_header off;

passenger_log_level 4;

# keep instances alive instead of respawning
passenger_min_instances 6;

server {
    listen 80;
    server_name myapp.org www.myapp.org;
    return 301 https://myapp.org$request_uri;
}

server {
    listen 443 ssl http2; #https of www*, 301 to right domain.
    server_name www.myapp.org;

    ssl_certificate /etc/letsencrypt/live/myapp.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myapp.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    return 301 https://myapp.org$request_uri;
}

server {
    listen 443 ssl http2;
    server_name myapp.org;

    # Tell Nginx and Passenger where your app's 'public' directory is
    root /var/www/myapp/bundle/public;

    # Turn on Passenger
    passenger_enabled on;

    # Tell Passenger that your app is a Meteor app
    passenger_app_type node;
    passenger_startup_file main.js;

    # number of proxies in front of server so client ip address can be found
    passenger_env_var HTTP_FORWARDED_COUNT 1;

    # Tell your app where MongoDB is
    passenger_env_var MONGO_URL mongodb://localhost:27017/myapp;

    # Tell your app about the oplog
    passenger_env_var MONGO_OPLOG_URL mongodb://localhost:27017/local;

    # Tell your app what its root URL is
    passenger_env_var ROOT_URL 'https://myapp.org/';

    # maintenance mode on / off
    passenger_env_var MAINTENANCE_MODE false;

    ...mail and other credentials

    # deny all paths by default
    location / {
        deny all;
    }

    # allow sockjs
    location /sockjs { }

    # allow main menu routes
    location = / { }
    location = /people { }
    location = /about { }
    ....

    # allow user pages
    location /user { }


    # allow account routes
    location = /login { }
    location = /register { }
    location = /welcome { }
    location = /account { }
    location /verify-email { }
    location = /change-password { }
    location = /forgot-password { }
    location /reset-password { }

    # serve js and css
    location ~* "^/[a-z0-9]{40}\.(css|js)$" {
      root /var/www/myapp/bundle/programs/web.browser;
      access_log off;
      expires max;
    }

    # serve public folder
    location ~ \.(jpg|jpeg|png|gif|mp3|ico|pdf|svg) {
      root /var/www/myapp/bundle/public;
      access_log off;
      expires max;
    }

    # deny unwanted requests
    location ~ (\.php|.aspx|.asp|myadmin) {
      return 404;
    }

    # don't show nginx version
    server_tokens off;

    add_header X-Frame-Options SAMEORIGIN;

    # SSL options are set in /etc/letsencrypt/options-ssl-nginx.conf
    # however they are also in /etc/nginx/nginx.conf for general use

    ssl_certificate /etc/letsencrypt/live/myapp.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myapp.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Comment by CamJN** [comment]
The `Passengerfile.json` that I mentioned is a file you can put in your app to pass configuration to Passenger, usually used by Passenger standalone, but i mentioned it because of this bit in your deploy script:

```
# Copy over persistent files
if [[ -e $APP_DIR/bundle/Passengerfile.json ]]; then
  cp $APP_DIR/bundle/Passengerfile.json $APP_DIR/tmp/bundle/
fi
```

**Comment by Shelagh-Lewins** [comment]
Thanks! I copied that from the tutorial. No, there is no file $APP_DIR/bundle/Passengerfile.json on my server. There is only star.json:

```
{
  "format": "site-archive-pre1",
  "builtBy": "Meteor METEOR@2.0",
  "programs": [
    {
      "name": "web.browser",
      "arch": "web.browser",
      "path": "programs/web.browser/program.json"
    },
    {
      "name": "web.browser.legacy",
      "arch": "web.browser.legacy",
      "path": "programs/web.browser.legacy/program.json"
    },
    {
      "name": "server",
      "arch": "os",
      "path": "programs/server/boot.js"
    }
  ],
  "meteorRelease": "METEOR@2.0",
  "nodeVersion": "12.20.1",
  "npmVersion": "6.14.8",
  "gitCommitHash": "b1aecdb6ed878e1a4d61d2191157845d2960d642"
}
```

If you think it might cause a problem, I can removing that section from the script?

**Comment by CamJN** [comment]
No no, if you don't have such a file, then that part of the script does nothing. Can you run `passenger-status` with your app running? Also can you try adding `passenger_app_root /var/www/myapp/bundle;` to your `/etc/nginx/sites-enabled/myapp.conf` virtual host (`server{}` block), it should be redundant but I wonder, because Passenger seems convinced that the app runs in `/var/www/myapp/bundle/programs`, possibly because meteor changes the `pwd` to that on app-startup.

**Comment by Shelagh-Lewins** [comment]
Running `sudo passenger-status` with my app running gives me this output:

```
*** Cleaning stale instance directory /tmp/passenger.EVU8TNw
*** Cleaning stale instance directory /tmp/passenger.AYxDaLB
*** Cleaning stale instance directory /tmp/passenger.j3lkzui
Version : 6.0.7
Date    : 2021-08-26 09:07:23 +0000
Instance: QRWZRi8r (nginx/1.18.0 Phusion_Passenger/6.0.7)

----------- General information -----------
Max pool size : 6
App groups    : 2
Processes     : 6
Requests in top-level queue : 0

----------- Application groups -----------
/var/www/myapp/bundle (production):
  App root: /var/www/myapp/bundle
  Requests in queue: 0
  * PID: 2317679   Sessions: 4       Processed: 29      Uptime: 9h 6m 17s
    CPU: 0%      Memory  : 352M    Last used: 3m 22s 
  * PID: 2317737   Sessions: 4       Processed: 74      Uptime: 9h 6m 12s
    CPU: 0%      Memory  : 238M    Last used: 51m 17s
  * PID: 2317861   Sessions: 4       Processed: 63      Uptime: 9h 6m 2s
    CPU: 0%      Memory  : 105M    Last used: 17m 1s a
  * PID: 2317919   Sessions: 4       Processed: 64      Uptime: 9h 5m 58s
    CPU: 0%      Memory  : 115M    Last used: 3m 21s 
  * PID: 2317978   Sessions: 4       Processed: 95      Uptime: 9h 5m 54s
    CPU: 0%      Memory  : 178M    Last used: 48m 23s
  * PID: 2318241   Sessions: 4       Processed: 44      Uptime: 8h 59m 10s
    CPU: 0%      Memory  : 79M     Last used: 8m 20s

/var/www/myapp/bundle/programs (production):
  App root: /var/www/myapp/bundle/programs
  Requests in queue: 7

```

**Comment by Shelagh-Lewins** [comment]
I tried try adding `passenger_app_root /var/www/myapp/bundle;` to the` /etc/nginx/sites-enabled/myapp.conf` virtual host (`server{}` block) as you suggested. It seems to have worked! I just ran my deployment script twice without error!
I still don't know why it should be required on one of my servers but not the other, given that as far as I can tell they are identical, running the same versions of everything on the same configuration of droplet. But I'm happy to have a fix - thank you.
Might it be worth adding this configuration line to the Meteor / Passenger tutorial?

FYI, after making that change, `sudo passenger-status` now gives this:

```
Version : 6.0.7
Date    : 2021-08-26 09:39:02 +0000
Instance: taOhQJpx (nginx/1.18.0 Phusion_Passenger/6.0.7)

----------- General information -----------
Max pool size : 6
App groups    : 1
Processes     : 6
Requests in top-level queue : 0

----------- Application groups -----------
/var/www/myapp/bundle (production):
  App root: /var/www/myapp/bundle
  Requests in queue: 0
  * PID: 2337636   Sessions: 5       Processed: 38      Uptime: 4m 32s
    CPU: 4%      Memory  : 197M    Last used: 4m 20s ago
  * PID: 2337707   Sessions: 4       Processed: 23      Uptime: 4m 28s
    CPU: 2%      Memory  : 100M    Last used: 4m 24s ago
  * PID: 2337766   Sessions: 4       Processed: 9       Uptime: 4m 24s
    CPU: 4%      Memory  : 149M    Last used: 4m 20s ago
  * PID: 2337825   Sessions: 2       Processed: 2       Uptime: 4m 20s
    CPU: 2%      Memory  : 122M    Last used: 4m 15s ago
  * PID: 2337885   Sessions: 2       Processed: 4       Uptime: 4m 15s
    CPU: 3%      Memory  : 120M    Last used: 4m 15s ago
  * PID: 2337944   Sessions: 2       Processed: 3       Uptime: 4m 12s
    CPU: 2%      Memory  : 101M    Last used: 3s ago
```

Previously there were two application groups; now there is only the one.

**Comment by CamJN** [comment]
Ok i'll chalk this up to meteor's odd path manipulation
