### ISSUE TITLE
Unable to install libnginx-mod-http-passenger

### ISSUE THREAD

**Issue by veekram** [phusion/passenger#2349]
It's been a while I am trying to install phusion passenger. I followed [this](https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install/oss/bionic.html) official documentation from phusion passenger. 

Below is my configuration

```
Configuration:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename: bionic

Nginx:
nginx version: nginx/1.18.0
```

I get the following error while trying to install  libnginx-mod-http-passenger.
```sudo apt-get install -y libnginx-mod-http-passenger```

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-passenger : Depends: nginx-common (< 1.14.1) but 1.18.0-3ubuntu1+bionic1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Tried upgrading nginx version to `1.19`, still no luck. 

However downgrading nginx to version `1.14` and following [this](https://github.com/phusion/passenger/issues/2122#issuecomment-437087257) still works. But I am looking to upgrade nginx to either version `1.18.0` or `1.19.0` and latest stable version of phusion passenger.  Anyone faced this as well ?

**Comment by CamJN** [comment]
Bionic comes with Nginx 1.14, if you want to use our packaged Nginx module, you must use your distro's provided Nginx package. If for example you have the repo provided by NGINX setup, you will instead need to [compile a dynamic module compatible with that Nginx](https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#dynamic-module).
