### ISSUE TITLE
packagecloud repo responds 402, oss-binaries alternative repo is missing many RHEL 7 packages

### ISSUE THREAD

**Issue by ghost** [phusion/passenger#2350]
Previously, there was a packagecloud repo (baseurl https://packagecloud.io/phusion/passenger/el/7/$basearch for RHEL 7) that contained Passenger, Nginx builds with a statically linked passenger module, and other assorted passenger packages (mod_passenger for Apache, etc). This repo now returns a 402 - Payment Required status code (and displays the same in the Web UI). This behavior started around 22:30 UTC on Monday, March 29th 2021.

It looks like the instructions now point to the oss-binaries repo (baseurl https://oss-binaries.phusionpassenger.com/yum/passenger/el/7/x86_64/ for RHEL 7) but this repo lacks the nginx packages and also only contains the dynamic nginx module for passenger versions 6.0.5 and above. The nginx builds are available in the RHEL 6 oss-binaries repo.

Is it possible to get the Nginx RPMs that included the passenger module added to the oss-binaries repo? It would be extremely helpful if we could get the nginx 1.17.3 build.

**Comment by CamJN** [comment]
@FooBarWidget do you remember if this was a limitation of `createrepo` or did we just forget to migrate those packages?

**Comment by FooBarWidget** [comment]
As far as I can tell, no mistake was made during the migration of EL7 packages from PackageCloud to the new repo server. We used the exact same migration method for EL6 and EL7, namely using reposync.

Unfortunately we can't get the old packages back now that PackageCloud has gone defunct.
