### ISSUE TITLE
Ruby-related assets for newest Ruby patch versions

### ISSUE THREAD

**Issue by FraPazGal** [phusion/passenger#2353]
## Request

Ruby released a new patch version for all of its supported branches a couple of days ago, https://www.ruby-lang.org/en/news/. I was wondering if there are any plans on updating the rubyext assets used by passenger to these new versions. 

If this isn't viable in the short term, do you think the already released assets could be used with the latest Ruby patch?

Thanks for your time,
Francisco de Paz

**Comment by CamJN** [comment]
done in 6.0.9
