### ISSUE TITLE
Shutting down state stuck

### ISSUE THREAD

**Issue by izenk** [phusion/passenger#2355]
## Issue report

**Question 1: What is the problem?**
Passenger processes do not shut down, but stuck in "Shutting down..." for hours

**Question 2: Passenger version and integration mode**:

Version : 6.0.4
nginx/1.17.3 Phusion_Passenger/6.0.4

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 16.04.6 LTS

**Question 4: Passenger installation method**:
Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
ruby 2.6.5 with rvm

---

```
Version : 6.0.4
Date    : 2021-04-16 13:16:47 +0000
App groups    : 1

----------- Application groups -----------
core:
  App root: /home/app/core/current
  (spawning 1 new process...)
  Requests in queue: 0
  * PID: 27951   Sessions: 0       Processed: 30      Uptime: 7m 31s
    CPU: 1%      Memory  : 320M    Last used: 2s ago
  * PID: 27968   Sessions: 0       Processed: 10      Uptime: 7m 31s
    CPU: 0%      Memory  : 290M    Last used: 5s ago
  * PID: 27985   Sessions: 0       Processed: 6       Uptime: 7m 30s
    CPU: 0%      Memory  : 282M    Last used: 44s ago
  * PID: 19768   Sessions: 1       Processed: 87      Uptime: 2h 4m 38s
    CPU: 0%      Memory  : 336M    Last used: 1h 57m 43
    Shutting down...
  * PID: 20376   Sessions: 1       Processed: 14      Uptime: 1h 55m 37s
    CPU: 0%      Memory  : 298M    Last used: 1h 54m 4
    Shutting down...
  * PID: 20895   Sessions: 1       Processed: 45      Uptime: 1h 49m 19s
    CPU: 0%      Memory  : 337M    Last used: 1h 48m 3
    Shutting down...
```

There are some processes in status 'Shutting down...' - they stuck in this status for hours. At the same time passenger tries to spawn new processes what leads to total number up to 10 (max pool  size is 5) and it also leads to RAM overuse (up to 2x).
Restarting nginx or passenger helps.

**Comment by CamJN** [comment]
It is likely Passenger is waiting for websockets to close, is that correct?

**Comment by izenk** [comment]
Cant say exactly, because cant reproduce. But what I saw in passenger-status --show=server, there were requests (in "Shutting Down" processes) like '/api/v3/reseller/.../...' - definitely not using websockets

**Comment by CamJN** [comment]
Well, if you can't reproduce it, then i'll close. Passenger waits for processes to quit on shutdown, if they don't quit, then it'll hang.
