### ISSUE TITLE
GitHub releases for enterprise lagging behind open source

### ISSUE THREAD

**Issue by DimitriosLisenko** [phusion/passenger#2361]
I'm looking at the [GitHub releases](https://github.com/phusion/passenger/releases), and currently version 6.0.9 is the latest release for the open source version, but 6.0.6 is the latest release for the enterprise version. Looking inside the APT repository, 6.0.7-6.0.9 are currently available for the `libnginx-mod-http-passenger-enterprise` package, so I'm assuming that this release exists. Is there a different location I can find the enterprise source code for those versions, or is there a reason that the GitHub releases page is lagging behind for enterprise?

**Comment by CamJN** [comment]
Thanks for bringing that to my attention, those releases were never supposed to be on github. The proper place for getting the source code for enterprise is in the customer portal at https://www.phusionpassenger.com/customers/file_listing
