### ISSUE TITLE
Passenger 6.0.9 crashes while starting application

### ISSUE THREAD

**Issue by mookie-** [phusion/passenger#2368]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
Passenger should not crash.
- What is the actual behavior?
Passenger crashes while loading an application.
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer: I'm not sure if it's easy possible to reproduce.

**Question 2: Passenger version and integration mode**:

Your answer: open source 6.0.9 Apache

**Question 3: OS or Linux distro, platform (including version)**:

Your answer: Gentoo, all updates installed, x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[X] source tarball
[ ] Other, please specify:

Installed with this ebuild: https://github.com/gentoo/gentoo/blob/master/www-apache/passenger/passenger-6.0.9.ebuild

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Your answer: Ruby 2.7.2p137 installed with rbenv

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer: No

**Question 7: Anything else about your setup that we should know?**

Your answer: Here is the apache-configuration 

[apache-vhost.txt](https://github.com/phusion/passenger/files/6784624/apache-vhost.txt)
[passenger-module.conf.txt](https://github.com/phusion/passenger/files/6784643/passenger-module.conf.txt)

and the crash logs

[apache-error.log](https://github.com/phusion/passenger/files/6784616/apache-error.log)
[main.log](https://github.com/phusion/passenger/files/6784627/main.log)
[pool.log](https://github.com/phusion/passenger/files/6784628/pool.log)
[backtrace_oxt.log](https://github.com/phusion/passenger/files/6784629/backtrace_oxt.log)
[backtrace.log](https://github.com/phusion/passenger/files/6784630/backtrace.log)
[ulimits.log](https://github.com/phusion/passenger/files/6784632/ulimits.log)
[mbufs.log](https://github.com/phusion/passenger/files/6784633/mbufs.log)
[fds.log](https://github.com/phusion/passenger/files/6784634/fds.log)
[controller_states.log](https://github.com/phusion/passenger/files/6784635/controller_states.log)
[controller_configs.log](https://github.com/phusion/passenger/files/6784636/controller_configs.log)

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/features#premium-features) base. They also provide us with the means to continue our high level of open source support!

**Comment by CamJN** [comment]
I don't suppose it'd be possible to get a backtrace from a non-stripped build?

ATM these logs are the most interesting:
```
Thread 'Group process spawner: /home/deploy-user/app (production)' (0x7fc814458640, LWP 17135):
     in 'void Passenger::SpawningKit::Spawner::setConfigFromAppPoolOptions(Passenger::SpawningKit::Config*, Passenger::Json::Value&, const AppPoolOptions&)' (Spawner.h:83)
     in 'void Passenger::SpawningKit::SmartSpawner::startPreloader()' (SmartSpawner.h:310)
     in 'virtual Passenger::SpawningKit::Result Passenger::SpawningKit::SmartSpawner::spawn(const AppPoolOptions&)' (SmartSpawner.h:1281)
     in 'void Passenger::ApplicationPool2::Group::spawnThreadRealMain(const SpawnerPtr&, const Passenger::ApplicationPool2::Options&, unsigned int)' (SpawningAndRestarting.cpp:95)
```

```
Last assertion failure: (key.size() <= MAX_KEY_LENGTH), function Passenger::StringKeyTable<T, MoveSupport>::Cell* Passenger::StringKeyTable<T, MoveSupport>::realInsert(const Passenger::HashedStaticString&, ValueType, bool) [with ValueType = const Passenger::StaticString&; LocalMoveSupport = Passenger::SKT_DisableMoveSupport; T = Passenger::StaticString; MoveSupport = Passenger::SKT_DisableMoveSupport], file src/cxx_supportlib/DataStructures/StringKeyTable.h, line 257.
```

**Comment by mookie-** [comment]
Hello CamJN, thank you for your answer.
I've removed the gentoo installed passenger and did a tarball install like it is described here: https://www.phusionpassenger.com/library/install/apache/install/oss/tarball/

Here are the logs:
[apache_error.log](https://github.com/phusion/passenger/files/6796015/apache_error.log)
[pool.log](https://github.com/phusion/passenger/files/6796016/pool.log)
[main.log](https://github.com/phusion/passenger/files/6796017/main.log)
[controller_states.log](https://github.com/phusion/passenger/files/6796018/controller_states.log)
[backtrace_oxt.log](https://github.com/phusion/passenger/files/6796019/backtrace_oxt.log)
[backtrace.log](https://github.com/phusion/passenger/files/6796020/backtrace.log)
[ulimits.log](https://github.com/phusion/passenger/files/6796021/ulimits.log)
[mbufs.log](https://github.com/phusion/passenger/files/6796022/mbufs.log)
[fds.log](https://github.com/phusion/passenger/files/6796023/fds.log)
[controller_configs.log](https://github.com/phusion/passenger/files/6796024/controller_configs.log)

One "fun" thing is that two application which have mostly the identical codebase (they are the staging vhosts) are running fine.

**Comment by CamJN** [comment]
Thanks for that.

**Comment by mookie-** [comment]
@CamJN Thank you for looking at it.
As it's working for the other application, I've tried rebuilding the used ruby version and also all gems used but it still crashes. If you have any Idea what I could try to do, just tell me. Even if it's a wild guess :)

**Comment by CamJN** [comment]
Sorry for the delay, i got busy. So your symbolicated backtrace shows that it is indeed an insert into the StringKeyTable that crashes, due to the key being too long, where too long is "longer than 255 bytes". It looks like the key is the entire `SECRET_KEY_BASE=yoursecretkeyhere` string. What's weird is that the env vars are normally null separated at that point but this one has a `=`. I'm still looking for why that might be, can you look at how you're setting the `SECRET_KEY_BASE` It looks like Passenger isn't parsing it correctly.

**Comment by mookie-** [comment]
Thank you very much @CamJN!
I've tried to set the environment variable in the Apache vhost configuration with:
```
SetEnv SECRET_KEY_BASE=xxxx
```
where it should be:
```
SetEnv SECRET_KEY_BASE xxxx
```
This it a little bit embarrassing but I'm very thankful for your help!

I'll close the issue now, but if you want to do something with this, I'm happy to test something for you.
