### ISSUE TITLE
File has unexpected size (7635 != 6683). Mirror sync in progress?

### ISSUE THREAD

**Issue by gekkota** [phusion/passenger#2370]
When running a new install with Ubuntu 20.04 apache and apt, im getting this error:

Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/focal/main/binary-amd64/Packages.bz2  File has unexpected size (7635 != 6683). Mirror sync in progress?

Any clues on this?

**Comment by saratrice** [comment]
Same issue here:

```
E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (7637 != 6595). Mirror sync in progress? [IP: 109.107.35.58 443]
   Hashes of expected file:
    - Filesize:6595 [weak]
    - SHA512:4ebc1374c4ece8fa0f1a5c672d857f4c14fefb251ba4eaa7179ae941b412e2d72ccddbf0b1558244acfc0d5021e1f1a0f0ebca268cdd16e6675f9eeecbbb5dba
    - SHA256:276fe3102e8b7f135a907f9eced90982cc5ba79260abdc6add22685bb34b2fc4
    - SHA1:644e9d1ba3e4ae9b725fb331f710fb68aa2a2c96 [weak]
    - MD5Sum:ef7fa07af528c68ff0bdb747f6034cc8 [weak]
   Release file created at: Wed, 02 Jun 2021 18:27:43 +0000
```

**Comment by HallDJack** [comment]
I am also seeing this same issue. It is breaking my team's builds.

It looks like someone updated the package today (14-Jul-2021 07:29). My team has tried doing an `apt-get clean` before `apt-get update`, but that hasn't helped. 

It seems like something is out of sync with that package which is causing the file size to not match what is expected.

**Comment by Xymist** [comment]
Same here; this is a blocker for our build system as it stands.

**Comment by CamJN** [comment]
fixed now, sorry.
