### ISSUE TITLE
Passenger hangs on spawning (Ubuntu 20.04 Rails 5.2.6 Ruby-2.5.8 Passenger 6.0.10)

### ISSUE THREAD

**Issue by JMC-PK** [phusion/passenger#2374]
**Are you sure this is a bug in Passenger?**
Seems like it.

**Please try with the newest version of Passenger to avoid issues that have already been fixed**
Using 6.0.10

**Question 1: What is the problem?**
- What is the expected behavior?
process spawns and rails site loads
- What is the actual behavior?
process crashes at Load OS shell
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. 
set your hosts to 45.79.131.178 rpdf1.peoplekeys.com and visit https://rpdf1.peoplekeys.com/status

I have log level 7 enabled so you can see the output directly on that page. 

Your answer:

**Question 2: Passenger version and integration mode**:

Your answer:
```
passenger open source 6.0.010 standalone; 1.21.1/nginx open source
nginx version: nginx/1.21.1
built by gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --with-openssl=/tmp/openssl-1.1.1k --add-module=/tmp/incubator-pagespeed-ngx-1.14.33.1-RC1 --add-module=/tmp/headers-more-nginx-module --add-module=/tmp/ngx_brotli --add-module=/usr/share/passenger/ngx_http_passenger_module --prefix=/opt/nginx --with-http_ssl_module --with-http_slice_module --with-http_gzip_static_module --with-http_sub_module --with-http_stub_status_module --with-http_flv_module --with-http_xslt_module --with-http_image_filter_module --with-mail --with-mail_ssl_module --with-http_mp4_module --with-http_v2_module
```
**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:
unbuntu 20.04.2 fresh install with apt-get updates
Linux web01 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:
ruby-2.5.8, RVM, Rails 5.2.6

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:
No

**Question 7: Anything else about your setup that we should know?**

Your answer:

nginx config:
```
    location @passenger {
        root                                /var/www/nginx/rpdf.peoplekeys.com/live_site/public;
        passenger_enabled                   on;
        passenger_ruby                      /home/deploy/.rvm/gems/ruby-2.5.8@rpdf-rails5.2/wrappers/ruby;
        rails_env                           production;
        proxy_set_header                    X-Forwarded-Proto https;
        passenger_friendly_error_pages      on;
        passenger_min_instances             12;
        passenger_app_group_name            rpdf1-webapp-production;
    }
```
---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/features#premium-features) base. They also provide us with the means to continue our high level of open source support!

**Comment by JMC-PK** [comment]
I have this working on a separate 18.04 machine with 6.0.10 & I was attempting to rebuild the machine with 20.04. The config and everything else are identical except for the version of ubuntu & nginx version, that one is at:
```
nginx version: nginx/1.17.9
built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-openssl=/tmp/openssl-1.1.1d --add-module=/tmp/headers-more-nginx-module --add-module=/tmp/ngx_brotli --add-module=/usr/share/passenger/ngx_http_passenger_module --prefix=/opt/nginx --with-http_ssl_module --with-http_slice_module --with-http_gzip_static_module --with-http_sub_module --with-http_stub_status_module --with-http_flv_module --with-http_xslt_module --with-http_image_filter_module --with-mail --with-mail_ssl_module --with-http_mp4_module --with-http_v2_module 
```

**Comment by JMC-PK** [comment]
I tried to make a new rails app to test this with out-of-the-box settings.

rails new hello-world

same issue. 

![Screen Shot 2021-08-18 at 2 33 54 PM](https://user-images.githubusercontent.com/29738399/129953172-a3507b2a-e31a-4cb3-8a49-9f8b10ff10b4.png)

**Comment by JMC-PK** [comment]
I reinstalled both nginx 1.21.1 & passenger 6.0.10, and tried using the passenger 6.0.10 gem to compile the nginx module. 

ive even tried installing older versions. I went with SERVER_SOFTWARE=nginx/1.19.10 Phusion_Passenger/6.0.0 and I get the same error. 

I suppose next is trying to rebuild the server from scratch and see what that yields.

**Comment by JMC-PK** [comment]
Actually, I found out my recompiled older version of nginx wasn't loaded when I tried last time due to compile errors with the passenger module & GCC. 

I threw in the casting fix (void *) (modeled after this gcc8 patch ( https://github.com/wireapp/wire-server/pull/321/files/0cf2e50c6e8efa1ed95144899fad671b815e2438 )for that directly into passenger gem src ( passenger-6.0.0/src/nginx_module/Configuration.c ) and it recompiled it successfully. 

I rebooted the server for good measure and the new nginx and module spawned correctly. 

It is working with nginx/1.19.10 & Phusion_Passenger/6.0.0 

The issue is either with Nginx 1.21.1 or passenger 6.0.10 or a combo of both on 20.04.

**Comment by JMC-PK** [comment]
Since i fixed the issue, Im not sure if i should close this or not. The issue is fixed, by using older versions, that doesnt seem optimal.

**Comment by CamJN** [comment]
Those changes were made 3 years ago in https://github.com/phusion/passenger/commit/ccfa509d5143ea30ef44d73432e8193d278168bc so 6.0.10 definitely includes them. I'm going to close this as the needed changes are present.

**Comment by JMC-PK** [comment]
I dont think the issue is due to whatever changes you're referring to, simply because I installed 6.0.10 and this was occurring. 

Looking at your reference, youre referring to the void * changes i mentioned. That wasn't the issue. That was how I got an old version to work right now so I could have a functioning passenger. The original issue is with 6.0.10 and it wasn't working on a fresh install.
