### ISSUE TITLE
Allow / Deny does not work correctly (static files are delivered eventhough)

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#238]
_From [yves.vogl@deetune.com](https://code.google.com/u/113728181274361750751/) on September 20, 2008 11:25:05_

I set up a virtual host with Passenger 2.2 on Debian Etch, Apache 2.1
(Debian Package) 

Here's my (pretty simple and standard) virtual host

<VirtualHost *:80>                                        
  ServerName example.org
	ServerAlias *.example.org
  DocumentRoot /var/www/example.or/current/public
  <Directory /var/www/example.or/current/public>
    Options -Indexes Includes FollowSymLinks MultiViews +ExecCGI
    AllowOverride AuthConfig FileInfo Indexes Options Limit
    Order deny,allow
    Deny from all
    Allow from example.com
    Allow from 111.222.333.444
    Allow from 444.555.666
  </Directory>
</VirtualHost>

As long as I'm allowed to see the page, everything works fine. If I should
be denied to see the page, the Rails app doesn't seem to be fired up
completely – static content and some fragments are transfered to me anyway.

Another thing I noticed when I wanted to switch to mod_auth HTTP-BASIC due
to this issue: You've to enter your username/password several times (to be
specific: for each file on the first request). To avoid this, I had to save
the password to browsers-keychain and reload the page. This issue was
tested with Safari 3 (OS 10.5, Vista), Firefox 2/3 (OS 10.5, Vista),
Internet Fuckup 7 (Vista).

I'm not sure but I guess that there must be something bypassed – I'd
exspect that if a Deny/Allow ruleset is evaluated to deny a request, the
Rails app should not even be thought of by the webserver. 

Yves

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=137_

**Comment by OnixGH** [comment]
[PassengerHighPerformance](https://www.phusionpassenger.com/library/config/apache/reference/#passengerhighperformance) is documented with warnings. Please file a new issue if you have problems with the latest Passenger and this option off.
