### ISSUE TITLE
Passenger application groups disappeared on previously working system

### ISSUE THREAD

**Issue by tgreiser** [phusion/passenger#2393]
**Question 1: What is the problem?**

Passenger apps have stopped and will not restart. I am no longer able to restart my Rails apps via capistrano or passenger-config. The server was previously set up and working fine. I think the problem was introduced after an apt update and reboot.

```
01 passenger-config restart-app /var/www/inventory/development --ignore-app-not-running
01 There are no Phusion Passenger(R)-served applications running whose paths begin with '/var/www/inventory/development'.
```

- How can we reproduce it? I am not clear how to reproduce, but it seems to be a similar situation to https://github.com/phusion/passenger/issues/2392

Apache and passenger are running, but there are no Passenger RubyApps and no App groups listed.

```
# passenger-status
Version : 6.0.11
Date    : 2021-10-28 23:26:15 +0000
Instance: PDzzKrq3 (Apache/2.4.29 (Ubuntu) Phusion_Passenger/6.0.11)

----------- General information -----------
Max pool size : 6
App groups    : 0
Processes     : 0
Requests in top-level queue : 0

----------- Application groups -----------
# passenger-memory-stats
Version: 6.0.11
Date   : 2021-10-28 23:06:38 +0000

--------- Apache processes ---------
PID   PPID  VMSize    Private  Name
------------------------------------
1025  1     429.2 MB  1.8 MB   /usr/sbin/apache2 -k start
1072  1025  431.5 MB  0.2 MB   /usr/sbin/apache2 -k start
1073  1025  431.5 MB  0.2 MB   /usr/sbin/apache2 -k start
1074  1025  431.5 MB  0.3 MB   /usr/sbin/apache2 -k start
1075  1025  431.5 MB  0.2 MB   /usr/sbin/apache2 -k start
1076  1025  431.5 MB  0.2 MB   /usr/sbin/apache2 -k start
3833  1025  431.5 MB  0.2 MB   /usr/sbin/apache2 -k start
### Processes: 7
### Total private dirty RSS: 3.23 MB


-------- Nginx processes --------

### Processes: 0
### Total private dirty RSS: 0.00 MB


---- Passenger processes -----
PID   VMSize    Private  Name
------------------------------
1028  390.4 MB  2.8 MB   Passenger watchdog
1031  947.0 MB  3.9 MB   Passenger core
### Processes: 2
### Total private dirty RSS: 6.64 MB

```

**Question 2: Passenger version and integration mode**:
- open source 6.0.11 apache
- Apache/2.4.29

**Question 3: OS or Linux distro, platform (including version)**:

Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-1058-aws x86_64)

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.5.8, RVM, Rails 4.2

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No

**Comment by tgreiser** [comment]
This appears to be a bug or incompatibility with 6.0.11. I downgraded back to 6.0.10 and it started working again.

```
sudo apt install passenger=1:6.0.10-1~bionic1 libapache2-mod-passenger=1:6.0.10-1~bionic1 passenger-dev=1:6.0.10-1~bionic1
```

**Comment by CamJN** [comment]
What distro (and version) are you using, what directory is the instance registry set to, and if it's /tmp do you have a tmp cleaner process running (even unintentionally)?

**Comment by tgreiser** [comment]
On further testing, when loading passenger via apache2 - at least one request is required in order to start the passenger application groups. If I access the vhost URL with a browser, then the application group loads and passenger is available to receive deployments.
