### ISSUE TITLE
How fix default brew install permissions complaints?

### ISSUE THREAD

**Issue by gregwillits** [phusion/passenger#2394]
## Issue report

**Question 1: What is the problem?**

Following Passenger's web site, I used brew to install passenger. Running passenger yields the following complaints in the error_log.

```
 - /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini is not secure: it can be modified by user [USER_NAME]
 - /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger is not secure: it can be modified by user [USER_NAME]
 - /usr/local/opt/passenger/libexec/src/ruby_supportlib is not secure: it can be modified by user [USER_NAME]
 - /usr/local/opt/passenger/libexec/src is not secure: it can be modified by user [USER_NAME]
 - /usr/local/opt/passenger/libexec is not secure: it can be modified by user [USER_NAME]
 - /usr/local/opt/passenger is not secure: it can be modified by user [USER_NAME]
 - /usr/local/opt is not secure: it can be modified by user [USER_NAME]

Please either fix up the permissions for the insecure paths, or install Passenger in a different location that can only be modified by root.
```

- What is the expected behavior?

Maybe it's just me, but I would like more guidance on the website on how to go down either one of those two suggested corrective paths. It's not clear to me how to do either w/o creating problems with brew in general, future updates of passenger, etc.

**Question 2: Passenger version and integration mode**:

I am currently testing this with Passenger 6.0.11/Apache installed via brew on MacOS (10.15 and 11)

**Question 3: OS or Linux distro, platform (including version)**:

I am currently testing this with Passenger 6.0.11/Apache installed via brew on MacOS (10.15 and 11)

**Question 4: Passenger installation method**:

[X] OS X Homebrew

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.7.4, rbenv, Rails 6.1.4

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Installing on my own stand-alone Mac for small project

**Question 7: Anything else about your setup that we should know?**

I see this thread https://github.com/phusion/passenger/issues/2178 but that one was resolved by simply saying "ignore that for development" — well, for production, what do we do?

Fundamentally the setup is functioning, the sites are served, but assuming the warnings are there for a reason, I'd like to address them.

**Thanks.**

**Comment by CamJN** [comment]
This is simply the end result of Homebrew's decision to not require sudo/root in order to install software system-wide on a multi-user OS. You cannot use Passenger from homebrew in a secure way, without breaking homebrew (nor any other formulae for that matter). You can read homebrew's rationale for this here: https://docs.brew.sh/FAQ
