### ISSUE TITLE
Will passenger + nginx 1.20.x be available anytime soon with RHEL8, AlmaLinux8, RockyLinux8?

### ISSUE THREAD

**Issue by dave105010** [phusion/passenger#2403]
Hi,

Will passenger + nginx 1.20.x+ be available anytime soon for RHEL8, AlmaLinux8, RockyLinux8?

As CentOS 8 support ends in 21 days after the RedHat's worst treatment towards the community... 

We are currently forced to look for options(maybe Puma) other than Phusion Passenger and make a permanent switch to stop using Phusion Passenger on at least 30+ VMs as the only provided module comes with forced nginx 1.14.x installation which is very old and has tons of security vulnerabilities. 

We cannot compile or maintain nginx and/or Phusion Passenger by ourselves for that many VMs in a production environment. There can be so many different potential problems with no community support. That would also make it almost impossible to automate this to provision on that many VMs or it would require a ridiculous amount of time just to make sure that everything is right.

RHEL and CentOS caused so much trouble that we even considered using Ubuntu at this point.

I hope there is a way to make Nginx 1.20.x + passenger work together.

**Comment by CamJN** [comment]
DUp of https://github.com/phusion/passenger_rpm_automation/issues/18
