### ISSUE TITLE
How to install Passenger as an Nginx module? Tutorial doesn't explain.

### ISSUE THREAD

**Issue by shelagh-lewins-ucl** [phusion/passenger#2404]
** Operating system **
RedHat 8 Linux

** Nginx version **
1.20.1

https://www.phusionpassenger.com/library/install/nginx/install_as_nginx_module.html

** Passenger version **
6.0.12

** Passenger installation method **
Static or dynamic module for Nginx

I have hit the issue that the repo to install Passenger and Nginx on RedHat 8 installs Nginx 1.14.1, which is an unacceptable regression for us: https://github.com/phusion/passenger_rpm_automation/issues/18

I am therefore trying to follow the tutorial to install Passenger as a module of Nginx, and I am clearly missing something obvious, because the steps in the doc do not work.

Here's the doc I'm trying to follow:

https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#installing-passenger-as-a-normal-or-dynamic-nginx-module 

The doc says "The value for /path-to-passenger-module can be obtained with the command:"

`passenger-config --nginx-addon-dir`

If I haven't installed Passenger, then of course that fails with "command not found". If I have installed Passenger, it returns this:

`/opt/passenger-6.0.12/src/nginx_module`

However there is no folder or file at that location and the Nginx compile fails.

I assume that I need to get or build the Passenger module, but I haven't found any instructions on where to download it, or how to build it. Can you give me some guidance how to do this, and could this information be added to the tutorial?

**Comment by CamJN** [comment]
If you install passenger as per the instructions here: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/standalone/ (choose red hat 8 from the dropdown) then you should have all the files available, and should be able to proceed.

**Comment by Shelagh-Lewins** [comment]
Thanks, I'll give that a try. Can this information be added to the documentation? At present the instructions to which I linked above offer no guidance.

**Comment by Shelagh-Lewins** [comment]
I installed Passenger standalone [as per the documentation](https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/meteor/standalone/) and still had exactly the same problem.

`passenger-config --nginx-addon-dir`

returns

`/usr/share/passenger/ngx_http_passenger_module`

but there is no file there.

`ls -l /usr/share/passenger/`

returns

```
drwxr-xr-x. 3 root root  231 Dec 31 14:56 helper-scripts
-rw-r--r--. 1 root root 3524 Nov  3 21:28 mime.types
drwxr-xr-x. 4 root root   50 Dec 31 14:56 node
-rw-r--r--. 1 root root   79 Nov  3 21:28 release.txt
drwxr-xr-x. 2 root root   24 Dec 31 14:56 standalone_default_root
drwxr-xr-x. 8 root root  112 Dec 31 14:56 templates
-rw-r--r--. 1 root root 3225 Nov  3 21:28 union_station_gateway.crt
-rw-r--r--. 1 root root 4093 Nov  3 21:28 update_check_client_cert.p12
-rw-r--r--. 1 root root 5508 Nov  3 21:28 update_check_client_cert.pem
-rw-r--r--. 1 root root  800 Nov  3 21:28 update_check_server_pubkey.pem
```

The Passenger install seems to be OK:

`sudo /usr/bin/passenger-config validate-install`

returns "Everything looks good"

`passenger`

returns

`Phusion Passenger(R) Standalone, the easiest way to run web apps.`

So I am pretty sure Passenger Standalone is installed.

I downloaded the nginx source code and tried to configure it like this:

`./configure --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --add-dynamic-module=$(passenger-config --nginx-addon-dir)`

The configure process ended with this error:

```
checking for getaddrinfo() ... found
configuring additional dynamic modules
adding module in /usr/share/passenger/ngx_http_passenger_module
./configure: error: no /usr/share/passenger/ngx_http_passenger_module/config was found
```

Can you suggest what might be the problem? Installing Passenger does not give me the module file, so how can I get it?

**Comment by CamJN** [comment]
You're right I completely forgot that some of the sources were split off into the `passenger-devel` package. You need that too. I really should update the docs, as you've said.

**Comment by Shelagh-Lewins** [comment]
Thank you! I ran this:

`sudo dnf install passenger-devel.x86_64`

And then my .configure code as above, and then

`make modules`

This ran and has created the file

`objs/ngx_http_passenger_module.so`

That's great :)

**Comment by Shelagh-Lewins** [comment]
> You're right I completely forgot that some of the sources were split off into the `passenger-devel` package. You need that too. I really should update the docs, as you've said.

Instead of [analysing the compatibility string](https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#installing-passenger-as-a-normal-or-dynamic-nginx-module) and trying to understand the boolean list of flags, using nginx -V seems a much easier way to find the flags with which Nginx was compiled? I found that idea [here](https://gorails.com/blog/how-to-compile-dynamic-nginx-modules).

**Comment by CamJN** [comment]
That doesn't actually always work, there are Nginx packages out there where the configure flags don't match the compatibility string.

**Comment by Shelagh-Lewins** [comment]
Ah, I guess I was lucky!

I am so close to having this working; I've added the configuration file for my bundled Meteor app, but I now have an Nginx error:

`"/var/www/myapp/bundle/public/index.html" is not found `

I haven't moved any files, but there must be something which has to be differently configured when running Passenger as a dynamic module, compared to using the Passenger + Nginx combo.

**Comment by Shelagh-Lewins** [comment]
I must have been lucky with the flags...

It's almost working now but I am getting an Nginx error:

`"/var/www/myapp/bundle/public/index.html" is not found `

There is no actual folder /var/www/myapp/bundle/public but presumably Meteor does some magic with symlinks, as that was never a problem before?

I've used a copy of myapp.conf from the previous (working) version which used Nginx + Passenger. The file structure in /var/www/myapp is unchanged, so I guess there must be something different about configuring a Meteor app when using Passenger as a dynamic module? I have set `passenger_enabled on` but is there something else I need to do?

(With Passenger as a module, is there any way to inspect what it's doing? passenger-status says "Passenger doesn't seem to be running".)

Here's a snippet from myapp.conf, which as I say works when Nginx and Passenger are installed together.

```
    # Tell Nginx and Passenger where your app's 'public' directory is
    root /var/www/myapp/bundle/public;

    # Turn on Passenger
    passenger_enabled on;

    # number of proxy servers so client ip address can be found
    passenger_env_var HTTP_FORWARDED_COUNT 1;

    # Tell Passenger that your app is a Meteor app
    passenger_app_type node;

    passenger_startup_file main.js;
```

Thank you for your help so far. If you have any thoughts as to what needs to be configured differently when running Passenger as a dynamic module, that would be awesome also.

**Comment by CamJN** [comment]
Just some quick questions to rule out some easy to forget things: do you `load_module` the dynamic module you compiled? Have you restarted nginx? What does `nginx -t` say?

**Comment by Shelagh-Lewins** [comment]
Thanks! Yes:


/etc/nginx/nginx.conf
```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
load_module "/usr/share/nginx/modules/ngx_http_passenger_module.so";
include /usr/share/nginx/modules/*.conf;
```
...

```
sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

And I have run:

```
sudo service nginx stop
sudo service nginx start
```

There are no errors in the log, only the "is not found" message.

**Comment by Shelagh-Lewins** [comment]
Forgive me if this is a stupid question, but you don't have to include any configuration files do you, as in a normal build? e.g.

nginx.conf

`include /etc/nginx/passenger.conf`

Just checking whether the dynamic module is entirely self contained or whether we need to specify things like

```
passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby /usr/bin/passenger_free_ruby;
```

**Comment by CamJN** [comment]
Yeah all configuration must be done, just like with the compiled-in module.

**Comment by Shelagh-Lewins** [comment]
Thank you, that probably explains it, though when I tried setting the config, nginx failed to start with no errors in the log and a mysterious systemctl failure message:

`Job for nginx.service failed because a fatal signal was delivered causing the control process to dump core.`

With the compiled in module, the configuration is set up automatically; can you help me find out what variables I need to set to what values?

The real mystery for me is, what would I set passenger_root to? The file referenced by the compiled version doesn't exist in this installation:

`passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;`

is passenger_ruby just the path to my installation, ruby, e.g. /usr/bin/ruby?

is passenger_max_pool needed and how would I choose a value?

I have previously used Passenger's excellent compiled version so these things are not obvious to me...

Just to get my head round this, I previously assumed that the module was a self-contained package. Is that wrong? Does ngx_http_passenger_module.so actually just tell nginx how to include the standalone Passenger installation?

**Comment by CamJN** [comment]
Yes, the module just tells nginx how to talk to passenger. To find out what the crash is about, run nginx directly with `nginx` which should print errors to stdout. Passenger ruby is just a path to a ruby executable, and passenger root is available from `passenger-config --root`.

**Comment by Shelagh-Lewins** [comment]
Thank you! I have an exciting new error now that I have followed your instructions and set:

`     passenger_root /usr/local/share/gems/gems/passenger-6.0.12;`

Nginx error.log:

```
App 749889 output: SpawnEnvSetupperShell: /usr/local/share/gems/gems/passenger-6.0.12/buildout/support-binaries/PassengerAgent: Permission denied
App 749889 output: SpawnEnvSetupperShell: line 0: exec: /usr/local/share/gems/gems/passenger-6.0.12/buildout/support-binaries/PassengerAgent: cannot execute: Permission denied
```

Permissions on PassengerAgent are:

`-rwxr-xr-x. 1 root root 43749104 Jan  3 20:09 /usr/local/share/gems/gems/passenger-6.0.12/buildout/support-binaries/PassengerAgent`

**Comment by CamJN** [comment]
Hmm, given the permissions, I think the env setup process is running as the `nobody` user. Can you check the Nginx config for what user it will try to change to for workers? If there's none set or it's `root`, then passenger will change to `nobody` to reduce privileges.

**Comment by Shelagh-Lewins** [comment]
Is that worker_processes?

nginx.conf

```
user nginx;
worker_processes auto;
```

My app bundle is owned by a dedicated user, as recommended in the tutorials, but I don't know how you tell Passenger about that...in the compiled version it just works!

**Comment by Shelagh-Lewins** [comment]
I've changed permissions and Passenger is now starting! But there is an error with the app:

Error: Cannot find module '/usr/local/share/gems/gems/passenger-6.0.12/src/helper-scripts/node-loader.js'

I've done npm install in my bundle, so that isn't it.

**Comment by Shelagh-Lewins** [comment]
Thank you so much for your patient and excellent help. I have got it working, by changing ownership of PassengerAgent, and should be OK now. (somewhere in all the messing about I had removed the passenger_ruby setting, that was the final thing to get it right). You are a hero.

**Comment by Shelagh-Lewins** [comment]
For the documentation, modern Nginx is build using --with-compat, I think? So the doc could suggest that people use nginx -V and if it was built using --with-compat, they can do:

`./configure --with-compat --add-dynamic-module=$(passenger-config --nginx-addon-dir)`

then I think you don't need to actually make and install nginx do you? You can do:

`make modules`

so you won't interfere with the system nginx.
