### ISSUE TITLE
Cannot Build Nginx Module on Debian 11

### ISSUE THREAD

**Issue by DaAwesomeP** [phusion/passenger#2407]
## Issue report

**Question 1: What is the problem?**

I installed passenger via the provided Nginx repo. I can see the module in `/usr/share/passenger/ngx_http_passenger_module`. I attempted to use Nginx's provided `pkg-oss` tool to provide a Debian package containing the `.so` module. However regardless of if this is officially supported, I found some other issues.

1. `$PASSENGER_LIBS` is not set, but I'm unsure what would set it. Should I be sourcing some bash config file before compiling?
2. The build process attempts to run rake in the addon directory (or the addon directory copied to Nginx build directory), but there is no Rakefile in `/usr/share/passenger/ngx_http_passenger_module`.
3. This may have been a result of my troubleshooting which steps would fail, but I think `passenger-config` points to the wrong directory or not all the contents are present:
    ```bash
    $ passenger-config --nginx-dynamic-libs
    /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/LoggingKit.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/Exceptions.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/FileTools/PathManip.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/FileTools/FileManip.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/FileTools/PathSecurityCheck.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/ProcessManagement/Spawn.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/ProcessManagement/Utils.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/SystemTools/UserDatabase.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/Utils/SystemTime.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/StrIntTools/StrIntUtils.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/StrIntTools/StrIntUtilsNoStrictAliasing.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/IOTools/IOUtils.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/Algorithms/Hasher.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/Utils.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/jsoncpp.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/WatchdogLauncher.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/AppTypeDetector/CBindings.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/WrapperRegistry/CBindings.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/Utils/CachedFileStat.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/JsonTools/CBindings.o /usr/lib/passenger/nginx_dynamic/module_libpassenger_common/FileTools/PathManipCBindings.o /usr/lib/passenger/nginx_dynamic/libboost_oxt.a
    $ ls /usr/lib/passenger/nginx_dynamic/
    ls: cannot access '/usr/lib/passenger/nginx_dynamic/': No such file or directory
    $ ls /usr/lib/passenger/common/
    libboost_oxt.a  libpassenger_common
    ```
    The build looks for files like `/usr/lib/passenger/nginx_dynamic/module_libpassenger_common/LoggingKit.o` but I think it wants `/usr/lib/passenger/common/libpassenger_common/LoggingKit.o`. It looks for `/usr/lib/passenger/nginx_dynamic/libboost_oxt.a` but I think it wants `/usr/lib/passenger/common/libboost_oxt.a`.
4. I'm not sure why it decides to run the rake task. It checks that by checking `$PASSENGER_LIBS` (which I'm unsure how could be set previously)  and  `passenger-config --nginx-dynamic-compiled`, but clearly everything has been compiled because it exists in `/usr/lib/passenger/common/` and `passenger-config --nginx-dynamic-libs` returns a bunch of files.

**Question 2: Passenger version and integration mode**:
 open source 6.0.12

**Question 3: OS or Linux distro, platform (including version)**:
 Debian 11 amd64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
N/A

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
N/A

**Question 7: Anything else about your setup that we should know?**
 N/A

**Comment by CamJN** [comment]
Can you explain what you're trying to accomplish?

We provide an nginx module package `libnginx-mod-http-passenger` which provides the .so library which is compatible with the `nginx` package from debian 11.

If you are trying to build against a different nginx such as that provided by the Nginx company repo, then you want to install the standalone `passenger` package and follow the instructions here: https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#dynamic-module

If you're having trouble using nginx's packaging tools to provide a package built against another repo's nginx, that's not something that we actively support, so getting it working might be a pain.

**Comment by DaAwesomeP** [comment]
I was trying to use Nginx's packaging tools against Nginx's repo; it spits out a versioned `deb` file that ensures that Nginx will not update without the correct module version available.

Regardless, `passenger-config` was spitting out paths that did not exist (seemed like they would be on an RPM distro or another OS).

Unfortunately this was too much trouble to get to work so we've found another solution.
