### ISSUE TITLE
Nginx 1.20.2 + Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by VladimirPuidak** [phusion/passenger#2408]
Hi,
I tried to install Passenger for nginx 1.20.2. But after running "apt install libnginx-mod-http-passenger" it breaks my nginx. 
I've checked the information about Passenger package and I was confused by line **nginx-common (<< 1.18.1)** .
Is it mean that I have to use only nginx 1.18.x for Ubuntu 20.04.3 LTS?

**My environment:**
Ubuntu 20.04.3 LTS
nginx version: nginx/1.20.2

**Description of installed libnginx-mod-http-passenger:**
Package: libnginx-mod-http-passenger
Priority: optional
Section: ruby
Installed-Size: 1651
Maintainer: Phusion <info@phusion.nl>
Architecture: amd64
Source: passenger
Version: 1:6.0.10-1~ focal1
Depends: libc6 (>= 2.17), libgcc-s1 (>= 3.0), libstdc++6 (>= 9), passenger (= 1:6.0.10-1~focal1), nginx-common (>= 1.18.0-0ubuntu1.2), nginx-common (<< 1.18.1)

**Comment by CamJN** [comment]
All nginx modules must be compiled against one specific nginx version. Our packages are made to be compatible with the version of nginx provided in the distro repos. For Ubuntu 20.04 that's Nginx 1.18. You may use the base `passenger` package and compile an nginx module for whatever nginx you like by following these instructions: https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#dynamic-module
