### ISSUE TITLE
Path/Version Issues with 1.21.6_1

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2416]
## Issue report

Fill in as much as possible so that we can understand, find and fix the problem.

**Are you sure this is a bug in Passenger?**
yes

**Question 1: What is the problem?**
- What is the expected behavior?

For it to work.  It doesn't work because it's looking for a version that's not there.  So it doesn't work.  

- What is the actual behavior?

It doesn't work.  Because it's looking for a version that's been updated, and the directory names that uses versioning, demands a path that doesn't exist.  

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Ask away.  I updated `passenger` from `1.21.6` to `1.21.6_1` and this is what happens upon restarting `nginx`:

```
**The error**:
2022/03/10 01:18:17 [notice] 539#0: signal 1 (SIGHUP) received from 74363, reconfiguring
2022/03/10 01:18:17 [notice] 539#0: reconfiguring
2022/03/10 01:18:17 [emerg] 539#0: mkdir() "/opt/homebrew/Cellar/nginx/1.21.6/passenger_temp" failed (2: No such file or directory)
2022/03/10 01:19:14 [crit] 680#0: *168 connect() to unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.WZtsac7/agents.s/core failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.33, server: hq3.local, request: "GET / HTTP/1.1", upstream: "passenger:unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.WZtsac7/agents.s/core:", host: "hq3.local"
2022/03/10 01:19:14 [crit] 680#0: *168 connect() to unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.WZtsac7/agents.s/core failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.33, server: hq3.local, request: "GET /favicon.ico HTTP/1.1", upstream: "passenger:unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.WZtsac7/agents.s/core:", host: "hq3.local", referrer: "http://hq3.local/"

**Directories**:
>>> 1:18:49 rich@HQ3 nginx ➜ pwd
/opt/homebrew/Cellar/nginx
>>> 1:25:11 rich@HQ3 nginx ➜ l
total 0
drwxr-xr-x    3 rich  admin    96B  9 Mar 18:53 .
drwxrwxr-x  214 rich  admin   6.7K  9 Mar 10:59 ..
drwxr-xr-x   14 rich  admin   448B  9 Mar 18:53 1.21.6_1
>>> 1:25:20 rich@HQ3 nginx ➜
```

**Question 2: Passenger version and integration mode**:
RF: Passenger Standalone Info
_____ brew info nginx --with-passenger _____

nginx: stable 1.21.6 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/opt/homebrew/Cellar/nginx/1.21.6_1 (26 files, 2.2MB) *
  Poured from bottle on 2022-03-09 at 18:53:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1 ✔, pcre2 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g daemon off;
==> Analytics
install: 45,070 (30 days), 114,019 (90 days), 497,931 (365 days)
install-on-request: 45,008 (30 days), 113,836 (90 days), 496,880 (365 days)
build-error: 108 (30 days)

_____ brew info passenger _____

passenger: stable 6.0.12 (bottled), HEAD
Server for Ruby, Python, and Node.js apps via Apache/NGINX
https://www.phusionpassenger.com/
/opt/homebrew/Cellar/passenger/6.0.12_2 (5,008 files, 245.3MB) *
  Poured from bottle on 2022-03-09 at 18:52:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/passenger.rb
License: MIT
==> Dependencies
Build: nginx ✔
Required: openssl@1.1 ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate Phusion Passenger for Nginx, run:
  brew install nginx
And add the following to /opt/homebrew/etc/nginx/nginx.conf at the top scope (outside http{}):
  load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
And add the following to /opt/homebrew/etc/nginx/nginx.conf in the http scope:
  passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
  passenger_ruby /usr/bin/ruby;

To activate Phusion Passenger for Apache, create /etc/apache2/other/passenger.conf:
  LoadModule passenger_module /opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so
  PassengerRoot /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
  PassengerDefaultRuby /usr/bin/ruby
==> Analytics
install: 286 (30 days), 1,051 (90 days), 5,918 (365 days)
install-on-request: 273 (30 days), 986 (90 days), 5,504 (365 days)
build-error: 0 (30 days)

##### Homebrew installation passenger_files_comparator.rb #####
Suggested / current / suggested exists?:
load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
Suggested load_module exists: true

passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
Suggested passenger_root exists: true

passenger_ruby /usr/bin/ruby;
passenger_ruby /Users/rich/.rbenv/shims/ruby; \t\t\tDIFFERENT
Suggested passenger_ruby exists: true

_____ Ruby Info (programming language): _____

/Users/rich/.rbenv/shims/ruby
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
_____ nginx version: _____

nginx version: nginx/1.21.6
_____ OS Version: _____

ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
Software:

    System Software Overview:

      System Version: macOS 12.2.1 (21D62)
      Kernel Version: Darwin 21.3.0
      Boot Volume: Primer
      Boot Mode: Normal
      Computer Name: HQ3
      User Name: Rich (rich)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 23:58

**Question 4: Passenger installation method**:**
[ X ] OS X Homebrew

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
Nothing that I know of at this point.

**Comment by CamJN** [comment]
Homebrew needs to bump the revision on the passenger formula so that it builds a new bottle, however they do not allow me to open issues/PRs so it would be helpful if you could tell them they need to do that.

Alternatively you can tell your homebrew install to build passenger from source, that should work too.

**Comment by daBee** [comment]
Done.  Cheers

https://github.com/rbenv/rbenv/issues/1394

**Comment by CamJN** [comment]
You linked to an issue in the rbenv repo, you want the homebrew repo: https://github.com/Homebrew/homebrew-core

**Comment by daBee** [comment]
Oh...I see.  I'm tired.  I'll fix it.  

https://github.com/Homebrew/homebrew-core/issues/96698

**Comment by carlocab** [comment]
> Homebrew needs to bump the revision on the passenger formula so that it builds a new bottle

Rebuilding from source doesn't work (see https://github.com/Homebrew/homebrew-core/issues/96698#issuecomment-1065273204), so bumping the revision won't work either.

**Comment by CamJN** [comment]
@carlocab if building from source doesn't work that's an issue with homebrew, it's using a stale path from the old version of nginx `/opt/homebrew/Cellar/nginx/1.21.6/passenger_temp`

**Comment by carlocab** [comment]
> if building from source doesn't work that's an issue with homebrew

Perhaps, but if so then it must be due to an upstream change (either in `nginx` or in `passenger`), since nothing important has changed in the way Homebrew installs either in about two years.

**Comment by CamJN** [comment]
Something changed, because homebrew used to bump passenger automatically when nginx got a revision bump. Now it doesn't. 

Anyway, after building the passenger formula from source on my mac with the 1.21.6_1 nginx installed, passenger in nginx integration mode works fine.

**Comment by carlocab** [comment]
> Something changed, because homebrew used to bump passenger automatically when nginx got a revision bump. Now it doesn't.

Those are usually caught by test failures when testing dependents. `passenger`'s test hasn't changed in quite a while either, but [tested fine](https://github.com/Homebrew/homebrew-core/runs/5364538599?check_suite_focus=true#step:10:38) when `nginx` had its revision bumped.

> Anyway, after building the passenger formula from source on my mac with the 1.21.6_1 nginx installed, passenger in nginx integration mode works fine.

Yes, it seems @daBee was mistaken when they claimed that rebuilding from source does not fix this.

**Comment by CamJN** [comment]
Perhaps the old path without the revision in the version number was still present on the system that performed the test?

**Comment by daBee** [comment]
It's my workstation.  All packages `local`.  

So what paths should I be checking then?

Upon `nginx` restart:

    2022/03/11 13:09:11 [emerg] 539#0: mkdir() "/opt/homebrew/Cellar/nginx/1.21.6/passenger_temp" failed (2: No such file or directory)

Looking into its parent directory:

```
>>> 13:10:19 rich@HQ3 nginx ➜ ll
total 0
drwxr-xr-x  14 rich  admin   448B  9 Mar 18:53 1.21.6_1
>>> 13:10:20 rich@HQ3 nginx ➜ pwd
/opt/homebrew/Cellar/nginx
```

So there is the versioning on the `homebrew` install.  `nginx` is looking for `1.21.1`, and the directory it should be looking in is `1.21.6_1`.

**Comment by CamJN** [comment]
@dabee what is the output of these commands, I feel like something is being missed here.

```
arch
brew reinstall -s passenger
brew info passenger
```

Also, just to be super clear you don't have the following config option set in your nginx config?

`passenger_temp_path /opt/homebrew/Cellar/nginx/1.21.6/passenger_temp;`

**Comment by daBee** [comment]
```
>>> 13:29:45 rich@HQ3 ~ ➜ arch
brew reinstall -s passenger
brew info passenger
arm64
==> Downloading https://github.com/phusion/passenger/releases/download/release-6.0.12/passenger-6.0.12.tar.gz
Already downloaded: /Users/rich/Library/Caches/Homebrew/downloads/4d437ae3226fb490531da2599551562f5a62630ca1726bbeab44ab6b87d02a30--passenger-6.0.12.tar.gz
==> Reinstalling passenger
==> rake apache2
==> rake nginx
==> tar -xf /opt/homebrew/opt/nginx/share/nginx/src/src.tar.xz --strip-components 1
==> ./configure --prefix=/opt/homebrew/Cellar/nginx/1.21.6_1 --sbin-path=/opt/homebrew/Cellar/nginx/1.21.6_1/bin/nginx --with-cc-opt=-I/
==> make
==> ./dev/install_scripts_bootstrap_code.rb --ruby /opt/homebrew/Cellar/passenger/6.0.12_2/libexec/src/ruby_supportlib /opt/homebrew/Cel
==> ./bin/passenger-config compile-nginx-engine
==> ./dev/install_scripts_bootstrap_code.rb --nginx-module-config /opt/homebrew/Cellar/passenger/6.0.12_2/libexec/bin /opt/homebrew/Cell
==> Caveats
To activate Phusion Passenger for Nginx, run:
  brew install nginx
And add the following to /opt/homebrew/etc/nginx/nginx.conf at the top scope (outside http{}):
  load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
And add the following to /opt/homebrew/etc/nginx/nginx.conf in the http scope:
  passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
  passenger_ruby /usr/bin/ruby;

To activate Phusion Passenger for Apache, create /etc/apache2/other/passenger.conf:
  LoadModule passenger_module /opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so
  PassengerRoot /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
  PassengerDefaultRuby /usr/bin/ruby
==> Summary
🍺  /opt/homebrew/Cellar/passenger/6.0.12_2: 5,008 files, 245.3MB, built in 3 minutes 14 seconds
==> Running `brew cleanup passenger`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
passenger: stable 6.0.12 (bottled), HEAD
Server for Ruby, Python, and Node.js apps via Apache/NGINX
https://www.phusionpassenger.com/
/opt/homebrew/Cellar/passenger/6.0.12_2 (5,008 files, 245.3MB) *
  Built from source on 2022-03-11 at 13:33:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/passenger.rb
License: MIT
==> Dependencies
Build: nginx ✔
Required: openssl@1.1 ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate Phusion Passenger for Nginx, run:
  brew install nginx
And add the following to /opt/homebrew/etc/nginx/nginx.conf at the top scope (outside http{}):
  load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
And add the following to /opt/homebrew/etc/nginx/nginx.conf in the http scope:
  passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
  passenger_ruby /usr/bin/ruby;

To activate Phusion Passenger for Apache, create /etc/apache2/other/passenger.conf:
  LoadModule passenger_module /opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so
  PassengerRoot /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
  PassengerDefaultRuby /usr/bin/ruby
==> Analytics
install: 275 (30 days), 1,048 (90 days), 5,879 (365 days)
install-on-request: 263 (30 days), 986 (90 days), 5,472 (365 days)
build-error: 0 (30 days)
```

As for that directive, I do not have that in `nginx.conf`.  I've never even seen that.

**Comment by CamJN** [comment]
That output all looks good to me, if you restart `nginx` does it still have the same issue?

**Comment by daBee** [comment]
Same issue.  `nginx` reboot is what throws this error:

    2022/03/11 13:37:04 [emerg] 539#0: mkdir() "/opt/homebrew/Cellar/nginx/1.21.6/passenger_temp" failed (2: No such file or directory)

Now...give me 10 min and I'll restart the box.  Stranger things have happened.

**Comment by daBee** [comment]
Fixed.  I unplugged it, then plugged it back in.  A literal reboot is what brought this back.
