### ISSUE TITLE
ERB.new arguments deprecated

### ISSUE THREAD

**Issue by dmalan** [phusion/passenger#2417]
**Question 1: What is the problem?**
- What is the actual behavior?

Deprecation notices appear on startup, re https://github.com/phusion/passenger/blob/stable-6.0/src/ruby_supportlib/phusion_passenger/standalone/start_command/nginx_engine.rb#L282:

```
/usr/lib/ruby/vendor_ruby/phusion_passenger/standalone/start_command/nginx_engine.rb:282: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
/usr/lib/ruby/vendor_ruby/phusion_passenger/standalone/start_command/nginx_engine.rb:282: warning: Passing eoutvar with the 4th argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, eoutvar: ...) instead.
```

- How can we reproduce it? 

```
git clone https://gist.github.com/b6141f5d2730df8e28ff8961bc896bab.git
cd b6141f5d2730df8e28ff8961bc896bab
docker compose up
```

**Question 2: Passenger version and integration mode**:

Passenger 6.0.12-1~focal1 standalone

**Question 3: OS or Linux distro, platform (including version)**:

Ubuntu 20.04 LTS x86_64

**Question 4: Passenger installation method**:

[x] Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 3.1.1p18

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Docker 20.10.12 using https://github.com/cs50/server/blob/main/Dockerfile, which is based on https://github.com/cs50/cli/blob/main/Dockerfile.

Thank you!

**Comment by CamJN** [comment]
https://github.com/phusion/passenger/commit/7bd1035819006ffd05a99434eecd1be0b886f758

**Comment by dmalan** [comment]
Thank you, @CamJN!

**Comment by proigor** [comment]
Hi,
sorry if this is the wrong place to ask such question, but how to use this fix?
I'm using 'gem "passenger"' in gemfile and the latest 6.0.13 version doesn't include this fix.
Please, advise.

**Comment by CamJN** [comment]
You'd need to wait for us to release the next version of passenger.

**Comment by RandieM** [comment]
For what it's worth, I am receiving the following deprecation warnings at start-up:

```
.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/passenger-6.0.13/src/ruby_supportlib/phusion_passenger/standalone/start_command/nginx_engine.rb:182:` warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments. 

.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/passenger-6.0.13/src/ruby_supportlib/phusion_passenger/standalone/start_command/nginx_engine.rb:182: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```

**Comment by RandieM** [comment]
> For what it's worth, I am receiving the following deprecation warnings at start-up:
> 
> ```
> .rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/passenger-6.0.13/src/ruby_supportlib/phusion_passenger/standalone/start_command/nginx_engine.rb:182:` warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments. 
> 
> .rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/passenger-6.0.13/src/ruby_supportlib/phusion_passenger/standalone/start_command/nginx_engine.rb:182: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
> ```

Sorry, I didn't notice that the issue was closed. These additional warnings above are also gone by upgrading to Passenger 6.0.14.
