### ISSUE TITLE
Nginx-full 1.20.x installation from oss-binaries.phusionpassenger repository 

### ISSUE THREAD

**Issue by pitman123** [phusion/passenger#2422]
---

Hi, I just wnat to install nginx-full 1.20.x version on Debian 11 with oss-binaries.phusionpassenger repository. I have checked that there is such a package in the repository but when i check the command `apt list -a nginx-full` I do not get this package.
I get only nginx-full 1.18.x and 1.14.x.

Is it posiible to install nginx-full `1.20.x` from this repository?
Thnaks for help.

**Comment by CamJN** [comment]
No, we do not host `nginx-full` packages anymore, we only provide the `libnginx-mod-http-passenger` module package which can be loaded by the nginx available from the default debian repos.

**Comment by pitman123** [comment]
@CamJN  Thanks for the answer. So, should I install `nginx 1.20.x` and then the `libnginx-mod-http-passenger` mosule if I want to achieve the same as with `nginx-full 1.18.x `?

**Comment by CamJN** [comment]
an Nginx module can only be loaded by the version of nginx which it was built for. So our debian 11 module can only be loaded by nginx 1.18.

If you want to use nginx 1.20 on debian 11 you'll either need to build the passenger nginx module yourself or passenger can build an nginx with passenger built in for you using the `passenger-install-nginx-module` script in the passenger package. that currently defaults to nginx 1.20.2
