### ISSUE TITLE
No docs available anywhere for hardening NGINX Phusion Passenger 

### ISSUE THREAD

**Issue by alilland** [phusion/passenger#2427]
NGINX Provides a [guide for hardening NGINX](https://geekflare.com/nginx-webserver-security-hardening-guide/) that includes stripping the version number and descriptiveness of what headers are returned, I am struggling to identify how to remove certain details from the headers response, because editing normal NGINX configurations does not seem to work.

I do not know enough about how Passenger works with NGINX, the only reason I adopted it originally was because a coworker who I no longer work with always used it to deploy his ruby apps.

--

using `server_tokens off;` With the following `/etc/nginx/sites-available/default` file configurations, it seems I am unable to get the `Server` header to remove the Phusion Passenger version. This may be working as expected since its successfully removing the nginx version, but its not removing the Phusion Passenger details

I am also unable to hide the `X-Powered-By` header

this is an example verbose curl response
```                                                                                                                                                               
$  curl https://my.website.com -v
...
> GET / HTTP/1.1
> Host: my.website.com
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 13 Jun 2022 22:01:50 GMT
< Server: nginx + Phusion Passenger(R) 6.0.14
< Status: 200 OK
< Vary: Accept-Encoding, Origin
< X-Powered-By: Phusion Passenger(R) 6.0.14
< Content-Length: 52
< Connection: keep-alive
< 
* Connection #0 to host my.website.com left intact
"OK"  
```

`/etc/nginx/sites-available/default`
```conf
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  if ($http_x_forwarded_proto = 'http'){
    return 301 https://$host$request_uri;
  }

  passenger_enabled  on;
  root ...;

  server_name _;
  server_tokens off;

  location ~ /\.(?!well-known) {
    deny all;
  }

  location / {
    proxy_hide_header X-Powered-By;

    passenger_ruby          ...;
    passenger_base_uri      /;
    passenger_app_root      ...;
    passenger_document_root ...;
    passenger_min_instances ...;
  }
}
```

someone on Stackoverflow https://stackoverflow.com/posts/72609581 mentioned that it may be something unrelated to Nginx and related to passenger, so that has led me here looking for more info

**Comment by CamJN** [comment]
https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_show_version_in_header

**Comment by alilland** [comment]
> https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_show_version_in_header

this is excellent, thank you!

Is there any specific documentation of recommended hardening steps to be taken anywhere?

**Comment by CamJN** [comment]
No docs on that topic atm.

For the most part securing passenger has more to do with your file-system permissions than your nginx config.

For example if you installed Passenger from a ruby gem, then making sure that the passenger files cannot be modified by a non-root user, (we print a warning to the logs about this if it's wrong).
Make sure your app runs as an unprivileged user, and make sure that your app's files and database role are properly secured.

Other than that, you can browse the config options on the page i linked.
