### ISSUE TITLE
Documentation note for apache/passenger/macOS 12

### ISSUE THREAD

**Issue by jcrate** [phusion/passenger#2429]
This is not technically a Passenger problem. But it might be helpful to someone else eventually to add a note to the macOS install documentation regarding macOS 12 and accessing files on external volumes.  A note in the macOS 12 `brew info` blurb might be useful too.

 I've had passenger running with Apache (both installed via Homebrew) on another macOS 12 machine with no problems. But I just set up a new machine with files being accessed on external drives and ran into problems.

- There was an issue with open file limits (PassengerCore crash on startup), when starting apache via the httpd binary, as the homebrew installation recommends and specifies in the `org.apache.httpd.homebrew.plist`. Starting via `apachectl` sets ulimit to unlimited and avoids this issue. I'm not sure if this is related to or caused by the second issue. To fix this I changed the `org.apache.httpd.homebrew.plist` to execute the command `/usr/local/bin/apachectl start -D FOREGROUND`. 
- There was a permissions problem accessing files on an external volume. It was fine launching apache from the shell using `sudo apachectl start`, but not when started by loading the `org.apache.httpd.homebrew.plist`. To fix this I had to go to System Preferences -> Security & Privacy, Privacy tab, and allow Full Disk Access for `sh`. It should show in the list after running into these permissions problems.

**Comment by CamJN** [comment]
These are all homebrew problems, and should be reported there.
