### ISSUE TITLE
Support for RHEL9/AlmaLinux 9 via yum/dnf repo

### ISSUE THREAD

**Issue by conathan** [phusion/passenger#2431]
**Question 1: What is the problem?**

I would like to request mod_passenger support for RHEL9 (Specifically AlmaLinux 9 in our case)

At this time, the yum repository at https://oss-binaries.phusionpassenger.com/yum/passenger/el/ only has EL6,EL7,EL8.

**Question 2: Passenger version and integration mode**:

open source 6.0.14 via mod_passenger (apache)

**Question 3: OS or Linux distro, platform (including version)**:
AlmaLinux 9.0 x86_64

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[X] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Comment by CamJN** [comment]
Now that rocky linux has released a el9 build, we can start work on this. Alma isn't sufficiently compatible with RHEL for our purposes so we had to wait.

Our packages are installable and compatible with alma, they just can't be built on it.

**Comment by jaboutboul** [comment]
@CamJN can you please expand and provide some detail on what issues you found?

**Comment by CamJN** [comment]
Sure, unlike RHEL, rocky linux, or the now defunct non-stream centos, alma linux uses sub-keys to sign their packages, so they don't work in mock which we use to build our rpm's.

**Comment by jaboutboul** [comment]
Thanks. You’re probably trying to use Alma 8 mock chroot to build on a CentOS 7 host. They have older versions of yum and rpm which don’t support subkeys. There’s an RH BZ issue that was opened about this a while back: https://bugzilla.redhat.com/show_bug.cgi?id=2017069

**Comment by jaboutboul** [comment]
Hey @CamJN  9 no longer uses subkeys by the way.

**Comment by CamJN** [comment]
Looks like EPEL hasn't made a GeoIP package yet for el9: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/g/ need that to continue.

**Comment by carlwgeorge** [comment]
GeoIP is dead upstream, so it's doubtful it will be added to epel9 (although that's up to the GeoIP maintainer).

https://bugzilla.redhat.com/show_bug.cgi?id=2066787

**Comment by CamJN** [comment]
Dropped GeoIP, moving forward with this.

**Comment by CamJN** [comment]
Looks like there's still no epel 9 package for `rubygem-rack`, someone started adding one: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-1a8dcda52c but seems to have gotten distracted or busy. We'll need to wait for it.

**Comment by CamJN** [comment]
Technically there is a copr package, but asking people to enable copr is a bit much IMO.

**Comment by carlwgeorge** [comment]
Hey @tdawson, you built rubygem-rack for EPEL 9 but it is no longer showing up in the repo and the build is not tagged.  Was there some kind of issue that necessitated it getting pulled?

**Comment by tdawson** [comment]
Sorry about that.  Fixing it now.
rubygem-rack has/had a security CVE, ( https://bugzilla.redhat.com/show_bug.cgi?id=2099525 )and then I got it mixed up with rubygem-rails, which does not install. ( https://bugzilla.redhat.com/show_bug.cgi?id=2104327 )

I think the fastest way to get it back into epel9 is to get the security update some karma
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-0d0a29e337

**Comment by CamJN** [comment]
I upvoted it.

**Comment by tdawson** [comment]
We have enough upvotes now.  Thank you to all who gave the update karma.
It should go out in today's epel9 update.

Again, my apologies for removing it.

**Comment by CamJN** [comment]
So, this won't hold up the release which is coming along nicely, but since everyone in this thread has been quite responsive, I figured you might be able to help. I'd like to support "module streams" so that we can make a module for each version of nginx that you can install from the default distro repos. However I've not seen any docs that explain how to support module streams on the repo side, does anyone know where such docs exist? It won't be included for this release most likely as I'll have to update our publishing scripts but it'd be great to support the newer versions of nginx that are supported in el 8 & 9.

**Comment by conathan** [comment]
Speaking of Modules, something we found limiting on AlmaLinux 8, was it was only built against the Ruby 2.5 module (and so we can't use it directly for Ruby 2.6, 2.7, or 3.0).  Modules (or rpm's with the different native libraries for this would also be useful if possible).

As for how, Never figured out how to do it ourselves yet,  but we did find modulemd-tools at https://github.com/rpm-software-management/modulemd-tools that would probably be something we would run after packages are built on mock (once we figure it out anyway,  I've cheated and just used different internal rpm repositories for different ruby/php environments vs trying to make it work as one).
* From earlier discussion I believe your environment also does mock.




As for switching modules via mock, (nothing to do with the rpm having module information)

config_opts['module_setup_commands'] = [
    ('disable', 'php'),
    ('disable', 'postgresql'),
    ('enable', 'php:7.3'),
    ('enable', 'postgresql:13'),
    ('enable', 'javapackages-tools:201902')
    ]

**Comment by CamJN** [comment]
release with el9 support is out

**Comment by xorel** [comment]
May I ask if (and when if so) you release also the el9 packages at https://oss-binaries.phusionpassenger.com/yum/passenger/el/ ?

**Comment by CamJN** [comment]
Huh, they should have been published with Passenger 6.0.15... I just checked, and it looks like a step was missed in our CI config that led to them being skipped. I've got to make a 6.0.16 soon though for several reasons (ubuntu 2022/10, fixing #2445, hopefully adding arm packages) so this will get rolled into that release.

**Comment by daan-b** [comment]
Any progress? Is there a workaround?

**Comment by CamJN** [comment]
The el9 packages are enabled in the CI now, so the next release (scheduled for this month) will have them.

**Comment by CamJN** [comment]
This should be fixed now.

**Comment by Legends0** [comment]
> This should be fixed now.

Looks like the packages were not gpg signed or if they were, the signature is sha1...

- Package mod_passenger-6.0.16-1.el9.x86_64.rpm is not signed
- Package passenger-6.0.16-1.el9.x86_64.rpm is not signed
Error: GPG check FAILED

**Comment by CamJN** [comment]
The repomd.xml file is signed, and contains the checksums for all of the packages, no different from how el 6-8 have been.
