### ISSUE TITLE
6.0.15 missing in GH releases

### ISSUE THREAD

**Issue by mensfeld** [phusion/passenger#2444]
released here: https://rubygems.org/gems/passenger/versions/6.0.15 but missing here: https://github.com/phusion/passenger/releases

**Comment by CamJN** [comment]
Yes, the release hasn't finished, there's an issue I'm looking into, the github releases and blog etc will update when i'm done.

**Comment by mensfeld** [comment]
Roger

**Comment by andyshinn** [comment]
Is this also affecting the apt repo? Maybe we should keep this open until it is resolved? I have builds failing because of apt checksum issues that were working previously.

**Comment by CamJN** [comment]
Yes, it will be affecting everything.

**Comment by CamJN** [comment]
Though it looks like it's started to move again so it might be fixed soon

**Comment by andyshinn** [comment]
Thanks. I'm following this issue for when it is closed. If you could close and comment when it is resolved that would be awesome. Thanks, Cam.

**Comment by CamJN** [comment]
of course

**Comment by CamJN** [comment]
I think it should be fixed now, feel free to report any remaining issues, i'll close this in a few minutes if there are no reports
