### ISSUE TITLE
ubuntu 22.04 , nginx nginx/1.18

### ISSUE THREAD

**Issue by bcodermicro** [phusion/passenger#2448]
## Issue report

**Question 2: Passenger version and integration mode**:
open source latest for NGINX 

**Question 3: OS or Linux distro, platform (including version)**:
ubuntu 22.04 , nginx nginx/1.23.1

**Question 4: Passenger installation method**:

Your answer:

- [ ] RubyGems + Gemfile
- [ ] RubyGems, no Gemfile
- [X] Phusion APT repo
- [ ] Phusion YUM repo
- [ ] OS X Homebrew
- [ ] source tarball
- [ ] Other, please specify:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
NO

**Question 7: Anything else about your setup that we should know?**

Your answer:

from other readings of issues here it looks like that NGINX shipped with this distribution should be supported out of the box..

**Comment by CamJN** [comment]
The passenger nginx module for Ubuntu 22.04 is built against nginx 1.18, you've likely got a misconfigured repo file, check `/etc/apt/sources.list.d/passenger.list` if it says `jammy` as the distro name.

**Comment by bcodermicro** [comment]
the response to this is 

deb https://oss-binaries.phusionpassenger.com/apt/passenger jammy main

**Comment by CamJN** [comment]
Odd, can you show me what the error you're seeing is? I just tested installing nginx + libnginx-mod-http-passenger on a fresh jammy vm and didn't have any issues.

**Comment by bcodermicro** [comment]
Sure however from the ISO I did an apt uninstall and reinstall of NGINX and it bounced it from 1.18 to 1.22.. need to figure out how to get around that.

**Comment by CamJN** [comment]
Hmm, Ubuntu 22.04 definitely shouldn't be pulling in Nginx 1.22 on its own, sounds like something has added a source for nginx packages aside from the ubuntu repos, perhaps the official nginx repo?

**Comment by CamJN** [comment]
`apt show -a nginx` should tell you where the newer version is being pulled from.

**Comment by bcodermicro** [comment]
Ok just uninstalled everything....got rid of any extraneous repos and reinstalled nginx-extra from scratch...got 1.18 and then the install worked. not sure why it was reporing needing <1.14 when I did the process initially. Thanks for interacting.
