### ISSUE TITLE
core_api_server_addresses and core_api_server_authorizations - are these safe to use?

### ISSUE THREAD

**Issue by blowfishpro** [phusion/passenger#2450]
Through poking through the code in this repo I discovered these features for configuring the passenger core API - these two would be incredibly useful for exposing parts of that API to monitoring tools.  But while I was able to get them working with no issues, I can find almost no documentation on them, and I'm just wondering if they should be considered internal and subject to unannounced breaking changes or something like that?

**Comment by CamJN** [comment]
This is indeed a non-stable api, for which we make no promises about backwards compatibility.
