### ISSUE TITLE
Environment Variable Value home Changed to hoem

### ISSUE THREAD

**Issue by bantonj** [phusion/passenger#2451]
## Issue report

I recently upgraded from version `6.0.6` to `6.0.15` and noticed that one of my apps no longer started up correctly. This is when I noticed that the value for our environment variable `RACK_SITE` was being changed from `home` to `hoem`, which was breaking our startup logic in config.ru.

I tested different versions of passenger, and noticed that the issue began in version `6.0.7`. 

We have other apps that use that environment variable which are not affected, and I was able to work around this behavior by changing the value from `home` to `public`.

We are setting the environment variable in the Apache site conf like `SetEnv RACK_SITE home`. I can see that the environment variable is correctly set on the apache process by looking at `/proc/<process id>/environ`, and is incorrect in the ruby process.

**Comment by bantonj** [comment]
I did a bit more digging and this only happens when I use SetEnv in the Apache config, when I export the environment variable in the shell before running apache, it works fine.

**Comment by jtomson** [comment]
> I did a bit more digging and this only happens when I use SetEnv in the Apache config, when I export the environment variable in the shell before running apache, it works fine.

This seems similar to the report "Nginx passenger_env_var falsifying values" #2419 except this is occurring for apache?
