### ISSUE TITLE
libnginx-mod-http-passenger arm support

### ISSUE THREAD

**Issue by danquack** [phusion/passenger#2452]
## Issue report

**Question 1: What is the problem?**
Arm binary for `libnginx-mod-http-passenger` not available in oss binaries - https://oss-binaries.phusionpassenger.com/apt/passenger/dists/jammy/main/

- How can we reproduce it? 

```Dockerfile
# syntax=docker/dockerfile:1.4
FROM ubuntu:jammy

RUN <<eot 
  apt-get -qq update
  apt-get install -y -qq dirmngr gnupg apt-transport-https ca-certificates lsb-release
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
  echo deb [arch=$(dpkg --print-architecture)] https://oss-binaries.phusionpassenger.com/apt/passenger $(lsb_release -sc) main > /etc/apt/sources.list.d/passenger.list
  apt-get -qq update
  apt-get install -qq -y passenger libnginx-mod-http-passenger
eot
```

```
#9 32.98 E: Unable to locate package libnginx-mod-http-passenger
```

**Question 4: Passenger installation method**:

Your answer:

- [ ] RubyGems + Gemfile
- [ ] RubyGems, no Gemfile
- [x] Phusion APT repo
- [x] Phusion YUM repo
- [ ] OS X Homebrew
- [ ] source tarball
- [ ] Other, please specify:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer: Containerization (docker)

**Question 7: Anything else about your setup that we should know?**

Your answer: no

**Comment by CamJN** [comment]
The capacity to build that package has been added, they haven't been published to the repo yet as that will only happen in the next release after we have good feedback from the docker β. You could extract the binaries from the docker image I suppose for now.

**Comment by danquack** [comment]
@CamJN I originally opened this issue related to the apt repos, but have since also found a need for yum repos. Will the arm binaries also be disseminated to yum repos? I see #2431 was opened and discussed el9 support, so I imagine there's probably some pipeline publishing, but im not seeing it deployed to el8 either https://oss-binaries.phusionpassenger.com/yum/passenger/el/8/

**Comment by CamJN** [comment]
@danquack no, arm64 yum/dnf/rpm packaging is not implemented yet. I'll start working on it but it won't be released until the next release of passenger at the earliest.

**Comment by audip** [comment]
Howdy folks, this will certainly be a very interesting feature and it looks the binaries are available on the first link of the issue Dan created. 

Would we be able to move forward with this?
