### ISSUE TITLE
Passenger yum install fails bad repodata/repomd.xml 404

### ISSUE THREAD

**Issue by fithive** [phusion/passenger#2462]
## Issue report

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
Passenger package rpm 404 during installation
https://oss-binaries.phusionpassenger.com/yum/passenger/el/7/x86_64/repodata/e5ad74101c73242223445fc9b9336212c9d54cad8ad3b8c331f58fe9a7487306-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found

It looks like the packages were changed last night/this morning because from https://oss-binaries.phusionpassenger.com/yum/passenger/el/7/x86_64/repodata/ it has file dates on the folder index of 19-Dec-2022 15:06

It looks like the path in https://oss-binaries.phusionpassenger.com/yum/passenger/el/7/x86_64/repodata/repomd.xml is wrong showing e5ad74101c73242223445fc9b9336212c9d54cad8ad3b8c331f58fe9a7487306-primary.sqlite.bz2 when the folder actually has 62d1e1b587836c23e4f2748fcd680eaec3cd1248dc412b731115b50e33b781ad-primary.sqlite.bz2

- What is the expected behavior?
Package installs
- What is the actual behavior?
Fails with 404
- How can we reproduce it?
On centos 7 execute commands for installation referenced on passenger documentation https://www.phusionpassenger.com/docs/tutorials/installation/node/
```
curl --fail -sSLo /etc/yum.repos.d/passenger.repo https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo
yum install -y --enablerepo=epel passenger
```

Be as detailed as possible in your descriptions, include any logs and stack traces (don't just cut/paste the error, provide some logging before that too).

(if you are requesting a feature instead of reporting an issue, describe here what you have in mind and how it would help you)

Your answer:

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:
CentOS Linux release 7.9.2009

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[X] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:
Node

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:
No

**Question 7: Anything else about your setup that we should know?**

Your answer:
No

**Comment by fithive** [comment]
this is probably related to release https://github.com/phusion/passenger/releases/tag/release-6.0.16

For anyone else having this issue, I'm working around it for now with local install
```
wget https://oss-binaries.phusionpassenger.com/yum/passenger/el/7/x86_64/passenger-6.0.15-1.el7.x86_64.rpm
yum --disablerepo=passenger --enablerepo=epel --nogpgcheck localinstall passenger-6.0.15-1.el7.x86_64.rpm
```

**Comment by fithive** [comment]
![Screen Shot 2022-12-19 at 11 21 08 AM](https://user-images.githubusercontent.com/45855432/208493563-71e701a0-64c9-4e3a-9788-fdf999eb9155.png)
screenshot of files/urls for reference

**Comment by CamJN** [comment]
Should be fixed now.

**Comment by fithive** [comment]
thanks

just as confirmation, I was able to install the packages now from the repo - so it does indeed appear to be fixed
