### ISSUE TITLE
Bad Signing Key for Debian Bullseye

### ISSUE THREAD

**Issue by danquack** [phusion/passenger#2463]
## Issue report
Looks like were seeing same behavior as in #2142 with the latest release.

Fill in as much as possible so that we can understand, find and fix the problem.
**Are you sure this is a bug in Passenger?**
Please read our troubleshooting and debugging guides first:
https://www.phusionpassenger.com/library/admin/troubleshooting/
https://www.phusionpassenger.com/library/admin/

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

```
 apt-get -qq update
 apt-get install -y -qq dirmngr gnupg apt-transport-https ca-certificates lsb-release wget apt-utils
 apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
 echo deb https://oss-binaries.phusionpassenger.com/apt/passenger $(lsb_release -sc) main > /etc/apt/sources.list.d/passenger.list
 apt-get -qq update
```

```
W: GPG error: https://oss-binaries.phusionpassenger.com/apt/passenger bullseye Release: The following signatures were invalid: BADSIG 561F9B9CAC40B2F7 Phusion Automated Software Signing (Used by automated tools to sign software packages) <auto-software-signing@phusion.nl>
E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bullseye Release' is not signed.
#9 33.46 W: GPG error: https://oss-binaries.phusionpassenger.com/apt/passenger bullseye Release: The following signatures were invalid: BADSIG 561F9B9CAC40B2F7 Phusion Automated Software Signing (Used by automated tools to sign software packages) <auto-software-signing@phusion.nl>
#9 33.46 E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bullseye Release' is not signed.
```
```
~ cat /etc/apt/sources.list.d/passenger.list
deb https://oss-binaries.phusionpassenger.com/apt/passenger bullseye main
```

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64
debian 11.5

Your answer:

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[x] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

** Anything else**
This previous worked with `Phusion Passenger(R) 6.0.15`

**Comment by danquack** [comment]
@CamJN I see you're actively doing the release. is the remediation steps the same as #2142 with moving the file to a backup, or is there a known fix?

**Comment by danquack** [comment]
Unsure if its related, but by allowing insecure, I am able to switch the error to a warning but libnginx-mod-http-passenger is now missing.

**Comment by danquack** [comment]
Switching to insecure signing, allowed me to run update but now seeing mirroring occurring?

```
E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/bullseye/main/binary-amd64/Packages.bz2  File has unexpected size (6924 != 5627). Mirror sync in progress? [IP: 109.107.35.58 443]
   Hashes of expected file:
    - Filesize:5627 [weak]
    - SHA512:3cef48633e0818d8ae1e4a6b3cc39be93c2064b23502df10fbb70aae05bbc9cbc8cf0ff3cf9b035722a59a910c20d8d02a4a5d1119b27e875c7ea204ee08c641
    - SHA256:3f26ac97dbdf9efd1ea45859c7e2067939f15c56b19793f7ce59a3515f2d453e
    - SHA1:b3018b42de926ef6b94df6f8e72ab45eb0ec1119 [weak]
    - MD5Sum:fdb988122f11442d8dee4324a5e295eb [weak]
   Release file created at: Mon, 19 Sep 2022 16:29:56 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by CamJN** [comment]
Should be fixed now, i just had to clear the caches once the release was done.

**Comment by danquack** [comment]
Yup, looks like that fixed it
