### ISSUE TITLE
Passenger 6.0.16 doesn't compile against the new Ruby 3.2

### ISSUE THREAD

**Issue by gdonald** [phusion/passenger#2464]
Passenger 6.0.16 doesn't compile against the new Ruby 3.2 that was released today:

NoMethodError: undefined method `exists?' for File:Class

**Comment by panatamp** [comment]
File.exists? method was removed in Ruby 3.2. 
https://bugs.ruby-lang.org/issues/17391

It should be replaced by File.exist?

**Comment by kinnalru** [comment]
\+1
![Screenshot_20221228_174309](https://user-images.githubusercontent.com/1270997/209829054-6c09de25-a947-4869-84e6-25f4122f5d0c.png)

**Comment by CamJN** [comment]
https://github.com/phusion/passenger/commit/2edecc1a879bcddea894286d2dfa778bc9196bea

**Comment by jason-hobbs** [comment]
I am having the same exact problem.

**Comment by CamJN** [comment]
The fix was committed after 6.0.16, so it won't be available until 6.0.17 is released.

**Comment by jason-hobbs** [comment]
Any ETA on the 6.0.17 release?

**Comment by ChangJoo-Park** [comment]
Please support  3.2.0 🚀 

```shell
 [passenger_native_support.so] trying to compile for the current user (nobody) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-1sb05k.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://github.com/phusion/passenger/releases/download/release-6.0.16/rubyext-ruby-3.2.0-x86_64-linux.tar.gz: The requested URL returned error: 404 
     Trying next mirror...
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.16/rubyext-ruby-3.2.0-x86_64-linux.tar.gz: The requested URL returned error: 404 
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.16/rubyext-ruby-3.2.0-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
Error: The application encountered the following error: ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
```

**Comment by amjosuesanchez** [comment]
I was running into this issue but didn't want to wait so as a work around I manually modified the passenger files located under my rbenv path
`/usr/local/rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/passenger-6.0.16/`

I modified the following files, changed `exists?` to `exist?`

`./src/ruby_native_extension/extconf.rb:if RUBY_PLATFORM =~ /darwin/ && !File.exists?(RbConfig::CONFIG["rubyarchhdrdir"])
./src/ruby_supportlib/phusion_passenger/platform_info/operating_system.rb:      return File.exists?("/proc/xen/capabilities") && cpu_architectures[0] == "x86"
`

then I just ran the `passenger-install-nginx-module --auto --auto-download --prefix=/opt/nginx` and it was succesful.

**Comment by CamJN** [comment]
to expand on the above you can find the dir where passegner is installed and apply the patch:

cd ~/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/passenger-6.0.16/
curl https://github.com/phusion/passenger/commit/2edecc1a879bcddea894286d2dfa778bc9196bea.patch | patch -fp1

there will be some complaints from patch about files that don't exist in the gem, that's expected as we don't ship some dev files in the gem, but it should still patch the files that do exist

**Comment by djones** [comment]
When should we expect 6.0.17 to be released? are you on a particular release schedule or can you cut releases anytime? My sense is many of us would adopt it the moment it ships.

**Comment by CamJN** [comment]
There's no hard schedule, however I aim to release about once per quarter. That said I'm currently dealing with this: https://gitlab.com/qemu-project/qemu/-/issues/1147 in our CI so until I manage to build a patched qemu, I can't release.

**Comment by CamJN** [comment]
I'm releasing today, the qemu bugs were too much to deal with so i'm punting the arm rpms to some future release

**Comment by gdonald** [comment]
Passenger 6.0.17 compiles against Ruby 3.2.0 for me now and works great.  Thanks a lot.
