### ISSUE TITLE
Ubuntu 16.04 Passenger Xenial does not have a Release file

### ISSUE THREAD

**Issue by emammadov** [phusion/passenger#2467]
Hello,
We have Ubuntu 16.04 LTS. We want to upgrade Ubuntu version 18.04 and then 20.04. If I try to run apt update command, it gives the following errors for Phusion Passenger. Could you please help me?

`root@web:~# apt update Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB] Hit:2 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial InRelease Hit:3 http://de.archive.ubuntu.com/ubuntu xenial InRelease Get:4 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease [99.8 kB] Hit:5 http://repository.veeam.com/backup/linux/agent/dpkg/debian/public stable InRelease Get:6 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease [97.4 kB] Ign:7 https://oss-binaries.phusionpassenger.com/apt/passenger xenial InRelease Err:8 https://oss-binaries.phusionpassenger.com/apt/passenger xenial Release server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none Hit:9 https://deb.nodesource.com/node_6.x xenial InRelease Reading package lists... Done E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger xenial Release' does not have a Release file. N: Updating from such a repository can't be done securely, and is therefore disabled by default. N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by CamJN** [comment]
Both xenial and bionic have release files. There is something wrong with your apt configuration.
https://oss-binaries.phusionpassenger.com/apt/passenger/dists/xenial/Release
https://oss-binaries.phusionpassenger.com/apt/passenger/dists/bionic/Release

**Comment by emammadov** [comment]
Hello. Thank you for your information. Could you please let me know what the PPA name is?

**Comment by emammadov** [comment]
Thank you for your information. How can I remove PPA and readd it? I tried the following command, but it says, passenger doesn't have ppa name.

add-apt-repository --remove passenger

**Comment by emammadov** [comment]
Thank you for your information. I think the problem happens because of SSL. 

Err:8 https://oss-binaries.phusionpassenger.com/apt/passenger xenial Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

**Comment by CamJN** [comment]
try updating your `ca-certificates` package, something like `apt-get update && apt-get upgrade ca-certificates`

**Comment by excid3** [comment]
This is happening for a Xenial server I'm working on too.

Upgrading ca-certificates does not help.

```bash
ca-certificates is already the newest version (20210119~16.04.1).
```

**Comment by CamJN** [comment]
@excid3 https://oss-binaries.phusionpassenger.com/apt/passenger/dists/xenial/Release is still there, so can you provide your logs?

**Comment by excid3** [comment]
```ruby
$ apt update
W: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger xenial Release' does not have a Release file.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/dists/xenial/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by excid3** [comment]
I imagine it says it has no Release file because the SSL cert cannot be verified?

**Comment by CamJN** [comment]
Does `curl https://oss-binaries.phusionpassenger.com/apt/passenger/dists/xenial/Release` on that system also not work? I've just spun up a clean xenial vm and the ca-certificates package is sufficient for apt and curl to get that url.

**Comment by excid3** [comment]
I don't know if this fixed it, but I ran `apt upgrade` and it upgraded `apt apt-transport-https apt-utils` and it seems to work now. Maybe apt-transport-https includes its own certs or something?

Curl works now:
```bash
# curl https://oss-binaries.phusionpassenger.com/apt/passenger/dists/xenial/Release
Origin: . xenial
Label: . xenial
Suite: xenial
Codename: xenial
Date: Mon, 19 Sep 2022 16:31:21 UTC
Architectures: amd64 i386
Components: main
Description: Generated by aptly
```
and apt update is fine now too:
```bash
$ apt update 
Hit:11 https://oss-binaries.phusionpassenger.com/apt/passenger xenial Release
```
