### ISSUE TITLE
Issue running passenger on Ruby & Nginx

### ISSUE THREAD

**Issue by FractiekamerSplinter** [phusion/passenger#2471]
**Question 1: What is the problem?**

*** ERROR: the Nginx configuration that Phusion Passenger(R) Standalone generated internally contains problems. The error message returned by the Nginx engine is:

    /usr/lib/passenger/support-binaries/nginx-1.22.1: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

This probably means that you have found a bug in Phusion Passenger(R) Standalone. Please report this bug to our Github issue tracker: https://github.com/phusion/passenger/issues

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer: Phusion Passenger (r) 6.0.17

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 22.04

Your answer:

**Question 4: Passenger installation method**:

Your answer:
 RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer: Ruby 3..0.5

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Your answer: No

**Question 7: Anything else about your setup that we should know?**

passenger-standalone-1kwqafd.log

server {
        server_name _;
        
            listen 0.0.0.0:80;
        
            root '/home/decidim/decidim-app/public';
        
        passenger_app_root '/home/decidim/decidim-app';
        passenger_enabled on;
        
        passenger_app_env 'development';
        
        passenger_spawn_method 'smart';
        
        passenger_load_shell_envvars off;
        passenger_preload_bundler off;

        # Rails asset pipeline & webpacker support.
        location ~ "^/(assets|packs)/.+-([0-9a-f]{32}|[0-9a-f]{64}|[0-9a-f]{20}|[0-9a-f]{8})\..+" {
            error_page 490 = @static_asset;
            error_page 491 = @dynamic_request;
            recursive_error_pages on;
        
            if (-f $request_filename) {
                return 490;
            }
            if (!-f $request_filename) {
                return 491;
            }
        }
        location @static_asset {
            gzip_static on;
            expires max;
            add_header Cache-Control public;
            add_header ETag "";
        }
        location @dynamic_request {
            passenger_enabled on;
        }

        ### BEGIN your own configuration options ###
        # This is a good place to put your own config
        # options. Note that your options must not
        # conflict with the ones Passenger already sets.
        # Learn more at:
        # https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template

        ### END your own configuration options ###
    }
    passenger_pre_start http://0.0.0.0/;

**Comment by CamJN** [comment]
You say you installed passenger using RubyGems but the path `/usr/lib/passenger/support-binaries/nginx-1.22.1` looks like you installed passenger using apt, is it possible you might have two copies installed and they are getting mixed up together in your setup?

**Comment by FractiekamerSplinter** [comment]
Hi, You're right. I installed via apt (see below), but also added a ruby gem in my Gemfile:

sudo apt install -y dirmngr gnupg
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
sudo apt install -y apt-transport-https ca-certificates
sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger focal main > /etc/apt/sources.list.d/passenger.list'
sudo apt update
sudo apt install -y libnginx-mod-http-passenger

I activated passenger with this command

if [ ! -f /etc/nginx/modules-enabled/50-mod-http-passenger.conf ]; then sudo ln -s /usr/share/nginx/modules-available/mod-http-passenger.load /etc/nginx/modules-enabled/50-mod-http-passenger.conf ; fi

**Comment by CamJN** [comment]
Then something went wrong with the apt installation, OpenSSL 1.1.* should be installed automatically when you install passenger with apt. You can install it manually. If it is already installed are you setting `LD_LIBRARY_PATH` to anything?

**Comment by FractiekamerSplinter** [comment]
How can I install OpenSSL 1.1.* (I currently have OpenSSL 3.0 running)? Is the LD_Library _Path the same as  /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;? (my passenger_root)

**Comment by FractiekamerSplinter** [comment]
This is my Passenger .conf file 

### Begin automatically installed Phusion Passenger config snippet ###
passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby /home/decidim/.rbenv/shims/ruby;
### End automatically installed Phusion Passenger config snippet ###

When I checked Install everything was fine
$ sudo /usr/bin/passenger-config validate-install
What would you like to validate?
Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Passenger itself
   ⬡  Apache

-------------------------------------------------------------------------

 * Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... ✓

Everything looks good. :-)

Could it be a Ubuntu 22.04 issue?

**Comment by FractiekamerSplinter** [comment]
I separately installed openssl 1.1.1 and created symlinks from there, but still get this error:
PassengerAgent: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
2023/02/12 21:29:37 [alert] 43797#43797: Unable to start the Phusion Passenger(R) watchdog: it seems to have crashed during startup for an un

How can I get libcrypto.so.1.1 to load?

**Comment by CamJN** [comment]
I just noticed, you say you use ubuntu 22.04 but you installed passenger for focal (20.04), you want to uninstall passenger, and then edit the  `/etc/apt/sources.list.d/passenger.list` to say jammy.

**Comment by CamJN** [comment]
Then the deps should be fixed, sorry i didn't notice earlier.

**Comment by FractiekamerSplinter** [comment]
Hi CamJN, thanks for this. I removed and re-installed Passenger and set right permissions. This did the trick and now everything works! Thanks again for your assistance!
