### ISSUE TITLE
Web application could not be started by the Phusion Passenger(R) application server.

### ISSUE THREAD

**Issue by FractiekamerSplinter** [phusion/passenger#2472]
I tried to install a ruby gem, but somehow this messed up my complete application, running on passenger:

We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later.

[Technical details for the administrator of this website](https://defractiekamer.nl/#)
Error ID:
b8d712c0
Details:
Web application could not be started by the Phusion Passenger(R) application server.

Please read [the Passenger log file](https://www.phusionpassenger.com/library/admin/log_file/) (search for the Error ID) to find the details of the error.

[ E 2023-02-13 21:23:23.1085 103764/Tn age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/decidim/decidim-app: The application encountered the following error: Permission denied @ rb_sysopen - /home/decidim/decidim-app/config/master.key (Errno::EACCES)
  Error ID: 7152d353
  Error details saved to: /tmp/passenger-error-HRWQZW.html

How can I solve this?

**Comment by CamJN** [comment]
Permission denied opening: `/home/decidim/decidim-app/config/master.key`, so fix the permissions on that file so your app's user can read it.
