### ISSUE TITLE
I removed the gem file and kept the apt install, but then I get the following error:

### ISSUE THREAD

**Issue by FractiekamerSplinter** [phusion/passenger#2475]
Hi CamJN, I removed the gem file and kept the apt install, but then I get the following error:
[ E 2023-02-14 00:32:11.4307 10855/Tn age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/decidim/decidim-app: The application encountered the following error: Could not find passenger-6.0.17 in locally installed gems (Bundler::GemNotFound)

_Originally posted by @FractiekamerSplinter in https://github.com/phusion/passenger/issues/2474#issuecomment-1428920232_

**Comment by FractiekamerSplinter** [comment]
It should be right as I am using it in nginx?

passenger-config about ruby-command
passenger-config was invoked through the following Ruby interpreter:
Command: /home/decidim/.rbenv/versions/3.0.5/bin/ruby
Version: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
To use in Apache: PassengerRuby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
To use in Nginx : passenger_ruby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
To use with Standalone: /home/decidim/.rbenv/versions/3.0.5/bin/ruby /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/bin/passenger start

The following Ruby interpreter was found first in $PATH:
Command: /home/decidim/.rbenv/versions/3.0.5/bin/ruby
Version: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
To use in Apache: PassengerRuby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
To use in Nginx : passenger_ruby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
To use with Standalone: /home/decidim/.rbenv/versions/3.0.5/bin/ruby /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/bin/passenger start

**Comment by CamJN** [comment]
can you post the actual config you put in nginx?
