### ISSUE TITLE
Ubuntu 18.04.02 LTS (Bionic) packages not found

### ISSUE THREAD

**Issue by axys16** [phusion/passenger#2480]
**Question 1: What is the problem?**
Hi, I'm trying to upgrade servers from Ubuntu 18.04.02 LTS to Ubuntu 20.04.x

During the upgrade process (before do-release-upgrade), I have the following problem: 

sudo apt-get update

    E: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Origin' value from 'packagecloud.io/phusion/passenger' to '. bionic'
    E: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Label' value from 'passenger' to '. bionic'
    N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Version' value from '1' to ''

sudo apt-get dist-upgrade

    E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/bionic/main/p/passenger/passenger-dev_6.0.4-1~bionic1_amd64.deb  404  Not Found [IP: 109.107.35.58 443]
    E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/bionic/main/libn/passenger/libnginx-mod-http-passenger_6.0.4-1~bionic1_amd64.deb  404  Not Found [IP: 109.107.35.58 443]
    E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/bionic/main/p/passenger/passenger_6.0.4-1~bionic1_amd64.deb  404  Not Found [IP: 109.107.35.58 443]
    E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/bionic/main/p/passenger/passenger-doc_6.0.4-1~bionic1_all.deb  404  Not Found [IP: 109.107.35.58 443]

I have checked apt config:
sudo vim /etc/apt/sources.list.d/passenger.list

    deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main

It seems ok with the documentation : https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/

**Question 2: Passenger version and integration mode**:
The current version of Passenger on the server : open source 6.0.2/nginx

**Question 3: OS or Linux distro, platform (including version)**:
Ubuntu 18.04.02 LTS

**Question 4: Passenger installation method**:
Phusion APT repo

**Comment by CamJN** [comment]
Can you show me the output of `apt show passenger`

**Comment by axys16** [comment]
Package: passenger
    Version: 1:6.0.4-1~bionic1
    Priority: optional
    Section: ruby
    Maintainer: Phusion <info@phusion.nl>
    Installed-Size: 11.4 MB
    Provides: ruby-passenger
    Depends: libc6 (>= 2.27), libcurl4 (>= 7.16.2), libgcc1 (>= 1:3.0), libpcre3, zlib1g (>= 1:1.1.4), procps, ruby2.5 | ruby2.4 | ruby2.3 | ruby2.2 | ruby2.1 | ruby2.0 | ruby1.9.1 | ruby1.8 | ruby-interpreter, rubygems-integration (>= 1.8) | rubygems1.9.1 | rubygems1.9 | rubygems (>= 1.2), ruby-rack
    Recommends: passenger-doc (= 1:6.0.4-1~bionic1), passenger-dev (= 1:6.0.4-1~bionic1)
    Breaks: libapache2-mod-passenger (<< 1:6.0.4), libnginx-mod-http-passenger (<< 1:6.0.4), passenger-common, passenger-common1.8, passenger-common1.9.1, ruby-passenger
    Replaces: libapache2-mod-passenger (<< 1:6.0.4), libnginx-mod-http-passenger (<< 1:6.0.4), passenger-common, passenger-common1.8, passenger-common1.9.1, ruby-passenger
    Homepage: https://www.phusionpassenger.com/
    Download-Size: 2322 kB
    APT-Sources: https://oss-binaries.phusionpassenger.com/apt/passenger bionic/main amd64 Packages
    Description: Application server for Ruby, Node.js, Python, Meteor
     Passenger makes deployment of web apps very easy and robust.
     It can be used standalone or integrated with Nginx or Apache.
     Passenger is a Phusion product.
    
    N: There are 14 additional records. Please use the '-a' switch to see them.

**Comment by CamJN** [comment]
hmm can you check if apt itself might be out of date? the formatting of the output is a bit different from what I got on my bionic VM.

`sudo apt update  && sudo apt list --upgradable`

**Comment by axys16** [comment]
I think you are right, it was an apt itself upgrade problem. A sort of partial upgrade.
Now everything is ok and Passenger is now in 6.0.17.

Thank you for help.
