### ISSUE TITLE
passenger incompatible with global uncaught exception handling via at_exit

### ISSUE THREAD

**Issue by jtomson** [phusion/passenger#2481]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
- 'global exception handling' can be accomplished via the ruby `at_exit` hook and the global `$!` variable - required for most error-handling gems (e.g. Airbrake)

- What is the actual behavior?
- the `$!` variable is not available and "global exception handling" cannot be accomplished with gems e.g. Airbrake

- How can we reproduce it? 

This code, if run under passenger, will print nothing due to [the way exceptions are caught](https://github.com/phusion/passenger/blob/stable-6.0/src/ruby_supportlib/phusion_passenger/utils.rb#L116-L118) and `exit(1)` is called, overwriting the previous `$!` with the `SystemExit` exception.

```ruby
at_exit do
   puts "XXX at_exit - $! is: #{$!}" unless $!.is_a?(SystemExit)
end

raise "uncaught exception"
```

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

open source passenger-6.0.17 gem

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:

**Question 4: Passenger installation method**:

Your answer:
[ x] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

## Follow-up Question

Could a hook be made available with the original `$!` exception, or have it moved to another global variable, or some other workaround? Thanks!

**Comment by jtomson** [comment]
@CamJN this may be naive but would it be OK to add a 'last-chance' callback to the [public ruby api](https://github.com/phusion/passenger/blob/8b70688d622b5c99ea549ae6fa3a3be2b3de4679/src/ruby_supportlib/phusion_passenger/public_api.rb) - something like a `PhusionPassenger.unhandled_exception_before_exit(e)` callback that can be invoked? I could take a crack at a PR if that sounds reasonable thanks!

**Comment by CamJN** [comment]
Yeah, I'd happily review a PR.

**Comment by jtomson** [comment]
thanks @CamJN I've put up a simple callback at https://github.com/phusion/passenger/pull/2483 looking forward to any feedback

**Comment by jtomson** [comment]
should be fixed by https://github.com/phusion/passenger/pull/2483 thanks again @CamJN

**Comment by jtomson** [comment]
@CamJN do you have a timeframe for the next release now that this fix has been merged? I am happy to update the changelog etc let me know thanks!

**Comment by CamJN** [comment]
This month, but as to what day, I'm not yet sure.
