### ISSUE TITLE
Yet Another Path Issue Based On Version

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2487]
## Issue report

I've posted this at least twice before on the very same issue.  I install a version (`1.25.1.1`) and it's searching paths for a directory that's not there, because it's looking for a different version (`1.25.1`):

```2023/07/12 10:34:53 [emerg] 1211#0: mkdir() "/opt/homebrew/Cellar/nginx/1.25.1/passenger_temp" failed (2: No such file or directory)```

**Are you sure this is a bug in Passenger?**

Yes.  The following error:

```
2023/07/12 10:51:26 [error] 1315#0: *1232 connect() to unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.aFwnibq/agents.s/core failed (61: Connection refused) while connecting to upstream, client: 192.168.1.4, server: myworkstation.local, request: "GET / HTTP/1.1", upstream: "passenger:unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.aFwnibq/agents.s/core:", host: "myworkstation.local"
```

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

Reinstalled.  Same error.  If anything, updating to `1.25.1.1` is what created this problem.  This has happened multiple times in the past. 

**Question 1: What is the problem?**

HTTP error `502 Bad Gateway` because `Passenger` is misguided through different paths.  

**Question 2: Passenger version and integration mode**:

```
_____ brew info passenger _____

==> passenger: stable 6.0.18 (bottled), HEAD
Server for Ruby, Python, and Node.js apps via Apache/NGINX
https://www.phusionpassenger.com/
/opt/homebrew/Cellar/passenger/6.0.18_2 (5,145 files, 215.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-07-12 at 10:51:04
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/passenger.rb
License: MIT
==> Dependencies
Build: httpd ✘, nginx ✔
Required: apr ✔, apr-util ✔, openssl@3 ✔, pcre ✔, pcre2 ✔
==> Options
--HEAD
	Install HEAD version

_____ Ruby Info (programming language): _____

/Users/rich/.rbenv/shims/ruby
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
_____ nginx version: _____

nginx version: nginx/1.25.1
```

**Question 3: OS or Linux distro, platform (including version)**:

```
_____ OS Version: _____

ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82
Software:

    System Software Overview:

      System Version: macOS 13.4.1 (22F82)
      Kernel Version: Darwin 22.5.0
      Boot Volume: Primer
      Boot Mode: Normal
      Computer Name: HQ3
      User Name: Rich (rich)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 20 days, 15 hours, 32 minutes
```

**Question 4: Passenger installation method**:

( X ) OS X Homebrew

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
Nothing that I know of at this point.

**Comment by CamJN** [comment]
Since you installed a pre-built passenger, and you are getting a path to an old nginx dir, then homebrew needs to update their passenger bottle. We cannot help you with that because homebrew has banned me from sending them PRs. There are also other issues with their passenger formula, but those aren't related to this issue.

**Comment by daBee** [comment]
Ah that sounds like a lot of fun.  But good to know they have multiple issues.

OK, then should I be using the `gem` instead? I remember earlier that I shouldn't be using the `gem`, and should be using `homebrew`.  I'd love to avoid this issue, but I specifically remember reading I should be using the `homebrew` version.  In `Almalinux`, what should I be using as well?

**Comment by CamJN** [comment]
So there are tradeoffs with each version you can choose. The homebrew version will periodically be mismatched with the nginx as you have now, you can build the formula from source to fix this. The gem version will (by default) pull down pre-built binaries from our servers but must be built for the oldest supported version of macOS, which previously included high-sierra which required us to use some unreliable workarounds for an OS bug, but we no longer support high-sierra so those are gone, you do have to compile the nginx module manually if you use the rubygems version.

As for alma linux, I prefer to use our RPMs on anything RHEL-like, but the rubygems version is fine there if you want to keep things consistent.

**Comment by daBee** [comment]
OK, sounds like scripting a build for `MacOS` is the best way forward.  Cheers

**Comment by daBee** [comment]
Just an FYI, a machine reboot cleared it up.  Nowhere in the docs.
