### ISSUE TITLE
Rake not found while compiling nginx dynamic module

### ISSUE THREAD

**Issue by a7711555** [phusion/passenger#2490]
## Issue report

**Question 1: What is the problem?**
We are compiling the Nginx dynamic module according to the following documents.
- [Installing Passenger as a normal or dynamic Nginx module - Passenger Library](https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#dynamic-module)

When we execute the command below, we encounter the "No Rakefile found" error.
```bash=
sudo ./configure --prefix=/opt/nginx --add-dynamic-module=$(passenger-config --nginx-addon-dir)
```

The error message is
```bash=
configuring additional dynamic modules
adding module in /usr/share/passenger/ngx_http_passenger_module
*** The Phusion Passenger support files are not yet compiled. Compiling them for you... ***
*** Running 'rake  nginx:as_dynamic_module CACHING=false' in /usr/share/passenger/ngx_http_passenger_module... ***
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/share/rubygems-integration/all/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

Is there something we miss or we might have misunderstood?
Thanks a lot!

**Question 2: Passenger version and integration mode**:
- open source 6.0.18 (passenger/focal,now 1:6.0.18-1~focal1)
- Nginx 1.24.0

**Question 3: OS or Linux distro, platform (including version)**:
- Ubuntu 20.04.6 LTS

**Question 4: Passenger installation method**:
- Phusion APT repo

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
**Question 6: Are you using a PaaS and/or containerization? If so which one?**
**Question 7: Anything else about your setup that we should know?**

**Comment by CamJN** [comment]
This looks like your ruby is being managed by something like rvm or asdf or chruby or rbenv, and the relevant environment variables are not being inherited by subprocesses. In the case of bash for example this would be due to not `export`ing those variables. Hope this helps.

**Comment by a7711555** [comment]
> This looks like your ruby is being managed by something like rvm or asdf or chruby or rbenv, and the relevant environment variables are not being inherited by subprocesses. In the case of bash for example this would be due to not `export`ing those variables. Hope this helps.

Thanks to replying.  
Currently, we have tried pull the repo and built with `--add-dynamic-module={base}/passenger/src/nginx_module` and it works!
We will continue to try to figure out why the variables are not exporting.
Thanks a lot!

**Comment by a7711555** [comment]
We found that we just need to install passenger package to our system ruby
and it does find the Rakefile and works fine!

```
gem install passenger -v <version>
```

Thanks a lot~

**Comment by hikaen2** [comment]
same here.

debian's passenger package (https://packages.debian.org/bookworm/amd64/passenger/filelist) does not have the Rakefile that the gem package has, so it cannot build the module.
i think this is a debian bug.

workaround is:

```
apt purge passenger
gem install passenger -v <version>
```

**Comment by CamJN** [comment]
We have not yet released Debian 12 packages, report any such issues to whoever made the package you are installing.
