### ISSUE TITLE
Can't install with Ruby 2.7 on Alma 8 "package passenger-6.0.18-1.el8.x86_64 requires libruby.so.2.5"

### ISSUE THREAD

**Issue by GoodOldJack12** [phusion/passenger#2491]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
- What is the actual behavior?
- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Your answer:
> Expected behavior

Passenger 6.0.18 can be installed with Ruby 2.7 on Alma 8. 
>Actual behavior

It cannot be installed because it wants Ruby 2.5.
```
dnf install passenger 
Last metadata expiration check: 0:16:31 ago on Mon 07 Aug 2023 12:49:53 PM CEST.
Error: 
 Problem: package passenger-6.0.18-1.el8.x86_64 requires libruby.so.2.5()(64bit), but none of the providers can be installed
  - cannot install the best candidate for the job
  - package ruby-libs-2.5.9-110.module_el8.6.0+3074+4b08f9d4.x86_64 is filtered out by modular filtering
```
> Reproduction steps

Install Passenger on Alma 8 with the official passenger repo.

**Question 2: Passenger version and integration mode**:
Your answer:
Open source 6.0.18 apache

**Question 3: OS or Linux distro, platform (including version)**:
Your answer:
AlmaLinux release 8.8

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[x] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer:
Not relevant

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer:
No.

---

I want to stress that this is **not** a configuration issue. This is a packaging issue. 
This issue has been raised on this repo twice before:
* https://github.com/phusion/passenger/issues/2391
  * Response didn't acknowledge the actual problem (packaging issue, not config issue)
* https://github.com/phusion/passenger/issues/2431#issuecomment-1249771931
  * Not acknowledged

**Comment by CamJN** [comment]
`dnf update && dnf install -y ruby && ruby -v` gives `ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]`.

so that is the default ruby, and the one the passenger package relies on being present. you can install additional rubies for use in actually running passenger if you like but that one is an expected dep.

**Comment by GoodOldJack12** [comment]
> that is the default ruby

Unless the ruby 2.7 module is enabled, which I have, to support other applications.

> you can install additional rubies

I cant, in Alma 8, the Ruby 2.5 module and Ruby 2.7 module are mutually exclusive.

> that one is an expected dep

That's what I'm pointing out.  There's no reason for the passenger package to not accept `>=2.5`, since passenger is compatible with ruby 2.7.
