### ISSUE TITLE
Passenger Socket IO - Apache Return Error 101

### ISSUE THREAD

**Issue by DiegoVega19** [phusion/passenger#2493]
I have implemented a socket io server developed in node js / nestjs, which works perfectly on local, but when I configure it with apache and passenger in my QA server it gives me the error 101, any idea what could cause this problem?
Regards! 

This is my .conf file                                                                      

```
Listen 3001
<VirtualHost *:3001>
    ServerName localhost
    PassengerRuby /rubylocation
    PassengerAppRoot /mysocketproject
    PassengerStickySessions on
    PassengerAppType node
    PassengerStartupFile main.js

    <Directory /mysocketproject>
       Options FollowSymLinks
       AllowOverride None
       Order allow,deny
       Allow from all
       Allow from all
       Options -MultiViews
      # Uncomment this if you're on Apache = 2.4:
      Require all granted
  </Directory>  

</VirtualHost>
```

and this is my response from postman

Could not connect to locahost:3001
16:51:49
Error: Unexpected server response: 101

**Comment by CamJN** [comment]
Passenger's Apache integration is not able to proxy websockets on the same port as regular content, you can try and use the [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) module to bypass passenger for the ws requests. This would require your node app to serve ws requests on another port than http requests, see [this](https://www.phusionpassenger.com/docs/advanced_guides/in_depth/node/reverse_port_binding.html) for more details.
