### ISSUE TITLE
Debian 12 (bookworm) support

### ISSUE THREAD

**Issue by darkBuddha** [phusion/passenger#2494]
Hi guys, any idea when Debian 12 (bookworm) will be supported?

It was released 10 weeks ago: https://www.debian.org/News/2023/20230610

Just wanted to ugprade a production Debian 11 (bookworm) server, and the `/etc/apt/sources.list.d/passenger.repo` is the only file that makes trouble after `:%s/bullseye/bookworm/g`.

Thanks!

(2 years ago: #2380)

**Comment by CamJN** [comment]
dup https://github.com/phusion/passenger/issues/2488
