### ISSUE TITLE
Would be great to have a 6.0.19 release!

### ISSUE THREAD

**Issue by ivoanjo** [phusion/passenger#2500]
This is not an issue report per se, so apologies as I'm not following the usual model!

I've noticed that the last release (6.0.18) was back in June.

A few fixes/improvements have accumulated for release, including https://github.com/phusion/passenger/pull/2496, so yeah, it would be great to have a 6.0.19 release soon :)

**Comment by CamJN** [comment]
I agree and am working on it.

**Comment by ivoanjo** [comment]
Yay, awesome news! :)
