### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MarwanTukhta** [phusion/passenger#2519]
## Issue report
Passenger seem to be having a memory leak issue ever since we started using it, we added [jemalloc ](https://github.com/jemalloc/jemalloc) which helped a lot when using puma but didn't have any affect on passenger

**Are you sure this is a bug in Passenger?**
Yes

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

**Question 1: What is the problem?**
Your answer:

- What is the expected behavior?
No memory leak.
- What is the actual behavior?
Memory leak
- How can we reproduce it?
Rails 6 application with the following configs

passenger_detached_process_hook.sh
```
#!/bin/bash


# Get prometheus metrics path
metrics_path="$YABEDA_METRICS_PATH"
if [ -z $metrics_path ]; then
  metrics_path="$PASSENGER_APP_ROOT/prometheus_direct_file_store/"
fi

# Remove metrics files
rm $metrics_path/*___$PASSENGER_PROCESS_PID.bin

if [ $? != 0 ]; then
  echo "Error Deleting Process $PASSENGER_PROCESS_PID Metrics."
fi

#echo '***************'
#echo Process ID is $PASSENGER_PROCESS_PID
#echo Passenger env $PASSENGER_APP_ROOT
#echo '***************'
```
/etc/nginx/sites-enabled/webapp.conf
```
passenger_log_file /dev/stdout;
passenger_pool_idle_time 0;
passenger_disable_log_prefix on;
passenger_max_pool_size 25;

passenger_ctl hook_detached_process ./passenger_detached_process_hook.sh;

server {
    client_max_body_size 10m;
    listen 3000;
    server_name _;
    root /home/app/public;

    passenger_enabled on;

    passenger_user app;

    passenger_min_instances 25;


    passenger_max_requests 30000;

    access_log off;
    error_log /dev/stdout;
}

passenger_pre_start http://localhost:3000/;
```

Your answer:

**Question 2: Passenger version and integration mode**:
- Phusion Passenger(R) 6.0.17 with nginx

Your answer:

**Question 3: OS or Linux distro, platform (including version)**:
- using this image phusion/passenger-customizable:2.5.0

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ * ] Other, please specify:
using phusion/passenger-customizable:2.5.0 docker image

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Your answer:
- Ruby: 2.7.7
- RVM 
- Rails 6.0.6.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
Your answer:
- Docker image phusion/passenger-customizable:2.5.0

**Question 7: Anything else about your setup that we should know?**

Your answer:
we use k8s with pods with these resources
```
cpu: 5250m
memory: 13Gi
```

**Comment by CamJN** [comment]
Can you elaborate on the leak a bit? Do you know what process is leaking?

**Comment by MarwanTukhta** [comment]
> Can you elaborate on the leak a bit? Do you know what process is leaking?

The server process, its memory usage keeps increasing until the process is restarted

**Comment by CamJN** [comment]
This seems to be a leak in your app, not in the Passenger process.
