### ISSUE TITLE
Out of memory leads to passenger shutdown and ensuing 502 error on nginx

### ISSUE THREAD

**Issue by mamsyscheezoo** [phusion/passenger#2525]
The following snippet is from the nginx error logs
![out of memory](https://github.com/phusion/passenger/assets/161585573/77360402-23f7-40e2-83e2-455a78eca2af)

This indicates a memory issue, which caused passenger to shut down. 

We use certificates issued by LetsEncrypt and these certificates are automatically renewed by using a software called Certbot. 
Once the certificates are auto renewed, Certbot would reload nginx automatically at every renewal. This is because nginx does not read the certificate off disk every time, for performance reasons. Our certificate is valid for 3 months, but we renew the certificate every 2 months. Each time the nginx service was reloaded with no down time. This time Certbot attempted to reload the nginx service, but could not do so. Hence causing server downtime.

How can the memory issue be tracked down?

AND are you certain that the nginx failed to reload due to Memory issues?

**Comment by mamsyscheezoo** [comment]
Any updates please?

**Comment by CamJN** [comment]
That message does not come from passenger. Perhaps the perl module is out of memory?

**Comment by mamsyscheezoo** [comment]
How do I check that ? Can you please elaborate more on how can I debug this issue at my end? 
It will be greatly helpful.
