### ISSUE TITLE
Out of memory leads to passenger shutdown and ensuing 502 error on nginx

### ISSUE THREAD

**Issue by mamsyscheezoo** [phusion/passenger#2526]
This is the code snippet from the Nginx logs.

![out of memory](https://github.com/phusion/passenger/assets/161585573/333754ed-fff7-40af-a530-2039dcc2f600)

This indicates a memory issue, which caused passenger to shut down, eventually leading to server downtime.

We use certificates issued by Let's Encrypt, and these certificates are automatically renewed using a software called Certbot. Once the certificates are auto-renewed, Certbot usually reloads nginx automatically. This is because nginx does not read the certificate off disk every time for performance reasons. Our certificates are valid for 3 months, but we renew them every 2 months. Normally, nginx is reloaded without causing downtime. However, in the latest renewal attempt, Certbot was unable to reload the nginx service, resulting in server downtime. We suspect that this was due to "Out of Memory Issue".

How can the memory issue be tracked down? And is it certain that the nginx failed to reload due to Memory issues?
Also if the perl module is out of memory? How can we debug it and track the root cause.

Any detailed help would be great. Please.

**Comment by CamJN** [comment]
Since the issue is not with passenger, this is the wrong place to ask.
