### ISSUE TITLE
Cannot upgrade to 1.24.0-1: unmet dependencies

### ISSUE THREAD

**Issue by aski71** [phusion/passenger#2527]
Hi, 
apt is not upgrading my nginx installation.
Googled a lot but could not find an answer.

System is: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-97-generic x86_64)

`$ sudo apt upgrade nginx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libnginx-mod-http-geoip2 : Depends: nginx-common (= 1.18.0-6ubuntu14.4) but it is not installable
 libnginx-mod-http-image-filter : Depends: nginx-common (= 1.18.0-6ubuntu14.4) but it is not installable
 libnginx-mod-http-xslt-filter : Depends: nginx-common (= 1.18.0-6ubuntu14.4) but it is not installable
 libnginx-mod-mail : Depends: nginx-common (= 1.18.0-6ubuntu14.4) but it is not installable
 libnginx-mod-stream : Depends: nginx-common (= 1.18.0-6ubuntu14.4) but it is not installable
 libnginx-mod-stream-geoip2 : Depends: nginx-common (= 1.18.0-6ubuntu14.4) but it is not installable
E: Broken packages`

What can I do?

Thanks Alex

**Comment by aski71** [comment]
Sorry. Wrong window. Please ignore.

**Comment by CamJN** [comment]
No problem, but i'll recommend you check your nginx apt source, it looks like it says ubuntu 14.04 instead of 22.04.
