### ISSUE TITLE
Unable the fetch the repo for mod_passenger

### ISSUE THREAD

**Issue by xiangge** [phusion/passenger#2543]
Hey team, 
Today I found my docker file can't fetch the repo from the el-passenger.repo.

`curl --fail -sSLo passenger.repo https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo`

I can't open the upon link, do we change to the new location?

**Comment by lpearce-altair** [comment]
Looks like https://oss-binaries.phusionpassenger.com is down will probably need to wait for @CamJN to investigate...

**Comment by CamJN** [comment]
I kicked the server, can someone confirm it's good on your end?

**Comment by gl-dev-avinash** [comment]
@CamJN 

Still getting error, while building docker image

```
# Use the Ruby 3.2.2-bullseye image as a base
FROM ruby:3.2.2-bullseye

# Install our PGP key and add HTTPS support for APT - test
RUN apt-get update -y && apt-get install -y dirmngr \
                                            gnupg \
                                            apt-transport-https \
                                            ca-certificates \
                                            curl \
                                            cron \
                                            logrotate

RUN curl https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt | gpg --dearmor | tee /etc/apt/trusted.gpg.d/phusion.gpg >/dev/null

# Add our APT repository
RUN sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bullseye main > /etc/apt/sources.list.d/passenger.list'
RUN apt-get update

RUN apt-get install -y gettext-base \
    nginx-common=1.18.0-6.1+deb11u3 \
    nginx-extras=1.18.0-6.1+deb11u3

# Install Passenger + Nginx module
RUN apt-get install -y libnginx-mod-http-passenger

```

**Error**
```
14:37:55 Step 7/40 : RUN apt-get install -y libnginx-mod-http-passenger
14:38:00  ---> Running in 1e5d4f24ca94
14:38:00 Reading package lists...
14:38:01 Building dependency tree...
14:38:01 Reading state information...
14:38:01 [91mE: Unable to locate package libnginx-mod-http-passenger
14:38:01 [0mThe command '/bin/sh -c apt-get install -y libnginx-mod-http-passenger' returned a non-zero code: 100
```

**Comment by gl-dev-avinash** [comment]
@CamJN 
https://oss-binaries.phusionpassenger.com/apt/passenger/dists/bullseye/InRelease this is giving **404**

**Comment by gl-dev-avinash** [comment]
@CamJN 
https://oss-binaries.phusionpassenger.com/apt/passenger/dists/bullseye/InRelease -> this url returning **404**

**Comment by CamJN** [comment]
Interesting, that Dockerfile builds fine here. I think the link you posted is always 404, even when the server is working. It uses https://oss-binaries.phusionpassenger.com/apt/passenger/dists/bullseye/Release instead.

**Comment by gl-dev-avinash** [comment]
@CamJN 
Are you able to build image with given Dockerfile?

**Comment by CamJN** [comment]
Yes

**Comment by gl-dev-avinash** [comment]
But we still getting same error: 

```
Unable to locate package libnginx-mod-http-passenger
```

@CamJN any idea what we should do?

**Comment by CamJN** [comment]
I'm looking into it, probably a cache somewhere needs to be cleared.

**Comment by gl-dev-avinash** [comment]
@CamJN 

Bursting the cache with `--no-cache` worked. Thanks for the support!

**Comment by lpearce-altair** [comment]
`sudo curl --fail -sSLo /etc/yum.repos.d/passenger.repo https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo`

works for me now - thanks @CamJN

**Comment by xiangge** [comment]
It's back, thanks.
