### ISSUE TITLE
passenger 6.0.21 will not install on AlmaLinux 9 / RHEL 9

### ISSUE THREAD

**Issue by conathan** [phusion/passenger#2545]
It looks like passenger 6.0.21-1 depends on selinux-policy >= 38.1.35-2.el9_4.0.1.

This is not satisfied on AlmaLinux 9.4, which has 38.1.35-2.el9_4

I was advised on #almalinux irc, this version appears to be what is currently on RockyLinux 9, and may be specific to Rocky.  (who also mentioned RHEL9 is also 38.1.35-2.el9_4)

**Comment by CamJN** [comment]
Yes, Alma isn't a very good approximation of RHEL, that's why we went with rocky to build our images after CentOS stopped being stable.

**Comment by CamJN** [comment]
That's odd, previously rocky was a much better match for RHEL than Alma was, that's why we chose to build our packages there. I'll look at filing a bug report with rocky, they should be on the same version as rhel.

**Comment by CamJN** [comment]
It seems that there's a vulnerability in the package and the version had to be bumped? https://errata.rockylinux.org/RLBA-2024:2402 the matching RHEL errata isn't public yet but I imagine it will be bumped soon too.

**Comment by andrewlukoshko** [comment]
It is public https://access.redhat.com/errata/RHBA-2024:2402.
But with version 38.1.35-2.el9_4.

**Comment by CamJN** [comment]
Strange I had tried to visit that URL when I made my comment and it 404'd.

**Comment by jonathanspw** [comment]
> That's odd, previously rocky was a much better match for RHEL than Alma was, that's why we chose to build our packages there. I'll look at filing a bug report with rocky, they should be on the same version as rhel.

Not sure what you mean here.  We've always had 100% RHEL compatibility at AlmaLinux.

**Comment by CamJN** [comment]
> Not sure what you mean here. We've always had 100% RHEL compatibility at AlmaLinux.

For example, alma used subkeys to sign repos or packages or something early on, which wasn't what RHEL did. That made it not work as a substitute for CentOS when we switched over, because our package building host didn't understand them, and mock failed to setup the package building chroots.

Anyway rocky has fixed the macro, so we'll rebuild our packages and this will be fixed.

**Comment by CamJN** [comment]
I've tested the rebuilt packages in an alma vm and they install fine, will make a release soon.

**Comment by CamJN** [comment]
Release is out.
