### ISSUE TITLE
Unable to Install Passenger

### ISSUE THREAD

**Issue by yebityon** [phusion/passenger#2546]
Hello,

I've noticed that my Dockerfile can't install Passenger since this morning. I think it's a similar issue to #2543.

Has anyone else experienced the same issue?

```sh
❯ curl -I https://oss-binaries.phusionpassenger.com/apt/passenger/dists/bullseye/InRelease
curl: (35) Recv failure: Connection reset by peer
```

**Comment by infrabro** [comment]
`curl https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt | gpg --dearmor | tee /etc/apt/trusted.gpg.d/phusion.gpg >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to oss-binaries.phusionpassenger.com port 443 after 428 ms: Connection refused
gpg: no valid OpenPGP data found.`

I have this error. But yeah it doesnt work for me

**Comment by CamJN** [comment]
I restarted the server

**Comment by yebityon** [comment]
@CamJN 
Thank you. I have confirmed that the issue is resolved, and the installation of Passenger is now successful.

**Comment by infrabro** [comment]
yeah, it's resolved for me. tysm @CamJN

**Comment by bruno** [comment]
@CamJN we seem to be having the same problem again:

```Console
❯ curl -I https://oss-binaries.phusionpassenger.com/apt/passenger/dists/bullseye/InRelease
curl: (7) Failed to connect to oss-binaries.phusionpassenger.com port 443 after 345 ms: Couldn't connect to server
```

**Comment by gracegengau** [comment]
We're having the same "Failed to connect" issue.

**Comment by CamJN** [comment]
I've restarted it again.

**Comment by RafikFarhad** [comment]
@CamJN thanks. Do you have a mirror for this? Also is there any permanent solution for this is planned or taken?
