### ISSUE TITLE
Estimated Release date of Ubuntu 24.04 APT repository?

### ISSUE THREAD

**Issue by copiousfreetime** [phusion/passenger#2550]
## Issue report

**Question 1: What is the problem?**

I was expecting that the APT packages for Ubuntu 24.04 would be available, and currently according to https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/apache/install/ they are not. There is no `noble` repository at https://oss-binaries.phusionpassenger.com/apt/passenger/dists/

**Question 2: Passenger version and integration mode**:

- Attempting to use packaged version of open source 6.0.22

**Question 3: OS or Linux distro, platform (including version)**:

- Ubuntu 24.04

**Question 4: Passenger installation method**:

- [x] Phusion APT repo -- want to use
- [x] source tarball -- ended up using

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

- Ruby 3.3.2, rbenv Rails 7.1.3.3

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

- Deploying on Ubuntu 24.04 AMI in EC2

**Question 7: Anything else about your setup that we should know?**

I did do an initial install of the passenger that ships from Ubuntu (https://answers.launchpad.net/ubuntu/noble/+package/passenger) but it is 6.0.17 and it was messing up the HTTP headers -- which I think was GH-2503 and fixed in [6.0.19](https://github.com/phusion/passenger/releases/tag/release-6.0.19)

You also have my eternal thanks for making such a great product :-).

**Comment by akaspick** [comment]
Appears to be delayed due to bug: https://bugs.launchpad.net/ubuntu/+source/ubuntu-dev-tools/+bug/2058395

**Comment by mackuba** [comment]
I'm tracking this too - looking at the commits list, looks like the issue was resolved, noble is now listed in the changelog in the unreleased section. So probably queued for the next bugfix release?

**Comment by ashrafalzyoud** [comment]
Any update or what expect time to compitable 24.04

**Comment by CamJN** [comment]
We're just finishing up the next release, it should be soon.

**Comment by ashrafalzyoud** [comment]
Any News?!

**Comment by CamJN** [comment]
So we had to update the holy-build-box project in order to continue with the release, that work is done so work on the release has resumed. Sorry for the delay.

**Comment by ardianys** [comment]
watching this issue also

**Comment by akaspick** [comment]
6.0.23 released

https://github.com/phusion/passenger/releases/tag/release-6.0.23

**Comment by mackuba** [comment]
OMG YES

**Comment by ashrafalzyoud** [comment]
I'm not found Ubuntu 24.04 apt here
https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/apache/install/

**Comment by CamJN** [comment]
Yeah, I'm not done releasing the new version. Docs are part of that.

**Comment by CamJN** [comment]
docs are live https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/apache/install/enterprise/noble.html
