### ISSUE TITLE
Downtime https://oss-binaries.phusionpassenger.com

### ISSUE THREAD

**Issue by 23tux** [phusion/passenger#2552]
```
❯ curl https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt
curl: (7) Failed to connect to oss-binaries.phusionpassenger.com port 443 after 46 ms: Couldn't connect to server
```

It seems that the repository is down. Anyone here that can help?

**Comment by CamJN** [comment]
I've restarted it.

**Comment by 23tux** [comment]
It seems to be a regular problem, we encountered the same issue in the past. Is there a way to mirror it somewhere? This way we don't have to wait until someone creates an issue, and then the server is restarted.

**Comment by CamJN** [comment]
It is certainly possible to mirror it, not even difficult. I'm not aware of anyone doing so, though.
