### ISSUE TITLE
apt-get update fails for Jammy due to repository 'Origin' and 'Label' changes

### ISSUE THREAD

**Issue by jcrisp** [phusion/passenger#2560]
Hi, it looks like repository details have changed, causing apt-get update to fail:

E: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger jammy Release' changed its 'Origin' value from '. jammy' to 'Phusion-Passenger'
E: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger jammy Release' changed its 'Label' value from '. jammy' to 'Phusion-Passenger'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

Also config as follows:
cat /etc/apt/sources.list.d/passenger.list
deb [arch=amd64] https://oss-binaries.phusionpassenger.com/apt/passenger jammy main

Can this change in repository details be reverted? Or should it just be accepted explicitly?

Thanks
James

**Comment by CamJN** [comment]
Dup of https://github.com/phusion/passenger/issues/2558

**Comment by FooBarWidget** [comment]
It should be accepted explicitly.
