### ISSUE TITLE
Removed EL7 support broke Amazon Linux 2 in 6.0.23

### ISSUE THREAD

**Issue by toncid** [phusion/passenger#2562]
## Issue report

EL7 support was dropped from 6.0.23, which broke Amazon Linux 2 installations, which is actually supported until 2025-06-30.

**Are you sure this is a bug in Passenger?**

Yes. Well, the cause can be found in the [release notes](https://github.com/phusion/passenger/releases/tag/release-6.0.23):

> [RPMs] Remove EL7 RPMs, CentOS7 is EOL.

Amazon Linux 2 is usually detected as EL7.

**Please try with the newest version of Passenger to avoid issues that have already been fixed**

This is the current version.

**Question 1: What is the problem?**

Nginx cannot be installed on AL2 anymore:

```
# source /etc/rc.local 
According to the PID file '/var/www/app/tmp/pids/passenger.80.pid',
Phusion Passenger(R) Standalone doesn't seem to be running.

If you know that Phusion Passenger(R) Standalone *is* running then one of these
might be the cause of this error:

 * The Phusion Passenger(R) Standalone instance that you want to stop isn't running
   on port 80, but on another port. If this is the case then you
   should specify the right port with --port.
   If the instance is listening on a Unix socket file instead of a TCP port,
   then please specify the PID file's filename with --pid-file.
 * The instance that you want to stop has stored its PID file in a non-standard
   location. In this case please specify the right PID file with --pid-file.
 --> Downloading a Phusion Passenger(R) agent binary for your platform

 --> Installing Nginx 1.26.1 engine
     Sorry, the precompiled Nginx engine can not be run your system.

---------------------------------------

No precompiled Nginx engine could be downloaded. Compiling it from source instead.

Checking for required software...
...
```

As you can see, Nginx needs to be compiled from source, which eventually fails

```
...
-Wl,-E
/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
gmake[1]: *** [objs/nginx] Error 1
gmake[1]: Leaving directory `/tmp/passenger-install.15us776/nginx-1.26.1'
gmake: *** [build] Error 2
```

**Question 2: Passenger version and integration mode**:

Passenger Standalone v6.0.23

**Question 3: OS or Linux distro, platform (including version)**:

Amazon Linux 2 (up to date), x86_64

**Question 4: Passenger installation method**:

[x] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 3.0.6, Yum, Rails 6.1.7.8

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

No.

**Question 7: Anything else about your setup that we should know?**

No.

**Comment by CamJN** [comment]
From a fresh Amazon Linux 2 vm the following steps led to a working Passenger:
```
gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
yum install -y which tar gzip shadow-utils procps-ng pcre2-devel
\curl -sSL https://get.rvm.io | bash
bash -l
rvm install ruby-3.3
rvm use ruby-3.3
gem install passenger
passenger start
```

**Comment by toncid** [comment]
Hello @CamJN, thank you for your reply. Sorry, I wasn't clear. 

I am aware that Nginx can be compiled from source, I managed to get it working with your guidance, but it takes a long time.

I was thinking of (hopefully) switching to an AL2 Nginx RPM, instead of EOLed EL7: http://nginx.org/packages/amzn2/2/SRPMS/

**Comment by CamJN** [comment]
Using the nginx rpm from AL2 would require you to use the method described [here](https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/nginx/install_as_nginx_module.html#dynamic-module) to compile a dynamic nginx module. We do not provide rpms for Amazon Linux, and our EL rpms were never supported on Amazon Linux.

**Comment by toncid** [comment]
> We do not provide rpms for Amazon Linux, and our EL rpms were never supported on Amazon Linux.

Well, there is a regression of some sorts, since Passenger v6.0.22 downloads the precompiled binary and installs it within a second.

On the other hand, Passenger v6.0.23 does a full Nginx compilation that takes ~5 minutes to complete.

Obviously, I don't have a full understanding of how Passenger is installed (I would like to learn more about it) and I am assuming some things, but the regression is there.

**Comment by CamJN** [comment]
Yes, previously, passenger installed from ruby-gems on AM2 downloaded the precompiled generic linux binaries for EL7, which we no longer produce because EL7 is EOL. However this was more of a happy accident than a supported use-case. We don't test on or provide tier-1 support for Amazon Linux which is why we don't provide RPMs for example. 

In order to reduce the setup time you could precompile the binaries once and host them yourself on a server you control then point the passenger gem at them with `passenger-config install-standalone-runtime --url-root $URL`. That command will pull the binaries from the server you indicate instead of ours (you might need to futz with the path a bit, I don't remember the exact path it pulls from but you can check your server's access logs).

**Comment by toncid** [comment]
Thanks for the workaround!
