### ISSUE TITLE
Version Issue Again on MacOS

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2570]
## Issue report

Hi there.  With a recent system update, I've run into yet another version conflict.  This was yesterday and it didn't solve itself overnight.  I was hoping that my previous submissions would raise awareness on this type of version issue, but this seems to prevail.  

Feedback from nginx:

```
nginx: [emerg] module "/opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so" version 1027001 instead of 1027002 in /opt/homebrew/etc/nginx/nginx.conf:4
nginx: configuration file /opt/homebrew/etc/nginx/nginx.conf test failed
```

RF: My Passenger Standalone Info Script
_____ brew info nginx --with-passenger _____

==> nginx: stable 1.27.2 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
Installed
/opt/homebrew/Cellar/nginx/1.27.2 (27 files, 2.5MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-10-16 at 19:32:04
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@3 ✔, pcre2 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g daemon\ off\;
==> Analytics
install: 14,725 (30 days), 42,725 (90 days), 162,934 (365 days)
install-on-request: 14,711 (30 days), 42,664 (90 days), 162,475 (365 days)
build-error: 20 (30 days)

_____ brew info passenger _____

==> passenger: stable 6.0.23 (bottled), HEAD
Server for Ruby, Python, and Node.js apps via Apache/NGINX
https://www.phusionpassenger.com/
Installed
/opt/homebrew/Cellar/passenger/6.0.23_1 (5,110 files, 201.2MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-10-16 at 13:32:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/passenger.rb
License: MIT
==> Dependencies
Build: httpd ✘, nginx ✔
Required: apr ✔, apr-util ✔, openssl@3 ✔, pcre ✔, pcre2 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate Phusion Passenger for Nginx, run:
  brew install nginx
And add the following to /opt/homebrew/etc/nginx/nginx.conf at the top scope (outside http{}):
  load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
And add the following to /opt/homebrew/etc/nginx/nginx.conf in the http scope:
  passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
  passenger_ruby /usr/bin/ruby;

To activate Phusion Passenger for Apache, create /etc/apache2/other/passenger.conf:
  LoadModule passenger_module /opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so
  PassengerRoot /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
  PassengerDefaultRuby /usr/bin/ruby
==> Analytics
install: 75 (30 days), 378 (90 days), 1,931 (365 days)
install-on-request: 73 (30 days), 371 (90 days), 1,889 (365 days)
build-error: 2 (30 days)

Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
##### Homebrew installation passenger_files_comparator.rb #####
Suggested / current / suggested exists?:
load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
Suggested load_module exists: true

passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
Suggested passenger_root exists: true

passenger_ruby /usr/bin/ruby;
passenger_ruby /Users/rich/.rbenv/shims/ruby;                           # passinfo in terminal                    DIFFERENT
Suggested passenger_ruby exists: true

_____ Ruby Info (programming language): _____

/Users/rich/.rbenv/shims/ruby
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
_____ nginx version: _____

nginx version: nginx/1.27.2
_____ OS Version: _____

ProductName:		macOS
ProductVersion:		15.0.1
BuildVersion:		24A348
Software:

    System Software Overview:

      System Version: macOS 15.0.1 (24A348)
      Kernel Version: Darwin 24.0.0
      Boot Volume: Primer
      Boot Mode: Normal
      Computer Name: HQ3
      User Name: Rich (rich)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 8 days, 18 hours, 28 minutes

**Question 4: Passenger installation method**:**
( X ) OS X Homebrew

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
Nothing that I know of at this point.

**Comment by CamJN** [comment]
This isn't something I can do anything about. The homebrew package for passenger needs to be rebuilt against the new nginx version, it should always be rebuilt when nginx is updated, but they often fail to do so. I cannot do anything about that because I am banned from interacting with the homebrew organization on github.

**Comment by daBee** [comment]
OK, I will take it to them.  Cheers
