### ISSUE TITLE
(13)Permission denied: /home/cfc/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#279]
_From [zusocfc](https://code.google.com/u/111251389760572376295/) on December 17, 2008 03:27:30_

My host:
Ubuntu 8.04, Ruby 1.8.7, Apache 2, Rails 2.2.2

After I installed passenger and run 'passenger_install_apache_module' and
setup the apache2.conf and virtual host, I got the error:
(13)Permission denied: /home/cfc/.htaccess pcfg_openfile: unable to check
htaccess file, ensure it is readable

in the error log after I browse my site.

My VirutalHost:
<VirtualHost *:80>
  DocumentRoot "/home/cfc/dinstore_dev/public"
</VirtualHost>

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=178_

**Comment by moorem** [comment]
[Thu Apr 27 13:51:26.549344 2017] [core:crit] [pid 3796] (13)Permission denied: [client 207.46.13.162:2788] AH00529: /home/missingl/public_html/freelist/current/public/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/missingl/public_html/freelist/current/public/' is executable

**Comment by CamJN** [comment]
@moorem check the permissions on the path to the webapp, apache needs execute permissions on every parent directory of the webapp. You should check what user apache is being run as, and ensure they can cd to the webapp and read the htaccess file.
