### ISSUE TITLE
chrooting application

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#307]
_From [cmousefi](https://code.google.com/u/113153607382896147044/) on February 23, 2009 12:14:18_

I would like to run ruby executable under chroot environment? Is there a
possiblity to get a chrooting option for this?

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=207_

**Comment by milo-trujillo** [comment]
Has there been any progress on adding chroot support to Passenger? Since Passenger runs apps as separate processes it effectively bypasses mod_chroot in Apache, and could be quite a security hole.

**Comment by FooBarWidget** [comment]
No, and I doubt chroot support will ever be added to Passenger. It made some sense in the past, but now that we have containerization technologies such as LXC and Docker, chroot is effectively obsolete. Most users don't like to use chroots because managing them is a pain. Docker makes that much easier. On top of that, Docker isolates not only the filesystem but also the network and process namespace.

If we're ever going to implement something like this, it will be on top of Docker, not on chroot. But that raises another question: would that make sense? The way the Docker community advocates its use is that Passenger runs inside the container, not outside, and that containers are only managed through an orchestrator.
