### ISSUE TITLE
Nginx-Passenger should show a more friendly error message upon encountering a permission problem

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#402]
_From [honglilai](https://code.google.com/u/honglilai@gmail.com/) on May 31, 2009 11:14:30_

*What steps will reproduce the problem?*
1. Deploy a Rails app.
2. Make the root directory unreadable/unexecutable by Nginx.

*What is the expected output?*
2009/05/31 11:09:13 [error] 85938#0: *2
"/path/to/application/public/index.html" is forbidden (13: Permission denied)

*What do you see instead?*
A clear explanation as well as a suggestion. Something along the lines of:

  Phusion Passenger could not detect whether /path/to/application is a web
application because the Nginx worker process - which is running as user
xxxx - doesn't have permission to access this directory. Please make grand
read and execution access to user xxxx for the following directories:
  - /path/to/application
  - /path/to
  - /path

If /path/to/application is readable, but e.g. /path/to/application/config
is not, then an appropriate message should be shown.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=302_

**Comment by OnixGH** [comment]
The error is properly reported in Passenger 5:
```
Cannot stat '/home/onix/apps/rails/railsgirls/config.ru': Permission denied (errno=13); 
This error means that the Nginx worker process (PID 21170, running as UID 65534) does not have permission to access this file. 
Please read this page to learn how to fix this problem: https://www.phusionpassenger.com/library/admin/nginx/troubleshooting/?a=upon-accessing-the-web-app-nginx-reports-a-permission-denied-error; 
```
