### ISSUE TITLE
sudo passenger-status fails and subsequently causes 500 errors

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#424]
_From [luke&#37;lukeludwig.com@gtempaccount.com](https://code.google.com/u/112840008667348672836/) on June 23, 2009 16:36:06_

What steps will reproduce the problem? 1. sudo passenger-status What is the expected output? What do you see instead? This command outputs:
**\* Cleaning stale folder /tmp/passenger.2291
ERROR: Phusion Passenger doesn't seem to be running. What version of Phusion Passenger are you using? Which version of Rails? On what operating system? nginx/0.6.35 + Phusion Passenger 2.2.3 (mod_rails/mod_rack)
Rails 2.3.2
Gentoo Base System release 1.12.11.1 Please provide any additional information below. Running 'sudo passenger-status' works sometimes and fails sometimes, so
this problem occurs inconsistently. When it fails it says: "ERROR: Phusion
Passenger doesn't seem to be running." and subsequently causes Nginx to
serve up 500 errors until Nginx is restarted. I have reproduced this many
times.  Also, when this occurs this error shows up in the nginx/error.log file:

2009/06/23 06:49:32 [crit] 2312#0: *58818 connect() to unix:/tmp/
passenger.2291/master/helper_server.sock failed (2: No such file or
directory) while connecting to upstream, client: 75.146.189.233,
server: _, request: "GET /page/show/4280-calendar HTTP/1.1", upstream:
"unix:/tmp/passenger.2291/master/helper_server.sock:", host:
"demo.pucksystems2.com.stage.teamsporttech.com", referrer:
" http://demo.pucksystems2.com.stage.teamsporttech.com/page/show/4279-teams "

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=324_

**Comment by arjunthedragon** [comment]
I am having the same issue
