### ISSUE TITLE
Passenger 2.2.4 doesn't handle requests when using modgeoip2 with GeoIPScanProxyHeaders On

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#448]
_From [swisener](https://code.google.com/u/102549845895782996556/) on July 29, 2009 21:58:14_

What steps will reproduce the problem? 1. Install modgeoip2 1.2.5
2. Use the directive "GeoIPScanProxyHeaders On" in httpd.conf
3. Send an apache request that will hit a passenger instance What is the expected output? What do you see instead? Any request that hits a Passenger instance returns an error 500 and prints this error in the 
Apache error log:

[ pid=1896 file=ext/apache2/Hooks.cpp:693 time=2009-07-28 14:24:19.588 ]:
 Unexpected error in mod_passenger: basic_string::_S_construct NULL not valid
 Backtrace: not available What version of Phusion Passenger are you using? Which version of Rails? On what operating system? Mac OS 10.5.6 or SuSE Linux Enterprise Server 10 
Ruby Enterprise Edition 20090610
Apache 2.2.11
Passenger 2.2.4
Rails 2.2.2 Please provide any additional information below. The error does NOT occur in Passenger 2.2.2. I haven't verified whether or not it occurs in 
Passenger 2.2.3. Other functionality in modgeoip2 seems to work fine, as long as you don't use 
turn on GeoIPScanProxyHeaders.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=348_

**Comment by OnixGH** [comment]
modgeoip2 is now legacy, replaced by [MaxMind](https://github.com/maxmind/mod_maxminddb). Please file a new issue if there are any problems with that and the latest Passenger.
