### ISSUE TITLE
The HTTP client sent incomplete upload data.

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#454]
_From [Calvin.Tin.Chan](https://code.google.com/u/100427203572034042044/) on August 06, 2009 02:14:07_

What steps will reproduce the problem? 1. Uploading file using form multipart What is the expected output? What do you see instead? Backtrace:
     in 'boost::shared_ptrPassenger::BufferedUpload Hooks::receiveRequestBody(request_rec_, 
const char_)' (Hooks.cpp:1012)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:431)

[ pid=124 file=ext/apache2/Hooks.cpp:688 time=2009-08-05 13:36:37.246 ]:
  Unexpected error in mod_passenger: The HTTP client sent incomplete upload data.
  Backtrace:
     in 'boost::shared_ptrPassenger::BufferedUpload Hooks::receiveRequestBody(request_rec_, 
const char_)' (Hooks.cpp:1012)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:431) What version of Phusion Passenger are you using? Which version of Rails? On what operating system? passenger 2.2.4.  Mac OSX and problem only happens in Safari browser (I am using 4.0) Please provide any additional information below. When you click on submit the first time, the page just hang while loading, and nothing is being 
passed to the server.  However, if I click submit again, the file gets uploaded.  Weird....

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=354_

**Comment by danangindrak** [comment]
so what a solution? i cant add new issue on project.
[ 2015-11-12 09:54:22.0189 20005/7fb66373f740 apa/Hooks.cpp:651 ]: Unexpected error in mod_passenger: An error occurred while receiving HTTP upload data: The timeout specified has expired (70007)
  Backtrace:
     in 'void Hooks::sendRequestBody(const Passenger::FileDescriptor&, request_rec*, bool)' (Hooks.cpp:1162)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:533)

[ 2015-11-12 09:54:22.0197 2110/7f0d8035c700 Ser/Server.h:931 ]: [Client 1-164] Disconnecting client with error: error reading request body: Unexpected end-of-stream (errno=-1004)

**Comment by OnixGH** [comment]
If you are running Passenger 2, you need to upgrade to 5.0.21. Otherwise, please post a new issue (others are able to do this, not sure why you wouldn't be able to) and describe more details from your setup, how often the problem is occurring, etc.

**Comment by danangindrak** [comment]
okay OnixGH, thank you very much, now redmine been able to add a new issue.

**Comment by danangindrak** [comment]
hi OnixGH, before i just update passenger 5.0.21 and have same problem. i use redmine bitnami 2.6.7, and now i try to upgrade to passenger 5.0.21. but passenger cannot load mod_passenger.so

Cannot load /opt/redmine/ruby/lib/ruby/gems/2.0.0/gems/passenger-5.0.21/buildout/apache2/mod_passenger.so into server: /opt/redmine/ruby/lib/ruby/gems/2.0.0/      gems/passenger-5.0.21/buildout/apache2/mod_passenger.so: cannot open shared object file: No such file or directory 
apache config test fails, aborting
what because of problems in bitnami redmine? or just passeger not running and need mod_passenger.so ? what a solution ?
thanks before.

**Comment by OnixGH** [comment]
@danangindrak this Github thread is closed and not related to your issue. It sounds like a configuration error, please post your question on the [support forum](https://groups.google.com/forum/#!forum/phusion-passenger).
