### ISSUE TITLE
Proper SELinux support

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#462]
_From [edwin.moss](https://code.google.com/u/118330868891537906705/) on August 23, 2009 06:07:49_

What steps will reproduce the problem? 1. Installed passenger
2. Followed Selinux steps outlined in documentation
3. Still get errors. Errors go away when I disable Selinux but I would prefer not to have to do that.

My experience is similar to: http://blog.aproxacs.com/2009/07/03/passenger-and-se-linux/ If you need more detail let me know and I would be happy to assist.

Thanks,

Ed.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=362_

**Comment by OnixGH** [comment]
This was solved through our [RPM packages](https://blog.phusion.nl/2015/05/20/phusion-passenger-5-0-8-new-debian-packages-red-hat-packages-bug-fixes).
