### ISSUE TITLE
nginx gzip returns text/html and empty page when using page cache

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#492]
_From [pedro.teixeira](https://code.google.com/u/110034020070123735445/) on September 29, 2009 12:19:54_

What steps will reproduce the problem? 1. installed passenger 2.2.5 using instructions found on http://github.com/jnstq/rails-nginx-passenger-ubuntu . Ruby enterprise
edition is 1.8.6-20090610
2. Changed /opt/nginx/conf/nginx.conf, and on the http sections added "gzip
on;"
3. restarted nginx
4. installed simple rails application with page cache
5. for all pages: first page request went fine  => page cache regenerated
6. second page request returned a blank page.
7. Inspected HTTP header and content type was set to text/plain
8. Cleared page cache
9. Page rendered ok => page cache regenerated
10. page rendered ok

Using debian lenny (5)
using rails 2.3.4
Using ruby enterprise edition 1.8.6-20090610
Using passenger 2.2.5

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=392_

**Comment by OnixGH** [comment]
Doesn't seem to occur with Passenger 5.0.24, Nginx 1.8.1, Rails 4.2.4. In production mode I get a gzipped response with the html file from the public folder every time (Accept-Encoding:gzip, deflate, sdch).
