### ISSUE TITLE
Alias directive doesn't work if there isn't "index.html"

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#494]
_From [ibc&#37;aliax.net@gtempaccount.com](https://code.google.com/u/114163732876603645591/) on October 01, 2009 11:32:29_

- What steps will reproduce the problem?

Configure a virtualhost as follows:

  <VirtualHost *:80>
    ServerName mydomain.org
    DocumentRoot /var/www/rails-app/public/

    Alias /html /home/test-html
    Alias /php /home/test-php
  </VirtualHost>

Create a file /home/test-html/index.html and also a file /home/test-

Make sure mod_php is installed and working.

Open the browser in " http://mydomain.org ". The Rails app is open (OK).
Open the browser in " http://mydomain.org/html ". /home/test-html/index.html
is shown (OK).
Open the browser in " http://mydomain.org/php ". 404.html of rails app is
shown (ERROR).

- What is the expected output?

When opening " http://mydomain.org/php " Apache should show /home/test-

- What do you see instead?

The request is handled by mod_rails so it shows "/var/www/rails-

The only dirty workaround is writting all the path in the browser:
  " http://mydomain.org/php/index.php "

- What version of Phusion Passenger are you using?

passenger-2.2.5

- Which version of Rails?

Rails 2.3.4

- On what operating system?

Debian Lenny
apache2                             2.2.9-10+lenny4
apache2-mpm-prefork                 2.2.9-10+lenny4
apache2.2-common                    2.2.9-10+lenny4
libapache2-mod-php5                 5.2.6.dfsg.1-1+lenny3

- Please provide any additional information below.

I've also added in the virtualhost:

  <Directory /home/test-php/>
    AddType application/x-httpd-php .php
    DirectoryIndex index.php
  </Directory>

but it doesn't work at all.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=394_

**Comment by OnixGH** [comment]
Using `PassengerEnabled off` is actually the proper way to configure things when you are also serving other things than your app with Apache/Passenger. Passenger 5 features inheritance, so the setup is fairly simple:
```
<VirtualHost>
  ServerName mydomain.org
  DocumentRoot /var/www/rails-app/public/

  # Turn off by default so PHP etc. will work normally
  PassengerEnabled off
  <Directory /var/www/rails-app/public>
    # Turn on specifically for the app
    PassengerEnabled on
    ...
  </Directory>

  ...other <Directory> / <Location> parts

</<VirtualHost>
```
