### ISSUE TITLE
[APACHE]Upload Timeout error message

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#499]
_From [ryudoawaru](https://code.google.com/u/109963048433278366777/) on October 07, 2009 11:39:38_

What steps will reproduce the problem? I can't reproduce it, but it happens almost every 2-3 minutes. What is the expected output? What do you see instead? [ pid=22379 file=ext/apache2/Hooks.cpp:725 time=2009-10-07 17:21:01.149 ]:
  Unexpected error in mod_passenger: It looks like the browser did not
finish the file upload: it said it will upload 32 bytes, but it closed the
connection after sending 0 bytes. The user probably clicked Stop in the
browser or his Internet connection stalled.
  Backtrace:
     in 'void Hooks::receiveRequestBody(request_rec_, const char_,
std::string&)' (Hooks.cpp:1133)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:457)

[ pid=22379 file=ext/apache2/Hooks.cpp:725 time=2009-10-07 17:21:01.923 ]:
  Unexpected error in mod_passenger: An error occurred while receiving HTTP
upload data: The timeout specified has expired (70007)
  Backtrace:
     in 'void Hooks::receiveRequestBody(request_rec_, const char_,
std::string&)' (Hooks.cpp:1133)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:457) What version of Phusion Passenger are you using? Which version of Rails? On what operating system? Apache 2.2.14 Passenger 2.2.5

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=399_

**Comment by CamJN** [comment]
Please open a new issue and fill out the report form. A reproducible test case is awesome, thanks!
