### ISSUE TITLE
REMOTE_USER is not passed into a Python wsgi program

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#564]
_From [kim@westryn.net](https://code.google.com/u/107709708812107031634/) on February 22, 2010 04:09:59_

What steps will reproduce the problem? 1. Using Passenger 2.2.9 with Nginx 0.8.33 on FreeBSD 7.2 p6 using Ruby 1.9.1p376 and Python 
2.5.5
2. Configure SSL server with basic auth. Relevant parts of the nginx.conf file are:

http {

```
passenger_root /usr/local/lib/ruby/gems/1.9/gems/passenger-2.2.9;
passenger_ruby /usr/local/bin/ruby19;
passenger_default_user wsgi;

server {
    listen       www.xxx.yyy.zzz:443;
server_name  my.server.name;

ssl on;
    ssl_certificate      my.server.name.crt;
    ssl_certificate_key  my.server.name.key;

ssl_session_timeout  5m;

ssl_protocols  SSLv2 SSLv3 TLSv1;
    ssl_ciphers  ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
    ssl_prefer_server_ciphers   on;

    location / {
        root                  /usr/local/www/wsgi_app/public;
        passenger_enabled     on;
        auth_basic            "Restricted Area";
        auth_basic_user_file  htpasswd;
    }
}
```

}
1. Place the following passenger_wsgi.py file in /usr/local/www/wsgi_app

import sys
import os

def application(environ, start_response):
    start_response("200 OK", [])
    ret = ["&#37;s: &#37;s\n" &#37; (key, value)
           for key, value in environ.iteritems()]
    return ret

What is the expected output?

I expect to see key-value pairs, one of which is REMOTE_USER since I have to authenticate to get 
to this app.

What do you see instead?

I see the key-value pairs, but no REMOTE_USER.

I am able to figure out the value of REMOTE_USER by examining the HTTP_AUTHORIZATION value 
in the env variable.  This key has the authentication type, which is "Basic" and a base64 encoded 
string containing the user name and password.  I have made a patch to passenger-
2.2.9/lib/phusion_passenger/wsgi/request_handler.py that checks to see if the HTTP_AUTHORIZATION key is in the env variable, If it is, and if the auth type is "Basic", it extracts 
the user name from the base64 encoded string and adds the REMOTE_USER key with the user 
name as the value.

**Attachment:** [request_handler.py.patch](http://code.google.com/p/phusion-passenger/issues/detail?id=464)

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=464_

**Comment by mateusz-gozdek-sociomantic** [comment]
How to set this variable in Passenger 5? Just `passenger_set_header REMOTE_USER $remote_user`? Will it add `REMOTE_USER` variable into request environment?

**Comment by OnixGH** [comment]
Passenger 5 already sets REMOTE_USER.

**Comment by mateusz-gozdek-sociomantic** [comment]
And how about if I want to pass `$remote_user` from nginx oauth module? Will `passenger_set_header REMOTE_USER $remote_user` work as expected?

**Comment by OnixGH** [comment]
No, you can't use the CGI format with underscores: [documentation](www.phusionpassenger.com/library/config/reference/?a=passenger_set_header).

**Comment by mateusz-gozdek-sociomantic** [comment]
Yeah, my bad. of course I wanted to write `Remote-User`. 
My idea is to validate users using nginx oauth module and then pass `$remote_user` into passenger as `env['REMOTE_USER']`. I can't test it now, but I wanted to know, if using `passenger_set_header Remote-User $remote_user` will set `env['REMOTE_USER']` (preferred) or `env['HTTP_REMOTE_USER']` (as with rest of the headers).

**Comment by FooBarWidget** [comment]
`passenger_set_header Remote-User $remote_user` will result in `env['HTTP_REMOTE_USER']`, as per the HTTP-to-CGI mapping rules.
