### ISSUE TITLE
GET requests with query parametes should bypass the page cache

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#580]
_From [mguterl](https://code.google.com/u/100056476877658796590/) on April 03, 2010 17:03:47_

With thin, mongrel or any other upstream server in nginx I can rewrite
requests with query parameters to the upstream server.

GET / <-- should use public/index.html
GET /?p=46 <-- should hit the rack application 

Passenger always serves index.html even when there are query parameters.

I'm seeing this behavior with a s simple sinatra app with passenger 2.2.11.

Hongli Lai made the following suggestion:

"In the mean time you can work around it by storing page cache files
outside public and use mod_rewrite rules to conditionally redirect to
page cache files."

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=480_

**Comment by OnixGH** [comment]
The original request is a bad idea, query strings can easily be relevant to static pages as mentioned above (asset caching), but also simply for javascript in the page.

If you are using rewriting already anyway, you can just rewrite to the (separate) path of the rack app instead.
