### ISSUE TITLE
Rails apps and Apache SSI , cannot include a rails resource , receive routing error looking for calling template.

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#582]
_From [justin.maccarthy](https://code.google.com/u/103003715851673277500/) on April 05, 2010 10:12:19_

What steps will reproduce the problem? 1. Create a rails app with a static HTML page 
2. Use SSI to include a rails resource 	
3. view the html file 

What is the expected output? 

The results from the rails app 

What do you see instead?

Rails routing error
***
Routing Error

No route matches "/index.html" with {:method=>:get}  
***
where index.html is the static HTML file containing the SSI include statement, not the resource specified in the include..

What version of Phusion Passenger are you using? 2.211
Which version of Rails?  2.3.5
what operating system? OSX  Snow LEopard Please provide any additional information below. I've got a minimal rails  demo application demoing the issue here : http://github.com/macarthy/ssi_test I've also got a rack/ sinatra app with the same functionality that works here: http://github.com/macarthy/hello_sinatra There is a thread on the forum with discussion of the issue : http://groups.google.com/group/phusion-passenger/browse_thread/thread/e3e97af40c7a95af?hl=en Justin

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=482_

**Comment by OnixGH** [comment]
SSI was verified to work with Passenger 5.0.24 and Apache 2.4.7, as per the [documentation](https://httpd.apache.org/docs/2.4/mod/mod_include.html).

* Module `include` enabled.
* Apache configged:
```
AddType text/html .shtml
AddOutputFilter INCLUDES .shtml
Options +Includes
```
* The `#include virtual` of a rails app page works from a test .shtml
