### ISSUE TITLE
allow to parameters to be given to ruby process

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#619]
_From [kmyksvo](https://code.google.com/u/108467149367298200093/) on August 19, 2010 16:29:42_

What steps will reproduce the problem? 1. Debian Squeeze with:
   apache2 (2.2.16-1)
   ruby-1.9.1 (1.9.2~svn28788-1)
   rubygems1.9.1 (1.3.7-1)     
   passenger (2.2.15)
The first three ones are standard Debian packages installed with
'apt-get'. Passenger was installed with 'gem' (using above rubygems
package.

2. Due to a recent update of the ruby-1.9.1 .deb package, the 'gem'
command now fails with:
$ gem list
/usr/lib/ruby/1.9.1/rubygems/source_index.rb:68:in `installed_spec_directories': undefined method `path' for Gem:Module (NoMethodError)
...

The reason is that the new 'ruby' version now contains some 'gem'
functionality, giving some 'hickup' when the 'gem' command is executed.

Running 'gem' this way:

  ruby1.9.1 --disable-gem /usr/bin/gem list

'fixes' the problem from the command line.

The 'passenger' module fails though, as there are no way to specify
parameters to the 'ruby' process from the 'passenger' conf-file. (At
least I have not found a way to do this cleanly yet - found a non-clean
way though.)

Suggests that a new configuration parameter is added that allows one
to give parameters to the ruby process if needed. (I suspect that the
current problem with ruby/gem in Squeeze will go away when updated
packages are distributed, but a configuration parameter like this might
come handy later on. 3. What is the expected output? What do you see instead? See point 2 above. What version of Phusion Passenger are you using? Which version of Rails? On what operating system? See point 1 above. Please provide any additional information below.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=520_

**Comment by OnixGH** [comment]
This was implemented in Passenger 4, you can use `SetEnv` and `PassEnv` (Apache) or `env` (Nginx). See [documentation](https://www.phusionpassenger.com/library/indepth/environment_variables.html).
