### ISSUE TITLE
passenger standalone doesn't serve Rack::URLMap 

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#669]
_From [gotascii](https://code.google.com/u/100886051326284481673/) on October 29, 2010 00:44:02_

**What steps will reproduce the problem?**

~~~
mkdir testapp
cd testapp
mkdir public
~~~

create config.ru with the following contents:

~~~ 
map "/test" do
  app = lambda{|env| [200, {'Content-Type' => 'text/plain'}, ["test!"]]}
  run app
end
~~~

passenger start
browse to: http://0.0.0.0:3000/test

**What is the expected output?**

test!

**What do you see instead?**

Not Found: /test

**What version of Phusion Passenger are you using?**

3.0.0

**On what operating system?**

OSX 10.6.4
Rack version 1.2.1

**Please provide any additional information below.**

This test passes when I use Thin, so I am fairly certain the config.ru is valid. Any idea what is going on here? Thanks!

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=570_

**Comment by OnixGH** [comment]
Going to /test gives the expected output with Passenger 5.0.24.
