### ISSUE TITLE
Passenger keeps and services closed TCP connections

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#815]
_From [peterke](https://code.google.com/u/111224038748838071273/) on November 07, 2011 14:55:48_

What steps will reproduce the problem? 1. Pick a page that takes some time to load (e.g. 200+ms)
2. Refresh the browser many (20+) times, instantly one after the other. What is the expected output? What do you see instead? The initial and maybe couple more requests should get through to the Ruby app (since they pass through without being queued), but most of the middle ones should be dropped out of the passenger queue, since the TCP connections got closed.

Instead, all the connections are happily in the global passenger queue, they all get passed to ruby and serviced, and then all but the last fails with a broken pipe error since the TCP connection was long closed. What version of Phusion Passenger are you using? Which version of Rails? On what operating system? Passenger 3.0.7
OpenSuSE 11.4 Please provide any additional information below. This is rather a vicious cycle since a slower page load causes most of the users to refresh 2-3 times until they chill, which effectively triples the load on the server. After a burst of requests, the server simply wastes huge amounts of time processing long dead requests.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=716_

**Comment by CamJN** [comment]
Closing as a dup of https://github.com/phusion/passenger/issues/1432 which has more discussion.
