### ISSUE TITLE
WSGI handler doesn't work on Python 3

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#916]
_From [hack.augusto](https://code.google.com/u/106352118777189761639/) on December 16, 2012 09:51:55_
1. Install passenger 3.0.17-1 and configure apache
2. Install python 2 and python 3

Instead of the application running got:

The server encountered an internal error and was unable to complete your request. Error message: 
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

And the error log:

File "/usr/lib/passenger/lib/phusion_passenger/wsgi/request_handler.py", line 64
    except Exception, e:
                    ^
SyntaxError: invalid syntax

---

This happens because the file:

passenger/lib/phusion_passenger/wsgi/request_handler.py

has a hashbang that defaults to the latest python (#!/usr/bin/env python), if the machine has both python 2 and python 3 installed the script does not work, change the hashbang to "#!/usr/bin/env python2" should fix the problem.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=817_

**Comment by james1293** [comment]
For future reference: if you want Passenger to use Python3, specify the `python` option in the config.
More details:
[StackOverflow question](https://stackoverflow.com/a/52582232/1630632)
[Standalone](https://www.phusionpassenger.com/library/config/standalone/reference/#--python-python)
