### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#963]
_From [erichsen](https://code.google.com/u/110501215020307184839/) on March 21, 2013 20:55:18_

I run a Rails app on an Ubuntu 12.04 server Passenger 4.0.0 RC 4.

Every few hours Passenger restarts the app and the log file contains error messages related to "Too many open files".

This is the relevant part of the Apache log file from the latest crash:

[ 2013-03-21 20:23:07.0174 14160/7ff03effd700 agents/HelperAgent/RequestHandler.h:1178 ]: Cannot accept client: Too many open files (errno=24). Pausing listening on server socket for 3 seconds.
[ 2013-03-21 20:23:07.0187 14160/7ff04c358700 Pool2/Implementation.cpp:736 ]: Could not spawn process for group /var/www/holdsport/current#default: Cannot get user database entry for username 'nobody'
[ 2013-03-21 20:23:07.0189 14160/7ff03effd700 agents/HelperAgent/RequestHandler.h:1792 ]: [Client 8191] Cannot checkout session (exception type Passenger::RuntimeException): Cannot get user database entry for username 'nobody'
terminate called after throwing an instance of 'Passenger::FileSystemException'
  what():  Cannot open '/home/deploy/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/passenger-enterprise-server-4.0.0.rc4/resources/templates/error_layout.css' for reading: Too many open files (errno=24)
[ pid=14160, timestamp=1363893787 ] Process aborted! signo=SIGABRT(6), reason=SI_TKILL, signal sent by PID 14160 with UID 0, si_addr=0x3750, randomSeed=1363881962
[ pid=14160 ] Could not create crash log file, so dumping to stderr only.
Thu Mar 21 20:23:07 CET 2013
Linux 3.2.0-38-generic #61-Ubuntu SMP Tue Feb 19 12:18:21 UTC 2013 x86_64 x86_64
[ pid=14160 ] Phusion Passenger version: 4.0.0.rc4
[ pid=14160 ] libc backtrace available!
## Could not dump diagnostics: pipe() failed with errno=24

[ pid=14160 ] Dumping a more detailed backtrace with crash-watch...
Crash-watch is not installed. Please install it with 'gem install crash-watch' or download it from https://github.com/FooBarWidget/crash-watch .
[Thu Mar 21 20:23:07 2013] [error] [client 5.9.155.99] Premature end of script headers: media, referer: http://www.holdsport.dk/ [Thu Mar 21 20:23:07 2013] [error] [client 5.9.155.99] Premature end of script headers: activities.ics
[Thu Mar 21 20:23:07 2013] [error] [client 5.9.155.99] Premature end of script headers: v1
[ 2013-03-21 20:23:07.1867 4929/7f88d4350700 agents/Watchdog/Main.cpp:146 ]: Phusion Passenger helper agent (pid=14160) crashed with signal SIGABRT, restarting it...
[ 2013-03-21 20:23:07.2170 5505/7f048f623740 agents/HelperAgent/Main.cpp:537 ]: PassengerHelperAgent online, listening at unix:/tmp/passenger.1.0.4926/generation-0/request.socket
[ 2013-03-21 20:23:07.3387 5505/7f048f4eb700 Pool2/Spawner.h:723 ]: [App 5526 stdout]

And after that the app restarts.

I have upped the open file limit to 4096 but I still get the error.

Any hints to what might be wrong, would be very helpful :-)

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=864_

**Comment by radhika-oss** [comment]
I still see this issue on 6.0.6
